Deltares, Parsen Version 2.08.002.54560 (Win64), Feb 20 2018, 11:17:39

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 5                                       

Warning    : Start date in meteo-file differs from Sobek start date
Object-id  : Bui                                     

Informative Messages:        0
Warnings            :        2
Errors!             :        0

End of program
