substance 'NH4' active
   description        'Ammonium (NH4)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'CBOD5' active
   description        'carbonaceous BOD (first pool) at 5 days'
   concentration-unit '(gO2/m3)'
   waste-load-unit    '-'
end-substance
substance 'CBOD5_2' active
   description        'carbonaceous BOD (second pool) at 5 days'
   concentration-unit '(gO2/m3)'
   waste-load-unit    '-'
end-substance
substance 'OXY' active
   description        'Dissolved Oxygen'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'CBOD5_3' active
   description        'carbonaceous BOD (third pool) at 5 days'
   concentration-unit '(gO2/m3)'
   waste-load-unit    '-'
end-substance
parameter 'KsOxNit'
   description   'half saturation constant for DO cons.'
   unit          '(g/m3)'
   value          2
end-parameter
parameter 'SWVnNit'
   description   'switch for old (0), new (1), TEWOR (2) version'
   unit          '(-)'
   value          2
end-parameter
parameter 'RcNit'
   description   'first-order nitrification rate'
   unit          '(1/d)'
   value          0.5
end-parameter
parameter 'fDfwastNH4'
   description   'diffusive waste flux NH4'
   unit          '(gN/m2/d)'
   value          0
end-parameter
parameter 'fTEWORBOD'
   description   'TEWOR production flux of CBOD5_2'
   unit          '(gO2/m3/d)'
   value          0
end-parameter
parameter 'fTEWORBOD2'
   description   'TEWOR production flux of CBOD5_2'
   unit          '(gO2/m3/d)'
   value          0
end-parameter
parameter 'fTEWORBOD3'
   description   'TEWOR production flux of CBOD5_3'
   unit          '(gO2/m3/d)'
   value          0.74
end-parameter
parameter 'fTEWOROXY'
   description   'TEWOR production flux of OXY'
   unit          '(gO2/m3/d)'
   value          1.14
end-parameter
parameter 'fTEWORNH4'
   description   'TEWOR production flux of NH4'
   unit          '(gN/m3/d)'
   value          0
end-parameter
parameter 'DispConst'
   description   'horizontal dispersion constant'
   unit          '(-)'
   value          1
end-parameter
parameter 'RcBOD'
   description   'decay rate BOD (first pool) at 20 oC'
   unit          '(1/d)'
   value          0.6
end-parameter
parameter 'RcBOD_2'
   description   'decay rate BOD (second pool) at 20 oC'
   unit          '(1/d)'
   value          0.6
end-parameter
parameter 'RCBOD_3'
   description   'decay rate BOD (third pool) at 20 oC'
   unit          '(1/d)'
   value          0.1
end-parameter
parameter 'KMOX'
   description   'half sat const for limit. of BOD oxydation'
   unit          '(gO2/m3)'
   value          1
end-parameter
parameter 'VSedBOD5'
   description   'sedimentation velocity CBOD5'
   unit          '(m/d)'
   value          30
end-parameter
parameter 'VSedBOD5_2'
   description   'sedimentation velocity CBOD5_2'
   unit          '(m/d)'
   value          0.2
end-parameter
parameter 'Salinity'
   description   'Salinity'
   unit          '(g/kg)'
   value          35
end-parameter
parameter 'SWRear'
   description   'switch for oxygen reaeration formulation (1-12)'
   unit          '(-)'
   value          12
end-parameter
parameter 'TCRear'
   description   'temperature coefficient for rearation'
   unit          '(-)'
   value          1.024
end-parameter
parameter 'fcover'
   description   'fraction of water surface covered <0-1>'
   unit          '(-)'
   value          0
end-parameter
parameter 'KLRearMax'
   description   'maximum KLREAR oxygen for temp. correction'
   unit          '(m/d)'
   value          0.5
end-parameter
parameter 'KLRearMin'
   description   'minimum rearation transfer coefficient oxygen'
   unit          '(m/d)'
   value          0.2
end-parameter
parameter 'fSODaut'
   description   'autonomous SOD (no effect SOD stat.var)'
   unit          '(gO2/m2/d)'
   value          1
end-parameter
parameter 'COXSOD'
   description   'critical oxygen concentration for SOD decay'
   unit          '(gO2/m3)'
   value          0
end-parameter
parameter 'OOXSOD'
   description   'optimum oxygen concentration for SOD decay'
   unit          '(gO2/m3)'
   value          10
end-parameter
parameter 'VSedBOD5_3'
   description   'sedimentation velocity CBOD5_3'
   unit          '(m/d)'
   value          0
end-parameter
parameter 'Cl'
   description   'Chloride'
   unit          '(g/m3)'
   value          50
end-parameter
parameter 'Temp'
   description   'ambient water temperature'
   unit          '(oC)'
   value          0.1500E+02
end-parameter
parameter 'VWind'
   description   'wind speed'
   unit          '(m/s)'
   value          0.3000E+01
end-parameter
output 'Depth'
   description   'depth of segment'
end-output
output 'BOD5'
   description   'BOD5'
end-output
output 'BODu'
   description   'calculated carbonaceous BOD at ultimate'
end-output
output 'fSedBOD5'
   description   'sedimentation flux CBOD5'
end-output
output 'fSedBOD5_2'
   description   'sedimentation flux CBOD5_2'
end-output
output 'SaturOXY'
   description   'saturation concentration'
end-output
output 'RCREAR'
   description   'rate constant for reaeration'
end-output
output 'SatPercOXY'
   description   'Actual saturation percentage O2'
end-output
output 'DO'
   description   'dissolved oxygen concentration'
end-output
output 'fSedBOD5_3'
   description   'sedimentation flux CBOD5_3'
end-output
active-processes
   name  'Compos' 'Composition'
   name  'Nitrif_NH4' 'Nitrification of ammonium'
   name  'Dfwast_NH4' 'Diffusive waste NH4'
   name  'Prod_TEWOR' 'Production fluxes for TEWOR+'
   name  'DBOD_TEWOR' 'Oxydation of BOD'
   name  'RearOXY' 'Reaeration of oxygen'
   name  'SedOXYDem' 'Sediment oxygen demand'
   name  'PosOXY' 'Positive oxygen concentration'
   name  'DynDepth' 'dynamic calculation of the depth'
   name  'TotDepth' 'depth water column' 
   name  'SaturOXY' 'Saturation concentration oxygen'
end-active-processes
