substance 'AAP' active
   description        'adsorbed ortho phosphate'
   concentration-unit '(gP/m3)'
   waste-load-unit    '-'
end-substance
substance 'Test1' active
   description        'Test1  (Test1)'
   concentration-unit '(g/L)'
   waste-load-unit    '-'
end-substance
substance 'Test2' active
   description        'Test2  (Test2)'
   concentration-unit '(g/L)'
   waste-load-unit    '-'
end-substance
parameter 'Test1'
   description   'Test1'
   unit          '(-)'
   value          0.3000E+01
end-parameter
parameter 'SWAdsP'
   description   'switch PO4 adsorption <0=Kd|1=Langmuir|2=pHdep>'
   unit          '(-)'
   value          0
end-parameter
parameter 'Test2'
   description   'Test2'
   unit          '(-)'
   value          0.3000E+01
end-parameter
output 'AlgN'
   description   'total nitrogen in algae'
end-output
output 'Test'
   description   'Test <0-1>'
end-output
output 'AlgP'
   description   'total phosphorus in algae'
end-output
active-processes
   name  'Test' 'Test'
   name  'Test' 'Test'
   name  'AdsPO4AAP' 'Ad(De)Sorption ortho phosphorus to inorg. matter'
end-active-processes
