substance 'AAP' active
   description        'adsorbed ortho phosphorus'
   concentration-unit '(gP/m)'
   waste-load-unit    '-'
end-substance
parameter 'SWAdsP'
   description   'switch formulation <0=Kd|1=Langmuir|2=GEM>'
   unit          '(g/L)'
   value          0.1000E+01
end-parameter
output 'LimDLGreen'
   description   'Test'
end-output
active-processes
   name  'AdsPO4AAP' 'Test'
end-active-processes