substance 'TW' active
   description        'Watertemperatuur'
   concentration-unit 'oC'
   waste-load-unit    '-'
end-substance
substance 'Test1' active
   description        'Test substance concentration unit'
   concentration-unit '%'
   waste-load-unit    '-'
end-substance
substance 'Test2' active
   description        'Test substance waste-load unit'
   concentration-unit '-'
   waste-load-unit    '%'
end-substance
parameter 'RFS'
   description   'Reflexie korte golf straling'
   unit          '-'
   value            0.1000000    
end-parameter
parameter 'RFA'
   description   'Reflexie lange golfstraling'
   unit          '-'
   value            0.3000000E-01
end-parameter
parameter 'FS'
   description   'Korte golf straling'
   unit          'W/m2'
   value             0.000000    
end-parameter
parameter 'TA'
   description   'Luchttemperatuur'
   unit          'oC'
   value             20.00000    
end-parameter
parameter 'RV'
   description   'Relatieve vochtigheid'
   unit          '%'
   value             8.000000    
end-parameter
parameter 'Zon'
   description   'Percentage zonneschijnduur'
   unit          '%'
   value             100.0000    
end-parameter
parameter 'W'
   description   'Windsnelheid'
   unit          'm/s'
   value             2.000000    
end-parameter
parameter 'P'
   description   'Luchtdruk'
   unit          'mbar'
   value             1020.000    
end-parameter
output 'Z'
   description   'water depth'
end-output
output 'dt'
   description   'timestep of Duflow-quality calculation in seconds'
end-output
output 'ES'
   description   '1.33*0.75*exp(54.721-(6788.6/(TA+273.15))-5.0016*l'
end-output
output 'EA'
   description   'RV*ES*0.01'
end-output
output 'bw'
   description   '(100-Zon)/100'
end-output
output 'EPSA'
   description   '(0.53+0.067*EA**0.5)*(1+0.17*bw*bw)'
end-output
output 'SIGMA'
   description   '0.0000000567'
end-output
output 'RHO'
   description   '1000'
end-output
output 'Cp'
   description   '4200'
end-output
output 'FSnet'
   description   '(1-RFS)*FS'
end-output
output 'FA'
   description   'epsa*sigma*(TA+273.15)**4'
end-output
output 'FAnet'
   description   '(1-RFA)*FA'
end-output
output 'FW'
   description   '0.97*SIGMA*(TW+273.15)**4'
end-output
output 'K'
   description   '4.4+1.82*W'
end-output
output 'FL'
   description   'K*(ES-EA)'
end-output
output 'FC'
   description   '0.000619*P*(TW-TA)*FL/(ES-EA)'
end-output
output 'FSOM'
   description   'FSnet+FAnet-FW-FL-FC'
end-output
active-processes
   name  'HydDuflow' 'HydDuflow'
   name  'TEMP' 'TEMP'
end-active-processes
