//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaShell.NGHS.IO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeltaShell.NGHS.IO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t close grid nc file.
        /// </summary>
        public static string AGrid_CleanUp_Couldn_t_close_grid_nc_file {
            get {
                return ResourceManager.GetString("AGrid_CleanUp_Couldn_t_close_grid_nc_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get the network ids.
        /// </summary>
        public static string AGrid_Couldn_t_get_the_network_ids {
            get {
                return ResourceManager.GetString("AGrid_Couldn_t_get_the_network_ids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get the number of networks.
        /// </summary>
        public static string AGrid_Couldn_t_get_the_number_of_networks {
            get {
                return ResourceManager.GetString("AGrid_Couldn_t_get_the_number_of_networks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t create new NetCDF file at location .
        /// </summary>
        public static string AGrid_CreateFile_Couldn_t_create_new_NetCDF_file_at_location_ {
            get {
                return ResourceManager.GetString("AGrid_CreateFile_Couldn_t_create_new_NetCDF_file_at_location_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , because the API was not instantiated or Grid not valid Ugrid..
        /// </summary>
        public static string AGrid_GetValidGridApi___because_the_API_was_not_instantiated_or_Grid_not_valid_Ugrid_ {
            get {
                return ResourceManager.GetString("AGrid_GetValidGridApi___because_the_API_was_not_instantiated_or_Grid_not_valid_Ug" +
                        "rid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get coordinate system code because of err nr : .
        /// </summary>
        public static string AGrid_Initialize_Couldn_t_get_coordinate_system_code_because_of_err_nr___ {
            get {
                return ResourceManager.GetString("AGrid_Initialize_Couldn_t_get_coordinate_system_code_because_of_err_nr___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t open grid nc file: .
        /// </summary>
        public static string AGrid_Initialize_Couldn_t_open_grid_nc_file__ {
            get {
                return ResourceManager.GetString("AGrid_Initialize_Couldn_t_open_grid_nc_file__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , because of error number: {0}.
        /// </summary>
        public static string AGrid_ThrowIfError__because_of_error_number___0_ {
            get {
                return ResourceManager.GetString("AGrid_ThrowIfError__because_of_error_number___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read file {0} properly, it doesn&apos;t exist..
        /// </summary>
        public static string Could_not_read_file_0_properly_it_doesnt_exist {
            get {
                return ResourceManager.GetString("Could_not_read_file_0_properly_it_doesnt_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read file {0} properly, it seems empty.
        /// </summary>
        public static string Could_not_read_file_0_properly_it_seems_empty {
            get {
                return ResourceManager.GetString("Could_not_read_file_0_properly_it_seems_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided geometry type &apos;{0}&apos; is not supported..
        /// </summary>
        public static string CulvertDefinitionParser_Unsupported_culvert_geometry_type {
            get {
                return ResourceManager.GetString("CulvertDefinitionParser_Unsupported_culvert_geometry_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        public static string degreeCelcius {
            get {
                return ResourceManager.GetString("degreeCelcius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse {0} to a {1} for property {2} on line {3}..
        /// </summary>
        public static string DelftIniPropertyExtensionMethods_Cannot_parse_value_for_property {
            get {
                return ResourceManager.GetString("DelftIniPropertyExtensionMethods_Cannot_parse_value_for_property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level: {0}. message = {1}.
        /// </summary>
        public static string GridApi_Initialize_Level_0__Message_1_ {
            get {
                return ResourceManager.GetString("GridApi_Initialize_Level_0__Message_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress: {0:P2}. message = {1}.
        /// </summary>
        public static string GridApi_Initialize_Progress_0_Message_1_ {
            get {
                return ResourceManager.GetString("GridApi_Initialize_Progress_0_Message_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; does not contain a value in the file for category &apos;{1}&apos; on line {2}.
        /// </summary>
        public static string IniProperty_EmptyValue {
            get {
                return ResourceManager.GetString("IniProperty_EmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; contains an invalid floating-point number in the file for category &apos;{1}&apos; on line {2}: {3}.
        /// </summary>
        public static string IniProperty_InvalidDouble {
            get {
                return ResourceManager.GetString("IniProperty_InvalidDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is not found in the file for category &apos;{1}&apos; on line {2}.
        /// </summary>
        public static string IniProperty_NotFound {
            get {
                return ResourceManager.GetString("IniProperty_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} could not be found..
        /// </summary>
        public static string NGHSFileBase_File_could_not_be_found {
            get {
                return ResourceManager.GetString("NGHSFileBase_File_could_not_be_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open {0} because the file is locked by another process..
        /// </summary>
        public static string NGHSFileBase_File_is_locked {
            get {
                return ResourceManager.GetString("NGHSFileBase_File_is_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category {0} on line {1} does not contain the {2} property..
        /// </summary>
        public static string NodeFile_The_category_does_not_contain_property {
            get {
                return ResourceManager.GetString("NodeFile_The_category_does_not_contain_property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} contains unsupported value &apos;{1}&apos;: {2} at line number {3} will be skipped..
        /// </summary>
        public static string Property_0_contains_unsupported_value_1_2_at_line_number_3_will_be_skipped {
            get {
                return ResourceManager.GetString("Property_0_contains_unsupported_value_1_2_at_line_number_3_will_be_skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global attribute &quot;Conventions&quot; is missing in file {0}.
        /// </summary>
        public static string RemoteUGridApi_MissingGlobalAttributeConventions {
            get {
                return ResourceManager.GetString("RemoteUGridApi_MissingGlobalAttributeConventions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While reading Deltares netcdf file version type from file {0} we encounter the following problem: {1}.
        /// </summary>
        public static string RemoteUGridApi_ProblemWhileReadingConvention {
            get {
                return ResourceManager.GetString("RemoteUGridApi_ProblemWhileReadingConvention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum required NetCDF convention for this file is {0} but the provided convention is {1}. See global attribute &quot;Conventions&quot; in file {2}.
        /// </summary>
        public static string RemoteUGridApi_RequiredNetCDFVersion {
            get {
                return ResourceManager.GetString("RemoteUGridApi_RequiredNetCDFVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a branch for node with nodeId {0} (retention {1}, line number {2}).
        /// </summary>
        public static string RetentionCategoryParser_TrySetBranchChainage_Could_not_find_a_branch_for_node_with_nodeId__0___retention__1__ {
            get {
                return ResourceManager.GetString("RetentionCategoryParser_TrySetBranchChainage_Could_not_find_a_branch_for_node_wit" +
                        "h_nodeId__0___retention__1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find branch for branch id &quot;{0}&quot; (retention {1}, line number {2}).
        /// </summary>
        public static string RetentionCategoryParser_TrySetBranchChainage_Could_not_find_branch_for_branch_id___0____retention__1__ {
            get {
                return ResourceManager.GetString("RetentionCategoryParser_TrySetBranchChainage_Could_not_find_branch_for_branch_id_" +
                        "__0____retention__1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find node with nodeId {0} (retention {1}, line number {2}).
        /// </summary>
        public static string RetentionCategoryParser_TrySetBranchChainage_Could_not_find_node_with_nodeId__0__for_retention__1_ {
            get {
                return ResourceManager.GetString("RetentionCategoryParser_TrySetBranchChainage_Could_not_find_node_with_nodeId__0__" +
                        "for_retention__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention does not have a valid Branch property.
        /// </summary>
        public static string RetentionFileWriter_GenerateSpatialDataDefinition_Retention_does_not_have_a_valid_Branch_property {
            get {
                return ResourceManager.GetString("RetentionFileWriter_GenerateSpatialDataDefinition_Retention_does_not_have_a_valid" +
                        "_Branch_property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling the table of the Q or H variable failed!.
        /// </summary>
        public static string RoughnessDataFileReader_FillFunctionWithTableData_Filling_the_table_of_the_Q_or_H_function_failed_ {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_FillFunctionWithTableData_Filling_the_table_of_the_Q_or_H" +
                        "_function_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling the table of the Q or H variable failed, values count doesn&apos;t match the defined levels count!.
        /// </summary>
        public static string RoughnessDataFileReader_FillFunctionWithTableData_Filling_the_table_of_the_Q_or_H_function_failed__values_count_doesn_t_match_the_defined_levels_count_ {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_FillFunctionWithTableData_Filling_the_table_of_the_Q_or_H" +
                        "_function_failed__values_count_doesn_t_match_the_defined_levels_count_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read roughness definition data.
        /// </summary>
        public static string RoughnessDataFileReader_ReadDefinitionData_Could_not_read_roughness_definition_data {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadDefinitionData_Could_not_read_roughness_definition_da" +
                        "ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t read roughness section with a variable type of : {0}.
        /// </summary>
        public static string RoughnessDataFileReader_ReadDefinitionData_Couldn_t_read_roughness_section_with_a_function_type_of____0_ {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadDefinitionData_Couldn_t_read_roughness_section_with_a" +
                        "_function_type_of____0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding to network went wrong!.
        /// </summary>
        public static string RoughnessDataFileReader_ReadFile_adding_to_network_went_wrong_ {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadFile_adding_to_network_went_wrong_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read content section {0} properly.
        /// </summary>
        public static string RoughnessDataFileReader_ReadFile_Could_not_read_content_section__0__properly {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadFile_Could_not_read_content_section__0__properly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read file {0} properly, it seems empty.
        /// </summary>
        public static string RoughnessDataFileReader_ReadFile_Could_not_read_file__0__properly__it_seems_empty {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadFile_Could_not_read_file__0__properly__it_seems_empty" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set roughness data in model.
        /// </summary>
        public static string RoughnessDataFileReader_ReadFile_Could_not_set_roughness_data_in_model {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadFile_Could_not_set_roughness_data_in_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While reading roughness section an error occured :{0} {1}.
        /// </summary>
        public static string RoughnessDataFileReader_ReadFile_While_reading_roughness_section_an_error_occured___0___1_ {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadFile_While_reading_roughness_section_an_error_occured" +
                        "___0___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to branch ({0}) where the roughness should be put on is not available in the model.
        /// </summary>
        public static string RoughnessDataFileReader_ReadRoughnessBranchData_branch___0___where_the_roughness_should_be_put_on_is_not_available_in_the_model {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadRoughnessBranchData_branch___0___where_the_roughness_" +
                        "should_be_put_on_is_not_available_in_the_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read roughness branch data.
        /// </summary>
        public static string RoughnessDataFileReader_ReadRoughnessBranchData_Could_not_read_roughness_branch_data {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadRoughnessBranchData_Could_not_read_roughness_branch_d" +
                        "ata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the number of levels ({0}) and the defined number of levels of the branch property {1} are not the same of branch properties : {2}!.
        /// </summary>
        public static string RoughnessDataFileReader_ReadRoughnessBranchData_The_length_of_the_number_of_levels___0___and_the_defined_number_of_levels_of_the_branch_property__1__are_not_the_same_of_branch_properties____2__ {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadRoughnessBranchData_The_length_of_the_number_of_level" +
                        "s___0___and_the_defined_number_of_levels_of_the_branch_property__1__are_not_the_" +
                        "same_of_branch_properties____2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While reading branches for roughness section an error occured :{0} {1}.
        /// </summary>
        public static string RoughnessDataFileReader_ReadRoughnessBranchData_While_reading_branches_for_roughness_section_an_error_occured___0___1_ {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadRoughnessBranchData_While_reading_branches_for_roughn" +
                        "ess_section_an_error_occured___0___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import calibrated roughness section {0} because the calibrated roughness section you want to import doesn&apos;t exist in the model.
        /// </summary>
        public static string RoughnessDataFileReader_ReadRoughnessSection_Could_not_import_calibrated_roughness_section__0__because_the_calibrated_roughness_section_you_want_to_import_doesn_t_exist_in_the_model {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadRoughnessSection_Could_not_import_calibrated_roughnes" +
                        "s_section__0__because_the_calibrated_roughness_section_you_want_to_import_doesn_" +
                        "t_exist_in_the_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When reading reverse roughness section ({0}) the referring (linked) &apos;normal&apos; roughness section ({1}) is not found. The normal section ({1}) should be imported first!.
        /// </summary>
        public static string RoughnessDataFileReader_ReadRoughnessSection_When_reading_reverse_roughness_section___0___the_referring__linked___normal__roughness_section___1___is_not_found__The_normal_section___1___should_be_imported_first_ {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadRoughnessSection_When_reading_reverse_roughness_secti" +
                        "on___0___the_referring__linked___normal__roughness_section___1___is_not_found__T" +
                        "he_normal_section___1___should_be_imported_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While creating the roughnes section from the roughness file the fisrt argument of the roughness network coverage is not created (used to set the interpolation type.
        /// </summary>
        public static string RoughnessDataFileReader_ReadRoughnessSection_While_creating_the_roughnes_section_from_the_roughness_file_the_fisrt_argument_of_the_roughness_network_coverage_is_not_created__used_to_set_the_interpolation_type {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadRoughnessSection_While_creating_the_roughnes_section_" +
                        "from_the_roughness_file_the_fisrt_argument_of_the_roughness_network_coverage_is_" +
                        "not_created__used_to_set_the_interpolation_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While creating the roughnes section from the roughness file the roughness network coverage is not created.
        /// </summary>
        public static string RoughnessDataFileReader_ReadRoughnessSection_While_creating_the_roughnes_section_from_the_roughness_file_the_roughness_network_coverage_is_not_created {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadRoughnessSection_While_creating_the_roughnes_section_" +
                        "from_the_roughness_file_the_roughness_network_coverage_is_not_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No snapped geometry was generated for type {0}..
        /// </summary>
        public static string SnappedFeatureCollection_GetSnappedFeature_No_snapped_geometry_was_generated_for_type__0__ {
            get {
                return ResourceManager.GetString("SnappedFeatureCollection_GetSnappedFeature_No_snapped_geometry_was_generated_for_" +
                        "type__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t parse this type &apos;{0}&apos; to an element of the structure type enum..
        /// </summary>
        public static string StructureDefinitionParser_Could_not_parse_structure_type {
            get {
                return ResourceManager.GetString("StructureDefinitionParser_Could_not_parse_structure_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read structure..
        /// </summary>
        public static string StructureFileReader_Could_not_read_structure {
            get {
                return ResourceManager.GetString("StructureFileReader_Could_not_read_structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While creating structures the following error(s) occured:{0}{1}.
        /// </summary>
        public static string StructureFileReader_Errors_while_creating_structures {
            get {
                return ResourceManager.GetString("StructureFileReader_Errors_while_creating_structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} skipped during import as property &apos;{2}&apos; is not found in the &apos;{3}&apos; file on line {4}..
        /// </summary>
        public static string StructureParserBase_Missing_structure_property {
            get {
                return ResourceManager.GetString("StructureParserBase_Missing_structure_property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No definition parser available for this structure definition: {0}.{1} This structure is not yet supported in the kernel..
        /// </summary>
        public static string StructureParserProvider_No_parser_available {
            get {
                return ResourceManager.GetString("StructureParserProvider_No_parser_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get the node coordinates.
        /// </summary>
        public static string UGrid_GetAllNodeCoordinatesForMeshId_Couldn_t_get_the_node_coordinates {
            get {
                return ResourceManager.GetString("UGrid_GetAllNodeCoordinatesForMeshId_Couldn_t_get_the_node_coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get x node coordinates.
        /// </summary>
        public static string UGrid_GetAllNodeCoordinatesForMeshId_Couldn_t_get_x_node_coordinates {
            get {
                return ResourceManager.GetString("UGrid_GetAllNodeCoordinatesForMeshId_Couldn_t_get_x_node_coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get y node coordinates.
        /// </summary>
        public static string UGrid_GetAllNodeCoordinatesForMeshId_Couldn_t_get_y_node_coordinates {
            get {
                return ResourceManager.GetString("UGrid_GetAllNodeCoordinatesForMeshId_Couldn_t_get_y_node_coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get z node coordinates.
        /// </summary>
        public static string UGrid_GetAllNodeCoordinatesForMeshId_Couldn_t_get_z_node_coordinates {
            get {
                return ResourceManager.GetString("UGrid_GetAllNodeCoordinatesForMeshId_Couldn_t_get_z_node_coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get edge nodes of the mesh.
        /// </summary>
        public static string UGrid_GetEdgeNodesForMeshId_Couldn_t_get_edge_nodes_of_the_mesh {
            get {
                return ResourceManager.GetString("UGrid_GetEdgeNodesForMeshId_Couldn_t_get_edge_nodes_of_the_mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get face nodes of the mesh.
        /// </summary>
        public static string UGrid_GetFaceNodesForMeshId_Couldn_t_get_face_nodes_of_the_mesh {
            get {
                return ResourceManager.GetString("UGrid_GetFaceNodesForMeshId_Couldn_t_get_face_nodes_of_the_mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get meshname.
        /// </summary>
        public static string UGrid_GetMeshName_Couldn_t_get_meshname {
            get {
                return ResourceManager.GetString("UGrid_GetMeshName_Couldn_t_get_meshname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get the names at location.
        /// </summary>
        public static string UGrid_GetNamesAtLocation_Couldn_t_get_the_names_at_location {
            get {
                return ResourceManager.GetString("UGrid_GetNamesAtLocation_Couldn_t_get_the_names_at_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get the number of 2D meshes.
        /// </summary>
        public static string UGrid_GetNumberOf2DMeshes_Couldn_t_get_the_number_of_2D_meshes {
            get {
                return ResourceManager.GetString("UGrid_GetNumberOf2DMeshes_Couldn_t_get_the_number_of_2D_meshes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get number of edges.
        /// </summary>
        public static string UGrid_GetNumberOfEdgesForMeshId_Couldn_t_get_number_of_edges {
            get {
                return ResourceManager.GetString("UGrid_GetNumberOfEdgesForMeshId_Couldn_t_get_number_of_edges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get number of faces.
        /// </summary>
        public static string UGrid_GetNumberOfFacesForMeshId_Couldn_t_get_number_of_faces {
            get {
                return ResourceManager.GetString("UGrid_GetNumberOfFacesForMeshId_Couldn_t_get_number_of_faces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get max face nodes.
        /// </summary>
        public static string UGrid_GetNumberOfMaxFaceNodesForMeshId_Couldn_t_get_max_face_nodes {
            get {
                return ResourceManager.GetString("UGrid_GetNumberOfMaxFaceNodesForMeshId_Couldn_t_get_max_face_nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get the number of nodes.
        /// </summary>
        public static string UGrid_GetNumberOfNodesForMeshId_Couldn_t_get_the_number_of_nodes {
            get {
                return ResourceManager.GetString("UGrid_GetNumberOfNodesForMeshId_Couldn_t_get_the_number_of_nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get the number of names for location type.
        /// </summary>
        public static string UGrid_NumberOfNamesAtLocation_Couldn_t_get_the_number_of_names_for_location_type {
            get {
                return ResourceManager.GetString("UGrid_NumberOfNamesAtLocation_Couldn_t_get_the_number_of_names_for_location_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading z values at mesh faces.
        /// </summary>
        public static string UGrid_ReadZValuesAtFacesForMeshId_Error_reading_z_values_at_mesh_faces {
            get {
                return ResourceManager.GetString("UGrid_ReadZValuesAtFacesForMeshId_Error_reading_z_values_at_mesh_faces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading z values at mesh nodes.
        /// </summary>
        public static string UGrid_ReadZValuesAtNodesForMeshId_Error_reading_z_values_at_mesh_nodes {
            get {
                return ResourceManager.GetString("UGrid_ReadZValuesAtNodesForMeshId_Error_reading_z_values_at_mesh_nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t rewrite grid coordinates.
        /// </summary>
        public static string UGrid_RewriteGridCoordinates_Couldn_t_rewrite_grid_coordinates {
            get {
                return ResourceManager.GetString("UGrid_RewriteGridCoordinates_Couldn_t_rewrite_grid_coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing z values at mesh faces.
        /// </summary>
        public static string UGrid_WriteZValuesAtFacesForMeshId_Error_writing_z_values_at_mesh_faces {
            get {
                return ResourceManager.GetString("UGrid_WriteZValuesAtFacesForMeshId_Error_writing_z_values_at_mesh_faces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z-coordinate of mesh faces.
        /// </summary>
        public static string UGrid_WriteZValuesAtFacesForMeshId_z_coordinate_of_mesh_faces {
            get {
                return ResourceManager.GetString("UGrid_WriteZValuesAtFacesForMeshId_z_coordinate_of_mesh_faces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing z values at mesh nodes.
        /// </summary>
        public static string UGrid_WriteZValuesAtNodesForMeshId_Error_writing_z_values_at_mesh_nodes {
            get {
                return ResourceManager.GetString("UGrid_WriteZValuesAtNodesForMeshId_Error_writing_z_values_at_mesh_nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z-coordinate of mesh nodes.
        /// </summary>
        public static string UGrid_WriteZValuesAtNodesForMeshId_z_coordinate_of_mesh_nodes {
            get {
                return ResourceManager.GetString("UGrid_WriteZValuesAtNodesForMeshId_z_coordinate_of_mesh_nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get the z-coordinate.
        /// </summary>
        public static string UGrid_ZCoordinateFillValue_Couldn_t_get_the_z_coordinate {
            get {
                return ResourceManager.GetString("UGrid_ZCoordinateFillValue_Couldn_t_get_the_z_coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t set the z-coordinate.
        /// </summary>
        public static string UGrid_ZCoordinateFillValue_Couldn_t_set_the_z_coordinate {
            get {
                return ResourceManager.GetString("UGrid_ZCoordinateFillValue_Couldn_t_set_the_z_coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get number of 1D2DLinks from file.
        /// </summary>
        public static string UGrid1D2DLinks_Couldn_t_get_number_of_1D2DLinks {
            get {
                return ResourceManager.GetString("UGrid1D2DLinks_Couldn_t_get_number_of_1D2DLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t create a new link1D2Dmesh with {0} links from mesh1D to mesh2D.
        /// </summary>
        public static string UGrid1D2DLinks_Create1D2DLinksInFile_Couldn_t_create_new_link1D2Dmesh__with_0_links_from_mesh1D_to_mesh2D {
            get {
                return ResourceManager.GetString("UGrid1D2DLinks_Create1D2DLinksInFile_Couldn_t_create_new_link1D2Dmesh__with_0_lin" +
                        "ks_from_mesh1D_to_mesh2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t read links from file.
        /// </summary>
        public static string UGrid1D2DLinks_Read1D2DLinks_Couldn_t_read_links {
            get {
                return ResourceManager.GetString("UGrid1D2DLinks_Read1D2DLinks_Couldn_t_read_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t write 1D2DLinks to file.
        /// </summary>
        public static string UGrid1D2DLinks_Write1D2DLinks_Couldn_t_write_1D2DLinks {
            get {
                return ResourceManager.GetString("UGrid1D2DLinks_Write1D2DLinks_Couldn_t_write_1D2DLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read z-values at this location, CellEdges are not currently supported.
        /// </summary>
        public static string UGridFileHelper_ReadZValues_Unable_to_read_z_values_at_this_location__CellEdges_are_not_currently_supported {
            get {
                return ResourceManager.GetString("UGridFileHelper_ReadZValues_Unable_to_read_z_values_at_this_location__CellEdges_a" +
                        "re_not_currently_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read z-values from file: {0}, file is not UGrid convention.
        /// </summary>
        public static string UGridFileHelper_ReadZValues_Unable_to_read_z_values_from_file___0___file_is_not_UGrid_convention {
            get {
                return ResourceManager.GetString("UGridFileHelper_ReadZValues_Unable_to_read_z_values_from_file___0___file_is_not_U" +
                        "Grid_convention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write z-values at this location, CellEdges are not currently supported.
        /// </summary>
        public static string UGridFileHelper_WriteZValues_Unable_to_write_z_values_at_this_location__CellEdges_are_not_currently_supported {
            get {
                return ResourceManager.GetString("UGridFileHelper_WriteZValues_Unable_to_write_z_values_at_this_location__CellEdges" +
                        "_are_not_currently_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t create new network {0} with number of nodes {1}, number of branches {2}, number of geometry points {3}.
        /// </summary>
        public static string UGridNetwork_CreateNetworkInFile_Couldn_t_create_new_network__0__with_number_of_nodes__1___number_of_branches__2___number_of_geometry_points__3_ {
            get {
                return ResourceManager.GetString("UGridNetwork_CreateNetworkInFile_Couldn_t_create_new_network__0__with_number_of_n" +
                        "odes__1___number_of_branches__2___number_of_geometry_points__3_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t obtain the network name.
        /// </summary>
        public static string UGridNetwork_GetNetworkName_Couldn_t_obtain_the_network_name {
            get {
                return ResourceManager.GetString("UGridNetwork_GetNetworkName_Couldn_t_obtain_the_network_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get the number of network branches.
        /// </summary>
        public static string UGridNetwork_GetNumberOfNetworkBranches_Couldn_t_get_the_number_of_network_branches {
            get {
                return ResourceManager.GetString("UGridNetwork_GetNumberOfNetworkBranches_Couldn_t_get_the_number_of_network_branch" +
                        "es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get the number of network geometry points.
        /// </summary>
        public static string UGridNetwork_GetNumberOfNetworkGeometryPoints_Couldn_t_get_the_number_of_network_geometry_points {
            get {
                return ResourceManager.GetString("UGridNetwork_GetNumberOfNetworkGeometryPoints_Couldn_t_get_the_number_of_network_" +
                        "geometry_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get number of network nodes.
        /// </summary>
        public static string UGridNetwork_GetNumberOfNetworkNodes_Couldn_t_get_number_of_network_nodes {
            get {
                return ResourceManager.GetString("UGridNetwork_GetNumberOfNetworkNodes_Couldn_t_get_number_of_network_nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t read network branches.
        /// </summary>
        public static string UGridNetwork_ReadNetworkBranches_Couldn_t_read_network_branches {
            get {
                return ResourceManager.GetString("UGridNetwork_ReadNetworkBranches_Couldn_t_read_network_branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t read network geometry.
        /// </summary>
        public static string UGridNetwork_ReadNetworkGeometry_Couldn_t_read_network_geometry {
            get {
                return ResourceManager.GetString("UGridNetwork_ReadNetworkGeometry_Couldn_t_read_network_geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t read network nodes.
        /// </summary>
        public static string UGridNetwork_ReadNetworkNodes_Couldn_t_read_network_nodes {
            get {
                return ResourceManager.GetString("UGridNetwork_ReadNetworkNodes_Couldn_t_read_network_nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t write network branches.
        /// </summary>
        public static string UGridNetwork_WriteNetworkBranches_Couldn_t_write_network_branches {
            get {
                return ResourceManager.GetString("UGridNetwork_WriteNetworkBranches_Couldn_t_write_network_branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t write network geometry.
        /// </summary>
        public static string UGridNetwork_WriteNetworkGeometry_Couldn_t_write_network_geometry {
            get {
                return ResourceManager.GetString("UGridNetwork_WriteNetworkGeometry_Couldn_t_write_network_geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t write network nodes.
        /// </summary>
        public static string UGridNetwork_WriteNetworkNodes_Couldn_t_write_network_nodes {
            get {
                return ResourceManager.GetString("UGridNetwork_WriteNetworkNodes_Couldn_t_write_network_nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t create new network in .
        /// </summary>
        public static string UGridNetworkDiscretisation_CreateNetworkDiscretisationInFile_Couldn_t_create_new_network_in_ {
            get {
                return ResourceManager.GetString("UGridNetworkDiscretisation_CreateNetworkDiscretisationInFile_Couldn_t_create_new_" +
                        "network_in_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get the network discretisation IDs.
        /// </summary>
        public static string UGridNetworkDiscretisation_GetNetworkDiscretisationIds_Couldn_t_get_the_network_discretisation_IDs {
            get {
                return ResourceManager.GetString("UGridNetworkDiscretisation_GetNetworkDiscretisationIds_Couldn_t_get_the_network_d" +
                        "iscretisation_IDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get the mesh discretisation name.
        /// </summary>
        public static string UGridNetworkDiscretisation_GetNetworkDiscretisationName_Couldn_t_get_the_mesh_discretisation_name {
            get {
                return ResourceManager.GetString("UGridNetworkDiscretisation_GetNetworkDiscretisationName_Couldn_t_get_the_mesh_dis" +
                        "cretisation_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get the network Id corresponding to the network discretisation.
        /// </summary>
        public static string UGridNetworkDiscretisation_GetNetworkIdForMeshId_Couldn_t_get_the_network_Id_corresponding_to_the_network_discretisation {
            get {
                return ResourceManager.GetString("UGridNetworkDiscretisation_GetNetworkIdForMeshId_Couldn_t_get_the_network_Id_corr" +
                        "esponding_to_the_network_discretisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get the number of network discretisation points.
        /// </summary>
        public static string UGridNetworkDiscretisation_GetNumberOfNetworkDiscretisationPointsForMeshId_Couldn_t_get_the_number_of_network_discretisation_points {
            get {
                return ResourceManager.GetString("UGridNetworkDiscretisation_GetNumberOfNetworkDiscretisationPointsForMeshId_Couldn" +
                        "_t_get_the_number_of_network_discretisation_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get the number of network discretisations.
        /// </summary>
        public static string UGridNetworkDiscretisation_GetNumberOfNetworkDiscretisations_Couldn_t_get_the_number_of_network_discretisations {
            get {
                return ResourceManager.GetString("UGridNetworkDiscretisation_GetNumberOfNetworkDiscretisations_Couldn_t_get_the_num" +
                        "ber_of_network_discretisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t read the network discretisation point ids.
        /// </summary>
        public static string UGridNetworkDiscretisation_ReadNetworkDiscretisationPointIds_Couldn_t_read_discretisation_point_ids {
            get {
                return ResourceManager.GetString("UGridNetworkDiscretisation_ReadNetworkDiscretisationPointIds_Couldn_t_read_discre" +
                        "tisation_point_ids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t read the network discretisation points.
        /// </summary>
        public static string UGridNetworkDiscretisation_ReadNetworkDiscretisationPointsForMeshId_Couldn_t_read_the_network_discretisation_points {
            get {
                return ResourceManager.GetString("UGridNetworkDiscretisation_ReadNetworkDiscretisationPointsForMeshId_Couldn_t_read" +
                        "_the_network_discretisation_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t write the network discretisation point ids.
        /// </summary>
        public static string UGridNetworkDiscretisation_WriteNetworkDiscretisationPointIds_Couldn_t_write_discretisation_point_ids {
            get {
                return ResourceManager.GetString("UGridNetworkDiscretisation_WriteNetworkDiscretisationPointIds_Couldn_t_write_disc" +
                        "retisation_point_ids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t write the network discretisation points.
        /// </summary>
        public static string UGridNetworkDiscretisation_WriteNetworkDiscretisationPoints_Couldn_t_write_the_network_discretisation_points {
            get {
                return ResourceManager.GetString("UGridNetworkDiscretisation_WriteNetworkDiscretisationPoints_Couldn_t_write_the_ne" +
                        "twork_discretisation_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error disposing grid operation api: {0}.
        /// </summary>
        public static string WaterFlowFMModel_DisposeSnapApi_Error_disposing_grid_operation_api___0_ {
            get {
                return ResourceManager.GetString("WaterFlowFMModel_DisposeSnapApi_Error_disposing_grid_operation_api___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel failed to perform operation: {0}.
        /// </summary>
        public static string WaterFlowFMModel_GetGridSnapApi_Kernel_failed_to_perform_operation___0_ {
            get {
                return ResourceManager.GetString("WaterFlowFMModel_GetGridSnapApi_Kernel_failed_to_perform_operation___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last attempt to perform snapping operation failed, please verify the model first..
        /// </summary>
        public static string WaterFlowFMModel_GetGridSnapApi_Last_attempt_to_perform_snapping_operation_failed__please_verify_the_model_first_ {
            get {
                return ResourceManager.GetString("WaterFlowFMModel_GetGridSnapApi_Last_attempt_to_perform_snapping_operation_failed" +
                        "__please_verify_the_model_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when reading grid after 1d2d initialisation step in the D-FLow FM kernel: {0}.
        /// </summary>
        public static string WaterFlowFMModel_ReadGridFromNetFile_Error_when_reading_grid_after_1d2d_initialisation_step_in_the_D_FLow_FM_kernel___0_ {
            get {
                return ResourceManager.GetString("WaterFlowFMModel_ReadGridFromNetFile_Error_when_reading_grid_after_1d2d_initialis" +
                        "ation_step_in_the_D_FLow_FM_kernel___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reapplying existing spatial operations to new BedLevel Data.
        /// </summary>
        public static string WaterFlowFMModel_UpdateBathymetryCoverage_Reapplying_existing_spatial_operations_to_new_BedLevel_Data {
            get {
                return ResourceManager.GetString("WaterFlowFMModel_UpdateBathymetryCoverage_Reapplying_existing_spatial_operations_" +
                        "to_new_BedLevel_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BedLevel location specified does not match the existing BedLevel data, a new BedLevel Data will be generated..
        /// </summary>
        public static string WaterFlowFMModel_UpdateBathymetryCoverage_The_BedLevel_location_specified_does_not_match_the_existing_BedLevel_data__a_new_BedLevel_Data_will_be_generated_ {
            get {
                return ResourceManager.GetString("WaterFlowFMModel_UpdateBathymetryCoverage_The_BedLevel_location_specified_does_no" +
                        "t_match_the_existing_BedLevel_data__a_new_BedLevel_Data_will_be_generated_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstructured grid edge coverages are not currently supported.
        /// </summary>
        public static string WaterFlowFMModel_UpdateBathymetryCoverage_Unstructured_grid_edge_coverages_are_not_currently_supported {
            get {
                return ResourceManager.GetString("WaterFlowFMModel_UpdateBathymetryCoverage_Unstructured_grid_edge_coverages_are_no" +
                        "t_currently_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse horizontal_opening_direction of type &apos;{0}&apos;.
        /// </summary>
        public static string WeirFormulaParser_Could_not_parse_horizontal_gate_opening {
            get {
                return ResourceManager.GetString("WeirFormulaParser_Could_not_parse_horizontal_gate_opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided weir formula type &apos;{0}&apos; is unknown..
        /// </summary>
        public static string WeirFormulaParser_Unknow_formula_type {
            get {
                return ResourceManager.GetString("WeirFormulaParser_Unknow_formula_type", resourceCulture);
            }
        }
    }
}
