Sobek Parser V2.06.014.27565

Warning    : Structure at calculation point: grid point skipped
Object-id  : PompaAir_PasarIkan                      

Warning    : Structure at calculation point: grid point skipped
Object-id  : PintuMuaraKarang                        

Warning    : Structure at calculation point: grid point skipped
Object-id  : ITEM2                                   

Warning    : Structure at calculation point: grid point skipped
Object-id  : Sogo_gate                               

Warning    : Structure at calculation point: grid point skipped
Object-id  : SodetanGrogolGate                       

Warning    : Structure at calculation point: grid point skipped
Object-id  : Katulampa                               

Warning    : Structure at calculation point: grid point skipped
Object-id  : Katulampa11                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : Katulampa10                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : Katulampa9                              

Warning    : Structure at calculation point: grid point skipped
Object-id  : Katulampa2                              

Warning    : Structure at calculation point: grid point skipped
Object-id  : Katulampa3                              

Warning    : Structure at calculation point: grid point skipped
Object-id  : Katulampa8                              

Warning    : Structure at calculation point: grid point skipped
Object-id  : Katulampa4                              

Warning    : Structure at calculation point: grid point skipped
Object-id  : Katulampa7                              

Warning    : Structure at calculation point: grid point skipped
Object-id  : Katulampa6                              

Warning    : Structure at calculation point: grid point skipped
Object-id  : Katulampa5                              

Warning    : Structure at calculation point: grid point skipped
Object-id  : 21                                      

Warning    : Structure at calculation point: grid point skipped
Object-id  : EBC_Gate_III                            

Warning    : Structure at calculation point: grid point skipped
Object-id  : EBC_Gate_IV                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : EBC_Gate_II                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : EBC_Gate_I                              

Warning    : Structure at calculation point: grid point skipped
Object-id  : Marina_4                                

Warning    : Structure at calculation point: grid point skipped
Object-id  : PKPR_TG_top                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : Marina_5                                

Warning    : Structure at calculation point: grid point skipped
Object-id  : Marina_2                                

Warning    : Structure at calculation point: grid point skipped
Object-id  : Marina_1                                

Warning    : Structure at calculation point: grid point skipped
Object-id  : Marina_3                                

Warning    : Structure at calculation point: grid point skipped
Object-id  : CDG_02                                  

Warning    : Structure at calculation point: grid point skipped
Object-id  : Pluit_timur                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : Pluit_barat                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : BKT_WEIR_CIP                            

Warning    : Structure at calculation point: grid point skipped
Object-id  : BKT_Gate1_2                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : BKT_Gate1_3                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : BKT_Gate1_4                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : BKT_Gate1_1                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : BKT_Gate2_5                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : BKT_Gate2_2                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : BKT_Gate2_1                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : BKT_Gate2_4                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : BKT_Gate2_3                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : BKT_Gate3_4                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : BKT_Gate3_2                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : BKT_Gate3_5                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : BKT_Gate3_1                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : BKT_Gate3_3                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : BKT_weirs3                              

Warning    : Structure at calculation point: grid point skipped
Object-id  : BKT_weirs2                              

Warning    : Structure at calculation point: grid point skipped
Object-id  : BKT_weirs1                              

Warning    : Structure at calculation point: grid point skipped
Object-id  : Mang_Gate1                              

Warning    : Structure at calculation point: grid point skipped
Object-id  : Mang_Gate3                              

Warning    : Structure at calculation point: grid point skipped
Object-id  : KRT_gate5                               

Warning    : Structure at calculation point: grid point skipped
Object-id  : KRT_gate3                               

Warning    : Structure at calculation point: grid point skipped
Object-id  : PETUKANGAN_GATE                         

Warning    : Structure at calculation point: grid point skipped
Object-id  : Jembatan_Merah                          

Warning    : Structure at calculation point: grid point skipped
Object-id  : TANGKI_GATE                             

Warning    : Structure at calculation point: grid point skipped
Object-id  : 158                                     

Warning    : Structure at calculation point: grid point skipped
Object-id  : 166                                     

Warning    : Structure at calculation point: grid point skipped
Object-id  : KRT_gate2                               

Warning    : Structure at calculation point: grid point skipped
Object-id  : KRT_gate4                               

Warning    : Structure at calculation point: grid point skipped
Object-id  : PompaDudi                               

Warning    : Structure at calculation point: grid point skipped
Object-id  : CAKG_02                                 

Warning    : Structure at calculation point: grid point skipped
Object-id  : CAKG_03                                 

Warning    : Structure at calculation point: grid point skipped
Object-id  : ISTIQLAL_3                              

Warning    : Structure at calculation point: grid point skipped
Object-id  : ISTIQLAL_1                              

Warning    : Structure at calculation point: grid point skipped
Object-id  : ISTIQLAL_2                              

Warning    : Structure at calculation point: grid point skipped
Object-id  : PompaJelembar2                          

Warning    : Structure at calculation point: grid point skipped
Object-id  : PompaJelembar3                          

Warning    : Structure at calculation point: grid point skipped
Object-id  : PompaJelembarTimur                      

Warning    : Structure at calculation point: grid point skipped
Object-id  : KA_2-KamalPump                          

Warning    : Structure at calculation point: grid point skipped
Object-id  : KA_70                                   

Warning    : Structure at calculation point: grid point skipped
Object-id  : KA_71                                   

Warning    : Structure at calculation point: grid point skipped
Object-id  : KA_TanjunganGate                        

Warning    : Structure at calculation point: grid point skipped
Object-id  : KA_10-KamalGate                         

Warning    : Structure at calculation point: grid point skipped
Object-id  : cid_UpCid_Cdg_18                        

Warning    : Structure at calculation point: grid point skipped
Object-id  : cid_UpCid_Cdg_17                        

Warning    : Structure at calculation point: grid point skipped
Object-id  : cid_UpCid_Cdg_25                        

Warning    : Structure at calculation point: grid point skipped
Object-id  : cid_UpCid_Cdg_26                        

Warning    : Structure at calculation point: grid point skipped
Object-id  : cid_UpCid_Cdg_27                        

Warning    : Structure at calculation point: grid point skipped
Object-id  : cid_UpCid_Cdg_33                        

Warning    : Structure at calculation point: grid point skipped
Object-id  : cid_UpCid_Cdg_35                        

Warning    : Structure at calculation point: grid point skipped
Object-id  : cid_UpCid_Cdg_34                        

Warning    : Structure at calculation point: grid point skipped
Object-id  : cid_UpCid_Cdg_36                        

Warning    : Structure at calculation point: grid point skipped
Object-id  : cid_UpCid_Cdg_42                        

Warning    : Structure at calculation point: grid point skipped
Object-id  : cid_UpCid_Cdg_41                        

Warning    : Structure at calculation point: grid point skipped
Object-id  : cid_UpCid_Cdg_44                        

Warning    : Structure at calculation point: grid point skipped
Object-id  : cid_UpCid_Cdg_43                        

Warning    : Structure at calculation point: grid point skipped
Object-id  : BlencongGate                            

Warning    : Structure at calculation point: grid point skipped
Object-id  : SUNTER_SELATAN_GATE                     

Informative Messages:        0
Warnings            :       88
Errors!             :        0

End of program
