using System.IO;
using System.Linq;
using BasicModelInterface;
using DelftTools.Utils.Collections;
using DelftTools.Utils.IO;
using DeltaShell.NGHS.IO;
using DeltaShell.Plugins.FMSuite.FlowFM.ModelDefinition;

namespace DeltaShell.Plugins.FMSuite.FlowFM
{
    public partial class WaterFlowFMModel
    {
        private string progressText;
        private double previousProgress;

        public override string ProgressText => string.IsNullOrEmpty(progressText) ? base.ProgressText : progressText;

        public override IBasicModelInterface BMIEngine => DimrRunner.Api;

        protected override void OnInitialize()
        {
            previousProgress = 0;
            CacheTimes();
            DataItems.RemoveAllWhere(di => di.Tag == WaterFlowFMModelDataSet.DiaFileDataItemTag);
            boundaryConditionDataList = BoundaryConditions1D.ToList();

            ReportProgressText("Initializing");
            SetOutputDirProperty();
            SetWaqOutputDirProperty();
            if (Directory.Exists(WorkingOutputDirectoryPath))
            {
                DisconnectOutput();
                FileUtils.DeleteIfExists(WorkingOutputDirectoryPath);
                FileUtils.CreateDirectoryIfNotExists(WorkingOutputDirectoryPath);
            }

            DimrRunner.OnInitialize();
            
            ReportProgressText();
        }
        
        protected override void OnCleanup()
        {
            if (boundaryConditionDataList != null)
                foreach (var bc in boundaryConditionDataList)
                {
                    var data = bc.Data;
                    if (data != null)
                    {
                        data.SkipArgumentValidationInEvaluate = false;
                    }
                }

            boundaryConditionDataList = null;

            snapApiInErrorMode = false;
            base.OnCleanup();
            DimrRunner.OnCleanup();
            
            ReportProgressText();
            previousProgress = 0;
            CleanCacheTimes();
        }
        
        protected override void OnExecute()
        {
            DimrRunner.OnExecute();
        }

        protected override void OnFinish()
        {
            DimrRunner.OnFinish();
            currentOutputDirectoryPath = WorkingOutputDirectoryPath;

            // We know the cache file will either exist at the runMduPath because it 
            // was copied here, or it will be generated by the kernel during the run.
            string runMduPath = Path.Combine(WorkingDirectory, DirectoryName, InputFile);

            CacheFile.UpdatePathToMduLocation(runMduPath);
        }
        
        protected override void OnProgressChanged()
        {
            // Only update gui for every 1 percent progress (performance)
            double percentage = ProgressPercentage;

            if (percentage - previousProgress < 0.01) return;

            previousProgress = percentage;
            DimrRunner.OnProgressChanged();
            base.OnProgressChanged();
        }
        
        private void ReportProgressText(string text = null)
        {
            progressText = text;
            base.OnProgressChanged();
        }
        
        private void SetOutputDirProperty()
        {
            WaterFlowFMProperty outputDirProperty = ModelDefinition.GetModelProperty(KnownProperties.OutDir);

            string existingOutputDir = outputDirProperty.GetValueAsString();
            if (!existingOutputDir.StartsWith(DirectoryNameConstants.OutputDirectoryName))
            {
                outputDirProperty.SetValueFromString(DirectoryNameConstants.OutputDirectoryName);
                Log.InfoFormat("Running this model requires the OutputDirectory to be overwritten to: {0}",
                               DirectoryNameConstants.OutputDirectoryName);
            }
        }
        
        private void ClearWaqOutputDirProperty()
        {
            ModelDefinition.GetModelProperty(KnownProperties.WaqOutputDir).SetValueFromString(string.Empty);
        }
        
        private void SetWaqOutputDirProperty()
        {
            if (!SpecifyWaqOutputInterval)
            {
                return;
            }

            string delwaqDirectoryName = FileConstants.PrefixDelwaqDirectoryName + Name;
            string delwaqOutputDirectoryName = Path.Combine(DirectoryNameConstants.OutputDirectoryName, delwaqDirectoryName);
            
            ModelDefinition.GetModelProperty(KnownProperties.WaqOutputDir).SetValueFromString(delwaqOutputDirectoryName);
        }
    }
}