CP_1.0
BRCH id 'R_1' cp 1 ct bc 
TBLE
125 90 <
tble brch

BRCH id 'R_2' cp 1 ct bc 
TBLE
125 90 <
tble brch

BRCH id 'R_3' cp 1 ct bc 
TBLE
125 90 <
tble brch

BRCH id 'R_4' cp 1 ct bc 
TBLE
125 90 <
tble brch

BRCH id 'R_5' cp 1 ct bc 
TBLE
125 90 <
tble brch

BRCH id 'R_6' cp 1 ct bc 
TBLE
125 90 <
tble brch

BRCH id 'R_7' cp 1 ct bc 
TBLE
125 90 <
tble brch

BRCH id 'R_8' cp 1 ct bc 
TBLE
125 90 <
tble brch

