

ITEM
USEFOR 'Lateral inflow' 'Lateral inflow'
ABSOLUTE TIME
CONCENTRATION
USEFOR 'AAP' 'AAP'
USEFOR 'DetC' 'DetC'
USEFOR 'DetN' 'DetN'
USEFOR 'DetP' 'DetP'
USEFOR 'GREEN' 'GREEN'
USEFOR 'NH4' 'NH4'
USEFOR 'NO3' 'NO3'
USEFOR 'PO4' 'PO4'
USEFOR 'OXY' 'OXY'
USEFOR 'Cl' 'Cl'
USEFOR 'IM1' 'IM1'
DATA                         'AAP'         'DetC'        'DetN'        'DetP'        'GREEN'       'NH4'         'NO3'         'PO4'         'OXY'         'Cl'          'IM1' 
'1997/01/01-12:00:00'       333.1         -999          -999          -999          -999          -999          -999          -999          -999          -999          -999 
'1997/02/01-12:00:00'       333.2         -999          -999          -999          -999          -999          -999          -999          -999          -999          -999 

ITEM
USEFOR 'Boundary Flow' 'Boundary Flow'
CONCENTRATION
USEFOR 'AAP' 'AAP'
USEFOR 'DetC' 'DetC'
USEFOR 'DetN' 'DetN'
USEFOR 'DetP' 'DetP'
USEFOR 'GREEN' 'GREEN'
USEFOR 'NH4' 'NH4'
USEFOR 'NO3' 'NO3'
USEFOR 'PO4' 'PO4'
USEFOR 'OXY' 'OXY'
USEFOR 'Cl' 'Cl'
USEFOR 'IM1' 'IM1'
DATA           'AAP'         'DetC'        'DetN'        'DetP'        'GREEN'       'NH4'         'NO3'         'PO4'         'OXY'         'Cl'          'IM1' 
              444           -999          -999          -999          -999          -999          -999          -999          -999          -999          -999 


ITEM
USEFOR 'MyOwnLittleFraction' 'MyOwnLittleFraction'
CONCENTRATION
USEFOR 'AAP' 'AAP'
USEFOR 'DetC' 'DetC'
USEFOR 'DetN' 'DetN'
USEFOR 'DetP' 'DetP'
USEFOR 'GREEN' 'GREEN'
USEFOR 'NH4' 'NH4'
USEFOR 'NO3' 'NO3'
USEFOR 'PO4' 'PO4'
USEFOR 'OXY' 'OXY'
USEFOR 'Cl' 'Cl'
USEFOR 'IM1' 'IM1'
DATA           'AAP'         'DetC'        'DetN'        'DetP'        'GREEN'       'NH4'         'NO3'         'PO4'         'OXY'         'Cl'          'IM1' 
              456           -999          -999          -999          -999          -999          -999          -999          -999          -999          -999 

