Sobek Parser V2.04.80
file_glb_glb =                                                                                 
file_top_net = \SOBEK212\DRRSA.LIT\WORK\NETWORK.TP                                             
file_top_cpt = \SOBEK212\DRRSA.LIT\WORK\NETWORK.CP                                             
file_top_nfl =                                                                                 
file_top_nsa =                                                                                 
file_top_nsm =                                                                                 
file_top_dat = \SOBEK212\DRRSA.LIT\WORK\NODES.DAT                                              
file_top_xyc = \SOBEK212\DRRSA.LIT\WORK\NETWORK.D12                                            
file_crs_net = \SOBEK212\DRRSA.LIT\WORK\NETWORK.CR                                             
file_crs_def = \SOBEK212\DRRSA.LIT\WORK\PROFILE.DEF                                            
file_crs_dat = \SOBEK212\DRRSA.LIT\WORK\PROFILE.DAT                                            
file_str_net = \SOBEK212\DRRSA.LIT\WORK\NETWORK.ST                                             
file_str_def = \SOBEK212\DRRSA.LIT\WORK\STRUCT.DEF                                             
file_str_dbs = \SOBEK212\DRRSA.LIT\WORK\STRUCT.DEF                                             
file_str_dat = \SOBEK212\DRRSA.LIT\WORK\STRUCT.DAT                                             
file_str_con = \SOBEK212\DRRSA.LIT\WORK\CONTROL.DEF                                            
file_str_trg = \SOBEK212\DRRSA.LIT\WORK\TRIGGER.DEF                                            
file_str_ssa =                                                                                 
file_str_cmp = \SOBEK212\DRRSA.LIT\WORK\STRUCT.CMP                                             
file_str_csa =                                                                                 
file_str_vlv = \SOBEK212\DRRSA.LIT\WORK\VALVE.TAB                                              
file_str_mud =                                                                                 
file_str_mum =                                                                                 
file_frc_bed = \SOBEK212\DRRSA.LIT\WORK\FRICTION.DAT                                           
file_frc_wnd = \SOBEK212\DRRSA.LIT\WORK\FRICTION.DAT                                           
file_frc_exr =                                                                                 
file_frc_glf = \SOBEK212\DRRSA.LIT\WORK\FRICTION.DAT                                           
file_cnd_net = \SOBEK212\DRRSA.LIT\WORK\NETWORK.CN                                             
file_cnd_flb = \SOBEK212\DRRSA.LIT\WORK\BOUNDARY.DAT                                           
file_cnd_fll = \SOBEK212\DRRSA.LIT\WORK\LATERAL.DAT                                            
file_cnd_fbd = \SOBEK212\DRRSA.LIT\WORK\BOUNDLAT.DAT                                           
file_cnd_wqb =                                                                                 
file_cnd_wql =                                                                                 
file_cnd_sab =                                                                                 
file_cnd_sal = \SOBEK212\DRRSA.LIT\WORK\CONCSALT.DAT                                           
file_cnd_mob =                                                                                 
file_cnd_mon =                                                                                 
file_cnd_mol =                                                                                 
file_ini_igl = \SOBEK212\DRRSA.LIT\WORK\INITIAL.DAT                                            
file_ini_ifl = \SOBEK212\DRRSA.LIT\WORK\INITIAL.DAT                                            
file_ini_iwq =                                                                                 
file_ini_isa = \SOBEK212\DRRSA.LIT\WORK\INITSALT.DAT                                           
file_ini_imo =                                                                                 
file_met_wnd = \SOBEK212\FIXED\T25_MD.WDC                                                      
file_met_wnd = \SOBEK212\FIXED\T25_MD.WDC                                                      
file_met_bui = \SOBEK212\FIXED\T25_MD.BUI                                                      
file_met_sun =                                                                                 
file_met_wat =                                                                                 
file_met_air =                                                                                 
file_dsp_gld =                                                                                 
file_dsp_lod =                                                                                 
file_dsp_fwt =                                                                                 
file_dsp_mou =                                                                                 
file_dsp_brm =                                                                                 
file_grd_net = \SOBEK212\DRRSA.LIT\WORK\NETWORK.GR                                             
file_grd_seg =                                                                                 
file_grd_lim =                                                                                 
file_rtm_flt = ..\work\runtime.dat                                                             
file_rtm_fln = ..\work\runtime.dat                                                             
file_rtm_flm = ..\work\runtime.dat                                                             
file_rtm_flh = ..\work\runtime.dat                                                             
file_rtm_san =                                                                                 
file_rtm_sam =                                                                                 
file_rtm_sah =                                                                                 
file_rtm_sen =                                                                                 
file_rtm_sem =                                                                                 
file_rtm_seh =                                                                                 
file_rtm_mon =                                                                                 
file_rtm_mom =                                                                                 
file_rtm_moh =                                                                                 
file_rtm_wqt =                                                                                 
file_rtm_wqn =                                                                                 
file_rtm_wqm =                                                                                 
file_rtm_wqh =                                                                                 
file_rtm_pwq =                                                                                 
file_rtm_gwn =                                                                                 
file_trp_dat =                                                                                 
file_sub_sub =                                                                                 
file_gwm_gwm =                                                                                 
file_mea_net = \SOBEK212\DRRSA.LIT\WORK\NETWORK.ME                                             
Channel Flow/Urban/River version
SRW option switched off
ConveyanceAccuracyFactor= 0.015
CalculationPointMinDistDwn1=  0.50
CalculationPointMinDistUp 1=  0.50
CalculationPointMinDistDwn2=  0.50
CalculationPointMinDistUp 2=  0.50
CalculationPointMinDistDwn3=  0.50
CalculationPointMinDistUp 3=  0.50
CalculationPointMinDistDwn4=  0.50
CalculationPointMinDistUp 4=  0.50
CompoundObjectDistance= 10.00
No range check
Existance check
Original Profile Interpolation
 max_increase_width_with_h_subs=    99999.00    
 max_increase_width_with_h_nosubs=    99999.00    
 max_change_deltax_with_x =    99999.00    
 max_change_totwidth_with_x =    99999.00    
 max_change_flowwidth_with_x =    99999.00    
 dx_structure =    1.000000    
 dx_min =    1.000000    
Conveyance tables created
Output for total of sections only
 applications: <RIVR><FLOW> 

Computation of Conveyance tables

End of program
