using System.IO;
using BasicModelInterface;
using DelftTools.Shell.Core.Workflow;
using DelftTools.Utils.Collections;
using DelftTools.Utils.IO;
using DeltaShell.NGHS.IO;
using DeltaShell.Plugins.FMSuite.Common.IO;
using DeltaShell.Plugins.FMSuite.FlowFM.ModelDefinition;
using DeltaShell.Plugins.FMSuite.FlowFM.Properties;

namespace DeltaShell.Plugins.FMSuite.FlowFM.Model
{
    public partial class WaterFlowFMModel
    {
        #region Overrides of TimeDependentModelBase

        private double previousProgress = 0;
        private string progressText;

        public override string ProgressText => string.IsNullOrEmpty(progressText) ? base.ProgressText : progressText;
        public override IBasicModelInterface BMIEngine => runner.Api;

        protected override void OnReset()
        {
            base.OnReset();
            ReportProgressText(); // Reset the progress text
        }

        protected override void OnInitialize()
        {
            previousProgress = 0;
            DataItems.RemoveAllWhere(di => di.Tag == DiaFileDataItemTag);

            ReportProgressText("Initializing");

            // Force fm kernel to write output to 'output' Directory
            SetOutputDirProperty();
            SetWaqOutputDirProperty();

            if (Directory.Exists(WorkingOutputDirectoryPath))
            {
                DisconnectOutput();
                FileUtils.DeleteIfExists(WorkingOutputDirectoryPath);
                FileUtils.CreateDirectoryIfNotExists(WorkingOutputDirectoryPath);
            }

            runner.OnInitialize();

            ReportProgressText();
        }

        protected override void OnCleanup()
        {
            snapApiInErrorMode = false;
            base.OnCleanup();
            runner.OnCleanup();

            ReportProgressText();
        }

        protected override void OnExecute()
        {
            runner.OnExecute();
        }

        protected override void OnFinish()
        {
            runner.OnFinish();
            currentOutputDirectoryPath = WorkingOutputDirectoryPath;

            // We know the cache file will either exist at the runMduPath because it 
            // was copied here, or it will be generated by the kernel during the run.
            string runMduPath = Path.Combine(WorkingDirectoryPath,
                                             "dflowfm",
                                             $"{Name}{FileConstants.MduFileExtension}");

            CacheFile.UpdatePathToMduLocation(runMduPath);
            LogWarningWriteRestartModelRun();
        }

        protected override void OnProgressChanged()
        {
            // Only update gui for every 1 percent progress (performance)
            if (ProgressPercentage - previousProgress < 0.01)
            {
                return;
            }

            previousProgress = ProgressPercentage;
            runner.OnProgressChanged();
            base.OnProgressChanged();
        }

        private void ReportProgressText(string text = null)
        {
            progressText = text;
            base.OnProgressChanged();
        }

        private void LogWarningWriteRestartModelRun()
        {
            if (WriteRestart)
            {
                Log.Warn(Resources.WaterFlowFMModel_Save_project_after_model_run_with_write_restart);
            }
        }

        #endregion

        #region Implementation of IDimrModel

        public virtual bool CanRunParallel => true;

        public new virtual ActivityStatus Status
        {
            get => base.Status;
            set => base.Status = value;
        }

        public virtual bool RunsInIntegratedModel { get; set; }

        #endregion

        #region Output

        private void SetOutputDirProperty()
        {
            WaterFlowFMProperty outputDirProperty = ModelDefinition.GetModelProperty(KnownProperties.OutputDir);

            string existingOutputDir = outputDirProperty.GetValueAsString();
            if (!existingOutputDir.StartsWith(DirectoryNameConstants.OutputDirectoryName))
            {
                outputDirProperty.SetValueAsString(DirectoryNameConstants.OutputDirectoryName);
                Log.InfoFormat(Resources.WaterFlowFMModel_Running_this_model_requires_the_OutputDirectory_to_be_overwritten_to___0_,
                               DirectoryNameConstants.OutputDirectoryName);
            }
        }

        private void SetWaqOutputDirProperty()
        {
            if (!SpecifyWaqOutputInterval)
            {
                return;
            }

            string relativeDWaqOutputDirectory = Path.Combine(DirectoryNameConstants.OutputDirectoryName, DelwaqOutputDirectoryName);
            WaterFlowFMProperty waqOutputDirProperty = ModelDefinition.GetModelProperty(KnownProperties.WaqOutputDir);
            waqOutputDirProperty.SetValueAsString(relativeDWaqOutputDirectory);
        }

        private void ClearWaqOutputDirProperty()
        {
            ModelDefinition.GetModelProperty(KnownProperties.WaqOutputDir).SetValueAsString(string.Empty);
        }

        #endregion Output
    }
}