

ITEM
USEFOR 'Boundary Flow' 'Boundary Flow'
CONCENTRATION
USEFOR 'NH4' 'NH4'
USEFOR 'CBOD5' 'CBOD5'
USEFOR 'CBOD5_2' 'CBOD5_2'
USEFOR 'OXY' 'OXY'
USEFOR 'Continuity' 'Continuity'
DATA           'NH4'         'CBOD5'       'CBOD5_2'     'OXY'         'Continuity' 
              1             0             1             5.5           1 

ITEM
USEFOR 'Lateral inflow' 'Lateral inflow'
CONCENTRATION
USEFOR 'NH4' 'NH4'
USEFOR 'CBOD5' 'CBOD5'
USEFOR 'CBOD5_2' 'CBOD5_2'
USEFOR 'OXY' 'OXY'
USEFOR 'Continuity' 'Continuity'
DATA           'NH4'         'CBOD5'       'CBOD5_2'     'OXY'         'Continuity' 
              5.5           60            40            6.5             1 

