//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaShell.Plugins.FMSuite.Wave.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeltaShell.Plugins.FMSuite.Wave.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap wave {
            get {
                object obj = ResourceManager.GetObject("wave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the grids Coordinate System should be the same, either Spherical or Cardesian.
        /// </summary>
        public static string WaveDomainValidator_ValidateAllDomainsShareCoordinateSystem_All_the_grids_Coordinate_System_should_be_the_same__either_Spherical_or_Cardesian {
            get {
                return ResourceManager.GetString("WaveDomainValidator_ValidateAllDomainsShareCoordinateSystem_All_the_grids_Coordin" +
                        "ate_System_should_be_the_same__either_Spherical_or_Cardesian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaveSetup should be false when using Spherical Coordinate Systems..
        /// </summary>
        public static string WaveDomainValidator_ValidateAllDomainsShareCoordinateSystem_WaveSetup_should_be_false_when_using_Spherical_Coordinate_Systems_ {
            get {
                return ResourceManager.GetString("WaveDomainValidator_ValidateAllDomainsShareCoordinateSystem_WaveSetup_should_be_f" +
                        "alse_when_using_Spherical_Coordinate_Systems_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With WaveSetup set to True parallel runs will fail, normal runs with lakes will produce unreliable values..
        /// </summary>
        public static string WaveModel_WaveSetup_With_WaveSetup_set_to_True_parallel_runs_will_fail__normal_runs_with_lakes_will_produce_unreliable_values_ {
            get {
                return ResourceManager.GetString("WaveModel_WaveSetup_With_WaveSetup_set_to_True_parallel_runs_will_fail__normal_ru" +
                        "ns_with_lakes_will_produce_unreliable_values_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waves Model Properties.
        /// </summary>
        public static string WavePropertiesValidator_Validate_Waves_Model_Properties {
            get {
                return ResourceManager.GetString("WavePropertiesValidator_Validate_Waves_Model_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain: {0}.
        /// </summary>
        public static string WavePropertiesValidator_ValidateWindSpeedAndQuadruple_Domain___0_ {
            get {
                return ResourceManager.GetString("WavePropertiesValidator_ValidateWindSpeedAndQuadruple_Domain___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindSpeed is zero whereas quadruple is true..
        /// </summary>
        public static string WavePropertiesValidator_ValidateWindSpeedAndQuadruple_WindSpeed_is_zero_whereas_quadruple_is_true_ {
            get {
                return ResourceManager.GetString("WavePropertiesValidator_ValidateWindSpeedAndQuadruple_WindSpeed_is_zero_whereas_q" +
                        "uadruple_is_true_", resourceCulture);
            }
        }
    }
}
