using DelftTools.Shell.Core.Workflow.DataItems;
using DelftTools.Units;
using DelftTools.Utils.Collections.Generic;
using DeltaShell.Plugins.DelftModels.RainfallRunoff.FileWriter;

namespace DeltaShell.Plugins.DelftModels.RainfallRunoff
{
    public class EngineParameters
    {
        private static Unit GetCubicMeterUnit()
        {
            return new Unit("cubic meter", "m³");
        }

        private static Unit GetCubicMeterPerSecondUnit()
        {
            return new Unit("cubic meter per second", "m³/s");
        }
        private static Unit GetMilliMeterPerHourUnit()
        {
            return new Unit("millimeter per hour", "mm/hr");
        }

        private static Unit GetMillimeterUnit()
        {
            return new Unit("millimeter", "mm");
        }

        private static Unit GetMeterUnit()
        {
            return new Unit("meter", "m");
        }

        private static Unit GetDegreeCelsiusUnit()
        {
            return new Unit("degree celsius", "°C");
        }

        /// <summary>
        /// Returns the parameters the 'SobekRR' engine supports. 
        /// If the unit is dimensionless, both name and symbol are set to ""
        /// </summary>
        /// <returns></returns>
        public static IEventedList<EngineParameter> EngineMapping()
        {
            return new EventedList<EngineParameter>
                {
                    // paved
                    new EngineParameter(QuantityType.StorageRWA_mm, ElementSet.PavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.PavedStorageRWA, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.StorageDWA_mm, ElementSet.PavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.PavedStorageDWA, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.StorageStreet_mm, ElementSet.PavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.PavedStorageStreet, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.SpillingTotal, ElementSet.PavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.PavedSpillingTotal,
                                        GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.SpillingRWA, ElementSet.PavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.PavedSpillingRWA, GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.SpillingDWA, ElementSet.PavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.PavedSpillingDWA, GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.PumpedTotal, ElementSet.PavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.PavedPumpedTotal, GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.PumpedRWA, ElementSet.PavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.PavedPumpedRWA, GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.PumpedDWA, ElementSet.PavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.PavedPumpedDWA, GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.DWA2RWA, ElementSet.PavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.PavedDWAToRWA, GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.DWA2DWA, ElementSet.PavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.PavedDWAToDWA, GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.RWA2DWA, ElementSet.PavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.PavedRWAToDWA, GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.SurfaceRWA, ElementSet.PavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.PavedSurface_RWA, GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.EvaporationSurface, ElementSet.PavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.PavedEvapSurface, GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.StorageVolDyn, ElementSet.PavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.PavedVolDynStorage, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.Rainfall, ElementSet.PavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.PavedRainfall, GetCubicMeterPerSecondUnit()),

                    // unpaved

                    new EngineParameter(QuantityType.SurfRunoff, ElementSet.UnpavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.UnpavedSurfaceRunoff,
                                        GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.GwOutflow, ElementSet.UnpavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.UnpavedGwOutflow, GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.Rainfall, ElementSet.UnpavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.UnpavedRainfall, GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.EvaporationSurface, ElementSet.UnpavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.UnpavedEvaporationSurface,
                                        GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.Infiltration, ElementSet.UnpavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.UnpavedInfiltration,
                                        GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.Seepage, ElementSet.UnpavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.UnpavedSeepage, GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.EvaporationActual, ElementSet.UnpavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.UnpavedEvaporationActual,
                                        GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.EvaporationPotential, ElementSet.UnpavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.UnpavedEvaporationPotential,
                                        GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.Percolation, ElementSet.UnpavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.UnpavedPercolation,
                                        GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.CapillaryRise, ElementSet.UnpavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.UnpavedCapillaryRise,
                                        GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.GroundwaterLevel, ElementSet.UnpavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.UnpavedGroundwaterLevel, GetMeterUnit()),
                    new EngineParameter(QuantityType.Storage_mm, ElementSet.UnpavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.UnpavedStorageLandmm, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.GroundwaterVolume, ElementSet.UnpavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.UnpavedGroundwaterVolume, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.Storage_m3, ElementSet.UnpavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.UnpavedStorageLandm3, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.GroundwaterLevelThreshold, ElementSet.UnpavedElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.UnpavedGroundwaterLevelThreshold,
                                        new Unit("hour", "hour")),
                    new EngineParameter(QuantityType.GroundwaterLevelSurface, ElementSet.UnpavedElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.UnpavedGroundwaterLevelSurface, GetMeterUnit()),
                    new EngineParameter(QuantityType.StorageCoeff, ElementSet.UnpavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.UnpavedStorageCoeff,
                                        new Unit("Storage coefficient", "--")),
                    new EngineParameter(QuantityType.UnsatZoneContent, ElementSet.UnpavedElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.UnpavedUnsaturatedZone, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.UnsaturatedZoneVolume, ElementSet.UnpavedElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.UnpavedUnsaturatedZoneVolume,
                                        GetCubicMeterUnit()),


                    // greenhouse
                    new EngineParameter(QuantityType.Storage_m3, ElementSet.GreenhouseElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.GreenhouseStorageBasins, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.Flow, ElementSet.GreenhouseElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.GreenhouseFlowBasins,
                                        GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.Rainfall, ElementSet.GreenhouseElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.GreenhouseRainfall,
                                        GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.EvaporationSurface, ElementSet.GreenhouseElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.GreenhouseEvaporation,
                                        GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.WaterUse, ElementSet.GreenhouseElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.GreenhouseWaterUse,
                                        GetCubicMeterPerSecondUnit()),


                    //OpenWater
                    new EngineParameter(QuantityType.Rainfall, ElementSet.OpenWaterElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.OpenWaterRainfall,
                                        GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.EvaporationSurface, ElementSet.OpenWaterElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.OpenWaterEvaporation,
                                        GetCubicMeterPerSecondUnit()),

                    //Sacramento
                    new EngineParameter(QuantityType.SacrUZTWC, ElementSet.SacramentoElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.SacramentoUpperZoneTensionWaterCapacity,
                                        GetMillimeterUnit()),
                    new EngineParameter(QuantityType.SacrUZFWC, ElementSet.SacramentoElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.SacramentoUpperZoneFreeWaterCapacity,
                                        GetMillimeterUnit()),
                    new EngineParameter(QuantityType.SacrLZTWC, ElementSet.SacramentoElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.SacramentoLowerZoneTensionWaterCapacity,
                                        GetMillimeterUnit()),
                    new EngineParameter(QuantityType.SacrLZFSC, ElementSet.SacramentoElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames
                                            .SacramentoLowerZoneFreeSupplementalWaterCapacity,
                                        GetMillimeterUnit()),
                    new EngineParameter(QuantityType.SacrLZFPC, ElementSet.SacramentoElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.SacramentoLowerZoneFreePrimaryWaterCapacity,
                                        GetMillimeterUnit()),
                    new EngineParameter(QuantityType.SacrPrecip, ElementSet.SacramentoElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.SacramentoRainfall, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.SacrPotEvap, ElementSet.SacramentoElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.SacramentoPotEvap, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.SacrActEvap, ElementSet.SacramentoElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.SacramentoActEvap, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.SacrBaseFlow, ElementSet.SacramentoElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.SacramentoBaseFlow, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.SacrSurfFlow, ElementSet.SacramentoElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.SacramentoSurfaceFlow, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.SacrRunoffImpArea, ElementSet.SacramentoElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.SacramentoRunoffImpArea, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.SacrTotalRunoff, ElementSet.SacramentoElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.SacramentoTotalRunoff, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.SacrChannelInflow, ElementSet.SacramentoElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.SacramentoChannelInflow,
                                        GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.SacrSideSubSurfaceOutflow, ElementSet.SacramentoElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.SacramentoSideSubsurfaceOutflow,
                                        GetMillimeterUnit()),
                    new EngineParameter(QuantityType.SacrAddImpAreaContent, ElementSet.SacramentoElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.SacramentoAdditionalImpAreaContent,
                                        GetMillimeterUnit()),

                    //hbv
                    new EngineParameter(QuantityType.RunoffOutflow, ElementSet.HbvElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.HbvOutflow, GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.RunoffRainfall, ElementSet.HbvElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.HbvRainfall, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.RunoffSnowfall, ElementSet.HbvElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.HbvSnowfall, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.RunoffPotEvap, ElementSet.HbvElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.HbvPotEvap, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.RunoffActEvap, ElementSet.HbvElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.HbvActEvap, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.RunoffBaseflow, ElementSet.HbvElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.HbvBaseflow, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.RunoffInterflow, ElementSet.HbvElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.HbvInterflow, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.RunoffQuickflow, ElementSet.HbvElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.HbvQuickflow, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.RunoffDrySnowContent, ElementSet.HbvElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.HbvDrySnowContent, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.RunoffFreeWaterContent, ElementSet.HbvElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.HbvFreeWaterContent, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.RunoffSoilMoisture, ElementSet.HbvElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.HbvSoilMoisture, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.RunoffUpperZoneContent, ElementSet.HbvElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.HbvUpperZoneContent, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.RunoffLowerZoneContent, ElementSet.HbvElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.HbvLowerZoneContent, GetMillimeterUnit()),
                    new EngineParameter(QuantityType.RunoffTemperature, ElementSet.HbvElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.HbvTemperature, GetDegreeCelsiusUnit()),

                    //wwtp
                    new EngineParameter(QuantityType.FlowIn, ElementSet.WWTPElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.WWTPInFlow, GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.Flow, ElementSet.WWTPElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.WWTPOutFlow, GetCubicMeterPerSecondUnit()),



                    // balance per node
                    new EngineParameter(QuantityType.TotalInNonLinks_m3, ElementSet.BalanceNodeElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NodeBalanceFlowInNonLinks, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.TotalInViaLinks_m3, ElementSet.BalanceNodeElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NodeBalanceFlowInViaLinks, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.TotalOutNonLinks_m3, ElementSet.BalanceNodeElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NodeBalanceFlowOutNonLinks,
                                        GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.TotalOutViaLinks_m3, ElementSet.BalanceNodeElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NodeBalanceFlowOutViaLinks,
                                        GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.DeltaStorage_m3, ElementSet.BalanceNodeElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NodeBalanceDeltaStorage, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.BalanceError_m3, ElementSet.BalanceNodeElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NodeBalanceBalanceError, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.CumInNonLinks_m3, ElementSet.BalanceNodeElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NodeBalanceCumFlowInNonLinks,
                                        GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.CumInViaLinks_m3, ElementSet.BalanceNodeElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NodeBalanceCumFlowInViaLinks,
                                        GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.CumOutNonLinks_m3, ElementSet.BalanceNodeElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NodeBalanceCumFlowOutNonLinks,
                                        GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.CumOutViaLinks_m3, ElementSet.BalanceNodeElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NodeBalanceCumFlowOutViaLinks,
                                        GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.CumDeltaStorage_m3, ElementSet.BalanceNodeElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NodeBalanceCumDeltaStorage,
                                        GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.CumBalanceError_m3, ElementSet.BalanceNodeElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NodeBalanceCumBalanceError,
                                        GetCubicMeterUnit()),

                    // balance model
                    new EngineParameter(QuantityType.Rainfall, ElementSet.BalanceModelElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.ModelBalanceRainfall,
                                        GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.EvaporationPaved, ElementSet.BalanceModelElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.ModelBalanceEvaporationPaved,
                                        GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.EvaporationUnpaved, ElementSet.BalanceModelElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.ModelBalanceEvaporationUnpaved,
                                        GetCubicMeterPerSecondUnit()),
                    new EngineParameter(QuantityType.WaterUse, ElementSet.BalanceModelElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.ModelBalanceUseGreenhouses,
                                        GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.DWFPaved, ElementSet.BalanceModelElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.ModelBalanceDWFPaved, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NetSeepageUnpaved, ElementSet.BalanceModelElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.ModelBalanceNetSeepageUnpaved,
                                        GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.StoragePaved, ElementSet.BalanceModelElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.ModelBalanceStoragePaved, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.StorageUnpaved, ElementSet.BalanceModelElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.ModelBalanceStorageUnpaved,
                                        GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.StorageGreenhouses, ElementSet.BalanceModelElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.ModelBalanceStorageGreenhouses,
                                        GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.StorageWWTP, ElementSet.BalanceModelElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.ModelBalanceStorageWWTP, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.BoundariesOut, ElementSet.BalanceModelElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.ModelBalanceBoundariesOut, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.BoundariesIn, ElementSet.BalanceModelElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.ModelBalanceBoundariesIn, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.ExternalInflowRRRunoff, ElementSet.BalanceModelElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.ModelBalanceExternalInFlowRRRunoff,
                                        GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.StorageChangeRRRunoff, ElementSet.BalanceModelElmSet,
                                        DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.ModelBalanceStorageChangeRRRunoff,
                                        GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.BalanceError_m3, ElementSet.BalanceModelElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.ModelBalanceError, GetCubicMeterUnit()),

                    // NWRW balance
                    new EngineParameter(QuantityType.NwrwModelBalanceRainfall, ElementSet.BalanceModelElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NwrwModelBalanceRainfall, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwModelBalanceEvaporation, ElementSet.BalanceModelElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NwrwModelBalanceEvaporation, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwModelBalanceInfiltrStorage, ElementSet.BalanceModelElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NwrwModelBalanceInfiltrStorage, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwModelBalanceInfiltrRunOff, ElementSet.BalanceModelElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NwrwModelBalanceInfiltrRunOff, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwModelBalanceStorage, ElementSet.BalanceModelElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NwrwModelBalanceStorage, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwModelBalanceRWF, ElementSet.BalanceModelElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NwrwModelBalanceRWF, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwModelBalanceDWFPeople, ElementSet.BalanceModelElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NwrwModelBalanceDWFPeople, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwModelBalanceDWFCompanies, ElementSet.BalanceModelElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NwrwModelBalanceDWFCompanies, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwModelBalanceRWFAndDWF, ElementSet.BalanceModelElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NwrwModelBalanceRWFAndDWF, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwModelBalanceError, ElementSet.BalanceModelElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.NwrwModelBalanceError, GetCubicMeterUnit()),
                    
                    // NWRW 
                    new EngineParameter(QuantityType.Rainfall, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwRainfall, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.RunoffActEvap, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwEvaporation, GetCubicMeterUnit()),
                                        new EngineParameter(QuantityType.NwrwInflowSewer, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflowSewer, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInfilDepress, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInfilDepress, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInfilRunoff, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInfilRunoff, GetCubicMeterUnit()),
                    //new EngineParameter(QuantityType.NwrwRainfall, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwRainfall, GetCubicMeterUnit()),
                    //new EngineParameter(QuantityType.NwrwEvaporation, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwEvaporation, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwRWF, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwRWF, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwDWFPeople, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwDWFPeople, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwDWFCompanies, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwDWFCompanies, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwStorageDepress, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwStorageDepress, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwDynamicStorage, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwDynamicStorage, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInfCapSurf, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInfCapSurf, GetMilliMeterPerHourUnit()),
                    new EngineParameter(QuantityType.NwrwInfCapDyn, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInfCapDyn, GetMilliMeterPerHourUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewer1, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewer1, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewer2, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewer2, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewer3, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewer3, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewer4, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewer4, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewer5, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewer5, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewer6, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewer6, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewer7, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewer7, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewer8, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewer8, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewer9, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewer9, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewer10, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewer10, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewer11, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewer11, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewer12, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewer12, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewerSp1, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewerSp1, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewerSp2, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewerSp2, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewerSp3, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewerSp3, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewerSp4, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewerSp4, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewerSp5, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewerSp5, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewerSp6, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewerSp6, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewerSp7, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewerSp7, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewerSp8, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewerSp8, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewerSp9, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewerSp9, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewerSp10, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewerSp10, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewerSp11, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewerSp11, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwInflSewerSp12, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwInflSewerSp12, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwStorageSp1, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwStorageSp1, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwStorageSp2, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwStorageSp2, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwStorageSp3, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwStorageSp3, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwStorageSp4, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwStorageSp4, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwStorageSp5, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwStorageSp5, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwStorageSp6, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwStorageSp6, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwStorageSp7, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwStorageSp7, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwStorageSp8, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwStorageSp8, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwStorageSp9, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwStorageSp9, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwStorageSp10, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwStorageSp10, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwStorageSp11, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwStorageSp11, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwStorageSp12, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwStorageSp12, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwWadiInflow, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwWadiInflow, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwWadiInfiltr, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwWadiInfiltr, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwWadiSpill, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwWadiSpill, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwWadiDrain, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwWadiDrain, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwWadiStorage, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwWadiStorage, GetCubicMeterUnit()),
                    new EngineParameter(QuantityType.NwrwWadiLevel, ElementSet.NWRWElmSet, DataItemRole.Output, RainfallRunoffModelParameterNames.NwrwWadiLevel, GetMeterUnit()),
					

                    //link
                    new EngineParameter(QuantityType.Flow, ElementSet.LinkElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.LinkFlowOut, GetCubicMeterPerSecondUnit()),

                    //boundary
                    new EngineParameter(QuantityType.Flow, ElementSet.BoundaryElmSet, DataItemRole.Output,
                                        RainfallRunoffModelParameterNames.BoundaryDischarge,
                                        GetCubicMeterPerSecondUnit()),
                };
        }
    }
}