substance 'AAP' active
   description        'adsorbed ortho phosphate'
   concentration-unit '(gP/m3)'
   waste-load-unit    '-'
end-substance
substance 'DetC' active
   description        'Detritus Carbon  (DetC)'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'DetN' active
   description        'Detritus Nitrogen (DetN)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'DetP' active
   description        'Detritus Phosphorus (DetP)'
   concentration-unit '(gP/m3)'
   waste-load-unit    '-'
end-substance
substance 'NH4' active
   description        'Ammonium (NH4)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'NO3' active
   description        'Nitrate (NO3)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'PO4' active
   description        'Ortho-Phosphate (PO4)'
   concentration-unit '(gP/m3)'
   waste-load-unit    '-'
end-substance
substance 'CBOD5' active
   description        'carbonaceous BOD (first pool) at 5 days'
   concentration-unit '(gO2/m3)'
   waste-load-unit    '-'
end-substance
substance 'CBOD5_2' active
   description        'carbonaceous BOD (second pool) at 5 days'
   concentration-unit '(gO2/m3)'
   waste-load-unit    '-'
end-substance
substance 'OXY' active
   description        'Dissolved Oxygen'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'IM1' active
   description        'inorganic matter (IM1)'
   concentration-unit '(gDM/m3)'
   waste-load-unit    '-'
end-substance
substance 'SOD' inactive
   description        'Sediment oxygen demand (SOD)'
   concentration-unit '(gO2/m3)'
   waste-load-unit    '-'
end-substance
parameter 'SWAdsP'
   description   'switch PO4 adsorption <0=Kd|1=Langmuir|2=pHdep>'
   unit          '(-)'
   value          0
end-parameter
parameter 'KdPO4AAP'
   description   'distrib. coeff. (-) or ads. eq. const.'
   unit          '(m3/gP)'
   value          0.075
end-parameter
parameter 'RcDetC'
   description   'first-order mineralisation rate DetC'
   unit          '(1/d)'
   value          0
end-parameter
parameter 'TcDetC'
   description   'temperature coefficient for mineralisation DetC'
   unit          '(-)'
   value          1.05
end-parameter
parameter 'CTMin'
   description   'critical temperature for mineralisation'
   unit          '(oC)'
   value          3
end-parameter
parameter 'VSedDetC'
   description   'sedimentation velocity DetC'
   unit          '(m/d)'
   value          0
end-parameter
parameter 'TauCSDetC'
   description   'critical shear stress for sedimentation DetC'
   unit          '(N/m2)'
   value          0.1
end-parameter
parameter 'RcDetN'
   description   'first-order mineralisation rate DetN'
   unit          '(1/d)'
   value          0.1
end-parameter
parameter 'TcDetN'
   description   'temperature coefficient for mineralisation DetN'
   unit          '(-)'
   value          1.045
end-parameter
parameter 'fTEWORBOD'
   description   'TEWOR production flux of CBOD5_2'
   unit          '(gO2/m3/d)'
   value          0
end-parameter
parameter 'fTEWOROXY'
   description   'TEWOR production flux of OXY'
   unit          '(gO2/m3/d)'
   value          0
end-parameter
parameter 'fTEWORORGN'
   description   'TEWOR production flux of Org-N'
   unit          '(gN/m3/d)'
   value          0
end-parameter
parameter 'fTEWORNH4'
   description   'TEWOR production flux of NH4'
   unit          '(gN/m3/d)'
   value          0
end-parameter
parameter 'fTEWORNO3'
   description   'TEWOR production flux of NO3'
   unit          '(gN/m3/d)'
   value          0
end-parameter
parameter 'RcDetP'
   description   'first-order mineralisation rate DetP'
   unit          '(1/d)'
   value          0
end-parameter
parameter 'TcDetP'
   description   'temperature coefficient for mineralisation DetP'
   unit          '(-)'
   value          1.05
end-parameter
parameter 'TcNit'
   description   'temperature coefficient for nitrification'
   unit          '(-)'
   value          1.08
end-parameter
parameter 'COXNIT'
   description   'critical oxygen concentration for nitrification'
   unit          '(g/m3)'
   value          1
end-parameter
parameter 'RcNit'
   description   'first-order nitrification rate'
   unit          '(1/d)'
   value          0.1
end-parameter
parameter 'OOXNIT'
   description   'optimum oxygen concentration for nitrification'
   unit          '(gO2/m3)'
   value          5
end-parameter
parameter 'TcDenWat'
   description   'temperature coefficient for denitrification'
   unit          '(-)'
   value          1.045
end-parameter
parameter 'COXDEN'
   description   'critical oxygen concentration for denitrification'
   unit          '(g/m3)'
   value          3
end-parameter
parameter 'RcDenWat'
   description   'first-order denitrification rate in water column'
   unit          '(1/d)'
   value          0.1
end-parameter
parameter 'OOXDEN'
   description   'optimum oxygen concentration for denitrification'
   unit          '(gO2/m3)'
   value          1
end-parameter
parameter 'RcBOD'
   description   'decay rate BOD (first pool) at 20 oC'
   unit          '(1/d)'
   value          0.6
end-parameter
parameter 'RcBOD_2'
   description   'decay rate BOD (second pool) at 20 oC'
   unit          '(1/d)'
   value          0.1
end-parameter
parameter 'TcBOD'
   description   'temperature coefficient decay BOD'
   unit          '(-)'
   value          1.047
end-parameter
parameter 'COXBOD'
   description   'critical oxygen concentration for BOD decay'
   unit          '(gO2/m3)'
   value          1
end-parameter
parameter 'OOXBOD'
   description   'optimum oxygen concentration for BOD decay'
   unit          '(gO2/m3)'
   value          5
end-parameter
parameter 'CFLBOD'
   description   'oxygen function level for oxygen below COXBOD'
   unit          '(-)'
   value          0
end-parameter
parameter 'CurvBOD'
   description   'curvature of DO function for mineralisation BOD'
   unit          '(-)'
   value          0
end-parameter
parameter 'O2FuncBOD'
   description   'oxygen function for decay of CBOD'
   unit          '(-)'
   value          0
end-parameter
parameter 'BOD5'
   description   'BOD5'
   unit          '(gO2/m3)'
   value          0
end-parameter
parameter 'BODu'
   description   'calculated carbonaceous BOD at ultimate'
   unit          '(gO2/m3)'
   value          0
end-parameter
parameter 'VSedBOD5'
   description   'sedimentation velocity CBOD5'
   unit          '(m/d)'
   value          0
end-parameter
parameter 'VSedBOD5_2'
   description   'sedimentation velocity CBOD5_2'
   unit          '(m/d)'
   value          0.1
end-parameter
parameter 'SWRear'
   description   'switch for oxygen reaeration formulation (1-12)'
   unit          '(-)'
   value          1
end-parameter
parameter 'KLRear'
   description   'reaeration transfer coefficient'
   unit          '(m/d)'
   value          0.35
end-parameter
parameter 'TCRear'
   description   'temperature coefficient for rearation'
   unit          '(-)'
   value          1.024
end-parameter
parameter 'fSOD'
   description   'zeroth-order sediment oxygen demand flux'
   unit          '(gO2/m2/d)'
   value          0
end-parameter
parameter 'RcSOD'
   description   'decay rate SOD at 20 oC'
   unit          '(1/d)'
   value          0
end-parameter
parameter 'VSedIM1'
   description   'sedimentation velocity IM1'
   unit          '(m/d)'
   value          0
end-parameter
parameter 'TaucSIM1'
   description   'critical shear stress for sedimentation IM1'
   unit          '(N/m2)'
   value          0.1
end-parameter
parameter 'Temp'
   description   'ambient water temperature'
   unit          '(oC)'
   value          0.1500E+02
end-parameter
parameter 'VWind'
   description   'wind speed'
   unit          '(m/s)'
   value          0.3000E+01
end-parameter
output 'fSedIM1'
   description   'sedimentation flux IM1'
end-output
output 'Depth'
   description   'depth of segment'
end-output
output 'TotN'
   description   'total nitrogen (including algae)'
end-output
output 'KjelN'
   description   'Kjeldahl nitrogen'
end-output
output 'TotP'
   description   'total phosphorus (including algae)'
end-output
output 'SaturOXY'
   description   'saturation concentration'
end-output
output 'SatPercOXY'
   description   'Actual saturation percentage O2'
end-output
output 'DO'
   description   'dissolved oxygen concentration'
end-output
active-processes
   name  'AdsPO4AAP' 'Ad(De)Sorption ortho phosphorus to inorg. matter'
   name  'Sed_AAP' 'Sedimentation AAP (adsorbed PO4)'
   name  'Compos' 'Composition'
   name  'WM_DetC' 'Mineralisation detritus carbon'
   name  'SedDetC' 'Sedimentation detritus carbon'
   name  'WM_DetN' 'Mineralisation detritus nitrogen'
   name  'SedN_Det' 'Sedim. nutrients in detritus'
   name  'Prod_TEWOR' 'Production fluxes for TEWOR+'
   name  'WM_DetP' 'Mineralisation detritus phosphorus'
   name  'Nitrif_NH4' 'Nitrification of ammonium'
   name  'DenWat_NO3' 'Denitrification in water column'
   name  'BODCOD' 'Mineralisation BOD and COD'
   name  'S_CBOD51' 'Sedimentation CBOD5 (first pool)'
   name  'S_CBOD52' 'Sedimentation CBOD5_2 (second pool)'
   name  'RearOXY' 'Reaeration of oxygen'
   name  'SedOXYDem' 'Sediment oxygen demand'
   name  'PosOXY' 'Positive oxygen concentration'
   name  'Sed_IM1' 'Sedimentation IM1'
   name  'DynDepth' 'dynamic calculation of the depth'
   name  'POC_Dyn' 'Composition of POC (Dynamo & Bloom)'
   name  'CalTau' 'Calculation of bottom friction'
   name  'SaturOXY' 'Saturation concentration oxygen'
   name  'TotDepth' 'depth water column'
end-active-processes
