///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DHYDRO.Modules.AttributesTable
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RightClickAndChooseOptionInCell recording.
    /// </summary>
    [TestModule("0b04c9ae-3284-4368-a866-092d8c413bb7", ModuleType.Recording, 1)]
    public partial class RightClickChooseContextMenuItem : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DHYDRO.DHYDRO1D2DRepository repository.
        /// </summary>
        public static global::DHYDRO.DHYDRO1D2DRepository repo = global::DHYDRO.DHYDRO1D2DRepository.Instance;

        static RightClickChooseContextMenuItem instance = new RightClickChooseContextMenuItem();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RightClickChooseContextMenuItem()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RightClickChooseContextMenuItem Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable AttributeTableName.
        /// </summary>
        [TestVariable("3702f5ef-f369-4d0e-b6c1-9ea92f70a752")]
        public string AttributeTableName
        {
            get { return repo.AttributeTableName; }
            set { repo.AttributeTableName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable rowNumber.
        /// </summary>
        [TestVariable("8e9934c7-a04c-4bd8-b138-e1535118001c")]
        public string rowNumber
        {
            get { return repo.rowNumber; }
            set { repo.rowNumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable ColumnNumber.
        /// </summary>
        [TestVariable("30a85af4-a76a-456d-8d70-14bc7274106b")]
        public string ColumnNumber
        {
            get { return repo.ColumnNumber; }
            set { repo.ColumnNumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable MenuItemName.
        /// </summary>
        [TestVariable("614b7f5f-27d0-4639-a637-b89db75c6519")]
        public string MenuItemName
        {
            get { return repo.MenuItemName; }
            set { repo.MenuItemName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'DSWindow.ListView.AttributeTableCell' at Center.", repo.DSWindow.ListView.AttributeTableCellInfo, new RecordItemIndex(0));
            repo.DSWindow.ListView.AttributeTableCell.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuInMapTree.GenericMenuItem' at Center.", repo.ContextMenuInMapTree.GenericMenuItemInfo, new RecordItemIndex(1));
            repo.ContextMenuInMapTree.GenericMenuItem.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
