//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaShell.Plugins.ImportExport.Sobek.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeltaShell.Plugins.ImportExport.Sobek.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra friction file &apos;{0}&apos; found, but is not supported; skipping....
        /// </summary>
        public static string Extra_friction_file_0_found_but_is_not_supported {
            get {
                return ResourceManager.GetString("Extra_friction_file_0_found_but_is_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected 24 values but got {0} values. Skipping import of water use per capita per hour..
        /// </summary>
        public static string NwrwDryWeatherFlowDefinitionBuilder_WarningIncorrectNumberOfWaterCapacityPerHourValues {
            get {
                return ResourceManager.GetString("NwrwDryWeatherFlowDefinitionBuilder_WarningIncorrectNumberOfWaterCapacityPerHourV" +
                        "alues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sobek {
            get {
                object obj = ResourceManager.GetObject("sobek", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} import failed: {1}.
        /// </summary>
        public static string SobekRRMeteoDataImporter_AddMeteoData__0__import_failed___1_ {
            get {
                return ResourceManager.GetString("SobekRRMeteoDataImporter_AddMeteoData__0__import_failed___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meteo data with DataDistributionType {0} is not supported.
        /// </summary>
        public static string SobekRRMeteoDataImporter_AddMeteoData_Meteo_data_with_DataDistributionType__0__is_not_supported {
            get {
                return ResourceManager.GetString("SobekRRMeteoDataImporter_AddMeteoData_Meteo_data_with_DataDistributionType__0__is" +
                        "_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a catchment for the following stations {0}..
        /// </summary>
        public static string SobekRRMeteoDataImporter_AddMissingFeatures_Could_not_find_a_catchment_for_the_following_stations__0__ {
            get {
                return ResourceManager.GetString("SobekRRMeteoDataImporter_AddMissingFeatures_Could_not_find_a_catchment_for_the_fo" +
                        "llowing_stations__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file does not exist: {1}.
        /// </summary>
        public static string SobekRRMeteoDataImporter_CanReadEvaporation__0__file_does_not_exist___1_ {
            get {
                return ResourceManager.GetString("SobekRRMeteoDataImporter_CanReadEvaporation__0__file_does_not_exist___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaporation has multiple stations while precipitation has not! Not supported.
        /// </summary>
        public static string SobekRRMeteoDataImporter_CanReadEvaporation_Evaporation_has_multiple_stations_while_precipitation_has_not__Not_supported {
            get {
                return ResourceManager.GetString("SobekRRMeteoDataImporter_CanReadEvaporation_Evaporation_has_multiple_stations_whi" +
                        "le_precipitation_has_not__Not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainfall Runoff meteo data.
        /// </summary>
        public static string SobekRRMeteoDataImporter_DisplayName_Rainfall_Runoff_meteo_data {
            get {
                return ResourceManager.GetString("SobekRRMeteoDataImporter_DisplayName_Rainfall_Runoff_meteo_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} import failed, could not read header data from {1} file..
        /// </summary>
        public static string SobekRRMeteoDataImporter_GetBuiFileMeteoImportData__0__import_failed__could_not_read_header_data_from__1__file_ {
            get {
                return ResourceManager.GetString("SobekRRMeteoDataImporter_GetBuiFileMeteoImportData__0__import_failed__could_not_r" +
                        "ead_header_data_from__1__file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported meteo distribution type for evaporation..
        /// </summary>
        public static string SobekRRMeteoDataImporter_GetEvaporationMeteoStations_Unsupported_meteo_distribution_type_for_evaporation_ {
            get {
                return ResourceManager.GetString("SobekRRMeteoDataImporter_GetEvaporationMeteoStations_Unsupported_meteo_distributi" +
                        "on_type_for_evaporation_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .rks files are not supported. The first event will be imported as precipitation data..
        /// </summary>
        public static string SobekRRMeteoDataImporter_GetFilePaths__rks_files_are_not_supported__The_first_event_will_be_imported_as_precipitation_data_ {
            get {
                return ResourceManager.GetString("SobekRRMeteoDataImporter_GetFilePaths__rks_files_are_not_supported__The_first_eve" +
                        "nt_will_be_imported_as_precipitation_data_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of evaporation stations does not match the number of precipitation stations! Not supported.
        /// </summary>
        public static string SobekRRMeteoDataImporter_GetSobekRREvaporationMeteoImportData_Number_of_evaporation_stations_does_not_match_the_number_of_precipitation_stations__Not_supported {
            get {
                return ResourceManager.GetString("SobekRRMeteoDataImporter_GetSobekRREvaporationMeteoImportData_Number_of_evaporati" +
                        "on_stations_does_not_match_the_number_of_precipitation_stations__Not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing precipitation data....
        /// </summary>
        public static string SobekRRMeteoDataImporter_ImportMeteoData_Importing_precipitation_data___ {
            get {
                return ResourceManager.GetString("SobekRRMeteoDataImporter_ImportMeteoData_Importing_precipitation_data___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap STARTUP {
            get {
                object obj = ResourceManager.GetObject("STARTUP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
