Sobek Parser V2.05.027.20601

Warning    : Structure at calculation point: grid point skipped
Object-id  : S_10                                    
Object-name: Weir01                                  

Warning    : Start date in meteo-file differs from Sobek start date
Object-id  : Bui                                     

Warning    : Data for Non-Existent or Non-Active Controller
Object-id  : ##1                                     
Object-name: WeirControl01                           

Warning    : Data for Non-Existent or Non-Active Controller
Object-id  : ##2                                     
Object-name: WeirControl02                           

Warning    : Data for Non-Existent or Non-Active Controller
Object-id  : ##3                                     
Object-name: WeirControl03                           

Informative Messages:     0
Warnings            :     5
Errors!             :     0

End of program
