///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DHYDRO.Modules.ModelSettings__Waves_
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SetBoundarySettings recording.
    /// </summary>
    [TestModule("2e3ae591-8b32-4144-b779-332f626e8851", ModuleType.Recording, 1)]
    public partial class SetBoundarySettings : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DHYDRO.DHYDRORepository repository.
        /// </summary>
        public static global::DHYDRO.DHYDRORepository repo = global::DHYDRO.DHYDRORepository.Instance;

        static SetBoundarySettings instance = new SetBoundarySettings();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SetBoundarySettings()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SetBoundarySettings Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SettingsGroupBox.ForcingTypeComboBox' at Center.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SettingsGroupBox.ForcingTypeComboBoxInfo, new RecordItemIndex(0));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SettingsGroupBox.ForcingTypeComboBox.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SettingsContextMenu.Grid.ParametrizedConstant' at Center.", repo.SettingsContextMenu.Grid.ParametrizedConstantInfo, new RecordItemIndex(1));
            repo.SettingsContextMenu.Grid.ParametrizedConstant.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SettingsGroupBox.SpatialDefinitionComboBox' at Center.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SettingsGroupBox.SpatialDefinitionComboBoxInfo, new RecordItemIndex(2));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SettingsGroupBox.SpatialDefinitionComboBox.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SettingsContextMenu.Grid.SpatiallyVarying' at Center.", repo.SettingsContextMenu.Grid.SpatiallyVaryingInfo, new RecordItemIndex(3));
            repo.SettingsContextMenu.Grid.SpatiallyVarying.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.ParametersGroupBox.ShapeComboBox' at Center.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.ParametersGroupBox.ShapeComboBoxInfo, new RecordItemIndex(4));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.ParametersGroupBox.ShapeComboBox.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SettingsContextMenu.Grid.Jonswap1' at Center.", repo.SettingsContextMenu.Grid.Jonswap1Info, new RecordItemIndex(5));
            repo.SettingsContextMenu.Grid.Jonswap1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.AddNewDistanceTextBox' at Center.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.AddNewDistanceTextBoxInfo, new RecordItemIndex(6));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.AddNewDistanceTextBox.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(7));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '50000' with focus on 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.AddNewDistanceTextBox'.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.AddNewDistanceTextBoxInfo, new RecordItemIndex(8));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.AddNewDistanceTextBox.PressKeys("50000");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.AddSupportPointButton' at Center.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.AddSupportPointButtonInfo, new RecordItemIndex(9));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.AddSupportPointButton.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.AddNewDistanceTextBox' at Center.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.AddNewDistanceTextBoxInfo, new RecordItemIndex(10));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.AddNewDistanceTextBox.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(11));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '200000' with focus on 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.AddNewDistanceTextBox'.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.AddNewDistanceTextBoxInfo, new RecordItemIndex(12));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.AddNewDistanceTextBox.PressKeys("200000");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.AddSupportPointButton' at Center.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.AddSupportPointButtonInfo, new RecordItemIndex(13));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.AddSupportPointButton.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.SupportPoint2CheckBox' at Center.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.SupportPoint2CheckBoxInfo, new RecordItemIndex(14));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.SupportPoint2CheckBox.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.SupportPoint3CheckBox' at Center.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.SupportPoint3CheckBoxInfo, new RecordItemIndex(15));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.SupportPoint3CheckBox.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.SupportPoint2RadioButton' at Center.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.SupportPoint2RadioButtonInfo, new RecordItemIndex(16));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.SupportPoint2RadioButton.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.HeightField' at Center.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.HeightFieldInfo, new RecordItemIndex(17));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.HeightField.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(18));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '2.0' with focus on 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.HeightField'.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.HeightFieldInfo, new RecordItemIndex(19));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.HeightField.PressKeys("2.0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.PeriodField' at Center.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.PeriodFieldInfo, new RecordItemIndex(20));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.PeriodField.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(21));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '5.0' with focus on 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.PeriodField'.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.PeriodFieldInfo, new RecordItemIndex(22));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.PeriodField.PressKeys("5.0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.DirectionField' at Center.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.DirectionFieldInfo, new RecordItemIndex(23));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.DirectionField.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(24));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '315' with focus on 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.DirectionField'.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.DirectionFieldInfo, new RecordItemIndex(25));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.DirectionField.PressKeys("315");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.SpreadingField' at Center.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.SpreadingFieldInfo, new RecordItemIndex(26));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.SpreadingField.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(27));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '4' with focus on 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.SpreadingField'.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.SpreadingFieldInfo, new RecordItemIndex(28));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.SpreadingField.PressKeys("4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.SupportPoint3RadioButton' at Center.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.SupportPoint3RadioButtonInfo, new RecordItemIndex(29));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SupportPointsGroupBox.SupportPoint3RadioButton.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.HeightField' at Center.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.HeightFieldInfo, new RecordItemIndex(30));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.HeightField.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(31));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '4.0' with focus on 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.HeightField'.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.HeightFieldInfo, new RecordItemIndex(32));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.HeightField.PressKeys("4.0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.PeriodField' at Center.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.PeriodFieldInfo, new RecordItemIndex(33));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.PeriodField.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(34));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '5.0' with focus on 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.PeriodField'.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.PeriodFieldInfo, new RecordItemIndex(35));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.PeriodField.PressKeys("5.0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.DirectionField' at Center.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.DirectionFieldInfo, new RecordItemIndex(36));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.DirectionField.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(37));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '315' with focus on 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.DirectionField'.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.DirectionFieldInfo, new RecordItemIndex(38));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.DirectionField.PressKeys("315");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.SpreadingField' at Center.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.SpreadingFieldInfo, new RecordItemIndex(39));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.SpreadingField.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(40));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '4' with focus on 'DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.SpreadingField'.", repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.SpreadingFieldInfo, new RecordItemIndex(41));
            repo.DSWindow.DocumentsPaneCentral.WavesBoundaryEditor.SpatialParamertersGroupBox.SpreadingField.PressKeys("4");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
