substance 'CWTOT' active
   description        'CONCENTRATIE MICRO-VERONTREINIGING'
   concentration-unit 'g/m'
   waste-load-unit    '-'
end-substance
substance 'POCW' active
   description        'PARTICULAIR ORGANISCHE C WATERKOLOM'
   concentration-unit 'g/m'
   waste-load-unit    '-'
end-substance
substance 'SSW' active
   description        'ZWEVENDE STOF WATERKOLOM'
   concentration-unit 'g/m'
   waste-load-unit    '-'
end-substance
substance 'DOCW' active
   description        'OPGELOST ORGANISCH C WATERKOLOM'
   concentration-unit 'g/m'
   waste-load-unit    '-'
end-substance
substance 'AOCW' active
   description        'ALGEN KOOLSTOF'
   concentration-unit 'g/M'
   waste-load-unit    '-'
end-substance
substance 'DOCB' inactive
   description        'OPGELOST ORGANISCH C TOPLAAG'
   concentration-unit 'g/m'
   waste-load-unit    '-'
end-substance
substance 'POCB' inactive
   description        'PARTICULAIR ORGANISCH C TOPLAAG'
   concentration-unit 'g/m'
   waste-load-unit    '-'
end-substance
substance 'DOCSUB' inactive
   description        'OPGELOST ORGANISCH C SEDIMENT ONDERLAAG'
   concentration-unit 'g/m'
   waste-load-unit    '-'
end-substance
substance 'POCSUB' inactive
   description        'PARTICULAIR ORGANISCH C SEDIMENT ONDERLAAG'
   concentration-unit 'g/m'
   waste-load-unit    '-'
end-substance
substance 'CBTOT' inactive
   description        'MICRO-VERONTREINIGING TOPLAAG'
   concentration-unit 'g/m'
   waste-load-unit    '-'
end-substance
substance 'CSUBT' inactive
   description        'MICRO-VERONTREINIGING SEDIMENT ONDERLAAG'
   concentration-unit 'g/m'
   waste-load-unit    '-'
end-substance
parameter 'ALFA'
   description   'FRACTIE POC DIE VRIJKOMT AFSTERVING ALGEN'
   unit          'gPOC/gAO'
   value            0.5000000    
end-parameter
parameter 'DZ'
   description   'DIKTE AKTIEVE TOPLAAG SEDIMENT'
   unit          'm'
   value            0.1000000    
end-parameter
parameter 'EZ'
   description   'DIFFUSIE CONSTANTE GRENSVLAK SED/WATER'
   unit          'm2/day'
   value            0.5000000E-04
end-parameter
parameter 'FC'
   description   'VERHOUDING C/DROGE STOF ALGEN EN DETRITUS'
   unit          'kg/kg'
   value            0.5200000    
end-parameter
parameter 'KPAOC'
   description   'PARTITIECOEFFICIENT AOC'
   unit          'm3/g DOC'
   value            0.4900000E-02
end-parameter
parameter 'KPDOC'
   description   'PARTITIECOEFFICIENT DOC'
   unit          'm3/g DOC'
   value            0.5000000E-02
end-parameter
parameter 'KPPOC'
   description   'PARTITIECOEFFICIENT POC'
   unit          'm3/g DOC'
   value            0.4900000E-02
end-parameter
parameter 'KDAOC'
   description   'SNELHEIDSCONSTANTE AFSTERVING ALGEN'
   unit          '1/dag'
   value            0.5000000E-01
end-parameter
parameter 'KDC'
   description   'SNELHEIDSCONSTANTE AFBRAAK MICRO WATER'
   unit          '1/day'
   value            0.5000000E-04
end-parameter
parameter 'KHYDW'
   description   'SNELHEIDSCONSTANTE HYDROLYSE POC WATER'
   unit          '1/day'
   value            0.1000000E-01
end-parameter
parameter 'KHYDB'
   description   'SNELHEIDSCONSTANTE HYDROLYSE POC SEDIMENT'
   unit          '1/day'
   value            0.5000000E-04
end-parameter
parameter 'KDMINW'
   description   'SNELHEIDSCONSTANTE MINERALISATIE WATER'
   unit          '1/day'
   value            0.4000000E-01
end-parameter
parameter 'KDMINB'
   description   'SNELHEIDSCONSTANTE MINERALISATIE SEDIMENT'
   unit          '1/dag'
   value            0.1500000E-01
end-parameter
parameter 'KL'
   description   'STOFOVERDRACHTSCONSTANTE MICRO'
   unit          'm/day'
   value             1.920000    
end-parameter
parameter 'POR'
   description   'POROSITEIT'
   unit          '-'
   value            0.8000000    
end-parameter
parameter 'RHOANO'
   description   'DICHTHEID ANORGANISCHE STOF'
   unit          'g/m3'
   value             2600000.    
end-parameter
parameter 'RHOORG'
   description   'DICHTHEID ORGANISCHE STOF'
   unit          'g/m3'
   value             1000000.    
end-parameter
parameter 'VSN'
   description   'SEDIMENTATIESNELHEID ORG. MATERIAAL'
   unit          'm/dag'
   value            0.7000000    
end-parameter
parameter 'VSP'
   description   'SEDIMENTATIESNELHEID ALGEN'
   unit          'm/day'
   value            0.4000000    
end-parameter
parameter 'VSS'
   description   'SEDIMENTATIE SNELHEID SS'
   unit          'm/day'
   value             1.500000    
end-parameter
parameter 'FRES'
   description   'RESUSPENSIE FLUX'
   unit          'g/m2/day'
   value             20.00000    
end-parameter
parameter 'Fatm'
   description   'DIFFUSE BRON MICRO-VERONTREINIGING'
   unit          'g/m2/day'
   value             0.000000    
end-parameter
parameter 'PAOC'
   description   'AOC PRODUCTIESNELHEID'
   unit          'g/m3,day'
   value             1.000000    
end-parameter
output 'Z'
   description   'water depth'
end-output
output 'dt'
   description   'timestep of Duflow-quality calculation in seconds'
end-output
output 'SSB'
   description   'RHOANO*((1-POR)-(POCB/(FC*RHOORG)))+(POCB/FC)'
end-output
output 'FCSSW'
   description   '(POCW/FC)/SSW'
end-output
output 'FCSSB'
   description   '(POCB/FC)/SSB'
end-output
output 'FOMW'
   description   ' FCSSW/RHOORG'
end-output
output 'FSSW'
   description   ' (1-FCSSW)/RHOANO'
end-output
output 'FOMB'
   description   ' FCSSB/RHOORG'
end-output
output 'FSSB'
   description   ' (1-FCSSB)/RHOANO'
end-output
output 'RHOSSW'
   description   ' RHOORG*(FOMW/(FOMW+FSSW))+RHOANO*(FSSW/(FOMW+FSSW'
end-output
output 'RHOSSB'
   description   ' RHOORG*(FOMB/(FOMB+FSSB))+RHOANO*(FSSB/(FOMB+FSSB'
end-output
output 'VR'
   description   ' FRES/(RHOSSB*(1-POR))'
end-output
output 'VS'
   description   ' VSS*SSW/(RHOSSW*(1-POR))'
end-output
output 'FSPOC'
   description   'POCB/SSB'
end-output
output 'EZ2'
   description   '0.00001+EZ*EXP(-50*DZ)'
end-output
output 'CSUBDIS'
   description   'CSUBT/(1+KPPOC*POCSUB+KPDOC*DOCSUB)'
end-output
output 'CSUBDOC'
   description   'CSUBT*KPDOC*DOCSUB/(1+KPPOC*POCSUB+KPDOC*DOCSUB)'
end-output
output 'CWDIS'
   description   ' CWTOT           /(1+KPDOC*DOCW+KPPOC*POCW+KPAOC*A'
end-output
output 'CWDOC'
   description   ' CWTOT*KPDOC*DOCW/(1+KPDOC*DOCW+KPPOC*POCW+KPAOC*A'
end-output
output 'CWPOC'
   description   ' CWTOT*KPPOC*POCW/(1+KPDOC*DOCW+KPPOC*POCW+KPAOC*A'
end-output
output 'CWAOC'
   description   ' CWTOT*KPAOC*AOCW/(1+KPDOC*DOCW+KPPOC*POCW+KPAOC*A'
end-output
output 'CBDIS'
   description   ' CBTOT           /(1+KPDOC*DOCB+KPPOC*POCB)'
end-output
output 'CBDOC'
   description   ' CBTOT*KPDOC*DOCB/(1+KPDOC*DOCB+KPPOC*POCB)'
end-output
output 'CBPOC'
   description   ' CBTOT*KPPOC*POCB/(1+KPDOC*DOCB+KPPOC*POCB)'
end-output
output 'Matm'
   description   ' + Fatm'
end-output
output 'Msed'
   description   ' + VSN*CWPOC+VSP*CWAOC'
end-output
output 'Mres'
   description   ' + FRES*CBPOC/SSB'
end-output
output 'Mdif1'
   description   ' + EZ*POR*(CWDIS-CBDIS/POR)/(0.5*DZ)   &'
end-output
output 'Mdif2'
   description   ' + EZ2*(CBDIS-CSUBDIS)/(0.5*DZ)   &'
end-output
output 'Mverv'
   description   ' + KL*CWDIS/Z'
end-output
output 'Mafb1'
   description   ' + KDC*CWDIS*Z'
end-output
output 'Mafb2'
   description   ' + KDC*CBDIS*DZ'
end-output
output 'Mpsad1'
   description   ' + VR*(CBDIS+CBDOC)-VS*POR*(CWDIS+CWDOC)'
end-output
output 'Mpsad2'
   description   ' - VS*CBTOT+VR*CSUBT'
end-output
output 'CSSB'
   description   '1000*CBPOC/SSB'
end-output
output 'CSSW'
   description   '1000*CWPOC/SSW'
end-output
output 'CIW'
   description   '(CBDIS+CBDOC)/POR'
end-output
active-processes
   name  'HydDuflow' 'HydDuflow'
   name  'OMIVE' 'OMIVE'
end-active-processes
