//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaShell.Plugins.FMSuite.Wave.Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeltaShell.Plugins.FMSuite.Wave.Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap compass {
            get {
                object obj = ResourceManager.GetObject("compass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap domain {
            get {
                object obj = ResourceManager.GetObject("domain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_domain {
            get {
                object obj = ResourceManager.GetObject("folder_domain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Grid2D {
            get {
                object obj = ResourceManager.GetObject("Grid2D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hurricane2 {
            get {
                object obj = ResourceManager.GetObject("hurricane2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication files|*{0}.
        /// </summary>
        internal static string SelectComFileButton_ButtonAction_Communication_files___0_ {
            get {
                return ResourceManager.GetString("SelectComFileButton_ButtonAction_Communication_files___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wall_brick {
            get {
                object obj = ResourceManager.GetObject("wall_brick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wave {
            get {
                object obj = ResourceManager.GetObject("wave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string WaveBoundaryNodePresenter_GetContextMenu_Delete {
            get {
                return ResourceManager.GetString("WaveBoundaryNodePresenter_GetContextMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Interior Domain....
        /// </summary>
        internal static string WaveDomainNodePresenter_CreateAddDomainMenuItem_Add_Interior_Domain___ {
            get {
                return ResourceManager.GetString("WaveDomainNodePresenter_CreateAddDomainMenuItem_Add_Interior_Domain___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Exterior Domain....
        /// </summary>
        internal static string WaveDomainNodePresenter_CreateAddSuperDomainMenuItem_Add_Exterior_Domain___ {
            get {
                return ResourceManager.GetString("WaveDomainNodePresenter_CreateAddSuperDomainMenuItem_Add_Exterior_Domain___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Domain.
        /// </summary>
        internal static string WaveDomainNodePresenter_CreateDeleteDomainMenuItem_Delete_Domain {
            get {
                return ResourceManager.GetString("WaveDomainNodePresenter_CreateDeleteDomainMenuItem_Delete_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate....
        /// </summary>
        internal static string WaveModelNodePresenter_CreateValidationMenuItem_Validate___ {
            get {
                return ResourceManager.GetString("WaveModelNodePresenter_CreateValidationMenuItem_Validate___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupled to D-Flow FM.
        /// </summary>
        internal static string WaveSettingsHelper_GetWaveSettings_Coupled_to_D_Flow_FM {
            get {
                return ResourceManager.GetString("WaveSettingsHelper_GetWaveSettings_Coupled_to_D_Flow_FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupling start time.
        /// </summary>
        internal static string WaveSettingsHelper_GetWaveSettings_Coupling_start_time {
            get {
                return ResourceManager.GetString("WaveSettingsHelper_GetWaveSettings_Coupling_start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupling stop time.
        /// </summary>
        internal static string WaveSettingsHelper_GetWaveSettings_Coupling_stop_time {
            get {
                return ResourceManager.GetString("WaveSettingsHelper_GetWaveSettings_Coupling_stop_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupling time step.
        /// </summary>
        internal static string WaveSettingsHelper_GetWaveSettings_Coupling_time_step {
            get {
                return ResourceManager.GetString("WaveSettingsHelper_GetWaveSettings_Coupling_time_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupling time step [Dd HH:MM:SS.ZZZ].
        /// </summary>
        internal static string WaveSettingsHelper_GetWaveSettings_Coupling_time_step_tooltip {
            get {
                return ResourceManager.GetString("WaveSettingsHelper_GetWaveSettings_Coupling_time_step_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain specific settings.
        /// </summary>
        internal static string WaveSettingsHelper_GetWaveSettings_Domain_specific_settings {
            get {
                return ResourceManager.GetString("WaveSettingsHelper_GetWaveSettings_Domain_specific_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online-coupling time frame.
        /// </summary>
        internal static string WaveSettingsHelper_GetWaveSettings_Online_Coupling_Time_Frame {
            get {
                return ResourceManager.GetString("WaveSettingsHelper_GetWaveSettings_Online_Coupling_Time_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time within the coupled model run [YYYY-MM-DD HH:MM:SS].
        /// </summary>
        internal static string WaveSettingsHelper_GetWaveSettings_Start_time_within_the_coupled_model_run {
            get {
                return ResourceManager.GetString("WaveSettingsHelper_GetWaveSettings_Start_time_within_the_coupled_model_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop time within the coupled model run [YYYY-MM-DD HH:MM:SS].
        /// </summary>
        internal static string WaveSettingsHelper_GetWaveSettings_Stop_time_within_the_coupled_model_run {
            get {
                return ResourceManager.GetString("WaveSettingsHelper_GetWaveSettings_Stop_time_within_the_coupled_model_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, domain specific data can be filled in.
        /// </summary>
        internal static string WaveSettingsHelper_GetWaveSettings_When_enabled__domain_specific_data_can_be_filled_in {
            get {
                return ResourceManager.GetString("WaveSettingsHelper_GetWaveSettings_When_enabled__domain_specific_data_can_be_fill" +
                        "ed_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, run coupled to D-Flow FM core.
        /// </summary>
        internal static string WaveSettingsHelper_GetWaveSettings_When_enabled__run_coupled_to_D_Flow_FM_core {
            get {
                return ResourceManager.GetString("WaveSettingsHelper_GetWaveSettings_When_enabled__run_coupled_to_D_Flow_FM_core", resourceCulture);
            }
        }
    }
}
