//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaShell.Plugins.DelftModels.WaterQualityModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeltaShell.Plugins.DelftModels.WaterQualityModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create working directory &apos;{0}&apos;. Working directory set to &apos;{1}&apos;.
        /// </summary>
        public static string Could_not_create_working_directory {
            get {
                return ResourceManager.GetString("Could_not_create_working_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0} contains wrong substance value: {1}.
        /// </summary>
        public static string DataTableCsvFileReader_CreateDataTableCsvContents_Line__0__contains_wrong_substance_value___1_ {
            get {
                return ResourceManager.GetString("DataTableCsvFileReader_CreateDataTableCsvContents_Line__0__contains_wrong_substan" +
                        "ce_value___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; already exists within the database. The file that is being imported will be renamed to &apos;{1}&apos;. Note that your results may be affected by the new import.
        /// </summary>
        public static string DataTableManager_WriteTableContentsToNewTextDocumentFromFile_File___0___already_exists_within_the_database__The_file_that_is_being_imported_will_be_renamed_to___1____Note_that_your_results_may_be_affected_by_the_new_import {
            get {
                return ResourceManager.GetString("DataTableManager_WriteTableContentsToNewTextDocumentFromFile_File___0___already_e" +
                        "xists_within_the_database__The_file_that_is_being_imported_will_be_renamed_to___" +
                        "1____Note_that_your_results_may_be_affected_by_the_new_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History file was not found at {0}..
        /// </summary>
        public static string DelwaqNetCdfHistoryFileReader_Read_History_file_not_found {
            get {
                return ResourceManager.GetString("DelwaqNetCdfHistoryFileReader_Read_History_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map file was not found at {0}..
        /// </summary>
        public static string DelwaqNetCdfMapFileReader_Map_file_not_found {
            get {
                return ResourceManager.GetString("DelwaqNetCdfMapFileReader_Map_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hydFile {
            get {
                object obj = ResourceManager.GetObject("hydFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters of type &lt;{0}&gt; can only filter on functions with value type &lt;{1}&gt;..
        /// </summary>
        public static string LazyMapFileFunctionStore_GetArgumentValues_Filters_of_type___0___can_only_filter_on_functions_with_value_type___1___ {
            get {
                return ResourceManager.GetString("LazyMapFileFunctionStore_GetArgumentValues_Filters_of_type___0___can_only_filter_" +
                        "on_functions_with_value_type___1___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time series data could not be read because variable with standard name &apos;{0}&apos; was not found in file {1}..
        /// </summary>
        internal static string NetCdfFileReaderHelper_GetDateTimes_Time_variable_not_found {
            get {
                return ResourceManager.GetString("NetCdfFileReaderHelper_GetDateTimes_Time_variable_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No working directory specified. Working directory set to &apos;{0}&apos;.
        /// </summary>
        public static string No_working_directory_specified {
            get {
                return ResourceManager.GetString("No_working_directory_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Observation {
            get {
                object obj = ResourceManager.GetObject("Observation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default output parameters.
        /// </summary>
        public static string SubFileImporter_DefaultOutputParameters_Name {
            get {
                return ResourceManager.GetString("SubFileImporter_DefaultOutputParameters_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sub file was imported: the selected sub file does not exist.
        /// </summary>
        public static string SubFileImporter_File_not_found {
            get {
                return ResourceManager.GetString("SubFileImporter_File_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub file successfully imported from: {0}.
        /// </summary>
        public static string SubFileImporter_Import_Sub_file_successfully_imported_from___0_ {
            get {
                return ResourceManager.GetString("SubFileImporter_Import_Sub_file_successfully_imported_from___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substance and Process Library.
        /// </summary>
        public static string SubFileImporter_Name_Substance_and_Process_Library {
            get {
                return ResourceManager.GetString("SubFileImporter_Name_Substance_and_Process_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to output parameters.
        /// </summary>
        public static string SubFileImporter_OutputParameters_Name {
            get {
                return ResourceManager.GetString("SubFileImporter_OutputParameters_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameters.
        /// </summary>
        public static string SubFileImporter_Parameters_Name {
            get {
                return ResourceManager.GetString("SubFileImporter_Parameters_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sub file was imported: no file selection was made.
        /// </summary>
        public static string SubFileImporter_Path_not_set {
            get {
                return ResourceManager.GetString("SubFileImporter_Path_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processes.
        /// </summary>
        public static string SubFileImporter_Processes_Name {
            get {
                return ResourceManager.GetString("SubFileImporter_Processes_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substance process library is not set.
        /// </summary>
        public static string SubFileImporter_Substance_process_library_not_set {
            get {
                return ResourceManager.GetString("SubFileImporter_Substance_process_library_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to substances.
        /// </summary>
        public static string SubFileImporter_Substances_Name {
            get {
                return ResourceManager.GetString("SubFileImporter_Substances_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rad.
        /// </summary>
        public static string SubstanceProcessLibrary_OutputParameters_Rad {
            get {
                return ResourceManager.GetString("SubstanceProcessLibrary_OutputParameters_Rad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar radiation (W/m2).
        /// </summary>
        public static string SubstanceProcessLibrary_OutputParameters_Rad_description {
            get {
                return ResourceManager.GetString("SubstanceProcessLibrary_OutputParameters_Rad_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surf.
        /// </summary>
        public static string SubstanceProcessLibrary_OutputParameters_Surf {
            get {
                return ResourceManager.GetString("SubstanceProcessLibrary_OutputParameters_Surf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal surface area of a DELWAQ segment (m2).
        /// </summary>
        public static string SubstanceProcessLibrary_OutputParameters_Surf_description {
            get {
                return ResourceManager.GetString("SubstanceProcessLibrary_OutputParameters_Surf_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        public static string SubstanceProcessLibrary_OutputParameters_Temp {
            get {
                return ResourceManager.GetString("SubstanceProcessLibrary_OutputParameters_Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water temperature (oC).
        /// </summary>
        public static string SubstanceProcessLibrary_OutputParameters_Temp_description {
            get {
                return ResourceManager.GetString("SubstanceProcessLibrary_OutputParameters_Temp_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string SubstanceProcessLibrary_OutputParameters_Volume {
            get {
                return ResourceManager.GetString("SubstanceProcessLibrary_OutputParameters_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume of computational cell (m3).
        /// </summary>
        public static string SubstanceProcessLibrary_OutputParameters_Volume_description {
            get {
                return ResourceManager.GetString("SubstanceProcessLibrary_OutputParameters_Volume_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 512 80 &apos;;&apos;
        ///;DELWAQ_VERSION_4.910                               ; Delwaq version number
        ///;PRINT_OUTPUT_OPTION_9                              ; Debug level
        ///
        ///; TEMPLATE FILE FOR WATER QUALITY CALCULATION
        ///; First input block
        ///&apos;Water quality calculation&apos;
        ///&apos; &apos;
        ///&apos; &apos;
        ///INCLUDE &apos;includes_deltashell/B1_t0.inc&apos;             ; From UI: Time stamp
        ///INCLUDE &apos;includes_deltashell/B1_sublist.inc&apos;        ; From UI: Substance list
        ///#1;
        ///
        ///;###############################################################################
        ///; Se [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TemplateInpFile {
            get {
                return ResourceManager.GetString("TemplateInpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 512 80 &apos;;&apos;
        ///;DELWAQ_VERSION_4.910                               ; Delwaq version number
        ///;PRINT_OUTPUT_OPTION_9                              ; Debug level
        ///
        ///; TEMPLATE FILE FOR WATER QUALITY CALCULATION
        ///; First input block
        ///&apos;Water quality calculation&apos;
        ///&apos; &apos;
        ///&apos; &apos;
        ///INCLUDE &apos;includes_deltashell/B1_t0.inc&apos;             ; From UI: Time stamp
        ///INCLUDE &apos;includes_deltashell/B1_sublist.inc&apos;        ; From UI: Substance list
        ///#1;
        ///
        ///;###############################################################################
        ///; Se [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TemplateInpFileHybrid {
            get {
                return ResourceManager.GetString("TemplateInpFileHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000 80 &apos;;&apos;
        ///;DELWAQ_VERSION_4.910                               ; Delwaq version number
        ///;PRINT_OUTPUT_OPTION_4                              ; Debug level
        ///
        ///; TEMPLATE FILE FOR WATER QUALITY CALCULATION
        ///; First input block
        ///&apos;Water quality calculation&apos;
        ///&apos; &apos;
        ///&apos; &apos;
        ///INCLUDE &apos;includes_deltashell/B1_t0.inc&apos;             ; From UI: Time stamp
        ///INCLUDE &apos;includes_deltashell/B1_sublist.inc&apos;        ; From UI: Substance list
        ///#1;
        ///
        ///;###############################################################################
        ///; S [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TemplateInpFileNew {
            get {
                return ResourceManager.GetString("TemplateInpFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read output files : {0}.
        /// </summary>
        public static string WaqFileBasedProcessor_AddOutput_Could_not_read_output_files {
            get {
                return ResourceManager.GetString("WaqFileBasedProcessor_AddOutput_Could_not_read_output_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add output because work directory is empty..
        /// </summary>
        public static string WaqFileBasedProcessor_AddOutput_work_directory_is_empty {
            get {
                return ResourceManager.GetString("WaqFileBasedProcessor_AddOutput_work_directory_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time steps are inconsistent for the data related to variable {0}..
        /// </summary>
        public static string WaqHistoryFileParser_SetDataOnObservationVariableOutput_Time_steps_are_inconsistent_for_the_data_related_to_variable__0__ {
            get {
                return ResourceManager.GetString("WaqHistoryFileParser_SetDataOnObservationVariableOutput_Time_steps_are_inconsiste" +
                        "nt_for_the_data_related_to_variable__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid file was not found at {0}..
        /// </summary>
        public static string WaqInitializationDataVerifier_Grid_file_was_not_found {
            get {
                return ResourceManager.GetString("WaqInitializationDataVerifier_Grid_file_was_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &lt;{0}&gt; does not meet supported UGRID 1.0 or newer standard. Your NetCDF output file may not be properly viewed in the User Interface..
        /// </summary>
        public static string WaqInitializationDataVerifier_GridFile_does_not_meet_supported_UGRID_1_0 {
            get {
                return ResourceManager.GetString("WaqInitializationDataVerifier_GridFile does_not_meet_supported_UGRID_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} not found in the path {1}. No validations will be done for the coefficients..
        /// </summary>
        public static string WaqProcessesRules_ReadValidationCsv_File__0__not_found_in_the_path__1___No_validations_will_be_done_for_the_coefficients_ {
            get {
                return ResourceManager.GetString("WaqProcessesRules_ReadValidationCsv_File__0__not_found_in_the_path__1___No_valida" +
                        "tions_will_be_done_for_the_coefficients_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading file {0}: check the textual output files for more information..
        /// </summary>
        public static string WaqProcessorHelper_ParseHisFileData_An_error_occurred_while_reading_file {
            get {
                return ResourceManager.GetString("WaqProcessorHelper_ParseHisFileData_An_error_occurred_while_reading_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not recognized as a valid format for history files: {0}.
        /// </summary>
        public static string WaqProcessorHelper_ParseHisFileData_Invalid_file_format {
            get {
                return ResourceManager.GetString("WaqProcessorHelper_ParseHisFileData_Invalid_file_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rules found for {0}..
        /// </summary>
        public static string WaqValidationRulesExtension_ConstantProcessWithinRuleLimits_No_rules_found_for__0__ {
            get {
                return ResourceManager.GetString("WaqValidationRulesExtension_ConstantProcessWithinRuleLimits_No_rules_found_for__0" +
                        "__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process coefficient {0} (value:{1}) {2}{3}..
        /// </summary>
        public static string WaqValidationRulesExtension_GetWaqProcessValidationRuleAsString_Process_coefficient__0___value__1____2__3__ {
            get {
                return ResourceManager.GetString("WaqValidationRulesExtension_GetWaqProcessValidationRuleAsString_Process_coefficie" +
                        "nt__0___value__1____2__3__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Constant.
        /// </summary>
        public static string WaterQualityBoundaryData_Constant_post_fix {
            get {
                return ResourceManager.GetString("WaterQualityBoundaryData_Constant_post_fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant.
        /// </summary>
        public static string WaterQualityBoundaryData_SetConstFunction_Constant {
            get {
                return ResourceManager.GetString("WaterQualityBoundaryData_SetConstFunction_Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substance.
        /// </summary>
        public static string WaterQualityBoundaryData_SetConstFunction_Substance {
            get {
                return ResourceManager.GetString("WaterQualityBoundaryData_SetConstFunction_Substance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Time series.
        /// </summary>
        public static string WaterQualityBoundaryData_Time_series_post_fix {
            get {
                return ResourceManager.GetString("WaterQualityBoundaryData_Time_series_post_fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &lt;{0}&gt; does not meet supported UGRID 1.0 or newer standard..
        /// </summary>
        public static string WaterQualityModel_File_does_not_meet_supported_UGRID_1_0_or_newer_standard {
            get {
                return ResourceManager.GetString("WaterQualityModel_File_does_not_meet_supported_UGRID_1_0_or_newer_standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process coefficient {0} has been updated with the latest Hydrodynamic data file..
        /// </summary>
        public static string WaterQualityModel_HandleNewHydroDynamicsFunctionDataSet_The_process_coefficient__0__has_been_updated_with_the_latest_Hydrodynamic_data_file_ {
            get {
                return ResourceManager.GetString("WaterQualityModel_HandleNewHydroDynamicsFunctionDataSet_The_process_coefficient__" +
                        "0__has_been_updated_with_the_latest_Hydrodynamic_data_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinate system of the model: {0} has been set to {1}.
        /// </summary>
        public static string WaterQualityModel_ImportHydroData_The_coordinate_system_of_the_model___0__has_been_set_to__1_ {
            get {
                return ResourceManager.GetString("WaterQualityModel_ImportHydroData_The_coordinate_system_of_the_model___0__has_bee" +
                        "n_set_to__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output timers ({0}) have been synchronized to match the Simulation {0} ({1})..
        /// </summary>
        public static string WaterQualityModel_LogSynchronizedTimer_Output_timers___0___have_been_synchronized_to_match_the_Simulation__0____1___ {
            get {
                return ResourceManager.GetString("WaterQualityModel_LogSynchronizedTimer_Output_timers___0___have_been_synchronized" +
                        "_to_match_the_Simulation__0____1___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize pre-processor.{0}Please look at the List file for more information.{0}List file found in: Project view -&gt; Output -&gt; List file.{0} {1}.
        /// </summary>
        public static string WaterQualityModel_OnInitializeCore_Failed_to_initialize_pre_processor__0_Please_look_at_the_List_file_for_more_information__0_List_file_found_in__Project_view____Output____List_file__0___1_ {
            get {
                return ResourceManager.GetString("WaterQualityModel_OnInitializeCore_Failed_to_initialize_pre_processor__0_Please_l" +
                        "ook_at_the_List_file_for_more_information__0_List_file_found_in__Project_view___" +
                        "_Output____List_file__0___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linked flow.
        /// </summary>
        public static string WaterQualityModelValidate_CheckTimers_Linked_flow {
            get {
                return ResourceManager.GetString("WaterQualityModelValidate_CheckTimers_Linked_flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} period of the model ({1} - {2}) should be bounded by the {3} period of the {4}model ({5} - {6}).
        /// </summary>
        public static string WaterQualityModelValidate_CheckTimers_Period_should_be_correctly_bounded {
            get {
                return ResourceManager.GetString("WaterQualityModelValidate_CheckTimers_Period_should_be_correctly_bounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} start time cannot be after the {0} stop time.
        /// </summary>
        public static string WaterQualityModelValidate_CheckTimers_Start_time_cannot_be_after_stop_time {
            get {
                return ResourceManager.GetString("WaterQualityModelValidate_CheckTimers_Start_time_cannot_be_after_stop_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} start time must be expressed as &quot;{1} + N * {2}&quot; (N must be an integer).
        /// </summary>
        public static string WaterQualityModelValidate_CheckTimers_Start_time_must_be_aligned_with_sample {
            get {
                return ResourceManager.GetString("WaterQualityModelValidate_CheckTimers_Start_time_must_be_aligned_with_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} stop time must be expressed as &quot;{1} + N * {2}&quot; (N must be an integer).
        /// </summary>
        public static string WaterQualityModelValidate_CheckTimers_Stop_time_must_be_aligned_with_sample {
            get {
                return ResourceManager.GetString("WaterQualityModelValidate_CheckTimers_Stop_time_must_be_aligned_with_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} time step cannot be larger than the difference between the {0} start and stop time ({1}).
        /// </summary>
        public static string WaterQualityModelValidate_CheckTimers_Time_step_cannot_be_greater_than_difference_start_and_stop_time {
            get {
                return ResourceManager.GetString("WaterQualityModelValidate_CheckTimers_Time_step_cannot_be_greater_than_difference" +
                        "_start_and_stop_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} time step must be greater than 0.
        /// </summary>
        public static string WaterQualityModelValidate_CheckTimers_Time_step_must_be_greater_than_0 {
            get {
                return ResourceManager.GetString("WaterQualityModelValidate_CheckTimers_Time_step_must_be_greater_than_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} time step must be an integer positive non-zero multiple {1}of the {2} time step ({3}).
        /// </summary>
        public static string WaterQualityModelValidate_CheckTimers_Time_step_must_be_integer_positive_non_zero_multiple {
            get {
                return ResourceManager.GetString("WaterQualityModelValidate_CheckTimers_Time_step_must_be_integer_positive_non_zero" +
                        "_multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or the result of an integer division.
        /// </summary>
        public static string WaterQualityModelValidate_CheckTimers_Time_step_must_be_result_of_integer_division {
            get {
                return ResourceManager.GetString("WaterQualityModelValidate_CheckTimers_Time_step_must_be_result_of_integer_divisio" +
                        "n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timers for {0} are not equal to the simulation period of the model ({1}, {2}). Please verify that they overlap with the simulation period..
        /// </summary>
        public static string WaterQualityModelValidator_CheckTimers_Timers_for__0__are_not_equal_to_the_simulation_period_of_the_model___1____2____Please_verify_that_they_overlap_with_the_simulation_period_ {
            get {
                return ResourceManager.GetString("WaterQualityModelValidator_CheckTimers_Timers_for__0__are_not_equal_to_the_simula" +
                        "tion_period_of_the_model___1____2____Please_verify_that_they_overlap_with_the_si" +
                        "mulation_period_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hyd file with location {0} doesn&apos;t exist..
        /// </summary>
        public static string WaterQualityModelValidator_hyd_file_doesnt_exist {
            get {
                return ResourceManager.GetString("WaterQualityModelValidator_hyd_file_doesnt_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No process coefficient rules have been loaded. Therefore they cannot be validated..
        /// </summary>
        public static string WaterQualityModelValidator_ValidateProcessCoefficients_No_process_coefficient_rules_have_been_loaded__Therefore_they_cannot_be_validated_ {
            get {
                return ResourceManager.GetString("WaterQualityModelValidator_ValidateProcessCoefficients_No_process_coefficient_rul" +
                        "es_have_been_loaded__Therefore_they_cannot_be_validated_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Substance library does not contain the given parameter {0}..
        /// </summary>
        public static string WaterQualityModelValidator_ValidateProcessCoefficients_The_Substance_library_does_not_contain_the_given_parameter__0__ {
            get {
                return ResourceManager.GetString("WaterQualityModelValidator_ValidateProcessCoefficients_The_Substance_library_does" +
                        "_not_contain_the_given_parameter__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap weight {
            get {
                object obj = ResourceManager.GetObject("weight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
