; number of active and inactive substances
22             0
        ; active substances
1            'Continuity' ;Continuity
2            'NH4' ;Ammonium (NH4)
3            'NO3' ;Nitrate (NO3)
4            'PO4' ;Ortho-Phosphate (PO4)
5            'Si' ;dissolved Silica (Si)
6            'Opal' ;Opal-Si
7            'POC1' ;POC1 (fast decomposing fraction)
8            'PON1' ;PON1 (fast decomposing fraction)
9            'POP1' ;POP1 (fast decomposing fraction)
10            'POS1' ;POS1 (fast decomposing fraction)
11            'APHANIZO_E' ;APHANIZO energy type
12            'APHANIZO_N' ;APHANIZO nitrogen type
13            'APHANIZO_P' ;APHANIZO phosphorus type
14            'FDIATOMS_E' ;Fresh DIATOMS energy type
15            'FDIATOMS_P' ;Fresh DIATOMS P/Si type
16            'FFLAGELA' ;Fresh FLAGELAT energy type
17            'GREENS_E' ;GREENS energy type
18            'GREENS_N' ;GREENS nitrogen type
19            'GREENS_P' ;GREENS phosphorus type
20            'OSCILAT_E' ;OSCILAT energy type
21            'OSCILAT_N' ;OSCILAT nitrogen type
22            'OSCILAT_P' ;OSCILAT phosphorus type
        ; passive substances
