substance 'AAP' active
   description        'adsorbed ortho phosphate'
   concentration-unit '(gP/m3)'
   waste-load-unit    '-'
end-substance
substance 'DetC' active
   description        'Detritus Carbon  (DetC)'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'DetN' active
   description        'Detritus Nitrogen (DetN)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'DetP' active
   description        'Detritus Phosphorus (DetP)'
   concentration-unit '(gP/m3)'
   waste-load-unit    '-'
end-substance
substance 'DetSi' active
   description        'Detritus Silica (DetSi)'
   concentration-unit '(gSi/m3)'
   waste-load-unit    '-'
end-substance
substance 'NH4' active
   description        'Ammonium (NH4)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'NO3' active
   description        'Nitrate (NO3)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'OOC' active
   description        'Other Organic Carbon (OOC)'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'OON' active
   description        'Other Organic Nitrogen (OON)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'OOP' active
   description        'Other Organic Phosphorus (OOP)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'OOSi' active
   description        'Other Organic Silica (OOSi)'
   concentration-unit '(gSi/m3)'
   waste-load-unit    '-'
end-substance
substance 'PAP' active
   description        'Adsorbed ortho-phosphate (irreversible)'
   concentration-unit '(gP/m3)'
   waste-load-unit    '-'
end-substance
substance 'PO4' active
   description        'Ortho-Phosphate (PO4)'
   concentration-unit '(gP/m3)'
   waste-load-unit    '-'
end-substance
substance 'Si' active
   description        'dissolved Silica (Si)'
   concentration-unit '(gSi/m3)'
   waste-load-unit    '-'
end-substance
substance 'FDIATOMS_E' active
   description        'Fresh DIATOMS energy type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'FDIATOMS_P' active
   description        'Fresh DIATOMS P/Si type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'GREENS_E' active
   description        'GREENS energy type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'GREENS_P' active
   description        'GREENS phosphorus type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'MDIATOMS_E' active
   description        'Marine DIATOMS energy type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'MDIATOMS_N' active
   description        'Marine DIATOMS nitrogen type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'MDIATOMS_P' active
   description        'Marine DIATOMS phosphorus type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'MFLAGELA_E' active
   description        'Marine FLAGELAT energy type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'MFLAGELA_P' active
   description        'Marine FLAGELAT phosphorus typ'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'MICROCYS_E' active
   description        'MICROCYS energy type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'MICROCYS_N' active
   description        'MICROCYS nitrogen type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'MICROCYS_P' active
   description        'MICROCYS phosphorus type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'PHAEOCYS_E' active
   description        'Phaeocystis energy type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'PHAEOCYS_N' active
   description        'Phaeocystis nitrogen type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'PHAEOCYS_P' active
   description        'Phaeocystis phosphorus type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'OXY' active
   description        'Dissolved Oxygen'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'Cl' active
   description        'Chloride'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'Continuity' active
   description        'Continuity'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'cTR1' active
   description        'conservative tracer source 1'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'cTR2' active
   description        'conservative tracer source 2'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'cTR3' active
   description        'conservative tracer source 3'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'dTR1' active
   description        'decayable tracer source 1'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'dTR2' active
   description        'decayable tracer source 2'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'dTR3' active
   description        'decayable tracer source 3'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'IM1' active
   description        'inorganic matter (IM1)'
   concentration-unit '(gDM/m3)'
   waste-load-unit    '-'
end-substance
substance 'IM2' active
   description        'inorganic matter (IM2)'
   concentration-unit '(gDM/m3)'
   waste-load-unit    '-'
end-substance
substance 'IM3' active
   description        'inorganic matter (IM3)'
   concentration-unit '(gDM/m3)'
   waste-load-unit    '-'
end-substance
substance 'AAPS1' inactive
   description        'adsorbed O-PO4 in layer S1'
   concentration-unit '(gP)'
   waste-load-unit    '-'
end-substance
substance 'DetCS1' inactive
   description        'DetC in layer S1'
   concentration-unit '(gC)'
   waste-load-unit    '-'
end-substance
substance 'DetNS1' inactive
   description        'DetN in layer S1'
   concentration-unit '(gN)'
   waste-load-unit    '-'
end-substance
substance 'DetPS1' inactive
   description        'DetP in layer S1'
   concentration-unit '(gP)'
   waste-load-unit    '-'
end-substance
substance 'DetSiS1' inactive
   description        'DetSi in layer S1'
   concentration-unit '(gSi)'
   waste-load-unit    '-'
end-substance
substance 'OOCS1' inactive
   description        'OOC in layer S1'
   concentration-unit '(gC)'
   waste-load-unit    '-'
end-substance
substance 'OONS1' inactive
   description        'OON in layer S1'
   concentration-unit '(gN)'
   waste-load-unit    '-'
end-substance
substance 'OOPS1' inactive
   description        'OOP in layer S1'
   concentration-unit '(gP)'
   waste-load-unit    '-'
end-substance
substance 'OOSiS1' inactive
   description        'OOSi in layer S1'
   concentration-unit '(gSi)'
   waste-load-unit    '-'
end-substance
substance 'IM1S1' inactive
   description        'IM1 in layer S1'
   concentration-unit '(gDM)'
   waste-load-unit    '-'
end-substance
substance 'IM2S1' inactive
   description        'IM2 in layer S1'
   concentration-unit '(gDM)'
   waste-load-unit    '-'
end-substance
substance 'IM3S1' inactive
   description        'IM3 in layer S1'
   concentration-unit '(gDM)'
   waste-load-unit    '-'
end-substance
parameter 'SWAdsP'
   description   'switch PO4 adsorption <0=Kd|1=Langmuir|2=pHdep>'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'KdPO4AAP'
   description   'distrib. coeff. (-) or ads. eq. const.'
   unit          '(m3/gP)'
   value          0.1000E+00
end-parameter
parameter 'RcAdPO4AAP'
   description   'adsorption rate PO4 --> AAP'
   unit          '(1/d)'
   value          0.1000E+01
end-parameter
parameter 'RcAAPS1'
   description   'first-order AAP desorption rate in layer S1'
   unit          '(1/d)'
   value          0.1000E-01
end-parameter
parameter 'TcAAPS1'
   description   'temperature coefficient desorption in sediment'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'CTMinAAPS'
   description   'critical temperature for desorption'
   unit          '(oC)'
   value         -0.1000E+02
end-parameter
parameter 'TimMultBl'
   description   'ratio bloom/delwaq time step'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'BloomDepth'
   description   'average depth over Bloom time step'
   unit          '(m)'
   value          0.0000E+00
end-parameter
parameter 'ThrAlgNH4'
   description   'threshold concentration uptake ammonium'
   unit          '(gN/m3)'
   value          0.0000E+00
end-parameter
parameter 'ThrAlgNO3'
   description   'threshold concentration uptake nitrate'
   unit          '(gN/m3)'
   value          0.0000E+00
end-parameter
parameter 'ThrAlgPO4'
   description   'threshold concentration uptake phosphate'
   unit          '(gP/m3)'
   value          0.0000E+00
end-parameter
parameter 'ThrAlgSi'
   description   'threshold concentration uptake silicium'
   unit          '(gSi/m3)'
   value          0.0000E+00
end-parameter
parameter 'SWBloomOut'
   description   'switch on BLOOM output (0=no,1=yes)'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'FrAutFDI_E'
   description   'frac. mort. algae  dissolved as nutrients FDIATOMS_E'
   unit          '(-)'
   value          0.3500E+00
end-parameter
parameter 'FrAutFDI_P'
   description   'frac. mort. algae  dissolved as nutrients FDIATOMS_P'
   unit          '(-)'
   value          0.3500E+00
end-parameter
parameter 'FrAutGRE_E'
   description   'frac. mort. algae  dissolved as nutrients GREENS_E'
   unit          '(-)'
   value          0.3500E+00
end-parameter
parameter 'FrAutGRE_P'
   description   'frac. mort. algae  dissolved as nutrients GREENS_P'
   unit          '(-)'
   value          0.3500E+00
end-parameter
parameter 'FrAutMIC_E'
   description   'frac. mort. algae  dissolved as nutrients MICROCYS_E'
   unit          '(-)'
   value          0.3500E+00
end-parameter
parameter 'FrAutMIC_N'
   description   'frac. mort. algae  dissolved as nutrients MICROCYS_N'
   unit          '(-)'
   value          0.3500E+00
end-parameter
parameter 'FrAutMIC_P'
   description   'frac. mort. algae  dissolved as nutrients MICROCYS_P'
   unit          '(-)'
   value          0.3500E+00
end-parameter
parameter 'FrAutMDI_E'
   description   'frac. mort. algae  dissolved as nutrients MDIATOMS_E'
   unit          '(-)'
   value          0.3000E+00
end-parameter
parameter 'FrAutMDI_N'
   description   'frac. mort. algae  dissolved as nutrients MDIATOMS_N'
   unit          '(-)'
   value          0.3000E+00
end-parameter
parameter 'FrAutMDI_P'
   description   'frac. mort. algae  dissolved as nutrients MDIATOMS_P'
   unit          '(-)'
   value          0.3000E+00
end-parameter
parameter 'FrAutMFL_E'
   description   'frac. mort. algae  dissolved as nutrients MFLAGELA_E'
   unit          '(-)'
   value          0.3000E+00
end-parameter
parameter 'FrAutMFL_P'
   description   'frac. mort. algae  dissolved as nutrients MFLAGELA_P'
   unit          '(-)'
   value          0.3000E+00
end-parameter
parameter 'FrAutPHA_E'
   description   'frac. mort. algae  dissolved as nutrients PHAEOCYS_E'
   unit          '(-)'
   value          0.3000E+00
end-parameter
parameter 'FrAutPHA_N'
   description   'frac. mort. algae  dissolved as nutrients PHAEOCYS_N'
   unit          '(-)'
   value          0.3000E+00
end-parameter
parameter 'FrAutPHA_P'
   description   'frac. mort. algae  dissolved as nutrients PHAEOCYS_P'
   unit          '(-)'
   value          0.3000E+00
end-parameter
parameter 'FrDetFDI_E'
   description   'frac. mort. algae  detritus production FDIATOMS_E'
   unit          '(-)'
   value          0.5500E+00
end-parameter
parameter 'FrDetFDI_P'
   description   'frac. mort. algae  detritus production FDIATOMS_P'
   unit          '(-)'
   value          0.5500E+00
end-parameter
parameter 'FrDetGRE_E'
   description   'frac. mort. algae  detritus production GREENS_E'
   unit          '(-)'
   value          0.5500E+00
end-parameter
parameter 'FrDetGRE_P'
   description   'frac. mort. algae  detritus production GREENS_P'
   unit          '(-)'
   value          0.5500E+00
end-parameter
parameter 'FrDetMIC_E'
   description   'frac. mort. algae  detritus production MICROCYS_E'
   unit          '(-)'
   value          0.6200E+00
end-parameter
parameter 'FrDetMIC_N'
   description   'frac. mort. algae  detritus production MICROCYS_N'
   unit          '(-)'
   value          0.6200E+00
end-parameter
parameter 'FrDetMIC_P'
   description   'frac. mort. algae  detritus production MICROCYS_P'
   unit          '(-)'
   value          0.6200E+00
end-parameter
parameter 'FrDetMDI_E'
   description   'frac. mort. algae  detritus production MDIATOMS_E'
   unit          '(-)'
   value          0.7000E+00
end-parameter
parameter 'FrDetMDI_N'
   description   'frac. mort. algae  detritus production MDIATOMS_N'
   unit          '(-)'
   value          0.7000E+00
end-parameter
parameter 'FrDetMDI_P'
   description   'frac. mort. algae  detritus production MDIATOMS_P'
   unit          '(-)'
   value          0.7000E+00
end-parameter
parameter 'FrDetMFL_E'
   description   'frac. mort. algae  detritus production MFLAGELA_E'
   unit          '(-)'
   value          0.7000E+00
end-parameter
parameter 'FrDetMFL_P'
   description   'frac. mort. algae  detritus production MFLAGELA_P'
   unit          '(-)'
   value          0.7000E+00
end-parameter
parameter 'FrDetPHA_E'
   description   'frac. mort. algae  detritus production PHAEOCYS_E'
   unit          '(-)'
   value          0.7000E+00
end-parameter
parameter 'FrDetPHA_N'
   description   'frac. mort. algae  detritus production PHAEOCYS_N'
   unit          '(-)'
   value          0.7000E+00
end-parameter
parameter 'FrDetPHA_P'
   description   'frac. mort. algae  detritus production PHAEOCYS_P'
   unit          '(-)'
   value          0.7000E+00
end-parameter
parameter 'ExtVlFDI_E'
   description   'extinction coeff. visible light by algae FDIATOMS_E'
   unit          '(m2/gC)'
   value          0.2700E+00
end-parameter
parameter 'ExtVlFDI_P'
   description   'extinction coeff. visible light by algae FDIATOMS_P'
   unit          '(m2/gC)'
   value          0.1875E+00
end-parameter
parameter 'ExtVlGRE_E'
   description   'extinction coeff. visible light by algae GREENS_E'
   unit          '(m2/gC)'
   value          0.2250E+00
end-parameter
parameter 'ExtVlGRE_P'
   description   'extinction coeff. visible light by algae GREENS_P'
   unit          '(m2/gC)'
   value          0.1875E+00
end-parameter
parameter 'ExtVlMIC_E'
   description   'extinction coeff. visible light by algae MICROCYS_E'
   unit          '(m2/gC)'
   value          0.4000E+00
end-parameter
parameter 'ExtVlMIC_N'
   description   'extinction coeff. visible light by algae MICROCYS_N'
   unit          '(m2/gC)'
   value          0.2875E+00
end-parameter
parameter 'ExtVlMIC_P'
   description   'extinction coeff. visible light by algae MICROCYS_P'
   unit          '(m2/gC)'
   value          0.2875E+00
end-parameter
parameter 'ExtVlMDI_E'
   description   'extinction coeff. visible light by algae MDIATOMS_E'
   unit          '(m2/gC)'
   value          0.2400E+00
end-parameter
parameter 'ExtVlMDI_N'
   description   'extinction coeff. visible light by algae MDIATOMS_N'
   unit          '(m2/gC)'
   value          0.2100E+00
end-parameter
parameter 'ExtVlMDI_P'
   description   'extinction coeff. visible light by algae MDIATOMS_P'
   unit          '(m2/gC)'
   value          0.2100E+00
end-parameter
parameter 'ExtVlMFL_E'
   description   'extinction coeff. visible light by algae MFLAGELA_E'
   unit          '(m2/gC)'
   value          0.2500E+00
end-parameter
parameter 'ExtVlMFL_P'
   description   'extinction coeff. visible light by algae MFLAGELA_P'
   unit          '(m2/gC)'
   value          0.2250E+00
end-parameter
parameter 'ExtVlPHA_E'
   description   'extinction coeff. visible light by algae PHAEOCYS_E'
   unit          '(m2/gC)'
   value          0.4500E+00
end-parameter
parameter 'ExtVlPHA_N'
   description   'extinction coeff. visible light by algae PHAEOCYS_N'
   unit          '(m2/gC)'
   value          0.4125E+00
end-parameter
parameter 'ExtVlPHA_P'
   description   'extinction coeff. visible light by algae PHAEOCYS_P'
   unit          '(m2/gC)'
   value          0.4125E+00
end-parameter
parameter 'DMCFFDI_E'
   description   'DM:C ratio algae FDIATOMS_E'
   unit          '(gDM/gC)'
   value          0.3000E+01
end-parameter
parameter 'DMCFFDI_P'
   description   'DM:C ratio algae FDIATOMS_P'
   unit          '(gDM/gC)'
   value          0.2500E+01
end-parameter
parameter 'DMCFGRE_E'
   description   'DM:C ratio algae GREENS_E'
   unit          '(gDM/gC)'
   value          0.2500E+01
end-parameter
parameter 'DMCFGRE_P'
   description   'DM:C ratio algae GREENS_P'
   unit          '(gDM/gC)'
   value          0.2500E+01
end-parameter
parameter 'DMCFMIC_E'
   description   'DM:C ratio algae MICROCYS_E'
   unit          '(gDM/gC)'
   value          0.2500E+01
end-parameter
parameter 'DMCFMIC_N'
   description   'DM:C ratio algae MICROCYS_N'
   unit          '(gDM/gC)'
   value          0.2500E+01
end-parameter
parameter 'DMCFMIC_P'
   description   'DM:C ratio algae MICROCYS_P'
   unit          '(gDM/gC)'
   value          0.2500E+01
end-parameter
parameter 'DMCFMDI_E'
   description   'DM:C ratio algae MDIATOMS_E'
   unit          '(gDM/gC)'
   value          0.3000E+01
end-parameter
parameter 'DMCFMDI_N'
   description   'DM:C ratio algae MDIATOMS_N'
   unit          '(gDM/gC)'
   value          0.3000E+01
end-parameter
parameter 'DMCFMDI_P'
   description   'DM:C ratio algae MDIATOMS_P'
   unit          '(gDM/gC)'
   value          0.3000E+01
end-parameter
parameter 'DMCFMFL_E'
   description   'DM:C ratio algae MFLAGELA_E'
   unit          '(gDM/gC)'
   value          0.2500E+01
end-parameter
parameter 'DMCFMFL_P'
   description   'DM:C ratio algae MFLAGELA_P'
   unit          '(gDM/gC)'
   value          0.2500E+01
end-parameter
parameter 'DMCFPHA_E'
   description   'DM:C ratio algae PHAEOCYS_E'
   unit          '(gDM/gC)'
   value          0.2500E+01
end-parameter
parameter 'DMCFPHA_N'
   description   'DM:C ratio algae PHAEOCYS_N'
   unit          '(gDM/gC)'
   value          0.2500E+01
end-parameter
parameter 'DMCFPHA_P'
   description   'DM:C ratio algae PHAEOCYS_P'
   unit          '(gDM/gC)'
   value          0.2500E+01
end-parameter
parameter 'NCRFDI_E'
   description   'N:C ratio per algae type FDIATOMS_E'
   unit          '(gN/gC)'
   value          0.2100E+00
end-parameter
parameter 'NCRFDI_P'
   description   'N:C ratio per algae type FDIATOMS_P'
   unit          '(gN/gC)'
   value          0.1880E+00
end-parameter
parameter 'NCRGRE_E'
   description   'N:C ratio per algae type GREENS_E'
   unit          '(gN/gC)'
   value          0.2750E+00
end-parameter
parameter 'NCRGRE_P'
   description   'N:C ratio per algae type GREENS_P'
   unit          '(gN/gC)'
   value          0.2000E+00
end-parameter
parameter 'NCRMIC_E'
   description   'N:C ratio per algae type MICROCYS_E'
   unit          '(gN/gC)'
   value          0.2250E+00
end-parameter
parameter 'NCRMIC_N'
   description   'N:C ratio per algae type MICROCYS_N'
   unit          '(gN/gC)'
   value          0.1130E+00
end-parameter
parameter 'NCRMIC_P'
   description   'N:C ratio per algae type MICROCYS_P'
   unit          '(gN/gC)'
   value          0.1750E+00
end-parameter
parameter 'NCRMDI_E'
   description   'N:C ratio per algae type MDIATOMS_E'
   unit          '(gN/gC)'
   value          0.2550E+00
end-parameter
parameter 'NCRMDI_N'
   description   'N:C ratio per algae type MDIATOMS_N'
   unit          '(gN/gC)'
   value          0.7000E-01
end-parameter
parameter 'NCRMDI_P'
   description   'N:C ratio per algae type MDIATOMS_P'
   unit          '(gN/gC)'
   value          0.1050E+00
end-parameter
parameter 'NCRMFL_E'
   description   'N:C ratio per algae type MFLAGELA_E'
   unit          '(gN/gC)'
   value          0.2000E+00
end-parameter
parameter 'NCRMFL_P'
   description   'N:C ratio per algae type MFLAGELA_P'
   unit          '(gN/gC)'
   value          0.1130E+00
end-parameter
parameter 'NCRPHA_E'
   description   'N:C ratio per algae type PHAEOCYS_E'
   unit          '(gN/gC)'
   value          0.1875E+00
end-parameter
parameter 'NCRPHA_N'
   description   'N:C ratio per algae type PHAEOCYS_N'
   unit          '(gN/gC)'
   value          0.1350E+00
end-parameter
parameter 'NCRPHA_P'
   description   'N:C ratio per algae type PHAEOCYS_P'
   unit          '(gN/gC)'
   value          0.1875E+00
end-parameter
parameter 'PCRFDI_E'
   description   'P:C ratio per algae type FDIATOMS_E'
   unit          '(gP/gC)'
   value          0.1800E-01
end-parameter
parameter 'PCRFDI_P'
   description   'P:C ratio per algae type FDIATOMS_P'
   unit          '(gP/gC)'
   value          0.1130E-01
end-parameter
parameter 'PCRGRE_E'
   description   'P:C ratio per algae type GREENS_E'
   unit          '(gP/gC)'
   value          0.2380E-01
end-parameter
parameter 'PCRGRE_P'
   description   'P:C ratio per algae type GREENS_P'
   unit          '(gP/gC)'
   value          0.1250E-01
end-parameter
parameter 'PCRMIC_E'
   description   'P:C ratio per algae type MICROCYS_E'
   unit          '(gP/gC)'
   value          0.3000E-01
end-parameter
parameter 'PCRMIC_N'
   description   'P:C ratio per algae type MICROCYS_N'
   unit          '(gP/gC)'
   value          0.2750E-01
end-parameter
parameter 'PCRMIC_P'
   description   'P:C ratio per algae type MICROCYS_P'
   unit          '(gP/gC)'
   value          0.2250E-01
end-parameter
parameter 'PCRMDI_E'
   description   'P:C ratio per algae type MDIATOMS_E'
   unit          '(gP/gC)'
   value          0.3150E-01
end-parameter
parameter 'PCRMDI_N'
   description   'P:C ratio per algae type MDIATOMS_N'
   unit          '(gP/gC)'
   value          0.1200E-01
end-parameter
parameter 'PCRMDI_P'
   description   'P:C ratio per algae type MDIATOMS_P'
   unit          '(gP/gC)'
   value          0.1000E-01
end-parameter
parameter 'PCRMFL_E'
   description   'P:C ratio per algae type MFLAGELA_E'
   unit          '(gP/gC)'
   value          0.2000E-01
end-parameter
parameter 'PCRMFL_P'
   description   'P:C ratio per algae type MFLAGELA_P'
   unit          '(gP/gC)'
   value          0.7000E-02
end-parameter
parameter 'PCRPHA_E'
   description   'P:C ratio per algae type PHAEOCYS_E'
   unit          '(gP/gC)'
   value          0.2250E-01
end-parameter
parameter 'PCRPHA_N'
   description   'P:C ratio per algae type PHAEOCYS_N'
   unit          '(gP/gC)'
   value          0.2125E-01
end-parameter
parameter 'PCRPHA_P'
   description   'P:C ratio per algae type PHAEOCYS_P'
   unit          '(gP/gC)'
   value          0.1625E-01
end-parameter
parameter 'SCRFDI_E'
   description   'Si:C ratio per algae type FDIATOMS_E'
   unit          '(gSi/gC)'
   value          0.6600E+00
end-parameter
parameter 'SCRFDI_P'
   description   'Si:C ratio per algae type FDIATOMS_P'
   unit          '(gSi/gC)'
   value          0.5500E+00
end-parameter
parameter 'SCRGRE_E'
   description   'Si:C ratio per algae type GREENS_E'
   unit          '(gSi/gC)'
   value          0.1800E-02
end-parameter
parameter 'SCRGRE_P'
   description   'Si:C ratio per algae type GREENS_P'
   unit          '(gSi/gC)'
   value          0.1800E-02
end-parameter
parameter 'SCRMIC_E'
   description   'Si:C ratio per algae type MICROCYS_E'
   unit          '(gSi/gC)'
   value          0.1800E-02
end-parameter
parameter 'SCRMIC_N'
   description   'Si:C ratio per algae type MICROCYS_N'
   unit          '(gSi/gC)'
   value          0.1800E-02
end-parameter
parameter 'SCRMIC_P'
   description   'Si:C ratio per algae type MICROCYS_P'
   unit          '(gSi/gC)'
   value          0.1800E-02
end-parameter
parameter 'SCRMDI_E'
   description   'Si:C ratio per algae type MDIATOMS_E'
   unit          '(gSi/gC)'
   value          0.4470E+00
end-parameter
parameter 'SCRMDI_N'
   description   'Si:C ratio per algae type MDIATOMS_N'
   unit          '(gSi/gC)'
   value          0.2830E+00
end-parameter
parameter 'SCRMDI_P'
   description   'Si:C ratio per algae type MDIATOMS_P'
   unit          '(gSi/gC)'
   value          0.1520E+00
end-parameter
parameter 'SCRMFL_E'
   description   'Si:C ratio per algae type MFLAGELA_E'
   unit          '(gSi/gC)'
   value          0.0000E+00
end-parameter
parameter 'SCRMFL_P'
   description   'Si:C ratio per algae type MFLAGELA_P'
   unit          '(gSi/gC)'
   value          0.0000E+00
end-parameter
parameter 'SCRPHA_E'
   description   'Si:C ratio per algae type PHAEOCYS_E'
   unit          '(gSi/gC)'
   value          0.0000E+00
end-parameter
parameter 'SCRPHA_N'
   description   'Si:C ratio per algae type PHAEOCYS_N'
   unit          '(gSi/gC)'
   value          0.0000E+00
end-parameter
parameter 'SCRPHA_P'
   description   'Si:C ratio per algae type PHAEOCYS_P'
   unit          '(gSi/gC)'
   value          0.0000E+00
end-parameter
parameter 'ChlaCFDI_E'
   description   'Chlorophyll-a:C ratio per algae type FDIATOMS_E'
   unit          '(gChla/gC)'
   value          0.4000E-01
end-parameter
parameter 'ChlaCFDI_P'
   description   'Chlorophyll-a:C ratio per algae type FDIATOMS_P'
   unit          '(gChla/gC)'
   value          0.2500E-01
end-parameter
parameter 'ChlaCGRE_E'
   description   'Chlorophyll-a:C ratio per algae type GREENS_E'
   unit          '(gChla/gC)'
   value          0.3300E-01
end-parameter
parameter 'ChlaCGRE_P'
   description   'Chlorophyll-a:C ratio per algae type GREENS_P'
   unit          '(gChla/gC)'
   value          0.2500E-01
end-parameter
parameter 'ChlaCMIC_E'
   description   'Chlorophyll-a:C ratio per algae type MICROCYS_E'
   unit          '(gChla/gC)'
   value          0.2500E-01
end-parameter
parameter 'ChlaCMIC_N'
   description   'Chlorophyll-a:C ratio per algae type MICROCYS_N'
   unit          '(gChla/gC)'
   value          0.1700E-01
end-parameter
parameter 'ChlaCMIC_P'
   description   'Chlorophyll-a:C ratio per algae type MICROCYS_P'
   unit          '(gChla/gC)'
   value          0.1700E-01
end-parameter
parameter 'ChlaCMDI_E'
   description   'Chlorophyll-a:C ratio per algae type MDIATOMS_E'
   unit          '(gChla/gC)'
   value          0.5300E-01
end-parameter
parameter 'ChlaCMDI_N'
   description   'Chlorophyll-a:C ratio per algae type MDIATOMS_N'
   unit          '(gChla/gC)'
   value          0.1000E-01
end-parameter
parameter 'ChlaCMDI_P'
   description   'Chlorophyll-a:C ratio per algae type MDIATOMS_P'
   unit          '(gChla/gC)'
   value          0.1000E-01
end-parameter
parameter 'ChlaCMFL_E'
   description   'Chlorophyll-a:C ratio per algae type MFLAGELA_E'
   unit          '(gChla/gC)'
   value          0.2860E-01
end-parameter
parameter 'ChlaCMFL_P'
   description   'Chlorophyll-a:C ratio per algae type MFLAGELA_P'
   unit          '(gChla/gC)'
   value          0.7000E-02
end-parameter
parameter 'ChlaCPHA_E'
   description   'Chlorophyll-a:C ratio per algae type PHAEOCYS_E'
   unit          '(gChla/gC)'
   value          0.2860E-01
end-parameter
parameter 'ChlaCPHA_N'
   description   'Chlorophyll-a:C ratio per algae type PHAEOCYS_N'
   unit          '(gChla/gC)'
   value          0.1670E-01
end-parameter
parameter 'ChlaCPHA_P'
   description   'Chlorophyll-a:C ratio per algae type PHAEOCYS_P'
   unit          '(gChla/gC)'
   value          0.1670E-01
end-parameter
parameter 'PPMaxFDI_E'
   description   'pot. maximum growth rate at 0 dg C FDIATOMS_E'
   unit          '(1/d)'
   value          0.3500E+00
end-parameter
parameter 'PPMaxFDI_P'
   description   'pot. maximum growth rate at 0 dg C FDIATOMS_P'
   unit          '(1/d)'
   value          0.3500E+00
end-parameter
parameter 'PPMaxGRE_E'
   description   'pot. maximum growth rate at 0 dg C GREENS_E'
   unit          '(1/d)'
   value          0.6800E-01
end-parameter
parameter 'PPMaxGRE_P'
   description   'pot. maximum growth rate at 0 dg C GREENS_P'
   unit          '(1/d)'
   value          0.6800E-01
end-parameter
parameter 'PPMaxMIC_E'
   description   'pot. maximum growth rate at 0 dg C MICROCYS_E'
   unit          '(1/d)'
   value          0.5600E-01
end-parameter
parameter 'PPMaxMIC_N'
   description   'pot. maximum growth rate at 0 dg C MICROCYS_N'
   unit          '(1/d)'
   value          0.4800E-01
end-parameter
parameter 'PPMaxMIC_P'
   description   'pot. maximum growth rate at 0 dg C MICROCYS_P'
   unit          '(1/d)'
   value          0.4800E-01
end-parameter
parameter 'PPMaxMDI_E'
   description   'pot. maximum growth rate at 0 dg C MDIATOMS_E'
   unit          '(1/d)'
   value          0.8300E-01
end-parameter
parameter 'PPMaxMDI_N'
   description   'pot. maximum growth rate at 0 dg C MDIATOMS_N'
   unit          '(1/d)'
   value          0.6600E-01
end-parameter
parameter 'PPMaxMDI_P'
   description   'pot. maximum growth rate at 0 dg C MDIATOMS_P'
   unit          '(1/d)'
   value          0.6600E-01
end-parameter
parameter 'PPMaxMFL_E'
   description   'pot. maximum growth rate at 0 dg C MFLAGELA_E'
   unit          '(1/d)'
   value          0.9000E-01
end-parameter
parameter 'PPMaxMFL_P'
   description   'pot. maximum growth rate at 0 dg C MFLAGELA_P'
   unit          '(1/d)'
   value          0.7500E-01
end-parameter
parameter 'PPMaxPHA_E'
   description   'pot. maximum growth rate at 0 dg C PHAEOCYS_E'
   unit          '(1/d)'
   value          0.8400E-01
end-parameter
parameter 'PPMaxPHA_N'
   description   'pot. maximum growth rate at 0 dg C PHAEOCYS_N'
   unit          '(1/d)'
   value          0.7800E-01
end-parameter
parameter 'PPMaxPHA_P'
   description   'pot. maximum growth rate at 0 dg C PHAEOCYS_P'
   unit          '(1/d)'
   value          0.7800E-01
end-parameter
parameter 'TcPMxFDI_E'
   description   'temperature coefficient for growth FDIATOMS_E'
   unit          '(-)'
   value          0.1060E+01
end-parameter
parameter 'TcPMxFDI_P'
   description   'temperature coefficient for growth FDIATOMS_P'
   unit          '(-)'
   value          0.1054E+01
end-parameter
parameter 'TcPMxGRE_E'
   description   'temperature coefficient for growth GREENS_E'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'TcPMxGRE_P'
   description   'temperature coefficient for growth GREENS_P'
   unit          '(-)'
   value          0.3000E+01
end-parameter
parameter 'TcPMxMIC_E'
   description   'temperature coefficient for growth MICROCYS_E'
   unit          '(-)'
   value          0.3000E+01
end-parameter
parameter 'TcPMxMIC_N'
   description   'temperature coefficient for growth MICROCYS_N'
   unit          '(-)'
   value          0.5000E+01
end-parameter
parameter 'TcPMxMIC_P'
   description   'temperature coefficient for growth MICROCYS_P'
   unit          '(-)'
   value          0.5000E+01
end-parameter
parameter 'TcPMxMDI_E'
   description   'temperature coefficient for growth MDIATOMS_E'
   unit          '(-)'
   value         -0.1750E+01
end-parameter
parameter 'TcPMxMDI_N'
   description   'temperature coefficient for growth MDIATOMS_N'
   unit          '(-)'
   value         -0.2000E+01
end-parameter
parameter 'TcPMxMDI_P'
   description   'temperature coefficient for growth MDIATOMS_P'
   unit          '(-)'
   value         -0.2000E+01
end-parameter
parameter 'TcPMxMFL_E'
   description   'temperature coefficient for growth MFLAGELA_E'
   unit          '(-)'
   value         -0.1000E+01
end-parameter
parameter 'TcPMxMFL_P'
   description   'temperature coefficient for growth MFLAGELA_P'
   unit          '(-)'
   value         -0.1000E+01
end-parameter
parameter 'TcPMxPHA_E'
   description   'temperature coefficient for growth PHAEOCYS_E'
   unit          '(-)'
   value         -0.3250E+01
end-parameter
parameter 'TcPMxPHA_N'
   description   'temperature coefficient for growth PHAEOCYS_N'
   unit          '(-)'
   value         -0.3000E+01
end-parameter
parameter 'TcPMxPHA_P'
   description   'temperature coefficient for growth PHAEOCYS_P'
   unit          '(-)'
   value         -0.3000E+01
end-parameter
parameter 'TFPMxFDI_E'
   description   'growth response temp. (0-lin,<>0-expon) FDIATOMS_E'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'TFPMxFDI_P'
   description   'growth response temp. (0-lin,<>0-expon) FDIATOMS_P'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'TFPMxGRE_E'
   description   'growth response temp. (0-lin,<>0-expon) GREENS_E'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'TFPMxGRE_P'
   description   'growth response temp. (0-lin,<>0-expon) GREENS_P'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'TFPMxMIC_E'
   description   'growth response temp. (0-lin,<>0-expon) MICROCYS_E'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'TFPMxMIC_N'
   description   'growth response temp. (0-lin,<>0-expon) MICROCYS_N'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'TFPMxMIC_P'
   description   'growth response temp. (0-lin,<>0-expon) MICROCYS_P'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'TFPMxMDI_E'
   description   'growth response temp. (0-lin,<>0-expon) MDIATOMS_E'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'TFPMxMDI_N'
   description   'growth response temp. (0-lin,<>0-expon) MDIATOMS_N'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'TFPMxMDI_P'
   description   'growth response temp. (0-lin,<>0-expon) MDIATOMS_P'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'TFPMxMFL_E'
   description   'growth response temp. (0-lin,<>0-expon) MFLAGELA_E'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'TFPMxMFL_P'
   description   'growth response temp. (0-lin,<>0-expon) MFLAGELA_P'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'TFPMxPHA_E'
   description   'growth response temp. (0-lin,<>0-expon) PHAEOCYS_E'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'TFPMxPHA_N'
   description   'growth response temp. (0-lin,<>0-expon) PHAEOCYS_N'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'TFPMxPHA_P'
   description   'growth response temp. (0-lin,<>0-expon) PHAEOCYS_P'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'Mort0FDI_E'
   description   'mortality rate at 0 dg C FDIATOMS_E'
   unit          '(1/d)'
   value          0.3500E-01
end-parameter
parameter 'Mort0FDI_P'
   description   'mortality rate at 0 dg C FDIATOMS_P'
   unit          '(1/d)'
   value          0.4500E-01
end-parameter
parameter 'Mort0GRE_E'
   description   'mortality rate at 0 dg C GREENS_E'
   unit          '(1/d)'
   value          0.3500E-01
end-parameter
parameter 'Mort0GRE_P'
   description   'mortality rate at 0 dg C GREENS_P'
   unit          '(1/d)'
   value          0.4500E-01
end-parameter
parameter 'Mort0MIC_E'
   description   'mortality rate at 0 dg C MICROCYS_E'
   unit          '(1/d)'
   value          0.3500E-01
end-parameter
parameter 'Mort0MIC_N'
   description   'mortality rate at 0 dg C MICROCYS_N'
   unit          '(1/d)'
   value          0.4500E-01
end-parameter
parameter 'Mort0MIC_P'
   description   'mortality rate at 0 dg C MICROCYS_P'
   unit          '(1/d)'
   value          0.4500E-01
end-parameter
parameter 'Mort0MDI_E'
   description   'mortality rate at 0 dg C MDIATOMS_E'
   unit          '(1/d)'
   value          0.7000E-01
end-parameter
parameter 'Mort0MDI_N'
   description   'mortality rate at 0 dg C MDIATOMS_N'
   unit          '(1/d)'
   value          0.8000E-01
end-parameter
parameter 'Mort0MDI_P'
   description   'mortality rate at 0 dg C MDIATOMS_P'
   unit          '(1/d)'
   value          0.8000E-01
end-parameter
parameter 'Mort0MFL_E'
   description   'mortality rate at 0 dg C MFLAGELA_E'
   unit          '(1/d)'
   value          0.7000E-01
end-parameter
parameter 'Mort0MFL_P'
   description   'mortality rate at 0 dg C MFLAGELA_P'
   unit          '(1/d)'
   value          0.8000E-01
end-parameter
parameter 'Mort0PHA_E'
   description   'mortality rate at 0 dg C PHAEOCYS_E'
   unit          '(1/d)'
   value          0.7000E-01
end-parameter
parameter 'Mort0PHA_N'
   description   'mortality rate at 0 dg C PHAEOCYS_N'
   unit          '(1/d)'
   value          0.8000E-01
end-parameter
parameter 'Mort0PHA_P'
   description   'mortality rate at 0 dg C PHAEOCYS_P'
   unit          '(1/d)'
   value          0.8000E-01
end-parameter
parameter 'TcMrtFDI_E'
   description   'temperature coefficient for mortality FDIATOMS_E'
   unit          '(-)'
   value          0.1080E+01
end-parameter
parameter 'TcMrtFDI_P'
   description   'temperature coefficient for mortality FDIATOMS_P'
   unit          '(-)'
   value          0.1085E+01
end-parameter
parameter 'TcMrtGRE_E'
   description   'temperature coefficient for mortality GREENS_E'
   unit          '(-)'
   value          0.1080E+01
end-parameter
parameter 'TcMrtGRE_P'
   description   'temperature coefficient for mortality GREENS_P'
   unit          '(-)'
   value          0.1085E+01
end-parameter
parameter 'TcMrtMIC_E'
   description   'temperature coefficient for mortality MICROCYS_E'
   unit          '(-)'
   value          0.1080E+01
end-parameter
parameter 'TcMrtMIC_N'
   description   'temperature coefficient for mortality MICROCYS_N'
   unit          '(-)'
   value          0.1085E+01
end-parameter
parameter 'TcMrtMIC_P'
   description   'temperature coefficient for mortality MICROCYS_P'
   unit          '(-)'
   value          0.1085E+01
end-parameter
parameter 'TcMrtMDI_E'
   description   'temperature coefficient for mortality MDIATOMS_E'
   unit          '(-)'
   value          0.1072E+01
end-parameter
parameter 'TcMrtMDI_N'
   description   'temperature coefficient for mortality MDIATOMS_N'
   unit          '(-)'
   value          0.1085E+01
end-parameter
parameter 'TcMrtMDI_P'
   description   'temperature coefficient for mortality MDIATOMS_P'
   unit          '(-)'
   value          0.1085E+01
end-parameter
parameter 'TcMrtMFL_E'
   description   'temperature coefficient for mortality MFLAGELA_E'
   unit          '(-)'
   value          0.1072E+01
end-parameter
parameter 'TcMrtMFL_P'
   description   'temperature coefficient for mortality MFLAGELA_P'
   unit          '(-)'
   value          0.1085E+01
end-parameter
parameter 'TcMrtPHA_E'
   description   'temperature coefficient for mortality PHAEOCYS_E'
   unit          '(-)'
   value          0.1072E+01
end-parameter
parameter 'TcMrtPHA_N'
   description   'temperature coefficient for mortality PHAEOCYS_N'
   unit          '(-)'
   value          0.1085E+01
end-parameter
parameter 'TcMrtPHA_P'
   description   'temperature coefficient for mortality PHAEOCYS_P'
   unit          '(-)'
   value          0.1085E+01
end-parameter
parameter 'MRespFDI_E'
   description   'maintenance respiration rate at 0 dg C FDIATOMS_E'
   unit          '(1/d)'
   value          0.3100E-01
end-parameter
parameter 'MRespFDI_P'
   description   'maintenance respiration rate at 0 dg C FDIATOMS_P'
   unit          '(1/d)'
   value          0.3100E-01
end-parameter
parameter 'MRespGRE_E'
   description   'maintenance respiration rate at 0 dg C GREENS_E'
   unit          '(1/d)'
   value          0.3100E-01
end-parameter
parameter 'MRespGRE_P'
   description   'maintenance respiration rate at 0 dg C GREENS_P'
   unit          '(1/d)'
   value          0.3100E-01
end-parameter
parameter 'MRespMIC_E'
   description   'maintenance respiration rate at 0 dg C MICROCYS_E'
   unit          '(1/d)'
   value          0.1200E-01
end-parameter
parameter 'MRespMIC_N'
   description   'maintenance respiration rate at 0 dg C MICROCYS_N'
   unit          '(1/d)'
   value          0.1200E-01
end-parameter
parameter 'MRespMIC_P'
   description   'maintenance respiration rate at 0 dg C MICROCYS_P'
   unit          '(1/d)'
   value          0.1200E-01
end-parameter
parameter 'MRespMDI_E'
   description   'maintenance respiration rate at 0 dg C MDIATOMS_E'
   unit          '(1/d)'
   value          0.6000E-01
end-parameter
parameter 'MRespMDI_N'
   description   'maintenance respiration rate at 0 dg C MDIATOMS_N'
   unit          '(1/d)'
   value          0.6000E-01
end-parameter
parameter 'MRespMDI_P'
   description   'maintenance respiration rate at 0 dg C MDIATOMS_P'
   unit          '(1/d)'
   value          0.6000E-01
end-parameter
parameter 'MRespMFL_E'
   description   'maintenance respiration rate at 0 dg C MFLAGELA_E'
   unit          '(1/d)'
   value          0.6000E-01
end-parameter
parameter 'MRespMFL_P'
   description   'maintenance respiration rate at 0 dg C MFLAGELA_P'
   unit          '(1/d)'
   value          0.6000E-01
end-parameter
parameter 'MRespPHA_E'
   description   'maintenance respiration rate at 0 dg C PHAEOCYS_E'
   unit          '(1/d)'
   value          0.6000E-01
end-parameter
parameter 'MRespPHA_N'
   description   'maintenance respiration rate at 0 dg C PHAEOCYS_N'
   unit          '(1/d)'
   value          0.6000E-01
end-parameter
parameter 'MRespPHA_P'
   description   'maintenance respiration rate at 0 dg C PHAEOCYS_P'
   unit          '(1/d)'
   value          0.6000E-01
end-parameter
parameter 'TcRspFDI_E'
   description   'temperature coefficient for respiration FDIATOMS_E'
   unit          '(-)'
   value          0.1072E+01
end-parameter
parameter 'TcRspFDI_P'
   description   'temperature coefficient for respiration FDIATOMS_P'
   unit          '(-)'
   value          0.1072E+01
end-parameter
parameter 'TcRspGRE_E'
   description   'temperature coefficient for respiration GREENS_E'
   unit          '(-)'
   value          0.1072E+01
end-parameter
parameter 'TcRspGRE_P'
   description   'temperature coefficient for respiration GREENS_P'
   unit          '(-)'
   value          0.1072E+01
end-parameter
parameter 'TcRspMIC_E'
   description   'temperature coefficient for respiration MICROCYS_E'
   unit          '(-)'
   value          0.1072E+01
end-parameter
parameter 'TcRspMIC_N'
   description   'temperature coefficient for respiration MICROCYS_N'
   unit          '(-)'
   value          0.1072E+01
end-parameter
parameter 'TcRspMIC_P'
   description   'temperature coefficient for respiration MICROCYS_P'
   unit          '(-)'
   value          0.1072E+01
end-parameter
parameter 'TcRspMDI_E'
   description   'temperature coefficient for respiration MDIATOMS_E'
   unit          '(-)'
   value          0.1066E+01
end-parameter
parameter 'TcRspMDI_N'
   description   'temperature coefficient for respiration MDIATOMS_N'
   unit          '(-)'
   value          0.1066E+01
end-parameter
parameter 'TcRspMDI_P'
   description   'temperature coefficient for respiration MDIATOMS_P'
   unit          '(-)'
   value          0.1066E+01
end-parameter
parameter 'TcRspMFL_E'
   description   'temperature coefficient for respiration MFLAGELA_E'
   unit          '(-)'
   value          0.1066E+01
end-parameter
parameter 'TcRspMFL_P'
   description   'temperature coefficient for respiration MFLAGELA_P'
   unit          '(-)'
   value          0.1066E+01
end-parameter
parameter 'TcRspPHA_E'
   description   'temperature coefficient for respiration PHAEOCYS_E'
   unit          '(-)'
   value          0.1066E+01
end-parameter
parameter 'TcRspPHA_N'
   description   'temperature coefficient for respiration PHAEOCYS_N'
   unit          '(-)'
   value          0.1066E+01
end-parameter
parameter 'TcRspPHA_P'
   description   'temperature coefficient for respiration PHAEOCYS_P'
   unit          '(-)'
   value          0.1066E+01
end-parameter
parameter 'SDMixFDI_E'
   description   'distribution water column: fraction of depth FDIATOMS_E'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixFDI_P'
   description   'distribution water column: fraction of depth FDIATOMS_P'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixGRE_E'
   description   'distribution water column: fraction of depth GREENS_E'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixGRE_P'
   description   'distribution water column: fraction of depth GREENS_P'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixMIC_E'
   description   'distribution water column: fraction of depth MICROCYS_E'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixMIC_N'
   description   'distribution water column: fraction of depth MICROCYS_N'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixMIC_P'
   description   'distribution water column: fraction of depth MICROCYS_P'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixMDI_E'
   description   'distribution water column: fraction of depth MDIATOMS_E'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixMDI_N'
   description   'distribution water column: fraction of depth MDIATOMS_N'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixMDI_P'
   description   'distribution water column: fraction of depth MDIATOMS_P'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixMFL_E'
   description   'distribution water column: fraction of depth MFLAGELA_E'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixMFL_P'
   description   'distribution water column: fraction of depth MFLAGELA_P'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixPHA_E'
   description   'distribution water column: fraction of depth PHAEOCYS_E'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixPHA_N'
   description   'distribution water column: fraction of depth PHAEOCYS_N'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixPHA_P'
   description   'distribution water column: fraction of depth PHAEOCYS_P'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'Mort2FDI_E'
   description   'salinity dependent mortality rate at 0 dg C FDIATOMS_E'
   unit          '(1/d)'
   value          0.0000E+00
end-parameter
parameter 'Mort2FDI_P'
   description   'salinity dependent mortality rate at 0 dg C FDIATOMS_P'
   unit          '(1/d)'
   value          0.0000E+00
end-parameter
parameter 'Mort2GRE_E'
   description   'salinity dependent mortality rate at 0 dg C GREENS_E'
   unit          '(1/d)'
   value          0.0000E+00
end-parameter
parameter 'Mort2GRE_P'
   description   'salinity dependent mortality rate at 0 dg C GREENS_P'
   unit          '(1/d)'
   value          0.0000E+00
end-parameter
parameter 'Mort2MIC_E'
   description   'salinity dependent mortality rate at 0 dg C MICROCYS_E'
   unit          '(1/d)'
   value          0.0000E+00
end-parameter
parameter 'Mort2MIC_N'
   description   'salinity dependent mortality rate at 0 dg C MICROCYS_N'
   unit          '(1/d)'
   value          0.0000E+00
end-parameter
parameter 'Mort2MIC_P'
   description   'salinity dependent mortality rate at 0 dg C MICROCYS_P'
   unit          '(1/d)'
   value          0.0000E+00
end-parameter
parameter 'Mort2MDI_E'
   description   'salinity dependent mortality rate at 0 dg C MDIATOMS_E'
   unit          '(1/d)'
   value          0.0000E+00
end-parameter
parameter 'Mort2MDI_N'
   description   'salinity dependent mortality rate at 0 dg C MDIATOMS_N'
   unit          '(1/d)'
   value          0.0000E+00
end-parameter
parameter 'Mort2MDI_P'
   description   'salinity dependent mortality rate at 0 dg C MDIATOMS_P'
   unit          '(1/d)'
   value          0.0000E+00
end-parameter
parameter 'Mort2MFL_E'
   description   'salinity dependent mortality rate at 0 dg C MFLAGELA_E'
   unit          '(1/d)'
   value          0.0000E+00
end-parameter
parameter 'Mort2MFL_P'
   description   'salinity dependent mortality rate at 0 dg C MFLAGELA_P'
   unit          '(1/d)'
   value          0.0000E+00
end-parameter
parameter 'Mort2PHA_E'
   description   'salinity dependent mortality rate at 0 dg C PHAEOCYS_E'
   unit          '(1/d)'
   value          0.0000E+00
end-parameter
parameter 'Mort2PHA_N'
   description   'salinity dependent mortality rate at 0 dg C PHAEOCYS_N'
   unit          '(1/d)'
   value          0.0000E+00
end-parameter
parameter 'Mort2PHA_P'
   description   'salinity dependent mortality rate at 0 dg C PHAEOCYS_P'
   unit          '(1/d)'
   value          0.0000E+00
end-parameter
parameter 'MrtB1FDI_E'
   description   'coeff. b1 salinity dependent mort.func. FDIATOMS_E'
   unit          '(gCl/m3)'
   value          0.2000E-02
end-parameter
parameter 'MrtB1FDI_P'
   description   'coeff. b1 salinity dependent mort.func. FDIATOMS_P'
   unit          '(gCl/m3)'
   value          0.2000E-02
end-parameter
parameter 'MrtB1GRE_E'
   description   'coeff. b1 salinity dependent mort.func. GREENS_E'
   unit          '(gCl/m3)'
   value          0.2000E-02
end-parameter
parameter 'MrtB1GRE_P'
   description   'coeff. b1 salinity dependent mort.func. GREENS_P'
   unit          '(gCl/m3)'
   value          0.2000E-02
end-parameter
parameter 'MrtB1MIC_E'
   description   'coeff. b1 salinity dependent mort.func. MICROCYS_E'
   unit          '(gCl/m3)'
   value          0.2000E-02
end-parameter
parameter 'MrtB1MIC_N'
   description   'coeff. b1 salinity dependent mort.func. MICROCYS_N'
   unit          '(gCl/m3)'
   value          0.2000E-02
end-parameter
parameter 'MrtB1MIC_P'
   description   'coeff. b1 salinity dependent mort.func. MICROCYS_P'
   unit          '(gCl/m3)'
   value          0.2000E-02
end-parameter
parameter 'MrtB1MDI_E'
   description   'coeff. b1 salinity dependent mort.func. MDIATOMS_E'
   unit          '(gCl/m3)'
   value          0.2000E-02
end-parameter
parameter 'MrtB1MDI_N'
   description   'coeff. b1 salinity dependent mort.func. MDIATOMS_N'
   unit          '(gCl/m3)'
   value          0.2000E-02
end-parameter
parameter 'MrtB1MDI_P'
   description   'coeff. b1 salinity dependent mort.func. MDIATOMS_P'
   unit          '(gCl/m3)'
   value          0.2000E-02
end-parameter
parameter 'MrtB1MFL_E'
   description   'coeff. b1 salinity dependent mort.func. MFLAGELA_E'
   unit          '(gCl/m3)'
   value          0.2000E-02
end-parameter
parameter 'MrtB1MFL_P'
   description   'coeff. b1 salinity dependent mort.func. MFLAGELA_P'
   unit          '(gCl/m3)'
   value          0.2000E-02
end-parameter
parameter 'MrtB1PHA_E'
   description   'coeff. b1 salinity dependent mort.func. PHAEOCYS_E'
   unit          '(gCl/m3)'
   value          0.2000E-02
end-parameter
parameter 'MrtB1PHA_N'
   description   'coeff. b1 salinity dependent mort.func. PHAEOCYS_N'
   unit          '(gCl/m3)'
   value          0.2000E-02
end-parameter
parameter 'MrtB1PHA_P'
   description   'coeff. b1 salinity dependent mort.func. PHAEOCYS_P'
   unit          '(gCl/m3)'
   value          0.2000E-02
end-parameter
parameter 'MrtB2FDI_E'
   description   'coeff. b2 salinity dependent mort.func. FDIATOMS_E'
   unit          '(gCl/m3)'
   value          0.8000E+04
end-parameter
parameter 'MrtB2FDI_P'
   description   'coeff. b2 salinity dependent mort.func. FDIATOMS_P'
   unit          '(gCl/m3)'
   value          0.8000E+04
end-parameter
parameter 'MrtB2GRE_E'
   description   'coeff. b2 salinity dependent mort.func. GREENS_E'
   unit          '(gCl/m3)'
   value          0.8000E+04
end-parameter
parameter 'MrtB2GRE_P'
   description   'coeff. b2 salinity dependent mort.func. GREENS_P'
   unit          '(gCl/m3)'
   value          0.8000E+04
end-parameter
parameter 'MrtB2MIC_E'
   description   'coeff. b2 salinity dependent mort.func. MICROCYS_E'
   unit          '(gCl/m3)'
   value          0.8000E+04
end-parameter
parameter 'MrtB2MIC_N'
   description   'coeff. b2 salinity dependent mort.func. MICROCYS_N'
   unit          '(gCl/m3)'
   value          0.8000E+04
end-parameter
parameter 'MrtB2MIC_P'
   description   'coeff. b2 salinity dependent mort.func. MICROCYS_P'
   unit          '(gCl/m3)'
   value          0.8000E+04
end-parameter
parameter 'MrtB2MDI_E'
   description   'coeff. b2 salinity dependent mort.func. MDIATOMS_E'
   unit          '(gCl/m3)'
   value          0.8000E+04
end-parameter
parameter 'MrtB2MDI_N'
   description   'coeff. b2 salinity dependent mort.func. MDIATOMS_N'
   unit          '(gCl/m3)'
   value          0.8000E+04
end-parameter
parameter 'MrtB2MDI_P'
   description   'coeff. b2 salinity dependent mort.func. MDIATOMS_P'
   unit          '(gCl/m3)'
   value          0.8000E+04
end-parameter
parameter 'MrtB2MFL_E'
   description   'coeff. b2 salinity dependent mort.func. MFLAGELA_E'
   unit          '(gCl/m3)'
   value          0.8000E+04
end-parameter
parameter 'MrtB2MFL_P'
   description   'coeff. b2 salinity dependent mort.func. MFLAGELA_P'
   unit          '(gCl/m3)'
   value          0.8000E+04
end-parameter
parameter 'MrtB2PHA_E'
   description   'coeff. b2 salinity dependent mort.func. PHAEOCYS_E'
   unit          '(gCl/m3)'
   value          0.8000E+04
end-parameter
parameter 'MrtB2PHA_N'
   description   'coeff. b2 salinity dependent mort.func. PHAEOCYS_N'
   unit          '(gCl/m3)'
   value          0.8000E+04
end-parameter
parameter 'MrtB2PHA_P'
   description   'coeff. b2 salinity dependent mort.func. PHAEOCYS_P'
   unit          '(gCl/m3)'
   value          0.8000E+04
end-parameter
parameter 'RcDetC'
   description   'first-order mineralisation rate DetC'
   unit          '(1/d)'
   value          0.1200E+00
end-parameter
parameter 'TcDetC'
   description   'temperature coefficient for mineralisation DetC'
   unit          '(-)'
   value          0.1047E+01
end-parameter
parameter 'CTMin'
   description   'critical temperature for mineralisation'
   unit          '(oC)'
   value          0.3000E+01
end-parameter
parameter 'TauCSDetC'
   description   'critical shear stress for sedimentation DetC'
   unit          '(N/m2)'
   value          0.1000E+00
end-parameter
parameter 'MDETFF'
   description   'Faecal fraction for detritus of Mussel'
   unit          '(-)'
   value          0.5000E+00
end-parameter
parameter 'MDETPR'
   description   'Preference of Mussel for detritus'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'MGRZFM'
   description   'maximum filtration velocity Mussel'
   unit          '(m3/gC/d)'
   value          0.5000E-01
end-parameter
parameter 'MGRZGM'
   description   'maximum relative growth rate Mussel'
   unit          '(1/d)'
   value          0.2000E+00
end-parameter
parameter 'MGRZML'
   description   'multiplication factor for biomass Mussel'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'MGRZMM'
   description   'maximum relative mortality Mussel'
   unit          '(1/d)'
   value          0.2000E+00
end-parameter
parameter 'MGRZRE'
   description   'Maintenance respiration coefficient Mussel'
   unit          '(-)'
   value          0.2000E+00
end-parameter
parameter 'MGRZRM'
   description   'maximum daily uptake Mussel'
   unit          '(mgC/mgC.d)'
   value          0.1000E+00
end-parameter
parameter 'MGRZSE'
   description   'Standard respiration coefficient Mussel'
   unit          '(1/d)'
   value          0.5000E-02
end-parameter
parameter 'MFrDetBot'
   description   'Fract. produced detritus to bottom Mussel'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'MUnitSW'
   description   'Use gC/m3 (0) or gC/m2 (1) for Mussels'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SecchiExt1'
   description   'Secchi depth if extinction = 1 (Poole-Atkins)'
   unit          '(m)'
   value          0.1700E+01
end-parameter
parameter 'RcDetCS1'
   description   'first-order mineralisation rate DetC in layer S1'
   unit          '(1/d)'
   value          0.3000E-01
end-parameter
parameter 'TcBMDetC'
   description   'temperature coeff. mineralisation DetC in sediment'
   unit          '(-)'
   value          0.1090E+01
end-parameter
parameter 'RcDetN'
   description   'first-order mineralisation rate DetN'
   unit          '(1/d)'
   value          0.1200E+00
end-parameter
parameter 'TcDetN'
   description   'temperature coefficient for mineralisation DetN'
   unit          '(-)'
   value          0.1047E+01
end-parameter
parameter 'RcDetNS1'
   description   'first-order mineralisation rate DetN in layer S1'
   unit          '(1/d)'
   value          0.3000E-01
end-parameter
parameter 'RcDetP'
   description   'first-order mineralisation rate DetP'
   unit          '(1/d)'
   value          0.8000E-01
end-parameter
parameter 'TcDetP'
   description   'temperature coefficient for mineralisation DetP'
   unit          '(-)'
   value          0.1047E+01
end-parameter
parameter 'RcDetPS1'
   description   'first-order mineralisation rate DetP in layer S1'
   unit          '(1/d)'
   value          0.3000E-01
end-parameter
parameter 'RcDetSi'
   description   'first-order mineralisation rate DetSi'
   unit          '(1/d)'
   value          0.1000E-01
end-parameter
parameter 'TcDetSi'
   description   'temperature coefficient for mineralisation DetSi'
   unit          '(-)'
   value          0.1047E+01
end-parameter
parameter 'RcDetSiS1'
   description   'first-order mineralisation rate DetSi in layer S1'
   unit          '(1/d)'
   value          0.1500E-01
end-parameter
parameter 'TcNit'
   description   'temperature coefficient for nitrification'
   unit          '(-)'
   value          0.1070E+01
end-parameter
parameter 'CTNit'
   description   'critical temperature for nitrification'
   unit          '(oC)'
   value          0.3000E+01
end-parameter
parameter 'RcNit'
   description   'first-order nitrification rate'
   unit          '(1/d)'
   value          0.1000E+00
end-parameter
parameter 'RcOONS1'
   description   'first-order mineralisation rate OON in layer S1'
   unit          '(1/d)'
   value          0.3000E-01
end-parameter
parameter 'RcOON'
   description   'first-order mineralisation rate OON'
   unit          '(1/d)'
   value          0.1000E-01
end-parameter
parameter 'fDfwastNH4'
   description   'diffusive waste flux NH4'
   unit          '(gN/m2/d)'
   value         -0.9990E+03
end-parameter
parameter 'RcDenSed'
   description   'first-order denitrification rate in the sediment'
   unit          '(m/d)'
   value          0.1000E+00
end-parameter
parameter 'TcDen'
   description   'temperature coefficient for denitrification'
   unit          '(-)'
   value          0.1120E+01
end-parameter
parameter 'CTDEN'
   description   'critical temperature for denitrification'
   unit          '(oC)'
   value          0.2000E+01
end-parameter
parameter 'TcDenWat'
   description   'temperature coefficient for denitrification'
   unit          '(-)'
   value          0.1070E+01
end-parameter
parameter 'RcDenWat'
   description   'first-order denitrification rate in water column'
   unit          '(1/d)'
   value          0.1000E+00
end-parameter
parameter 'fDfwastNO3'
   description   'diffusive waste flux NO3'
   unit          '(gN/m2/d)'
   value         -0.9990E+03
end-parameter
parameter 'RcOOC'
   description   'first-order mineralisation rate OOC'
   unit          '(1/d)'
   value          0.1000E-01
end-parameter
parameter 'VSedOOC'
   description   'sedimentation velocity OOC'
   unit          '(m/d)'
   value          0.1000E+00
end-parameter
parameter 'RcOOCS1'
   description   'first-order mineralisation rate OOC in layer S1'
   unit          '(1/d)'
   value          0.3000E-01
end-parameter
parameter 'RcOOP'
   description   'first-order mineralisation rate OOP'
   unit          '(1/d)'
   value          0.1000E-01
end-parameter
parameter 'RcOOPS1'
   description   'first-order mineralisation rate OOP in layer S1'
   unit          '(1/d)'
   value          0.3000E-01
end-parameter
parameter 'RcOOSi'
   description   'first-order mineralisation rate OOSi'
   unit          '(1/d)'
   value          0.2000E-01
end-parameter
parameter 'RcOOSiS1'
   description   'first-order mineralisation rate OOSi in layer S1'
   unit          '(1/d)'
   value          0.1500E-01
end-parameter
parameter 'fDfwastPO4'
   description   'diffusive waste flux PO4'
   unit          '(gP/m2/d)'
   value         -0.9990E+03
end-parameter
parameter 'VsedFDI_E'
   description   'sedimentation velocity algae FDIATOMS_E'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'VsedFDI_P'
   description   'sedimentation velocity algae FDIATOMS_P'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'VsedGRE_E'
   description   'sedimentation velocity algae GREENS_E'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'VsedGRE_P'
   description   'sedimentation velocity algae GREENS_P'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'VsedMIC_E'
   description   'sedimentation velocity algae MICROCYS_E'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'VsedMIC_N'
   description   'sedimentation velocity algae MICROCYS_N'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'VsedMIC_P'
   description   'sedimentation velocity algae MICROCYS_P'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'VsedMDI_E'
   description   'sedimentation velocity algae MDIATOMS_E'
   unit          '(m/d)'
   value          0.5000E+00
end-parameter
parameter 'VsedMDI_N'
   description   'sedimentation velocity algae MDIATOMS_N'
   unit          '(m/d)'
   value          0.1000E+01
end-parameter
parameter 'VsedMDI_P'
   description   'sedimentation velocity algae MDIATOMS_P'
   unit          '(m/d)'
   value          0.1000E+01
end-parameter
parameter 'VsedMFL_E'
   description   'sedimentation velocity algae MFLAGELA_E'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'VsedMFL_P'
   description   'sedimentation velocity algae MFLAGELA_P'
   unit          '(m/d)'
   value          0.5000E+00
end-parameter
parameter 'VsedPHA_E'
   description   'sedimentation velocity algae PHAEOCYS_E'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'VsedPHA_N'
   description   'sedimentation velocity algae PHAEOCYS_N'
   unit          '(m/d)'
   value          0.5000E+00
end-parameter
parameter 'VsedPHA_P'
   description   'sedimentation velocity algae PHAEOCYS_P'
   unit          '(m/d)'
   value          0.5000E+00
end-parameter
parameter 'TaucS'
   description   'critical shear stress for sedimentation algae'
   unit          '(N/m2)'
   value          0.1000E+00
end-parameter
parameter 'SWRear'
   description   'switch for oxygen reaeration formulation (1-12)'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'KLRear'
   description   'reaeration transfer coefficient'
   unit          '(m/d)'
   value          0.1000E+01
end-parameter
parameter 'VSedIM1'
   description   'sedimentation velocity IM1'
   unit          '(m/d)'
   value          0.1000E+00
end-parameter
parameter 'TaucSIM1'
   description   'critical shear stress for sedimentation IM1'
   unit          '(N/m2)'
   value          0.1000E+00
end-parameter
parameter 'VSedIM2'
   description   'sedimentation velocity IM2'
   unit          '(m/d)'
   value          0.1000E+00
end-parameter
parameter 'TaucSIM2'
   description   'critical shear stress for sedimentation IM2'
   unit          '(N/m2)'
   value          0.1000E+00
end-parameter
parameter 'VSedIM3'
   description   'sedimentation velocity IM3'
   unit          '(m/d)'
   value          0.1000E+00
end-parameter
parameter 'TaucSIM3'
   description   'critical shear stress for sedimentation IM3'
   unit          '(N/m2)'
   value          0.1000E+00
end-parameter
parameter 'PORS1'
   description   'porosity of sediment layer S1'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'ExtVlIM1'
   description   'VL specific extinction coefficient M1'
   unit          '(m2/gDM)'
   value          0.1000E-01
end-parameter
parameter 'ExtVlIM2'
   description   'VL specific extinction coefficient IM2'
   unit          '(m2/gDM)'
   value          0.2500E-01
end-parameter
parameter 'ExtVlIM3'
   description   'VL specific extinction coefficient IM3'
   unit          '(m2/gDM)'
   value          0.2500E-01
end-parameter
parameter 'ExtVlBak'
   description   'background extinction visible light'
   unit          '(1/m)'
   value          0.8000E-01
end-parameter
parameter 'ExtVLSal0'
   description   'extra VL extinction at Salinity = 0'
   unit          '(1/m)'
   value          0.0000E+00
end-parameter
parameter 'SalExt0'
   description   'salinity value for extra extinction = 0'
   unit          '(g/kg)'
   value          0.3492E+02
end-parameter
parameter 'Latitude'
   description   'latitude of study area'
   unit          '(degrees)'
   value          0.5210E+02
end-parameter
parameter 'RefDay'
   description   'daynumber of reference day simulation'
   unit          '(d)'
   value          0.0000E+00
end-parameter
parameter 'V0SedDetC'
   description   'sedimentation velocity DetC'
   unit          '(m/d)'
   value         -0.9990E+03
end-parameter
parameter 'ZResDM'
   description   'zeroth-order resuspension flux'
   unit          '(gDM/m2/d)'
   value          0.0000E+00
end-parameter
parameter 'TaucRS1DM'
   description   'critical shear stress for resuspension DM layer S1'
   unit          '(N/m2)'
   value          0.2000E+00
end-parameter
parameter 'Zoopl_1'
   description   'Zooplnk biomass station 1'
   unit          '(gC/m3)'
   value          0.0000E+00
end-parameter
parameter 'Mussl_1'
   description   'Mussel  biomass station 1'
   unit          '(gC/m2)'
   value          0.0000E+00
end-parameter
parameter 'Zoopl_2'
   description   'Zooplnk biomass station 2'
   unit          '(gC/m3)'
   value          0.0000E+00
end-parameter
parameter 'Mussl_2'
   description   'Mussel  biomass station 2'
   unit          '(gC/m2)'
   value          0.0000E+00
end-parameter
parameter 'Zoopl_3'
   description   'Zooplnk biomass station 3'
   unit          '(gC/m3)'
   value          0.0000E+00
end-parameter
parameter 'Mussl_3'
   description   'Mussel  biomass station 3'
   unit          '(gC/m2)'
   value          0.0000E+00
end-parameter
parameter 'Zoopl_4'
   description   'Zooplnk biomass station 4'
   unit          '(gC/m3)'
   value          0.0000E+00
end-parameter
parameter 'Mussl_4'
   description   'Mussel  biomass station 4'
   unit          '(gC/m2)'
   value          0.0000E+00
end-parameter
parameter 'Zoopl_5'
   description   'Zooplnk biomass station 5'
   unit          '(gC/m3)'
   value          0.0000E+00
end-parameter
parameter 'Mussl_5'
   description   'Mussel  biomass station 5'
   unit          '(gC/m2)'
   value          0.0000E+00
end-parameter
parameter 'Zoopl_6'
   description   'Zooplnk biomass station 6'
   unit          '(gC/m3)'
   value          0.0000E+00
end-parameter
parameter 'Mussl_6'
   description   'Mussel  biomass station 6'
   unit          '(gC/m2)'
   value          0.0000E+00
end-parameter
parameter 'Zoopl_7'
   description   'Zooplnk biomass station 7'
   unit          '(gC/m3)'
   value          0.0000E+00
end-parameter
parameter 'Mussl_7'
   description   'Mussel  biomass station 7'
   unit          '(gC/m2)'
   value          0.0000E+00
end-parameter
parameter 'Zoopl_8'
   description   'Zooplnk biomass station 8'
   unit          '(gC/m3)'
   value          0.0000E+00
end-parameter
parameter 'Mussl_8'
   description   'Mussel  biomass station 8'
   unit          '(gC/m2)'
   value          0.0000E+00
end-parameter
parameter 'GrazStat'
   description   'Station used to derive grazing functions'
   unit          '(-)'
   value         -0.9990E+03
end-parameter
parameter 'VBurDMS1'
   description   'first order burial rate for layer S1'
   unit          '(1/d)'
   value          0.0000E+00
end-parameter
parameter 'SWSediment'
   description   'switch for sediment (0=fixed, 1=variable)'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'ExtVlDetC'
   description   'VL specific extinction coefficient DetC'
   unit          '(m2/gC)'
   value          0.4700E+00
end-parameter
output 'fSedIM1'
   description   'sedimentation flux IM1'
end-output
output 'fSedIM2'
   description   'sedimentation flux IM2'
end-output
output 'fSedIM3'
   description   'sedimentation flux IM3'
end-output
output 'Depth'
   description   'depth of segment'
end-output
output 'fBurS1AAP'
   description   'burial flux AAP from layer S1'
end-output
output 'TimMultBl'
   description   'ratio bloom/delwaq time step'
end-output
output 'ExtVl'
   description   'total extinction coefficient visible light'
end-output
output 'ExtVlPhyt'
   description   'VL extinction by phytoplankton'
end-output
output 'DayL'
   description   'daylength <0-1>'
end-output
output 'Phyt'
   description   'total carbon in phytoplankton'
end-output
output 'AlgN'
   description   'total nitrogen in algae'
end-output
output 'AlgP'
   description   'total phosphorus in algae'
end-output
output 'Chlfa'
   description   'Chlorophyll-a concentration'
end-output
output 'Limit Chlo'
   description   'total chlorophyll in algae'
end-output
output 'Limit nit'
   description   'limiting factor nitrogen'
end-output
output 'Limit pho'
   description   'limiting factor phosphorus'
end-output
output 'Limit sil'
   description   'limiting factor silicate'
end-output
output 'Limit e'
   description   'limiting factor energy'
end-output
output 'Limit gro'
   description   'limiting factor growth'
end-output
output 'Limit mor'
   description   'limiting factor mortality'
end-output
output 'fPPtot'
   description   'total net primary production'
end-output
output 'fFixNUpt'
   description   'uptake flux of nitrogen by fixation'
end-output
output 'BLOOMGRP'
   description   'algae group concentration'
end-output
output 'VSedDetC'
   description   'sedimentation velocity DetC'
end-output
output 'Tau'
   description   'total bottom shear stress'
end-output
output 'fSedDetC'
   description   'sedimentation flux DetC'
end-output
output 'fResS1DM'
   description   'total resuspension flux DM from layer S1'
end-output
output 'FrDetCS1'
   description   'fraction DetC in layer S1'
end-output
output 'Zooplank'
   description   'input concentration of zooplankton-grazer1'
end-output
output 'Mussel'
   description   'input concentration of Mussel'
end-output
output 'CZooplank'
   description   'calculated concentration of zooplankton-grazer1'
end-output
output 'CMussel'
   description   'calculated concentration of mussel-grazer2'
end-output
output 'SecchiDept'
   description   'Secchi depth'
end-output
output 'fSedFDI_E'
   description   'sedimentation flux algae FDIATOMS_E'
end-output
output 'fSedFDI_P'
   description   'sedimentation flux algae FDIATOMS_P'
end-output
output 'fSedGRE_E'
   description   'sedimentation flux algae GREENS_E'
end-output
output 'fSedGRE_P'
   description   'sedimentation flux algae GREENS_P'
end-output
output 'fSedMIC_E'
   description   'sedimentation flux algae MICROCYS_E'
end-output
output 'fSedMIC_N'
   description   'sedimentation flux algae MICROCYS_N'
end-output
output 'fSedMIC_P'
   description   'sedimentation flux algae MICROCYS_P'
end-output
output 'fSedMDI_E'
   description   'sedimentation flux algae MDIATOMS_E'
end-output
output 'fSedMDI_N'
   description   'sedimentation flux algae MDIATOMS_N'
end-output
output 'fSedMDI_P'
   description   'sedimentation flux algae MDIATOMS_P'
end-output
output 'fSedMFL_E'
   description   'sedimentation flux algae MFLAGELA_E'
end-output
output 'fSedMFL_P'
   description   'sedimentation flux algae MFLAGELA_P'
end-output
output 'fSedPHA_E'
   description   'sedimentation flux algae PHAEOCYS_E'
end-output
output 'fSedPHA_N'
   description   'sedimentation flux algae PHAEOCYS_N'
end-output
output 'fSedPHA_P'
   description   'sedimentation flux algae PHAEOCYS_P'
end-output
output 'VxSedAlg'
   description   'sedimentation velocity'
end-output
output 'fSedPHYT'
   description   'total sedimentation flux phytoplankton'
end-output
output 'fBurS1DM'
   description   'total burial flux DM from layer S1'
end-output
output 'fBurS1DetC'
   description   'burial flux DetC from layer S1'
end-output
output 'fSedDetN'
   description   'sedimentation flux DetN'
end-output
output 'fSedDetP'
   description   'sedimentation flux DetP'
end-output
output 'fSedDetSi'
   description   'sedimentation flux DetSi'
end-output
output 'fDfwastNH4'
   description   'diffusive waste flux NH4'
end-output
output 'fDfwastNO3'
   description   'diffusive waste flux NO3'
end-output
output 'fBurS1OOC'
   description   'burial flux OOC from layer S1'
end-output
output 'fDfwastPO4'
   description   'diffusive waste flux PO4'
end-output
output 'DfWstPO4_A'
   description   'A factor diffusive waste flux PO4'
end-output
output 'DfWstPO4_B'
   description   'B factor diffusive waste flux PO4'
end-output
output 'DfWastPO4'
   description   'calc. diffusive waste flux PO4'
end-output
output 'Salinity'
   description   'Salinity'
end-output
output 'SaturOXY'
   description   'saturation concentration'
end-output
output 'SatPercOXY'
   description   'Actual saturation percentage O2'
end-output
output 'AgeTR1'
   description   'calculated  AGE  for water from source 1'
end-output
output 'AgeTR2'
   description   'calculated  AGE  for water from source 2'
end-output
output 'AgeTR3'
   description   'calculated  AGE  for water from source 3'
end-output
output 'VSedIM1'
   description   'sedimentation velocity IM1'
end-output
output 'fResS1IM1'
   description   'resuspension flux IM1 from layer S1'
end-output
output 'fBurS1IM1'
   description   'burial flux of IM1 from layer S1'
end-output
output 'fResS1IM2'
   description   'resuspension flux IM2 from layer S1'
end-output
output 'fResS1IM3'
   description   'resuspension flux IM3 from layer S1'
end-output
output 'ActThS1'
   description   'actual thickness layer S1'
end-output
output 'IM1S1M2'
   description   'IM1 per m2 in layer S1'
end-output
output 'IM2S1M2'
   description   'IM2 per m2 in layer S1'
end-output
output 'IM3S1M2'
   description   'IM3 per m2 in layer S1'
end-output
output 'DetCS1M2'
   description   'DetC per m2 in layer S1'
end-output
output 'OOCS1M2'
   description   'OOC per m2 in layer S1'
end-output
output 'AAPS1M2'
   description   'adsorbed O-PO4 per m2 in layer S1'
end-output
output 'DetNS1M2'
   description   'DetN per m2 in layer S1'
end-output
output 'DetPS1M2'
   description   'DetP per m2 in layer S1'
end-output
output 'DetSiS1M2'
   description   'DetSi per m2 in layer S1'
end-output
output 'OONS1M2'
   description   'OON per m2 in layer S1'
end-output
output 'OOPS1M2'
   description   'OOP per m2 in layer S1'
end-output
output 'OOSiS1M2'
   description   'OOSi per m2 in layer S1'
end-output
output 'fBurS1Gree'
   description   'burial flux Greens from layer S1'
end-output
output 'fBurS1Diat'
   description   'burial flux Diatoms from layer S1'
end-output
output 'ExtVlOSS'
   description   'VL extinction by POC'
end-output
output 'ExtVlBak'
   description   'background extinction visible light'
end-output
output 'ExtVlISS'
   description   'VL extinction by inorganic suspended matter'
end-output
output 'SS'
   description   'suspended solids'
end-output
output 'Zoopl_1'
   description   'Zooplnk biomass station 1'
end-output
output 'Mussl_1'
   description   'Mussel  biomass station 1'
end-output
output 'Zoopl_2'
   description   'Zooplnk biomass station 2'
end-output
output 'Mussl_2'
   description   'Mussel  biomass station 2'
end-output
output 'Zoopl_3'
   description   'Zooplnk biomass station 3'
end-output
output 'Mussl_3'
   description   'Mussel  biomass station 3'
end-output
output 'Zoopl_4'
   description   'Zooplnk biomass station 4'
end-output
output 'Mussl_4'
   description   'Mussel  biomass station 4'
end-output
output 'Zoopl_5'
   description   'Zooplnk biomass station 5'
end-output
output 'Mussl_5'
   description   'Mussel  biomass station 5'
end-output
output 'Zoopl_6'
   description   'Zooplnk biomass station 6'
end-output
output 'Mussl_6'
   description   'Mussel  biomass station 6'
end-output
output 'Zoopl_7'
   description   'Zooplnk biomass station 7'
end-output
output 'Mussl_7'
   description   'Mussel  biomass station 7'
end-output
output 'Zoopl_8'
   description   'Zooplnk biomass station 8'
end-output
output 'Mussl_8'
   description   'Mussel  biomass station 8'
end-output
output 'GrazStat'
   description   'Station used to derive grazing functions'
end-output
output 'fSedDM'
   description   'total sedimentation flux dry matter'
end-output
output 'TotN'
   description   'total nitrogen (including algae)'
end-output
output 'DIN'
   description   'dissolved inorganic nitrogen'
end-output
output 'TotP'
   description   'total phosphorus (including algae)'
end-output
output 'FDIATOMS'
   description   'Freshwater Diatoms'
end-output
output 'GREENS'
   description   'Green algae'
end-output
output 'MDIATOMS'
   description   'Marine Diatoms'
end-output
output 'MFLAGELA'
   description   'Marine flagellates'
end-output
output 'MICROCYS'
   description   'Microcystis'
end-output
output 'PHAEOCYS'
   description   'Phaeocystis'
end-output
active-processes
   name  'AdsPO4AAP' 'Ad(De)Sorption ortho phosphorus to inorg. matter'
   name  'Sed_AAP' 'Sedimentation AAP (adsorbed PO4)'
   name  'Res_AAP' 'Resuspension AAP (adsorbed PO4)'
   name  'Deso_AAPS1' 'Desorption of adsorbed phosphates in sediment S1'
   name  'BurS1_AAP' 'Burial of AAP (adsorbed PO4) from sediment S1'
   name  'BLOOM_P' 'BLOOM II algae module'
   name  'WM_DetC' 'Mineralisation detritus carbon'
   name  'SedDetC' 'Sedimentation detritus carbon'
   name  'Res_DetC' 'Resuspension detritus carbon'
   name  'CONSBL' 'Grazing module'
   name  'Secchi' 'Extinction of visible-light (370-680nm)'
   name  'BMS1_DetC' 'Mineralisation detritus carbon in sediment S1'
   name  'SedPhBlo_P' 'Sum sedimentation of algae - Bloom'
   name  'BurS1_DetC' 'Burial detritus carbon from sediment S1'
   name  'WM_DetN' 'Mineralisation detritus nitrogen'
   name  'SedN_Det' 'Sedim. nutrients in detritus'
   name  'ResN_Det' 'Resuspension nutrients in detritus'
   name  'BMS1_DetN' 'Mineralisation detritus nitrogen in sediment S1'
   name  'BurS1N_Det' 'Burial nutrients in detritus from sediment S1'
   name  'WM_DetP' 'Mineralisation detritus phosphorus'
   name  'BMS1_DetP' 'Mineralisation detritus phosphorus in sediment S1'
   name  'WM_DetSi' 'Mineralisation detritus silicium'
   name  'BMS1_DetSi' 'Mineralisation detritus silica in sediment S1'
   name  'Nitrif_NH4' 'Nitrification of ammonium'
   name  'BMS1_OON' 'Mineralisation other organic N in sediment S1'
   name  'WM_OON' 'Mineralisation other organic nitrogen'
   name  'Dfwast_NH4' 'Diffusive waste NH4'
   name  'DenSed_NO3' 'Denitrification in sediment'
   name  'DenWat_NO3' 'Denitrification in water column'
   name  'Dfwast_NO3' 'Diffusive waste NO3'
   name  'WM_OOC' 'Mineralisation other organic carbon'
   name  'Sed_OOC' 'Sedimentation other organic carbon'
   name  'Res_OOC' 'Resuspension other organic carbon'
   name  'BMS1_OOC' 'Mineralisation other organic C in sediment S1'
   name  'BurS1_OOC' 'Burial other organic carbon from sediment S1'
   name  'SedN_OOC' 'Sedim. nutrients in OOC'
   name  'ResN_OO' 'Resuspension nutrients in other organics'
   name  'BurS1N_OO' 'Burial nutrients in oth. organics from sediment S1'
   name  'WM_OOP' 'Mineralisation other organic phosphorus'
   name  'BMS1_OOP' 'Mineralisation other organic P in sediment S1'
   name  'WM_OOSi' 'Mineralisation other organic silica'
   name  'BMS1_OOSi' 'Mineralisation other organic Si in sediment S1'
   name  'Dfwast_PO4' 'Diffusive waste PO4'
   name  'SEDALG' 'Sedimentation of algae species'
   name  'RearOXY' 'Reaeration of oxygen'
   name  'Age1' 'Age of water from source 1'
   name  'Age2' 'Age of water from source 2'
   name  'Age3' 'Age of water from source 3'
   name  'Sed_IM1' 'Sedimentation IM1'
   name  'Res_IM1' 'Resuspension 1st inorganic matter'
   name  'BurS1_IM1' 'Burial 1st-inorganic matter from S1'
   name  'Sed_IM2' 'Sedimentation IM2'
   name  'Res_IM2' 'Resuspension 2nd inorganic matter'
   name  'Sed_IM3' 'Sedimentation IM3'
   name  'Res_IM3' 'Resuspension 3rd inorganic matter'
   name  'DynDepth' 'dynamic calculation of the depth'
   name  'Sum_ResS1' 'Sum of (in)organics resuspending from S1'
   name  'S1_Comp' 'Composition sediment layer S1'
   name  'Sum_BurS1' 'Sum of (in)organic substances buried from S1'
   name  'Extinc_VL' 'Extinction of visible-light (370-680nm)'
   name  'EXTINABVLP' 'Extinction of light by algae (Bloom)'
   name  'Daylength' 'Daylength calculation'
   name  'CalVS_DetC' 'Sedimentation velocity DetC = f (Temp SS Sal)'
   name  'CalTau' 'Calculation of bottom friction'
   name  'Res_DM' 'Resuspension total bottom material (dry mass)'
   name  'ForGra' 'Select forcing of grazers'
   name  'Bur_DM' 'Burial total bottom mass (dry matter)'
   name  'POC_Dyn' 'Composition of POC (Dynamo & Bloom)'
   name  'Salin' 'calculation of salinity from chloride'
   name  'SaturOXY' 'Saturation concentration oxygen'
   name  'TotDepth' 'depth water column'
   name  'BurS1_Gree' 'Burial green algae from sediment S1'
   name  'BurS1_Diat' 'Burial diatoms from sediment S1'
   name  'ExtPODVL' 'Extinction of light by POC (Dynamo & Bloom)'
   name  'Compos' 'Composition'
   name  'Sum_Sedim' 'Total of all sedimenting substances'
end-active-processes
