GR_1.2
GRID id '1' ci '1' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'T1_h1' '2' 0 0 '' 'T1_h1_Q=0' '' <
400 0 '10' 'T1_h2' '8' 400 0 '' 'T1_h2' '' <
500 0 '8' 'T1_h3' '' 500 0 '' 'T1_h3' '' <
tble grid
GRID id '2' ci '2' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'T2_h3' '3' 500 50 '' 'T2_h3' '' <
150 0 '3' 'T2_h2' '4' 350 50 '' 'T2_h2' '' <
500 0 '21' 'T2_h1' '' 0 50 '' 'T2_h1_Q=0' '' <
tble grid
GRID id '3' ci '3' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'T3_h1' 'T3_R1' 0 100 '' 'T3_h1_h=2m' 'T3_R1' <
400 0 '14' 'T3_h2' '5' 400 100 '' 'T3_h2' '' <
500 0 '5' 'T3_h3' '' 500 100 '' 'T3_h3' '' <
tble grid
GRID id '4' ci '4' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'T4_h3' '7' 500 150 '' 'T4_h3' '' <
150 0 '7' 'T4_h2' 'T4_R2' 350 150 '' 'T4_h2' 'T4_R2' <
500 0 '12' 'T4_h1' '' 0 150 '' 'T4_h1_h=2m' '' <
tble grid
GRID id '5' ci '5' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'T5_h1' '1' 0 200 '' 'T5_h1_Qh_rel' '' <
400 0 '22' 'T5_h2' '17' 400 200 '' 'T5_h2' '' <
500 0 '17' 'T5_h3' '' 500 200 '' 'T5_h3' '' <
tble grid
GRID id '6' ci '6' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'T6_h3' '16' 500 250 '' 'T6_h3' '' <
150 0 '16' 'T6_h2' '18' 350 250 '' 'T6_h2' '' <
500 0 '20' 'T6_h1' '' 0 250 '' 'T6_h1_Qh_rel' '' <
tble grid
GRID id '7' ci '7' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'T7_h6' '25' 500 300 '' '' '' <
50 0 'T7_R5' 'T7_h5' 'T7_R4' 450 300 'T7_R5' '' 'T7_R4' <
300 0 '9' 'T7_h4' 'T7_R3' 200 300 '9' '' 'T7_R3' <
350 0 'T7_R3' 'T7_h3' '27' 150 300 'T7_R3' '' '' <
400 0 'T7_R2' 'T7_h2' 'T7_R1' 100 300 'T7_R2' '' 'T7_R1' <
500 0 '24' 'T7_h1' '' 0 300 '' 'T7_h1_h=2m' '' <
tble grid
