///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DHYDRO.Modules.ModelSettings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SetSpectralDomainSettings recording.
    /// </summary>
    [TestModule("041bf6cb-b1bf-4d92-a33d-143fb5e45abf", ModuleType.Recording, 1)]
    public partial class SetSpectralDomainSettings : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DHYDRO.DHYDRORepository repository.
        /// </summary>
        public static global::DHYDRO.DHYDRORepository repo = global::DHYDRO.DHYDRORepository.Instance;

        static SetSpectralDomainSettings instance = new SetSpectralDomainSettings();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SetSpectralDomainSettings()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SetSpectralDomainSettings Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.ComboBoxFirstRow' at Center.", repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.ComboBoxFirstRowInfo, new RecordItemIndex(0));
            repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.ComboBoxFirstRow.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SettingsContextMenu.Circle' at Center.", repo.SettingsContextMenu.CircleInfo, new RecordItemIndex(1));
            repo.SettingsContextMenu.Circle.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow2' at Center.", repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow2Info, new RecordItemIndex(2));
            repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow2.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(3));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '36' with focus on 'DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow2'.", repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow2Info, new RecordItemIndex(4));
            repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow2.PressKeys("36");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow5' at Center.", repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow5Info, new RecordItemIndex(5));
            repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow5.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(6));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '24' with focus on 'DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow5'.", repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow5Info, new RecordItemIndex(7));
            repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow5.PressKeys("24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow6' at Center.", repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow6Info, new RecordItemIndex(8));
            repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow6.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(9));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0,03' with focus on 'DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow6'.", repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow6Info, new RecordItemIndex(10));
            repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow6.PressKeys("0,03");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow7' at Center.", repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow7Info, new RecordItemIndex(11));
            repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow7.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(12));
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow7'.", repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow7Info, new RecordItemIndex(13));
            repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.TextRow7.PressKeys("1");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
