///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DHYDRO.Modules.ModelSettings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SetTimeFrameSettings recording.
    /// </summary>
    [TestModule("5db26d24-9913-4622-af11-98104ae5007f", ModuleType.Recording, 1)]
    public partial class SetTimeFrameSettings : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DHYDRO.DHYDRORepository repository.
        /// </summary>
        public static global::DHYDRO.DHYDRORepository repo = global::DHYDRO.DHYDRORepository.Instance;

        static SetTimeFrameSettings instance = new SetTimeFrameSettings();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SetTimeFrameSettings()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SetTimeFrameSettings Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '0.7' on item 'DSWindow.ListView.MainTabControl.TimeFrame.MaxCourantNrField'.", repo.DSWindow.ListView.MainTabControl.TimeFrame.MaxCourantNrFieldInfo, new RecordItemIndex(0));
            repo.DSWindow.ListView.MainTabControl.TimeFrame.MaxCourantNrField.Element.SetAttributeValue("Text", "0.7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '2001-01-01 00:00:00' on item 'DSWindow.ListView.MainTabControl.TimeFrame.ReferenceTimeField'.", repo.DSWindow.ListView.MainTabControl.TimeFrame.ReferenceTimeFieldInfo, new RecordItemIndex(1));
            repo.DSWindow.ListView.MainTabControl.TimeFrame.ReferenceTimeField.Element.SetAttributeValue("Text", "2001-01-01 00:00:00");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '0' on item 'DSWindow.ListView.MainTabControl.TimeFrame.TimeZoneField'.", repo.DSWindow.ListView.MainTabControl.TimeFrame.TimeZoneFieldInfo, new RecordItemIndex(2));
            repo.DSWindow.ListView.MainTabControl.TimeFrame.TimeZoneField.Element.SetAttributeValue("Text", "0");
            Delay.Milliseconds(0);
            
            // Set to: 0d00:05:00.000
            Report.Log(ReportLevel.Info, "Set value", "Set to: 0d00:05:00.000\r\nSetting attribute Text to '0' on item 'DSWindow.ListView.MainTabControl.TimeFrame.UserTimeStep.DaysField'.", repo.DSWindow.ListView.MainTabControl.TimeFrame.UserTimeStep.DaysFieldInfo, new RecordItemIndex(3));
            repo.DSWindow.ListView.MainTabControl.TimeFrame.UserTimeStep.DaysField.Element.SetAttributeValue("Text", "0");
            Delay.Milliseconds(0);
            
            // Set to: 0d00:05:00.000
            Report.Log(ReportLevel.Info, "Set value", "Set to: 0d00:05:00.000\r\nSetting attribute Text to '00' on item 'DSWindow.ListView.MainTabControl.TimeFrame.UserTimeStep.HoursField'.", repo.DSWindow.ListView.MainTabControl.TimeFrame.UserTimeStep.HoursFieldInfo, new RecordItemIndex(4));
            repo.DSWindow.ListView.MainTabControl.TimeFrame.UserTimeStep.HoursField.Element.SetAttributeValue("Text", "00");
            Delay.Milliseconds(0);
            
            // Set to: 0d00:05:00.000
            Report.Log(ReportLevel.Info, "Set value", "Set to: 0d00:05:00.000\r\nSetting attribute Text to '05' on item 'DSWindow.ListView.MainTabControl.TimeFrame.UserTimeStep.MinutesField'.", repo.DSWindow.ListView.MainTabControl.TimeFrame.UserTimeStep.MinutesFieldInfo, new RecordItemIndex(5));
            repo.DSWindow.ListView.MainTabControl.TimeFrame.UserTimeStep.MinutesField.Element.SetAttributeValue("Text", "05");
            Delay.Milliseconds(0);
            
            // Set to: 0d00:05:00.000
            Report.Log(ReportLevel.Info, "Set value", "Set to: 0d00:05:00.000\r\nSetting attribute Text to '00' on item 'DSWindow.ListView.MainTabControl.TimeFrame.UserTimeStep.SecondsField'.", repo.DSWindow.ListView.MainTabControl.TimeFrame.UserTimeStep.SecondsFieldInfo, new RecordItemIndex(6));
            repo.DSWindow.ListView.MainTabControl.TimeFrame.UserTimeStep.SecondsField.Element.SetAttributeValue("Text", "00");
            Delay.Milliseconds(0);
            
            // Set to: 0d00:05:00.000
            Report.Log(ReportLevel.Info, "Set value", "Set to: 0d00:05:00.000\r\nSetting attribute Text to '000' on item 'DSWindow.ListView.MainTabControl.TimeFrame.UserTimeStep.MilliSecondsField'.", repo.DSWindow.ListView.MainTabControl.TimeFrame.UserTimeStep.MilliSecondsFieldInfo, new RecordItemIndex(7));
            repo.DSWindow.ListView.MainTabControl.TimeFrame.UserTimeStep.MilliSecondsField.Element.SetAttributeValue("Text", "000");
            Delay.Milliseconds(0);
            
            // Set to: 0d06:00:00.000
            Report.Log(ReportLevel.Info, "Set value", "Set to: 0d06:00:00.000\r\nSetting attribute Text to '0' on item 'DSWindow.ListView.MainTabControl.TimeFrame.NodalUpdateInterval.DaysField'.", repo.DSWindow.ListView.MainTabControl.TimeFrame.NodalUpdateInterval.DaysFieldInfo, new RecordItemIndex(8));
            repo.DSWindow.ListView.MainTabControl.TimeFrame.NodalUpdateInterval.DaysField.Element.SetAttributeValue("Text", "0");
            Delay.Milliseconds(0);
            
            // Set to: 0d06:00:00.000
            Report.Log(ReportLevel.Info, "Set value", "Set to: 0d06:00:00.000\r\nSetting attribute Text to '06' on item 'DSWindow.ListView.MainTabControl.TimeFrame.NodalUpdateInterval.HoursField'.", repo.DSWindow.ListView.MainTabControl.TimeFrame.NodalUpdateInterval.HoursFieldInfo, new RecordItemIndex(9));
            repo.DSWindow.ListView.MainTabControl.TimeFrame.NodalUpdateInterval.HoursField.Element.SetAttributeValue("Text", "06");
            Delay.Milliseconds(0);
            
            // Set to: 0d06:00:00.000
            Report.Log(ReportLevel.Info, "Set value", "Set to: 0d06:00:00.000\r\nSetting attribute Text to '00' on item 'DSWindow.ListView.MainTabControl.TimeFrame.NodalUpdateInterval.MinutesField'.", repo.DSWindow.ListView.MainTabControl.TimeFrame.NodalUpdateInterval.MinutesFieldInfo, new RecordItemIndex(10));
            repo.DSWindow.ListView.MainTabControl.TimeFrame.NodalUpdateInterval.MinutesField.Element.SetAttributeValue("Text", "00");
            Delay.Milliseconds(0);
            
            // Set to: 0d06:00:00.000
            Report.Log(ReportLevel.Info, "Set value", "Set to: 0d06:00:00.000\r\nSetting attribute Text to '00' on item 'DSWindow.ListView.MainTabControl.TimeFrame.NodalUpdateInterval.SecondsField'.", repo.DSWindow.ListView.MainTabControl.TimeFrame.NodalUpdateInterval.SecondsFieldInfo, new RecordItemIndex(11));
            repo.DSWindow.ListView.MainTabControl.TimeFrame.NodalUpdateInterval.SecondsField.Element.SetAttributeValue("Text", "00");
            Delay.Milliseconds(0);
            
            // Set to: 0d06:00:00.000
            Report.Log(ReportLevel.Info, "Set value", "Set to: 0d06:00:00.000\r\nSetting attribute Text to '000' on item 'DSWindow.ListView.MainTabControl.TimeFrame.NodalUpdateInterval.MilliSecondsField'.", repo.DSWindow.ListView.MainTabControl.TimeFrame.NodalUpdateInterval.MilliSecondsFieldInfo, new RecordItemIndex(12));
            repo.DSWindow.ListView.MainTabControl.TimeFrame.NodalUpdateInterval.MilliSecondsField.Element.SetAttributeValue("Text", "000");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '30' on item 'DSWindow.ListView.MainTabControl.TimeFrame.MaxTimeStepField'.", repo.DSWindow.ListView.MainTabControl.TimeFrame.MaxTimeStepFieldInfo, new RecordItemIndex(13));
            repo.DSWindow.ListView.MainTabControl.TimeFrame.MaxTimeStepField.Element.SetAttributeValue("Text", "30");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '1' on item 'DSWindow.ListView.MainTabControl.TimeFrame.InitialTimeStepField'.", repo.DSWindow.ListView.MainTabControl.TimeFrame.InitialTimeStepFieldInfo, new RecordItemIndex(14));
            repo.DSWindow.ListView.MainTabControl.TimeFrame.InitialTimeStepField.Element.SetAttributeValue("Text", "1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '2001-01-01 00:00:00' on item 'DSWindow.ListView.MainTabControl.TimeFrame.StartTimeField'.", repo.DSWindow.ListView.MainTabControl.TimeFrame.StartTimeFieldInfo, new RecordItemIndex(15));
            repo.DSWindow.ListView.MainTabControl.TimeFrame.StartTimeField.Element.SetAttributeValue("Text", "2001-01-01 00:00:00");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '2001-01-02 00:00:00' on item 'DSWindow.ListView.MainTabControl.TimeFrame.StopTimeField'.", repo.DSWindow.ListView.MainTabControl.TimeFrame.StopTimeFieldInfo, new RecordItemIndex(16));
            repo.DSWindow.ListView.MainTabControl.TimeFrame.StopTimeField.Element.SetAttributeValue("Text", "2001-01-02 00:00:00");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
