substance 'EIGEN' active
   description        'water dat bij aanvang in systeem aanwezig is'
   concentration-unit '{no unit}'
   waste-load-unit    '-'
end-substance
substance 'dis32' active
   description        'regenwater afkomstig uit rwa district 32'
   concentration-unit '-'
   waste-load-unit    '-'
end-substance
substance 'dis33' active
   description        'regenwater afkomstig uit rwa district 33'
   concentration-unit '-'
   waste-load-unit    '-'
end-substance
substance 'dis34' active
   description        'regenwater afkomstig uit rwa district 34'
   concentration-unit '-'
   waste-load-unit    '-'
end-substance
substance 'dis39a' active
   description        'regenwater afkomstig uit rwa district 39'
   concentration-unit '-'
   waste-load-unit    '-'
end-substance
substance 'dis39b' active
   description        'regenwater afkomstig uit rwa district 39'
   concentration-unit '-'
   waste-load-unit    '-'
end-substance
substance 'INlaat' active
   description        'inlaatwater'
   concentration-unit '-'
   waste-load-unit    '-'
end-substance
output 'Z'
   description   'water depth'
end-output
output 'dt'
   description   'timestep of Duflow-quality calculation in seconds'
end-output
output 'TOT'
   description   'EIGEN+dis32+dis33+dis34+dis39a+dis39b+INlaat+0.000'
end-output
output 'EIG'
   description   'EIGEN/TOT'
end-output
output 'd32'
   description   'dis32/TOT'
end-output
output 'd33'
   description   'dis33/TOT'
end-output
output 'd34'
   description   'dis34/TOT'
end-output
output 'd39a'
   description   'dis39a/TOT'
end-output
output 'd39b'
   description   'dis39b/TOT'
end-output
output 'INL'
   description   'INLAAT/TOT'
end-output
active-processes
   name  'HydDuflow' 'HydDuflow'
   name  'FRACT' 'FRACT'
end-active-processes
