                                                                                
 Found -A command line switch                                                   
 ONLY activated processes are switched on                                       
 Found -NP command line switch                                                  
 No processes from the process definition file are switched on                  


 Model :            Water quality calculation Sobek-WQ      
                                                            


 Run   :                                                    
                    T0: 1996.01.01 00:00:00  (scu=       1s)


 
 Using process definition file : proc_def                                
 Version number                :       4.52
 Serial                        :          1
 
 
total number of substances with fractions :  0
 WARNING: circular input output relation detected in process library
# Determining which processes can be switched on                                                    
                                                                                                    
                                                                                                    
# determinig the processes to model the substances.                                                 
                                                                                                    
-fluxes for [Cl                  ]                                                                  
 no fluxes found                                                                                    
-dispersion for [Cl                  ]                                                              
 no dispersions found                                                                               
-velocity for [Cl                  ]                                                                
 no velocity found                                                                                  
                                                                                                    
# locating processes for requested output                                                           
                                                                                                    
# determining the input for the processes (in reversed order)                                       
                                                                                                    
# determining the use of the delwaq input                                       
                                                                                
 info: constant [Iteration ] is not used by the proces system                   
 info: constant [VWIND     ] is not used by the proces system                   
 info: constant [WINDDIR   ] is not used by the proces system                   
 info: constant [NATTEMP   ] is not used by the proces system                   
 info: constant [RAD       ] is not used by the proces system                   
 info: parameter [Xseg      ] is not used by the proces system                  
 info: parameter [Yseg      ] is not used by the proces system                  
 info: segment function [Chezy     ] is not used by the proces system           
 info: segment function [Surf      ] is not used by the proces system           
 info: segment function [Velocity  ] is not used by the proces system           
 info: segment function [Width     ] is not used by the proces system           
                                                                                
# locating requested output from active processes                                                   
                                                                                                    
                                                                                                    
