GR_1.2
GRID id 'R_1' ci 'R_1' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'NOD00000' 'R_1_1' 0 0 '' '' '' <
250 0 'R_1_3' 'NOD00001' '' 250 0 '' '' '' <
tble grid
GRID id 'R_2' ci 'R_2' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'NOD00001' 'R_2_1' 250 0 '' '' '' <
250 0 'R_2_3' 'NOD00002' '' 500 0 '' '' '' <
tble grid
GRID id 'R_3' ci 'R_3' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'NOD00002' 'R_3_1' 500 0 '' '' '' <
250 0 'R_3_3' 'NOD00003' '' 750 0 '' '' '' <
tble grid
GRID id 'R_4' ci 'R_4' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'NOD00003' 'R_4_1' 750 0 '' '' '' <
250 0 'R_4_3' 'NOD00004' '' 1000 0 '' '' '' <
tble grid
GRID id 'R_5' ci 'R_5' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'NOD00004' 'R_5_1' 1000 0 '' '' '' <
250 0 'R_5_3' 'NOD00005' '' 1250 0 '' '' '' <
tble grid
GRID id 'R_6' ci 'R_6' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'NOD00005' 'R_6_1' 1250 0 '' '' '' <
250 0 'R_6_3' 'NOD00006' '' 1500 0 '' '' '' <
tble grid
GRID id 'R_7' ci 'R_7' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'NOD00006' 'R_7_1' 1500 0 '' '' '' <
250 0 'R_7_3' 'NOD00007' '' 1750 0 '' '' '' <
tble grid
GRID id 'R_8' ci 'R_8' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'NOD00007' 'R_8_1' 1750 0 '' '' '' <
250 0 'R_8_3' 'NOD00008' '' 2000 0 '' '' '' <
tble grid
