CR_1.1
CRSN id 'P_1_1' nm '' ci 'R_1' lc 1 crsn
CRSN id 'P_1_2' nm '' ci 'R_1' lc 249 crsn
CRSN id 'P_2_1' nm '' ci 'R_2' lc 1 crsn
CRSN id 'P_2_2' nm '' ci 'R_2' lc 249 crsn
CRSN id 'P_3_1' nm '' ci 'R_3' lc 1 crsn
CRSN id 'P_3_2' nm '' ci 'R_3' lc 249 crsn
CRSN id 'P_4_1' nm '' ci 'R_4' lc 1 crsn
CRSN id 'P_4_2' nm '' ci 'R_4' lc 249 crsn
CRSN id 'P_5_1' nm '' ci 'R_5' lc 1 crsn
CRSN id 'P_5_2' nm '' ci 'R_5' lc 249 crsn
CRSN id 'P_6_1' nm '' ci 'R_6' lc 1 crsn
CRSN id 'P_6_2' nm '' ci 'R_6' lc 249 crsn
CRSN id 'P_7_1' nm '' ci 'R_7' lc 1 crsn
CRSN id 'P_7_2' nm '' ci 'R_7' lc 249 crsn
CRSN id 'P_8_1' nm '' ci 'R_8' lc 1 crsn
CRSN id 'P_8_2' nm '' ci 'R_8' lc 249 crsn
