

ITEM
USEFOR 'Boundary Flow' 'Boundary Flow'
CONCENTRATION
USEFOR 'CWTOT' 'CWTOT'
USEFOR 'POCW' 'POCW'
USEFOR 'SSW' 'SSW'
USEFOR 'DOCW' 'DOCW'
USEFOR 'AOCW' 'AOCW'
DATA           'CWTOT'       'POCW'        'SSW'         'DOCW'        'AOCW' 
              0             0             0             0             0 


ITEM
USEFOR 'Lateral inflow' 'Lateral inflow'
CONCENTRATION
USEFOR 'CWTOT' 'CWTOT'
USEFOR 'POCW' 'POCW'
USEFOR 'SSW' 'SSW'
USEFOR 'DOCW' 'DOCW'
USEFOR 'AOCW' 'AOCW'
DATA           'CWTOT'       'POCW'        'SSW'         'DOCW'        'AOCW' 
              0             0             0             0             0 

