///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DHYDRO.Modules.Map
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DoubleClickOnMap recording.
    /// </summary>
    [TestModule("370e08fb-dfdd-4ca5-a04a-006d54548a71", ModuleType.Recording, 1)]
    public partial class DoubleClickOnMap : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DHYDRO.DHYDRORepository repository.
        /// </summary>
        public static global::DHYDRO.DHYDRORepository repo = global::DHYDRO.DHYDRORepository.Instance;

        static DoubleClickOnMap instance = new DoubleClickOnMap();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DoubleClickOnMap()
        {
            PixelCoordinates = "0;0";
            WorldCoordinates = "0;0";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DoubleClickOnMap Instance
        {
            get { return instance; }
        }

#region Variables

        string _PixelCoordinates;

        /// <summary>
        /// Gets or sets the value of variable PixelCoordinates.
        /// </summary>
        [TestVariable("d7b4cda5-6f79-485b-8af1-0a83d5a7fdbc")]
        public string PixelCoordinates
        {
            get { return _PixelCoordinates; }
            set { _PixelCoordinates = value; }
        }

        string _WorldCoordinates;

        /// <summary>
        /// Gets or sets the value of variable WorldCoordinates.
        /// </summary>
        [TestVariable("d3ba1fc1-e053-43c3-9b35-0345077993ee")]
        public string WorldCoordinates
        {
            get { return _WorldCoordinates; }
            set { _WorldCoordinates = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'DSWindow.ListView.CentralMapContainer.CentralMap' at position from variable $PixelCoordinates.", repo.DSWindow.ListView.CentralMapContainer.CentralMapInfo, new RecordItemIndex(0));
            repo.DSWindow.ListView.CentralMapContainer.CentralMap.DoubleClick(PixelCoordinates, 10);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
