using System;
using System.Collections.Generic;
using DeltaShell.NGHS.IO.Handlers;
using DeltaShell.Plugins.FMSuite.Common;
using DeltaShell.Plugins.FMSuite.Common.IO.Files;
using DeltaShell.Plugins.FMSuite.Common.IO.Files.Structures;
using DeltaShell.Plugins.FMSuite.FlowFM.ModelDefinition;
using DeltaShell.Plugins.FMSuite.FlowFM.Properties;
using log4net;

namespace DeltaShell.Plugins.FMSuite.FlowFM.IO.Files
{
    public class MduFileReader : FMSuiteFileBase
    {
        private static readonly ILog log = LogManager.GetLogger(typeof(MduFileReader));

        private static readonly Dictionary<string, string> backwardsCompatiblePropertyMapping =
            new Dictionary<string, string>
            {
                {"enclosurefile", "GridEnclosureFile"},
                {"trtdt", "DtTrt"},
                {"botlevuni", "BedLevUni"},
                {"botlevtype", "BedLevType"},
                {"mduformatversion", "FileVersion"}
            };

        private readonly Dictionary<string, string> mduComments = new Dictionary<string, string>();

        public void Read(string filePath, WaterFlowFMModelDefinition definition)
        {
            var logHandler = new LogHandler("reading the mdu file", log);
            OpenInputFile(filePath);
            IgnoreCommentLines(new[]
            {
                "# Generated on",
                "# Generated by",
                "# Deltares,"
            });

            try
            {
                string currentGroupName = null;

                string line = GetNextLine();
                var readNextLine = true;
                while (line != null)
                {
                    line = line.Trim().Replace(
                        "\0", " "); // some mdu files contain null characters (generated by interactor GUI)
                    if (line.StartsWith("["))
                    {
                        // group line
                        int endIndex = line.LastIndexOf("]", StringComparison.Ordinal);
                        if (endIndex < 2)
                        {
                            throw new FormatException(
                                string.Format("Invalid group on line {0} in file {1}", LineNumber, filePath));
                        }

                        currentGroupName = line.Substring(1, endIndex - 1).Trim();
                        string currentGroupNameLowerCase = currentGroupName.ToLower();

                        if (currentGroupNameLowerCase.Equals("model"))
                        {
                            currentGroupName = "General";
                        }
                    }
                    else
                    {
                        // property line
                        string mduPropertyName;
                        string mduPropertyLowerCase;
                        string[] fields = GetPropertyLine(line, out mduPropertyName, out mduPropertyLowerCase);

                        if (backwardsCompatiblePropertyMapping.ContainsKey(mduPropertyLowerCase))
                        {
                            mduPropertyName = backwardsCompatiblePropertyMapping[mduPropertyLowerCase];
                        }

                        if (mduPropertyLowerCase.Equals("hdam"))
                        {
                            line = GetNextLine();
                            continue;
                        }

                        mduPropertyLowerCase = mduPropertyName.ToLower();

                        string mduPropertyValue = fields[1].Trim();

                        if (mduPropertyLowerCase == KnownProperties.FixedWeirScheme && mduPropertyValue != "0" &&
                            mduPropertyValue != "6" && mduPropertyValue != "8" && mduPropertyValue != "9")
                        {
                            log.Warn(string.Format(
                                         "Obsolete Fixed Weir Scheme {0} detected and it will be corrected to the default Numerical Scheme.",
                                         mduPropertyValue));
                            mduPropertyValue = "6";
                        }

                        GetPropertyComment(line, mduPropertyName, fields.Length > 2, false);

                        string mduComment = null;
                        if (mduComments.ContainsKey(mduPropertyName))
                        {
                            mduComment = mduComments[mduPropertyName];
                        }

                        bool isKnownProperty = definition.ContainsProperty(mduPropertyName);

                        WaterFlowFMProperty currentProperty;
                        if (isKnownProperty)
                        {
                            currentProperty = definition.GetModelProperty(mduPropertyName);
                        }
                        else
                        {
                            // create definition for unknown property:
                            WaterFlowFMPropertyDefinition propDef =
                                WaterFlowFMPropertyDefinitionCreator.CreateForCustomProperty(
                                    currentGroupName,
                                    mduPropertyName,
                                    mduComment);

                            currentProperty = new WaterFlowFMProperty(propDef, mduPropertyValue);

                            definition.AddProperty(currentProperty);
                        }

                        if (!string.IsNullOrEmpty(mduPropertyValue))
                        {
                            if (mduPropertyValue.EndsWith(@"\"))
                            {
                                mduPropertyValue = GetMduPropertyMultipleLineValueRecursive(mduPropertyName,
                                                                                            mduPropertyValue,
                                                                                            ref line,
                                                                                            ref readNextLine);
                            }

                            try
                            {
                                currentProperty.SetValueAsString(mduPropertyValue);
                            }
                            catch (FormatException e) when (e.InnerException is ArgumentNullException || e.InnerException is FormatException)
                            {
                                logHandler.ReportWarningFormat(Resources.MduFile_ReadProperties_An_unsupported_option_for_0_has_been_detected,
                                                               currentProperty.PropertyDefinition.Caption);
                            }

                            if (mduComments.ContainsKey(mduPropertyName) && !isKnownProperty)
                            {
                                currentProperty.PropertyDefinition.Description = mduComments[mduPropertyName];
                            }
                        }
                    }

                    if (readNextLine)
                    {
                        line = GetNextLine();
                    }

                    readNextLine = true; //Reset it if needed.
                }
            }
            finally
            {
                logHandler.LogReport();
                CloseInputFile();
            }

            definition.GetModelProperty(KnownProperties.RefDate).Value =
                FMParser.ParseFMDateTime(definition.GetModelProperty(KnownProperties.RefDate).GetValueAsString());

            definition.SetGuiTimePropertiesFromMduProperties();

            // update the heat flux model in the definition, because the event of KnownProperties.Temperature is not bubbled during loading of an mdu file.
            definition.UpdateHeatFluxModel();

            // update the write shape file properties as they are not visible in the gui.
            definition.UpdateWriteOutputSnappedFeatures();
        }

        private static string[] GetPropertyLine(string line, out string mduPropertyName,
                                                out string mduPropertyLowerCase)
        {
            string[] fields = line.Split('=', '#');
            mduPropertyName = fields[0].Trim();

            mduPropertyLowerCase = mduPropertyName.ToLower();
            return fields;
        }

        private string GetMduPropertyMultipleLineValueRecursive(string mduPropertyName, string mduPropertyValue,
                                                                ref string line, ref bool readNextLine)
        {
            line = GetNextLine();
            if (line == null || !mduPropertyValue.EndsWith(@"\"))
            {
                readNextLine = false;
                return mduPropertyValue;
            }

            mduPropertyValue = mduPropertyValue.Replace("\\", string.Empty).Trim();

            /* Check if it's a new property or a new line value */
            string[] lineValueWithComment = line.Split('#');
            string lineValue = lineValueWithComment[0];
            if (lineValue.Contains("="))
            {
                //It actually read a new property display a log warning / error and keep on reading the mdu file.
                log.WarnFormat("Found a new property while the mdu expected a new multiple line value {0}", line);
                readNextLine = false;
                return mduPropertyValue;
            }

            GetPropertyComment(line, mduPropertyName, line.Split('#').Length == 2, true);

            if (!string.IsNullOrEmpty(lineValue))
            {
                string multipleLineValues = GetMduPropertyMultipleLineValueRecursive(mduPropertyName,
                                                                                     lineValue.Trim(),
                                                                                     ref line,
                                                                                     ref readNextLine);
                mduPropertyValue += $" {multipleLineValues}";
            }

            return mduPropertyValue;
        }

        private void GetPropertyComment(string line, string mduPropertyName, bool condition, bool isMultipleLine)
        {
            if (condition)
            {
                int commentStart = line.IndexOf('#') + 1;
                if (commentStart > 0)
                {
                    string comment = isMultipleLine
                                         ? (mduComments.ContainsKey(mduPropertyName)
                                                ? mduComments[mduPropertyName]
                                                : "#")
                                           + line.Substring(commentStart)
                                         : line.Substring(commentStart);

                    mduComments[mduPropertyName] = comment.Trim();
                }
            }
        }
    }
}