//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaShell.Plugins.FMSuite.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeltaShell.Plugins.FMSuite.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backwards Compatibility: &apos;{0}&apos; has been updated to &apos;{1}&apos;.
        /// </summary>
        public static string DelftIniBackwardsCompatibilityHelper_GetUpdatedName_Backwards_Compatibility____0___has_been_updated_to___1__ {
            get {
                return ResourceManager.GetString("DelftIniBackwardsCompatibilityHelper_GetUpdatedName_Backwards_Compatibility____0_" +
                        "__has_been_updated_to___1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream is not readable..
        /// </summary>
        public static string DiaFileReader_GetAllMessages_Stream_is_not_readable_ {
            get {
                return ResourceManager.GetString("DiaFileReader_GetAllMessages_Stream_is_not_readable_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed. Current project does not contain unique names for features..
        /// </summary>
        public static string Feature2DImportExportBase_AddOrReplace_Import_failed_Current_project_does_not_contain_unique_names_for_features {
            get {
                return ResourceManager.GetString("Feature2DImportExportBase_AddOrReplace_Import_failed_Current_project_does_not_con" +
                        "tain_unique_names_for_features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of imported features did not contain unique names. Names were made unique during import..
        /// </summary>
        public static string Feature2DImportExportBase_AddOrReplace_The_list_of_imported_features_did_not_contain_unique_names_Names_were_made_unique_during_import {
            get {
                return ResourceManager.GetString("Feature2DImportExportBase_AddOrReplace_The_list_of_imported_features_did_not_cont" +
                        "ain_unique_names_Names_were_made_unique_during_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse time reference.
        /// </summary>
        public static string FMNetCdfFileFunctionStore_Could_not_parse_time_reference {
            get {
                return ResourceManager.GetString("FMNetCdfFileFunctionStore_Could_not_parse_time_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} is not supported by our computational core and will be removed from your input file..
        /// </summary>
        public static string Parameter__0__is_not_supported_by_our_computational_core_and_will_be_removed_from_your_input_file {
            get {
                return ResourceManager.GetString("Parameter__0__is_not_supported_by_our_computational_core_and_will_be_removed_from" +
                        "_your_input_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating the snapped geometry for feature &apos;{0}&apos; failed: {1}.
        /// </summary>
        public static string SnappedFeatureCollection_Calculating_the_snapped_geometry_for_feature___0___failed___1_ {
            get {
                return ResourceManager.GetString("SnappedFeatureCollection_Calculating_the_snapped_geometry_for_feature___0___faile" +
                        "d___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to generate Time series for 2D Structure: {0}, property: {1} mapped as {2}, type: {3} which is not yet supported..
        /// </summary>
        public static string StructureFactory_GetNotSupportedTimeSeriesMessage_Trying_to_generate_Time_series_for_2D_Structure___0___property___1__mapped_as__2___type___3__which_is_not_yet_supported_ {
            get {
                return ResourceManager.GetString("StructureFactory_GetNotSupportedTimeSeriesMessage_Trying_to_generate_Time_series_" +
                        "for_2D_Structure___0___property___1__mapped_as__2___type___3__which_is_not_yet_s" +
                        "upported_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid value{0} was encountered (expected {1}) for property &apos;{2}&apos; on line {3}.
        /// </summary>
        public static string StructureFile_An_invalid_value__0__was_encountered_expected__1__for_property__2__on_line__3__ {
            get {
                return ResourceManager.GetString("StructureFile_An_invalid_value__0__was_encountered_expected__1__for_property__2__" +
                        "on_line__3__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category [{0}] not supported for structures and is skipped. (Line {1}).
        /// </summary>
        public static string StructureFile_Category__0__not_supported_for_structures_and_is_skipped_Line__1__ {
            get {
                return ResourceManager.GetString("StructureFile_Category__0__not_supported_for_structures_and_is_skipped_Line__1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert .ini structure definition to actual structure (Line {0}): {1}.
        /// </summary>
        public static string StructureFile_Failed_to_convert_ini_structure_definition_to_actual_structure_Line__0____1__ {
            get {
                return ResourceManager.GetString("StructureFile_Failed_to_convert_ini_structure_definition_to_actual_structure_Line" +
                        "__0____1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligated property &apos;{0}&apos; expected but is missing; Structure is skipped. (Line {1}).
        /// </summary>
        public static string StructureFile_Obligated_property__0__expected_but_is_missing_Structure_is_skipped_Line__1__ {
            get {
                return ResourceManager.GetString("StructureFile_Obligated_property__0__expected_but_is_missing_Structure_is_skipped" +
                        "_Line__1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; not supported for structures of type &apos;{1}&apos; and is skipped. (Line {2}).
        /// </summary>
        public static string StructureFile_Property__0__not_supported_for_structures_of_type__1__and_is_skipped_Line__2__ {
            get {
                return ResourceManager.GetString("StructureFile_Property__0__not_supported_for_structures_of_type__1__and_is_skippe" +
                        "d_Line__2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing structure time series folder {0} with {1}... all structure time series will be written to this folder. (Line {2}).
        /// </summary>
        public static string StructureFile_Replacing_structure_time_series_folder__0__with__1__all_structure_time_series_will_be_written_to_this_folder_Line__2__ {
            get {
                return ResourceManager.GetString("StructureFile_Replacing_structure_time_series_folder__0__with__1__all_structure_t" +
                        "ime_series_will_be_written_to_this_folder_Line__2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure time series {0} will be written to the time series folder {1}. (Line {2}).
        /// </summary>
        public static string StructureFile_Structure_time_series__0__will_be_written_to_the_time_series_folder__1__Line__2__ {
            get {
                return ResourceManager.GetString("StructureFile_Structure_time_series__0__will_be_written_to_the_time_series_folder" +
                        "__1__Line__2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert .ini structure definition &apos;{0}&apos; to actual structure..
        /// </summary>
        public static string StructuresFile_ConvertStructure_Failed_to_convert__ini_structure_definition___0___to_actual_structure_ {
            get {
                return ResourceManager.GetString("StructuresFile_ConvertStructure_Failed_to_convert__ini_structure_definition___0__" +
                        "_to_actual_structure_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while reading and converting 2D Structures from {0}.
        /// </summary>
        public static string StructuresFile_ReadStructuresFileRelativeToReferenceFile_Error_while_reading_and_converting_2D_Structures_from__0_ {
            get {
                return ResourceManager.GetString("StructuresFile_ReadStructuresFileRelativeToReferenceFile_Error_while_reading_and_" +
                        "converting_2D_Structures_from__0_", resourceCulture);
            }
        }
    }
}
