substance 'Continuity' active
   description        'Continuity'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'NH4' active
   description        'Ammonium (NH4)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'CBOD5' active
   description        'carbonaceous BOD (first pool) at 5 days'
   concentration-unit '(gO2/m3)'
   waste-load-unit    '-'
end-substance
substance 'CBOD5_2' active
   description        'carbonaceous BOD (second pool) at 5 days'
   concentration-unit '(gO2/m3)'
   waste-load-unit    '-'
end-substance
substance 'OXY' active
   description        'Dissolved Oxygen'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
parameter 'Temp'
   description   'Water temperature'
   unit          'Celsius'
   value          0.1800E+02
end-parameter
parameter 'VWind'
   description   'wind velocity'
   unit          'm/s'
   value          0
end-parameter
parameter 'Winddir'
   description   'wind direction'
   unit          'deg'
   value          0
end-parameter
parameter 'Rad'
   description   'Solar radiation'
   unit          'W/m2'
   value          50
end-parameter
parameter 'TcNit'
   description   'temperature coefficient for nitrification'
   unit          '(-)'
   value          0.1070E+01
end-parameter
parameter 'COXNIT'
   description   'critical oxygen concentration for nitrification'
   unit          '(g/m3)'
   value          0.1000E+01
end-parameter
parameter 'RcNit'
   description   'first-order nitrification rate'
   unit          '(1/d)'
   value          0.1000E+00
end-parameter
parameter 'OOXNIT'
   description   'optimum oxygen concentration for nitrification'
   unit          '(gO2/m3)'
   value          0.5000E+01
end-parameter
parameter 'fTEWORBOD'
   description   'TEWOR production flux of CBOD5_2'
   unit          '(gO2/m3/d)'
   value          0.0000E+00
end-parameter
parameter 'fTEWOROXY'
   description   'TEWOR production flux of OXY'
   unit          '(gO2/m3/d)'
   value          0.0000E+00
end-parameter
parameter 'fTEWORNH4'
   description   'TEWOR production flux of NH4'
   unit          '(gN/m3/d)'
   value          0.0000E+00
end-parameter
parameter 'RcBOD'
   description   'decay rate BOD (first pool) at 20 oC'
   unit          '(1/d)'
   value          0.3000E+00
end-parameter
parameter 'RcBOD_2'
   description   'decay rate BOD (second pool) at 20 oC'
   unit          '(1/d)'
   value          0.1500E+00
end-parameter
parameter 'TcBOD'
   description   'temperature coefficient decay BOD'
   unit          '(-)'
   value          0.1040E+01
end-parameter
parameter 'COXBOD'
   description   'critical oxygen concentration for BOD decay'
   unit          '(gO2/m3)'
   value          0.1000E+01
end-parameter
parameter 'OOXBOD'
   description   'optimum oxygen concentration for BOD decay'
   unit          '(gO2/m3)'
   value          0.5000E+01
end-parameter
parameter 'CFLBOD'
   description   'oxygen function level for oxygen below COXBOD'
   unit          '(-)'
   value          0.3000E+00
end-parameter
parameter 'O2FuncBOD'
   description   'oxygen function for decay of CBOD'
   unit          '(-)'
   value         -999
end-parameter
parameter 'BOD5'
   description   'BOD5'
   unit          '(gO2/m3)'
   value         -999
end-parameter
parameter 'BODu'
   description   'calculated carbonaceous BOD at ultimate'
   unit          '(gO2/m3)'
   value         -999
end-parameter
parameter 'VSedBOD5'
   description   'sedimentation velocity CBOD5'
   unit          '(m/d)'
   value          0.1000E+00
end-parameter
parameter 'VSedBOD5_2'
   description   'sedimentation velocity CBOD5_2'
   unit          '(m/d)'
   value          0.1000E+00
end-parameter
parameter 'Salinity'
   description   'Salinity'
   unit          '(g/kg)'
   value          0.3500E+02
end-parameter
parameter 'SWRear'
   description   'switch for oxygen reaeration formulation (1-13)'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'KLRear'
   description   'reaeration transfer coefficient'
   unit          '(m/d)'
   value          0.1000E+01
end-parameter
parameter 'TCRear'
   description   'temperature coefficient for rearation'
   unit          '(-)'
   value          0.1016E+01
end-parameter
parameter 'fSOD'
   description   'zeroth-order sediment oxygen demand flux'
   unit          '(gO2/m2/d)'
   value          0.0000E+00
end-parameter
parameter 'RcSOD'
   description   'decay rate SOD at 20 oC'
   unit          '(1/d)'
   value          0.1000E+00
end-parameter
output 'ResTim'
   description   'residence time'
end-output
output 'SaturOXY'
   description   'saturation concentration'
end-output
output 'SatPercOXY'
   description   'Actual saturation percentage O2'
end-output
active-processes
   name  'ResTim' 'residence time'
   name  'Nitrif_NH4' 'Nitrification of ammonium'
   name  'Prod_TEWOR' 'Production fluxes for TEWOR+'
   name  'BODCOD' 'Mineralisation BOD and COD'
   name  'S_CBOD51' 'Sedimentation CBOD5 (first pool)'
   name  'S_CBOD52' 'Sedimentation CBOD5_2 (second pool)'
   name  'RearOXY' 'Reaeration of oxygen'
   name  'SedOXYDem' 'Sediment oxygen demand'
   name  'CalTau' 'Calculation of bottom friction'
   name  'DynDepth' 'dynamic calculation of the depth'
   name  'SaturOXY' 'Saturation concentration oxygen'
   name  'TotDepth' 'depth water column'
end-active-processes
