substance 'slib1' active
   description        'conc fractie 1 in water'
   concentration-unit 'g/m3'
   waste-load-unit    '-'
end-substance
substance 'slib2' active
   description        'conc fractie 2 in water'
   concentration-unit 'g/m3'
   waste-load-unit    '-'
end-substance
substance 'slib3' active
   description        'conc fractie 3 in water'
   concentration-unit 'g/m3'
   waste-load-unit    '-'
end-substance
substance 'dikte1' inactive
   description        'slibdikte fractie 1'
   concentration-unit 'cm'
   waste-load-unit    '-'
end-substance
substance 'dikte2' inactive
   description        'slibdikte fractie 2'
   concentration-unit 'cm'
   waste-load-unit    '-'
end-substance
substance 'dikte3' inactive
   description        'slibdikte fractie 3'
   concentration-unit 'cm'
   waste-load-unit    '-'
end-substance
parameter 'Ws1'
   description   'valsnelheid fractie 1'
   unit          'm/dag'
   value             1.000000    
end-parameter
parameter 'Ubcr1'
   description   'kr orbitaalsnelheid fractie 1'
   unit          'm/sec'
   value            0.1000000E-04
end-parameter
parameter 'Kres1'
   description   'resuspensie const fractie 1'
   unit          'gs/m3d'
   value             43.20000    
end-parameter
parameter 'ro1'
   description   'dichtheid fractie 1 in bodem'
   unit          'g/m2cm'
   value             1000.000    
end-parameter
parameter 'Ws2'
   description   'valsnelheid fractie 1'
   unit          'm/dag'
   value             5.000000    
end-parameter
parameter 'Ubcr2'
   description   'kr orbitaalsnelheid fractie 2'
   unit          'm/sec'
   value            0.1000000E-03
end-parameter
parameter 'Kres2'
   description   'resuspensie const fractie 2'
   unit          'gs/m3d'
   value             112.3000    
end-parameter
parameter 'ro2'
   description   'dichtheid fractie 2 in bodem'
   unit          'g/m2,cm'
   value             1000.000    
end-parameter
parameter 'Ws3'
   description   'valsnelheid fractie 3'
   unit          'm/dag'
   value             40.00000    
end-parameter
parameter 'Ubcr3'
   description   'kr orbitaalsnelheid fractie 3'
   unit          'm/sec'
   value            0.1000000E-02
end-parameter
parameter 'Kres3'
   description   'resuspensie const fractie 3'
   unit          'gs/m3d'
   value             1728.000    
end-parameter
parameter 'ro3'
   description   'dichtheid fractie 3 in bodem'
   unit          'g/m2,cm'
   value             1000.000    
end-parameter
parameter 'achter'
   description   'achtergrondconc zwevende stof'
   unit          'gr/m3'
   value             10.00000    
end-parameter
parameter 'Ub'
   description   'orbitaalsnelheid aan de bodem'
   unit          'm/sec'
   value            0.1000000    
end-parameter
output 'Z'
   description   'water depth'
end-output
output 'dt'
   description   'timestep of Duflow-quality calculation in seconds'
end-output
output 'resflux1'
   description   ' Kres1*(Ub-Ubcr1)'
end-output
output 'resflux2'
   description   ' Kres2*(Ub-Ubcr2)'
end-output
output 'resflux3'
   description   ' Kres3*(Ub-Ubcr3)'
end-output
output 'zwevend'
   description   '  achter + slib1 + slib2 + slib3'
end-output
output 'sliblaag'
   description   ' dikte1 + dikte2 + dikte3'
end-output
active-processes
   name  'HydDuflow' 'HydDuflow'
   name  'SLIBME' 'SLIBME'
end-active-processes
