Sobek Parser V2.07.001.46474

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73211453                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73216813                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : STW_001115                              

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73215837                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73211101                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : STW_001117                              

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73213149                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73216333                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 29                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73223293                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73229325                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73225181                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73210269                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73208941                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73208381                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73224157                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73224877                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73220125                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73218413                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DAM_000942                              

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73218333                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73219485                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73210813                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : STW_001116                              

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73206749                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73225197                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73208525                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73218749                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73214861                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73221405                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73218045                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73219677                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73226253                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73212109                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73428228                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73207453                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73225293                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73428235                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73207613                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73218077                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73205853                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73222493                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73223165                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73205885                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73209981                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73227037                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 40                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DAM_000928                              

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73206061                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73214221                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73428232                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73207165                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73213357                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73206605                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73211661                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73229965                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73227581                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73210173                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73214941                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73222957                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73224813                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73207373                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73206877                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73206189                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73220973                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73215565                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 81                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : STW_001207                              

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73206909                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73222429                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 20                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 21                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 22                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 25                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73228637                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73207421                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 52                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 59                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : STW_001213                              

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 77                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 71                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 72                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 73                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 74                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 75                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 76                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 69                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 70                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73226141                            

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : DKR_73221085                            

Warning    : Start date in meteo-file differs from Sobek start date
Object-id  : Bui                                     

Informative Messages:        0
Warnings            :       91
Errors!             :        0

End of program
