///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DHYDRO.Modules.DocumentViews
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ClickIconButton recording.
    /// </summary>
    [TestModule("fdefa161-d28e-47a4-b1f4-4ab906ae401f", ModuleType.Recording, 1)]
    public partial class ClickIconButton : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DHYDRO.DHYDRO1D2DRepository repository.
        /// </summary>
        public static global::DHYDRO.DHYDRO1D2DRepository repo = global::DHYDRO.DHYDRO1D2DRepository.Instance;

        static ClickIconButton instance = new ClickIconButton();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ClickIconButton()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ClickIconButton Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable ListNumber.
        /// </summary>
        [TestVariable("75f205f7-6b98-4d43-a77f-7cd7ba1974d9")]
        public string ListNumber
        {
            get { return repo.ListNumber; }
            set { repo.ListNumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable ContainerNumber.
        /// </summary>
        [TestVariable("5058835a-0156-4675-b74e-b2fbcd497f26")]
        public string ContainerNumber
        {
            get { return repo.ContainerNumber; }
            set { repo.ContainerNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.GenericIconButton' at Center.", repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.GenericIconButtonInfo, new RecordItemIndex(0));
            repo.DSWindow.ListView.MainTabControl.ListGroupsOutputSettings.GenericIconButton.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
