///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DHYDRO.Modules.DocumentViews
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateNewSharedDefinitionRectangle recording.
    /// </summary>
    [TestModule("968fc015-0f25-452c-85f5-917657460dae", ModuleType.Recording, 1)]
    public partial class CreateNewSharedDefinitionRectangle : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DHYDRO.DHYDRO1D2DRepository repository.
        /// </summary>
        public static global::DHYDRO.DHYDRO1D2DRepository repo = global::DHYDRO.DHYDRO1D2DRepository.Instance;

        static CreateNewSharedDefinitionRectangle instance = new CreateNewSharedDefinitionRectangle();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateNewSharedDefinitionRectangle()
        {
            HeigthValue = "";
            WidthValue = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateNewSharedDefinitionRectangle Instance
        {
            get { return instance; }
        }

#region Variables

        string _HeigthValue;

        /// <summary>
        /// Gets or sets the value of variable HeigthValue.
        /// </summary>
        [TestVariable("c48cb631-232c-4352-a4d8-fde4caabd0a3")]
        public string HeigthValue
        {
            get { return _HeigthValue; }
            set { _HeigthValue = value; }
        }

        string _WidthValue;

        /// <summary>
        /// Gets or sets the value of variable WidthValue.
        /// </summary>
        [TestVariable("50754540-d402-41c1-8b55-db868f7c66e5")]
        public string WidthValue
        {
            get { return _WidthValue; }
            set { _WidthValue = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.ListView.BtnNewSharedDefinition' at Center.", repo.DSWindow.ListView.BtnNewSharedDefinitionInfo, new RecordItemIndex(0));
            repo.DSWindow.ListView.BtnNewSharedDefinition.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.ListView.BtnEdit' at Center.", repo.DSWindow.ListView.BtnEditInfo, new RecordItemIndex(1));
            repo.DSWindow.ListView.BtnEdit.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(2));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.ListView.WinFormsAdapter.ComboBoxShapeType' at Center.", repo.DSWindow.ListView.WinFormsAdapter.ComboBoxShapeTypeInfo, new RecordItemIndex(3));
            repo.DSWindow.ListView.WinFormsAdapter.ComboBoxShapeType.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ComboBoxList.Rectangle' at Center.", repo.ComboBoxList.RectangleInfo, new RecordItemIndex(4));
            repo.ComboBoxList.Rectangle.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Check() on item 'DSWindow.ListView.WinFormsAdapter.CheckboxIsClosedProfile'.", repo.DSWindow.ListView.WinFormsAdapter.CheckboxIsClosedProfileInfo, new RecordItemIndex(5));
            repo.DSWindow.ListView.WinFormsAdapter.CheckboxIsClosedProfile.Check();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.ListView.TextBoxHeight' at Center.", repo.DSWindow.ListView.TextBoxHeightInfo, new RecordItemIndex(6));
            repo.DSWindow.ListView.TextBoxHeight.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$HeigthValue' on item 'DSWindow.ListView.TextBoxHeight'.", repo.DSWindow.ListView.TextBoxHeightInfo, new RecordItemIndex(7));
            repo.DSWindow.ListView.TextBoxHeight.Element.SetAttributeValue("Text", HeigthValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.ListView.TextBoxWidth' at Center.", repo.DSWindow.ListView.TextBoxWidthInfo, new RecordItemIndex(8));
            repo.DSWindow.ListView.TextBoxWidth.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'DSWindow.ListView.TextBoxWidth'.", repo.DSWindow.ListView.TextBoxWidthInfo, new RecordItemIndex(9));
            Keyboard.PrepareFocus(repo.DSWindow.ListView.TextBoxWidth);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$WidthValue' with focus on 'DSWindow.ListView.TextBoxWidth'.", repo.DSWindow.ListView.TextBoxWidthInfo, new RecordItemIndex(10));
            repo.DSWindow.ListView.TextBoxWidth.PressKeys(WidthValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.ListView.WinFormsAdapter.Append' at Center.", repo.DSWindow.ListView.WinFormsAdapter.AppendInfo, new RecordItemIndex(11));
            repo.DSWindow.ListView.WinFormsAdapter.Append.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DSWindow.ListView.WinFormsAdapter.CancelEdit' at Center.", repo.DSWindow.ListView.WinFormsAdapter.CancelEditInfo, new RecordItemIndex(12));
            repo.DSWindow.ListView.WinFormsAdapter.CancelEdit.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
