GR_1.2
GRID id '1' ci '1' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'T1_x=0m' '1' 500 0 '' 'T1_ConstantStorage_Qlat=0' '' <
250 0 '1' 'T1_x=250m' '11' 250 0 '' '' '' <
500 0 '2' '1' '' 0 0 '' 'Q(t)' '' <
tble grid
GRID id '2' ci '2' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'T2_x=0m' '3' 500 50 '' 'T2_BlockedTableStorage_Qlat=0' '' <
250 0 '3' 'T2_x=250m' '21' 250 50 '' '' '' <
500 0 '8' '4' '' 0 50 '' 'Q(t)' '' <
tble grid
GRID id '3' ci '3' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'T3_x=0m' '4' 500 100 '' 'T3_LinearTableStorage_Qlat=0' '' <
250 0 '4' 'T3_x=250m' '31' 250 100 '' '' '' <
500 0 '9' '5' '' 0 100 '' 'Q(t)' '' <
tble grid
GRID id '4' ci '4' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'T4_x=0m' '4_1' 500 150 '' 'T4_NoStorage_PosQlat' '' <
250 0 '4_1' 'T4_x=250m' '41' 250 150 '' '' '' <
500 0 '4_3' '6' '' 0 150 '' 'Q=0' '' <
tble grid
GRID id '5' ci '5' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'T5_x=0m' '5_1' 500 200 '' 'T5_ConstantStorage_NegQlat' '' <
250 0 '5_1' 'T5_x=250m' '51' 250 200 '' '' '' <
500 0 '6' '7' '' 0 200 '' 'Q=0' '' <
tble grid
GRID id '6' ci '6' re 0 dc 0 gr gr 
'GridPoint Table' PDIN 0 0 '' pdin CLTT 'Location' '1/R' cltt CLID '' '' clid
TBLE
0 0 '' 'T6_x=0m' '6_1' 500 250 '' 'T6_BlockedTableStorage_Qlat=f(t)' '' <
250 0 '6_1' 'T6_x=250m' '61' 250 250 '' '' '' <
500 0 '7' '3' '' 0 250 '' 'Q=0' '' <
tble grid
