CR_1.1
CRSN id '2' nm '' ci '1' lc 450 crsn
CRSN id '8' nm '' ci '2' lc 450 crsn
CRSN id '9' nm '' ci '3' lc 450 crsn
CRSN id '10' nm '' ci '4' lc 450 crsn
CRSN id '11' nm '' ci '5' lc 450 crsn
CRSN id '12' nm '' ci '6' lc 450 crsn
STON id 'T1_x=0m' ci '1' lc 0 st 'Normal' ston
STON id 'T2_x=0m' ci '2' lc 0 st 'Normal' ston
STON id 'T3_x=0m' ci '3' lc 0 st 'Normal' ston
STON id 'T4_x=0m' ci '4' lc 0 st 'Normal' ston
STON id 'T5_x=0m' ci '5' lc 0 st 'Normal' ston
STON id 'T6_x=0m' ci '6' lc 0 st 'Normal' ston
