CR_1.1
CRSN id '3' nm '' ci '1' lc 250 crsn
CRSN id '4' nm '' ci '1' lc 4750 crsn
CRSN id '18' nm '' ci '2' lc 250 crsn
CRSN id '19' nm '' ci '2' lc 4750 crsn
CRSN id '20' nm '' ci '3' lc 250 crsn
CRSN id '21' nm '' ci '3' lc 4750 crsn
CRSN id '22' nm '' ci '4' lc 250 crsn
CRSN id '23' nm '' ci '4' lc 4750 crsn
CRSN id '24' nm '' ci '5' lc 250 crsn
CRSN id '25' nm '' ci '5' lc 4750 crsn
CRSN id '26' nm '' ci '6' lc 250 crsn
CRSN id '27' nm '' ci '6' lc 4750 crsn
CRSN id '38' nm '' ci '7' lc 250 crsn
CRSN id '39' nm '' ci '7' lc 4750 crsn
