ST_1.0
STRU id 'GeneralStructure' nm 'GeneralStructure' ci '1' lc 2500 stru
STRU id 'Weir' nm 'Weir' ci '2' lc 2500 stru
STRU id 'Orifice' nm 'Orifice' ci '3' lc 2500 stru
STRU id 'Culvert' nm 'Culvert' ci '4' lc 2500 stru
STRU id 'Siphon' nm 'Siphon' ci '5' lc 2500 stru
STRU id 'InvertedSiphon' nm 'InvertedSiphon' ci '6' lc 2500 stru
STRU id 'RiverWeir' nm 'RiverWeir' ci '7' lc 2500 stru
