Deltares, Parsen Version 2.08.002.54560 (Win64), Feb 20 2018, 11:17:39

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : GeneralStructure                        
Object-name: GeneralStructure                        

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : Weir                                    
Object-name: Weir                                    

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : Orifice                                 
Object-name: Orifice                                 

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : Culvert                                 
Object-name: Culvert                                 

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : Siphon                                  
Object-name: Siphon                                  

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : InvertedSiphon                          
Object-name: InvertedSiphon                          

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : RiverWeir                               
Object-name: RiverWeir                               

Warning    : Start date in meteo-file differs from Sobek start date
Object-id  : Bui                                     

Informative Messages:        0
Warnings            :        8
Errors!             :        0

End of program
