Deltares, Parsen Version 2.08.002.54560 (Win64), Feb 20 2018, 11:17:39

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 5                                       

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 28                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 29                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 30                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 31                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 32                                      

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 35                                      

Warning    : Start date in meteo-file differs from Sobek start date
Object-id  : Bui                                     

Informative Messages:        0
Warnings            :        8
Errors!             :        0

End of program
