                                                                                
 Found -NP command line switch                                                  
 No processes from the process definition file are switched on                  


 Model :            Fraction calculation Sobek-WQ           
                                                            


 Run   :                                                    
                    T0: 2012.01.01 00:00:00  (scu=       1s)


 Using default configuration: WAQ                                               
 
 Using process definition file : proc_def                                
 Version number                :       4.52
 Serial                        :       1980
 
 
total number of substances with fractions :  0
 WARNING: circular input output relation detected in process library
# Determining which processes can be switched on                                                    
                                                                                                    
                                                                                                    
# determinig the processes to model the substances.                                                 
                                                                                                    
-fluxes for [Check               ]                                                                  
 no fluxes found                                                                                    
-dispersion for [Check               ]                                                              
 no dispersions found                                                                               
-velocity for [Check               ]                                                                
 no velocity found                                                                                  
                                                                                                    
-fluxes for [Initial             ]                                                                  
 no fluxes found                                                                                    
-dispersion for [Initial             ]                                                              
 no dispersions found                                                                               
-velocity for [Initial             ]                                                                
 no velocity found                                                                                  
                                                                                                    
-fluxes for [Boundary Flow       ]                                                                  
 no fluxes found                                                                                    
-dispersion for [Boundary Flow       ]                                                              
 no dispersions found                                                                               
-velocity for [Boundary Flow       ]                                                                
 no velocity found                                                                                  
                                                                                                    
# locating processes for requested output                                                           
                                                                                                    
# determining the input for the processes (in reversed order)                                       
                                                                                                    
# determining the use of the delwaq input                                       
                                                                                
 info: constant [Iteration ] is not used by the proces system                   
 info: segment function [Chezy     ] is not used by the proces system           
 info: segment function [Surf      ] is not used by the proces system           
 info: segment function [Velocity  ] is not used by the proces system           
 info: segment function [Width     ] is not used by the proces system           
                                                                                
# locating requested output from active processes                                                   
                                                                                                    
                                                                                                    
