ST_1.0
STRU id 'br_6' nm 'Msimbazi Kawawa road bridge' ci 'R_1' lc 2079.3344569603 stru
STRU id 'br_5' nm 'Msimbazi Kigogo road bridge' ci 'R_1' lc 2350.61161372133 stru
STRU id 'br_9' nm 'Msimbaz Kiembe Mbuzi Rd bridge' ci 'R_3' lc 9547.85008438245 stru
STRU id 'br_8' nm 'Msimbazi railroad bridge' ci 'R_3' lc 11940.3485691893 stru
STRU id 'br_7' nm 'Matumbi Culvert' ci 'R_3' lc 12288.5411761871 stru
STRU id 'br_12' nm '' ci 'R_4' lc 7554.35453854193 stru
STRU id 'br_11' nm 'Mkwajuni culvert' ci 'R_4' lc 8814.24150307956 stru
STRU id 'br_19' nm '' ci 'R_5' lc 7660.76076677262 stru
STRU id 'br_18' nm '' ci 'R_5' lc 8277.21975243637 stru
STRU id 'br_3' nm 'Jangwani East 2 culvert' ci 'rr_1' lc 111.037663328177 stru
STRU id 'br_4' nm 'Jangwani East 1 culvert' ci 'rr_2' lc 118.25792771024 stru
STRU id 'br_1' nm 'Selander bridge' ci '5' lc 51.3647614668269 stru
STRU id 'br_2' nm 'Jangwani West bridge' ci '7' lc 29.7885870113319 stru
