Sobek Parser V2.07.004.50272

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 5##6                                    
Object-name: Advanced                                

Warning    : Start date in meteo-file differs from Sobek start date
Object-id  : Bui                                     

Informative Messages:        0
Warnings            :        2
Errors!             :        0

End of program
