

ITEM
USEFOR 'Boundary Flow' 'Boundary Flow'
CONCENTRATION
USEFOR 'Cl' 'Cl'
DATA           'Cl' 
              350 


ITEM
USEFOR 'Inlaatwater' 'Inlaatwater'
CONCENTRATION
USEFOR 'Cl' 'Cl'
USEFOR 'cTR1' 'cTR1'
USEFOR 'cTR2' 'cTR2'
USEFOR 'cTR3' 'cTR3'
DATA           'Cl'          'cTR1'        'cTR2'        'cTR3' 
              450           0             1             0 


ITEM
USEFOR 'Lateral inflow' 'Lateral inflow'
CONCENTRATION
USEFOR 'Cl' 'Cl'
USEFOR 'cTR1' 'cTR1'
USEFOR 'cTR2' 'cTR2'
USEFOR 'cTR3' 'cTR3'
DATA           'Cl'          'cTR1'        'cTR2'        'cTR3' 
              -999          0             0             1 


ITEM
USEFOR 'Gemaal DGP' 'Gemaal DGP'
CONCENTRATION
USEFOR 'Cl' 'Cl'
USEFOR 'cTR1' 'cTR1'
USEFOR 'cTR2' 'cTR2'
USEFOR 'cTR3' 'cTR3'
DATA           'Cl'          'cTR1'        'cTR2'        'cTR3' 
              350           0             1             0 

ITEM
USEFOR 'Inlaat DGP' 'Inlaat DGP'
CONCENTRATION
USEFOR 'Cl' 'Cl'
USEFOR 'cTR1' 'cTR1'
USEFOR 'cTR2' 'cTR2'
USEFOR 'cTR3' 'cTR3'
DATA           'Cl'          'cTR1'        'cTR2'        'cTR3' 
              350           0             1             0 

ITEM
USEFOR 'Gemaal Van Haaften' 'Gemaal Van Haaften'
CONCENTRATION
USEFOR 'Cl' 'Cl'
USEFOR 'cTR1' 'cTR1'
USEFOR 'cTR2' 'cTR2'
USEFOR 'cTR3' 'cTR3'
DATA           'Cl'          'cTR1'        'cTR2'        'cTR3' 
              350           0             1             0 

ITEM
USEFOR 'Inlaat van Haaften' 'Inlaat van Haaften'
CONCENTRATION
USEFOR 'Cl' 'Cl'
USEFOR 'cTR1' 'cTR1'
USEFOR 'cTR2' 'cTR2'
USEFOR 'cTR3' 'cTR3'
DATA           'Cl'          'cTR1'        'cTR2'        'cTR3' 
              350           0             1             0 


ITEM
USEFOR 'Inlaat Oud Kijkuit' 'Inlaat Oud Kijkuit'
CONCENTRATION
USEFOR 'Cl' 'Cl'
USEFOR 'cTR1' 'cTR1'
USEFOR 'cTR2' 'cTR2'
USEFOR 'cTR3' 'cTR3'
DATA           'Cl'          'cTR1'        'cTR2'        'cTR3' 
              350           0             1             0 


ITEM
USEFOR 'Gemaal De Eendracht' 'Gemaal De Eendracht'
CONCENTRATION
USEFOR 'Cl' 'Cl'
USEFOR 'cTR1' 'cTR1'
USEFOR 'cTR2' 'cTR2'
USEFOR 'cTR3' 'cTR3'
DATA           'Cl'          'cTR1'        'cTR2'        'cTR3' 
              350           0             1             0 


ITEM
USEFOR 'Inlaat Deurloo' 'Inlaat Deurloo'
CONCENTRATION
USEFOR 'Cl' 'Cl'
USEFOR 'cTR1' 'cTR1'
USEFOR 'cTR2' 'cTR2'
USEFOR 'cTR3' 'cTR3'
DATA           'Cl'          'cTR1'        'cTR2'        'cTR3' 
              350           0             1             0 


ITEM
USEFOR 'Kwelbuizen' 'Kwelbuizen'
CONCENTRATION
USEFOR 'Cl' 'Cl'
USEFOR 'cTR1' 'cTR1'
USEFOR 'cTR2' 'cTR2'
USEFOR 'cTR3' 'cTR3'
DATA           'Cl'          'cTR1'        'cTR2'        'cTR3' 
              18000         0             0             0 

ITEM
USEFOR 'Suatiesluis Stavenis' 'Suatiesluis Stavenis'
CONCENTRATION
USEFOR 'Cl' 'Cl'
USEFOR 'cTR1' 'cTR1'
USEFOR 'cTR2' 'cTR2'
USEFOR 'cTR3' 'cTR3'
DATA           'Cl'          'cTR1'        'cTR2'        'cTR3' 
              18000         -999          -999          -999 


ITEM
USEFOR 'Evaporation' 'Evaporation'
CONCENTRATION
USEFOR 'Cl' 'Cl'
USEFOR 'cTR1' 'cTR1'
USEFOR 'cTR2' 'cTR2'
USEFOR 'cTR3' 'cTR3'
DATA           'Cl'          'cTR1'        'cTR2'        'cTR3' 
              0             0             0             0 


ITEM
USEFOR 'Neerslag' 'Neerslag'
CONCENTRATION
USEFOR 'Cl' 'Cl'
USEFOR 'cTR1' 'cTR1'
USEFOR 'cTR2' 'cTR2'
USEFOR 'cTR3' 'cTR3'
DATA           'Cl'          'cTR1'        'cTR2'        'cTR3' 
              10            0             0             0 


ITEM
USEFOR 'Dijkse kwel' 'Dijkse kwel'
CONCENTRATION
USEFOR 'Cl' 'Cl'
USEFOR 'cTR1' 'cTR1'
USEFOR 'cTR2' 'cTR2'
USEFOR 'cTR3' 'cTR3'
DATA           'Cl'          'cTR1'        'cTR2'        'cTR3' 
              18000         0             0             0 

