                                                                                
 found -p command line switch                                                   
 
 Using process definition file : c:\Program Files (x86)\Deltares\Delft3D 4.01.00\win32\waq\default\proc_def
 Version number                :       5.03
 Serial                        : 2014112001
 
                                                                                
 found -eco command line switch                                                 
 using default eco input file:bloom.spe                                         


 Model :                                                    
                                                            


 Run   :                                                    
                    T0: 1992.08.31 00:00:00  (scu=       1s)


# scanning input for old process definitions
 found only_active constant                                                     
 only activated processes are switched on                                       
 
total number of substances with fractions :  0
# Determining which processes can be switched on                                                    
                                                                                                    
 Input for [DynDepth            ] dynamic calculation of the depth                                  
   Process is activated                                                                             
                                                                                                    
 Input for [TotDepth            ] depth water column                                                
   Process is activated                                                                             
                                                                                                    
 Input for [VertDisp            ] Vertical dispersion (segment -> exchange)                         
   WARNING : activated process can NOT be switched on                                               
   Not found:[VertDisper          ] vertical dispersion                                             
                                                                                                    
                                                                                                    
# determinig the processes to model the substances.                                                 
                                                                                                    
-fluxes for [Continuity          ]                                                                  
 no fluxes found                                                                                    
-dispersion for [Continuity          ]                                                              
 found dispersion[VertDisp            ] vertical dispersion                                         
   from proces [VertDisp            ] Vertical dispersion (segment -> exchange)                     
   info : can not switch [VertDisp            ] on, not using disp.                                 
-velocity for [Continuity          ]                                                                
 no velocity found                                                                                  
                                                                                                    
# locating processes for requested output                                                           
                                                                                                    
 output [theta               ] will be generated by numerical scheme            
# determining the input for the processes (in reversed order)                                       
                                                                                                    
 Input for [TotDepth            ] depth water column                                                
       [Depth               ] depth of segment                                                      
       Using output from proces [DynDepth            ]                                              
       [Surf                ] horizontal surface area of a DELWAQ segment                           
       Using parameter nr  1                                                                        
                                                                                                    
 Input for [DynDepth            ] dynamic calculation of the depth                                  
       [Volume              ] volume of computational cell                                          
       Using DELWAQ volume                                                                          
       [Surf                ] horizontal surface area of a DELWAQ segment                           
       Using parameter nr  1                                                                        
                                                                                                    
# determining the use of the delwaq input                                       
                                                                                
 info: constant [CLOSE_ERR ] is not used by the proces system                   
 info: constant [ScaleVDisp] is not used by the proces system                   
 info: constant [MaxIter   ] is not used by the proces system                   
 info: constant [Tolerance ] is not used by the proces system                   
 info: constant [Iteration ] is not used by the proces system                   
 info: constant [MaxIterati] is not used by the proces system                   
 info: parameter [bottomdept] is not used by the proces system                  
                                                                                
# locating requested output from active processes                                                   
                                                                                                    
 output [LocalDepth          ] from proces [TotDepth  ]                                             
                                                                                                    
