                                                                                
 Found -A command line switch                                                   
 ONLY activated processes are switched on                                       
 Found -NP command line switch                                                  
 No processes from the process definition file are switched on                  


 Model :            Fraction calculation Sobek-WQ           
                                                            


 Run   :                                                    
                    T0: 2009.01.01 01:00:00  (scu=       1s)


 WARNING: circular input output relation detected in process library
 
 Using process definition file : proc_def                                
 Version number                :       4.52
 Serial                        :  825379650
 
# Determining which processes can be switched on                                                    
                                                                                                    
                                                                                                    
# Determinig the processes to model the substances.                             
                                                                                
-Fluxes for [Check     ]                                                        
 No fluxes found                                                                
-Dispersion for [Check     ]                                                    
 No dispersions found                                                           
-Velocity for [Check     ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Initial   ]                                                        
 No fluxes found                                                                
-Dispersion for [Initial   ]                                                    
 No dispersions found                                                           
-Velocity for [Initial   ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Lateral in]                                                        
 No fluxes found                                                                
-Dispersion for [Lateral in]                                                    
 No dispersions found                                                           
-Velocity for [Lateral in]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Boundary F]                                                        
 No fluxes found                                                                
-Dispersion for [Boundary F]                                                    
 No dispersions found                                                           
-Velocity for [Boundary F]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Geuzenveld]                                                        
 No fluxes found                                                                
-Dispersion for [Geuzenveld]                                                    
 No dispersions found                                                           
-Velocity for [Geuzenveld]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Louwesweg ]                                                        
 No fluxes found                                                                
-Dispersion for [Louwesweg ]                                                    
 No dispersions found                                                           
-Velocity for [Louwesweg ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Plesmanlaa]                                                        
 No fluxes found                                                                
-Dispersion for [Plesmanlaa]                                                    
 No dispersions found                                                           
-Velocity for [Plesmanlaa]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [NicoBroekh]                                                        
 No fluxes found                                                                
-Dispersion for [NicoBroekh]                                                    
 No dispersions found                                                           
-Velocity for [NicoBroekh]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Cramerslui]                                                        
 No fluxes found                                                                
-Dispersion for [Cramerslui]                                                    
 No dispersions found                                                           
-Velocity for [Cramerslui]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Heemstedes]                                                        
 No fluxes found                                                                
-Dispersion for [Heemstedes]                                                    
 No dispersions found                                                           
-Velocity for [Heemstedes]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Akersluis ]                                                        
 No fluxes found                                                                
-Dispersion for [Akersluis ]                                                    
 No dispersions found                                                           
-Velocity for [Akersluis ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [neerslag  ]                                                        
 No fluxes found                                                                
-Dispersion for [neerslag  ]                                                    
 No dispersions found                                                           
-Velocity for [neerslag  ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [verhard-sl]                                                        
 No fluxes found                                                                
-Dispersion for [verhard-sl]                                                    
 No dispersions found                                                           
-Velocity for [verhard-sl]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [verhard   ]                                                        
 No fluxes found                                                                
-Dispersion for [verhard   ]                                                    
 No dispersions found                                                           
-Velocity for [verhard   ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [onverhard-]                                                        
 No fluxes found                                                                
-Dispersion for [onverhard-]                                                    
 No dispersions found                                                           
-Velocity for [onverhard-]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [onverhard ]                                                        
 No fluxes found                                                                
-Dispersion for [onverhard ]                                                    
 No dispersions found                                                           
-Velocity for [onverhard ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [neerslag-s]                                                        
 No fluxes found                                                                
-Dispersion for [neerslag-s]                                                    
 No dispersions found                                                           
-Velocity for [neerslag-s]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [REST_NicoB]                                                        
 No fluxes found                                                                
-Dispersion for [REST_NicoB]                                                    
 No dispersions found                                                           
-Velocity for [REST_NicoB]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [REST_Westl]                                                        
 No fluxes found                                                                
-Dispersion for [REST_Westl]                                                    
 No dispersions found                                                           
-Velocity for [REST_Westl]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Multatuli ]                                                        
 No fluxes found                                                                
-Dispersion for [Multatuli ]                                                    
 No dispersions found                                                           
-Velocity for [Multatuli ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [SuppletieS]                                                        
 No fluxes found                                                                
-Dispersion for [SuppletieS]                                                    
 No dispersions found                                                           
-Velocity for [SuppletieS]                                                      
 No velocity found                                                              
                                                                                
# Locating processes for requested output                                       
                                                                                
# Determining the input for the processes (in reversed order)                   
                                                                                
# Determining the use of the DELWAQ input                                       
                                                                                
 INFO: Constant [Iteration ] is NOT used by the PROCES system                   
                                                                                
# Locating requested output from active processes                               
                                                                                
                                                                                
