Sobek Parser V2.07.001.46474

Warning    : Calculation point at Structure: Calculation Point Skipped
Object-id  : 11693                                   

Warning    : Duplicate YZ-Points in YZ-Profile Not Allowed.
             Duplicates have been ignored.
             Definition used in Cross-Section '105023P0190'

Warning    : Duplicate YZ-Points in YZ-Profile Not Allowed.
             Duplicates have been ignored.
             Definition used in Cross-Section '105023P0620'

Warning    : Duplicate YZ-Points in YZ-Profile Not Allowed.
             Duplicates have been ignored.
             Definition used in Cross-Section '105023P0980'

Informative Messages:        0
Warnings            :        4
Errors!             :        0

End of program
