CR_1.1
CRSN id 'T1_Up_Crs' nm 'T1_Up_Crs' ci '1' lc 0 crsn
CRSN id 'T1_Dwn_Crs' nm 'T1_Dwn_Crs' ci '1' lc 2000 crsn
CRSN id 'T2_Up_Crs' nm 'T2_Up_Crs' ci '2' lc 0 crsn
CRSN id 'T2_Dwn_Crs' nm 'T2_Dwn_Crs' ci '2' lc 2000 crsn
CRSN id 'T3_Dwn_Crs' nm 'T3_Dwn_Crs' ci '3' lc 0 crsn
CRSN id 'T3_Up_Crs' nm 'T3_Up_Crs' ci '3' lc 2000 crsn
CRSN id 'T4_Dwn_Crs' nm 'T4_Dwn_Crs' ci '4' lc 0 crsn
CRSN id 'T4_Up_Crs' nm 'T4_Up_Crs' ci '4' lc 2000 crsn
CRSN id 'T5_Up_Crs' nm 'T5_Up_Crs' ci '5' lc 0 crsn
CRSN id 'T5_Dwn_Crs' nm 'T5_Dwn_Crs' ci '5' lc 2000 crsn
CRSN id 'T6_Dwn_Crs' nm 'T6_Dwn_Crs' ci '6' lc 0 crsn
CRSN id 'T6_Up_Crs' nm 'T6_Up_Crs' ci '6' lc 2000 crsn
