using System.Linq;
using DeltaShell.NGHS.IO.Helpers;
using DeltaShell.Plugins.FMSuite.FlowFM.SedMor.ModelDefinition;

namespace DeltaShell.Plugins.FMSuite.FlowFM.SedMor.IO
{
    public class SedFile
    {
        public string SedFilePath { get; private set; }

        //todo: comments. they appear to be autogenerated, so put it in csv? (with unit?)

        public SedimentModelDefinition Load(string path)
        {
            SedFilePath = path;

            var modelDefinition = new SedimentModelDefinition();
            var modelSchema = modelDefinition.ModelSchema;
            var sedimentSchema = modelDefinition.SedimentSchema;
            var sedCategories = new SedMorDelftIniReader().ReadDelftIniFile(path);
            foreach (var category in sedCategories)
            {
                if (category.Name == "Sediment") // special treatment
                {
                    var sediment = new Sediment();
                    SedMorFileHelper.LoadCategoryIntoProperties(category, sediment.Properties, sedimentSchema, "Sediment");
                    modelDefinition.Sediments.Add(sediment);
                }
                else if (modelSchema.ModelDefinitionCategory.ContainsKey(category.Name))
                {
                    SedMorFileHelper.LoadCategoryIntoProperties(category,
                                               modelDefinition.Properties,
                                               modelSchema.PropertyDefinitions,
                                               modelSchema.ModelDefinitionCategory[category.Name].Name);
                }
            }
            return modelDefinition;
        }

        public void Save(string path, SedimentModelDefinition definition)
        {
            var writer = new SedMorDelftIniWriter();

            var categories = SedMorFileHelper.PutPropertiesIntoCategories(definition.Properties);
            foreach (var sediment in definition.Sediments)
            {
                var sedimentCategory = new DelftIniCategory("Sediment");

                foreach (var property in sediment.Properties.Values)
                {
                    var propDef = property.PropertyDefinition;
                    SedMorFileHelper.AddProperty(sedimentCategory, propDef.FilePropertyName, property);
                }

                categories.Add(sedimentCategory);
            }

            writer.WriteDelftIniFile(categories.ToList(), path);
        }
    }
}