using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using DelftTools.Utils.Collections.Extensions;
using DeltaShell.NGHS.IO.Helpers;
using GeoAPI.Geometries;

namespace DeltaShell.Plugins.FMSuite.Common.Gui.RgfGrid
{
    /// <summary>
    /// The RgfConfig grid describes a single .d3d file used to instruct RGFGrid
    /// to open the correct files.
    ///
    /// It provides the data storage of the necessary information, as well as a
    /// method to generate a set of <see cref="IDelftIniCategory"/> out of it.
    /// </summary>
    public class RgfConfig
    {
        #region PropertiesAndHeaderConst
        // Properties and Headers as defined in the .d3d file of RGFGrid.        
        /// <summary> The FileInformation header of the .d3d file. </summary>
        public const string FileInformationHeader = "FileInformation";
        /// <summary> The file generated by property name of the FileInformation header. </summary>
        public const string FileGeneratedBy = "FileGeneratedBy";
        /// <summary> The file creation data property name of the FileInformation header. </summary>
        public const string FileCreationData = "FileCreationDate";
        /// <summary> The file version property name of the FileInformation header. </summary>
        public const string FileVersion = "FileVersion";

        /// <summary> The Geometry header of the .d3d file. </summary>
        public const string GeometryHeader = "Geometry";
        /// <summary> The land boundary file property name of the Geometry header. </summary>
        public const string LandBoundaryFile = "LandBoundaryFile";
        /// <summary> The land boundary format property name of the Geometry header. </summary>
        public const string LandBoundaryFormat = "LandBoundaryFormat";

        /// <summary> The Grid header of the .d3d file. </summary>
        public const string GridHeader = "Grid";
        /// <summary> The type property name of the Grid header. </summary>
        public const string GridType = "Type";
        /// <summary> The file name property name of the Grid header. </summary>
        public const string GridFileName = "FileName";

        /// <summary> The Polygons header of the .d3d file. </summary>
        public const string PolygonsHeader = "Polygons";
        /// <summary> The file name property of the Polygons header. </summary>
        public const string PolygonFileName = "FileName";

        /// <summary> The batch header of the .d3d file. </summary>
        public const string BatchHeader = "Batch";
        /// <summary> The grid type property name of the Batch header. </summary>
        public const string BatchGridType = "Gridtype";
        /// <summary> The file name property name of the Batch header. </summary>
        public const string BatchFileName = "FileName";

        /// <summary> The fm grid keyword value for <see cref="GridType"/>. </summary>
        public const string FMGridKeyword = "DFLOW_FM";
        /// <summary>The GRD keyword value for <see cref="GridType"/></summary>
        public const string GrdKeyword = "RGF";

        /// <summary> The sepran grid value. </summary>
        public const string SepranGrid = "sepran_grid";
        #endregion

        /// <summary>
        /// Initializes a new empty <see cref="RgfConfig"/>.
        /// </summary>
        public RgfConfig()
        {
            AdditionalGeometryPaths = new List<string>();
            GridFileNames = new List<Tuple<string, string>>();

            PolFileName = null;
            Polygons = null;
        }

        /// <summary>
        /// Get or set the additional geometry paths of this <see cref="RgfConfig"/>.
        /// </summary>
        /// <value> The additional geometry paths. </value>
        public IList<string> AdditionalGeometryPaths { get; set; }

        /// <summary>
        /// Get or set the polygons of this <see cref="RgfConfig"/>.
        /// </summary>
        /// <value> The polygons. </value>
        public IList<IPolygon> Polygons { get; set; }

        /// <summary>
        /// Get or set the name of the polygon file.
        /// </summary>
        /// <value> The name of the polygon file. </value>
        public string PolFileName { get; set; }

        /// <summary>
        /// Get or set tuples describing the (grid file name, encoding of the grid file name).
        /// </summary>
        /// <value> The grid file names and their corresponding encodings. </value>
        public IList<Tuple<string, string>> GridFileNames { get; set; }

        /// <summary>
        /// Adds the grid file names without encoding. The encoding is determined based
        /// upon the file extension of the grid file names.
        /// </summary>
        /// <param name="gridFileNames"> The file names of the grids. </param>
        public void AddGridFileNames(params string[] gridFileNames)
        {
            foreach (string name in gridFileNames)
            {
                bool isNCGrid = Path.GetExtension(name) == ".nc";
                GridFileNames.Add(new Tuple<string, string>(name, isNCGrid ? FMGridKeyword : GrdKeyword));
            }
        }

        /// <summary>
        /// Add the set of file names and corresponding formats of the grids to this <see cref="RgfConfig"/>.
        /// </summary>
        /// <param name="gridFileNames"> The file names and corresponding formats of the grids. </param>
        public void AddGridFileNames(params Tuple<string, string>[] gridFileNames)
        {
            GridFileNames.AddRange(gridFileNames);
        }

        /// <summary>
        /// Convert this <see cref="RgfConfig"/> to its corresponding set of <see cref="DelftIniCategory"/>.
        /// </summary>
        /// <returns>
        /// The set of <see cref="IDelftIniCategory"/> that describes this <see cref="RgfConfig"/>.
        /// </returns>
        /// <exception cref="InvalidOperationException">
        /// GridFileNames is null.
        /// or
        /// AdditionalGeometryPaths is null.
        /// </exception>
        public IEnumerable<IDelftIniCategory> ToDelftIniCategories()
        {
            if (GridFileNames == null)
            {
                throw new InvalidOperationException("GridFileNames is null.");
            }

            if (AdditionalGeometryPaths == null)
            {
                throw new InvalidOperationException("AdditionalGeometryPaths is null.");
            }

            var categories = new List<IDelftIniCategory>();
            categories.Add(ParseFileInformationCategory());
            categories.AddRange(AdditionalGeometryPaths.Select(ParseGeometryCategory));
            categories.AddRange(GridFileNames.Select(t => ParseGridCategory(t.Item1, t.Item2)));

            if (PolFileName != null && Polygons != null)
            {
                categories.Add(ParsePolygonsCategory(PolFileName));
                categories.Add(ParseBatchCategory(GridFileNames[0].Item1));
            }

            return categories;
        }

        /// <summary>
        /// Generate the FileInformation <see cref="IDelftIniCategory"/>.
        /// </summary>
        /// <returns>
        /// The FileInformation <see cref="IDelftIniCategory"/>
        /// </returns>
        private static IDelftIniCategory ParseFileInformationCategory()
        {
            var fileInformationCategory = new DelftIniCategory(FileInformationHeader);
            fileInformationCategory.AddProperty(FileGeneratedBy, "Generated by DeltaShell");
            fileInformationCategory.AddProperty(FileCreationData, DateTime.Today);
            fileInformationCategory.AddProperty(FileVersion, "0.00");

            return fileInformationCategory;
        }

        /// <summary>
        /// Generate the Geometry <see cref="IDelftIniCategory"/> with the given <paramref name="additionalPath"/>.
        /// </summary>
        /// <param name="additionalPath">The additional path.</param>
        /// <returns>
        /// The Geometry <see cref="IDelftIniCategory"/>
        /// </returns>
        /// <exception cref="InvalidOperationException">
        /// Unknown additional file format: {extension}
        /// </exception>
        private static IDelftIniCategory ParseGeometryCategory(string additionalPath)
        {
            string formatString;
            string extension = Path.GetExtension(additionalPath) ?? "";

            switch (extension)
            {
                case "":
                case ".ldb":
                    formatString = "TEKAL";
                    break;
                case ".shp":
                    formatString = "SHAPEFILE";
                    break;
                default:
                    throw new InvalidOperationException($"Unknown additional file format: {extension}");
            }

            var category = new DelftIniCategory(GeometryHeader);
            category.AddProperty(LandBoundaryFile, additionalPath);
            category.AddProperty(LandBoundaryFormat, formatString);

            return category;
        }

        /// <summary>
        /// Generate the Grid <see cref="IDelftIniCategory"/> with the given <paramref name="fileName"/> and <paramref name="fileType"/>.
        /// </summary>
        /// <param name="fileName"> The file name of the grid. </param>
        /// <param name="fileType"> The file type of the grid. </param>
        /// <returns>
        /// The Grid <see cref="IDelftIniCategory"/>.
        /// </returns>
        private static IDelftIniCategory ParseGridCategory(string fileName, string fileType)
        {
            var category = new DelftIniCategory(GridHeader);
            category.AddProperty(GridType, fileType);
            category.AddProperty(GridFileName, fileName);

            return category;
        }

        /// <summary>
        /// Generate the Polygons <see cref="IDelftIniCategory"/> with the given <paramref name="polFileName"/>.
        /// </summary>
        /// <param name="polFileName"> Name of the polygon file. </param>
        /// <returns>
        /// The Polygons <see cref="IDelftIniCategory"/>.
        /// </returns>
        private static IDelftIniCategory ParsePolygonsCategory(string polFileName)
        {
            var category = new DelftIniCategory(PolygonsHeader);
            category.AddProperty(PolygonFileName, polFileName);

            return category;
        }

        /// <summary>
        /// Generate the Batch <see cref="IDelftIniCategory"/> with the given <paramref name="gridFileName"/>.
        /// </summary>
        /// <param name="gridFileName"> Name of the grid file. </param>
        /// <returns>
        /// The Batch <see cref="IDelftIniCategory"/>.
        /// </returns>
        private static IDelftIniCategory ParseBatchCategory(string gridFileName)
        {
            var category = new DelftIniCategory(BatchHeader);
            category.AddProperty(BatchGridType, SepranGrid);
            category.AddProperty(BatchFileName, gridFileName);

            return category;
        }
    }
}
