//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaShell.Plugins.FMSuite.FlowFM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeltaShell.Plugins.FMSuite.FlowFM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap area2d {
            get {
                object obj = ResourceManager.GetObject("area2d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dry_point {
            get {
                object obj = ResourceManager.GetObject("dry_point", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot export in this format if the grid is not correct..
        /// </summary>
        public static string ExportGrid_Cannot_export_in_this_format_if_the_grid_is_not_correct {
            get {
                return ResourceManager.GetString("ExportGrid_Cannot_export_in_this_format_if_the_grid_is_not_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to simulate 2D/3D flow of water in rivers, channels, lakes, estuarine &amp; coastal areas and seas..
        /// </summary>
        public static string FlowFMApplicationPlugin_Description {
            get {
                return ResourceManager.GetString("FlowFMApplicationPlugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported three-dimensional time dependent variable found. Will not import variable ({0}), because the map file version does not support it..
        /// </summary>
        public static string FMMapFileFunctionStore_ConstructFunctions_Time_dependent_variable___0___has_been_filtered_out {
            get {
                return ResourceManager.GetString("FMMapFileFunctionStore_ConstructFunctions_Time_dependent_variable___0___has_been_" +
                        "filtered_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set coordinate system in output map because grid is not set.
        /// </summary>
        public static string FMMapFileFunctionStore_CoordinateSystem_Could_not_set_coordinate_system_in_output_map_because_grid_is_not_set {
            get {
                return ResourceManager.GetString("FMMapFileFunctionStore_CoordinateSystem_Could_not_set_coordinate_system_in_output" +
                        "_map_because_grid_is_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create spatial data {0} on volume location. This is currenty not supported. .
        /// </summary>
        public static string FMMapFileFunctionStore_CreateCoverage_CannotCreateSpatialDataOnVolumeLocation {
            get {
                return ResourceManager.GetString("FMMapFileFunctionStore_CreateCoverage_CannotCreateSpatialDataOnVolumeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} depends on Netlink dimension. This is currenty not supported. .
        /// </summary>
        public static string FMMapFileFunctionStore_CreateCoverage_NetlinkDimensionCurrentyNotSupported {
            get {
                return ResourceManager.GetString("FMMapFileFunctionStore_CreateCoverage_NetlinkDimensionCurrentyNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected location (dimension) &apos;{0}&apos;.
        /// </summary>
        public static string FMMapFileFunctionStore_CreateCoverage_UnexpectedLocationDimension {
            get {
                return ResourceManager.GetString("FMMapFileFunctionStore_CreateCoverage_UnexpectedLocationDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to construct grid spatial data : {0}.
        /// </summary>
        public static string FMMapFileFunctionStore_CreateCoverageFromNetCdfVariable_FailedToConstructGridSpatialData {
            get {
                return ResourceManager.GetString("FMMapFileFunctionStore_CreateCoverageFromNetCdfVariable_FailedToConstructGridSpat" +
                        "ialData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netcdf variable {0} of type {1} has been ignored..
        /// </summary>
        public static string FMMapFileFunctionStore_CreateCoverageFromNetCdfVariable_NetcdfVariableHasBeenIgnored {
            get {
                return ResourceManager.GetString("FMMapFileFunctionStore_CreateCoverageFromNetCdfVariable_NetcdfVariableHasBeenIgno" +
                        "red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FunctionGrid2D {
            get {
                object obj = ResourceManager.GetObject("FunctionGrid2D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GateSmall {
            get {
                object obj = ResourceManager.GetObject("GateSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hurricane2 {
            get {
                object obj = ResourceManager.GetObject("hurricane2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Observation {
            get {
                object obj = ResourceManager.GetObject("Observation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PumpSmall {
            get {
                object obj = ResourceManager.GetObject("PumpSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StructureFeatureSmall {
            get {
                object obj = ResourceManager.GetObject("StructureFeatureSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TextDocument {
            get {
                object obj = ResourceManager.GetObject("TextDocument", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TimeSeries {
            get {
                object obj = ResourceManager.GetObject("TimeSeries", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap unstruc {
            get {
                object obj = ResourceManager.GetObject("unstruc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap unstrucModel {
            get {
                object obj = ResourceManager.GetObject("unstrucModel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap unstrucWater {
            get {
                object obj = ResourceManager.GetObject("unstrucWater", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WeirSmall {
            get {
                object obj = ResourceManager.GetObject("WeirSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
