ST_1.0
STRU id 'brug_1' nm 'Hofvlietbrug' ci 'Almelose kanaal ben' lc 83.2794621273749 stru
STRU id 'SW9360-SW9364-S570' nm 'Keersluis' ci 'Almelose kanaal ben' lc 188.347095567549 stru
STRU id 'brug_11' nm 'Diezerkadebrug' ci 'stadsgrachten Zwolle Noord' lc 324.494794557821 stru
STRU id 'brug_10' nm 'Dijkstraat' ci 'stadsgrachten Zwolle Noord' lc 898.473615002316 stru
STRU id 'brug_9' nm 'Diezerpoortbrug' ci 'stadsgrachten Zwolle Midden' lc 116.82765595205 stru
STRU id 'brug_8' nm 'Pelserbrugje' ci 'stadsgrachten Zwolle Midden' lc 341.116350320944 stru
STRU id 'brug_7' nm 'Vispoortenbrug' ci 'stadsgrachten Zwolle Midden' lc 527.562941512255 stru
STRU id 'brug_5' nm 'Sassenpoortbrug' ci 'stadsgrachten Zwolle Zuid' lc 780.201688872843 stru
STRU id 'brug_4' nm 'Nieuwe_Havebrug' ci 'stadsgrachten Zwolle Zuid' lc 1288.25682608874 stru
STRU id 'brug_3' nm 'Kamperpoortbrug' ci 'stadsgrachten Zwolle Zuid' lc 1707.17573479323 stru
STRU id 'brug_18' nm 'Blokjesbrug' ci 'Almelose kanaal' lc 223.476224941486 stru
STRU id 'brug_17' nm 'Spoorbrug' ci 'Almelose kanaal' lc 650.373467329579 stru
STRU id 'brug_15' nm 'Weteringbrug' ci 'Almelose kanaal' lc 1773.85374766583 stru
STRU id 'brug_14' nm 'Achterdijkspad' ci 'Almelose kanaal' lc 2240.33163084065 stru
STRU id 'brug_13' nm 'Hanekampbrug' ci 'Almelose kanaal' lc 2650.68563212537 stru
STRU id 'brug_39' nm 'Langeslagbrug' ci 'Nieuwe Wetering' lc 89.9921219808985 stru
STRU id 'brug_38' nm 'Hoevenbrug_NW' ci 'Nieuwe Wetering' lc 2779.33373166739 stru
STRU id 'brug_37' nm 'Paxtonstraat_NW' ci 'Nieuwe Wetering' lc 3132.82669499934 stru
STRU id 'brug_35' nm 'Oldeneelallee_NW' ci 'Nieuwe Wetering' lc 3788.07072890726 stru
STRU id 'OK7000-OK7010-S36' nm 'stuwLangeslag_OK' ci 'Overijsselsch Kanaal' lc 4.92767027651322 stru
STRU id 'SW4110-SW5070-S127' nm 'stuw3A' ci 'Soestwetering' lc 2.53106053732028 stru
STRU id 'brug_27' nm 'Kappeweg' ci 'Soestwetering' lc 560.995986105379 stru
STRU id 'brug_26' nm 'Soestweteringpad' ci 'Soestwetering' lc 3644.14459922748 stru
STRU id 'brug_25' nm 'Kolkweg' ci 'Soestwetering' lc 7457.68477658362 stru
STRU id 'brug_24' nm 'Aalvangersweg' ci 'Soestwetering' lc 8420.82823330273 stru
STRU id 'brug_23' nm 'brugje_SW' ci 'Soestwetering' lc 9853.93464915654 stru
STRU id 'brug_22' nm 'Sekdoornsedijk_SW' ci 'Soestwetering' lc 10347.0841200839 stru
STRU id 'brug_21' nm 'Paxtonstraat_SW' ci 'Soestwetering' lc 10702.2277130106 stru
STRU id 'brug_20' nm 'Oldeneelallee_SW' ci 'Soestwetering' lc 11312.2994105801 stru
STRU id 'brug_19' nm 'Gerenvonder' ci 'Soestwetering' lc 11633.3650771535 stru
STRU id 'brug_12' nm 'brug_Turfmarkt' ci '2' lc 195.566062312051 stru
STRU id 'brug_44' nm 'Ybrug_Lemelerveld' ci 'Bo_Overijsselsch Kanaal' lc 4.90004206631993 stru
STRU id 'OK5450-OK5460-S35' nm 'stuwOK3' ci 'Bo_Overijsselsch Kanaal' lc 1061.62105013673 stru
STRU id 'brug_43' nm 'Dalsmholterweg' ci 'Bo_Overijsselsch Kanaal' lc 2347.47449787571 stru
STRU id 'OK5465-OK5470-S34' nm 'stuwOK3' ci 'Bo_Overijsselsch Kanaal' lc 4118.37793550657 stru
STRU id 'brug_42' nm 'Heinoseweg' ci 'Bo_Overijsselsch Kanaal' lc 6428.76508638751 stru
STRU id 'brug_41' nm 'Twentseweg' ci 'Bo_Overijsselsch Kanaal' lc 8273.09570520867 stru
STRU id 'brug_40' nm 'Zwolseweg' ci 'Bo_Overijsselsch Kanaal' lc 9203.89228396362 stru
STRU id 'OK5290-OK5334-S14' nm 'stuwOK1' ci 'Bo_1' lc .516654964400168 stru
STRU id 'brug_47' nm 'Korteveldsweg' ci 'Bo_1' lc 1228.23217193969 stru
STRU id 'brug_46' nm 'Ommerweg' ci 'Bo_1' lc 3684.90155393776 stru
STRU id 'brug_34' nm 'Dingshofweg' ci 'Bo_Soestwetering' lc 1675.23574154219 stru
STRU id 'brug_33' nm 'Kotterikstraat' ci 'Bo_Soestwetering' lc 2703.40123825929 stru
STRU id 'brug_32' nm 'Bruinsweg' ci 'Bo_Soestwetering' lc 3327.01009363181 stru
STRU id 'brug_31' nm 'Holstweg' ci 'Bo_Soestwetering' lc 3686.99689351656 stru
STRU id 'brug_30' nm 'Kloosterstraat' ci 'Bo_Soestwetering' lc 4484.28450319937 stru
STRU id 'brug_29' nm 'Plattenbergbrug' ci 'Bo_Soestwetering' lc 5915.30515672559 stru
STRU id 'brug_28' nm 'Raalterweg' ci 'Bo_Soestwetering' lc 7237.35309607041 stru
STRU id 'brug_45' nm 'Deventerweg' ci '3' lc 61.8766268680705 stru
STRU id 'OK5435-OK5440-S11' nm 'stuwOK2' ci '3' lc 332.16424512499 stru
