Sobek Parser V2.06.014.27565

Warning    : Structure at calculation point: grid point skipped
Object-id  : 5                                       

Warning    : Structure at calculation point: grid point skipped
Object-id  : 6                                       

Warning    : Structure at calculation point: grid point skipped
Object-id  : 7                                       

Warning    : Structure at calculation point: grid point skipped
Object-id  : 8                                       

Warning    : Structure at calculation point: grid point skipped
Object-id  : 9                                       

Warning    : Structure at calculation point: grid point skipped
Object-id  : 10                                      

Warning    : Structure at calculation point: grid point skipped
Object-id  : 11                                      

Warning    : Structure at calculation point: grid point skipped
Object-id  : 12                                      

Warning    : Structure at calculation point: grid point skipped
Object-id  : 13                                      

Warning    : Structure at calculation point: grid point skipped
Object-id  : 14                                      

Warning    : Structure at calculation point: grid point skipped
Object-id  : 15                                      

Warning    : Structure at calculation point: grid point skipped
Object-id  : 16                                      

Warning    : Structure at calculation point: grid point skipped
Object-id  : 17                                      

Warning    : Structure at calculation point: grid point skipped
Object-id  : 18                                      

Warning    : Structure at calculation point: grid point skipped
Object-id  : 19                                      

Warning    : Structure at calculation point: grid point skipped
Object-id  : 20                                      

Warning    : Structure at calculation point: grid point skipped
Object-id  : 22                                      

Warning    : Structure at calculation point: grid point skipped
Object-id  : 23                                      

Warning    : Start date in meteo-file differs from Sobek start date
Object-id  : Bui                                     

Informative Messages:        0
Warnings            :       19
Errors!             :        0

End of program
