substance 'AAP' active
   description        'adsorbed ortho phosphate'
   concentration-unit '(gP/m3)'
   waste-load-unit    '-'
end-substance
substance 'DetC' active
   description        'Detritus Carbon  (DetC)'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'DetN' active
   description        'Detritus Nitrogen (DetN)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'DetP' active
   description        'Detritus Phosphorus (DetP)'
   concentration-unit '(gP/m3)'
   waste-load-unit    '-'
end-substance
substance 'GREEN' active
   description        'Algae (non-Diatoms)'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'NH4' active
   description        'Ammonium (NH4)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'NO3' active
   description        'Nitrate (NO3)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'OOC' active
   description        'Other Organic Carbon (OOC)'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'OON' active
   description        'Other Organic Nitrogen (OON)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'OOP' active
   description        'Other Organic Phosphorus (OOP)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'PO4' active
   description        'Ortho-Phosphate (PO4)'
   concentration-unit '(gP/m3)'
   waste-load-unit    '-'
end-substance
substance 'Cu' active
   description        'Copper (Cu)'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'Ni' active
   description        'Nickel (Ni)'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'Zn' active
   description        'Zinc (Zn)'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'Cl' active
   description        'Chloride'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'Continuity' active
   description        'Continuity'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'cTR1' active
   description        'conservative tracer source 1'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'cTR2' active
   description        'conservative tracer source 2'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'dTR2' active
   description        'decayable tracer source 2'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'IM1' active
   description        'inorganic matter (IM1)'
   concentration-unit '(gDM/m3)'
   waste-load-unit    '-'
end-substance
substance 'AAPS1' inactive
   description        'adsorbed O-PO4 in layer S1'
   concentration-unit '(gP)'
   waste-load-unit    '-'
end-substance
substance 'DetCS1' inactive
   description        'DetC in layer S1'
   concentration-unit '(gC)'
   waste-load-unit    '-'
end-substance
substance 'DetNS1' inactive
   description        'DetN in layer S1'
   concentration-unit '(gN)'
   waste-load-unit    '-'
end-substance
substance 'DetPS1' inactive
   description        'DetP in layer S1'
   concentration-unit '(gP)'
   waste-load-unit    '-'
end-substance
substance 'OOCS1' inactive
   description        'OOC in layer S1'
   concentration-unit '(gC)'
   waste-load-unit    '-'
end-substance
substance 'OONS1' inactive
   description        'OON in layer S1'
   concentration-unit '(gN)'
   waste-load-unit    '-'
end-substance
substance 'OOPS1' inactive
   description        'OOP in layer S1'
   concentration-unit '(gP)'
   waste-load-unit    '-'
end-substance
substance 'CuS1' inactive
   description        'Cu in layer S1'
   concentration-unit '(g)'
   waste-load-unit    '-'
end-substance
substance 'NiS1' inactive
   description        'Ni in layer S1'
   concentration-unit '(g)'
   waste-load-unit    '-'
end-substance
substance 'ZnS1' inactive
   description        'Zn in layer S1'
   concentration-unit '(g)'
   waste-load-unit    '-'
end-substance
substance 'IM1S1' inactive
   description        'IM1 in layer S1'
   concentration-unit '(gDM)'
   waste-load-unit    '-'
end-substance
parameter 'IM2'
   description   'inorganic matter (IM2)'
   unit          '(gDM/m3)'
   value          0.0000E+00
end-parameter
parameter 'SWAdsP'
   description   'switch PO4 adsorption <0=Kd|1=Langmuir|2=pHdep>'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'KdPO4AAP'
   description   'distrib. coeff. (-) or ads. eq. const.'
   unit          '(m3/gP)'
   value          0.1000E+00
end-parameter
parameter 'RcAAPS1'
   description   'first-order AAP desorption rate in layer S1'
   unit          '(1/d)'
   value          0.1000E-01
end-parameter
parameter 'RcDetC'
   description   'first-order mineralisation rate DetC'
   unit          '(1/d)'
   value          0.1200E+00
end-parameter
parameter 'TcDetC'
   description   'temperature coefficient for mineralisation DetC'
   unit          '(-)'
   value          0.1047E+01
end-parameter
parameter 'CTMin'
   description   'critical temperature for mineralisation'
   unit          '(oC)'
   value          0.3000E+01
end-parameter
parameter 'NCRatGreen'
   description   'N:C ratio Greens'
   unit          '(gN/gC)'
   value          0.1600E+00
end-parameter
parameter 'PCRatGreen'
   description   'P:C ratio Greens'
   unit          '(gP/gC)'
   value          0.2000E-01
end-parameter
parameter 'FrAutGreen'
   description   'fraction autolysis Greens'
   unit          '(-)'
   value          0.3000E+00
end-parameter
parameter 'FrDetGreen'
   description   'fraction to detritus by mortality Greens'
   unit          '(-)'
   value          0.7000E+00
end-parameter
parameter 'VSedDetC'
   description   'sedimentation velocity DetC'
   unit          '(m/d)'
   value          0.1000E+00
end-parameter
parameter 'TauCSDetC'
   description   'critical shear stress for sedimentation DetC'
   unit          '(N/m2)'
   value          0.1000E+00
end-parameter
parameter 'RcDetCS1'
   description   'first-order mineralisation rate DetC in layer S1'
   unit          '(1/d)'
   value          0.3000E-01
end-parameter
parameter 'RcDetN'
   description   'first-order mineralisation rate DetN'
   unit          '(1/d)'
   value          0.1200E+00
end-parameter
parameter 'TcDetN'
   description   'temperature coefficient for mineralisation DetN'
   unit          '(-)'
   value          0.1047E+01
end-parameter
parameter 'RcDetNS1'
   description   'first-order mineralisation rate DetN in layer S1'
   unit          '(1/d)'
   value          0.3000E-01
end-parameter
parameter 'RcDetP'
   description   'first-order mineralisation rate DetP'
   unit          '(1/d)'
   value          0.8000E-01
end-parameter
parameter 'TcDetP'
   description   'temperature coefficient for mineralisation DetP'
   unit          '(-)'
   value          0.1047E+01
end-parameter
parameter 'RcDetPS1'
   description   'first-order mineralisation rate DetP in layer S1'
   unit          '(1/d)'
   value          0.3000E-01
end-parameter
parameter 'PPMaxGreen'
   description   'maximum production rate Greens'
   unit          '(1/d)'
   value          0.1800E+01
end-parameter
parameter 'MRespGreen'
   description   'maintenance respiration Greens st.temp'
   unit          '(-)'
   value          0.4500E-01
end-parameter
parameter 'GRespGreen'
   description   'growth respiration factor Greens'
   unit          '(-)'
   value          0.1500E+00
end-parameter
parameter 'Mort0Green'
   description   'mortality rate constant Greens'
   unit          '(1/d)'
   value          0.3500E+00
end-parameter
parameter 'MinGreen'
   description   'Minimum level Greens in mortality'
   unit          '(gC/m3)'
   value          0.0000E+00
end-parameter
parameter 'TcNit'
   description   'temperature coefficient for nitrification'
   unit          '(-)'
   value          0.1070E+01
end-parameter
parameter 'CTNit'
   description   'critical temperature for nitrification'
   unit          '(oC)'
   value          0.3000E+01
end-parameter
parameter 'COXNIT'
   description   'critical oxygen concentration for nitrification'
   unit          '(g/m3)'
   value          0.1000E+01
end-parameter
parameter 'RcNit'
   description   'first-order nitrification rate'
   unit          '(1/d)'
   value          0.1000E+00
end-parameter
parameter 'OOXNIT'
   description   'optimum oxygen concentration for nitrification'
   unit          '(gO2/m3)'
   value          0.5000E+01
end-parameter
parameter 'RcOONS1'
   description   'first-order mineralisation rate OON in layer S1'
   unit          '(1/d)'
   value          0.3000E-01
end-parameter
parameter 'RcDenSed'
   description   'first-order denitrification rate in the sediment'
   unit          '(m/d)'
   value          0.1000E+00
end-parameter
parameter 'TcDenWat'
   description   'temperature coefficient for denitrification'
   unit          '(-)'
   value          0.1070E+01
end-parameter
parameter 'COXDEN'
   description   'critical oxygen concentration for denitrification'
   unit          '(g/m3)'
   value          0.3000E+01
end-parameter
parameter 'RcDenWat'
   description   'first-order denitrification rate in water column'
   unit          '(1/d)'
   value          0.1000E+00
end-parameter
parameter 'OOXDEN'
   description   'optimum oxygen concentration for denitrification'
   unit          '(gO2/m3)'
   value          0.1000E+01
end-parameter
parameter 'VSedOOC'
   description   'sedimentation velocity OOC'
   unit          '(m/d)'
   value          0.1000E+00
end-parameter
parameter 'TaucSOOC'
   description   'critical shear stress for sedimentation OOC'
   unit          '(N/m2)'
   value          0.1000E+00
end-parameter
parameter 'RcOOCS1'
   description   'first-order mineralisation rate OOC in layer S1'
   unit          '(1/d)'
   value          0.3000E-01
end-parameter
parameter 'RcOOPS1'
   description   'first-order mineralisation rate OOP in layer S1'
   unit          '(1/d)'
   value          0.3000E-01
end-parameter
parameter 'RcDecTR2'
   description   'decay rate tracer2 for AGE calculations'
   unit          '(1/d)'
   value          0.1000E-01
end-parameter
parameter 'VSedIM1'
   description   'sedimentation velocity IM1'
   unit          '(m/d)'
   value          0.1000E+00
end-parameter
parameter 'TaucSIM1'
   description   'critical shear stress for sedimentation IM1'
   unit          '(N/m2)'
   value          0.1000E+00
end-parameter
parameter 'Grtochl'
   description   'Chlorophyll-a:C ratio in Greens'
   unit          '(mg Chlfa/g C)'
   value          0.5000E+02
end-parameter
parameter 'ZResDM'
   description   'zeroth-order resuspension flux'
   unit          '(gDM/m2/d)'
   value          0.0000E+00
end-parameter
parameter 'TaucRS1DM'
   description   'critical shear stress for resuspension DM layer S1'
   unit          '(N/m2)'
   value          0.2000E+00
end-parameter
parameter 'ExtVlIM1'
   description   'VL specific extinction coefficient M1'
   unit          '(m2/gDM)'
   value          0.1000E-01
end-parameter
parameter 'ExtVlIM2'
   description   'VL specific extinction coefficient IM2'
   unit          '(m2/gDM)'
   value          0.2500E-01
end-parameter
parameter 'ExtVlBak'
   description   'background extinction visible light'
   unit          '(1/m)'
   value          0.8000E-01
end-parameter
parameter 'VBurDMS1'
   description   'first order burial rate for layer S1'
   unit          '(1/d)'
   value          0.0000E+00
end-parameter
parameter 'MaxTHS1'
   description   'maximum thickness layer S1'
   unit          '(m)'
   value          0.5000E-01
end-parameter
parameter 'OptDLGreen'
   description   'daylength for growth saturation Greens'
   unit          '(d)'
   value          0.5800E+00
end-parameter
parameter 'PrfNH4gree'
   description   'ammonium preferency over nitrate Greens'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'KMDINgreen'
   description   'half-saturation value N Greens'
   unit          '(gN/m3)'
   value          0.5000E-02
end-parameter
parameter 'KMPgreen'
   description   'half-saturation value P Greens'
   unit          '(gP/m3)'
   value          0.1000E-02
end-parameter
parameter 'RadSatGree'
   description   'total radiation growth saturation greens'
   unit          '(W/m2)'
   value          0.3000E+02
end-parameter
parameter 'TcGroGreen'
   description   'temperature coeff. for growth processes Greens'
   unit          '(-)'
   value          0.1040E+01
end-parameter
parameter 'TcDecGreen'
   description   'temp. coeff. for respiration and mortality Greens'
   unit          '(-)'
   value          0.1070E+01
end-parameter
parameter 'ExtVlDetC'
   description   'VL specific extinction coefficient DetC'
   unit          '(m2/gC)'
   value          0.4700E+00
end-parameter
parameter 'ExtVlGreen'
   description   'VL specific extinction coefficient Greens'
   unit          '(m2/gC)'
   value          0.1500E+00
end-parameter
output 'fSedIM1'
   description   'sedimentation flux IM1'
end-output
output 'Depth'
   description   'depth of segment'
end-output
output 'AlgN'
   description   'total nitrogen in algae'
end-output
output 'AlgP'
   description   'total phosphorus in algae'
end-output
output 'SS'
   description   'suspended solids'
end-output
output 'TotN'
   description   'total nitrogen (including algae)'
end-output
output 'KjelN'
   description   'Kjeldahl nitrogen'
end-output
output 'TotP'
   description   'total phosphorus (including algae)'
end-output
output 'Tau'
   description   'total bottom shear stress'
end-output
output 'ExtVl'
   description   'total extinction coefficient visible light'
end-output
output 'fBurS1DM'
   description   'total burial flux DM from layer S1'
end-output
output 'LimDLGreen'
   description   'daylength limitation function for Greens <0-1>'
end-output
output 'LimNutGree'
   description   'nutrient limitation function Greens <0-1>'
end-output
output 'LimRadGree'
   description   'radiation limitation function Greens <0-1>'
end-output
output 'TFGroGreen'
   description   'temperature function growth Greens <0-1>'
end-output
output 'RcGroGreen'
   description   'primary production rate (minus respiration) Greens'
end-output
output 'RcMrtGreen'
   description   'mortality rate Greens'
end-output
output 'RcRespGree'
   description   'respiration rate Greens'
end-output
output 'fPPGreen'
   description   'net primary production of Greens'
end-output
output 'AgeTR2'
   description   'calculated  AGE  for water from source 2'
end-output
output 'ActThS1'
   description   'actual thickness layer S1'
end-output
output 'Chlfa'
   description   'Chlorophyll-a concentration'
end-output
output 'ExtVlPhyt'
   description   'VL extinction by phytoplankton'
end-output
output 'DayL'
   description   'daylength <0-1>'
end-output
active-processes
   name  'AdsPO4AAP' 'Ad(De)Sorption ortho phosphorus to inorg. matter'
   name  'Sed_AAP' 'Sedimentation AAP (adsorbed PO4)'
   name  'Res_AAP' 'Resuspension AAP (adsorbed PO4)'
   name  'Deso_AAPS1' 'Desorption of adsorbed phosphates in sediment S1'
   name  'BurS1_AAP' 'Burial of AAP (adsorbed PO4) from sediment S1'
   name  'Compos' 'Composition'
   name  'WM_DetC' 'Mineralisation detritus carbon'
   name  'NutRel_Alg' 'Release (nutrients/detritus) by of mortality algae'
   name  'SedDetC' 'Sedimentation detritus carbon'
   name  'Res_DetC' 'Resuspension detritus carbon'
   name  'Secchi' 'Extinction of visible-light (370-680nm)'
   name  'BMS1_DetC' 'Mineralisation detritus carbon in sediment S1'
   name  'BurS1_DetC' 'Burial detritus carbon from sediment S1'
   name  'WM_DetN' 'Mineralisation detritus nitrogen'
   name  'SedN_Det' 'Sedim. nutrients in detritus'
   name  'ResN_Det' 'Resuspension nutrients in detritus'
   name  'BMS1_DetN' 'Mineralisation detritus nitrogen in sediment S1'
   name  'BurS1N_Det' 'Burial nutrients in detritus from sediment S1'
   name  'WM_DetP' 'Mineralisation detritus phosphorus'
   name  'BMS1_DetP' 'Mineralisation detritus phosphorus in sediment S1'
   name  'GroMrt_Gre' 'Nett primary production and mortality green algae'
   name  'PPrLim' 'Limitation (numerical) on primary production'
   name  'Sed_Gre' 'Sedimentation green algae'
   name  'NutUpt_Alg' 'Uptake of nutrients by growth of algae'
   name  'Nitrif_NH4' 'Nitrification of ammonium'
   name  'BMS1_OON' 'Mineralisation other organic N in sediment S1'
   name  'DenSed_NO3' 'Denitrification in sediment'
   name  'DenWat_NO3' 'Denitrification in water column'
   name  'Sed_OOC' 'Sedimentation other organic carbon'
   name  'Res_OOC' 'Resuspension other organic carbon'
   name  'BMS1_OOC' 'Mineralisation other organic C in sediment S1'
   name  'BurS1_OOC' 'Burial other organic carbon from sediment S1'
   name  'SedN_OOC' 'Sedim. nutrients in OOC'
   name  'ResN_OO' 'Resuspension nutrients in other organics'
   name  'BurS1N_OO' 'Burial nutrients in oth. organics from sediment S1'
   name  'BMS1_OOP' 'Mineralisation other organic P in sediment S1'
   name  'Sed_Cu' 'Sedimentation adsorbed Cu'
   name  'Res_Cu' 'Resuspension adsorbed Cu'
   name  'Sed_Ni' 'Sedimentation adsorbed Ni'
   name  'Res_Ni' 'Resuspension adsorbed Ni'
   name  'Sed_Zn' 'Sedimentation adsorbed Zn'
   name  'Res_Zn' 'Resuspension adsorbed Zn'
   name  'Age2' 'Age of water from source 2'
   name  'Sed_IM1' 'Sedimentation IM1'
   name  'Res_IM1' 'Resuspension 1st inorganic matter'
   name  'BurS1_IM1' 'Burial 1st-inorganic matter from S1'
   name  'DynDepth' 'dynamic calculation of the depth'
   name  'Sum_ResS1' 'Sum of (in)organics resuspending from S1'
   name  'S1_Comp' 'Composition sediment layer S1'
   name  'Sum_BurS1' 'Sum of (in)organic substances buried from S1'
   name  'Phy_dyn' 'Computation of phytoplankton - Dynamo'
   name  'POC_Dyn' 'Composition of POC (Dynamo & Bloom)'
   name  'CalTau' 'Calculation of bottom friction'
   name  'Res_DM' 'Resuspension total bottom material (dry mass)'
   name  'Extinc_VL' 'Extinction of visible-light (370-680nm)'
   name  'Bur_DM' 'Burial total bottom mass (dry matter)'
   name  'Salin' 'calculation of salinity from chloride'
   name  'DL_Green' 'Daylength function for green algae'
   name  'NLGreen' 'Nutrient limiation function for green algae'
   name  'Rad_Green' 'Light efficiency function green algae'
   name  'TF_Green' 'Temperature functions for green algae'
   name  'PartWK_Cu' 'Partitioning Cu in water column'
   name  'PartS1_Cu' 'Partitioning Cu in S1'
   name  'PartWK_Ni' 'Partitioning Ni in water column'
   name  'PartS1_Ni' 'Partitioning Ni in S1'
   name  'PartWK_Zn' 'Partitioning Zn in water column'
   name  'PartS1_Zn' 'Partitioning Zn in S1'
   name  'TotDepth' 'depth water column'
   name  'ExtPODVL' 'Extinction of light by POC (Dynamo & Bloom)'
   name  'ExtPhDVL' 'Extinction of visual light by algae (Dynamo)'
   name  'Sum_Sedim' 'Total of all sedimenting substances'
   name  'Daylength' 'Daylength calculation'
end-active-processes
