substance 'sDShootP' inactive
   description        'Shoot biomass'
   concentration-unit 'gD/m2'
   waste-load-unit    '-'
end-substance
substance 'sNShootP' inactive
   description        'N in Shoot'
   concentration-unit 'gN/m2'
   waste-load-unit    '-'
end-substance
substance 'sPShootP' inactive
   description        'P in Shoot'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sDRootPh' inactive
   description        'Root biomass'
   concentration-unit 'gD/m2'
   waste-load-unit    '-'
end-substance
substance 'sNRootPh' inactive
   description        'N in Root'
   concentration-unit 'gN/m2'
   waste-load-unit    '-'
end-substance
substance 'sPRootPh' inactive
   description        'P in Root'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sDIMW' active
   description        'inorg. matter in water'
   concentration-unit 'mg/l'
   waste-load-unit    '-'
end-substance
substance 'sDHumS' inactive
   description        'humus in sediment'
   concentration-unit 'g/m2'
   waste-load-unit    '-'
end-substance
substance 'sDDetW' active
   description        'Detritus'
   concentration-unit 'mg/l'
   waste-load-unit    '-'
end-substance
substance 'sDIMS' inactive
   description        'inorg. matter in sediment'
   concentration-unit 'g/m2'
   waste-load-unit    '-'
end-substance
substance 'sDDetS' inactive
   description        'Sediment detritus'
   concentration-unit 'g/m2'
   waste-load-unit    '-'
end-substance
substance 'sO2W' active
   description        'Oxygen in water'
   concentration-unit 'mgO2/l'
   waste-load-unit    '-'
end-substance
substance 'sPO4W' active
   description        'SRP in water'
   concentration-unit 'mgP/l'
   waste-load-unit    '-'
end-substance
substance 'sPAIMW' active
   description        'P-adsorbed onto IM in water'
   concentration-unit 'mgP/l'
   waste-load-unit    '-'
end-substance
substance 'sPDetW' active
   description        'Detritus'
   concentration-unit 'mgP/l'
   waste-load-unit    '-'
end-substance
substance 'sPO4S' inactive
   description        'Pore water P'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sPAIMS' inactive
   description        'P-adsorbed onto IM in sediment'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sPHumS' inactive
   description        'humus in sediment'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sPDetS' inactive
   description        'Sediment P'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sNH4W' active
   description        'ammonium in water'
   concentration-unit 'mgN/l/d'
   waste-load-unit    '-'
end-substance
substance 'sNO3W' active
   description        'nitrate in water'
   concentration-unit 'mgN/l'
   waste-load-unit    '-'
end-substance
substance 'sNDetW' active
   description        'Detritus in water'
   concentration-unit 'mgN/l/d'
   waste-load-unit    '-'
end-substance
substance 'sNH4S' inactive
   description        'Pore water ammonium'
   concentration-unit 'gN/m2/d'
   waste-load-unit    '-'
end-substance
substance 'sNO3S' inactive
   description        'Pore water nitrate'
   concentration-unit 'gN/m2/d'
   waste-load-unit    '-'
end-substance
substance 'sNHumS' inactive
   description        'Humus in sediment'
   concentration-unit 'gN/m2'
   waste-load-unit    '-'
end-substance
substance 'sNDetS' inactive
   description        'Sediment detritus N'
   concentration-unit 'gN/m2/d'
   waste-load-unit    '-'
end-substance
substance 'sSiO2W' active
   description        'dissolved silica in water'
   concentration-unit 'mgSi/l'
   waste-load-unit    '-'
end-substance
substance 'sSiDetW' active
   description        'Detritus'
   concentration-unit 'mgSi/l'
   waste-load-unit    '-'
end-substance
substance 'sSiDetS' inactive
   description        'Sediment detritus Si'
   concentration-unit 'gSi/m2'
   waste-load-unit    '-'
end-substance
substance 'sDDiatW' active
   description        'Diatoms'
   concentration-unit 'mgD/l'
   waste-load-unit    '-'
end-substance
substance 'sDGrenW' active
   description        'Green algae'
   concentration-unit 'mgD/l'
   waste-load-unit    '-'
end-substance
substance 'sDBlueW' active
   description        'Blue-greens'
   concentration-unit 'mgD/l'
   waste-load-unit    '-'
end-substance
substance 'sPDiatW' active
   description        'Diatoms'
   concentration-unit 'mgP/l'
   waste-load-unit    '-'
end-substance
substance 'sPGrenW' active
   description        'Green algae'
   concentration-unit 'mgP/l'
   waste-load-unit    '-'
end-substance
substance 'sPBlueW' active
   description        'Blue-greens'
   concentration-unit 'mgP/l'
   waste-load-unit    '-'
end-substance
substance 'sNDiatW' active
   description        'Diatoms'
   concentration-unit 'mgN/l'
   waste-load-unit    '-'
end-substance
substance 'sNGrenW' active
   description        'Green algae'
   concentration-unit 'mgN/l'
   waste-load-unit    '-'
end-substance
substance 'sNBlueW' active
   description        'Blue-greens'
   concentration-unit 'mgN/l'
   waste-load-unit    '-'
end-substance
substance 'sDDiatS' inactive
   description        'Diatoms'
   concentration-unit 'gD m-2'
   waste-load-unit    '-'
end-substance
substance 'sDGrenS' inactive
   description        'Green algae'
   concentration-unit 'gD m-2'
   waste-load-unit    '-'
end-substance
substance 'sDBlueS' inactive
   description        'Blue-greens'
   concentration-unit 'gD m-2'
   waste-load-unit    '-'
end-substance
substance 'sPDiatS' inactive
   description        'Diatoms'
   concentration-unit 'gP m-2'
   waste-load-unit    '-'
end-substance
substance 'sPGrenS' inactive
   description        'Green algae'
   concentration-unit 'gP m-2'
   waste-load-unit    '-'
end-substance
substance 'sPBlueS' inactive
   description        'Blue-greens'
   concentration-unit 'gP m-2'
   waste-load-unit    '-'
end-substance
substance 'sNDiatS' inactive
   description        'Diatoms'
   concentration-unit 'gN m-2'
   waste-load-unit    '-'
end-substance
substance 'sNGrenS' inactive
   description        'Green algae'
   concentration-unit 'gN m-2'
   waste-load-unit    '-'
end-substance
substance 'sNBlueS' inactive
   description        'Blue-greens'
   concentration-unit 'gN m-2'
   waste-load-unit    '-'
end-substance
substance 'sDVeg' inactive
   description        'Vegetation'
   concentration-unit 'gD/m2'
   waste-load-unit    '-'
end-substance
substance 'sPVeg' inactive
   description        'Vegetation'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sNVeg' inactive
   description        'Vegetation'
   concentration-unit 'gN/m2'
   waste-load-unit    '-'
end-substance
substance 'sDZoo' inactive
   description        'Zooplankton'
   concentration-unit 'gD/m2'
   waste-load-unit    '-'
end-substance
substance 'sPZoo' inactive
   description        'Zooplankton'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sNZoo' inactive
   description        'Zooplankton'
   concentration-unit 'gN/m2'
   waste-load-unit    '-'
end-substance
substance 'sDBent' inactive
   description        'Zoobenthos'
   concentration-unit 'gD/m2'
   waste-load-unit    '-'
end-substance
substance 'sPBent' inactive
   description        'Zoobenthos'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sNBent' inactive
   description        'Zoobenthos'
   concentration-unit 'gN/m2'
   waste-load-unit    '-'
end-substance
substance 'sDFiAd' inactive
   description        'Adult fish'
   concentration-unit 'gD/m2'
   waste-load-unit    '-'
end-substance
substance 'sPFiAd' inactive
   description        'Adult fish'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sNFiAd' inactive
   description        'Adult fish'
   concentration-unit 'gN/m2'
   waste-load-unit    '-'
end-substance
substance 'sDFiJv' inactive
   description        'Young fish'
   concentration-unit 'gD/m2'
   waste-load-unit    '-'
end-substance
substance 'sPFiJv' inactive
   description        'Young fish'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sNFiJv' inactive
   description        'Young fish'
   concentration-unit 'gN/m2'
   waste-load-unit    '-'
end-substance
substance 'sDPisc' inactive
   description        'predatory fish'
   concentration-unit 'gD/m2'
   waste-load-unit    '-'
end-substance
substance 'sDExtTot' inactive
   description        'total amount of DW moved into or out from the syst'
   concentration-unit 'g/m2'
   waste-load-unit    '-'
end-substance
substance 'sPExtTot' inactive
   description        'total amount of P moved into or out from the syste'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sNExtTot' inactive
   description        'total amount of N moved into or out from the syste'
   concentration-unit 'gN/m2'
   waste-load-unit    '-'
end-substance
substance 'sSiExtTo' inactive
   description        'total amount of Si moved into or out from the syst'
   concentration-unit 'gSi/m2'
   waste-load-unit    '-'
end-substance
substance 'Time' inactive
   description        'time'
   concentration-unit 'day'
   waste-load-unit    '-'
end-substance
parameter 'BeginTime'
   description   'begintime'
   unit          'day'
   value             0.000000    
end-parameter
parameter 'EndTime'
   description   '(=1 year)'
   unit          'day'
   value             365.0000    
end-parameter
parameter 'ConstDepth'
   description   'If T, water depth kept constant by  daily dredging'
   unit          '{no unit}'
   value             1.000000    
end-parameter
parameter 'Marsh'
   description   'Used in DUFLOW version only: if T, section is mars'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'UseWindFun'
   description   'FALSE = no wind function for shear stress,'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'ReadTemp'
   description   'If TRUE use measured time-series of temperature, o'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'ReadLOut'
   description   'If TRUE use measured time-series of light, otherwi'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'ReadVWind'
   description   'If TRUE use measured time-series of wind, otherwis'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'RewindInpu'
   description   'Only important if time-series are being used.'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'YearZero'
   description   'Note: also Dayno 1 = 1. Jan. of this year.'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'cFetch'
   description   'wind fetch'
   unit          'm'
   value             1000.000    
end-parameter
parameter 'fMarsh'
   description   'relative marsh area'
   unit          'm2 marsh m-2 lake'
   value             0.000000    
end-parameter
parameter 'fLutum'
   description   'lutum content of inorg. matter'
   unit          '-'
   value            0.1000000    
end-parameter
parameter 'fFeDIM'
   description   'Fe content of inorg. matter'
   unit          'gFe/gD'
   value            0.1000000E-01
end-parameter
parameter 'fAlDIM'
   description   'Al content of inorg. matter'
   unit          'gAl/gD'
   value            0.1000000E-01
end-parameter
parameter 'cTmAve'
   description   'average water temperature'
   unit          'oC'
   value             12.00000    
end-parameter
parameter 'cTmVar'
   description   'annual temperature variation'
   unit          'oC'
   value             10.00000    
end-parameter
parameter 'cTimeLag'
   description   'time lag for temperature'
   unit          'day'
   value             40.00000    
end-parameter
parameter 'cVWind'
   description   'average wind speed'
   unit          'm/s'
   value             5.000000    
end-parameter
parameter 'cQInf'
   description   'infiltration rate'
   unit          'mm/day'
   value             0.000000    
end-parameter
parameter 'cPBackLoad'
   description   '0.00016'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'cNBackLoad'
   description   '0.009'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'cLDayAve'
   description   'annual average radiation'
   unit          'J/m2/day'
   value            0.1000000E+08
end-parameter
parameter 'cLDayVar'
   description   'annual variation in radiation'
   unit          'J/m2/day'
   value             8000000.    
end-parameter
parameter 'cfDayAve'
   description   'average day length'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'cfDayVar'
   description   'annual variation in day length'
   unit          '-'
   value            0.2000000    
end-parameter
parameter 'fRefl'
   description   '0.1'
   unit          '{no unit}'
   value            0.2000000    
end-parameter
parameter 'cExtWat'
   description   'background extinction'
   unit          'm-1'
   value            0.5000000    
end-parameter
parameter 'cDredInter'
   description   'dredging interval'
   unit          'y'
   value             9999000.    
end-parameter
parameter 'cDredStart'
   description   'first dredging year (should be n times cDredInterv'
   unit          'y'
   value             9999000.    
end-parameter
parameter 'cDepthRef'
   description   'reference water depth for dredging'
   unit          'day'
   value            0.1000000E-32
end-parameter
parameter 'cLengDred'
   description   'length of dredging period'
   unit          'day'
   value             10.00000    
end-parameter
parameter 'fEffDred'
   description   'dredging efficiency (<1.0)'
   unit          '-'
   value            0.9500000    
end-parameter
parameter 'fEffDredBe'
   description   'dredging efficiency for zoobenthos (<1.0)'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'fEffDredLe'
   description   'dredging efficiency for duckweed (<1.0)'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'fPAR'
   description   'fraction photosynthetically active radiation (PAR)'
   unit          '-'
   value            0.4800000    
end-parameter
parameter 'cExtSpDet'
   description   'specific extinction detritus'
   unit          'm2/gDW'
   value            0.1500000    
end-parameter
parameter 'cExtSpIM'
   description   'specific extinction inert matter'
   unit          'm2/gDW'
   value            0.5000000E-01
end-parameter
parameter 'sDepthW0'
   description   'initial water depth'
   unit          'm'
   value             2.000000    
end-parameter
parameter 'sDIMW0'
   description   'water IM'
   unit          'mgDW/l'
   value             5.000000    
end-parameter
parameter 'sDDetW0'
   description   'water detritus'
   unit          'mgDW/l'
   value             2.000000    
end-parameter
parameter 'sO2W0'
   description   'oxygen in water'
   unit          'mgO2/l'
   value             10.00000    
end-parameter
parameter 'sPO4W0'
   description   'undefined'
   unit          'mgP/l'
   value            0.1000000E-01
end-parameter
parameter 'sPAIMW0'
   description   'adsorbed on IM in water'
   unit          'mgP/l'
   value             0.000000    
end-parameter
parameter 'sNO3W0'
   description   'NO3 in water'
   unit          'mgN/l'
   value            0.1000000    
end-parameter
parameter 'sNH4W0'
   description   'NH4 in water'
   unit          'mgN/l'
   value            0.1000000    
end-parameter
parameter 'sNH4S0'
   description   'dissolved N-NH4 in interstitial water'
   unit          'gN/m2'
   value            0.2000000E-01
end-parameter
parameter 'sNO3S0'
   description   'dissolved N-NO3 in interstitial water'
   unit          'gN/m2'
   value            0.2000000E-02
end-parameter
parameter 'sSiO2W0'
   description   'dissolved silica in water'
   unit          'mgSi/l'
   value             3.000000    
end-parameter
parameter 'sDPhytW0'
   description   'phytoplankton'
   unit          'mgDW/l'
   value            0.1000000E-32
end-parameter
parameter 'sDDiatW0'
   description   'Diatoms in water'
   unit          'mgDW/l'
   value            0.5000000    
end-parameter
parameter 'sDGrenW0'
   description   'Green algae in water'
   unit          'mgDW/l'
   value            0.5000000    
end-parameter
parameter 'sDBlueW0'
   description   'Blue-greens in water'
   unit          'mgDW/l'
   value             3.000000    
end-parameter
parameter 'sDPhytS0'
   description   'sediment algae'
   unit          'gDW/m2'
   value            0.1000000E-32
end-parameter
parameter 'sDDiatS0'
   description   'Sediment diatoms'
   unit          'gDW/m2'
   value            0.1000000E-02
end-parameter
parameter 'sDGrenS0'
   description   'Sediment greens'
   unit          'gDW/m2'
   value            0.1000000E-02
end-parameter
parameter 'sDBlueS0'
   description   'Sediment blue-greens'
   unit          'gDW/m2'
   value            0.1000000E-02
end-parameter
parameter 'sDVeg0'
   description   'Vegetation'
   unit          'gDW/m2'
   value             1.000000    
end-parameter
parameter 'sDElod0'
   description   'undefined'
   unit          'gD/m2'
   value            0.1000000E-32
end-parameter
parameter 'sDChar0'
   description   'undefined'
   unit          'gD/m2'
   value            0.1000000E-32
end-parameter
parameter 'sDCera0'
   description   'undefined'
   unit          'gD/m2'
   value            0.1000000E-32
end-parameter
parameter 'sDLemn0'
   description   'undefined'
   unit          'gD/m2'
   value            0.1000000E-32
end-parameter
parameter 'sDNymp0'
   description   'undefined'
   unit          'gD/m2'
   value            0.1000000E-32
end-parameter
parameter 'sDHelo0'
   description   'undefined'
   unit          'gD/m2'
   value            0.1000000E-32
end-parameter
parameter 'sDZoo0'
   description   'Zooplankton'
   unit          'mgDW/l'
   value            0.5000000E-01
end-parameter
parameter 'sDFiJv0'
   description   'Juvenile whitefish'
   unit          'gDW/m2'
   value            0.5000000    
end-parameter
parameter 'sDFiAd0'
   description   'Adult whitefish'
   unit          'gDW/m2'
   value             2.000000    
end-parameter
parameter 'sDPisc0'
   description   'Predatory fish'
   unit          'gDW/m2'
   value            0.1000000E-01
end-parameter
parameter 'sDBent0'
   description   'Zoobenthos'
   unit          'gDW/m2'
   value             1.000000    
end-parameter
parameter 'fDTotS0'
   description   'initial dry-weight fraction in sediment'
   unit          'g solid g-1 sediment'
   value            0.3000000    
end-parameter
parameter 'fDOrgS0'
   description   'initial organic fraction of sediment DW'
   unit          'g/g'
   value            0.1000000    
end-parameter
parameter 'fDDetS0'
   description   'initial detritus fraction of sediment organic matt'
   unit          'g/g'
   value            0.5000000E-01
end-parameter
parameter 'fPInorgS0'
   description   'initial inorg. P fraction in sed.'
   unit          'gP/gD'
   value            0.5000000E-03
end-parameter
parameter 'fPAdsS0'
   description   'initial adsorbed fraction of inorg. P in sed.'
   unit          '-'
   value            0.9900000    
end-parameter
parameter 'cPDDet0'
   description   'initial P fraction in detritus'
   unit          'gP/gDDet'
   value            0.2500000E-02
end-parameter
parameter 'cNDDet0'
   description   'initial N fraction in detritus'
   unit          'gN/gDDet'
   value            0.2500000E-01
end-parameter
parameter 'cSiDDet0'
   description   'initial Si fraction in detritus   Tentative'
   unit          'gSi/gDDet'
   value            0.1000000E-01
end-parameter
parameter 'cPDHum0'
   description   'initial P fraction in humus'
   unit          'gP/gDDet'
   value            0.5000000E-02
end-parameter
parameter 'cNDHum0'
   description   'initial N fraction in humus'
   unit          'gN/gDDet'
   value            0.5000000E-01
end-parameter
parameter 'cPDPhyt0'
   description   'initial P fraction in algae'
   unit          'gP/gD'
   value            0.1000000E-01
end-parameter
parameter 'cNDPhyt0'
   description   'initial N fraction in algae'
   unit          'gN/gD'
   value            0.1000000    
end-parameter
parameter 'cPDDiat0'
   description   'initial P fraction in diatoms'
   unit          'gP/gD'
   value            0.1000000E-01
end-parameter
parameter 'cNDDiat0'
   description   'initial N fraction in diatoms'
   unit          'gN/gD'
   value            0.1000000    
end-parameter
parameter 'cPDGren0'
   description   'initial P fraction in green algae'
   unit          'gP/gD'
   value            0.1000000E-01
end-parameter
parameter 'cNDGren0'
   description   'initial N fraction in green algae'
   unit          'gN/gD'
   value            0.1000000    
end-parameter
parameter 'cPDBlue0'
   description   'initial P fraction in blue-green algae'
   unit          'gP/gD'
   value            0.1000000E-01
end-parameter
parameter 'cNDBlue0'
   description   'initial N fraction in blue-green algae'
   unit          'gN/gD'
   value            0.1000000    
end-parameter
parameter 'cPDVeg0'
   description   'initial P fraction in veg.'
   unit          'gP/gD'
   value            0.2000000E-02
end-parameter
parameter 'cNDVeg0'
   description   'initial N fraction in veg.'
   unit          'gN/gD'
   value            0.2000000E-01
end-parameter
parameter 'cPDElod0'
   description   'initial P fraction in Elod.'
   unit          'gP/gD'
   value            0.2000000E-02
end-parameter
parameter 'cNDElod0'
   description   'initial N fraction in Elod.'
   unit          'gN/gD'
   value            0.2000000E-01
end-parameter
parameter 'cPDChar0'
   description   'initial P fraction in Char.'
   unit          'gP/gD'
   value            0.2000000E-02
end-parameter
parameter 'cNDChar0'
   description   'initial N fraction in Char.'
   unit          'gN/gD'
   value            0.2000000E-01
end-parameter
parameter 'cPDCera0'
   description   'initial P fraction in Cera.'
   unit          'gP/gD'
   value            0.2000000E-02
end-parameter
parameter 'cNDCera0'
   description   'initial N fraction in Cera.'
   unit          'gN/gD'
   value            0.2000000E-01
end-parameter
parameter 'cPDLemn0'
   description   'initial P fraction in Lemn.'
   unit          'gP/gD'
   value            0.5000000E-02
end-parameter
parameter 'cNDLemn0'
   description   'initial N fraction in Lemn.'
   unit          'gN/gD'
   value            0.5000000E-01
end-parameter
parameter 'cPDNymp0'
   description   'initial P fraction in Nymp.'
   unit          'gP/gD'
   value            0.2000000E-02
end-parameter
parameter 'cNDNymp0'
   description   'initial N fraction in Nymp.'
   unit          'gN/gD'
   value            0.2000000E-01
end-parameter
parameter 'cPDHelo0'
   description   'initial P fraction in Helo.'
   unit          'gP/gD'
   value            0.2000000E-02
end-parameter
parameter 'cNDHelo0'
   description   'initial N fraction in Helo.'
   unit          'gN/gD'
   value            0.2000000E-01
end-parameter
parameter 'cSiDDiat'
   description   '(Mylius, 1991)'
   unit          '{no unit}'
   value            0.1500000    
end-parameter
parameter 'cPDZooRef'
   description   'reference P/C-ratio herb. zooplankton'
   unit          'mgP/mgDW'
   value            0.1000000E-01
end-parameter
parameter 'cNDZooRef'
   description   'reference N/C-ratio herb. zooplankton'
   unit          'mgN/mgDW'
   value            0.7000000E-01
end-parameter
parameter 'cPDBentRef'
   description   'reference P/C ratio of zoobenthos'
   unit          'mgP/mgDW'
   value            0.1000000E-01
end-parameter
parameter 'cNDBentRef'
   description   'reference N/C ratio of zoobenthos'
   unit          'mgN/mgDW'
   value            0.7000000E-01
end-parameter
parameter 'cPDFishRef'
   description   'reference P/C ratio of Fish'
   unit          'mgP/mgDW'
   value            0.2200000E-01
end-parameter
parameter 'cNDFishRef'
   description   'reference N/C ratio of Fish'
   unit          'mgN/mgDW'
   value            0.1000000    
end-parameter
parameter 'cPDPisc'
   description   'reference P/C ratio of Pisc'
   unit          'mgP/mgDW'
   value            0.2200000E-01
end-parameter
parameter 'cNDPisc'
   description   'reference N/C ratio of Pisc'
   unit          'mgN/mgDW'
   value            0.1000000    
end-parameter
parameter 'cNLoadS'
   description   'N fertilizer to sediment'
   unit          'gN/m2/day'
   value             0.000000    
end-parameter
parameter 'fNH4LoadS'
   description   'NH4 fraction of N fertilizer to sediment'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'cDErosTot'
   description   'Erosion input (tentative)'
   unit          'g/m2/day'
   value            0.1000000    
end-parameter
parameter 'fSedErosIM'
   description   'instantly sedimentating fraction of IM'
   unit          '-'
   value            0.9500000    
end-parameter
parameter 'fDOrgSoil'
   description   'fraction soil organic matter'
   unit          '-'
   value            0.1000000    
end-parameter
parameter 'cPDSoilOM'
   description   'P/day ratio of soil organic matter'
   unit          'gP/gD'
   value            0.1000000E-02
end-parameter
parameter 'cNDSoilOM'
   description   'N/day ratio of soil organic matter'
   unit          'gN/gD'
   value            0.1000000E-01
end-parameter
parameter 'cPO4Ground'
   description   'undefined'
   unit          'mgP/l'
   value            0.1000000    
end-parameter
parameter 'cNH4Ground'
   description   'undefined'
   unit          'mgN/l'
   value             1.000000    
end-parameter
parameter 'cNO3Ground'
   description   'undefined'
   unit          'mgN/l'
   value            0.1000000    
end-parameter
parameter 'cDepthS'
   description   'sediment depth'
   unit          'm'
   value            0.1000000    
end-parameter
parameter 'cCPerDW'
   description   'C content of organic matter'
   unit          'gC/gDW'
   value            0.4000000    
end-parameter
parameter 'cRhoIM'
   description   'density of sediment IM'
   unit          'g/m3 solid'
   value             2500000.    
end-parameter
parameter 'cRhoOM'
   description   'density of sediment detritus'
   unit          'g/m3'
   value             1400000.    
end-parameter
parameter 'cTmRef'
   description   'reference temperature'
   unit          'oC'
   value             20.00000    
end-parameter
parameter 'cAerRoot'
   description   'coefficient for VWind^0.5'
   unit          '{no unit}'
   value            0.7270000    
end-parameter
parameter 'cAerLin'
   description   'coefficient for VWind (is negative.)'
   unit          's/day'
   value           -0.3710000    
end-parameter
parameter 'cAerSquare'
   description   'coefficient for VWind^2'
   unit          '{no unit}'
   value            0.3760000E-01
end-parameter
parameter 'cThetaAer'
   description   'Temperature coeff. for reaeration  (Downing & True'
   unit          '1/e^oC'
   value             1.024000    
end-parameter
parameter 'kLemnAer'
   description   'undefined'
   unit          'm2/gD'
   value            0.1000000E-01
end-parameter
parameter 'cVSetIM'
   description   'max. sedimentation velocity of inert org. matter'
   unit          'm/day'
   value             1.000000    
end-parameter
parameter 'cVSetDet'
   description   'max. sedimentation velocity of detritus'
   unit          'm/day'
   value            0.2500000    
end-parameter
parameter 'cThetaSet'
   description   'temp. parameter of sedimentation'
   unit          '1/e^oC'
   value             1.010000    
end-parameter
parameter 'cSuspMin'
   description   'undefined'
   unit          '{no unit}'
   value             6.100000    
end-parameter
parameter 'cSuspMax'
   description   'undefined'
   unit          '{no unit}'
   value             25.20000    
end-parameter
parameter 'cSuspSlope'
   description   'undefined'
   unit          '{no unit}'
   value             2.100000    
end-parameter
parameter 'hDepthSusp'
   description   'undefined'
   unit          '{no unit}'
   value             2.000000    
end-parameter
parameter 'cFetchRef'
   description   'undefined'
   unit          '{no unit}'
   value             1000.000    
end-parameter
parameter 'fLutumRef'
   description   'undefined'
   unit          '{no unit}'
   value            0.2000000    
end-parameter
parameter 'cSuspRef'
   description   'CONSTANT  cVCritResus   = 0.1'
   unit          '{no unit}'
   value            0.5000000    
end-parameter
parameter 'kVegResus'
   description   'rel. resuspension reduction per g vegetation'
   unit          'm2/gDW'
   value            0.1000000E-01
end-parameter
parameter 'kTurbFish'
   description   'relative resuspension by adult fish browsing'
   unit          'g/g fish/day'
   value             1.000000    
end-parameter
parameter 'kResusPhyt'
   description   'max. phytopl. resuspension'
   unit          'day-1'
   value            0.2500000    
end-parameter
parameter 'cResusPhyt'
   description   'exp. par. for phytopl. resuspension'
   unit          '(gD/m2/day)-1'
   value           -0.3790000    
end-parameter
parameter 'cThetaMinW'
   description   'expon. temp. constant of mineralization in water'
   unit          '-'
   value             1.070000    
end-parameter
parameter 'kDMinDetW'
   description   'decomposition constant of detritus'
   unit          'day-1'
   value            0.1000000E-01
end-parameter
parameter 'hO2BOD'
   description   'half-sat. oxygen conc. for BOD'
   unit          'mgO2/l'
   value             1.000000    
end-parameter
parameter 'O2PerNO3'
   description   'mol O2 formed per mol NO3- ammonified'
   unit          '-'
   value             1.500000    
end-parameter
parameter 'cThetaMinS'
   description   'expon. temp. constant of sediment mineralization'
   unit          '-'
   value             1.070000    
end-parameter
parameter 'kDMinDetS'
   description   'decomposition constant of sediment detritus'
   unit          'day-1'
   value            0.2000000E-02
end-parameter
parameter 'fRefrDetS'
   description   'refractory fraction of sed. detritus'
   unit          '-'
   value            0.1500000    
end-parameter
parameter 'hNO3Denit'
   description   'quadratic half-sat. NO3 conc. for denitrification'
   unit          'mgN/l'
   value             2.000000    
end-parameter
parameter 'NO3PerC'
   description   'mol NO3 denitrified per mol C mineralised'
   unit          '-'
   value            0.8000000    
end-parameter
parameter 'kDMinHum'
   description   'maximum decomposition constant of humic material ('
   unit          'day-1'
   value            0.1000000E-04
end-parameter
parameter 'kNitrW'
   description   'undefined'
   unit          '{no unit}'
   value            0.1000000    
end-parameter
parameter 'kNitrS'
   description   'undefined'
   unit          '{no unit}'
   value             1.000000    
end-parameter
parameter 'cThetaNitr'
   description   'undefined'
   unit          '{no unit}'
   value             1.080000    
end-parameter
parameter 'O2PerNH4'
   description   'mol O2 used per mol NH4+ nitrified'
   unit          '-'
   value             2.000000    
end-parameter
parameter 'hO2Nitr'
   description   'undefined'
   unit          'mgO2/l'
   value             2.000000    
end-parameter
parameter 'kPDifPO4'
   description   'mol. PO4 diffusion constant'
   unit          'm2/day'
   value            0.7200000E-04
end-parameter
parameter 'kNDifNO3'
   description   'mol. NO3 diffusion constant'
   unit          'm2/day'
   value            0.8600000E-04
end-parameter
parameter 'kNDifNH4'
   description   'mol. NH4 diffusion constant'
   unit          'm2/day'
   value            0.1120000E-03
end-parameter
parameter 'kO2Dif'
   description   'mol. O2 diffusion constant'
   unit          'm2/day'
   value            0.2600000E-04
end-parameter
parameter 'cThetaDif'
   description   'Temperature coefficient for diffusion'
   unit          '{no unit}'
   value             1.020000    
end-parameter
parameter 'fDepthDifS'
   description   'nutrient diffusion distance as fraction of sedimen'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'cTurbDifNu'
   description   'bioturbation factor for diffusion'
   unit          '-'
   value             5.000000    
end-parameter
parameter 'cTurbDifO2'
   description   'bioturbation factor for diffusion'
   unit          '-'
   value             5.000000    
end-parameter
parameter 'kPSorp'
   description   'P sorption rate constant   not too high -> model s'
   unit          'day-1'
   value            0.5000000E-01
end-parameter
parameter 'cRelPAdsD'
   description   'max. P adsorption per g DW'
   unit          'gP/gD'
   value            0.3000000E-04
end-parameter
parameter 'cRelPAdsFe'
   description   'max. P adsorption per g Fe'
   unit          'gP/gFe'
   value            0.6500000E-01
end-parameter
parameter 'cRelPAdsAl'
   description   'max. P adsorption per g Al'
   unit          'gP/gAl'
   value            0.1340000    
end-parameter
parameter 'cKPAdsOx'
   description   'P adsorption affinity at oxidized conditions'
   unit          'm3/gP'
   value            0.6000000    
end-parameter
parameter 'fRedMax'
   description   'max. reduction factor of P adsorption affinity'
   unit          '-'
   value            0.9000000    
end-parameter
parameter 'coPO4Max'
   description   'max. SRP conc. in pore water'
   unit          'mgP/l'
   value             1.000000    
end-parameter
parameter 'kPChemPO4'
   description   'chem. PO4 loss rate'
   unit          'day-1'
   value            0.3000000E-01
end-parameter
parameter 'fObstrLemn'
   description   'obstructed fraction of duckweed outflow'
   unit          '-'
   value             1.000000    
end-parameter
parameter 'cDayManVeg'
   description   'first mowing day (default: non-existent)'
   unit          'day'
   value            -9999000.    
end-parameter
parameter 'cDayManVe2'
   description   'second mowing day (Note: 259 = 16 Sep)'
   unit          'day'
   value            -9999000.    
end-parameter
parameter 'fManVeg'
   description   'Fraction removed by management , for submerged pla'
   unit          '-'
   value             0.000000    
end-parameter
parameter 'fManLemn'
   description   'Fraction of duckweed removed by management'
   unit          '-'
   value             0.000000    
end-parameter
parameter 'fManHelo'
   description   'Fraction of helophytes and nymphaeids removed by m'
   unit          '-'
   value             0.000000    
end-parameter
parameter 'cLengMan'
   description   'length of mowing period'
   unit          'day'
   value             10.00000    
end-parameter
parameter 'cYearStart'
   description   'first year of birds  presence'
   unit          'y'
   value             0.000000    
end-parameter
parameter 'cDayStartB'
   description   'yearly first day of birds  presence'
   unit          'day'
   value             46.00000    
end-parameter
parameter 'cDayEndBir'
   description   'yearly last day of birds  presence'
   unit          'day'
   value             288.0000    
end-parameter
parameter 'cBirdsPerh'
   description   'number of birds per ha vegetated lake (Default = 0'
   unit          'n/ha'
   value             0.000000    
end-parameter
parameter 'cDGrazPerB'
   description   'daily grazing of birds'
   unit          'gD/coot/day'
   value             45.00000    
end-parameter
parameter 'hDVegBird'
   description   'half-sat. vegetation biomass'
   unit          '{no unit}'
   value             5.000000    
end-parameter
parameter 'fDAssBird'
   description   'birds assim. efficiency'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'fDissEgesB'
   description   'fraction dissolved nutrient of coot egestion'
   unit          '-'
   value            0.2500000    
end-parameter
parameter 'fDissMortV'
   description   'fraction dissolved nutrients from died plants'
   unit          '-'
   value            0.2500000    
end-parameter
parameter 'cLengAllo'
   description   'duration of allocation and reallocation phase'
   unit          'day'
   value             15.00000    
end-parameter
parameter 'cLengMort'
   description   'duration of autumn mortality period'
   unit          'day'
   value             15.00000    
end-parameter
parameter 'UseEmpUpt'
   description   'F = do not use this empirical relation.'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'fSedUptVeg'
   description   'maximum sediment fraction of nutrient uptake'
   unit          '-'
   value            0.9980000    
end-parameter
parameter 'fSedUptVef'
   description   'sigm. regr. coeff. for sediment fraction of nutrie'
   unit          '-'
   value             2.660000    
end-parameter
parameter 'fSedUptVep'
   description   'exponent in sigm. regr. for sediment fraction of n'
   unit          '0.83   -'
   value             0.000000    
end-parameter
parameter 'fRootVegSu'
   description   'root fraction outside growing season'
   unit          'g root / g veg'
   value            0.1000000    
end-parameter
parameter 'fRootVegWi'
   description   'root fraction outside growing season'
   unit          'g root / g veg'
   value            0.6000000    
end-parameter
parameter 'fFloatVeg'
   description   'floating fraction of shoot'
   unit          'g floating / g shoot'
   value             0.000000    
end-parameter
parameter 'fEmergVeg'
   description   'emergent fraction of shoot'
   unit          'g floating / g shoot'
   value             0.000000    
end-parameter
parameter 'fDepth1Veg'
   description   'max. upper depth of submerged veget. layer, as fra'
   unit          '-'
   value             0.000000    
end-parameter
parameter 'fDepth2Veg'
   description   'max. lower depth of submerged veget. layer, as fra'
   unit          '-'
   value             1.000000    
end-parameter
parameter 'cDLayerVeg'
   description   'biomass of a single layer floating leaves'
   unit          'gD/m2'
   value             0.000000    
end-parameter
parameter 'cCovSpVeg'
   description   'specific cover'
   unit          '% cover per gD/m2'
   value            0.5000000    
end-parameter
parameter 'kMigrVeg'
   description   'vegetation migration rate'
   unit          'day-1'
   value            0.1000000E-02
end-parameter
parameter 'cDVegIn'
   description   ' external vegetation density'
   unit          'gD/m2'
   value             1.000000    
end-parameter
parameter 'cTmInitVeg'
   description   'temperature for initial growth'
   unit          'oC'
   value             9.000000    
end-parameter
parameter 'cDCarrVeg'
   description   'max. vegetation standing crop'
   unit          'gDW/m2'
   value             400.0000    
end-parameter
parameter 'cMuMaxVeg'
   description   'maximum growth rate of vegetation at 20oC'
   unit          'g/g shoot/day'
   value            0.2000000    
end-parameter
parameter 'cQ10ProdVe'
   description   'temperature quotient of production'
   unit          '-'
   value             1.200000    
end-parameter
parameter 'hLRefVeg'
   description   'half-sat. light at 20 oC'
   unit          'W/m2 PAR'
   value             17.00000    
end-parameter
parameter 'cExtSpVeg'
   description   'specific extinction'
   unit          'm2/gDW'
   value            0.1000000E-01
end-parameter
parameter 'kDRespVeg'
   description   'dark respiration rate of vegetation'
   unit          'day-1'
   value            0.2000000E-01
end-parameter
parameter 'cQ10RespVe'
   description   'temperature quotient of respiration'
   unit          '-'
   value             2.000000    
end-parameter
parameter 'kMortVegSu'
   description   'vegetation mortality rate in Spring and Summer  (l'
   unit          'day-1'
   value            0.5000000E-02
end-parameter
parameter 'fWinVeg'
   description   'fraction surviving in winter'
   unit          '-'
   value            0.3000000    
end-parameter
parameter 'cDayWinVeg'
   description   'end of growing season  = 16 Sep'
   unit          'day'
   value             259.0000    
end-parameter
parameter 'fDetWMortV'
   description   'fraction of shoot mortality becoming water detritu'
   unit          '-'
   value            0.1000000    
end-parameter
parameter 'cPrefVegBi'
   description   'edibility for birds'
   unit          '-'
   value             1.000000    
end-parameter
parameter 'cVPUptMaxV'
   description   'maximum P uptake capacity of vegetation'
   unit          'mgP/mgD/day'
   value            0.1000000E-01
end-parameter
parameter 'cAffPUptVe'
   description   'initial P uptake affinity vegetation'
   unit          'l/mgD/day'
   value            0.2000000    
end-parameter
parameter 'cPDVegMin'
   description   'minimum P/day ratio vegetation'
   unit          'mgP/mg'
   value            0.8000000E-03
end-parameter
parameter 'cPDVegMax'
   description   'maximum P/day ratio vegetation'
   unit          'mgP/mgD'
   value            0.3500000E-02
end-parameter
parameter 'cVNUptMaxV'
   description   'maximum N uptake capacity of vegetation'
   unit          'mgN/mgD/day'
   value            0.1000000    
end-parameter
parameter 'cAffNUptVe'
   description   'initial N uptake affinity vegetation'
   unit          'l/mgD/day'
   value            0.2000000    
end-parameter
parameter 'cNDVegMin'
   description   'minimum N/day ratio vegetation'
   unit          'mgN/mgD'
   value            0.1000000E-01
end-parameter
parameter 'cNDVegMax'
   description   'maximum N/day ratio vegetation'
   unit          'mgN/mgD'
   value            0.3500000E-01
end-parameter
parameter 'cPACoefMin'
   description   'minimum Poole-Atkins coefficient'
   unit          '-'
   value             1.500000    
end-parameter
parameter 'cPACoefMax'
   description   '3.0'
   unit          '{no unit}'
   value             2.500000    
end-parameter
parameter 'hPACoef'
   description   'decrease constant for P.A. coeff. with DOMW'
   unit          'g/m2'
   value             3.000000    
end-parameter
parameter 'cSecchiPlu'
   description   'maximum Secchi depth above water depth'
   unit          'm'
   value             0.000000    
end-parameter
parameter 'cEuph'
   description   'conversion constant Secchi depth -> euphotic depth'
   unit          '-'
   value             1.700000    
end-parameter
parameter 'cCovSpPhyt'
   description   'specific coverage  Tentative'
   unit          '% per gD/m2'
   value             2.000000    
end-parameter
parameter 'cTmOptLoss'
   description   'optimum temp. for grazing'
   unit          'oC'
   value             25.00000    
end-parameter
parameter 'cSigTmLoss'
   description   'temperature constant of grazing(sigma in Gaussian'
   unit          'oC'
   value             13.00000    
end-parameter
parameter 'fDissMortP'
   description   'soluble nutrient fraction of died Algae'
   unit          '-'
   value            0.2000000    
end-parameter
parameter 'fDissLoss'
   description   'dissolved nutrient fraction of grazing loss'
   unit          '-'
   value            0.2500000    
end-parameter
parameter 'cMuMaxDiat'
   description   'maximum growth rate Diatoms'
   unit          'day-1'
   value             2.000000    
end-parameter
parameter 'cTmOptDiat'
   description   'optimum temp. diatoms'
   unit          'oC'
   value             18.00000    
end-parameter
parameter 'cSigTmDiat'
   description   'temperature constant diatoms(sigma in Gaussian cur'
   unit          'oC'
   value             20.00000    
end-parameter
parameter 'cExtSpDiat'
   description   'specific extinction Diatoms'
   unit          'm2/gDW'
   value            0.2500000    
end-parameter
parameter 'UseSteeleD'
   description   ' Flag : 1 = use Steele function,0 = use Lehman fun'
   unit          '{no unit}'
   value             1.000000    
end-parameter
parameter 'cLOptRefDi'
   description   'optimum PAR for Diatoms at 20 oC(Steele function)'
   unit          'W/m2'
   value             54.00000    
end-parameter
parameter 'hLRefDiat'
   description   'half-sat. PAR at 20 oC(Lehmann function)   Fake va'
   unit          'W/m2'
   value             1000.000    
end-parameter
parameter 'cChDDiatMi'
   description   'min. chlorophyll/C ratio Diatoms'
   unit          'mgChl/mgDW'
   value            0.4000000E-02
end-parameter
parameter 'cChDDiatMa'
   description   'max. chlorophyll/C ratio Diatoms'
   unit          'mgChl/mgDW'
   value            0.1200000E-01
end-parameter
parameter 'kDRespDiat'
   description   'maintenance respiration constant diatoms(= 0.05 *'
   unit          'day-1'
   value            0.1000000    
end-parameter
parameter 'kLossDiat'
   description   'grazing loss rate for Diatoms'
   unit          '-'
   value            0.2500000    
end-parameter
parameter 'kMortDiatW'
   description   'mortality constant of Diatoms in water'
   unit          'day-1'
   value            0.1000000E-01
end-parameter
parameter 'kMortDiatS'
   description   'mortality constant of sed. Diatoms'
   unit          'day-1'
   value            0.5000000E-01
end-parameter
parameter 'cVSetDiat'
   description   'sedimentation velocity Diatoms'
   unit          'm/day'
   value            0.5000000    
end-parameter
parameter 'cVPUptMaxD'
   description   'maximum P uptake capacity of Diatoms'
   unit          'mgP/mgDW/day'
   value            0.1000000E-01
end-parameter
parameter 'cAffPUptDi'
   description   'initial P uptake affinity Diatoms'
   unit          'l/mgDW/day'
   value            0.2000000    
end-parameter
parameter 'cPDDiatMin'
   description   'minimum P/day ratio Diatoms'
   unit          'mgP/mgDW'
   value            0.5000000E-03
end-parameter
parameter 'cPDDiatMax'
   description   'max. P/day ratio Diatoms'
   unit          'mgP/mgDW'
   value            0.5000000E-02
end-parameter
parameter 'cVNUptMaxD'
   description   'maximum N uptake capacity of Diatoms'
   unit          'mgN/mgDW/day'
   value            0.7000000E-01
end-parameter
parameter 'cAffNUptDi'
   description   'initial N uptake affinity Diatoms'
   unit          'l/mgDW/day'
   value            0.2000000    
end-parameter
parameter 'cNDDiatMin'
   description   'minimum N/day ratio Diatoms'
   unit          'mgN/mgDW'
   value            0.1000000E-01
end-parameter
parameter 'cNDDiatMax'
   description   'max. N/day ratio Diatoms'
   unit          'mgN/mgDW'
   value            0.5000000E-01
end-parameter
parameter 'hSiAssDiat'
   description   '(Pohlmann et al,1989,zie Mylius 1991)'
   unit          '{no unit}'
   value            0.9000000E-01
end-parameter
parameter 'cMuMaxGren'
   description   'maximum growth rate greens'
   unit          'day-1'
   value             1.500000    
end-parameter
parameter 'cTmOptGren'
   description   'optimum temp. of greens'
   unit          'oC'
   value             25.00000    
end-parameter
parameter 'cSigTmGren'
   description   'temperature constant greens(sigma in Gaussian curv'
   unit          'oC'
   value             15.00000    
end-parameter
parameter 'cExtSpGren'
   description   'specific extinction greens'
   unit          'm2/gDW'
   value            0.2500000    
end-parameter
parameter 'UseSteeleG'
   description   ' Flag : 1 = use Steele function,0 = use Lehman fun'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'hLRefGren'
   description   'half-sat. PAR for green algae at 20 oC(Lehmann fun'
   unit          'W/m2'
   value             17.00000    
end-parameter
parameter 'cLOptRefGr'
   description   'optimum PAR at 20 oC(Steele function)    Fake valu'
   unit          'W/m2'
   value             1000.000    
end-parameter
parameter 'cChDGrenMi'
   description   'min. chlorophyll/C ratio greens'
   unit          'mgChl/mgDW'
   value            0.1000000E-01
end-parameter
parameter 'cChDGrenMa'
   description   'max. chlorophyll/C ratio greens'
   unit          'mgChl/mgDW'
   value            0.2000000E-01
end-parameter
parameter 'kDRespGren'
   description   'maintenance respiration constant greens(= 0.05 * M'
   unit          'day-1'
   value            0.7500000E-01
end-parameter
parameter 'kLossGren'
   description   'grazing loss rate for greens'
   unit          '-'
   value            0.2500000    
end-parameter
parameter 'kMortGrenW'
   description   'mortality constant of Diatoms in water'
   unit          'day-1'
   value            0.1000000E-01
end-parameter
parameter 'kMortGrenS'
   description   'mortality constant greens'
   unit          'day-1'
   value            0.5000000E-01
end-parameter
parameter 'cVSetGren'
   description   '0.08'
   unit          '{no unit}'
   value            0.2000000    
end-parameter
parameter 'cVPUptMaxG'
   description   'maximum P uptake capacity of greens'
   unit          'mgP/mgDW/day'
   value            0.1000000E-01
end-parameter
parameter 'cAffPUptGr'
   description   'initial P uptake affinity greens'
   unit          'l/mgDW/day'
   value            0.2000000    
end-parameter
parameter 'cPDGrenMin'
   description   'minimum P/day ratio greens'
   unit          'mgP/mgDW'
   value            0.1500000E-02
end-parameter
parameter 'cPDGrenMax'
   description   'max. P/day ratio greens'
   unit          'mgP/mgDW'
   value            0.1500000E-01
end-parameter
parameter 'cVNUptMaxG'
   description   'maximum N uptake capacity of greens'
   unit          'mgN/mgDW/day'
   value            0.7000000E-01
end-parameter
parameter 'cAffNUptGr'
   description   'initial N uptake affinity greens'
   unit          'l/mgDW/day'
   value            0.2000000    
end-parameter
parameter 'cNDGrenMin'
   description   'minimum N/day ratio greens'
   unit          'mgN/mgDW'
   value            0.2000000E-01
end-parameter
parameter 'cNDGrenMax'
   description   'max. N/day ratio greens'
   unit          'mgN/mgDW'
   value            0.1000000    
end-parameter
parameter 'hSiAssGren'
   description   'half-sat. Si conc. for growth of green algae   = 0'
   unit          'mgSi/l'
   value             0.000000    
end-parameter
parameter 'cMuMaxBlue'
   description   'maximum growth rate Bluegreens'
   unit          'day-1'
   value            0.6000000    
end-parameter
parameter 'cTmOptBlue'
   description   'optimum temp. blue-greens'
   unit          'oC'
   value             25.00000    
end-parameter
parameter 'cSigTmBlue'
   description   'temperature constant blue-greens(sigma in Gaussian'
   unit          'oC'
   value             12.00000    
end-parameter
parameter 'cExtSpBlue'
   description   'specific extinction Bluegreens'
   unit          'm2/gDW'
   value            0.3500000    
end-parameter
parameter 'UseSteeleB'
   description   ' Flag : 1 = use Steele function,0 = use Lehman fun'
   unit          '{no unit}'
   value             1.000000    
end-parameter
parameter 'cLOptRefBl'
   description   'optimum PAR for blue-greens at 20 oC(Steele functi'
   unit          'W/m2'
   value             13.60000    
end-parameter
parameter 'hLRefBlue'
   description   'half-sat. PAR at 20 oC(Lehmann function)   Fake va'
   unit          'W/m2'
   value             1000.000    
end-parameter
parameter 'cChDBlueMi'
   description   'min. chlorophyll/C ratio Bluegreens'
   unit          'mgChl/mgDW'
   value            0.5000000E-02
end-parameter
parameter 'cChDBlueMa'
   description   'max. chlorophyll/C ratio Bluegreens'
   unit          'mgChl/mgDW'
   value            0.1500000E-01
end-parameter
parameter 'cCyDBlueMi'
   description   'min. c-phycocyanin/C ratio Bluegreens'
   unit          'mgChl/mgDW'
   value            0.4000000E-02
end-parameter
parameter 'cCyDBlueMa'
   description   'max. c-phycocyanin/C ratio Bluegreens'
   unit          'mgChl/mgDW'
   value            0.6000000E-01
end-parameter
parameter 'kDRespBlue'
   description   'maintenance respiration constant blue-greens(= 0.0'
   unit          'day-1'
   value            0.3000000E-01
end-parameter
parameter 'kLossBlue'
   description   'grazing loss rate for Blue-greens'
   unit          '-'
   value            0.3000000E-01
end-parameter
parameter 'kMortBlueW'
   description   'mortality constant of blue-greens in water'
   unit          'day-1'
   value            0.1000000E-01
end-parameter
parameter 'kMortBlueS'
   description   'mortality constant Bluegreens'
   unit          'day-1'
   value            0.2000000    
end-parameter
parameter 'cVSetBlue'
   description   'sedimentation velocity Blue-greens'
   unit          'm/day'
   value            0.6000000E-01
end-parameter
parameter 'cVPUptMaxB'
   description   'maximum P uptake capacity of Bluegreens'
   unit          'mgP/mgDW/day'
   value            0.4000000E-01
end-parameter
parameter 'cAffPUptBl'
   description   'initial P uptake affinity Bluegreens'
   unit          'l/mgDW/day'
   value            0.8000000    
end-parameter
parameter 'cPDBlueMin'
   description   'minimum P/day ratio Bluegreens'
   unit          'mgP/mgDW'
   value            0.2500000E-02
end-parameter
parameter 'cPDBlueMax'
   description   'max. P/day ratio blue-greens'
   unit          'mgP/mgDW'
   value            0.2500000E-01
end-parameter
parameter 'cVNUptMaxB'
   description   'maximum N uptake capacity of Bluegreens'
   unit          'mgN/mgDW/day'
   value            0.7000000E-01
end-parameter
parameter 'cAffNUptBl'
   description   'initial N uptake affinity Bluegreens'
   unit          'l/mgDW/day'
   value            0.2000000    
end-parameter
parameter 'cNDBlueMin'
   description   'minimum N/day ratio Bluegreens'
   unit          'mgN/mgDW'
   value            0.3000000E-01
end-parameter
parameter 'cNDBlueMax'
   description   '0.12'
   unit          '{no unit}'
   value            0.1500000    
end-parameter
parameter 'hSiAssBlue'
   description   'half-sat. Si conc. for growth of blue-greens   = 0'
   unit          'mgSi/l'
   value             0.000000    
end-parameter
parameter 'cDBentIn'
   description   'external zoobenthos density'
   unit          'gD/m2'
   value            0.1000000E-01
end-parameter
parameter 'kMigrBent'
   description   'zoobenthos migration rate'
   unit          'day-1'
   value            0.1000000E-02
end-parameter
parameter 'kMigrFish'
   description   'fish migration rate'
   unit          'day-1'
   value            0.1000000E-02
end-parameter
parameter 'cDFiJvIn'
   description   'external fish density'
   unit          'gD/m2'
   value            0.5000000E-02
end-parameter
parameter 'cDFiAdIn'
   description   'external fish density'
   unit          'gD/m2'
   value            0.5000000E-02
end-parameter
parameter 'kHarvFishW'
   description   'fish harvesting fraction in winter'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'kHarvFishS'
   description   'fish harvesting fraction in summer'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'cDPiscIn'
   description   'external Pisc density'
   unit          'gD/m2'
   value            0.1000000E-02
end-parameter
parameter 'kMigrPisc'
   description   'Pisc migration rate'
   unit          'day-1'
   value            0.1000000E-02
end-parameter
parameter 'kHarvPiscW'
   description   'Pisc harvesting fraction in winter'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'kHarvPiscS'
   description   'Pisc harvesting fraction in summer'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'cFiltMax'
   description   'maximum filtering rate(when DOMW=0)'
   unit          'ltr/mgDW/day'
   value             4.500000    
end-parameter
parameter 'hFilt'
   description   'half-sat. food conc. for filtering'
   unit          'mgDW/l'
   value             1.000000    
end-parameter
parameter 'cDCarrZoo'
   description   'carrying capacity of zooplankton'
   unit          'mg/l'
   value             25.00000    
end-parameter
parameter 'cPrefDiat'
   description   'selection factor for Diatoms'
   unit          '-'
   value            0.7500000    
end-parameter
parameter 'cPrefGren'
   description   'selection factor for Greens'
   unit          '-'
   value            0.7500000    
end-parameter
parameter 'cPrefBlue'
   description   'selection factor for Bluegreens  Cal.'
   unit          '-'
   value            0.1250000    
end-parameter
parameter 'cPrefDet'
   description   'selection factor for detritus'
   unit          '-'
   value            0.2500000    
end-parameter
parameter 'fDAssZoo'
   description   'DW-assimilation efficiency of herb. zooplankton'
   unit          '-'
   value            0.3500000    
end-parameter
parameter 'fDissEgesZ'
   description   'soluble nutrient fraction of by herb.zoopl. egeste'
   unit          '-'
   value            0.2500000    
end-parameter
parameter 'kDRespZoo'
   description   'maintenance respiration constant herb.zooplankton'
   unit          'day-1'
   value            0.1500000    
end-parameter
parameter 'kMortZoo'
   description   'mortality constant herb.zooplankton'
   unit          'day-1'
   value            0.4000000E-01
end-parameter
parameter 'fDissMortZ'
   description   'soluble nutrient fraction of died zooplankton'
   unit          '-'
   value            0.1000000    
end-parameter
parameter 'cTmOptZoo'
   description   'optimum temp. zooplankton'
   unit          'oC'
   value             25.00000    
end-parameter
parameter 'cSigTmZoo'
   description   'temperature constant zooplankton(sigma in Gaussian'
   unit          'oC'
   value             13.00000    
end-parameter
parameter 'cDCarrBent'
   description   'tentative'
   unit          '{no unit}'
   value             10.00000    
end-parameter
parameter 'kDAssBent'
   description   'maximum assimilation rate'
   unit          'day-1'
   value            0.1000000    
end-parameter
parameter 'hDFoodBent'
   description   'half-saturating food for zoobenthos'
   unit          'g/m2'
   value             200.0000    
end-parameter
parameter 'fDAssBent'
   description   'C ass. efficiency of zoobenthos'
   unit          '-'
   value            0.3000000    
end-parameter
parameter 'fDissEgest'
   description   'soluble nutrient fraction of by zoobenthos egested'
   unit          '-'
   value            0.2500000    
end-parameter
parameter 'kDRespBent'
   description   'maint. respiration constant of zoobenthos'
   unit          'day-1'
   value            0.5000000E-02
end-parameter
parameter 'kMortBent'
   description   'mortality constant of zoobenthos'
   unit          'day-1'
   value            0.5000000E-02
end-parameter
parameter 'fDissMortB'
   description   'soluble P fraction of died zoobenthos P'
   unit          '-'
   value            0.1000000    
end-parameter
parameter 'cTmOptBent'
   description   'optimum temp. of zoobenthos'
   unit          'oC'
   value             25.00000    
end-parameter
parameter 'cSigTmBent'
   description   'temperature constant of zoobenthos(sigma in Gaussi'
   unit          'oC'
   value             16.00000    
end-parameter
parameter 'fDBone'
   description   'fraction of fish C fixed in bones and scales'
   unit          '-'
   value            0.3500000    
end-parameter
parameter 'fPBone'
   description   'fraction of fish P fixed in bones and scales'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'cDCarrFish'
   description   'carrying capacity of fish(= 100 gFW/m2,Grimm 1983)'
   unit          'gDW/m2'
   value             15.00000    
end-parameter
parameter 'fDissEgesF'
   description   'soluble nutrient fraction of by fish egested food'
   unit          '-'
   value            0.2500000    
end-parameter
parameter 'fDissMortF'
   description   'soluble nutrient fraction of died fish(excl. bones'
   unit          '-'
   value            0.1000000    
end-parameter
parameter 'cTmOptFish'
   description   'optimum temp. of fish'
   unit          'oC'
   value             25.00000    
end-parameter
parameter 'cSigTmFish'
   description   'temperature constant of fish(sigma in Gaussian cur'
   unit          'oC'
   value             10.00000    
end-parameter
parameter 'cDayReprFi'
   description   'reproduction date of fish  = 1 May'
   unit          '-'
   value             120.0000    
end-parameter
parameter 'fReprFish'
   description   'yearly reproduction fraction of adult fish'
   unit          '-'
   value            0.2000000E-01
end-parameter
parameter 'fAgeFish'
   description   'yearly ageing fraction of young fish'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'cRelVegFis'
   description   'decrease of fish feeding per % vegetation cover(ma'
   unit          '-'
   value            0.9000000E-02
end-parameter
parameter 'kDAssFiJv'
   description   'maximum assimilation rate of young fish'
   unit          'day-1'
   value            0.1200000    
end-parameter
parameter 'hDZooFiJv'
   description   'half-saturating zooplankton biomass for young fish'
   unit          'g/m2'
   value             1.250000    
end-parameter
parameter 'fDAssFiJv'
   description   'C assimilation efficiency of young fish'
   unit          '-'
   value            0.4000000    
end-parameter
parameter 'kDRespFiJv'
   description   'maintenance respiration constant of young fish'
   unit          'day-1'
   value            0.1000000E-01
end-parameter
parameter 'kMortFiJv'
   description   'specific mortality of young fish(= 0.1 y-1)'
   unit          'day-1'
   value            0.1370000E-02
end-parameter
parameter 'kDAssFiAd'
   description   'maximum assimilation rate of adult fish'
   unit          'day-1'
   value            0.6000000E-01
end-parameter
parameter 'hDBentFiAd'
   description   'half-saturating zoobenthos biomass for adult fish'
   unit          'g/m2'
   value             2.500000    
end-parameter
parameter 'fDAssFiAd'
   description   'C assimilation efficiency of adult fish'
   unit          '-'
   value            0.4000000    
end-parameter
parameter 'kDRespFiAd'
   description   'maintenance respiration constant of adult fish'
   unit          'day-1'
   value            0.4000000E-02
end-parameter
parameter 'kMortFiAd'
   description   'specific mortality of adult fish(= 0.1 y-1)'
   unit          'day-1'
   value            0.2700000E-03
end-parameter
parameter 'cDCarrPisc'
   description   'maximum carrying capacity of Pisc(=75 kg/ha)'
   unit          'gDW.m-2'
   value             1.200000    
end-parameter
parameter 'cDCarrPisn'
   description   'minimum carrying capacity of Pisc(=6 kg/ha)'
   unit          'gDW.m-2'
   value            0.1000000    
end-parameter
parameter 'cDCarrPise'
   description   'carrying capacity of Pisc for lake without marsh z'
   unit          'gDW.m-2'
   value            0.1000000    
end-parameter
parameter 'cDPhraMinP'
   description   'min. reed biomass for Pisc'
   unit          'gD.m-2'
   value             50.00000    
end-parameter
parameter 'cCovVegMin'
   description   'min. subm.veg. coverage for Pisc'
   unit          '%'
   value             40.00000    
end-parameter
parameter 'cRelPhraPi'
   description   'rel. Pisc density per % reed if subm.veg. absent'
   unit          'gD.m-2.%-1'
   value            0.7500000E-01
end-parameter
parameter 'cRelVegPis'
   description   'extra rel. Pisc density per % reed if aCovVeg > cC'
   unit          'gD.m-2.%-1'
   value            0.3000000E-01
end-parameter
parameter 'kDAssPisc'
   description   'maximum assimilation rate'
   unit          'day-1'
   value            0.2500000E-01
end-parameter
parameter 'hDVegPisc'
   description   'half-sat. vegetation biomass for Pisc growth'
   unit          'g/m2'
   value             5.000000    
end-parameter
parameter 'hDFishPisc'
   description   'half-saturating DFish for Pisc predation'
   unit          'g/m2'
   value             1.000000    
end-parameter
parameter 'fDAssPisc'
   description   'C ass. efficiency of Pisc'
   unit          '-'
   value            0.4000000    
end-parameter
parameter 'fDissEgesP'
   description   'soluble P fraction of by fish egested food'
   unit          '-'
   value            0.2500000    
end-parameter
parameter 'kDRespPisc'
   description   'maint. respiration constant of Pisc'
   unit          'day-1'
   value            0.5000000E-02
end-parameter
parameter 'kMortPisc'
   description   'specific mortality of Pisc  = 0.1 y-1'
   unit          'day-1'
   value            0.2700000E-03
end-parameter
parameter 'fDissMortc'
   description   'soluble nutrient fraction of died Pisc(excl. bones'
   unit          '-'
   value            0.1000000    
end-parameter
parameter 'cTmOptPisc'
   description   'optimum temp. of Pisc'
   unit          'oC'
   value             25.00000    
end-parameter
parameter 'cSigTmPisc'
   description   'temperature constant of Pisc(sigma in Gaussian cur'
   unit          'oC'
   value             10.00000    
end-parameter
parameter 'cPDPhra0'
   description   'initial P/day ratio of reed'
   unit          'gP/gD'
   value            0.2000000E-02
end-parameter
parameter 'cNDPhra0'
   description   'initial N/day ratio of reed'
   unit          'gN/gD'
   value            0.2000000E-01
end-parameter
parameter 'cDensStemP'
   description   'density stem(+/- 13.9)'
   unit          'm-2'
   value             61.50000    
end-parameter
parameter 'cTmInitPhr'
   description   'temp.start initial growth'
   unit          '°C'
   value             8.000000    
end-parameter
parameter 'fDAllPhra'
   description   'allocation fraction'
   unit          '-'
   value            0.3000000    
end-parameter
parameter 'kDAllPhra'
   description   'allocation rate'
   unit          '1/day'
   value            0.5000000E-01
end-parameter
parameter 'cDStemPhra'
   description   'average stem weight'
   unit          'g/m'
   value             6.000000    
end-parameter
parameter 'cQ10ProdPh'
   description   'temp. quotient of production'
   unit          '-'
   value             2.000000    
end-parameter
parameter 'cMuPhraMax'
   description   'maximum growth rate reed'
   unit          '1/day'
   value            0.3000000E-01
end-parameter
parameter 'cDShootPhr'
   description   'max. shoot biomass of reed'
   unit          'gD/m2'
   value             3500.000    
end-parameter
parameter 'cCovSpPhra'
   description   'specific coverage'
   unit          '% cover per gD/m2'
   value            0.1000000    
end-parameter
parameter 'cPDPhraMin'
   description   'min.Phra P/day -ratio'
   unit          '-'
   value            0.8000000E-03
end-parameter
parameter 'cPDPhraMax'
   description   'max.Phra P/day -ratio'
   unit          '-'
   value            0.3000000E-02
end-parameter
parameter 'cNDPhraMin'
   description   'min.Phra N/day -ratio'
   unit          '-'
   value            0.8000000E-02
end-parameter
parameter 'cNDPhraMax'
   description   'max.Phra N/day -ratio'
   unit          '-'
   value            0.3000000E-01
end-parameter
parameter 'cAffNUptPh'
   description   'N uptake affinity reed'
   unit          'l/mgD/day'
   value            0.2000000E-03
end-parameter
parameter 'cAffPUptPh'
   description   'P uptake affinity reed'
   unit          'l/mgD/day'
   value            0.2000000E-03
end-parameter
parameter 'cVNUptPhra'
   description   'max. uptake rate N     0.01'
   unit          'mgN/mgD/day'
   value            0.1000000    
end-parameter
parameter 'cVPUptPhra'
   description   'max. uptake rate P     0.001'
   unit          'mgP/mgD/day'
   value            0.1000000E-01
end-parameter
parameter 'kDRespPhra'
   description   'respiration rate of reed'
   unit          '1/day'
   value            0.1000000E-02
end-parameter
parameter 'cQ10RespPh'
   description   'temp. quotient of respiration'
   unit          '1/e^°C'
   value             2.500000    
end-parameter
parameter 'fDayWin'
   description   'Start autumn'
   unit          '{no unit}'
   value            0.5200000    
end-parameter
parameter 'fDRealPhra'
   description   'reallocated fraction day'
   unit          '-'
   value            0.8500000    
end-parameter
parameter 'kDRealPhra'
   description   'reallocation rate day'
   unit          '1/day'
   value            0.5000000E-01
end-parameter
parameter 'kDMortShoo'
   description   'mortality rate shoots'
   unit          '1/day'
   value             0.000000    
end-parameter
parameter 'kDMortRoot'
   description   'mortality rate roots'
   unit          '1/day'
   value            0.3910000E-03
end-parameter
parameter 'cDayWinPhr'
   description   'begin autumn(16 sept.)'
   unit          'day'
   value             259.0000    
end-parameter
parameter 'cLengMortS'
   description   'length of shoot mort. period'
   unit          'day'
   value             42.00000    
end-parameter
parameter 'cDayManPhr'
   description   'time of management'
   unit          'day'
   value             255.0000    
end-parameter
parameter 'fManPhra'
   description   'fraction biomass loss'
   unit          '-'
   value             0.000000    
end-parameter
parameter 'kDManShoot'
   description   'rate of management'
   unit          '1/day'
   value             1.000000    
end-parameter
parameter 'sDShootPhr'
   description   'shoot biomass'
   unit          'gD/m2'
   value             1000.000    
end-parameter
parameter 'sDRootPhra'
   description   'root biomass'
   unit          'gD/m2'
   value             5000.000    
end-parameter
parameter 'mTemp'
   description   'undefined'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'mLOut'
   description   'undefined'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'mVWind'
   description   'undefined'
   unit          '{no unit}'
   value             0.000000    
end-parameter
output 'Z'
   description   'water depth'
end-output
output 'Q'
   description   'Flow'
end-output
output 'As'
   description   'Flow area'
end-output
output 'dt'
   description   'Quality time step'
end-output
output 'dx'
   description   'Half of the length of section'
end-output
output 'V'
   description   'Half of the volume of section'
end-output
output 'Wf'
   description   'Wind velocity'
end-output
output 'Wd'
   description   'Wind direction'
end-output
output 'sDepthW'
   description   ' Z'
end-output
output 'sDPhytW'
   description   ' 0.0'
end-output
output 'sPPhytW'
   description   ' 0.0'
end-output
output 'sNPhytW'
   description   ' 0.0'
end-output
output 'sDPhytS'
   description   ' 0.0'
end-output
output 'sPPhytS'
   description   ' 0.0'
end-output
output 'sNPhytS'
   description   ' 0.0'
end-output
output 'sDElod'
   description   ' 0.0'
end-output
output 'sDChar'
   description   ' 0.0'
end-output
output 'sDCera'
   description   ' 0.0'
end-output
output 'sDLemn'
   description   ' 0.0'
end-output
output 'sDNymp'
   description   ' 0.0'
end-output
output 'sDHelo'
   description   ' 0.0'
end-output
output 'sPElod'
   description   ' 0.0'
end-output
output 'sPChar'
   description   ' 0.0'
end-output
output 'sPCera'
   description   ' 0.0'
end-output
output 'sPLemn'
   description   ' 0.0'
end-output
output 'sPNymp'
   description   ' 0.0'
end-output
output 'sPHelo'
   description   ' 0.0'
end-output
output 'sNElod'
   description   ' 0.0'
end-output
output 'sNChar'
   description   ' 0.0'
end-output
output 'sNCera'
   description   ' 0.0'
end-output
output 'sNLemn'
   description   ' 0.0'
end-output
output 'sNNymp'
   description   ' 0.0'
end-output
output 'sNHelo'
   description   ' 0.0'
end-output
output 'DaysPerYea'
   description   ' 365.0'
end-output
output 'TenDays'
   description   ' 10.0'
end-output
output 'HoursPerDa'
   description   ' 24.0'
end-output
output 'SecsPerDay'
   description   ' 86400.0'
end-output
output 'mmPerm'
   description   ' 1000.0'
end-output
output 'm2Perha'
   description   ' 10000.0'
end-output
output 'mgPerg'
   description   ' 1000.0'
end-output
output 'gPerkg'
   description   ' 1000.0'
end-output
output 'gPerton'
   description   ' 1000000.0'
end-output
output 'PerCent'
   description   ' 0.01'
end-output
output 'NearZero'
   description   ' 0.000000000000000000000000000000001'
end-output
output 'molO2molC'
   description   ' 2.6667'
end-output
output 'molO2molN'
   description   ' 2.2857'
end-output
output 'molNmolC'
   description   ' 1.1667'
end-output
output 'cRhoWat'
   description   ' 1000000.0'
end-output
output 'Pi'
   description   ' 2.0*ASIN(1.0)'
end-output
output 'sPDetW0'
   description   ' cPDDet0 * sDDetW0'
end-output
output 'sNDetW0'
   description   ' cNDDet0 * sDDetW0'
end-output
output 'sSiDetW0'
   description   ' cSiDDet0 * sDDetW0'
end-output
output 'bRhoSolidS'
   description   ' fDOrgS0 * cRhoOM + (1 - fDOrgS0) * cRhoIM'
end-output
output 'bPorS'
   description   ' (1.0 - fDTotS0) * bRhoSolidS0 / cRhoWat / ( fDTot'
end-output
output 'bPorCorS'
   description   ' bPorS ** (bPorS + 1.0)'
end-output
output 'bRhoTotS0'
   description   ' bRhoSolidS0 * (1.0 - bPorS)'
end-output
output 'bDTotS0'
   description   ' bRhoTotS0 * cDepthS'
end-output
output 'sDHumS0'
   description   ' (1.0 - fDDetS0) * fDOrgS0 * bDTotS0'
end-output
output 'sDDetS0'
   description   ' fDDetS0 * fDOrgS0 * bDTotS0'
end-output
output 'sDIMS0'
   description   ' bDTotS0 - sDHumS0 - sDDetS0'
end-output
output 'sPHumS0'
   description   ' cPDHum0 * sDHumS0'
end-output
output 'sNHumS0'
   description   ' cNDHum0 * sDHumS0'
end-output
output 'sPDetS0'
   description   ' cPDDet0 * sDDetS0'
end-output
output 'sNDetS0'
   description   ' cNDDet0 * sDDetS0'
end-output
output 'sSiDetS0'
   description   ' cSiDDet0 * sDDetS0'
end-output
output 'sPAIMS0'
   description   ' fPAdsS0 * fPInorgS0 * bDTotS0'
end-output
output 'sPO4S0'
   description   ' (1.0 - fPAdsS0) * fPInorgS0 * bDTotS0'
end-output
output 'sPPhytW0'
   description   ' cPDPhyt0 * sDPhytW0'
end-output
output 'sNPhytW0'
   description   ' cNDPhyt0 * sDPhytW0'
end-output
output 'sPDiatW0'
   description   ' cPDDiat0 * sDDiatW0'
end-output
output 'sNDiatW0'
   description   ' cNDDiat0 * sDDiatW0'
end-output
output 'sPGrenW0'
   description   ' cPDGren0 * sDGrenW0'
end-output
output 'sNGrenW0'
   description   ' cNDGren0 * sDGrenW0'
end-output
output 'sPBlueW0'
   description   ' cPDBlue0 * sDBlueW0'
end-output
output 'sNBlueW0'
   description   ' cNDBlue0 * sDBlueW0'
end-output
output 'sPPhytS0'
   description   ' cPDPhyt0 * sDPhytS0'
end-output
output 'sNPhytS0'
   description   ' cNDPhyt0 * sDPhytS0'
end-output
output 'sPDiatS0'
   description   ' cPDDiat0 * sDDiatS0'
end-output
output 'sNDiatS0'
   description   ' cNDDiat0 * sDDiatS0'
end-output
output 'sPGrenS0'
   description   ' cPDGren0 * sDGrenS0'
end-output
output 'sNGrenS0'
   description   ' cNDGren0 * sDGrenS0'
end-output
output 'sPBlueS0'
   description   ' cPDBlue0 * sDBlueS0'
end-output
output 'sNBlueS0'
   description   ' cNDBlue0 * sDBlueS0'
end-output
output 'sPVeg0'
   description   ' cPDVeg0 * sDVeg0'
end-output
output 'sNVeg0'
   description   ' cNDVeg0 * sDVeg0'
end-output
output 'sPChar0'
   description   ' cPDChar0 * sDChar0'
end-output
output 'sNChar0'
   description   ' cNDChar0 * sDChar0'
end-output
output 'sPElod0'
   description   ' cPDElod0 * sDElod0'
end-output
output 'sNElod0'
   description   ' cNDElod0 * sDElod0'
end-output
output 'sPCera0'
   description   ' cPDCera0 * sDCera0'
end-output
output 'sNCera0'
   description   ' cNDCera0 * sDCera0'
end-output
output 'sPLemn0'
   description   ' cPDLemn0 * sDLemn0'
end-output
output 'sNLemn0'
   description   ' cNDLemn0 * sDLemn0'
end-output
output 'sPNymp0'
   description   ' cPDNymp0 * sDNymp0'
end-output
output 'sNNymp0'
   description   ' cNDNymp0 * sDNymp0'
end-output
output 'sPHelo0'
   description   ' cPDHelo0 * sDHelo0'
end-output
output 'sNHelo0'
   description   ' cNDHelo0 * sDHelo0'
end-output
output 'sPZoo0'
   description   ' cPDZooRef * sDZoo0'
end-output
output 'sNZoo0'
   description   ' cNDZooRef * sDZoo0'
end-output
output 'sPFiJv0'
   description   ' cPDFishRef * sDFiJv0'
end-output
output 'sPFiAd0'
   description   ' cPDFishRef * sDFiAd0'
end-output
output 'sNFiJv0'
   description   ' cNDFishRef * sDFiJv0'
end-output
output 'sNFiAd0'
   description   ' cNDFishRef * sDFiAd0'
end-output
output 'sPBent0'
   description   ' cPDBentRef * sDBent0'
end-output
output 'sNBent0'
   description   ' cNDBentRef * sDBent0'
end-output
output 'uDPhytW0'
   description   ' sDDiatW0 + sDGrenW0 + sDBlueW0'
end-output
output 'uPPhytW0'
   description   ' sPDiatW0 + sPGrenW0 + sPBlueW0'
end-output
output 'uNPhytW0'
   description   ' sNDiatW0 + sNGrenW0 + sNBlueW0'
end-output
output 'uDPhytS0'
   description   ' sDDiatS0 + sDGrenS0 + sDBlueS0'
end-output
output 'uPPhytS0'
   description   ' sPDiatS0 + sPGrenS0 + sPBlueS0'
end-output
output 'uNPhytS0'
   description   ' sNDiatS0 + sNGrenS0 + sNBlueS0'
end-output
output 'uDVeg0'
   description   ' sDVeg0'
end-output
output 'uPVeg0'
   description   ' sPVeg0'
end-output
output 'uNVeg0'
   description   ' sNVeg0'
end-output
output 'uDFish0'
   description   ' sDFiJv0 + sDFiAd0'
end-output
output 'uPFish0'
   description   ' sPFiJv0 + sPFiAd0'
end-output
output 'uNFish0'
   description   ' sNFiJv0 + sNFiAd0'
end-output
output 'uPPisc0'
   description   ' cPDPisc * sDPisc'
end-output
output 'uNPisc0'
   description   ' cNDPisc * sDPisc'
end-output
output 'sPShootPhr'
   description   ' cPDPhra0 * sDShootPhra0'
end-output
output 'sPRootPhra'
   description   ' cPDPhra0 * sDRootPhra0'
end-output
output 'sNShootPhr'
   description   ' cNDPhra0 * sDShootPhra0'
end-output
output 'sNRootPhra'
   description   ' cNDPhra0 * sDRootPhra0'
end-output
output 'uDTotM0'
   description   ' sDShootPhra0 + sDRootPhra0'
end-output
output 'uPTotM0'
   description   ' sPShootPhra0 + sPRootPhra0'
end-output
output 'uNTotM0'
   description   ' sNShootPhra0 + sNRootPhra0'
end-output
output 'uSiTotM0'
   description   ' 0.0'
end-output
output 'uDTotT0'
   description   ' (sDIMW0 + sDDetW0 + uDPhytW0 + sDZoo0) * sDepthW'
end-output
output 'uPTotT0'
   description   ' (sPO4W0 + sPDetW0 + sPAIMW0 + uPPhytW0 + sPZoo0)'
end-output
output 'uNTotT0'
   description   ' (sNH4W0 + sNO3W0 + sNDetW0 + uNPhytW0 + sNZoo0) *'
end-output
output 'uSiTotT0'
   description   ' (sSiO2W0 + sSiDetW0 + cSiDDiat * sDDiatW0) * sDep'
end-output
output 'ukOut'
   description   ' 0.0'
end-output
output 'vTranDepth'
   description   ' 0.0'
end-output
output 'wDTranIMW'
   description   ' 0.0'
end-output
output 'wDTranDetW'
   description   ' 0.0'
end-output
output 'wDTranPhyt'
   description   ' 0.0'
end-output
output 'wDTranZoo'
   description   ' 0.0'
end-output
output 'tDTranTotT'
   description   ' 0.0'
end-output
output 'wO2TranW'
   description   ' 0.0'
end-output
output 'wPTranPO4W'
   description   ' 0.0'
end-output
output 'wPTranAIMW'
   description   ' 0.0'
end-output
output 'wPTranDetW'
   description   ' 0.0'
end-output
output 'wPTranPhyt'
   description   ' 0.0'
end-output
output 'wPTranZoo'
   description   ' 0.0'
end-output
output 'tPTranTotT'
   description   ' 0.0'
end-output
output 'wNTranNH4W'
   description   ' 0.0'
end-output
output 'wNTranNO3W'
   description   ' 0.0'
end-output
output 'wNTranDetW'
   description   ' 0.0'
end-output
output 'wNTranPhyt'
   description   ' 0.0'
end-output
output 'wNTranZoo'
   description   ' 0.0'
end-output
output 'tNTranTotT'
   description   ' 0.0'
end-output
output 'wSiTranSiO'
   description   ' 0.0'
end-output
output 'wSiTranDet'
   description   ' 0.0'
end-output
output 'tSiTranTot'
   description   ' 0.0'
end-output
output 'wDTranBlue'
   description   ' 0.0'
end-output
output 'wPTranBlue'
   description   ' 0.0'
end-output
output 'wNTranBlue'
   description   ' 0.0'
end-output
output 'wDTranGren'
   description   ' 0.0'
end-output
output 'wPTranGren'
   description   ' 0.0'
end-output
output 'wNTranGren'
   description   ' 0.0'
end-output
output 'wDTranDiat'
   description   ' 0.0'
end-output
output 'wPTranDiat'
   description   ' 0.0'
end-output
output 'wNTranDiat'
   description   ' 0.0'
end-output
output 'wDExchIM'
   description   ' 0.0'
end-output
output 'wDExchDet'
   description   ' 0.0'
end-output
output 'wO2Exch'
   description   ' 0.0'
end-output
output 'wPExchPO4'
   description   ' 0.0'
end-output
output 'wPExchDet'
   description   ' 0.0'
end-output
output 'wPExchAIM'
   description   ' 0.0'
end-output
output 'wNExchNH4'
   description   ' 0.0'
end-output
output 'wNExchNO3'
   description   ' 0.0'
end-output
output 'wNExchDet'
   description   ' 0.0'
end-output
output 'wDExchPhyt'
   description   ' 0.0'
end-output
output 'wPExchPhyt'
   description   ' 0.0'
end-output
output 'wNExchPhyt'
   description   ' 0.0'
end-output
output 'wDExchDiat'
   description   ' 0.0'
end-output
output 'wPExchDiat'
   description   ' 0.0'
end-output
output 'wNExchDiat'
   description   ' 0.0'
end-output
output 'wSiExchDia'
   description   ' 0.0'
end-output
output 'wDExchGren'
   description   ' 0.0'
end-output
output 'wPExchGren'
   description   ' 0.0'
end-output
output 'wNExchGren'
   description   ' 0.0'
end-output
output 'wDExchBlue'
   description   ' 0.0'
end-output
output 'wPExchBlue'
   description   ' 0.0'
end-output
output 'wNExchBlue'
   description   ' 0.0'
end-output
output 'wSiExchDet'
   description   ' 0.0'
end-output
output 'wSiExchSiO'
   description   ' 0.0'
end-output
output 'wDExchZoo'
   description   ' 0.0'
end-output
output 'wPExchZoo'
   description   ' 0.0'
end-output
output 'wNExchZoo'
   description   ' 0.0'
end-output
output 'TimeYears'
   description   ' Time / DaysPerYear'
end-output
output 'Day'
   description   ' Time - INT(TimeYears) * DaysPerYear'
end-output
output 'Years'
   description   ' YearZero + TimeYears'
end-output
output 'uTm'
   description   ' mTemp'
end-output
output 'uVWind'
   description   ' cVWind'
end-output
output 'ufDay'
   description   ' cfDayAve - cfDayVar * COS(2.0*Pi*(Time+TenDays) /'
end-output
output 'uLOut'
   description   ' mLOut / ufDay'
end-output
output 'uLDay'
   description   ' cLDayAve - cLDayVar * COS(2.0*Pi*(Time+TenDays)'
end-output
output 'uLPAR0'
   description   '  fPAR * (1.0 - fRefl) * uLOut'
end-output
output 'aExtPhyt'
   description   ' cExtSpDiat * sDDiatW + cExtSpGren * sDGrenW +   c'
end-output
output 'aExtDet'
   description   ' cExtSpDet * sDDetW'
end-output
output 'aExtIM'
   description   ' cExtSpIM * sDIMW'
end-output
output 'aExtCoefOp'
   description   ' cExtWat + aExtIM + aExtDet + aExtPhyt'
end-output
output 'oDPhytW'
   description   ' sDDiatW + sDGrenW + sDBlueW'
end-output
output 'oPPhytW'
   description   ' sPDiatW + sPGrenW + sPBlueW'
end-output
output 'oNPhytW'
   description   ' sNDiatW + sNGrenW + sNBlueW'
end-output
output 'aDPhytS'
   description   ' sDDiatS + sDGrenS + sDBlueS'
end-output
output 'aPPhytS'
   description   ' sPDiatS + sPGrenS + sPBlueS'
end-output
output 'aNPhytS'
   description   ' sNDiatS + sNGrenS + sNBlueS'
end-output
output 'oDOMW'
   description   ' sDDetW + oDPhytW'
end-output
output 'oDSestW'
   description   ' oDOMW + sDIMW'
end-output
output 'oPOMW'
   description   ' oPPhytW + sPDetW'
end-output
output 'oPSestW'
   description   ' oPPhytW + sPDetW + sPAIMW'
end-output
output 'oPInorgW'
   description   ' sPO4W + sPAIMW'
end-output
output 'oPTotW'
   description   ' oPSestW + sPO4W'
end-output
output 'oNDissW'
   description   ' sNO3W + sNH4W'
end-output
output 'oNOMW'
   description   ' oNPhytW + sNDetW'
end-output
output 'oNSestW'
   description   ' oNOMW'
end-output
output 'oNkjW'
   description   ' oNSestW + sNH4W'
end-output
output 'oNTotW'
   description   ' oNkjW + sNO3W'
end-output
output 'aDTotS'
   description   ' sDIMS + sDHumS + sDDetS'
end-output
output 'aRhoTotS'
   description   ' aDTotS / cDepthS'
end-output
output 'aRhoSolidS'
   description   ' (sDIMS * cRhoIM + (sDHumS + sDDetS) * cRhoOM) / a'
end-output
output 'afDTotS'
   description   ' 1.0 / (1.0 + bPorS/(1.0-bPorS) * cRhoWat / aRhoSo'
end-output
output 'afDOrgS'
   description   ' (sDHumS + sDDetS) / aDTotS'
end-output
output 'afDetS'
   description   ' sDDetS / (sDHumS + sDDetS)'
end-output
output 'afDetTotS'
   description   ' sDDetS / (sDIMS + sDHumS + sDDetS)'
end-output
output 'aPInorgS'
   description   ' sPO4S + sPAIMS'
end-output
output 'aPTotAvail'
   description   ' sPDetS + aPInorgS + aPPhytS'
end-output
output 'aPTotS'
   description   ' aPTotAvailS + sPHumS'
end-output
output 'afPInorgS'
   description   ' aPInorgS / aDTotS'
end-output
output 'afPTotS'
   description   ' aPTotS / aDTotS'
end-output
output 'afPO4S'
   description   ' sPO4S / (aPTotAvailS + NearZero)'
end-output
output 'oPO4S'
   description   ' sPO4S / cDepthS / bPorS'
end-output
output 'aNDissS'
   description   ' sNH4S + sNO3S'
end-output
output 'aNkjAvailS'
   description   ' sNDetS + aNPhytS + sNH4S'
end-output
output 'aNkjS'
   description   ' aNkjAvailS + sNHumS'
end-output
output 'aNTotAvail'
   description   ' aNkjAvailS + sNO3S'
end-output
output 'aNTotS'
   description   ' aNkjS + sNO3S'
end-output
output 'afNInorgS'
   description   ' aNDissS / aDTotS'
end-output
output 'afNTotS'
   description   ' aNTotS / aDTotS'
end-output
output 'oNO3S'
   description   ' sNO3S / cDepthS / bPorS'
end-output
output 'oNH4S'
   description   ' sNH4S / cDepthS / bPorS'
end-output
output 'oNDissS'
   description   ' aNDissS / cDepthS / bPorS'
end-output
output 'rPDIMW'
   description   ' sPAIMW / sDIMW'
end-output
output 'rPDIMS'
   description   ' sPAIMS / sDIMS'
end-output
output 'rPDDetW'
   description   ' sPDetW / (sDDetW+NearZero)'
end-output
output 'rNDDetW'
   description   ' sNDetW / (sDDetW+NearZero)'
end-output
output 'rSiDDetW'
   description   ' sSiDetW / (sDDetW+NearZero)'
end-output
output 'rPDHumS'
   description   ' sPHumS / (sDHumS+NearZero)'
end-output
output 'rNDHumS'
   description   ' sNHumS / (sDHumS+NearZero)'
end-output
output 'rPDDetS'
   description   ' sPDetS / (sDDetS+NearZero)'
end-output
output 'rNDDetS'
   description   ' sNDetS / (sDDetS+NearZero)'
end-output
output 'rSiDDetS'
   description   ' sSiDetS / (sDDetS+NearZero)'
end-output
output 'tPInfPO4W'
   description   ' cQInf / mmPerm * sPO4W'
end-output
output 'tNInfNH4W'
   description   ' cQInf / mmPerm * sNH4W'
end-output
output 'tNInfNO3W'
   description   ' cQInf / mmPerm * sNO3W'
end-output
output 'tPInfPO4S'
   description   ' cQInf / mmPerm * oPO4S'
end-output
output 'tNInfNH4S'
   description   ' cQInf / mmPerm * oNH4S'
end-output
output 'tNInfNO3S'
   description   ' cQInf / mmPerm * oNO3S'
end-output
output 'tNH4LoadS'
   description   ' fNH4LoadS * cNLoadS'
end-output
output 'tNO3LoadS'
   description   ' cNLoadS - tNH4LoadS'
end-output
output 'uDErosIM'
   description   ' (1.0 - fDOrgSoil) * cDErosTot'
end-output
output 'uDErosIMS'
   description   ' fSedErosIM * uDErosIM'
end-output
output 'uDErosIMW'
   description   ' uDErosIM - uDErosIMS'
end-output
output 'uDErosOM'
   description   ' fDOrgSoil * cDErosTot'
end-output
output 'uPErosOM'
   description   ' cPDSoilOM * uDErosOM'
end-output
output 'uNErosOM'
   description   ' cNDSoilOM * uDErosOM'
end-output
output 'uO2Sat'
   description   ' 14.652 - 0.41022 * uTm + 0.007991 * uTm**2 -  0.0'
end-output
output 'kAer'
   description   ' cAerRoot * uVWind**0.5 + cAerLin * uVWind +   cAe'
end-output
output 'uFunTmAer'
   description   ' cThetaAer ** (uTm-cTmRef)'
end-output
output 'aFunLemnAe'
   description   ' 1.0'
end-output
output 'tO2Aer'
   description   ' kAer * uFunTmAer * (uO2Sat - sO2W) * aFunLemnAer'
end-output
output 'uFunTmFish'
   description   ' EXP( -0.5/cSigTmFish**2 * ((uTm - cTmOptFish)**2'
end-output
output 'tDTurbFish'
   description   ' (kTurbFish * uFunTmFish * sDFiAd)'
end-output
output 'tDTurbFisM'
   description   ' fLutum * sDIMS / (fLutum * sDIMS + sDDetS) * tDTu'
end-output
output 'aFunVegRes'
   description   ' MAX(1.0 - kVegResus * sDVeg, 0.0)'
end-output
output 'aFunDimSus'
   description   ' cSuspRef * ((cSuspMin + cSuspMax /   (1.0 + EXP(c'
end-output
output 'tDResusTau'
   description   ' MIN(aFunDimSusp, SQRT(aFunDimSusp +NearZero))  *'
end-output
output 'tDResusBar'
   description   ' tDResusTauDead + tDTurbFish'
end-output
output 'tDResusDea'
   description   ' tDResusBareDead * aFunVegResus'
end-output
output 'tDResusIM'
   description   ' fLutum * sDIMS / (fLutum * sDIMS + sDDetS) * tDRe'
end-output
output 'tDResusDet'
   description   ' sDDetS / (fLutum * sDIMS + sDDetS) * tDResusIM'
end-output
output 'akResusPhy'
   description   ' kResusPhytMax * (1.0 - EXP(cResusPhytExp * tDResu'
end-output
output 'tDResusPhy'
   description   ' akResusPhytRef * aDPhytS'
end-output
output 'tPResusDet'
   description   ' rPDDetS * tDResusDet'
end-output
output 'tPResusPO4'
   description   ' sPO4S / sDDetS * tDResusDet'
end-output
output 'tPResusAIM'
   description   ' sPAIMS / sDIMS * tDResusIM'
end-output
output 'tNResusNO3'
   description   ' sNO3S / sDDetS * tDResusDet'
end-output
output 'tNResusNH4'
   description   ' sNH4S / sDDetS * tDResusDet'
end-output
output 'tNResusDet'
   description   ' rNDDetS * tDResusDet'
end-output
output 'tSiResusDe'
   description   ' rSiDDetS * tDResusDet'
end-output
output 'aFunTauSet'
   description   ' MIN(1.0 / SQRT(aFunDimSusp +NearZero), 1.0)'
end-output
output 'aFunTauSeM'
   description   ' aFunTauSetOM'
end-output
output 'uFunTmSet'
   description   ' cThetaSet ** (uTm-cTmRef)'
end-output
output 'uCorVSetIM'
   description   ' aFunTauSetIM * SQRT(fLutumRef/fLutum) * uFunTmSet'
end-output
output 'tDSetIM'
   description   ' uCorVSetIM * sDIMW'
end-output
output 'tPSetAIM'
   description   ' sPAIMW / sDIMW * tDSetIM'
end-output
output 'uCorVSetDe'
   description   ' cVSetDet * aFunTauSetOM * uFunTmSet'
end-output
output 'tDSetDet'
   description   ' uCorVSetDet * sDDetW'
end-output
output 'tPSetDet'
   description   ' uCorVSetDet * sPDetW'
end-output
output 'tNSetDet'
   description   ' uCorVSetDet * sNDetW'
end-output
output 'tSiSetDet'
   description   ' uCorVSetDet * sSiDetW'
end-output
output 'kPMinDetW'
   description   ' kDMinDetW'
end-output
output 'kNMinDetW'
   description   ' kDMinDetW'
end-output
output 'kSiMinDetW'
   description   ' kDMinDetW'
end-output
output 'uFunTmMinW'
   description   ' cThetaMinW ** (uTm-cTmRef)'
end-output
output 'wDMinDetW'
   description   ' kDMinDetW * uFunTmMinW * sDDetW'
end-output
output 'wPMinDetW'
   description   ' kPMinDetW * uFunTmMinW * sPDetW'
end-output
output 'wNMinDetW'
   description   ' kNMinDetW * uFunTmMinW * sNDetW'
end-output
output 'wSiMinDetW'
   description   ' kSiMinDetW * uFunTmMinW * sSiDetW'
end-output
output 'aCorO2BOD'
   description   ' sO2W / (hO2BOD + sO2W)'
end-output
output 'wO2MinDetW'
   description   ' molO2molC * cCPerDW * aCorO2BOD * wDMinDetW'
end-output
output 'wDDenitW'
   description   ' sNO3W**2.0 / (hNO3Denit**2.0 + sNO3W**2.0)   * (1'
end-output
output 'wNDenitW'
   description   ' NO3PerC * molNmolC * cCPerDW * wDDenitW'
end-output
output 'uFunTmNitr'
   description   ' cThetaNitr ** (uTm-cTmRef)'
end-output
output 'aCorO2Nitr'
   description   ' sO2W ** 2.0 / (hO2Nitr ** 2.0 + sO2W ** 2.0)'
end-output
output 'wNNitrW'
   description   ' kNitrW * uFunTmNitr * aCorO2NitrW * sNH4W'
end-output
output 'wO2NitrW'
   description   ' O2PerNH4 * molO2molN * wNNitrW'
end-output
output 'kPMinDetS'
   description   ' kDMinDetS'
end-output
output 'kNMinDetS'
   description   ' kDMinDetS'
end-output
output 'kSiMinDetS'
   description   ' kDMinDetS'
end-output
output 'uFunTmMinS'
   description   ' cThetaMinS ** (uTm-cTmRef)'
end-output
output 'tDMinDetS'
   description   ' kDMinDetS * uFunTmMinS * sDDetS'
end-output
output 'tPMinDetS'
   description   ' kPMinDetS * uFunTmMinS * sPDetS'
end-output
output 'tNMinDetS'
   description   ' kNMinDetS * uFunTmMinS * sNDetS'
end-output
output 'tSiMinDetS'
   description   ' kSiMinDetS * uFunTmMinS * sSiDetS'
end-output
output 'uFunTmDif'
   description   ' cThetaDif ** (uTm-cTmRef)'
end-output
output 'akO2DifCor'
   description   ' kO2Dif * uFunTmDif * cTurbDifO2 * bPorCorS'
end-output
output 'tSOD'
   description   ' (molO2molC * cCPerDW * (1.0 - fRefrDetS) * tDMinD'
end-output
output 'aDepthOxyS'
   description   ' (2.0 * sO2W * akO2DifCor / tSOD) ** 0.5'
end-output
output 'afOxySed'
   description   ' aDepthOxySed / cDepthS'
end-output
output 'tDMinOxyDe'
   description   ' afOxySed * (1.0 - fRefrDetS) * tDMinDetS'
end-output
output 'tO2MinDetS'
   description   ' molO2molC * cCPerDW * tDMinOxyDetS'
end-output
output 'tDDenitS'
   description   ' oNO3S**2.0 / (hNO3Denit**2.0 + oNO3S**2.0)   * (1'
end-output
output 'tNDenitS'
   description   ' NO3PerC * molNmolC * cCPerDW * tDDenitS'
end-output
output 'tNNitrS'
   description   ' afOxySed * kNitrS * uFunTmNitr * sNH4S'
end-output
output 'tO2NitrS'
   description   ' O2PerNH4 * molO2molN * tNNitrS'
end-output
output 'tDMinHumS'
   description   ' kDMinHum * uFunTmMinS * afOxySed * sDHumS'
end-output
output 'tPMinHumS'
   description   ' kDMinHum * uFunTmMinS * afOxySed * sPHumS'
end-output
output 'tNMinHumS'
   description   ' kDMinHum * uFunTmMinS * afOxySed * sNHumS'
end-output
output 'aDepthDif'
   description   ' fDepthDifS * cDepthS'
end-output
output 'tPDifPO4'
   description   ' kPDifPO4 * uFunTmDif * cTurbDifNut * bPorCorS *'
end-output
output 'tNDifNO3'
   description   ' kNDifNO3 * uFunTmDif * cTurbDifNut * bPorCorS *'
end-output
output 'tNDifNH4'
   description   ' kNDifNH4 * uFunTmDif * cTurbDifNut * bPorCorS *'
end-output
output 'tO2Dif'
   description   ' kO2Dif / aDepthDif * uFunTmDif * cTurbDifO2 * bPo'
end-output
output 'tPDifGroun'
   description   ' 0.0'
end-output
output 'tNDifGroun'
   description   ' 0.0'
end-output
output 'tNDifGrou4'
   description   ' 0.0'
end-output
output 'aPAdsMaxW'
   description   ' cRelPAdsD + aCorO2BOD * cRelPAdsFe * fFeDIM   + c'
end-output
output 'aKPAdsW'
   description   ' (1.0 - fRedMax * (1.0-aCorO2BOD)) * cKPAdsOx'
end-output
output 'aPIsoAdsW'
   description   ' aPAdsMaxW * aKPAdsW * sPO4W / (1.0 + aKPAdsW * sP'
end-output
output 'aPEqIMW'
   description   ' aPIsoAdsW * sDIMW'
end-output
output 'wPSorpIMW'
   description   ' kPSorp * (aPEqIMW - sPAIMW)'
end-output
output 'aPAdsMaxS'
   description   ' cRelPAdsD + afOxySed * cRelPAdsFe * fFeDIM    + c'
end-output
output 'aKPAdsS'
   description   ' (1.0 - fRedMax * (1.0-afOxySed)) * cKPAdsOx'
end-output
output 'aPIsoAdsS'
   description   ' aPAdsMaxS * aKPAdsS * oPO4S / (1.0 + aKPAdsS * oP'
end-output
output 'aPEqIMS'
   description   ' aPIsoAdsS * sDIMS'
end-output
output 'tPSorpIMS'
   description   ' kPSorp * (aPEqIMS - sPAIMS)'
end-output
output 'tPChemPO4'
   description   ' MAX( 0.0, kPChemPO4 * (oPO4S - coPO4Max) )'
end-output
output 'wDAbioIMW'
   description   ' (uDErosIMW - tDSetIM + tDResusIM) / sDepthW'
end-output
output 'wDAbioDetW'
   description   ' (- tDSetDet + tDResusDet ) / sDepthW - wDMinDetW'
end-output
output 'tDAbioIMS'
   description   ' uDErosIMS + tDSetIM - tDResusIM'
end-output
output 'tDAbioDetS'
   description   ' tDSetDet - tDResusDet - tDMinDetS'
end-output
output 'tDAbioHumS'
   description   ' uDErosOM + fRefrDetS * tDMinDetS - tDMinHumS'
end-output
output 'tDAbioTotT'
   description   ' cDErosTot - wDMinDetW * sDepthW   - (1.0 - fRefrD'
end-output
output 'wO2AbioW'
   description   ' tO2Aer / sDepthW - wO2MinDetW - wO2NitrW   - (tO2'
end-output
output 'wPAbioDetW'
   description   ' - wPMinDetW - (tPSetDet - tPResusDet) / sDepthW'
end-output
output 'wPAbioPO4W'
   description   ' wPMinDetW - wPSorpIMW - tPInfPO4W / sDepthW   + t'
end-output
output 'wPAbioAIMW'
   description   ' (- tPSetAIM + tPResusAIM) / sDepthW + wPSorpIMW'
end-output
output 'tPAbioDetS'
   description   ' - tPMinDetS + tPSetDet - tPResusDet'
end-output
output 'tPAbioHumS'
   description   ' uPErosOM + fRefrDetS * tPMinDetS - tPMinHumS'
end-output
output 'tPAbioPO4S'
   description   ' tPInfPO4W - tPInfPO4S + (1.0-fRefrDetS) * tPMinDe'
end-output
output 'tPAbioAIMS'
   description   ' tPSetAIM - tPResusAIM + tPSorpIMS'
end-output
output 'tPAbioTotT'
   description   ' uPErosOM - tPChemPO4 - tPInfPO4S - tPDifGroundPO4'
end-output
output 'wNAbioNH4W'
   description   ' wNMinDetW - wNNitrW - tNInfNH4W / sDepthW   + (tN'
end-output
output 'wNAbioNO3W'
   description   ' wNNitrW - wNDenitW + (tNDifNO3 + tNResusNO3 - tNI'
end-output
output 'wNAbioDetW'
   description   ' - wNMinDetW - (tNSetDet - tNResusDet ) / sDepthW'
end-output
output 'tNAbioNH4S'
   description   ' tNInfNH4W - tNInfNH4S + (1.0-fRefrDetS) * tNMinDe'
end-output
output 'tNAbioNO3S'
   description   ' tNInfNO3W - tNInfNO3S + tNNitrS - tNDenitS   - tN'
end-output
output 'tNAbioDetS'
   description   ' - tNMinDetS + tNSetDet - tNResusDet'
end-output
output 'tNAbioHumS'
   description   ' uNErosOM + fRefrDetS * tNMinDetS - tNMinHumS'
end-output
output 'tNAbioTotT'
   description   ' uNErosOM - tNDenitS - wNDenitW * sDepthW - tNInfN'
end-output
output 'wSiAbioSiO'
   description   ' wSiMinDetW + (1.0 - fRefrDetS) * tSiMinDetS / sDe'
end-output
output 'wSiAbioDet'
   description   ' - wSiMinDetW - (tSiSetDet - tSiResusDet) / sDepth'
end-output
output 'tSiAbioDet'
   description   ' - tSiMinDetS + tSiSetDet - tSiResusDet'
end-output
output 'tSiAbioTot'
   description   ' - fRefrDetS * tSiMinDetS'
end-output
output 'FlagInitVe'
   description   ' 0'
end-output
output 'aDayInitVe'
   description   ' Day'
end-output
output 'bfRootVeg'
   description   ' fRootVegWin'
end-output
output 'bfShootVeg'
   description   ' 1.0 - bfRootVeg'
end-output
output 'aDRootVeg'
   description   ' bfRootVeg * sDVeg'
end-output
output 'aDShootVeg'
   description   ' bfShootVeg * sDVeg'
end-output
output 'aDEmergVeg'
   description   ' fEmergVeg * aDShootVeg'
end-output
output 'aDFloatVeg'
   description   ' fFloatVeg * aDShootVeg'
end-output
output 'bfSubVeg'
   description   ' 1.0 - fFloatVeg - fEmergVeg'
end-output
output 'aDSubVeg'
   description   ' bfSubVeg * aDShootVeg'
end-output
output 'aExtVeg'
   description   ' cExtSpVeg * aDSubVeg / sDepthW'
end-output
output 'aDepth1Veg'
   description   ' fDepth1Veg * sDepthW'
end-output
output 'aDepth2Veg'
   description   ' fDepth2Veg * sDepthW'
end-output
output 'afCovSurfV'
   description   ' MIN(1.0, MAX(aDFloatVeg / (cDLayerVeg   + NearZer'
end-output
output 'afCovEmerg'
   description   ' MIN(1.0, PerCent * cCovSpVeg * aDEmergVeg)'
end-output
output 'aCovVeg'
   description   ' MIN(100.0, cCovSpVeg * aDShootVeg)'
end-output
output 'aDVeg'
   description   ' sDVeg'
end-output
output 'aPVeg'
   description   ' sPVeg'
end-output
output 'aNVeg'
   description   ' sNVeg'
end-output
output 'aExtCoef'
   description   ' aExtCoefOpen + aExtVeg'
end-output
output 'aLPARBot'
   description   '  uLPAR0 * EXP(- aExtCoef * sDepthW)'
end-output
output 'rPDVeg'
   description   ' sPVeg / (sDVeg+NearZero)'
end-output
output 'rNDVeg'
   description   ' sNVeg / (sDVeg+NearZero)'
end-output
output 'tDMigrVeg'
   description   ' kMigrVeg * (cDVegIn - sDVeg)'
end-output
output 'tPMigrVeg'
   description   ' kMigrVeg * (cPDVeg0* cDVegIn - sPVeg)'
end-output
output 'tNMigrVeg'
   description   ' kMigrVeg * (cNDVeg0* cDVegIn - sNVeg)'
end-output
output 'uFunTmProd'
   description   ' cQ10ProdVeg ** (0.1 * (uTm - cTmRef))'
end-output
output 'uFunTmResp'
   description   ' cQ10RespVeg ** (0.1 * (uTm - cTmRef))'
end-output
output 'aVPUptMaxC'
   description   ' MAX( 0.0,  cVPUptMaxVeg * uFunTmProdVeg *  (cPDVe'
end-output
output 'aVPUptVegW'
   description   ' sPO4W * aVPUptMaxCrVeg /  (aVPUptMaxCrVeg / cAffP'
end-output
output 'tPUptVegW'
   description   ' aVPUptVegW * (aDSubVeg + aDFloatVeg)'
end-output
output 'aVPUptVegS'
   description   ' oPO4S * aVPUptMaxCrVeg /  (aVPUptMaxCrVeg / cAffP'
end-output
output 'tPUptVegS'
   description   ' aVPUptVegS * aDRootVeg'
end-output
output 'tPUptVeg'
   description   ' tPUptVegW + tPUptVegS'
end-output
output 'aVNUptMaxC'
   description   ' MAX( 0.0,  cVNUptMaxVeg * uFunTmProdVeg *  (cNDVe'
end-output
output 'ahNUptVeg'
   description   ' aVNUptMaxCrVeg / cAffNUptVeg'
end-output
output 'aVNUptVegW'
   description   ' oNDissW * aVNUptMaxCrVeg / (ahNUptVeg + oNDissW)'
end-output
output 'tNUptVegW'
   description   ' aVNUptVegW * (aDSubVeg + aDFloatVeg)'
end-output
output 'afNH4UptVe'
   description   ' sNH4W * sNO3W / ((ahNUptVeg + sNH4W) *  (ahNUptVe'
end-output
output 'tNUptNH4Ve'
   description   ' afNH4UptVegW * tNUptVegW'
end-output
output 'tNUptNO3Ve'
   description   ' tNUptVegW - tNUptNH4VegW'
end-output
output 'aVNUptVegS'
   description   ' oNDissS * aVNUptMaxCrVeg / (ahNUptVeg + oNDissS)'
end-output
output 'tNUptVegS'
   description   ' aVNUptVegS * aDRootVeg'
end-output
output 'afNH4UptVS'
   description   ' oNH4S * oNO3S / ((ahNUptVeg + oNH4S +NearZero) *'
end-output
output 'tNUptNH4VS'
   description   ' afNH4UptVegS * tNUptVegS'
end-output
output 'tNUptNO3VS'
   description   ' tNUptVegS - tNUptNH4VegS'
end-output
output 'tNUptVeg'
   description   ' tNUptVegW + tNUptVegS'
end-output
output 'afPUptVegS'
   description   ' 0.0'
end-output
output 'afNUptVegS'
   description   ' 0.0'
end-output
output 'aLPAR1Veg'
   description   '  uLPAR0 * EXP(- aExtCoefOpen * aDepth1Veg)'
end-output
output 'aLPAR2Veg'
   description   '  aLPAR1Veg * EXP(- aExtCoef   * (aDepth2Veg - aDe'
end-output
output 'uhLVeg'
   description   ' hLRefVeg * uFunTmProdVeg'
end-output
output 'aLLimShoot'
   description   ' fEmergVeg + fFloatVeg * (1.0 - afCovEmergVeg) +'
end-output
output 'aMuTmLVeg'
   description   ' ufDay * bfShootVeg * aLLimShootVeg   * uFunTmProd'
end-output
output 'aPLimVeg'
   description   ' MAX(0.0, (1.0 - cPDVegMin / rPDVeg)   * cPDVegMax'
end-output
output 'aNLimVeg'
   description   ' MAX(0.0, (1.0 - cNDVegMin / rNDVeg)   * cNDVegMax'
end-output
output 'aNutLimVeg'
   description   ' MIN( aPLimVeg, aNLimVeg)'
end-output
output 'aMuVeg'
   description   ' aMuTmLVeg * aNutLimVeg'
end-output
output 'bkMortVeg'
   description   ' kMortVegSum'
end-output
output 'akDIncrVeg'
   description   ' aMuTmLVeg - kDRespVeg * uFunTmRespVeg   - bkMortV'
end-output
output 'tDEnvVeg'
   description   ' MAX(0.0, akDIncrVeg / (cDCarrVeg+NearZero)   * sD'
end-output
output 'tDEnvProdV'
   description   ' aMuVeg / cMuMaxVeg * tDEnvVeg'
end-output
output 'tDProdVeg'
   description   ' MAX(0.0, aMuVeg * sDVeg  - tDEnvProdVeg)'
end-output
output 'tDProdSubV'
   description   ' bfSubVeg * tDProdVeg'
end-output
output 'tDRespVeg'
   description   ' kDRespVeg * uFunTmRespVeg * sDVeg'
end-output
output 'tDEnvMortV'
   description   ' tDEnvVeg - tDEnvProdVeg'
end-output
output 'tDMortVeg'
   description   ' bkMortVeg * sDVeg + tDEnvMortVeg'
end-output
output 'tDMortVegW'
   description   ' fDetWMortVeg * (1.0 - bfRootVeg) * tDMortVeg'
end-output
output 'tDMortVegS'
   description   ' tDMortVeg - tDMortVegW'
end-output
output 'tDGrazVegB'
   description   ' cPrefVegBird * sDVeg / (hDVegBird + sDVeg)  * cBi'
end-output
output 'bkManVeg'
   description   ' - log(1.0 - fManVeg) / cLengMan'
end-output
output 'tDManVeg'
   description   ' bkManVeg * sDVeg'
end-output
output 'tPManVeg'
   description   ' rPDVeg * tDManVeg'
end-output
output 'tNManVeg'
   description   ' rNDVeg * tDManVeg'
end-output
output 'tDBedVeg'
   description   ' tDMigrVeg + tDProdVeg - tDRespVeg - tDMortVeg  -'
end-output
output 'tO2ProdVeg'
   description   ' molO2molC * cCPerDW * tDProdVeg'
end-output
output 'tO2RespVeg'
   description   ' molO2molC * cCPerDW * bfSubVeg * tDRespVeg   * aC'
end-output
output 'tO2RespVeS'
   description   ' molO2molC * cCPerDW * bfRootVeg * tDRespVeg   * a'
end-output
output 'tO2ProdVeS'
   description   ' MIN (tO2RespVegS, tO2ProdVeg)'
end-output
output 'tO2ProdVeW'
   description   ' MIN( tO2ProdVeg - tO2ProdVegS,   bfSubVeg * tO2Pr'
end-output
output 'tO2UptNO3V'
   description   ' O2PerNO3 * molO2molN * bfSubVeg * tNUptNO3VegW'
end-output
output 'tO2UptNO3S'
   description   ' O2PerNO3 * molO2molN * tNUptNO3VegS'
end-output
output 'tPExcrVeg'
   description   ' rPDVeg / (cPDVegMin + rPDVeg) * rPDVeg   * tDResp'
end-output
output 'tPExcrVegS'
   description   ' bfRootVeg * tPExcrVeg'
end-output
output 'tPExcrVegW'
   description   ' tPExcrVeg - tPExcrVegS'
end-output
output 'tPMortVeg'
   description   ' rPDVeg * tDMortVeg'
end-output
output 'tPMortVegP'
   description   ' fDissMortVeg * tPMortVeg'
end-output
output 'tPMortVegS'
   description   ' bfRootVeg * tPMortVegPO4'
end-output
output 'tPMortVegW'
   description   ' tPMortVegPO4 - tPMortVegPO4S'
end-output
output 'tPMortVegD'
   description   ' tPMortVeg - tPMortVegPO4'
end-output
output 'tPMortVetW'
   description   ' fDetWMortVeg * (1.0 - bfRootVeg) *   tPMortVegDet'
end-output
output 'tPMortVetS'
   description   ' tPMortVegDet - tPMortVegDetW'
end-output
output 'tPGrazVegB'
   description   ' rPDVeg * tDGrazVegBird'
end-output
output 'tPBedVeg'
   description   ' tPMigrVeg + tPUptVeg - tPExcrVeg - tPMortVeg  - t'
end-output
output 'tNExcrVeg'
   description   ' rNDVeg / (cNDVegMin + rNDVeg) * rNDVeg   * tDResp'
end-output
output 'tNExcrVegS'
   description   ' bfRootVeg * tNExcrVeg'
end-output
output 'tNExcrVegW'
   description   ' tNExcrVeg - tNExcrVegS'
end-output
output 'tNMortVeg'
   description   ' rNDVeg * tDMortVeg'
end-output
output 'tNMortVegN'
   description   ' fDissMortVeg * tNMortVeg'
end-output
output 'tNMortVegS'
   description   ' bfRootVeg * tNMortVegNH4'
end-output
output 'tNMortVegW'
   description   ' tNMortVegNH4 - tNMortVegNH4S'
end-output
output 'tNMortVegD'
   description   ' tNMortVeg - tNMortVegNH4'
end-output
output 'tNMortVetW'
   description   ' fDetWMortVeg * (1.0 - bfRootVeg) *   tNMortVegDet'
end-output
output 'tNMortVetS'
   description   ' tNMortVegDet - tNMortVegDetW'
end-output
output 'tNGrazVegB'
   description   ' rNDVeg * tDGrazVegBird'
end-output
output 'tNBedVeg'
   description   ' tNMigrVeg + tNUptVeg - tNExcrVeg - tNMortVeg  - t'
end-output
output 'tDAssVegBi'
   description   ' fDAssBird * tDGrazVegBird'
end-output
output 'tDEgesBird'
   description   ' tDGrazVegBird - tDAssVegBird'
end-output
output 'tPAssVegBi'
   description   ' fDAssBird * tPGrazVegBird'
end-output
output 'tPEgesBird'
   description   ' tPGrazVegBird - tPAssVegBird'
end-output
output 'tPEgesBir4'
   description   ' fDissEgesBird * tPEgesBird'
end-output
output 'tPEgesBirt'
   description   ' tPEgesBird - tPEgesBirdPO4'
end-output
output 'tNAssVegBi'
   description   ' fDAssBird * tNGrazVegBird'
end-output
output 'tNEgesBird'
   description   ' tNGrazVegBird - tNAssVegBird'
end-output
output 'tNEgesBir4'
   description   ' fDissEgesBird * tNEgesBird'
end-output
output 'tNEgesBirt'
   description   ' tNEgesBird - tNEgesBirdNH4'
end-output
output 'wDBedDetW'
   description   '(tDMortVegW  + tDEgesBird) / sDepthW'
end-output
output 'tDBedDetS'
   description   ' tDMortVegS'
end-output
output 'tDBedTotT'
   description   ' tDMigrVeg + tDProdVeg - tDRespVeg - tDManVeg - tD'
end-output
output 'wPBedPO4W'
   description   '(- tPUptVegW + tPExcrVegW + tPMortVegPO4W + tPEges'
end-output
output 'wPBedDetW'
   description   '(tPMortVegDetW + tPEgesBirdDet) / sDepthW'
end-output
output 'tPBedPO4S'
   description   ' - tPUptVegS + tPExcrVegS + tPMortVegPO4S'
end-output
output 'tPBedDetS'
   description   ' tPMortVegDetS'
end-output
output 'tPBedTotT'
   description   ' tPMigrVeg - tPManVeg - tPAssVegBird'
end-output
output 'wNBedNH4W'
   description   '(- tNUptNH4VegW + tNExcrVegW + tNMortVegNH4W + tNE'
end-output
output 'wNBedNO3W'
   description   '  - tNUptNO3VegW / sDepthW'
end-output
output 'wNBedDetW'
   description   '(tNMortVegDetW + tNEgesBirdDet) / sDepthW'
end-output
output 'tNBedNH4S'
   description   '  - tNUptNH4VegS + tNExcrVegS + tNMortVegNH4S'
end-output
output 'tNBedNO3S'
   description   '  - tNUptNO3VegS'
end-output
output 'tNBedDetS'
   description   '  tNMortVegDetS'
end-output
output 'tNBedTotT'
   description   ' tNMigrVeg - tNManVeg - tNAssVegBird'
end-output
output 'tO2BedW'
   description   ' tO2ProdVegW - tO2RespVegW + tO2UptNO3VegW'
end-output
output 'tO2BedS'
   description   ' tO2ProdVegS - tO2RespVegS + tO2UptNO3VegS'
end-output
output 'UseLoss'
   description   ' 0.0'
end-output
output 'uFunTmLoss'
   description   ' EXP(-0.5/cSigTmLoss**2 *((uTm-cTmOptLoss)**2 -(cT'
end-output
output 'rPDBlueW'
   description   ' sPBlueW /(sDBlueW+NearZero)'
end-output
output 'rNDBlueW'
   description   ' sNBlueW /(sDBlueW+NearZero)'
end-output
output 'rPDBlueS'
   description   ' sPBlueS /(sDBlueS+NearZero)'
end-output
output 'rNDBlueS'
   description   ' sNBlueS /(sDBlueS+NearZero)'
end-output
output 'uFunTmBlue'
   description   ' EXP(-0.5/cSigTmBlue**2 *((uTm-cTmOptBlue)**2 - (c'
end-output
output 'uFunTmProe'
   description   ' uFunTmBlue'
end-output
output 'uFunTmRese'
   description   ' uFunTmBlue'
end-output
output 'aVPUptMaxe'
   description   ' MAX(0.0,cVPUptMaxBlue * uFunTmProdBlue *(cPDBlueM'
end-output
output 'aVPUptBlue'
   description   ' sPO4W * aVPUptMaxCrBlue /(aVPUptMaxCrBlue  / cAff'
end-output
output 'wPUptBlue'
   description   ' aVPUptBlue * sDBlueW'
end-output
output 'aVNUptMaxe'
   description   ' MAX(0.0,cVNUptMaxBlue * uFunTmProdBlue * (cNDBlue'
end-output
output 'ahNUptBlue'
   description   ' aVNUptMaxCrBlue / cAffNUptBlue'
end-output
output 'aVNUptBlue'
   description   ' oNDissW * aVNUptMaxCrBlue /(ahNUptBlue  + oNDissW'
end-output
output 'wNUptBlue'
   description   ' aVNUptBlue * sDBlueW'
end-output
output 'afNH4UptBl'
   description   ' sNH4W * sNO3W /((ahNUptBlue +  sNH4W) *(ahNUptBlu'
end-output
output 'wNUptNH4Bl'
   description   ' afNH4UptBlue * wNUptBlue'
end-output
output 'wNUptNO3Bl'
   description   ' wNUptBlue - wNUptNH4Blue'
end-output
output 'uMuMaxTmBl'
   description   ' cMuMaxBlue * uFunTmProdBlue'
end-output
output 'aPLimBlue'
   description   ' MAX(0.0,(1.0 - cPDBlueMin / rPDBlueW)   * cPDBlue'
end-output
output 'aNLimBlue'
   description   ' MAX(0.0,(1.0 - cNDBlueMin / rNDBlueW)   * cNDBlue'
end-output
output 'aSiLimBlue'
   description   ' sSiO2W /(hSiAssBlue + sSiO2W)'
end-output
output 'aLLimBlue'
   description   '   UseSteeleBlue *(EXP(1.0) /(aExtCoef * sDepthW)'
end-output
output 'aMuTmLBlue'
   description   ' ufDay *(1.0 - afCovSurfVeg) * aLLimBlue  * uMuMax'
end-output
output 'aNutLimBlu'
   description   ' MIN(aPLimBlue,aNLimBlue,aSiLimBlue)'
end-output
output 'aMuBlue'
   description   '  aNutLimBlue * aMuTmLBlue'
end-output
output 'wDAssBlue'
   description   ' aMuBlue*sDBlueW'
end-output
output 'rChDBlue'
   description   ' cChDBlueMax -(cChDBlueMax - cChDBlueMin) *  aLLim'
end-output
output 'oChlaBlue'
   description   ' mgPerg * rChDBlue * sDBlueW'
end-output
output 'aExtChBlue'
   description   ' cExtSpBlue / rChDBlue'
end-output
output 'ukDRespTmB'
   description   ' kDRespBlue * uFunTmRespBlue'
end-output
output 'wDRespBlue'
   description   ' ukDRespTmBlue * sDBlueW'
end-output
output 'ukLossTmBl'
   description   ' UseLoss * kLossBlue * uFunTmLoss'
end-output
output 'wDLossBlue'
   description   ' ukLossTmBlue * sDBlueW'
end-output
output 'wDMortBlue'
   description   ' kMortBlueW * sDBlueW'
end-output
output 'uCorVSetBl'
   description   ' cVSetBlue * aFunTauSetOM * uFunTmSet'
end-output
output 'tDSetBlue'
   description   ' uCorVSetBlue * sDBlueW'
end-output
output 'tDResusBlu'
   description   ' sDBlueS /(aDPhytS+NearZero) * tDResusPhytTot'
end-output
output 'tDRespBlue'
   description   ' ukDRespTmBlue * sDBlueS'
end-output
output 'tDMortBlue'
   description   ' kMortBlueS * sDBlueS'
end-output
output 'ukDDecBlue'
   description   ' ukDRespTmBlue + ukLossTmBlue + kMortBlueW   +(uCo'
end-output
output 'wPExcrBlue'
   description   ' rPDBlueW /(cPDBlueMin + rPDBlueW) * rPDBlueW   *'
end-output
output 'wPLossBlue'
   description   ' rPDBlueW * wDLossBlue'
end-output
output 'wPMortBlue'
   description   ' kMortBlueW * sPBlueW'
end-output
output 'tPSetBlue'
   description   ' rPDBlueW * tDSetBlue'
end-output
output 'tPResusBlu'
   description   ' rPDBlueS * tDResusBlue'
end-output
output 'tPExcrBlue'
   description   ' rPDBlueS /(cPDBlueMin + rPDBlueS) * rPDBlueS   *'
end-output
output 'tPMortBlue'
   description   ' kMortBlueS * sPBlueS'
end-output
output 'wNExcrBlue'
   description   ' rNDBlueW /(cNDBlueMin + rNDBlueW) * rNDBlueW   *'
end-output
output 'wNLossBlue'
   description   ' rNDBlueW * wDLossBlue'
end-output
output 'wNMortBlue'
   description   ' kMortBlueW * sNBlueW'
end-output
output 'tNSetBlue'
   description   ' rNDBlueW * tDSetBlue'
end-output
output 'tNResusBlu'
   description   ' rNDBlueS * tDResusBlue'
end-output
output 'tNExcrBlue'
   description   ' rNDBlueS /(cNDBlueMin + rNDBlueS) * rNDBlueS   *'
end-output
output 'tNMortBlue'
   description   ' kMortBlueS * sNBlueS'
end-output
output 'wDPrimBlue'
   description   ' wDAssBlue - wDRespBlueW - wDLossBlue  - wDMortBlu'
end-output
output 'wPPrimBlue'
   description   ' wPUptBlue - wPExcrBlueW - wPLossBlue   - wPMortBl'
end-output
output 'wNPrimBlue'
   description   ' wNUptBlue - wNExcrBlueW - wNLossBlue  - wNMortBlu'
end-output
output 'tDPrimBlue'
   description   ' tDSetBlue - tDResusBlue - tDMortBlueS   - tDRespB'
end-output
output 'tPPrimBlue'
   description   ' tPSetBlue - tPResusBlue - tPMortBlueS   - tPExcrB'
end-output
output 'tNPrimBlue'
   description   ' tNSetBlue - tNResusBlue - tNMortBlueS   - tNExcrB'
end-output
output 'rPDGrenW'
   description   ' sPGrenW /(sDGrenW+NearZero)'
end-output
output 'rNDGrenW'
   description   ' sNGrenW /(sDGrenW+NearZero)'
end-output
output 'rPDGrenS'
   description   ' sPGrenS /(sDGrenS+NearZero)'
end-output
output 'rNDGrenS'
   description   ' sNGrenS /(sDGrenS+NearZero)'
end-output
output 'uFunTmGren'
   description   ' EXP(-0.5/cSigTmGren**2 *((uTm-cTmOptGren)**2 - (c'
end-output
output 'uFunTmPron'
   description   ' uFunTmGren'
end-output
output 'uFunTmResn'
   description   ' uFunTmGren'
end-output
output 'aVPUptMaxn'
   description   ' MAX(0.0,cVPUptMaxGren * uFunTmProdGren *(cPDGrenM'
end-output
output 'aVPUptGren'
   description   ' sPO4W * aVPUptMaxCrGren /(aVPUptMaxCrGren  / cAff'
end-output
output 'wPUptGren'
   description   ' aVPUptGren * sDGrenW'
end-output
output 'aVNUptMaxn'
   description   ' MAX(0.0,cVNUptMaxGren * uFunTmProdGren * (cNDGren'
end-output
output 'ahNUptGren'
   description   ' aVNUptMaxCrGren / cAffNUptGren'
end-output
output 'aVNUptGren'
   description   ' oNDissW * aVNUptMaxCrGren /(ahNUptGren  + oNDissW'
end-output
output 'wNUptGren'
   description   ' aVNUptGren * sDGrenW'
end-output
output 'afNH4UptGr'
   description   ' sNH4W * sNO3W /((ahNUptGren +  sNH4W) *(ahNUptGre'
end-output
output 'wNUptNH4Gr'
   description   ' afNH4UptGren * wNUptGren'
end-output
output 'wNUptNO3Gr'
   description   ' wNUptGren - wNUptNH4Gren'
end-output
output 'uMuMaxTmGr'
   description   ' cMuMaxGren * uFunTmProdGren'
end-output
output 'aPLimGren'
   description   ' MAX(0.0,(1.0 - cPDGrenMin / rPDGrenW)   * cPDGren'
end-output
output 'aNLimGren'
   description   ' MAX(0.0,(1.0 - cNDGrenMin / rNDGrenW)   * cNDGren'
end-output
output 'aSiLimGren'
   description   ' sSiO2W /(hSiAssGren + sSiO2W)'
end-output
output 'aLLimGren'
   description   '   UseSteeleGren *(EXP(1.0) /(aExtCoef * sDepthW)'
end-output
output 'aMuTmLGren'
   description   ' ufDay *(1.0 - afCovSurfVeg) * aLLimGren  * uMuMax'
end-output
output 'aNutLimGre'
   description   ' MIN(aPLimGren,aNLimGren,aSiLimGren)'
end-output
output 'aMuGren'
   description   '  aNutLimGren * aMuTmLGren'
end-output
output 'wDAssGren'
   description   ' aMuGren*sDGrenW'
end-output
output 'rChDGren'
   description   ' cChDGrenMax -(cChDGrenMax - cChDGrenMin) *  aLLim'
end-output
output 'oChlaGren'
   description   ' mgPerg * rChDGren * sDGrenW'
end-output
output 'aExtChGren'
   description   ' cExtSpGren / rChDGren'
end-output
output 'ukDRespTmG'
   description   ' kDRespGren * uFunTmRespGren'
end-output
output 'wDRespGren'
   description   ' ukDRespTmGren * sDGrenW'
end-output
output 'ukLossTmGr'
   description   ' UseLoss * kLossGren * uFunTmLoss'
end-output
output 'wDLossGren'
   description   ' ukLossTmGren * sDGrenW'
end-output
output 'wDMortGren'
   description   ' kMortGrenW * sDGrenW'
end-output
output 'uCorVSetGr'
   description   ' cVSetGren * aFunTauSetOM * uFunTmSet'
end-output
output 'tDSetGren'
   description   ' uCorVSetGren * sDGrenW'
end-output
output 'tDResusGre'
   description   ' sDGrenS /(aDPhytS+NearZero) * tDResusPhytTot'
end-output
output 'tDRespGren'
   description   ' ukDRespTmGren * sDGrenS'
end-output
output 'tDMortGren'
   description   ' kMortGrenS * sDGrenS'
end-output
output 'ukDDecGren'
   description   ' ukDRespTmGren + ukLossTmGren + kMortGrenW   +(uCo'
end-output
output 'wPExcrGren'
   description   ' rPDGrenW /(cPDGrenMin + rPDGrenW) * rPDGrenW   *'
end-output
output 'wPLossGren'
   description   ' rPDGrenW * wDLossGren'
end-output
output 'wPMortGren'
   description   ' kMortGrenW * sPGrenW'
end-output
output 'tPSetGren'
   description   ' rPDGrenW * tDSetGren'
end-output
output 'tPResusGre'
   description   ' rPDGrenS * tDResusGren'
end-output
output 'tPExcrGren'
   description   ' rPDGrenS /(cPDGrenMin + rPDGrenS) * rPDGrenS   *'
end-output
output 'tPMortGren'
   description   ' kMortGrenS * sPGrenS'
end-output
output 'wNExcrGren'
   description   ' rNDGrenW /(cNDGrenMin + rNDGrenW) * rNDGrenW   *'
end-output
output 'wNLossGren'
   description   ' rNDGrenW * wDLossGren'
end-output
output 'wNMortGren'
   description   ' kMortGrenW * sNGrenW'
end-output
output 'tNSetGren'
   description   ' rNDGrenW * tDSetGren'
end-output
output 'tNResusGre'
   description   ' rNDGrenS * tDResusGren'
end-output
output 'tNExcrGren'
   description   ' rNDGrenS /(cNDGrenMin + rNDGrenS) * rNDGrenS   *'
end-output
output 'tNMortGren'
   description   ' kMortGrenS * sNGrenS'
end-output
output 'wDPrimGren'
   description   ' wDAssGren - wDRespGrenW - wDLossGren  - wDMortGre'
end-output
output 'wPPrimGren'
   description   ' wPUptGren - wPExcrGrenW - wPLossGren   - wPMortGr'
end-output
output 'wNPrimGren'
   description   ' wNUptGren - wNExcrGrenW - wNLossGren  - wNMortGre'
end-output
output 'tDPrimGren'
   description   ' tDSetGren - tDResusGren - tDMortGrenS   - tDRespG'
end-output
output 'tPPrimGren'
   description   ' tPSetGren - tPResusGren - tPMortGrenS   - tPExcrG'
end-output
output 'tNPrimGren'
   description   ' tNSetGren - tNResusGren - tNMortGrenS   - tNExcrG'
end-output
output 'rPDDiatW'
   description   ' sPDiatW /(sDDiatW+NearZero)'
end-output
output 'rNDDiatW'
   description   ' sNDiatW /(sDDiatW+NearZero)'
end-output
output 'rPDDiatS'
   description   ' sPDiatS /(sDDiatS+NearZero)'
end-output
output 'rNDDiatS'
   description   ' sNDiatS /(sDDiatS+NearZero)'
end-output
output 'uFunTmDiat'
   description   ' EXP(-0.5/cSigTmDiat**2 *((uTm-cTmOptDiat)**2 - (c'
end-output
output 'uFunTmProt'
   description   ' uFunTmDiat'
end-output
output 'uFunTmRest'
   description   ' uFunTmDiat'
end-output
output 'aVPUptMaxt'
   description   ' MAX(0.0,cVPUptMaxDiat * uFunTmProdDiat *(cPDDiatM'
end-output
output 'aVPUptDiat'
   description   ' sPO4W * aVPUptMaxCrDiat /(aVPUptMaxCrDiat  / cAff'
end-output
output 'wPUptDiat'
   description   ' aVPUptDiat * sDDiatW'
end-output
output 'aVNUptMaxt'
   description   ' MAX(0.0,cVNUptMaxDiat * uFunTmProdDiat * (cNDDiat'
end-output
output 'ahNUptDiat'
   description   ' aVNUptMaxCrDiat / cAffNUptDiat'
end-output
output 'aVNUptDiat'
   description   ' oNDissW * aVNUptMaxCrDiat /(ahNUptDiat  + oNDissW'
end-output
output 'wNUptDiat'
   description   ' aVNUptDiat * sDDiatW'
end-output
output 'afNH4UptDi'
   description   ' sNH4W * sNO3W /((ahNUptDiat +  sNH4W) *(ahNUptDia'
end-output
output 'wNUptNH4Di'
   description   ' afNH4UptDiat * wNUptDiat'
end-output
output 'wNUptNO3Di'
   description   ' wNUptDiat - wNUptNH4Diat'
end-output
output 'uMuMaxTmDi'
   description   ' cMuMaxDiat * uFunTmProdDiat'
end-output
output 'aPLimDiat'
   description   ' MAX(0.0,(1.0 - cPDDiatMin / rPDDiatW)   * cPDDiat'
end-output
output 'aNLimDiat'
   description   ' MAX(0.0,(1.0 - cNDDiatMin / rNDDiatW)   * cNDDiat'
end-output
output 'aSiLimDiat'
   description   ' sSiO2W /(hSiAssDiat + sSiO2W)'
end-output
output 'aLLimDiat'
   description   '   UseSteeleDiat *(EXP(1.0) /(aExtCoef * sDepthW)'
end-output
output 'aMuTmLDiat'
   description   ' ufDay *(1.0 - afCovSurfVeg) * aLLimDiat  * uMuMax'
end-output
output 'aNutLimDia'
   description   ' MIN(aPLimDiat,aNLimDiat,aSiLimDiat)'
end-output
output 'aMuDiat'
   description   '  aNutLimDiat * aMuTmLDiat'
end-output
output 'wDAssDiat'
   description   ' aMuDiat*sDDiatW'
end-output
output 'rChDDiat'
   description   ' cChDDiatMax -(cChDDiatMax - cChDDiatMin) *  aLLim'
end-output
output 'oChlaDiat'
   description   ' mgPerg * rChDDiat * sDDiatW'
end-output
output 'aExtChDiat'
   description   ' cExtSpDiat / rChDDiat'
end-output
output 'ukDRespTmD'
   description   ' kDRespDiat * uFunTmRespDiat'
end-output
output 'wDRespDiat'
   description   ' ukDRespTmDiat * sDDiatW'
end-output
output 'ukLossTmDi'
   description   ' UseLoss * kLossDiat * uFunTmLoss'
end-output
output 'wDLossDiat'
   description   ' ukLossTmDiat * sDDiatW'
end-output
output 'wDMortDiat'
   description   ' kMortDiatW * sDDiatW'
end-output
output 'uCorVSetDi'
   description   ' cVSetDiat * aFunTauSetOM * uFunTmSet'
end-output
output 'tDSetDiat'
   description   ' uCorVSetDiat * sDDiatW'
end-output
output 'tDResusDia'
   description   ' sDDiatS /(aDPhytS+NearZero) * tDResusPhytTot'
end-output
output 'tDRespDiat'
   description   ' ukDRespTmDiat * sDDiatS'
end-output
output 'tDMortDiat'
   description   ' kMortDiatS * sDDiatS'
end-output
output 'ukDDecDiat'
   description   ' ukDRespTmDiat + ukLossTmDiat + kMortDiatW   +(uCo'
end-output
output 'wPExcrDiat'
   description   ' rPDDiatW /(cPDDiatMin + rPDDiatW) * rPDDiatW   *'
end-output
output 'wPLossDiat'
   description   ' rPDDiatW * wDLossDiat'
end-output
output 'wPMortDiat'
   description   ' kMortDiatW * sPDiatW'
end-output
output 'tPSetDiat'
   description   ' rPDDiatW * tDSetDiat'
end-output
output 'tPResusDia'
   description   ' rPDDiatS * tDResusDiat'
end-output
output 'tPExcrDiat'
   description   ' rPDDiatS /(cPDDiatMin + rPDDiatS) * rPDDiatS   *'
end-output
output 'tPMortDiat'
   description   ' kMortDiatS * sPDiatS'
end-output
output 'wNExcrDiat'
   description   ' rNDDiatW /(cNDDiatMin + rNDDiatW) * rNDDiatW   *'
end-output
output 'wNLossDiat'
   description   ' rNDDiatW * wDLossDiat'
end-output
output 'wNMortDiat'
   description   ' kMortDiatW * sNDiatW'
end-output
output 'tNSetDiat'
   description   ' rNDDiatW * tDSetDiat'
end-output
output 'tNResusDia'
   description   ' rNDDiatS * tDResusDiat'
end-output
output 'tNExcrDiat'
   description   ' rNDDiatS /(cNDDiatMin + rNDDiatS) * rNDDiatS   *'
end-output
output 'tNMortDiat'
   description   ' kMortDiatS * sNDiatS'
end-output
output 'wDPrimDiat'
   description   ' wDAssDiat - wDRespDiatW - wDLossDiat  - wDMortDia'
end-output
output 'wPPrimDiat'
   description   ' wPUptDiat - wPExcrDiatW - wPLossDiat   - wPMortDi'
end-output
output 'wNPrimDiat'
   description   ' wNUptDiat - wNExcrDiatW - wNLossDiat  - wNMortDia'
end-output
output 'tDPrimDiat'
   description   ' tDSetDiat - tDResusDiat - tDMortDiatS   - tDRespD'
end-output
output 'tPPrimDiat'
   description   ' tPSetDiat - tPResusDiat - tPMortDiatS   - tPExcrD'
end-output
output 'tNPrimDiat'
   description   ' tNSetDiat - tNResusDiat - tNMortDiatS   - tNExcrD'
end-output
output 'oChla'
   description   ' oChlaDiat + oChlaGren + oChlaBlue'
end-output
output 'wDAssPhyt'
   description   ' wDAssDiat + wDAssGren + wDAssBlue'
end-output
output 'wDRespPhyt'
   description   ' wDRespDiatW + wDRespGrenW + wDRespBlueW'
end-output
output 'wDMortPhyt'
   description   ' wDMortDiatW + wDMortGrenW + wDMortBlueW'
end-output
output 'tDSetPhyt'
   description   ' tDSetDiat + tDSetGren + tDSetBlue'
end-output
output 'wDLossPhyt'
   description   ' wDLossDiat + wDLossGren + wDLossBlue'
end-output
output 'wDPrimPhyt'
   description   ' wDPrimDiatW + wDPrimGrenW + wDPrimBlueW'
end-output
output 'wPUptPhyt'
   description   ' wPUptDiat + wPUptGren + wPUptBlue'
end-output
output 'wPExcrPhyt'
   description   ' wPExcrDiatW + wPExcrGrenW + wPExcrBlueW'
end-output
output 'wPMortPhyt'
   description   ' wPMortDiatW + wPMortGrenW + wPMortBlueW'
end-output
output 'tPSetPhyt'
   description   ' tPSetDiat + tPSetGren + tPSetBlue'
end-output
output 'tPResusPhy'
   description   ' tPResusDiat + tPResusGren + tPResusBlue'
end-output
output 'wPLossPhyt'
   description   ' wPLossDiat + wPLossGren + wPLossBlue'
end-output
output 'wPPrimPhyt'
   description   ' wPPrimDiatW + wPPrimGrenW  + wPPrimBlueW'
end-output
output 'wNUptPhyt'
   description   ' wNUptDiat + wNUptGren + wNUptBlue'
end-output
output 'wNUptNH4Ph'
   description   ' wNUptNH4Diat + wNUptNH4Gren + wNUptNH4Blue'
end-output
output 'wNUptNO3Ph'
   description   ' wNUptNO3Diat + wNUptNO3Gren + wNUptNO3Blue'
end-output
output 'wNExcrPhyt'
   description   ' wNExcrDiatW + wNExcrGrenW + wNExcrBlueW'
end-output
output 'wNMortPhyt'
   description   ' wNMortDiatW + wNMortGrenW + wNMortBlueW'
end-output
output 'tNSetPhyt'
   description   ' tNSetDiat + tNSetGren + tNSetBlue'
end-output
output 'tNResusPhy'
   description   ' tNResusDiat + tNResusGren + tNResusBlue'
end-output
output 'wNLossPhyt'
   description   ' wNLossDiat + wNLossGren + wNLossBlue'
end-output
output 'wNPrimPhyt'
   description   ' wNPrimDiatW + wNPrimGrenW  + wNPrimBlueW'
end-output
output 'tDRespPhyt'
   description   ' tDRespDiatS + tDRespGrenS + tDRespBlueS'
end-output
output 'tDMortPhyt'
   description   ' tDMortDiatS + tDMortGrenS + tDMortBlueS'
end-output
output 'tDPrimPhyt'
   description   ' tDPrimDiatS + tDPrimGrenS + tDPrimBlueS'
end-output
output 'tPExcrPhyt'
   description   ' tPExcrDiatS + tPExcrGrenS + tPExcrBlueS'
end-output
output 'tPMortPhyt'
   description   ' tPMortDiatS + tPMortGrenS + tPMortBlueS'
end-output
output 'tPPrimPhyt'
   description   ' tPPrimDiatS + tPPrimGrenS + tPPrimBlueS'
end-output
output 'tNExcrPhyt'
   description   ' tNExcrDiatS + tNExcrGrenS + tNExcrBlueS'
end-output
output 'tNMortPhyt'
   description   ' tNMortDiatS + tNMortGrenS + tNMortBlueS'
end-output
output 'tNPrimPhyt'
   description   ' tNPrimDiatS + tNPrimGrenS + tNPrimBlueS'
end-output
output 'wSiUptDiat'
   description   ' cSiDDiat * wDAssDiat'
end-output
output 'wSiExcrDia'
   description   ' cSiDDiat * wDRespDiatW'
end-output
output 'wSiLossDia'
   description   ' cSiDDiat * wDLossDiat'
end-output
output 'wSiMortDia'
   description   ' cSiDDiat * wDMortDiatW'
end-output
output 'tSiSetDiat'
   description   ' cSiDDiat * tDSetDiat'
end-output
output 'tSiResusDi'
   description   ' cSiDDiat * tDResusDiat'
end-output
output 'wSiPrimDia'
   description   ' wSiUptDiat - tSiSetDiat / sDepthW    - wSiExcrDia'
end-output
output 'rCyDBlue'
   description   ' cCyDBlueMax -(cCyDBlueMax - cCyDBlueMin) * aLLimB'
end-output
output 'oCyan'
   description   ' rCyDBlue * sDBlueW * mgPerg'
end-output
output 'fDDiat'
   description   ' sDDiatW /(sDDiatW + sDGrenW + sDBlueW   + NearZer'
end-output
output 'wDPrimDetW'
   description   ' wDMortPhytW + wDLossPhyt'
end-output
output 'tDPrimDetS'
   description   ' tDMortPhytS'
end-output
output 'tDPrimTotT'
   description   '(wDAssPhyt - wDRespPhytW) * sDepthW - tDRespPhytS'
end-output
output 'wO2ProdPhy'
   description   ' molO2molC * cCPerDW * wDAssPhyt'
end-output
output 'wO2RespPhy'
   description   ' molO2molC * cCPerDW * wDRespPhytW * aCorO2BOD'
end-output
output 'wO2UptNO3P'
   description   ' O2PerNO3 * molO2molN * wNUptNO3Phyt'
end-output
output 'wO2PrimW'
   description   ' wO2ProdPhyt - wO2RespPhytW + wO2UptNO3Phyt'
end-output
output 'tO2RespPhy'
   description   ' molO2molC * cCPerDW * tDRespPhytS * afOxySed'
end-output
output 'tO2PrimS'
   description   ' tO2RespPhytS'
end-output
output 'wPMortPhyW'
   description   ' fDissMortPhyt * wPMortPhytW'
end-output
output 'wPMortPhtW'
   description   ' wPMortPhytW - wPMortPhytPO4W'
end-output
output 'wPLossPhy4'
   description   ' fDissLoss * wPLossPhyt'
end-output
output 'wPLossPhet'
   description   ' wPLossPhyt - wPLossPhytPO4'
end-output
output 'wPPrimPO4W'
   description   ' - wPUptPhyt + wPExcrPhytW   + wPLossPhytPO4 + wPM'
end-output
output 'wPPrimDetW'
   description   ' wPLossPhytDet + wPMortPhytDetW'
end-output
output 'tPMortPhyS'
   description   ' fDissMortPhyt * tPMortPhytS'
end-output
output 'tPMortPhtS'
   description   ' tPMortPhytS - tPMortPhytPO4S'
end-output
output 'tPPrimDetS'
   description   ' tPMortPhytDetS'
end-output
output 'tPPrimPO4S'
   description   ' tPExcrPhytS + tPMortPhytPO4S'
end-output
output 'tPPrimTotT'
   description   ' 0.0'
end-output
output 'wNMortPhyW'
   description   ' fDissMortPhyt * wNMortPhytW'
end-output
output 'wNMortPhtW'
   description   ' wNMortPhytW - wNMortPhytNH4W'
end-output
output 'wNLossPhy4'
   description   ' fDissLoss * wNLossPhyt'
end-output
output 'wNLossPhet'
   description   ' wNLossPhyt - wNLossPhytNH4'
end-output
output 'wNPrimNH4W'
   description   ' - wNUptNH4Phyt + wNExcrPhytW + wNLossPhytNH4   +'
end-output
output 'wNPrimNO3W'
   description   ' - wNUptNO3Phyt'
end-output
output 'wNPrimDetW'
   description   ' wNLossPhytDet + wNMortPhytDetW'
end-output
output 'tNMortPhyS'
   description   ' fDissMortPhyt * tNMortPhytS'
end-output
output 'tNMortPhtS'
   description   ' tNMortPhytS - tNMortPhytNH4S'
end-output
output 'tNPrimNH4S'
   description   ' tNExcrPhytS + tNMortPhytNH4S'
end-output
output 'tNPrimNO3S'
   description   ' 0.0'
end-output
output 'tNPrimDetS'
   description   ' tNMortPhytDetS'
end-output
output 'tNPrimTotT'
   description   ' 0.0'
end-output
output 'tSiExcrDia'
   description   ' cSiDDiat * tDRespDiatS'
end-output
output 'tSiMortDia'
   description   ' cSiDDiat * tDMortDiatS'
end-output
output 'wSiPrimSiO'
   description   ' wSiExcrDiatW - wSiUptDiat + tSiExcrDiatS / sDepth'
end-output
output 'wSiPrimDet'
   description   ' wSiMortDiatW + wSiLossDiat'
end-output
output 'tSiPrimDia'
   description   ' tSiSetDiat - tSiResusDiat   - tSiExcrDiatS - tSiM'
end-output
output 'tSiPrimDet'
   description   ' tSiMortDiatS'
end-output
output 'tSiPrimTot'
   description   ' 0.0'
end-output
output 'aPACoef'
   description   ' cPACoefMin  +(cPACoefMax - cPACoefMin) * hPACoef'
end-output
output 'bSecchiMax'
   description   ' sDepthW + cSecchiPlus'
end-output
output 'aSecchi'
   description   ' MIN(bSecchiMax,aPACoef / aExtCoefOpen)'
end-output
output 'aDepthEuph'
   description   ' cEuph * aSecchi'
end-output
output 'aRelDepthE'
   description   ' aDepthEuph / sDepthW'
end-output
output 'aChlaH'
   description   ' oChla * sDepthW'
end-output
output 'aCovPhytW'
   description   ' cCovSpPhyt *(oDPhytW * sDepthW)'
end-output
output 'rExtChPhyt'
   description   ' aExtPhyt /(oChla / mgPerg + NearZero)'
end-output
output 'uFunTmZoo'
   description   ' EXP(-0.5/cSigTmZoo**2 *((uTm-cTmOptZoo)**2 -(cTmR'
end-output
output 'rPDZoo'
   description   ' sPZoo /(sDZoo+NearZero)'
end-output
output 'rNDZoo'
   description   ' sNZoo/(sDZoo+NearZero)'
end-output
output 'oDFoodZoo'
   description   ' cPrefDiat * sDDiatW + cPrefGren * sDGrenW   + cPr'
end-output
output 'aFilt'
   description   ' cFiltMax * uFunTmZoo * hFilt /(hFilt + oDOMW)'
end-output
output 'ukDAssTmZo'
   description   ' fDAssZoo * cFiltMax * uFunTmZoo * hFilt'
end-output
output 'aDSatZoo'
   description   ' oDFoodZoo /(hFilt + oDOMW)'
end-output
output 'ukDRespTmZ'
   description   ' kDRespZoo * uFunTmZoo'
end-output
output 'ukDIncrZoo'
   description   ' ukDAssTmZoo - ukDRespTmZoo - kMortZoo'
end-output
output 'wDEnvZoo'
   description   ' MAX(0.0,ukDIncrZoo / cDCarrZoo * sDZoo**2)'
end-output
output 'wDAssZoo'
   description   ' aDSatZoo *(ukDAssTmZoo * sDZoo - wDEnvZoo)'
end-output
output 'wDConsZoo'
   description   ' wDAssZoo / fDAssZoo'
end-output
output 'wDConsDetZ'
   description   ' cPrefDet*sDDetW / oDFoodZoo * wDConsZoo'
end-output
output 'wDConsDiat'
   description   ' cPrefDiat*sDDiatW / oDFoodZoo * wDConsZoo'
end-output
output 'wDConsGren'
   description   ' cPrefGren*sDGrenW / oDFoodZoo * wDConsZoo'
end-output
output 'wDConsBlue'
   description   ' cPrefBlue*sDBlueW / oDFoodZoo * wDConsZoo'
end-output
output 'wDConsPhyt'
   description   ' wDConsDiatZoo + wDConsGrenZoo + wDConsBlueZoo'
end-output
output 'wDEgesZoo'
   description   ' wDConsZoo - wDAssZoo'
end-output
output 'aCorDRespZ'
   description   ' MAX(cPDZooRef / rPDZoo,cNDZooRef / rNDZoo)'
end-output
output 'wDRespZoo'
   description   ' aCorDRespZoo * ukDRespTmZoo * sDZoo'
end-output
output 'wDMortZoo'
   description   ' kMortZoo * sDZoo +(1.0 - aDSatZoo) * wDEnvZoo'
end-output
output 'oPFoodZoo'
   description   ' cPrefDiat*sPDiatW + cPrefGren*sPGrenW + cPrefBlue'
end-output
output 'rPDFoodZoo'
   description   ' oPFoodZoo /(oDFoodZoo+NearZero)'
end-output
output 'wPConsDiat'
   description   ' rPDDiatW * wDConsDiatZoo'
end-output
output 'wPConsGren'
   description   ' rPDGrenW * wDConsGrenZoo'
end-output
output 'wPConsBlue'
   description   ' rPDBlueW * wDConsBlueZoo'
end-output
output 'wPConsPhyt'
   description   ' wPConsDiatZoo + wPConsGrenZoo + wPConsBlueZoo'
end-output
output 'wPConsDetZ'
   description   ' rPDDetW * wDConsDetZoo'
end-output
output 'wPConsZoo'
   description   ' wPConsPhytZoo + wPConsDetZoo'
end-output
output 'afPAssZoo'
   description   ' MIN(1.0,cPDZooRef / rPDFoodZoo * fDAssZoo)'
end-output
output 'wPAssZoo'
   description   ' afPAssZoo * wPConsZoo'
end-output
output 'wPEgesZoo'
   description   ' wPConsZoo - wPAssZoo'
end-output
output 'wPEgesZooP'
   description   ' fDissEgesZoo*wPEgesZoo'
end-output
output 'wPEgesZooD'
   description   ' wPEgesZoo - wPEgesZooPO4'
end-output
output 'akPExcrZoo'
   description   ' rPDZoo / cPDZooRef * kDRespZoo'
end-output
output 'wPExcrZoo'
   description   ' akPExcrZoo*sPZoo'
end-output
output 'wPMortZoo'
   description   ' rPDZoo * wDMortZoo'
end-output
output 'wPMortZooP'
   description   ' fDissMortZoo * wPMortZoo'
end-output
output 'wPMortZooD'
   description   ' wPMortZoo - wPMortZooPO4'
end-output
output 'oNFoodZoo'
   description   ' cPrefDiat*sNDiatW + cPrefGren*sNGrenW + cPrefBlue'
end-output
output 'rNDFoodZoo'
   description   ' oNFoodZoo /(oDFoodZoo+NearZero)'
end-output
output 'wNConsDiat'
   description   ' rNDDiatW*wDConsDiatZoo'
end-output
output 'wNConsGren'
   description   ' rNDGrenW*wDConsGrenZoo'
end-output
output 'wNConsBlue'
   description   ' rNDBlueW*wDConsBlueZoo'
end-output
output 'wNConsPhyt'
   description   ' wNConsDiatZoo + wNConsGrenZoo + wNConsBlueZoo'
end-output
output 'wNConsDetZ'
   description   ' rNDDetW*wDConsDetZoo'
end-output
output 'wNConsZoo'
   description   ' wNConsPhytZoo + wNConsDetZoo'
end-output
output 'afNAssZoo'
   description   ' MIN(1.0,cNDZooRef / rNDFoodZoo * fDAssZoo)'
end-output
output 'wNAssZoo'
   description   ' afNAssZoo*wNConsZoo'
end-output
output 'wNEgesZoo'
   description   ' wNConsZoo - wNAssZoo'
end-output
output 'wNEgesZooN'
   description   ' fDissEgesZoo*wNEgesZoo'
end-output
output 'wNEgesZooD'
   description   ' wNEgesZoo - wNEgesZooNH4'
end-output
output 'kNExcrZoo'
   description   ' rNDZoo / cNDZooRef * kDRespZoo'
end-output
output 'wNExcrZoo'
   description   ' kNExcrZoo*sNZoo'
end-output
output 'wNMortZoo'
   description   ' rNDZoo*wDMortZoo'
end-output
output 'wNMortZooN'
   description   ' fDissMortZoo*wNMortZoo'
end-output
output 'wNMortZooD'
   description   ' wNMortZoo - wNMortZooNH4'
end-output
output 'wSiConsDia'
   description   ' cSiDDiat * wDConsDiatZoo'
end-output
output 'uFunTmBent'
   description   ' EXP(-0.5/cSigTmBent**2 *((uTm-cTmOptBent)**2 - (c'
end-output
output 'aDFoodBent'
   description   ' sDDetS + aDPhytS'
end-output
output 'rPDBent'
   description   ' sPBent /(sDBent+NearZero)'
end-output
output 'rNDBent'
   description   ' sNBent /(sDBent+NearZero)'
end-output
output 'tDMigrBent'
   description   ' kMigrBent *(cDBentIn - sDBent)'
end-output
output 'aDSatBent'
   description   ' aDFoodBent /(hDFoodBent + aDFoodBent)'
end-output
output 'ukDIncrBen'
   description   '(kDAssBent - kDRespBent) * uFunTmBent - kMortBent'
end-output
output 'tDEnvBent'
   description   ' MAX(0.0,ukDIncrBent / cDCarrBent * sDBent**2)'
end-output
output 'tDAssBent'
   description   ' aDSatBent *(kDAssBent * uFunTmBent * sDBent - tDE'
end-output
output 'aDAssBentS'
   description   ' tDAssBent / sDBent'
end-output
output 'tDConsBent'
   description   ' tDAssBent / fDAssBent'
end-output
output 'tDConsDetB'
   description   ' sDDetS / aDFoodBent * tDConsBent'
end-output
output 'tDConsDiat'
   description   ' sDDiatS / aDFoodBent * tDConsBent'
end-output
output 'tDConsGren'
   description   ' sDGrenS / aDFoodBent * tDConsBent'
end-output
output 'tDConsBlue'
   description   ' sDBlueS / aDFoodBent * tDConsBent'
end-output
output 'tDConsPhyt'
   description   ' tDConsDiatBent + tDConsGrenBent + tDConsBlueBent'
end-output
output 'tDEgesBent'
   description   ' tDConsBent - tDAssBent'
end-output
output 'tDRespBent'
   description   '(cPDBentRef / rPDBent) * kDRespBent * uFunTmBent *'
end-output
output 'tDMortBent'
   description   ' kMortBent*sDBent +(1.0 - aDSatBent) * tDEnvBent'
end-output
output 'aPFoodBent'
   description   ' sPDetS + aPPhytS'
end-output
output 'rPDFoodBen'
   description   ' aPFoodBent /(aDFoodBent+NearZero)'
end-output
output 'tPConsDetB'
   description   ' rPDDetS * tDConsDetBent'
end-output
output 'tPConsDiat'
   description   ' rPDDiatS * tDConsDiatBent'
end-output
output 'tPConsGren'
   description   ' rPDGrenS * tDConsGrenBent'
end-output
output 'tPConsBlue'
   description   ' rPDBlueS * tDConsBlueBent'
end-output
output 'tPConsPhyt'
   description   ' tPConsDiatBent + tPConsGrenBent + tPConsBlueBent'
end-output
output 'tPConsBent'
   description   ' tPConsDetBent + tPConsPhytBent'
end-output
output 'afPAssBent'
   description   ' MIN(1.0,cPDBentRef / rPDFoodBent * fDAssBent)'
end-output
output 'tPAssBent'
   description   ' afPAssBent * tPConsBent'
end-output
output 'tPEgesBent'
   description   ' tPConsBent - tPAssBent'
end-output
output 'tPEgesBen4'
   description   ' fDissEgesBent * tPEgesBent'
end-output
output 'tPEgesBeet'
   description   '(1.0 - fDissEgesBent) * tPEgesBent'
end-output
output 'tPExcrBent'
   description   '(rPDBent / cPDBentRef) * kDRespBent * uFunTmBent *'
end-output
output 'tPMortBent'
   description   ' rPDBent * tDMortBent'
end-output
output 'tPMortBen4'
   description   ' fDissMortBent * tPMortBent'
end-output
output 'tPMortBeet'
   description   '(1.0-fDissMortBent)*tPMortBent'
end-output
output 'tPMigrBent'
   description   ' kMigrBent *(cPDBentRef*cDBentIn - sPBent)'
end-output
output 'aNFoodBent'
   description   ' sNDetS + aNPhytS'
end-output
output 'rNDFoodBen'
   description   ' aNFoodBent /(aDFoodBent+NearZero)'
end-output
output 'tNMigrBent'
   description   ' kMigrBent *(cNDBentRef*cDBentIn - sNBent)'
end-output
output 'tNConsDetB'
   description   ' rNDDetS * tDConsDetBent'
end-output
output 'tNConsDiat'
   description   ' rNDDiatS * tDConsDiatBent'
end-output
output 'tNConsGren'
   description   ' rNDGrenS * tDConsGrenBent'
end-output
output 'tNConsBlue'
   description   ' rNDBlueS * tDConsBlueBent'
end-output
output 'tNConsPhyt'
   description   ' tNConsDiatBent + tNConsGrenBent + tNConsBlueBent'
end-output
output 'tNConsBent'
   description   ' tNConsDetBent + tNConsPhytBent'
end-output
output 'afNAssBent'
   description   ' MIN(1.0,cNDBentRef / rNDFoodBent * fDAssBent)'
end-output
output 'tNAssBent'
   description   ' afNAssBent * tNConsBent'
end-output
output 'tNEgesBent'
   description   ' tNConsBent - tNAssBent'
end-output
output 'tNEgesBen4'
   description   ' fDissEgesBent * tNEgesBent'
end-output
output 'tNEgesBeet'
   description   '(1.0 - fDissEgesBent) * tNEgesBent'
end-output
output 'tNExcrBent'
   description   '(rNDBent / cNDBentRef) * kDRespBent * uFunTmBent *'
end-output
output 'tNMortBent'
   description   ' rNDBent * tDMortBent'
end-output
output 'tNMortBen4'
   description   ' fDissMortBent*tNMortBent'
end-output
output 'tNMortBeet'
   description   '(1.0-fDissMortBent)*tNMortBent'
end-output
output 'tSiConsDia'
   description   ' cSiDDiat * tDConsDiatBent'
end-output
output 'aDFish'
   description   ' sDFiJv + sDFiAd'
end-output
output 'aPFish'
   description   ' sPFiJv + sPFiAd'
end-output
output 'aNFish'
   description   ' sNFiJv + sNFiAd'
end-output
output 'rPDFiJv'
   description   ' sPFiJv /(sDFiJv+NearZero)'
end-output
output 'rPDFiAd'
   description   ' sPFiAd /(sDFiAd+NearZero)'
end-output
output 'rNDFiJv'
   description   ' sNFiJv /(sDFiJv+NearZero)'
end-output
output 'rNDFiAd'
   description   ' sNFiAd /(sDFiAd+NearZero)'
end-output
output 'tDReprFish'
   description   ' fReprFish * sDFiAd'
end-output
output 'tDAgeFish'
   description   ' fAgeFish * sDFiJv'
end-output
output 'aFunVegFis'
   description   ' MAX(0.0,1.0 - cRelVegFish * aCovVeg)'
end-output
output 'aDSatFiJv'
   description   '(sDZoo * sDepthW) **2 /(hDZooFiJv **2 + (sDZoo * s'
end-output
output 'ukDIncrFiJ'
   description   '(kDAssFiJv - kDRespFiJv) * uFunTmFish - kMortFiJv'
end-output
output 'tDEnvFiJv'
   description   ' MAX(0.0,ukDIncrFiJv /(cDCarrFish - sDFiAd) * sDFi'
end-output
output 'tDAssFiJv'
   description   ' aDSatFiJv *(kDAssFiJv * uFunTmFish * sDFiJv  - tD'
end-output
output 'tDConsFiJv'
   description   ' tDAssFiJv / fDAssFiJv'
end-output
output 'tDEgesFiJv'
   description   ' tDConsFiJv - tDAssFiJv'
end-output
output 'tDRespFiJv'
   description   '(cPDFishRef / rPDFiJv) * kDRespFiJv * uFunTmFish *'
end-output
output 'tDMortFiJv'
   description   ' kMortFiJv * sDFiJv +(1.0 - aDSatFiJv) * tDEnvFiJv'
end-output
output 'tDMigrFiJv'
   description   ' kMigrFish *(cDFiJvIn - sDFiJv)'
end-output
output 'aDSatFiAd'
   description   '(aFunVegFish * sDBent) **2 /(hDBentFiAd **2 + (aFu'
end-output
output 'ukDIncrFiA'
   description   '(kDAssFiAd - kDRespFiAd) * uFunTmFish - kMortFiAd'
end-output
output 'tDEnvFiAd'
   description   ' MAX(0.0,ukDIncrFiAd /(cDCarrFish - sDFiJv) * sDFi'
end-output
output 'tDAssFiAd'
   description   ' aDSatFiAd *(kDAssFiAd * uFunTmFish * sDFiAd - tDE'
end-output
output 'tDConsFiAd'
   description   ' tDAssFiAd / fDAssFiAd'
end-output
output 'tDEgesFiAd'
   description   ' tDConsFiAd - tDAssFiAd'
end-output
output 'tDRespFiAd'
   description   '(cPDFishRef / rPDFiAd) * kDRespFiAd * uFunTmFish *'
end-output
output 'tDMortFiAd'
   description   ' kMortFiAd * sDFiAd +(1.0 - aDSatFiAd) * tDEnvFiAd'
end-output
output 'ukHarvFish'
   description   '  kHarvFishWin'
end-output
output 'tDHarvFish'
   description   ' ukHarvFish * sDFiAd'
end-output
output 'tDMigrFiAd'
   description   ' kMigrFish *(cDFiAdIn - sDFiAd)'
end-output
output 'tDMortFish'
   description   ' tDMortFiJv + tDMortFiAd'
end-output
output 'tDMortFist'
   description   ' fDBone * tDMortFish'
end-output
output 'tDMortFiet'
   description   ' tDMortFish - tDMortFishBot'
end-output
output 'tPReprFish'
   description   ' rPDFiAd * tDReprFish'
end-output
output 'tPAgeFish'
   description   ' rPDFiJv * tDAgeFish'
end-output
output 'tPMigrFiJv'
   description   ' kMigrFish *(cPDFishRef * cDFiJvIn - sPFiJv)'
end-output
output 'tPConsFiJv'
   description   ' rPDZoo * tDConsFiJv'
end-output
output 'afPAssFiJv'
   description   ' MIN(1.0,cPDFishRef / rPDZoo * fDAssFiJv)'
end-output
output 'tPAssFiJv'
   description   ' afPAssFiJv * tPConsFiJv'
end-output
output 'tPEgesFiJv'
   description   ' tPConsFiJv - tPAssFiJv'
end-output
output 'tPExcrFiJv'
   description   '(rPDFiJv / cPDFishRef) * kDRespFiJv * uFunTmFish *'
end-output
output 'tPMortFiJv'
   description   ' rPDFiJv * tDMortFiJv'
end-output
output 'tPMigrFiAd'
   description   ' kMigrFish *(cPDFishRef * cDFiAdIn - sPFiAd)'
end-output
output 'tPConsFiAd'
   description   ' rPDBent * tDConsFiAd'
end-output
output 'afPAssFiAd'
   description   ' MIN(1.0,cPDFishRef / rPDBent * fDAssFiAd)'
end-output
output 'tPAssFiAd'
   description   ' afPAssFiAd * tPConsFiAd'
end-output
output 'tPEgesFiAd'
   description   ' tPConsFiAd - tPAssFiAd'
end-output
output 'tPExcrFiAd'
   description   '(rPDFiAd / cPDFishRef) * kDRespFiAd * uFunTmFish *'
end-output
output 'tPMortFiAd'
   description   ' rPDFiAd * tDMortFiAd'
end-output
output 'tPHarvFish'
   description   ' rPDFiAd * tDHarvFish'
end-output
output 'tPMortFish'
   description   ' tPMortFiJv + tPMortFiAd'
end-output
output 'tPMortFist'
   description   ' fPBone * tPMortFish'
end-output
output 'tPMortFis4'
   description   ' fDissMortFish *(tPMortFish - tPMortFishBot)'
end-output
output 'tPMortFiet'
   description   ' tPMortFish - tPMortFishBot - tPMortFishPO4'
end-output
output 'tPEgesFish'
   description   ' tPEgesFiJv + tPEgesFiAd'
end-output
output 'tPEgesFis4'
   description   ' fDissEgesFish * tPEgesFish'
end-output
output 'tPEgesFist'
   description   ' tPEgesFish - tPEgesFishPO4'
end-output
output 'tNReprFish'
   description   ' rNDFiAd * tDReprFish'
end-output
output 'tNAgeFish'
   description   ' rNDFiJv * tDAgeFish'
end-output
output 'tNMigrFiJv'
   description   ' kMigrFish *(cNDFishRef * cDFiJvIn - sNFiJv)'
end-output
output 'tNConsFiJv'
   description   ' rNDZoo * tDConsFiJv'
end-output
output 'afNAssFiJv'
   description   ' MIN(1.0,cNDFishRef / rNDZoo * fDAssFiJv)'
end-output
output 'tNAssFiJv'
   description   ' afNAssFiJv * tNConsFiJv'
end-output
output 'tNEgesFiJv'
   description   ' tNConsFiJv - tNAssFiJv'
end-output
output 'tNExcrFiJv'
   description   '(rNDFiJv / cNDFishRef) * kDRespFiJv * uFunTmFish *'
end-output
output 'tNMortFiJv'
   description   ' rNDFiJv * tDMortFiJv'
end-output
output 'tNMigrFiAd'
   description   ' kMigrFish *(cNDFishRef * cDFiAdIn - sNFiAd)'
end-output
output 'tNConsFiAd'
   description   ' rNDBent * tDConsFiAd'
end-output
output 'afNAssFiAd'
   description   ' MIN(1.0,cNDFishRef / rNDBent * fDAssFiAd)'
end-output
output 'tNAssFiAd'
   description   ' afNAssFiAd * tNConsFiAd'
end-output
output 'tNEgesFiAd'
   description   ' tNConsFiAd - tNAssFiAd'
end-output
output 'tNExcrFiAd'
   description   '(rNDFiAd / cNDFishRef) * kDRespFiAd * uFunTmFish *'
end-output
output 'tNMortFiAd'
   description   ' rNDFiAd * tDMortFiAd'
end-output
output 'tNHarvFish'
   description   ' rNDFiAd * tDHarvFish'
end-output
output 'tNMortFish'
   description   ' tNMortFiJv + tNMortFiAd'
end-output
output 'tNMortFist'
   description   ' fDBone * tNMortFish'
end-output
output 'tNMortFis4'
   description   ' fDissMortFish *(tNMortFish - tNMortFishBot)'
end-output
output 'tNMortFiet'
   description   ' tNMortFish - tNMortFishBot - tNMortFishNH4'
end-output
output 'tNEgesFish'
   description   ' tNEgesFiJv + tNEgesFiAd'
end-output
output 'tNEgesFis4'
   description   ' fDissEgesFish * tNEgesFish'
end-output
output 'tNEgesFist'
   description   ' tNEgesFish - tNEgesFishNH4'
end-output
output 'uFunTmPisc'
   description   ' EXP(-0.5 / cSigTmPisc**2 *((uTm - cTmOptPisc)**2'
end-output
output 'tDMigrPisc'
   description   ' kMigrPisc *(cDPiscIn - sDPisc)'
end-output
output 'aDCarrPisc'
   description   ' MAX(cDCarrPiscMin,MIN(cDCarrPiscMax,cDCarrPiscBar'
end-output
output 'aFunVegPis'
   description   ' aDSubVeg /(hDVegPisc + aDSubVeg + 0.0000000000000'
end-output
output 'aDSatPisc'
   description   ' aDFish**2 /(hDFishPisc**2 + aDFish**2)'
end-output
output 'akDIncrPis'
   description   '(kDAssPisc * aFunVegPisc - kDRespPisc) * uFunTmPis'
end-output
output 'tDEnvPisc'
   description   ' MAX(0.0,akDIncrPisc / aDCarrPisc * sDPisc**2)'
end-output
output 'tDAssPisc'
   description   ' aDSatPisc *(kDAssPisc * aFunVegPisc * uFunTmPisc'
end-output
output 'tDConsPisc'
   description   ' tDAssPisc / fDAssPisc'
end-output
output 'tDEgesPisc'
   description   ' tDConsPisc - tDAssPisc'
end-output
output 'tDConsFiJc'
   description   ' sDFiJv / aDFish * tDConsPisc'
end-output
output 'tDConsFiAc'
   description   ' tDConsPisc - tDConsFiJvPisc'
end-output
output 'tDRespPisc'
   description   ' kDRespPisc * uFunTmPisc * sDPisc'
end-output
output 'tDMortPisc'
   description   ' kMortPisc * sDPisc +(1.0 - aDSatPisc) * tDEnvPisc'
end-output
output 'tDMortPist'
   description   ' fDBone * tDMortPisc'
end-output
output 'tDMortPiet'
   description   ' tDMortPisc - tDMortPiscBot'
end-output
output 'ukHarvPisc'
   description   '  kHarvPiscWin'
end-output
output 'tDHarvPisc'
   description   ' ukHarvPisc * sDPisc'
end-output
output 'aPPisc'
   description   ' cPDPisc * sDPisc'
end-output
output 'tPConsFiJc'
   description   ' rPDFiJv * tDConsFiJvPisc'
end-output
output 'tPConsFiAc'
   description   ' rPDFiAd * tDConsFiAdPisc'
end-output
output 'tPConsPisc'
   description   ' tPConsFiJvPisc + tPConsFiAdPisc'
end-output
output 'rPDFoodPis'
   description   ' tPConsPisc / tDConsPisc'
end-output
output 'afPAssPisc'
   description   ' MIN(1.0,cPDPisc / rPDFoodPisc * fDAssPisc)'
end-output
output 'tPAssPisc'
   description   ' afPAssPisc * tPConsPisc'
end-output
output 'tPEgesPisc'
   description   ' tPConsPisc - tPAssPisc'
end-output
output 'tPEgesPis4'
   description   ' fDissEgesPisc * tPEgesPisc'
end-output
output 'tPEgesPist'
   description   ' tPEgesPisc - tPEgesPiscPO4'
end-output
output 'tPExcrPisc'
   description   ' cPDPisc * tDRespPisc'
end-output
output 'tPMortPisc'
   description   ' cPDPisc * tDMortPisc'
end-output
output 'tPMortPist'
   description   ' fPBone * tPMortPisc'
end-output
output 'tPMortPis4'
   description   ' fDissMortPisc *(tPMortPisc - tPMortPiscBot)'
end-output
output 'tPMortPiet'
   description   ' tPMortPisc - tPMortPiscBot - tPMortPiscPO4'
end-output
output 'tPMigrPisc'
   description   ' kMigrPisc *(cPDPisc * cDPiscIn - aPPisc)'
end-output
output 'tPHarvPisc'
   description   ' cPDPisc * tDHarvPisc'
end-output
output 'aNPisc'
   description   ' cNDPisc * sDPisc'
end-output
output 'tNConsFiJc'
   description   ' rNDFiJv * tDConsFiJvPisc'
end-output
output 'tNConsFiAc'
   description   ' rNDFiAd * tDConsFiAdPisc'
end-output
output 'tNConsPisc'
   description   ' tNConsFiJvPisc + tNConsFiAdPisc'
end-output
output 'rNDFoodPis'
   description   ' tNConsPisc / tDConsPisc'
end-output
output 'afNAssPisc'
   description   ' MIN(1.0,cNDPisc / rNDFoodPisc * fDAssPisc)'
end-output
output 'tNAssPisc'
   description   ' afNAssPisc * tNConsPisc'
end-output
output 'tNEgesPisc'
   description   ' tNConsPisc - tNAssPisc'
end-output
output 'tNEgesPis4'
   description   ' fDissEgesPisc * tNEgesPisc'
end-output
output 'tNEgesPist'
   description   ' tNEgesPisc - tNEgesPiscNH4'
end-output
output 'tNExcrPisc'
   description   ' cNDPisc * tDRespPisc'
end-output
output 'tNMortPisc'
   description   ' cNDPisc * tDMortPisc'
end-output
output 'tNMortPist'
   description   ' fDBone * tNMortPisc'
end-output
output 'tNMortPis4'
   description   ' fDissMortPisc *(tNMortPisc - tNMortPiscBot)'
end-output
output 'tNMortPiet'
   description   ' tNMortPisc - tNMortPiscBot - tNMortPiscNH4'
end-output
output 'tNMigrPisc'
   description   ' kMigrPisc *(cNDPisc * cDPiscIn - aNPisc)'
end-output
output 'tNHarvPisc'
   description   ' cNDPisc * tDHarvPisc'
end-output
output 'wDWebZoo'
   description   ' wDAssZoo - wDRespZoo   -  wDMortZoo - tDConsFiJv'
end-output
output 'wPWebZoo'
   description   ' wPAssZoo - wPExcrZoo   -  wPMortZoo - tPConsFiJv'
end-output
output 'wNWebZoo'
   description   ' wNAssZoo - wNExcrZoo   -  wNMortZoo - tNConsFiJv'
end-output
output 'tDWebBent'
   description   ' tDMigrBent + tDAssBent - tDConsFiAd - tDRespBent'
end-output
output 'tPWebBent'
   description   ' tPMigrBent + tPAssBent - tPConsFiAd - tPExcrBent'
end-output
output 'tNWebBent'
   description   ' tNMigrBent + tNAssBent - tNConsFiAd - tNExcrBent'
end-output
output 'tDWebFiJv'
   description   ' tDMigrFiJv + tDReprFish - tDAgeFish + tDAssFiJv -'
end-output
output 'tPWebFiJv'
   description   ' tPMigrFiJv + tPReprFish - tPAgeFish + tPAssFiJv -'
end-output
output 'tNWebFiJv'
   description   ' tNMigrFiJv + tNReprFish - tNAgeFish + tNAssFiJv -'
end-output
output 'tDWebFiAd'
   description   ' tDMigrFiAd + tDAssFiAd - tDRespFiAd - tDMortFiAd'
end-output
output 'tPWebFiAd'
   description   ' tPMigrFiAd + tPAssFiAd - tPExcrFiAd - tPMortFiAd'
end-output
output 'tNWebFiAd'
   description   ' tNMigrFiAd + tNAssFiAd - tNExcrFiAd - tNMortFiAd'
end-output
output 'tDWebPisc'
   description   ' tDMigrPisc + tDAssPisc - tDRespPisc - tDMortPisc'
end-output
output 'wDWebDetW'
   description   ' - wDConsDetZoo + wDEgesZoo + wDMortZoo   +(tDEges'
end-output
output 'wDWebDiatW'
   description   ' - wDConsDiatZoo'
end-output
output 'wDWebGrenW'
   description   ' - wDConsGrenZoo'
end-output
output 'wDWebBlueW'
   description   ' - wDConsBlueZoo'
end-output
output 'tDWebDetS'
   description   ' - tDConsDetBent + tDEgesBent + tDMortBent'
end-output
output 'tDWebDiatS'
   description   '  - tDConsDiatBent'
end-output
output 'tDWebGrenS'
   description   '  - tDConsGrenBent'
end-output
output 'tDWebBlueS'
   description   '  - tDConsBlueBent'
end-output
output 'tDWebPhytS'
   description   ' tDWebDiatS + tDWebGrenS + tDWebBlueS'
end-output
output 'tDWebTotT'
   description   ' - wDRespZoo * sDepthW   + tDMigrFiJv + tDMigrFiAd'
end-output
output 'wPWebPO4W'
   description   '  + wPExcrZoo + wPEgesZooPO4 + wPMortZooPO4   +(tP'
end-output
output 'wPWebDetW'
   description   ' - wPConsDetZoo + wPEgesZooDet + wPMortZooDet   +('
end-output
output 'wPWebDiatW'
   description   '  - wPConsDiatZoo'
end-output
output 'wPWebGrenW'
   description   ' - wPConsGrenZoo'
end-output
output 'wPWebBlueW'
   description   '  - wPConsBlueZoo'
end-output
output 'tPWebPO4S'
   description   ' tPExcrBent + tPEgesBentPO4 + tPMortBentPO4'
end-output
output 'tPWebDetS'
   description   '  - tPConsDetBent + tPEgesBentDet + tPMortBentDet'
end-output
output 'tPWebDiatS'
   description   '  - tPConsDiatBent'
end-output
output 'tPWebGrenS'
   description   '  - tPConsGrenBent'
end-output
output 'tPWebBlueS'
   description   '  - tPConsBlueBent'
end-output
output 'tPWebPhytS'
   description   ' tPWebDiatS + tPWebGrenS + tPWebBlueS'
end-output
output 'tPWebTotT'
   description   ' tPMigrFiJv + tPMigrFiAd + tPMigrPisc  + tPMigrBen'
end-output
output 'wNWebNH4W'
   description   ' wNExcrZoo + wNEgesZooNH4 + wNMortZooNH4   +(tNExc'
end-output
output 'wNWebNO3W'
   description   ' 0.0'
end-output
output 'wNWebDetW'
   description   ' - wNConsDetZoo + wNEgesZooDet + wNMortZooDet   +('
end-output
output 'wNWebDiatW'
   description   '  - wNConsDiatZoo'
end-output
output 'wNWebGrenW'
   description   '  - wNConsGrenZoo'
end-output
output 'wNWebBlueW'
   description   '  - wNConsBlueZoo'
end-output
output 'tNWebNH4S'
   description   ' tNExcrBent + tNEgesBentNH4 + tNMortBentNH4'
end-output
output 'tNWebNO3S'
   description   ' 0.0'
end-output
output 'tNWebDetS'
   description   '  - tNConsDetBent + tNEgesBentDet + tNMortBentDet'
end-output
output 'tNWebDiatS'
   description   '  - tNConsDiatBent'
end-output
output 'tNWebGrenS'
   description   '  - tNConsGrenBent'
end-output
output 'tNWebBlueS'
   description   '  - tNConsBlueBent'
end-output
output 'tNWebPhytS'
   description   ' tNWebDiatS + tNWebGrenS + tNWebBlueS'
end-output
output 'tNWebTotT'
   description   ' tNMigrFiJv + tNMigrFiAd + tNMigrPisc  + tNMigrBen'
end-output
output 'wSiWebSiO2'
   description   ' 0.0'
end-output
output 'wSiWebDetW'
   description   ' wSiConsDiatZoo'
end-output
output 'tSiWebDetS'
   description   ' tSiConsDiatBent'
end-output
output 'tSiWebTotT'
   description   ' 0.0'
end-output
output 'aPrefAve'
   description   '(cPrefDiat * sDDiatW + cPrefGren * sDGrenW +   cPr'
end-output
output 'wDConsZoo2'
   description   ' aFilt * aPrefAve * oDOMW * sDZoo'
end-output
output 'aDConsZooS'
   description   ' wDConsZoo / sDZoo'
end-output
output 'aDAssZooSp'
   description   ' wDAssZoo / sDZoo'
end-output
output 'aDGrazSp'
   description   ' wDConsZoo / oDOMW'
end-output
output 'aPConsZooS'
   description   ' wPConsZoo / sPZoo'
end-output
output 'aPGrazSp'
   description   ' wPConsZoo / oPOMW'
end-output
output 'aNConsZooS'
   description   ' wNConsZoo / sNZoo'
end-output
output 'aNGrazSp'
   description   ' wNConsZoo / oNOMW'
end-output
output 'afDShootPh'
   description   ' sDShootPhra /(sDRootPhra + sDShootPhra)'
end-output
output 'rDSRPhra'
   description   ' sDShootPhra/sDRootPhra'
end-output
output 'rPDShootPh'
   description   ' sPShootPhra/sDShootPhra'
end-output
output 'rNDShootPh'
   description   ' sNShootPhra/sDShootPhra'
end-output
output 'rPDRootPhr'
   description   ' sPRootPhra/sDRootPhra'
end-output
output 'rNDRootPhr'
   description   ' sNRootPhra/sDRootPhra'
end-output
output 'aLengShoot'
   description   ' sDShootPhra / cDStemPhra / cDensStemPhra'
end-output
output 'FlagInitPh'
   description   ' 0'
end-output
output 'aDAllPhra'
   description   ' 0.0'
end-output
output 'tDAllPhra'
   description   ' 0.0'
end-output
output 'TimeInitPh'
   description   ' Time'
end-output
output 'tNTransPhr'
   description   ' rNDRootPhra * tDAllPhra'
end-output
output 'tPTransPhr'
   description   ' rPDRootPhra * tDAllPhra'
end-output
output 'aVNUptPhra'
   description   ' MAX(0.0,cVNUptPhraMax * cQ10ProdPhra **(0.1 *(uTm'
end-output
output 'ahNUptPhra'
   description   ' aVNUptPhraMaxCr / cAffNUptPhra'
end-output
output 'aVNUptPhrS'
   description   ' aVNUptPhraMaxCr * oNDissS /(ahNUptPhraS + oNDissS'
end-output
output 'tNUptPhraS'
   description   ' aVNUptPhraS * sDRootPhra'
end-output
output 'tNUptNH4Ph'
   description   ' sNH4S / aNDissS * tNUptPhraS'
end-output
output 'tNUptNO3Ph'
   description   ' tNUptPhraS - tNUptNH4PhraS'
end-output
output 'tNUptShoot'
   description   ' afDShootPhra * tNUptPhraS'
end-output
output 'tNUptRootP'
   description   ' tNUptPhraS - tNUptShootPhra'
end-output
output 'aVPUptPhra'
   description   ' MAX(0.0,cVPUptPhraMax * cQ10ProdPhra **(0.1 *(uTm'
end-output
output 'ahPUptPhra'
   description   ' aVPUptPhraMaxCr / cAffPUptPhra'
end-output
output 'aVPUptPhrS'
   description   ' aVPUptPhraMaxCr * oPO4S /(ahPUptPhraS + oPO4S)'
end-output
output 'tPUptPhraS'
   description   ' aVPUptPhraS * sDRootPhra'
end-output
output 'tPUptShoot'
   description   ' afDShootPhra * tPUptPhraS'
end-output
output 'tPUptRootP'
   description   ' tPUptPhraS - tPUptShootPhra'
end-output
output 'uFunTmProa'
   description   ' cQ10ProdPhra **(0.1 *(uTm - cTmRef))'
end-output
output 'ukDRespTmP'
   description   ' kDRespPhra * cQ10RespPhra **(0.1 *(uTm - cTmRef))'
end-output
output 'aMuPhotPhr'
   description   ' cMuPhraMax * uFunTmProdPhra * ufDay'
end-output
output 'aNLimProdP'
   description   '(1.0 - cNDPhraMin / rNDRootPhra) * cNDPhraMax /(cN'
end-output
output 'aPLimProdP'
   description   '(1.0 - cPDPhraMin / rPDRootPhra) * cPDPhraMax /(cP'
end-output
output 'aNutLimPhr'
   description   ' MIN(aNLimProdPhra,aPLimProdPhra)'
end-output
output 'aMuPhra'
   description   ' aMuPhotPhra * aNutLimPhra'
end-output
output 'akDIncrPhr'
   description   ' aMuPhotPhra - ukDRespTmPhra - kDMortShootPhra'
end-output
output 'tDDensPhra'
   description   ' MAX(0.0,akDIncrPhra / cDShootPhraMax * sDShootPhr'
end-output
output 'tDDensProd'
   description   ' aMuPhra / cMuPhraMax * tDDensPhra'
end-output
output 'tDProdPhra'
   description   ' aMuPhra * sDShootPhra - tDDensProdPhra'
end-output
output 'tDProdShoo'
   description   ' afDShootPhra * tDProdPhra'
end-output
output 'tDProdRoot'
   description   ' tDProdPhra - tDProdShootPhra'
end-output
output 'tDRespShoo'
   description   ' ukDRespTmPhra * sDShootPhra'
end-output
output 'tDRespRoot'
   description   ' ukDRespTmPhra * sDRootPhra'
end-output
output 'tO2RespRoo'
   description   ' molO2molC * cCPerDW * tDRespRootPhra * afOxySed'
end-output
output 'tO2FlowPhr'
   description   ' tO2RespRootPhra'
end-output
output 'FlagRealPh'
   description   ' 0'
end-output
output 'aDRealPhra'
   description   ' 0.0'
end-output
output 'tDRealPhra'
   description   ' 0.0'
end-output
output 'TimeRealPh'
   description   ' Time'
end-output
output 'tNRetrPhra'
   description   ' rNDShootPhra * tDRealPhra'
end-output
output 'tPRetrPhra'
   description   ' rPDShootPhra * tDRealPhra'
end-output
output 'tDMortShoo'
   description   ' kDMortShootPhra * sDShootPhra'
end-output
output 'tNMortShoo'
   description   ' rNDShootPhra * tDMortShootPhra'
end-output
output 'tPMortShoo'
   description   ' rPDShootPhra * tDMortShootPhra'
end-output
output 'tDMortRoot'
   description   ' kDMortRootPhra * sDRootPhra'
end-output
output 'tNMortRoot'
   description   ' rNDRootPhra * tDMortRootPhra'
end-output
output 'tPMortRoot'
   description   ' rPDRootPhra * tDMortRootPhra'
end-output
output 'tDManShoot'
   description   ' fManPhra * sDShootPhra'
end-output
output 'tNManShoot'
   description   ' tDManShootPhra * rNDShootPhra'
end-output
output 'tPManShoot'
   description   ' tDManShootPhra * rPDShootPhra'
end-output
output 'dDShootPhr'
   description   ' tDProdShootPhra - tDRespShootPhra - tDMortShootPh'
end-output
output 'dNShootPhr'
   description   ' tNUptShootPhra - tNMortShootPhra + tNTransPhra  -'
end-output
output 'dPShootPhr'
   description   ' tPUptShootPhra - tPMortShootPhra + tPTransPhra  -'
end-output
output 'dDRootPhra'
   description   ' tDProdRootPhra - tDRespRootPhra - tDMortRootPhra'
end-output
output 'dNRootPhra'
   description   ' tNUptRootPhra - tNMortRootPhra - tNTransPhra  + t'
end-output
output 'dPRootPhra'
   description   ' tPUptRootPhra - tPMortRootPhra - tPTransPhra  + t'
end-output
output 'tDSetTot'
   description   ' tDSetIM + tDSetDet + tDSetPhyt'
end-output
output 'tPSetTot'
   description   ' tPSetAIM + tPSetDet + tPSetPhyt'
end-output
output 'tNSetTot'
   description   ' tNSetDet + tNSetPhyt'
end-output
output 'tDResusTot'
   description   ' tDResusDead + tDResusPhytTot'
end-output
output 'tPResusTot'
   description   ' tPResusDet + tPResusAIM + tPResusPhyt + tPResusPO'
end-output
output 'tNResusTot'
   description   ' tNResusDet + tNResusNH4 + tNResusNO3 + tNResusPhy'
end-output
output 'bTimeDred'
   description   '(INT(TimeYears/cDredInterval) * cDredInterval) * D'
end-output
output 'aDepthStar'
   description   ' sDepthW'
end-output
output 'akDredDept'
   description   '(log(cDepthRef / aDepthStart)) / cLengDred'
end-output
output 'akDred'
   description   '(- log(1.0 - fEffDred)) / cLengDred'
end-output
output 'akDredBent'
   description   '(- log(1.0 - fEffDredBent)) / cLengDred'
end-output
output 'akDredLemn'
   description   '(- log(1.0 - fEffDredLemn)) / cLengDred'
end-output
output 'vDredDepth'
   description   ' akDredDepth * sDepthW'
end-output
output 'tDDredDetS'
   description   ' akDred * sDDetS'
end-output
output 'tPDredDetS'
   description   ' akDred * sPDetS'
end-output
output 'tNDredDetS'
   description   ' akDred * sNDetS'
end-output
output 'tSiDredDet'
   description   ' akDred * sSiDetS'
end-output
output 'tPDredAIMS'
   description   ' akDred * sPAIMS'
end-output
output 'bRhoSolidl'
   description   ' fDOrgSoil * cRhoOM +(1 - fDOrgSoil) * cRhoIM'
end-output
output 'tDDredNetS'
   description   ' -(tDDredDetS / cRhoOM) * bRhoSolidSoil'
end-output
output 'tDDredNetI'
   description   '(1 - fDOrgSoil) * tDDredNetSoil'
end-output
output 'tDDredNetH'
   description   ' fDOrgSoil * tDDredNetSoil'
end-output
output 'tPDredNetH'
   description   ' cPDSoilOM * tDDredNetHumS'
end-output
output 'tNDredNetH'
   description   ' cNDSoilOM * tDDredNetHumS'
end-output
output 'tDDredDiat'
   description   ' akDred * sDDiatS'
end-output
output 'tPDredDiat'
   description   ' akDred * sPDiatS'
end-output
output 'tNDredDiat'
   description   ' akDred * sNDiatS'
end-output
output 'tDDredGren'
   description   ' akDred * sDGrenS'
end-output
output 'tPDredGren'
   description   ' akDred * sPGrenS'
end-output
output 'tNDredGren'
   description   ' akDred * sNGrenS'
end-output
output 'tDDredBlue'
   description   ' akDred * sDBlueS'
end-output
output 'tPDredBlue'
   description   ' akDred * sPBlueS'
end-output
output 'tNDredBlue'
   description   ' akDred * sNBlueS'
end-output
output 'tDDredPhyt'
   description   ' tDDredDiatS+tDDredGrenS+tDDredBlueS'
end-output
output 'tPDredPhyt'
   description   ' tPDredDiatS+tPDredGrenS+tPDredBlueS'
end-output
output 'tNDredPhyt'
   description   ' tNDredDiatS+tNDredGrenS+tNDredBlueS'
end-output
output 'tDDredBent'
   description   ' akDredBent * sDBent'
end-output
output 'tPDredBent'
   description   ' akDredBent * sPBent'
end-output
output 'tNDredBent'
   description   ' akDredBent * sNBent'
end-output
output 'tDDredVeg'
   description   ' akDred * sDVeg'
end-output
output 'tPDredVeg'
   description   ' akDred * sPVeg'
end-output
output 'tNDredVeg'
   description   ' akDred * sNVeg'
end-output
output 'tDDredNetT'
   description   ' tDDredDetS - tDDredNetSoil + tDDredPhytS + tDDred'
end-output
output 'tPDredNetT'
   description   ' tPDredDetS - tPDredNetHumS + tPDredAIMS + tPDredP'
end-output
output 'tNDredNetT'
   description   ' tNDredDetS - tNDredNetHumS + tNDredPhytS + tNDred'
end-output
output 'tSiDredTot'
   description   ' tSiDredDetS + cSiDDiat * tDDredDiatS'
end-output
output 'tDIMS'
   description   ' tDAbioIMS'
end-output
output 'tDHumS'
   description   ' tDAbioHumS'
end-output
output 'tDDetS'
   description   ' tDAbioDetS + tDPrimDetS + tDWebDetS + tDBedDetS'
end-output
output 'vDeltaS'
   description   '(tDIMS / cRhoIM +(tDHumS + tDDetS) / cRhoOM)'
end-output
output 'tDBurIM'
   description   '((tDHumS + tDDetS) +(cRhoOM / cRhoIM) * tDIMS) / ('
end-output
output 'tDBurOM'
   description   '(sDHumS + sDDetS) / sDIMS * tDBurIM'
end-output
output 'tDBurDet'
   description   ' sDDetS /(sDHumS + sDDetS) * tDBurOM'
end-output
output 'tDBurHum'
   description   ' tDBurOM - tDBurDet'
end-output
output 'tDBurTot'
   description   ' tDBurIM + tDBurOM'
end-output
output 'tPBurHum'
   description   ' rPDHumS * tDBurHum'
end-output
output 'tPBurDet'
   description   ' rPDDetS * tDBurDet'
end-output
output 'tPBurAIM'
   description   ' sPAIMS / sDIMS * tDBurIM'
end-output
output 'tPBurPO4'
   description   ' sPO4S *(vDeltaS / cDepthS)'
end-output
output 'tPBurTot'
   description   ' tPBurDet + tPBurHum + tPBurAIM + tPBurPO4'
end-output
output 'tNBurHum'
   description   ' rNDHumS * tDBurHum'
end-output
output 'tNBurDet'
   description   ' rNDDetS * tDBurDet'
end-output
output 'tNBurNH4'
   description   ' sNH4S *(vDeltaS / cDepthS)'
end-output
output 'tNBurNO3'
   description   ' sNO3S *(vDeltaS / cDepthS)'
end-output
output 'tNBurTot'
   description   ' tNBurDet + tNBurHum + tNBurNH4 + tNBurNO3'
end-output
output 'tSiBurDet'
   description   ' rSiDDetS * tDBurDet'
end-output
output 'tSiBurTot'
   description   ' tSiBurDet'
end-output
output 'vDeltaW'
   description   ' 0.0'
end-output
output 'aRelDeltaW'
   description   '(vDeltaW + vDredDepthW) / sDepthW'
end-output
output 'dDepthW'
   description   ' vTranDepthW + vDeltaW + vDredDepthW'
end-output
output 'dPO4W'
   description   ' wPTranPO4W + wPAbioPO4W + wPPrimPO4W + wPBedPO4W'
end-output
output 'dPAIMW'
   description   ' wPTranAIMW + wPAbioAIMW - aRelDeltaW * sPAIMW - w'
end-output
output 'dNH4W'
   description   ' wNTranNH4W + wNAbioNH4W + wNPrimNH4W + wNBedNH4W'
end-output
output 'dNO3W'
   description   ' wNTranNO3W + wNAbioNO3W + wNPrimNO3W + wNBedNO3W'
end-output
output 'dSiO2W'
   description   ' wSiTranSiO2 + wSiAbioSiO2W + wSiPrimSiO2W - aRelD'
end-output
output 'dO2W'
   description   ' wO2TranW + wO2AbioW + wO2PrimW + tO2BedW / sDepth'
end-output
output 'dDIMW'
   description   ' wDTranIMW + wDAbioIMW - aRelDeltaW * sDIMW - wDEx'
end-output
output 'dDDetW'
   description   ' wDTranDetW + wDAbioDetW + wDPrimDetW + wDBedDetW'
end-output
output 'dPDetW'
   description   ' wPTranDetW + wPAbioDetW + wPPrimDetW + wPBedDetW'
end-output
output 'dNDetW'
   description   ' wNTranDetW + wNAbioDetW + wNPrimDetW + wNBedDetW'
end-output
output 'dSiDetW'
   description   ' wSiTranDetW + wSiAbioDetW + wSiPrimDetW + wSiWebD'
end-output
output 'dDDiatW'
   description   ' wDTranDiat + wDPrimDiatW + wDWebDiatW - aRelDelta'
end-output
output 'dDGrenW'
   description   ' wDTranGren + wDPrimGrenW + wDWebGrenW - aRelDelta'
end-output
output 'dDBlueW'
   description   ' wDTranBlue + wDPrimBlueW + wDWebBlueW - aRelDelta'
end-output
output 'dPDiatW'
   description   ' wPTranDiat + wPPrimDiatW + wPWebDiatW - aRelDelta'
end-output
output 'dPGrenW'
   description   ' wPTranGren + wPPrimGrenW + wPWebGrenW - aRelDelta'
end-output
output 'dPBlueW'
   description   ' wPTranBlue + wPPrimBlueW + wPWebBlueW - aRelDelta'
end-output
output 'dNDiatW'
   description   ' wNTranDiat + wNPrimDiatW + wNWebDiatW - aRelDelta'
end-output
output 'dNGrenW'
   description   ' wNTranGren + wNPrimGrenW + wNWebGrenW - aRelDelta'
end-output
output 'dNBlueW'
   description   ' wNTranBlue + wNPrimBlueW + wNWebBlueW - aRelDelta'
end-output
output 'dPO4S'
   description   ' tPAbioPO4S - tPBurPO4   + tPPrimPO4S + tPBedPO4S'
end-output
output 'dPAIMS'
   description   ' tPAbioAIMS - tPBurAIM - tPDredAIMS'
end-output
output 'dNH4S'
   description   ' tNAbioNH4S - tNBurNH4   + tNPrimNH4S + tNBedNH4S'
end-output
output 'dNO3S'
   description   ' tNAbioNO3S - tNBurNO3    + tNPrimNO3S + tNBedNO3S'
end-output
output 'dDIMS'
   description   ' tDAbioIMS - tDBurIM - tDDredNetIMS'
end-output
output 'dDHumS'
   description   ' tDAbioHumS - tDBurHum - tDDredNetHumS'
end-output
output 'dPHumS'
   description   ' tPAbioHumS - tPBurHum - tPDredNetHumS'
end-output
output 'dNHumS'
   description   ' tNAbioHumS - tNBurHum - tNDredNetHumS'
end-output
output 'dDDetS'
   description   ' tDAbioDetS - tDBurDet + tDPrimDetS + tDBedDetS +'
end-output
output 'dPDetS'
   description   ' tPAbioDetS - tPBurDet + tPPrimDetS + tPBedDetS +'
end-output
output 'dNDetS'
   description   ' tNAbioDetS - tNBurDet + tNPrimDetS + tNBedDetS +'
end-output
output 'dSiDetS'
   description   ' tSiAbioDetS - tSiBurDet + tSiPrimDetS + tSiWebDet'
end-output
output 'dDDiatS'
   description   ' tDPrimDiatS + tDWebDiatS - tDDredDiatS'
end-output
output 'dDGrenS'
   description   ' tDPrimGrenS + tDWebGrenS - tDDredGrenS'
end-output
output 'dDBlueS'
   description   ' tDPrimBlueS + tDWebBlueS - tDDredBlueS'
end-output
output 'dPDiatS'
   description   ' tPPrimDiatS + tPWebDiatS - tPDredDiatS'
end-output
output 'dPGrenS'
   description   ' tPPrimGrenS + tPWebGrenS - tPDredGrenS'
end-output
output 'dPBlueS'
   description   ' tPPrimBlueS + tPWebBlueS - tPDredBlueS'
end-output
output 'dNDiatS'
   description   ' tNPrimDiatS + tNWebDiatS - tNDredDiatS'
end-output
output 'dNGrenS'
   description   ' tNPrimGrenS + tNWebGrenS - tPDredGrenS'
end-output
output 'dNBlueS'
   description   ' tNPrimBlueS + tNWebBlueS - tNDredBlueS'
end-output
output 'dDVeg'
   description   ' tDBedVeg - tDDredVeg'
end-output
output 'dPVeg'
   description   ' tPBedVeg - tPDredVeg'
end-output
output 'dNVeg'
   description   ' tNBedVeg - tNDredVeg'
end-output
output 'dDZoo'
   description   ' wDTranZoo + wDWebZoo - aRelDeltaW * sDZoo - wDExc'
end-output
output 'dPZoo'
   description   ' wPTranZoo + wPWebZoo - aRelDeltaW * sPZoo - wPExc'
end-output
output 'dNZoo'
   description   ' wNTranZoo + wNWebZoo - aRelDeltaW * sNZoo - wNExc'
end-output
output 'dDBent'
   description   ' tDWebBent - tDDredBent'
end-output
output 'dPBent'
   description   ' tPWebBent - tPDredBent'
end-output
output 'dNBent'
   description   ' tNWebBent - tNDredBent'
end-output
output 'dDFiAd'
   description   ' tDWebFiAd'
end-output
output 'dPFiAd'
   description   ' tPWebFiAd'
end-output
output 'dNFiAd'
   description   ' tNWebFiAd'
end-output
output 'dDFiJv'
   description   ' tDWebFiJv'
end-output
output 'dPFiJv'
   description   ' tPWebFiJv'
end-output
output 'dNFiJv'
   description   ' tNWebFiJv'
end-output
output 'dDPisc'
   description   ' tDWebPisc'
end-output
output 'aDTotM'
   description   ' sDShootPhra + sDRootPhra'
end-output
output 'aPTotM'
   description   ' sPShootPhra + sPRootPhra'
end-output
output 'aNTotM'
   description   ' sNShootPhra + sNRootPhra'
end-output
output 'aSiTotM'
   description   ' 0.0'
end-output
output 'tDMarsTotT'
   description   '(tDProdPhra - tDRespShootPhra - tDRespRootPhra - t'
end-output
output 'tPMarsTotT'
   description   ' - tPManShootPhra * fMarsh'
end-output
output 'tNMarsTotT'
   description   ' - tNManShootPhra * fMarsh'
end-output
output 'tSiMarsTot'
   description   ' 0.0'
end-output
output 'tDExtTotT'
   description   ' - tDBurTot  + tDAbioTotT + tDPrimTotT + tDBedTotT'
end-output
output 'aDTotT'
   description   '(sDIMW+sDDetW+sDDiatW+sDGrenW+sDBlueW+sDZoo) * sDe'
end-output
output 'tPExtTotT'
   description   ' cPBackLoad - tPBurTot   + tPAbioTotT + tPPrimTotT'
end-output
output 'aPTotT'
   description   '(sPO4W+sPDetW+sPDiatW+sPGrenW+sPBlueW   +sPZoo+sPA'
end-output
output 'tNExtTotT'
   description   ' cNBackLoad - tNBurTot   + tNAbioTotT + tNPrimTotT'
end-output
output 'aNTotT'
   description   '(sNH4W+sNO3W+sNDetW+sNDiatW+sNGrenW+sNBlueW  +sNZo'
end-output
output 'tSiExtTotT'
   description   ' tSiAbioTotT - tSiBurTot   + tSiPrimTotT + tSiMars'
end-output
output 'aSiTotT'
   description   '(sSiO2W + sSiDetW + cSiDDiat*sDDiatW) *sDepthW   +'
end-output
output 'aDError'
   description   ' aDTotT - sDExtTotT'
end-output
output 'aPError'
   description   ' aPTotT - sPExtTotT'
end-output
output 'aNError'
   description   ' aNTotT - sNExtTotT'
end-output
output 'aSiError'
   description   ' aSiTotT - sSiExtTotT'
end-output
active-processes
   name  'HydDuflow' 'HydDuflow'
   name  'Pcl508' 'Pcl508'
end-active-processes
