substance 'sDIMW' active
   description        'inorg. matter in water'
   concentration-unit 'mg/l'
   waste-load-unit    '-'
end-substance
substance 'sDHumS' inactive
   description        'humus in sediment'
   concentration-unit 'g/m2'
   waste-load-unit    '-'
end-substance
substance 'sDDetW' active
   description        'Detritus'
   concentration-unit 'mg/l'
   waste-load-unit    '-'
end-substance
substance 'sDIMS' inactive
   description        'inorg. matter in sediment'
   concentration-unit 'g/m2'
   waste-load-unit    '-'
end-substance
substance 'sDDetS' inactive
   description        'Sediment detritus'
   concentration-unit 'g/m2'
   waste-load-unit    '-'
end-substance
substance 'sO2W' active
   description        'Oxygen in water'
   concentration-unit 'mgO2/l'
   waste-load-unit    '-'
end-substance
substance 'sPO4W' active
   description        'SRP in water'
   concentration-unit 'mgP/l'
   waste-load-unit    '-'
end-substance
substance 'sPAIMW' active
   description        'P-adsorbed onto IM in water'
   concentration-unit 'mgP/l'
   waste-load-unit    '-'
end-substance
substance 'sPDetW' active
   description        'Detritus'
   concentration-unit 'mgP/l'
   waste-load-unit    '-'
end-substance
substance 'sPO4S' inactive
   description        'Pore water P'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sPAIMS' inactive
   description        'P-adsorbed onto IM in sediment'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sPHumS' inactive
   description        'humus in sediment'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sPDetS' inactive
   description        'Sediment P'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sNH4W' active
   description        'ammonium in water'
   concentration-unit 'mgN/l/d'
   waste-load-unit    '-'
end-substance
substance 'sNO3W' active
   description        'nitrate in water'
   concentration-unit 'mgN/l'
   waste-load-unit    '-'
end-substance
substance 'sNDetW' active
   description        'Detritus in water'
   concentration-unit 'mgN/l/d'
   waste-load-unit    '-'
end-substance
substance 'sNH4S' inactive
   description        'Pore water ammonium'
   concentration-unit 'gN/m2/d'
   waste-load-unit    '-'
end-substance
substance 'sNO3S' inactive
   description        'Pore water nitrate'
   concentration-unit 'gN/m2/d'
   waste-load-unit    '-'
end-substance
substance 'sNHumS' inactive
   description        'Humus in sediment'
   concentration-unit 'gN/m2'
   waste-load-unit    '-'
end-substance
substance 'sNDetS' inactive
   description        'Sediment detritus N'
   concentration-unit 'gN/m2/d'
   waste-load-unit    '-'
end-substance
substance 'sDPhytW' active
   description        'Phytoplankton'
   concentration-unit 'mgD/l'
   waste-load-unit    '-'
end-substance
substance 'sPPhytW' active
   description        'Phytoplankton'
   concentration-unit 'mgP/l'
   waste-load-unit    '-'
end-substance
substance 'sNPhytW' active
   description        'Phytoplankton'
   concentration-unit 'mgN/l'
   waste-load-unit    '-'
end-substance
substance 'sDPhytS' inactive
   description        'Sediment algae'
   concentration-unit 'mgD/l'
   waste-load-unit    '-'
end-substance
substance 'sPPhytS' inactive
   description        'Sediment algae'
   concentration-unit 'gP m-2'
   waste-load-unit    '-'
end-substance
substance 'sNPhytS' inactive
   description        'Sediment algae'
   concentration-unit 'gN m-2'
   waste-load-unit    '-'
end-substance
substance 'sDElod' inactive
   description        'rooted plants'
   concentration-unit 'gD/m2'
   waste-load-unit    '-'
end-substance
substance 'sDChar' inactive
   description        'characeans'
   concentration-unit 'gD/m2'
   waste-load-unit    '-'
end-substance
substance 'sDCera' inactive
   description        'non-rooted plants'
   concentration-unit 'gD/m2'
   waste-load-unit    '-'
end-substance
substance 'sDLemn' inactive
   description        'duckweed'
   concentration-unit 'gD/m2'
   waste-load-unit    '-'
end-substance
substance 'sDNymp' inactive
   description        'nymphaeids'
   concentration-unit 'gD/m2'
   waste-load-unit    '-'
end-substance
substance 'sDHelo' inactive
   description        'helophytes'
   concentration-unit 'gD/m2'
   waste-load-unit    '-'
end-substance
substance 'sPElod' inactive
   description        'rooted plants'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sPChar' inactive
   description        'characeans'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sPCera' inactive
   description        'non-rooted plants'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sPLemn' inactive
   description        'duckweed'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sPNymp' inactive
   description        'nymphaeids'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sPHelo' inactive
   description        'helophytes'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sNElod' inactive
   description        'rooted plants'
   concentration-unit 'gN/m2'
   waste-load-unit    '-'
end-substance
substance 'sNChar' inactive
   description        'characeans'
   concentration-unit 'gN/m2'
   waste-load-unit    '-'
end-substance
substance 'sNCera' inactive
   description        'non-rooted plants'
   concentration-unit 'gN/m2'
   waste-load-unit    '-'
end-substance
substance 'sNLemn' inactive
   description        'duckweed'
   concentration-unit 'gN/m2'
   waste-load-unit    '-'
end-substance
substance 'sNNymp' inactive
   description        'nymphaeids'
   concentration-unit 'gN/m2'
   waste-load-unit    '-'
end-substance
substance 'sNHelo' inactive
   description        'helophytes'
   concentration-unit 'gN/m2'
   waste-load-unit    '-'
end-substance
substance 'sDExtTot' inactive
   description        'total amount of DW moved into or out from the syst'
   concentration-unit 'g/m2'
   waste-load-unit    '-'
end-substance
substance 'sPExtTot' inactive
   description        'total amount of P moved into or out from the syste'
   concentration-unit 'gP/m2'
   waste-load-unit    '-'
end-substance
substance 'sNExtTot' inactive
   description        'total amount of N moved into or out from the syste'
   concentration-unit 'gN/m2'
   waste-load-unit    '-'
end-substance
substance 'Time' inactive
   description        'time'
   concentration-unit 'day'
   waste-load-unit    '-'
end-substance
parameter 'BeginTime'
   description   'begintime'
   unit          'day'
   value             0.000000    
end-parameter
parameter 'EndTime'
   description   '(=1 year)'
   unit          'day'
   value             365.0000    
end-parameter
parameter 'InitCalc'
   description   'If T, skip calculation of initial values; used in'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'ConstDepth'
   description   'If T, water depth kept constant by  daily dredging'
   unit          '{no unit}'
   value             1.000000    
end-parameter
parameter 'Lake'
   description   'undefined'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'Ditch'
   description   'undefined'
   unit          '{no unit}'
   value             1.000000    
end-parameter
parameter 'InclTran'
   description   'undefined'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'InclPrim'
   description   'undefined'
   unit          '{no unit}'
   value             1.000000    
end-parameter
parameter 'InclThreeA'
   description   'undefined'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'InclPhytS'
   description   'undefined'
   unit          '{no unit}'
   value             1.000000    
end-parameter
parameter 'InclBed'
   description   'undefined'
   unit          '{no unit}'
   value             1.000000    
end-parameter
parameter 'InclSixVeg'
   description   'undefined'
   unit          '{no unit}'
   value             1.000000    
end-parameter
parameter 'InclWeb'
   description   'undefined'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'InclMarsh'
   description   'undefined'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'iCase'
   description   'undefined'
   unit          '{no unit}'
   value             1.000000    
end-parameter
parameter 'UseWindFun'
   description   'FALSE = no wind function for shear stress,'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'ReadTemp'
   description   'If TRUE use measured time-series of temperature, o'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'ReadLOut'
   description   'If TRUE use measured time-series of light, otherwi'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'ReadVWind'
   description   'If TRUE use measured time-series of wind, otherwis'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'RewindInpu'
   description   'Only important if time-series are being used.'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'YearZero'
   description   'Note: also Dayno 1 = 1. Jan. of this year.'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'cFetch'
   description   'wind fetch'
   unit          'm'
   value             0.000000    
end-parameter
parameter 'fMarsh'
   description   'relative marsh area'
   unit          'm2 marsh m-2 lake'
   value             0.000000    
end-parameter
parameter 'fLutum'
   description   'lutum content of inorg. matter'
   unit          '-'
   value            0.1000000    
end-parameter
parameter 'fFeDIM'
   description   'Fe content of inorg. matter'
   unit          'gFe/gD'
   value            0.1000000E-01
end-parameter
parameter 'fAlDIM'
   description   'Al content of inorg. matter'
   unit          'gAl/gD'
   value            0.1000000E-01
end-parameter
parameter 'cTmAve'
   description   'average water temperature'
   unit          'oC'
   value             12.00000    
end-parameter
parameter 'cTmVar'
   description   'annual temperature variation'
   unit          'oC'
   value             10.00000    
end-parameter
parameter 'cTimeLag'
   description   'time lag for temperature'
   unit          'day'
   value             40.00000    
end-parameter
parameter 'cVWind'
   description   'average wind speed'
   unit          'm/s'
   value             5.000000    
end-parameter
parameter 'cQInf'
   description   'infiltration rate'
   unit          'mm/day'
   value             0.000000    
end-parameter
parameter 'cPBackLoad'
   description   '0.00016'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'cNBackLoad'
   description   '0.009'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'cLDayAve'
   description   'annual average radiation'
   unit          'J/m2/day'
   value            0.1000000E+08
end-parameter
parameter 'cLDayVar'
   description   'annual variation in radiation'
   unit          'J/m2/day'
   value             8000000.    
end-parameter
parameter 'cfDayAve'
   description   'average day length'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'cfDayVar'
   description   'annual variation in day length'
   unit          '-'
   value            0.2000000    
end-parameter
parameter 'fRefl'
   description   '0.1'
   unit          '{no unit}'
   value            0.2000000    
end-parameter
parameter 'cExtWat'
   description   'background extinction'
   unit          'm-1'
   value            0.5000000    
end-parameter
parameter 'cDredInter'
   description   'dredging interval'
   unit          'y'
   value             9999000.    
end-parameter
parameter 'cDredStart'
   description   'first dredging year (should be n times cDredInterv'
   unit          'y'
   value             9999000.    
end-parameter
parameter 'cDepthRef'
   description   'reference water depth for dredging'
   unit          'day'
   value            0.1000000E-32
end-parameter
parameter 'cLengDred'
   description   'length of dredging period'
   unit          'day'
   value             10.00000    
end-parameter
parameter 'fEffDred'
   description   'dredging efficiency (<1.0)'
   unit          '-'
   value            0.9500000    
end-parameter
parameter 'fEffDredBe'
   description   'dredging efficiency for zoobenthos (<1.0)'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'fEffDredLe'
   description   'dredging efficiency for duckweed (<1.0)'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'fPAR'
   description   'fraction photosynthetically active radiation (PAR)'
   unit          '-'
   value            0.4800000    
end-parameter
parameter 'cExtSpDet'
   description   'specific extinction detritus'
   unit          'm2/gDW'
   value            0.1500000    
end-parameter
parameter 'cExtSpIM'
   description   'specific extinction inert matter'
   unit          'm2/gDW'
   value            0.5000000E-01
end-parameter
parameter 'sDepthW0'
   description   'initial water depth'
   unit          'm'
   value            0.5000000    
end-parameter
parameter 'sDIMW0'
   description   'water IM'
   unit          'mgDW/l'
   value             5.000000    
end-parameter
parameter 'sDDetW0'
   description   'water detritus'
   unit          'mgDW/l'
   value             2.000000    
end-parameter
parameter 'sO2W0'
   description   'oxygen in water'
   unit          'mgO2/l'
   value             10.00000    
end-parameter
parameter 'sPO4W0'
   description   'undefined'
   unit          'mgP/l'
   value            0.1000000E-01
end-parameter
parameter 'sPAIMW0'
   description   'adsorbed on IM in water'
   unit          'mgP/l'
   value             0.000000    
end-parameter
parameter 'sNO3W0'
   description   'NO3 in water'
   unit          'mgN/l'
   value            0.1000000    
end-parameter
parameter 'sNH4W0'
   description   'NH4 in water'
   unit          'mgN/l'
   value            0.1000000    
end-parameter
parameter 'sNH4S0'
   description   'dissolved N-NH4 in interstitial water'
   unit          'gN/m2'
   value            0.2000000E-01
end-parameter
parameter 'sNO3S0'
   description   'dissolved N-NO3 in interstitial water'
   unit          'gN/m2'
   value            0.2000000E-02
end-parameter
parameter 'sDPhytW0'
   description   'phytoplankton'
   unit          'mgDW/l'
   value             1.000000    
end-parameter
parameter 'sDPhytS0'
   description   'sediment algae'
   unit          'gDW/m2'
   value            0.1000000E-02
end-parameter
parameter 'sDElod0'
   description   'undefined'
   unit          'gD/m2'
   value             1.000000    
end-parameter
parameter 'sDChar0'
   description   'undefined'
   unit          'gD/m2'
   value             1.000000    
end-parameter
parameter 'sDCera0'
   description   'undefined'
   unit          'gD/m2'
   value             1.000000    
end-parameter
parameter 'sDLemn0'
   description   'undefined'
   unit          'gD/m2'
   value             1.000000    
end-parameter
parameter 'sDNymp0'
   description   'undefined'
   unit          'gD/m2'
   value             1.000000    
end-parameter
parameter 'sDHelo0'
   description   'undefined'
   unit          'gD/m2'
   value             1.000000    
end-parameter
parameter 'fDTotS0'
   description   'initial dry-weight fraction in sediment'
   unit          'g solid g-1 sediment'
   value            0.3000000    
end-parameter
parameter 'fDOrgS0'
   description   'initial organic fraction of sediment DW'
   unit          'g/g'
   value            0.1000000    
end-parameter
parameter 'fDDetS0'
   description   'initial detritus fraction of sediment organic matt'
   unit          'g/g'
   value            0.1000000    
end-parameter
parameter 'fPInorgS0'
   description   'initial inorg. P fraction in sed.'
   unit          'gP/gD'
   value            0.5000000E-03
end-parameter
parameter 'fPAdsS0'
   description   'initial adsorbed fraction of inorg. P in sed.'
   unit          '-'
   value            0.9900000    
end-parameter
parameter 'cPDDet0'
   description   'initial P fraction in detritus'
   unit          'gP/gDDet'
   value            0.2500000E-02
end-parameter
parameter 'cNDDet0'
   description   'initial N fraction in detritus'
   unit          'gN/gDDet'
   value            0.2500000E-01
end-parameter
parameter 'cSiDDet0'
   description   'initial Si fraction in detritus   Tentative'
   unit          'gSi/gDDet'
   value            0.1000000E-01
end-parameter
parameter 'cPDHum0'
   description   'initial P fraction in humus'
   unit          'gP/gDDet'
   value            0.5000000E-02
end-parameter
parameter 'cNDHum0'
   description   'initial N fraction in humus'
   unit          'gN/gDDet'
   value            0.5000000E-01
end-parameter
parameter 'cPDPhyt0'
   description   'initial P fraction in algae'
   unit          'gP/gD'
   value            0.1000000E-01
end-parameter
parameter 'cNDPhyt0'
   description   'initial N fraction in algae'
   unit          'gN/gD'
   value            0.1000000    
end-parameter
parameter 'cPDElod0'
   description   'initial P fraction in Elod.'
   unit          'gP/gD'
   value            0.2000000E-02
end-parameter
parameter 'cNDElod0'
   description   'initial N fraction in Elod.'
   unit          'gN/gD'
   value            0.2000000E-01
end-parameter
parameter 'cPDChar0'
   description   'initial P fraction in Char.'
   unit          'gP/gD'
   value            0.2000000E-02
end-parameter
parameter 'cNDChar0'
   description   'initial N fraction in Char.'
   unit          'gN/gD'
   value            0.2000000E-01
end-parameter
parameter 'cPDCera0'
   description   'initial P fraction in Cera.'
   unit          'gP/gD'
   value            0.2000000E-02
end-parameter
parameter 'cNDCera0'
   description   'initial N fraction in Cera.'
   unit          'gN/gD'
   value            0.2000000E-01
end-parameter
parameter 'cPDLemn0'
   description   'initial P fraction in Lemn.'
   unit          'gP/gD'
   value            0.5000000E-02
end-parameter
parameter 'cNDLemn0'
   description   'initial N fraction in Lemn.'
   unit          'gN/gD'
   value            0.5000000E-01
end-parameter
parameter 'cPDNymp0'
   description   'initial P fraction in Nymp.'
   unit          'gP/gD'
   value            0.2000000E-02
end-parameter
parameter 'cNDNymp0'
   description   'initial N fraction in Nymp.'
   unit          'gN/gD'
   value            0.2000000E-01
end-parameter
parameter 'cPDHelo0'
   description   'initial P fraction in Helo.'
   unit          'gP/gD'
   value            0.2000000E-02
end-parameter
parameter 'cNDHelo0'
   description   'initial N fraction in Helo.'
   unit          'gN/gD'
   value            0.2000000E-01
end-parameter
parameter 'cNLoadS'
   description   'N fertilizer to sediment'
   unit          'gN/m2/day'
   value             0.000000    
end-parameter
parameter 'fNH4LoadS'
   description   'NH4 fraction of N fertilizer to sediment'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'cDErosTot'
   description   'Erosion input (tentative)'
   unit          'g/m2/day'
   value             10.00000    
end-parameter
parameter 'fSedErosIM'
   description   'instantly sedimentating fraction of IM'
   unit          '-'
   value            0.9500000    
end-parameter
parameter 'fDOrgSoil'
   description   'fraction soil organic matter'
   unit          '-'
   value            0.1000000    
end-parameter
parameter 'cPDSoilOM'
   description   'P/D ratio of soil organic matter'
   unit          'gP/gD'
   value            0.1000000E-02
end-parameter
parameter 'cNDSoilOM'
   description   'N/D ratio of soil organic matter'
   unit          'gN/gD'
   value            0.1000000E-01
end-parameter
parameter 'cPO4Ground'
   description   'PO4 in (deeper) groundwater'
   unit          'mgP/l'
   value            0.1000000    
end-parameter
parameter 'cNH4Ground'
   description   'NH4 in (deeper) groundwater'
   unit          'mgN/l'
   value             1.000000    
end-parameter
parameter 'cNO3Ground'
   description   'NO3 in (deeper) groundwater'
   unit          'mgN/l'
   value            0.1000000    
end-parameter
parameter 'cDepthS'
   description   'sediment depth'
   unit          'm'
   value            0.1000000    
end-parameter
parameter 'cCPerDW'
   description   'C content of organic matter'
   unit          'gC/gDW'
   value            0.4000000    
end-parameter
parameter 'cRhoIM'
   description   'density of sediment IM'
   unit          'g/m3 solid'
   value             2500000.    
end-parameter
parameter 'cRhoOM'
   description   'density of sediment detritus'
   unit          'g/m3'
   value             1400000.    
end-parameter
parameter 'cTmRef'
   description   'reference temperature'
   unit          'oC'
   value             20.00000    
end-parameter
parameter 'cAerRoot'
   description   'coefficient for VWind^0.5'
   unit          '{no unit}'
   value            0.7270000    
end-parameter
parameter 'cAerLin'
   description   'coefficient for VWind (is negative.)'
   unit          's/day'
   value           -0.3710000    
end-parameter
parameter 'cAerSquare'
   description   'coefficient for VWind^2'
   unit          '{no unit}'
   value            0.3760000E-01
end-parameter
parameter 'cThetaAer'
   description   'Temperature coeff. for reaeration  (Downing & True'
   unit          '1/e^oC'
   value             1.024000    
end-parameter
parameter 'kLemnAer'
   description   'reaeration reduction by duckweed'
   unit          '(gD/m2)-1'
   value            0.1000000E-01
end-parameter
parameter 'cVSetIM'
   description   'max. sedimentation velocity of inert org. matter'
   unit          'm/day'
   value             1.000000    
end-parameter
parameter 'cVSetDet'
   description   'max. sedimentation velocity of detritus'
   unit          'm/day'
   value            0.2500000    
end-parameter
parameter 'cThetaSet'
   description   'temp. parameter of sedimentation'
   unit          '1/e^oC'
   value             1.010000    
end-parameter
parameter 'cSuspMin'
   description   'undefined'
   unit          '{no unit}'
   value             6.100000    
end-parameter
parameter 'cSuspMax'
   description   'undefined'
   unit          '{no unit}'
   value             25.20000    
end-parameter
parameter 'cSuspSlope'
   description   'undefined'
   unit          '{no unit}'
   value             2.100000    
end-parameter
parameter 'hDepthSusp'
   description   'undefined'
   unit          '{no unit}'
   value             2.000000    
end-parameter
parameter 'cFetchRef'
   description   'undefined'
   unit          '{no unit}'
   value             1000.000    
end-parameter
parameter 'fLutumRef'
   description   'undefined'
   unit          '{no unit}'
   value            0.2000000    
end-parameter
parameter 'cSuspRef'
   description   'undefined'
   unit          '{no unit}'
   value            0.5000000    
end-parameter
parameter 'kVegResus'
   description   'rel. resuspension reduction per g vegetation'
   unit          'm2/gDW'
   value            0.1000000E-01
end-parameter
parameter 'kTurbFish'
   description   'relative resuspension by adult fish browsing'
   unit          'g/g fish/day'
   value             1.000000    
end-parameter
parameter 'kResusPhyt'
   description   'max. phytopl. resuspension'
   unit          'day-1'
   value            0.2500000    
end-parameter
parameter 'cResusPhyt'
   description   'exp. par. for phytopl. resuspension'
   unit          '(gD/m2/day)-1'
   value           -0.3790000    
end-parameter
parameter 'cThetaMinW'
   description   'expon. temp. constant of mineralization in water'
   unit          '-'
   value             1.070000    
end-parameter
parameter 'kDMinDetW'
   description   'decomposition constant of detritus'
   unit          'day-1'
   value            0.1000000E-01
end-parameter
parameter 'hO2BOD'
   description   'half-sat. oxygen conc. for BOD'
   unit          'mgO2/l'
   value             1.000000    
end-parameter
parameter 'O2PerNO3'
   description   'mol O2 formed per mol NO3- ammonified'
   unit          '-'
   value             1.500000    
end-parameter
parameter 'cThetaMinS'
   description   'expon. temp. constant of sediment mineralization'
   unit          '-'
   value             1.070000    
end-parameter
parameter 'kDMinDetS'
   description   'decomposition constant of sediment detritus'
   unit          'day-1'
   value            0.2000000E-02
end-parameter
parameter 'fRefrDetS'
   description   'refractory fraction of sed. detritus'
   unit          '-'
   value            0.1500000    
end-parameter
parameter 'hNO3Denit'
   description   'quadratic half-sat. NO3 conc. for denitrification'
   unit          'mgN/l'
   value             2.000000    
end-parameter
parameter 'NO3PerC'
   description   'mol NO3 denitrified per mol C mineralised'
   unit          '-'
   value            0.8000000    
end-parameter
parameter 'kDMinHum'
   description   'maximum decomposition constant of humic material ('
   unit          'day-1'
   value            0.1000000E-04
end-parameter
parameter 'kNitrW'
   description   'nitrification constant in water'
   unit          'day-1'
   value            0.1000000    
end-parameter
parameter 'kNitrS'
   description   'nitrification constant in sediment top layer'
   unit          'day-1'
   value             1.000000    
end-parameter
parameter 'cThetaNitr'
   description   'expon. temperature constant of nitrification'
   unit          '1/e^oC'
   value             1.080000    
end-parameter
parameter 'O2PerNH4'
   description   'mol O2 used per mol NH4+ nitrified'
   unit          '-'
   value             2.000000    
end-parameter
parameter 'hO2Nitr'
   description   'half-sat. O2 conc. for nitrification'
   unit          'mgO2/l'
   value             2.000000    
end-parameter
parameter 'kPDifPO4'
   description   'mol. PO4 diffusion constant'
   unit          'm2/day'
   value            0.7200000E-04
end-parameter
parameter 'kNDifNO3'
   description   'mol. NO3 diffusion constant'
   unit          'm2/day'
   value            0.8600000E-04
end-parameter
parameter 'kNDifNH4'
   description   'mol. NH4 diffusion constant'
   unit          'm2/day'
   value            0.1120000E-03
end-parameter
parameter 'kO2Dif'
   description   'mol. O2 diffusion constant'
   unit          'm2/day'
   value            0.2600000E-04
end-parameter
parameter 'cThetaDif'
   description   'Temperature coefficient for diffusion'
   unit          '1/e^oC'
   value             1.020000    
end-parameter
parameter 'fDepthDifS'
   description   'nutrient diffusion distance as fraction of sedimen'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'cTurbDifNu'
   description   'bioturbation factor for diffusion'
   unit          '-'
   value             5.000000    
end-parameter
parameter 'cTurbDifO2'
   description   'bioturbation factor for diffusion'
   unit          '-'
   value             5.000000    
end-parameter
parameter 'kPSorp'
   description   'P sorption rate constant   not too high -> model s'
   unit          'day-1'
   value            0.5000000E-01
end-parameter
parameter 'cRelPAdsD'
   description   'max. P adsorption per g DW'
   unit          'gP/gD'
   value            0.3000000E-04
end-parameter
parameter 'cRelPAdsFe'
   description   'max. P adsorption per g Fe'
   unit          'gP/gFe'
   value            0.6500000E-01
end-parameter
parameter 'cRelPAdsAl'
   description   'max. P adsorption per g Al'
   unit          'gP/gAl'
   value            0.1340000    
end-parameter
parameter 'cKPAdsOx'
   description   'P adsorption affinity at oxidized conditions'
   unit          'm3/gP'
   value            0.6000000    
end-parameter
parameter 'fRedMax'
   description   'max. reduction factor of P adsorption affinity'
   unit          '-'
   value            0.9000000    
end-parameter
parameter 'coPO4Max'
   description   'max. SRP conc. in pore water'
   unit          'mgP/l'
   value             2.000000    
end-parameter
parameter 'kPChemPO4'
   description   'chem. PO4 loss rate'
   unit          'day-1'
   value            0.3000000E-01
end-parameter
parameter 'fObstrLemn'
   description   'obstructed fraction of duckweed outflow'
   unit          '-'
   value             1.000000    
end-parameter
parameter 'cDayManVeg'
   description   'first mowing day (default: non-existent)'
   unit          'day'
   value            -9999000.    
end-parameter
parameter 'cDayManVe2'
   description   '259.0'
   unit          '{no unit}'
   value            -9999000.    
end-parameter
parameter 'fManVeg'
   description   'Fraction removed by management , for submerged pla'
   unit          '-'
   value            0.8000000    
end-parameter
parameter 'fManLemn'
   description   'Fraction of duckweed removed by management'
   unit          '-'
   value            0.4000000    
end-parameter
parameter 'fManHelo'
   description   'Fraction of helophytes and nymphaeids removed by m'
   unit          '-'
   value            0.8000000    
end-parameter
parameter 'cLengMan'
   description   'length of mowing period'
   unit          'day'
   value             10.00000    
end-parameter
parameter 'cYearStart'
   description   'first year of birds  presence'
   unit          'y'
   value             0.000000    
end-parameter
parameter 'cDayStartB'
   description   'yearly first day of birds  presence'
   unit          'day'
   value             46.00000    
end-parameter
parameter 'cDayEndBir'
   description   'yearly last day of birds  presence'
   unit          'day'
   value             288.0000    
end-parameter
parameter 'cBirdsPerh'
   description   'number of birds per ha vegetated lake (Default = 0'
   unit          'n/ha'
   value             0.000000    
end-parameter
parameter 'cDGrazPerB'
   description   'daily grazing of birds'
   unit          'gD/coot/day'
   value             45.00000    
end-parameter
parameter 'hDVegBird'
   description   'half-sat. vegetation biomass'
   unit          '{no unit}'
   value             5.000000    
end-parameter
parameter 'fDAssBird'
   description   'birds assim. efficiency'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'fDissEgesB'
   description   'fraction dissolved nutrient of coot egestion'
   unit          '-'
   value            0.2500000    
end-parameter
parameter 'fDissMortV'
   description   'fraction dissolved nutrients from died plants'
   unit          '-'
   value            0.2500000    
end-parameter
parameter 'cLengAllo'
   description   'duration of allocation and reallocation phase'
   unit          'day'
   value             15.00000    
end-parameter
parameter 'cLengMort'
   description   'duration of autumn mortality period'
   unit          'day'
   value             15.00000    
end-parameter
parameter 'fSedUptVeg'
   description   'maximum sediment fraction of nutrient uptake'
   unit          '-'
   value            0.9980000    
end-parameter
parameter 'fSedUptVef'
   description   'sigm. regr. coeff. for sediment fraction of nutrie'
   unit          '-'
   value             2.660000    
end-parameter
parameter 'fSedUptVep'
   description   'exponent in sigm. regr. for sediment fraction of n'
   unit          '-'
   value           -0.8300000    
end-parameter
parameter 'fRootElodS'
   description   'root fraction outside growing season'
   unit          'g root / g veg'
   value            0.1000000    
end-parameter
parameter 'fRootElodW'
   description   'root fraction outside growing season'
   unit          'g root / g veg'
   value            0.6000000    
end-parameter
parameter 'fFloatElod'
   description   'floating fraction of shoot'
   unit          'g floating / g shoot'
   value             0.000000    
end-parameter
parameter 'fEmergElod'
   description   'emergent fraction of shoot'
   unit          'g floating / g shoot'
   value             0.000000    
end-parameter
parameter 'fDepth1Elo'
   description   'max. upper depth of submerged veget. layer, as fra'
   unit          '-'
   value             0.000000    
end-parameter
parameter 'fDepth2Elo'
   description   'max. lower depth of submerged veget. layer, as fra'
   unit          '-'
   value             1.000000    
end-parameter
parameter 'cDLayerElo'
   description   'biomass of a single layer floating leaves'
   unit          'gD/m2'
   value             0.000000    
end-parameter
parameter 'cCovSpElod'
   description   'specific cover  Tent.'
   unit          '% cover per gD/m2'
   value            0.5000000    
end-parameter
parameter 'kMigrElod'
   description   'vegetation migration rate'
   unit          'day-1'
   value            0.1000000E-04
end-parameter
parameter 'cDElodIn'
   description   ' external vegetation density'
   unit          'gD/m2'
   value            0.1000000    
end-parameter
parameter 'cTmInitElo'
   description   'temperature for start of season'
   unit          'oC'
   value             10.00000    
end-parameter
parameter 'cDCarrElod'
   description   'max. vegetation biomass'
   unit          'gDW/m2'
   value             500.0000    
end-parameter
parameter 'cMuMaxElod'
   description   'maximum growth rate of vegetation at 20oC'
   unit          'g/g shoot/day'
   value            0.3200000    
end-parameter
parameter 'cQ10ProdEl'
   description   'temperature quotient of production'
   unit          '-'
   value             1.200000    
end-parameter
parameter 'hLRefElod'
   description   'half-sat. light at 20 oC'
   unit          'W/m2 PAR'
   value             32.00000    
end-parameter
parameter 'cExtSpElod'
   description   'specific extinction'
   unit          'm2/gDW'
   value            0.1000000E-01
end-parameter
parameter 'kDRespElod'
   description   'dark respiration rate of vegetation'
   unit          'day-1'
   value            0.2400000E-01
end-parameter
parameter 'cQ10RespEl'
   description   'temperature quotient of respiration'
   unit          '-'
   value             1.500000    
end-parameter
parameter 'cDayWinElo'
   description   'end of growing season  = 16 Sep'
   unit          '-'
   value             259.0000    
end-parameter
parameter 'kMortElodS'
   description   'vegetation mortality rate in Spring and Summer  (l'
   unit          'day-1'
   value            0.5000000E-02
end-parameter
parameter 'fWinElod'
   description   'fraction surviving in winter'
   unit          '-'
   value            0.2000000    
end-parameter
parameter 'fDetWMortE'
   description   'fraction of shoot mortality becoming water detritu'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'cPrefElodB'
   description   'edibility for birds'
   unit          '-'
   value             1.000000    
end-parameter
parameter 'cVPUptMaxE'
   description   'maximum P uptake capacity of vegetation'
   unit          'mgP/mgD/day'
   value            0.1000000E-01
end-parameter
parameter 'cAffPUptEl'
   description   'initial P uptake affinity vegetation'
   unit          'l/mgD/day'
   value            0.2000000    
end-parameter
parameter 'cPDElodMin'
   description   '0.001'
   unit          '{no unit}'
   value            0.8000000E-03
end-parameter
parameter 'cPDElodMax'
   description   'Best, 1979'
   unit          '{no unit}'
   value            0.3500000E-02
end-parameter
parameter 'cVNUptMaxE'
   description   'maximum N uptake capacity of vegetation'
   unit          'mgN/mgD/day'
   value            0.1000000    
end-parameter
parameter 'cAffNUptEl'
   description   'initial N uptake affinity vegetation'
   unit          'l/mgD/day'
   value            0.2000000    
end-parameter
parameter 'cNDElodMin'
   description   'minimum N/D ratio vegetation'
   unit          'mgN/mgD'
   value            0.1000000E-01
end-parameter
parameter 'cNDElodMax'
   description   '3 a 4 %, Best 1979'
   unit          '{no unit}'
   value            0.3500000E-01
end-parameter
parameter 'fRootCharS'
   description   'root fraction in growing season'
   unit          'g root / g veg'
   value            0.5000000E-01
end-parameter
parameter 'fRootCharW'
   description   'root fraction outside growing season'
   unit          'g root / g veg'
   value            0.1000000    
end-parameter
parameter 'fFloatChar'
   description   'floating fraction of shoot'
   unit          'g floating / g shoot'
   value             0.000000    
end-parameter
parameter 'fEmergChar'
   description   'emergent fraction of shoot'
   unit          'g floating / g shoot'
   value             0.000000    
end-parameter
parameter 'fDepth1Cha'
   description   'max. upper depth of submerged veget. layer, as fra'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'fDepth2Cha'
   description   'max. lower depth of submerged veget. layer, as fra'
   unit          '-'
   value             1.000000    
end-parameter
parameter 'cCovSpChar'
   description   'specific cover  Tent.'
   unit          '% cover per gD/m2'
   value            0.5000000    
end-parameter
parameter 'cDLayerCha'
   description   'biomass of a single layer floating leaves'
   unit          'gD/m2'
   value             0.000000    
end-parameter
parameter 'kMigrChar'
   description   'vegetation migration rate'
   unit          'day-1'
   value            0.1000000E-04
end-parameter
parameter 'cDCharIn'
   description   ' external vegetation density'
   unit          'gD/m2'
   value            0.1000000    
end-parameter
parameter 'cTmInitCha'
   description   'temperature for start of season'
   unit          'oC'
   value             10.00000    
end-parameter
parameter 'cDCarrChar'
   description   'max. vegetation biomass'
   unit          'gDW/m2'
   value             500.0000    
end-parameter
parameter 'cMuMaxChar'
   description   'maximum growth rate of vegetation at 20oC'
   unit          'g/g shoot/day'
   value            0.2200000    
end-parameter
parameter 'cQ10ProdCh'
   description   'temperature quotient of production'
   unit          '-'
   value             1.200000    
end-parameter
parameter 'hLRefChar'
   description   'half-sat. light at 20 oC'
   unit          'W/m2 PAR'
   value             19.00000    
end-parameter
parameter 'cExtSpChar'
   description   'specific extinction'
   unit          'm2/gDW'
   value            0.1000000E-01
end-parameter
parameter 'kDRespChar'
   description   'dark respiration rate of vegetation'
   unit          'day-1'
   value            0.2500000E-01
end-parameter
parameter 'cQ10RespCh'
   description   'temperature quotient of respiration'
   unit          '-'
   value             1.200000    
end-parameter
parameter 'cDayWinCha'
   description   'end of growing season  = 16 Sep'
   unit          '-'
   value             259.0000    
end-parameter
parameter 'kMortCharS'
   description   'vegetation mortality rate in Spring and Summer  (l'
   unit          'day-1'
   value            0.5000000E-02
end-parameter
parameter 'fWinChar'
   description   'fraction surviving in winter'
   unit          '-'
   value            0.9000000    
end-parameter
parameter 'fDetWMortC'
   description   'fraction of shoot mortality becoming water detritu'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'cPrefCharB'
   description   'edibility for birds'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'cVPUptMaxC'
   description   'maximum P uptake capacity of vegetation'
   unit          'mgP/mgD/day'
   value            0.1000000E-01
end-parameter
parameter 'cAffPUptCh'
   description   'initial P uptake affinity vegetation'
   unit          'l/mgD/day'
   value            0.2000000    
end-parameter
parameter 'cPDCharMin'
   description   'minimum P/D ratio vegetation'
   unit          'mgP/mg'
   value            0.1200000E-02
end-parameter
parameter 'cPDCharMax'
   description   'Best, 1979'
   unit          '{no unit}'
   value            0.3500000E-02
end-parameter
parameter 'cVNUptMaxC'
   description   'maximum N uptake capacity of vegetation'
   unit          'mgN/mgD/day'
   value            0.1000000    
end-parameter
parameter 'cAffNUptCh'
   description   'initial N uptake affinity vegetation'
   unit          'l/mgD/day'
   value            0.2000000    
end-parameter
parameter 'cNDCharMin'
   description   'minimum N/D ratio vegetation'
   unit          'mgN/mgD'
   value            0.1000000E-01
end-parameter
parameter 'cNDCharMax'
   description   'minimum N/D ratio vegetation (3-4 %, Best 1979)'
   unit          'mgN/mgD'
   value            0.3500000E-01
end-parameter
parameter 'fRootCeraS'
   description   'root fraction in growing season'
   unit          'g root / g veg'
   value             0.000000    
end-parameter
parameter 'fRootCeraW'
   description   'root fraction outside growing season'
   unit          'g root / g veg'
   value             0.000000    
end-parameter
parameter 'fFloatCera'
   description   'floating fraction of shoot'
   unit          'g floating / g shoot'
   value             0.000000    
end-parameter
parameter 'fEmergCera'
   description   'emergent fraction of shoot'
   unit          'g floating / g shoot'
   value             0.000000    
end-parameter
parameter 'fDepth1Cer'
   description   'max. upper depth of submerged veget. layer, as fra'
   unit          '-'
   value             0.000000    
end-parameter
parameter 'fDepth2Cer'
   description   'max. lower depth of submerged veget. layer, as fra'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'cCovSpCera'
   description   'specific cover  Tent.'
   unit          '% cover per gD/m2'
   value            0.5000000    
end-parameter
parameter 'cDLayerCer'
   description   'biomass of a single layer floating leaves'
   unit          'gD/m2'
   value             0.000000    
end-parameter
parameter 'kMigrCera'
   description   'vegetation migration rate'
   unit          'day-1'
   value            0.1000000E-04
end-parameter
parameter 'cDCeraIn'
   description   ' external vegetation density'
   unit          'gD/m2'
   value            0.1000000    
end-parameter
parameter 'cTmInitCer'
   description   'temperature for start of season'
   unit          'oC'
   value             10.00000    
end-parameter
parameter 'cDCarrCera'
   description   'max. vegetation standing crop'
   unit          'gDW/m2'
   value             500.0000    
end-parameter
parameter 'cMuMaxCera'
   description   'maximum growth rate of vegetation at 20oC'
   unit          'g/g shoot/day'
   value            0.2100000    
end-parameter
parameter 'cQ10ProdCe'
   description   'temperature quotient of production'
   unit          '-'
   value             1.500000    
end-parameter
parameter 'hLRefCera'
   description   'half-sat. light at 20 oC'
   unit          'W/m2 PAR'
   value             25.00000    
end-parameter
parameter 'cExtSpCera'
   description   'specific extinction'
   unit          'm2/gDW'
   value            0.1000000E-01
end-parameter
parameter 'kDRespCera'
   description   'dark respiration rate of vegetation'
   unit          'day-1'
   value            0.2400000E-01
end-parameter
parameter 'cQ10RespCe'
   description   'temperature quotient of repiration'
   unit          '-'
   value             2.000000    
end-parameter
parameter 'cDayWinCer'
   description   'end of growing season  = 16 Sep'
   unit          '-'
   value             259.0000    
end-parameter
parameter 'kMortCeraS'
   description   'vegetation mortality rate in Spring and Summer  (l'
   unit          'day-1'
   value            0.5000000E-02
end-parameter
parameter 'fWinCera'
   description   'fraction surviving in winter'
   unit          '-'
   value            0.1000000    
end-parameter
parameter 'fDetWMorta'
   description   'fraction of shoot mortality becoming water detritu'
   unit          '-'
   value            0.5000000    
end-parameter
parameter 'cPrefCeraB'
   description   'edibility for birds'
   unit          '-'
   value             0.000000    
end-parameter
parameter 'cVPUptMaxa'
   description   'maximum P uptake capacity of vegetation'
   unit          'mgP/mgD/day'
   value            0.1000000E-01
end-parameter
parameter 'cAffPUptCe'
   description   'initial P uptake affinity vegetation'
   unit          'l/mgD/day'
   value            0.2000000    
end-parameter
parameter 'cPDCeraMin'
   description   'minimum P/D ratio vegetation'
   unit          'mgP/mg'
   value            0.1200000E-02
end-parameter
parameter 'cPDCeraMax'
   description   'Best 1979'
   unit          '{no unit}'
   value            0.3500000E-02
end-parameter
parameter 'cVNUptMaxa'
   description   'maximum N uptake capacity of vegetation'
   unit          'mgN/mgD/day'
   value            0.1000000    
end-parameter
parameter 'cAffNUptCe'
   description   'initial N uptake affinity vegetation'
   unit          'l/mgD/day'
   value            0.2000000    
end-parameter
parameter 'cNDCeraMin'
   description   'minimum N/D ratio vegetation'
   unit          'mgN/mgD'
   value            0.1000000E-01
end-parameter
parameter 'cNDCeraMax'
   description   'maximum N/D ratio vegetation (3-4 %, Best 1979)'
   unit          'mgN/mgD'
   value            0.3300000E-01
end-parameter
parameter 'fRootLemnS'
   description   'root fraction in growing season'
   unit          'g root / g veg'
   value             0.000000    
end-parameter
parameter 'fRootLemnW'
   description   'root fraction outside growing season'
   unit          'g root / g veg'
   value             0.000000    
end-parameter
parameter 'fFloatLemn'
   description   'floating fraction of shoot'
   unit          'g floating / g shoot'
   value             1.000000    
end-parameter
parameter 'fEmergLemn'
   description   'emergent fraction of shoot'
   unit          'g emergent / g shoot'
   value             0.000000    
end-parameter
parameter 'fDepth1Lem'
   description   'max. upper depth of submerged veget. layer, as fra'
   unit          '-'
   value             0.000000    
end-parameter
parameter 'fDepth2Lem'
   description   'max. lower depth of submerged veget. layer, as fra'
   unit          '-'
   value             0.000000    
end-parameter
parameter 'cCovSpLemn'
   description   'specific cover  Tent.'
   unit          '% cover per gD/m2'
   value             1.000000    
end-parameter
parameter 'cDLayerLem'
   description   'biomass of a single layer floating leaves'
   unit          'gD/m2'
   value             100.0000    
end-parameter
parameter 'cTmInitLem'
   description   'temperature for start of season'
   unit          'oC'
   value             10.00000    
end-parameter
parameter 'cDCarrLemn'
   description   'max. vegetation standing crop'
   unit          'gDW/m2'
   value             575.0000    
end-parameter
parameter 'cMuMaxLemn'
   description   'maximum growth rate at 20oC'
   unit          'g/g shoot/day'
   value            0.4000000    
end-parameter
parameter 'cQ10ProdLe'
   description   'temperature quotient of production'
   unit          '-'
   value             2.500000    
end-parameter
parameter 'hLRefLemn'
   description   'half-sat. light at 20 oC (n.a.) (STOWA 1992: 15 W/'
   unit          'W/m2 PAR'
   value             7.500000    
end-parameter
parameter 'cExtSpLemn'
   description   'specific extinction (not appl.)'
   unit          'm2/gDW'
   value            0.1000000E-01
end-parameter
parameter 'ckMigrLemn'
   description   'vegetation migration rate'
   unit          'day-1'
   value            0.1000000E-04
end-parameter
parameter 'cDLemnIn'
   description   ' external vegetation density'
   unit          'gD/m2'
   value            0.1000000    
end-parameter
parameter 'kDRespLemn'
   description   'dark respiration rate of vegetation'
   unit          'day-1'
   value            0.3000000E-01
end-parameter
parameter 'cQ10RespLe'
   description   'temperature quotient of respiration'
   unit          '-'
   value             3.000000    
end-parameter
parameter 'cDayWinLem'
   description   'end of growing season  = 16 Oct'
   unit          '-'
   value             289.0000    
end-parameter
parameter 'kMortLemnS'
   description   'vegetation mortality rate in Spring and Summer  (l'
   unit          'day-1'
   value            0.2000000E-01
end-parameter
parameter 'fWinLemn'
   description   'fraction surviving in winter'
   unit          '-'
   value            0.2000000    
end-parameter
parameter 'fDetWMortL'
   description   'fraction of shoot mortality becoming water detritu'
   unit          '-'
   value            0.8000000    
end-parameter
parameter 'cPrefLemnB'
   description   'edibility for birds'
   unit          '-'
   value             0.000000    
end-parameter
parameter 'cVPUptMaxL'
   description   'maximum P uptake capacity of vegetation'
   unit          'mgP/mgD/day'
   value            0.5000000E-02
end-parameter
parameter 'cAffPUptLe'
   description   'initial P uptake affinity vegetation'
   unit          'l/mgD/day'
   value            0.2000000E-01
end-parameter
parameter 'cPDLemnMin'
   description   'minimum P/D ratio vegetation'
   unit          'mgP/mgD'
   value            0.4000000E-02
end-parameter
parameter 'cPDLemnMax'
   description   'maximum P/D ratio vegetation'
   unit          'mgP/mgD'
   value            0.2600000E-01
end-parameter
parameter 'cVNUptMaxL'
   description   'maximum N uptake capacity of vegetation'
   unit          'mgN/mgD/day'
   value            0.5000000E-01
end-parameter
parameter 'cAffNUptLe'
   description   'initial N uptake affinity vegetation'
   unit          'l/mgD/day'
   value            0.2000000E-01
end-parameter
parameter 'cNDLemnMin'
   description   'Stowa 92-09, p 5'
   unit          '{no unit}'
   value            0.4000000E-01
end-parameter
parameter 'cNDLemnMax'
   description   'Stowa 92-09, p 5'
   unit          '{no unit}'
   value            0.1000000    
end-parameter
parameter 'fRootNympS'
   description   'root fraction in growing season (Wetzel 1983, p 54'
   unit          'g root / g veg'
   value            0.7500000    
end-parameter
parameter 'fRootNympW'
   description   'root fraction outside growing season'
   unit          'g root / g veg'
   value            0.9500000    
end-parameter
parameter 'fFloatNymp'
   description   'floating fraction of shoot'
   unit          'g floating / g shoot'
   value             1.000000    
end-parameter
parameter 'fEmergNymp'
   description   'emergent fraction of shoot'
   unit          'g floating / g shoot'
   value             0.000000    
end-parameter
parameter 'fDepth1Nym'
   description   'max. upper depth of submerged veget. layer, as fra'
   unit          '-'
   value             0.000000    
end-parameter
parameter 'fDepth2Nym'
   description   'max. upper depth of submerged veget. layer, as fra'
   unit          '-'
   value             0.000000    
end-parameter
parameter 'cCovSpNymp'
   description   'specific cover  Tent.'
   unit          '% cover per gD/m2'
   value            0.5000000    
end-parameter
parameter 'cDLayerNym'
   description   'biomass of a single layer floating leaves'
   unit          'gD/m2'
   value             100.0000    
end-parameter
parameter 'kMigrNymp'
   description   'vegetation migration rate'
   unit          'day-1'
   value            0.1000000E-04
end-parameter
parameter 'cDNympIn'
   description   ' external vegetation density'
   unit          'gD/m2'
   value            0.1000000    
end-parameter
parameter 'cTmInitNym'
   description   'temperature for start of season'
   unit          'oC'
   value             10.00000    
end-parameter
parameter 'cDCarrNymp'
   description   'max. vegetation standing crop'
   unit          'gDW/m2'
   value             500.0000    
end-parameter
parameter 'cMuMaxNymp'
   description   'maximum growth rate of vegetation at 20oC'
   unit          'g/g shoot/day'
   value            0.1000000    
end-parameter
parameter 'cQ10ProdNy'
   description   'temperature quotient of production'
   unit          '-'
   value             1.500000    
end-parameter
parameter 'hLRefNymp'
   description   'half-sat. light at 20 oC  (n.a.)'
   unit          'W/m2 PAR'
   value             25.00000    
end-parameter
parameter 'cExtSpNymp'
   description   'specific extinction   (n.a.)'
   unit          'm2/gDW'
   value            0.1000000E-01
end-parameter
parameter 'kDRespNymp'
   description   'dark respiration rate of vegetation'
   unit          'day-1'
   value            0.1000000E-01
end-parameter
parameter 'cQ10RespNy'
   description   'temperature quotient of respiration'
   unit          '-'
   value             2.000000    
end-parameter
parameter 'cDayWinNym'
   description   'end of growing season  = 16 Sep'
   unit          '-'
   value             259.0000    
end-parameter
parameter 'kMortNympS'
   description   'vegetation mortality rate in Spring and Summer  (l'
   unit          'day-1'
   value            0.5000000E-02
end-parameter
parameter 'fWinNymp'
   description   'fraction surviving in winter'
   unit          '-'
   value            0.3330000    
end-parameter
parameter 'fDetWMortN'
   description   'fraction of shoot mortality becoming water detritu'
   unit          '-'
   value            0.2500000    
end-parameter
parameter 'cPrefNympB'
   description   'edibility for birds'
   unit          '-'
   value             0.000000    
end-parameter
parameter 'cVPUptMaxN'
   description   'maximum P uptake capacity of vegetation'
   unit          'mgP/mgD/day'
   value            0.1000000E-01
end-parameter
parameter 'cAffPUptNy'
   description   'initial P uptake affinity vegetation'
   unit          'l/mgD/day'
   value            0.2000000    
end-parameter
parameter 'cPDNympMin'
   description   'minimum P/D ratio vegetation'
   unit          'mgP/mg'
   value            0.1000000E-02
end-parameter
parameter 'cPDNympMax'
   description   'maximum P/D ratio vegetation'
   unit          'mgP/mgD'
   value            0.7500000E-02
end-parameter
parameter 'cVNUptMaxN'
   description   'maximum N uptake capacity of vegetation'
   unit          'mgN/mgD/day'
   value            0.1000000    
end-parameter
parameter 'cAffNUptNy'
   description   'initial N uptake affinity vegetation'
   unit          'l/mgD/day'
   value            0.2000000    
end-parameter
parameter 'cNDNympMin'
   description   'minimum N/D ratio vegetation'
   unit          'mgN/mgD'
   value            0.1000000E-01
end-parameter
parameter 'cNDNympMax'
   description   'maximum N/D ratio vegetation'
   unit          'mgN/mgD'
   value            0.3000000E-01
end-parameter
parameter 'fRootHeloS'
   description   'root fraction in growing season (Wetzel 1983, p 54'
   unit          'g root / g veg'
   value            0.5000000    
end-parameter
parameter 'fRootHeloW'
   description   'root fraction outside growing season'
   unit          'g root / g veg'
   value            0.8000000    
end-parameter
parameter 'fFloatHelo'
   description   'floating fraction of shoot'
   unit          'g floating / g shoot'
   value             0.000000    
end-parameter
parameter 'fEmergHelo'
   description   'emergent fraction of shoot'
   unit          'g floating / g shoot'
   value             1.000000    
end-parameter
parameter 'fDepth1Hel'
   description   'max. upper depth of submerged veget. layer, as fra'
   unit          '-'
   value             0.000000    
end-parameter
parameter 'fDepth2Hel'
   description   'max. upper depth of submerged veget. layer, as fra'
   unit          '-'
   value             0.000000    
end-parameter
parameter 'cDCarrHelo'
   description   'max. vegetation standing crop'
   unit          'gDW/m2'
   value             2000.000    
end-parameter
parameter 'cCovSpHelo'
   description   'specific cover  Tent.'
   unit          '% cover per gD/m2'
   value            0.5000000E-01
end-parameter
parameter 'cDLayerHel'
   description   'biomass of a single layer floating leaves m2/gDW'
   unit          'gD/m2'
   value             0.000000    
end-parameter
parameter 'kMigrHelo'
   description   'vegetation migration rate'
   unit          'day-1'
   value            0.1000000E-04
end-parameter
parameter 'cDHeloIn'
   description   ' external vegetation density'
   unit          'gD/m2'
   value            0.1000000    
end-parameter
parameter 'cTmInitHel'
   description   'temperature for start of season'
   unit          'oC'
   value             10.00000    
end-parameter
parameter 'cMuMaxHelo'
   description   'maximum growth rate of vegetation at 20oC'
   unit          'g/g shoot/day'
   value            0.1000000    
end-parameter
parameter 'cQ10ProdHe'
   description   'temperature quotient of production'
   unit          '-'
   value             1.500000    
end-parameter
parameter 'hLRefHelo'
   description   'half-sat. light at 20 oC  (n.a.)'
   unit          'W/m2 PAR'
   value             25.00000    
end-parameter
parameter 'cExtSpHelo'
   description   'specific extinction   (n.a.)'
   unit          'm2/gDW'
   value            0.1000000E-01
end-parameter
parameter 'kDRespHelo'
   description   'dark respiration rate of vegetation'
   unit          'day-1'
   value            0.1000000E-01
end-parameter
parameter 'cQ10RespHe'
   description   'temperature quotient of respiration'
   unit          '-'
   value             2.000000    
end-parameter
parameter 'cDayWinHel'
   description   'end of growing season  = 16 Sep'
   unit          '-'
   value             259.0000    
end-parameter
parameter 'kMortHeloS'
   description   'vegetation mortality rate in Spring and Summer  (l'
   unit          'day-1'
   value            0.5000000E-02
end-parameter
parameter 'fWinHelo'
   description   'fraction surviving in winter'
   unit          '-'
   value            0.3330000    
end-parameter
parameter 'fDetWMortH'
   description   'fraction of shoot mortality becoming water detritu'
   unit          '-'
   value            0.2500000    
end-parameter
parameter 'cPrefHeloB'
   description   'edibility for birds'
   unit          '-'
   value             0.000000    
end-parameter
parameter 'cVPUptMaxH'
   description   'maximum P uptake capacity of vegetation'
   unit          'mgP/mgD/day'
   value            0.1000000E-01
end-parameter
parameter 'cAffPUptHe'
   description   'initial P uptake affinity vegetation'
   unit          'l/mgD/day'
   value            0.2000000    
end-parameter
parameter 'cPDHeloMin'
   description   'minimum P/D ratio vegetation'
   unit          'mgP/mg'
   value            0.1000000E-02
end-parameter
parameter 'cPDHeloMax'
   description   'maximum P/D ratio vegetation'
   unit          'mgP/mgD'
   value            0.7500000E-02
end-parameter
parameter 'cVNUptMaxH'
   description   'maximum N uptake capacity of vegetation'
   unit          'mgN/mgD/day'
   value            0.1000000    
end-parameter
parameter 'cAffNUptHe'
   description   'initial N uptake affinity vegetation'
   unit          'l/mgD/day'
   value            0.2000000    
end-parameter
parameter 'cNDHeloMin'
   description   'minimum N/D ratio vegetation'
   unit          'mgN/mgD'
   value            0.1000000E-01
end-parameter
parameter 'cNDHeloMax'
   description   'maximum N/D ratio vegetation'
   unit          'mgN/mgD'
   value            0.3000000E-01
end-parameter
parameter 'cPACoefMin'
   description   'minimum Poole-Atkins coefficient'
   unit          '-'
   value             1.500000    
end-parameter
parameter 'cPACoefMax'
   description   'maximum Poole-Atkins coefficient'
   unit          '-'
   value             2.500000    
end-parameter
parameter 'hPACoef'
   description   'decrease constant for P.A. coeff. with DOMW'
   unit          'g/m2'
   value             3.000000    
end-parameter
parameter 'cSecchiPlu'
   description   'maximum Secchi depth above water depth'
   unit          'm'
   value             0.000000    
end-parameter
parameter 'cEuph'
   description   'conversion constant Secchi depth -> euphotic depth'
   unit          '-'
   value             1.700000    
end-parameter
parameter 'cCovSpPhyt'
   description   'specific coverage  Tentative'
   unit          '% per gD/m2'
   value             2.000000    
end-parameter
parameter 'cTmOptLoss'
   description   'optimum temp. for grazing'
   unit          'oC'
   value             25.00000    
end-parameter
parameter 'cSigTmLoss'
   description   'temperature constant of grazing(sigma in Gaussian'
   unit          'oC'
   value             13.00000    
end-parameter
parameter 'fDissMortP'
   description   'soluble nutrient fraction of died Algae'
   unit          '-'
   value            0.2000000    
end-parameter
parameter 'fDissLoss'
   description   'dissolved nutrient fraction of grazing loss'
   unit          '-'
   value            0.2500000    
end-parameter
parameter 'cMuMaxPhyt'
   description   'maximum growth rate algae'
   unit          'day-1'
   value             1.900000    
end-parameter
parameter 'cTmOptPhyt'
   description   'optimum temp. of algae'
   unit          'oC'
   value             25.00000    
end-parameter
parameter 'cSigTmPhyt'
   description   'temperature constant greens(sigma in Gaussian curv'
   unit          'oC'
   value             15.00000    
end-parameter
parameter 'cExtSpPhyt'
   description   'specific extinction algae'
   unit          'm2/gDW'
   value            0.2500000    
end-parameter
parameter 'UseSteeleP'
   description   ' Flag : 1 = use Steele function,0 = use Lehman fun'
   unit          '{no unit}'
   value             0.000000    
end-parameter
parameter 'hLRefPhyt'
   description   'half-sat. PAR for algae at 20 oC(Lehmann function)'
   unit          'W/m2'
   value             10.20000    
end-parameter
parameter 'cLOptRefPh'
   description   'optimum PAR at 20 oC(Steele function)    Fake valu'
   unit          'W/m2'
   value             1000.000    
end-parameter
parameter 'cChDPhytMi'
   description   'min. chlorophyll/C ratio algae'
   unit          'mgChl/mgDW'
   value            0.1000000E-01
end-parameter
parameter 'cChDPhytMa'
   description   'max. chlorophyll/C ratio algae'
   unit          'mgChl/mgDW'
   value            0.2000000E-01
end-parameter
parameter 'kDRespPhyt'
   description   'maintenance respiration constant greens'
   unit          'day-1'
   value            0.1000000    
end-parameter
parameter 'kLossPhyt'
   description   'grazing loss rate for algae'
   unit          '-'
   value             0.000000    
end-parameter
parameter 'kMortPhytW'
   description   'mortality constant of algae in water'
   unit          'day-1'
   value            0.1000000E-01
end-parameter
parameter 'cVSetPhyt'
   description   'sedimentation velocity algae'
   unit          'm/day'
   value            0.1000000    
end-parameter
parameter 'kMortPhytS'
   description   'mortality constant algae'
   unit          'day-1'
   value            0.5000000E-01
end-parameter
parameter 'cVPUptMaxP'
   description   'maximum P uptake capacity of algae'
   unit          'mgP/mgDW/day'
   value            0.1000000E-01
end-parameter
parameter 'cAffPUptPh'
   description   'initial P uptake affinity algae'
   unit          'l/mgDW/day'
   value            0.2000000    
end-parameter
parameter 'cPDPhytMin'
   description   'minimum P/D ratio algae'
   unit          'mgP/mgDW'
   value            0.2000000E-02
end-parameter
parameter 'cPDPhytMax'
   description   'max. P/D ratio algae'
   unit          'mgP/mgDW'
   value            0.1500000E-01
end-parameter
parameter 'cVNUptMaxP'
   description   'maximum N uptake capacity of algae'
   unit          'mgN/mgDW/day'
   value            0.7000000E-01
end-parameter
parameter 'cAffNUptPh'
   description   'initial N uptake affinity algae'
   unit          'l/mgDW/day'
   value            0.2000000    
end-parameter
parameter 'cNDPhytMin'
   description   'minimum N/D ratio algae'
   unit          'mgN/mgDW'
   value            0.2000000E-01
end-parameter
parameter 'cNDPhytMax'
   description   'max. N/D ratio algae'
   unit          'mgN/mgDW'
   value            0.1000000    
end-parameter
parameter 'hSiAssPhyt'
   description   'half-sat. Si conc. for growth of algae   = 0'
   unit          'mgSi/l'
   value             0.000000    
end-parameter
parameter 'mTemp'
   description   'water temperature'
   unit          'oC'
   value             20.00000    
end-parameter
parameter 'mLOut'
   description   'light'
   unit          'W/m2'
   value             500.0000    
end-parameter
parameter 'mVWind'
   description   'wind speed'
   unit          'm/s'
   value             5.000000    
end-parameter
output 'Z'
   description   'water depth'
end-output
output 'Q'
   description   'Flow'
end-output
output 'As'
   description   'Flow area'
end-output
output 'dt'
   description   'Quality time step'
end-output
output 'dx'
   description   'Half of the length of section'
end-output
output 'V'
   description   'Half of the volume of section'
end-output
output 'Wf'
   description   'Wind velocity'
end-output
output 'Wd'
   description   'Wind direction'
end-output
output 'sDepthW'
   description   ' Z'
end-output
output 'DaysPerYea'
   description   ' 365.0'
end-output
output 'TenDays'
   description   ' 10.0'
end-output
output 'HoursPerDa'
   description   ' 24.0'
end-output
output 'SecsPerDay'
   description   ' 86400.0'
end-output
output 'mmPerm'
   description   ' 1000.0'
end-output
output 'm2Perha'
   description   ' 10000.0'
end-output
output 'mgPerg'
   description   ' 1000.0'
end-output
output 'gPerkg'
   description   ' 1000.0'
end-output
output 'gPerton'
   description   ' 1000000.0'
end-output
output 'PerCent'
   description   ' 0.01'
end-output
output 'NearZero'
   description   ' 0.000000000000000000000000000000001'
end-output
output 'molO2molC'
   description   ' 2.6667'
end-output
output 'molO2molN'
   description   ' 2.2857'
end-output
output 'molNmolC'
   description   ' 1.1667'
end-output
output 'cRhoWat'
   description   ' 1000000.0'
end-output
output 'Pi'
   description   ' 2.0*ASIN(1.0)'
end-output
output 'sPDetW0'
   description   ' cPDDet0 * sDDetW0'
end-output
output 'sNDetW0'
   description   ' cNDDet0 * sDDetW0'
end-output
output 'sSiDetW0'
   description   ' cSiDDet0 * sDDetW0'
end-output
output 'bRhoSolidS'
   description   ' fDOrgS0 * cRhoOM + (1 - fDOrgS0) * cRhoIM'
end-output
output 'bPorS'
   description   ' (1.0 - fDTotS0) * bRhoSolidS0 / cRhoWat / ( fDTot'
end-output
output 'bPorCorS'
   description   ' bPorS ** (bPorS + 1.0)'
end-output
output 'bRhoTotS0'
   description   ' bRhoSolidS0 * (1.0 - bPorS)'
end-output
output 'bDTotS0'
   description   ' bRhoTotS0 * cDepthS'
end-output
output 'sDHumS0'
   description   ' (1.0 - fDDetS0) * fDOrgS0 * bDTotS0'
end-output
output 'sDDetS0'
   description   ' fDDetS0 * fDOrgS0 * bDTotS0'
end-output
output 'sDIMS0'
   description   ' bDTotS0 - sDHumS0 - sDDetS0'
end-output
output 'sPHumS0'
   description   ' cPDHum0 * sDHumS0'
end-output
output 'sNHumS0'
   description   ' cNDHum0 * sDHumS0'
end-output
output 'sPDetS0'
   description   ' cPDDet0 * sDDetS0'
end-output
output 'sNDetS0'
   description   ' cNDDet0 * sDDetS0'
end-output
output 'sSiDetS0'
   description   ' cSiDDet0 * sDDetS0'
end-output
output 'sPAIMS0'
   description   ' fPAdsS0 * fPInorgS0 * bDTotS0'
end-output
output 'sPO4S0'
   description   ' (1.0 - fPAdsS0) * fPInorgS0 * bDTotS0'
end-output
output 'sPPhytW0'
   description   ' cPDPhyt0 * sDPhytW0'
end-output
output 'sNPhytW0'
   description   ' cNDPhyt0 * sDPhytW0'
end-output
output 'sPPhytS0'
   description   ' cPDPhyt0 * sDPhytS0'
end-output
output 'sNPhytS0'
   description   ' cNDPhyt0 * sDPhytS0'
end-output
output 'sPChar0'
   description   ' cPDChar0 * sDChar0'
end-output
output 'sNChar0'
   description   ' cNDChar0 * sDChar0'
end-output
output 'sPElod0'
   description   ' cPDElod0 * sDElod0'
end-output
output 'sNElod0'
   description   ' cNDElod0 * sDElod0'
end-output
output 'sPCera0'
   description   ' cPDCera0 * sDCera0'
end-output
output 'sNCera0'
   description   ' cNDCera0 * sDCera0'
end-output
output 'sPLemn0'
   description   ' cPDLemn0 * sDLemn0'
end-output
output 'sNLemn0'
   description   ' cNDLemn0 * sDLemn0'
end-output
output 'sPNymp0'
   description   ' cPDNymp0 * sDNymp0'
end-output
output 'sNNymp0'
   description   ' cNDNymp0 * sDNymp0'
end-output
output 'sPHelo0'
   description   ' cPDHelo0 * sDHelo0'
end-output
output 'sNHelo0'
   description   ' cNDHelo0 * sDHelo0'
end-output
output 'uDPhytW0'
   description   ' sDPhytW0'
end-output
output 'uPPhytW0'
   description   ' sPPhytW0'
end-output
output 'uNPhytW0'
   description   ' sNPhytW0'
end-output
output 'uDPhytS0'
   description   ' sDPhytS0'
end-output
output 'uPPhytS0'
   description   ' sPPhytS0'
end-output
output 'uNPhytS0'
   description   ' sNPhytS0'
end-output
output 'uDVeg0'
   description   ' sDElod0 + sDChar0 + sDCera0  + sDLemn0 + sDNymp0'
end-output
output 'uPVeg0'
   description   ' sPElod0 + sPChar0 + sPCera0  + sPLemn0 + sPNymp0'
end-output
output 'uNVeg0'
   description   ' sNElod0 + sNChar0 + sNCera0  + sNLemn0 + sNNymp0'
end-output
output 'uDTotM0'
   description   ' 0.0'
end-output
output 'uPTotM0'
   description   ' 0.0'
end-output
output 'uNTotM0'
   description   ' 0.0'
end-output
output 'uSiTotM0'
   description   ' 0.0'
end-output
output 'uDTotT0'
   description   ' (sDIMW0 + sDDetW0 + uDPhytW0) * sDepthW    + uDVe'
end-output
output 'uPTotT0'
   description   ' (sPO4W0 + sPDetW0 + sPAIMW0 + uPPhytW0)   * sDept'
end-output
output 'uNTotT0'
   description   ' (sNH4W0 + sNO3W0 + sNDetW0 + uNPhytW0) * sDepthW'
end-output
output 'ukOut'
   description   ' 0.0'
end-output
output 'vTranDepth'
   description   ' 0.0'
end-output
output 'wDTranIMW'
   description   ' 0.0'
end-output
output 'wDTranDetW'
   description   ' 0.0'
end-output
output 'wDTranPhyt'
   description   ' 0.0'
end-output
output 'wDTranZoo'
   description   ' 0.0'
end-output
output 'tDTranTotT'
   description   ' 0.0'
end-output
output 'wO2TranW'
   description   ' 0.0'
end-output
output 'wPTranPO4W'
   description   ' 0.0'
end-output
output 'wPTranAIMW'
   description   ' 0.0'
end-output
output 'wPTranDetW'
   description   ' 0.0'
end-output
output 'wPTranPhyt'
   description   ' 0.0'
end-output
output 'wPTranZoo'
   description   ' 0.0'
end-output
output 'tPTranTotT'
   description   ' 0.0'
end-output
output 'wNTranNH4W'
   description   ' 0.0'
end-output
output 'wNTranNO3W'
   description   ' 0.0'
end-output
output 'wNTranDetW'
   description   ' 0.0'
end-output
output 'wNTranPhyt'
   description   ' 0.0'
end-output
output 'wNTranZoo'
   description   ' 0.0'
end-output
output 'tNTranTotT'
   description   ' 0.0'
end-output
output 'wSiTranSiO'
   description   ' 0.0'
end-output
output 'wSiTranDet'
   description   ' 0.0'
end-output
output 'tSiTranTot'
   description   ' 0.0'
end-output
output 'wDTranBlue'
   description   ' 0.0'
end-output
output 'wPTranBlue'
   description   ' 0.0'
end-output
output 'wNTranBlue'
   description   ' 0.0'
end-output
output 'wDTranGren'
   description   ' 0.0'
end-output
output 'wPTranGren'
   description   ' 0.0'
end-output
output 'wNTranGren'
   description   ' 0.0'
end-output
output 'wDTranDiat'
   description   ' 0.0'
end-output
output 'wPTranDiat'
   description   ' 0.0'
end-output
output 'wNTranDiat'
   description   ' 0.0'
end-output
output 'wDWebIMW'
   description   ' 0.0'
end-output
output 'wDWebDetW'
   description   ' 0.0'
end-output
output 'tDWebTotT'
   description   ' 0.0'
end-output
output 'wPWebPO4W'
   description   ' 0.0'
end-output
output 'wPWebAIMW'
   description   ' 0.0'
end-output
output 'wPWebDetW'
   description   ' 0.0'
end-output
output 'tPWebTotT'
   description   ' 0.0'
end-output
output 'wNWebNH4W'
   description   ' 0.0'
end-output
output 'wNWebNO3W'
   description   ' 0.0'
end-output
output 'wNWebDetW'
   description   ' 0.0'
end-output
output 'tNWebTotT'
   description   ' 0.0'
end-output
output 'wSiWebDetW'
   description   ' 0.0'
end-output
output 'wDWebPhytW'
   description   ' 0.0'
end-output
output 'wPWebPhytW'
   description   ' 0.0'
end-output
output 'wNWebPhytW'
   description   ' 0.0'
end-output
output 'wDWebBlueW'
   description   ' 0.0'
end-output
output 'wPWebBlueW'
   description   ' 0.0'
end-output
output 'wNWebBlueW'
   description   ' 0.0'
end-output
output 'wDWebGrenW'
   description   ' 0.0'
end-output
output 'wPWebGrenW'
   description   ' 0.0'
end-output
output 'wNWebGrenW'
   description   ' 0.0'
end-output
output 'wDWebDiatW'
   description   ' 0.0'
end-output
output 'wPWebDiatW'
   description   ' 0.0'
end-output
output 'wNWebDiatW'
   description   ' 0.0'
end-output
output 'tDWebDetS'
   description   ' 0.0'
end-output
output 'tPWebPO4S'
   description   ' 0.0'
end-output
output 'tPWebAIMS'
   description   ' 0.0'
end-output
output 'tPWebDetS'
   description   ' 0.0'
end-output
output 'tNWebNH4S'
   description   ' 0.0'
end-output
output 'tNWebNO3S'
   description   ' 0.0'
end-output
output 'tNWebDetS'
   description   ' 0.0'
end-output
output 'tSiWebDetS'
   description   ' 0.0'
end-output
output 'tSiWebTotT'
   description   ' 0.0'
end-output
output 'tDWebPhytS'
   description   ' 0.0'
end-output
output 'tPWebPhytS'
   description   ' 0.0'
end-output
output 'tNWebPhytS'
   description   ' 0.0'
end-output
output 'tDWebBlueS'
   description   ' 0.0'
end-output
output 'tPWebBlueS'
   description   ' 0.0'
end-output
output 'tNWebBlueS'
   description   ' 0.0'
end-output
output 'tDWebGrenS'
   description   ' 0.0'
end-output
output 'tPWebGrenS'
   description   ' 0.0'
end-output
output 'tNWebGrenS'
   description   ' 0.0'
end-output
output 'tDWebDiatS'
   description   ' 0.0'
end-output
output 'tPWebDiatS'
   description   ' 0.0'
end-output
output 'tNWebDiatS'
   description   ' 0.0'
end-output
output 'wDExchIM'
   description   ' 0.0'
end-output
output 'wDExchDet'
   description   ' 0.0'
end-output
output 'wO2Exch'
   description   ' 0.0'
end-output
output 'wPExchPO4'
   description   ' 0.0'
end-output
output 'wPExchDet'
   description   ' 0.0'
end-output
output 'wPExchAIM'
   description   ' 0.0'
end-output
output 'wNExchNH4'
   description   ' 0.0'
end-output
output 'wNExchNO3'
   description   ' 0.0'
end-output
output 'wNExchDet'
   description   ' 0.0'
end-output
output 'wDExchPhyt'
   description   ' 0.0'
end-output
output 'wPExchPhyt'
   description   ' 0.0'
end-output
output 'wNExchPhyt'
   description   ' 0.0'
end-output
output 'wDExchDiat'
   description   ' 0.0'
end-output
output 'wPExchDiat'
   description   ' 0.0'
end-output
output 'wNExchDiat'
   description   ' 0.0'
end-output
output 'wSiExchDia'
   description   ' 0.0'
end-output
output 'wDExchGren'
   description   ' 0.0'
end-output
output 'wPExchGren'
   description   ' 0.0'
end-output
output 'wNExchGren'
   description   ' 0.0'
end-output
output 'wDExchBlue'
   description   ' 0.0'
end-output
output 'wPExchBlue'
   description   ' 0.0'
end-output
output 'wNExchBlue'
   description   ' 0.0'
end-output
output 'wSiExchDet'
   description   ' 0.0'
end-output
output 'wSiExchSiO'
   description   ' 0.0'
end-output
output 'wDExchZoo'
   description   ' 0.0'
end-output
output 'wPExchZoo'
   description   ' 0.0'
end-output
output 'wNExchZoo'
   description   ' 0.0'
end-output
output 'aDTotM'
   description   ' 0.0'
end-output
output 'aPTotM'
   description   ' 0.0'
end-output
output 'aNTotM'
   description   ' 0.0'
end-output
output 'aSiTotM'
   description   ' 0.0'
end-output
output 'tDMarsTotT'
   description   ' 0.0'
end-output
output 'tPMarsTotT'
   description   ' 0.0'
end-output
output 'tNMarsTotT'
   description   ' 0.0'
end-output
output 'tSiMarsTot'
   description   ' 0.0'
end-output
output 'TimeYears'
   description   ' Time / DaysPerYear'
end-output
output 'Day'
   description   ' Time - INT(TimeYears) * DaysPerYear'
end-output
output 'Years'
   description   ' YearZero + TimeYears'
end-output
output 'uTm'
   description   ' mTemp'
end-output
output 'uVWind'
   description   ' cVWind'
end-output
output 'ufDay'
   description   ' cfDayAve - cfDayVar * COS(2.0*Pi*(Time+TenDays) /'
end-output
output 'uLOut'
   description   ' mLOut / ufDay'
end-output
output 'uLDay'
   description   ' cLDayAve - cLDayVar * COS(2.0*Pi*(Time+TenDays)'
end-output
output 'uLPAR0'
   description   '  fPAR * (1.0 - fRefl) * uLOut'
end-output
output 'aExtPhyt'
   description   ' cExtSpPhyt * sDPhytW'
end-output
output 'aExtDet'
   description   ' cExtSpDet * sDDetW'
end-output
output 'aExtIM'
   description   ' cExtSpIM * sDIMW'
end-output
output 'aExtCoefOp'
   description   ' cExtWat + aExtIM + aExtDet + aExtPhyt'
end-output
output 'oDPhytW'
   description   ' sDPhytW'
end-output
output 'oPPhytW'
   description   ' sPPhytW'
end-output
output 'oNPhytW'
   description   ' sNPhytW'
end-output
output 'aDPhytS'
   description   ' sDPhytS'
end-output
output 'aPPhytS'
   description   ' sPPhytS'
end-output
output 'aNPhytS'
   description   ' sNPhytS'
end-output
output 'oDOMW'
   description   ' sDDetW + oDPhytW'
end-output
output 'oDSestW'
   description   ' oDOMW + sDIMW'
end-output
output 'oPOMW'
   description   ' oPPhytW + sPDetW'
end-output
output 'oPSestW'
   description   ' oPPhytW + sPDetW + sPAIMW'
end-output
output 'oPInorgW'
   description   ' sPO4W + sPAIMW'
end-output
output 'oPTotW'
   description   ' oPSestW + sPO4W'
end-output
output 'oNDissW'
   description   ' sNO3W + sNH4W'
end-output
output 'oNOMW'
   description   ' oNPhytW + sNDetW'
end-output
output 'oNSestW'
   description   ' oNOMW'
end-output
output 'oNkjW'
   description   ' oNSestW + sNH4W'
end-output
output 'oNTotW'
   description   ' oNkjW + sNO3W'
end-output
output 'aDTotS'
   description   ' sDIMS + sDHumS + sDDetS'
end-output
output 'aRhoTotS'
   description   ' aDTotS / cDepthS'
end-output
output 'aRhoSolidS'
   description   ' (sDIMS * cRhoIM + (sDHumS + sDDetS) * cRhoOM) / a'
end-output
output 'afDTotS'
   description   ' 1.0 / (1.0 + bPorS/(1.0-bPorS) * cRhoWat / aRhoSo'
end-output
output 'afDOrgS'
   description   ' (sDHumS + sDDetS) / aDTotS'
end-output
output 'afDetS'
   description   ' sDDetS / (sDHumS + sDDetS)'
end-output
output 'afDetTotS'
   description   ' sDDetS / (sDIMS + sDHumS + sDDetS)'
end-output
output 'aPInorgS'
   description   ' sPO4S + sPAIMS'
end-output
output 'aPTotAvail'
   description   ' sPDetS + aPInorgS + aPPhytS'
end-output
output 'aPTotS'
   description   ' aPTotAvailS + sPHumS'
end-output
output 'afPInorgS'
   description   ' aPInorgS / aDTotS'
end-output
output 'afPTotS'
   description   ' aPTotS / aDTotS'
end-output
output 'afPO4S'
   description   ' sPO4S / (aPTotAvailS + NearZero)'
end-output
output 'oPO4S'
   description   ' sPO4S / cDepthS / bPorS'
end-output
output 'aNDissS'
   description   ' sNH4S + sNO3S'
end-output
output 'aNkjAvailS'
   description   ' sNDetS + aNPhytS + sNH4S'
end-output
output 'aNkjS'
   description   ' aNkjAvailS + sNHumS'
end-output
output 'aNTotAvail'
   description   ' aNkjAvailS + sNO3S'
end-output
output 'aNTotS'
   description   ' aNkjS + sNO3S'
end-output
output 'afNInorgS'
   description   ' aNDissS / aDTotS'
end-output
output 'afNTotS'
   description   ' aNTotS / aDTotS'
end-output
output 'oNO3S'
   description   ' sNO3S / cDepthS / bPorS'
end-output
output 'oNH4S'
   description   ' sNH4S / cDepthS / bPorS'
end-output
output 'oNDissS'
   description   ' aNDissS / cDepthS / bPorS'
end-output
output 'rPDIMW'
   description   ' sPAIMW / sDIMW'
end-output
output 'rPDIMS'
   description   ' sPAIMS / sDIMS'
end-output
output 'rPDDetW'
   description   ' sPDetW / (sDDetW+NearZero)'
end-output
output 'rNDDetW'
   description   ' sNDetW / (sDDetW+NearZero)'
end-output
output 'rPDHumS'
   description   ' sPHumS / (sDHumS+NearZero)'
end-output
output 'rNDHumS'
   description   ' sNHumS / (sDHumS+NearZero)'
end-output
output 'rPDDetS'
   description   ' sPDetS / (sDDetS+NearZero)'
end-output
output 'rNDDetS'
   description   ' sNDetS / (sDDetS+NearZero)'
end-output
output 'tPInfPO4W'
   description   ' cQInf / mmPerm * sPO4W'
end-output
output 'tNInfNH4W'
   description   ' cQInf / mmPerm * sNH4W'
end-output
output 'tNInfNO3W'
   description   ' cQInf / mmPerm * sNO3W'
end-output
output 'tPInfPO4S'
   description   ' cQInf / mmPerm * oPO4S'
end-output
output 'tNInfNH4S'
   description   ' cQInf / mmPerm * oNH4S'
end-output
output 'tNInfNO3S'
   description   ' cQInf / mmPerm * oNO3S'
end-output
output 'tNH4LoadS'
   description   ' fNH4LoadS * cNLoadS'
end-output
output 'tNO3LoadS'
   description   ' cNloadS - tNH4LoadS'
end-output
output 'uDErosIM'
   description   ' (1.0 - fDOrgSoil) * cDErosTot'
end-output
output 'uDErosIMS'
   description   ' fSedErosIM * uDErosIM'
end-output
output 'uDErosIMW'
   description   ' uDErosIM - uDErosIMS'
end-output
output 'uDErosOM'
   description   ' fDOrgSoil * cDErosTot'
end-output
output 'uPErosOM'
   description   ' cPDSoilOM * uDErosOM'
end-output
output 'uNErosOM'
   description   ' cNDSoilOM * uDErosOM'
end-output
output 'uO2Sat'
   description   ' 14.652 - 0.41022 * uTm + 0.007991 * uTm**2 -  0.0'
end-output
output 'kAer'
   description   ' cAerRoot * uVWind**0.5 + cAerLin * uVWind +   cAe'
end-output
output 'uFunTmAer'
   description   ' cThetaAer ** (uTm-cTmRef)'
end-output
output 'aFunLemnAe'
   description   ' MAX(0.0, 1.0 - (kLemnAer * sDLemn))'
end-output
output 'tO2Aer'
   description   ' kAer * uFunTmAer * (uO2Sat - sO2W) * aFunLemnAer'
end-output
output 'tDTurbFish'
   description   ' 0.0'
end-output
output 'tDTurbFisM'
   description   ' fLutum * sDIMS / (fLutum * sDIMS + sDDetS) * tDTu'
end-output
output 'aDVeg'
   description   ' sDElod + sDChar + sDCera  + sDLemn + sDNymp + sDH'
end-output
output 'aFunVegRes'
   description   ' MAX(1.0 - kVegResus * aDVeg, 0.0)'
end-output
output 'aFunDimSus'
   description   ' cSuspRef * ((cSuspMin + cSuspMax /   (1.0 + EXP(c'
end-output
output 'tDResusTau'
   description   ' MIN(aFunDimSusp, (aFunDimSusp +NearZero)**0.5)  *'
end-output
output 'tDResusBar'
   description   ' tDResusTauDead + tDTurbFish'
end-output
output 'tDResusDea'
   description   ' tDResusBareDead * aFunVegResus'
end-output
output 'tDResusIM'
   description   ' fLutum * sDIMS / (fLutum * sDIMS + sDDetS) * tDRe'
end-output
output 'tDResusDet'
   description   ' sDDetS / (fLutum * sDIMS + sDDetS) * tDResusDead'
end-output
output 'akResusPhy'
   description   ' kResusPhytMax * (1.0 - EXP(cResusPhytExp * tDResu'
end-output
output 'tDResusPhy'
   description   ' akResusPhytRef * aDPhytS'
end-output
output 'tPResusDet'
   description   ' rPDDetS * tDResusDet'
end-output
output 'tPResusPO4'
   description   ' sPO4S / sDDetS * tDResusDet'
end-output
output 'tPResusAIM'
   description   ' sPAIMS / sDIMS * tDResusIM'
end-output
output 'tNResusNO3'
   description   ' sNO3S / sDDetS * tDResusDet'
end-output
output 'tNResusNH4'
   description   ' sNH4S / sDDetS * tDResusDet'
end-output
output 'tNResusDet'
   description   ' rNDDetS * tDResusDet'
end-output
output 'aFunTauSet'
   description   ' MIN(1.0 / (aFunDimSusp +NearZero)**0.5, 1.0)'
end-output
output 'aFunTauSeM'
   description   ' aFunTauSetOM'
end-output
output 'uFunTmSet'
   description   ' cThetaSet ** (uTm-cTmRef)'
end-output
output 'uCorVSetIM'
   description   ' aFunTauSetIM * (fLutumRef/fLutum)**0.5 * uFunTmSe'
end-output
output 'tDSetIM'
   description   ' uCorVSetIM * sDIMW'
end-output
output 'tPSetAIM'
   description   ' sPAIMW / sDIMW * tDSetIM'
end-output
output 'uCorVSetDe'
   description   ' cVSetDet * aFunTauSetOM * uFunTmSet'
end-output
output 'tDSetDet'
   description   ' uCorVSetDet * sDDetW'
end-output
output 'tPSetDet'
   description   ' uCorVSetDet * sPDetW'
end-output
output 'tNSetDet'
   description   ' uCorVSetDet * sNDetW'
end-output
output 'kPMinDetW'
   description   ' kDMinDetW'
end-output
output 'kNMinDetW'
   description   ' kDMinDetW'
end-output
output 'kSiMinDetW'
   description   ' kDMinDetW'
end-output
output 'uFunTmMinW'
   description   ' cThetaMinW ** (uTm-cTmRef)'
end-output
output 'wDMinDetW'
   description   ' kDMinDetW * uFunTmMinW * sDDetW'
end-output
output 'wPMinDetW'
   description   ' kPMinDetW * uFunTmMinW * sPDetW'
end-output
output 'wNMinDetW'
   description   ' kNMinDetW * uFunTmMinW * sNDetW'
end-output
output 'aCorO2BOD'
   description   ' sO2W / (hO2BOD + sO2W)'
end-output
output 'wO2MinDetW'
   description   ' molO2molC * cCPerDW * aCorO2BOD * wDMinDetW'
end-output
output 'wDDenitW'
   description   ' sNO3W**2.0 / (hNO3Denit**2.0 + sNO3W**2.0)   * (1'
end-output
output 'wNDenitW'
   description   ' NO3PerC * molNmolC * cCPerDW * wDDenitW'
end-output
output 'uFunTmNitr'
   description   ' cThetaNitr ** (uTm-cTmRef)'
end-output
output 'aCorO2Nitr'
   description   ' sO2W ** 2.0 / (hO2Nitr ** 2.0 + sO2W ** 2.0)'
end-output
output 'wNNitrW'
   description   ' kNitrW * uFunTmNitr * aCorO2NitrW * sNH4W'
end-output
output 'wO2NitrW'
   description   ' O2PerNH4 * molO2molN * wNNitrW'
end-output
output 'kPMinDetS'
   description   ' kDMinDetS'
end-output
output 'kNMinDetS'
   description   ' kDMinDetS'
end-output
output 'uFunTmMinS'
   description   ' cThetaMinS ** (uTm-cTmRef)'
end-output
output 'tDMinDetS'
   description   ' kDMinDetS * uFunTmMinS * sDDetS'
end-output
output 'tPMinDetS'
   description   ' kPMinDetS * uFunTmMinS * sPDetS'
end-output
output 'tNMinDetS'
   description   ' kNMinDetS * uFunTmMinS * sNDetS'
end-output
output 'uFunTmDif'
   description   ' cThetaDif ** (uTm-cTmRef)'
end-output
output 'akO2DifCor'
   description   ' kO2Dif * uFunTmDif * cTurbDifO2 * bPorCorS'
end-output
output 'tSOD'
   description   ' (molO2molC * cCPerDW * (1.0 - fRefrDetS) * tDMinD'
end-output
output 'aDepthOxyS'
   description   ' (2.0 * sO2W * akO2DifCor / tSOD) ** 0.5'
end-output
output 'afOxySed'
   description   ' aDepthOxySed / cDepthS'
end-output
output 'tDMinOxyDe'
   description   ' afOxySed * (1.0 - fRefrDetS) * tDMinDetS'
end-output
output 'tO2MinDetS'
   description   ' molO2molC * cCPerDW * tDMinOxyDetS'
end-output
output 'tDDenitS'
   description   ' oNO3S**2.0 / (hNO3Denit**2.0 + oNO3S**2.0)   * (1'
end-output
output 'tNDenitS'
   description   ' NO3PerC * molNmolC * cCPerDW * tDDenitS'
end-output
output 'tNNitrS'
   description   ' afOxySed * kNitrS * uFunTmNitr * sNH4S'
end-output
output 'tO2NitrS'
   description   ' O2PerNH4 * molO2molN * tNNitrS'
end-output
output 'tDMinHumS'
   description   ' kDMinHum * uFunTmMinS * afOxySed * sDHumS'
end-output
output 'tPMinHumS'
   description   ' kDMinHum * uFunTmMinS * afOxySed * sPHumS'
end-output
output 'tNMinHumS'
   description   ' kDMinHum * uFunTmMinS * afOxySed * sNHumS'
end-output
output 'aDepthDif'
   description   ' fDepthDifS * cDepthS'
end-output
output 'tPDifPO4'
   description   ' kPDifPO4 * uFunTmDif * cTurbDifNut * bPorCorS *'
end-output
output 'tNDifNO3'
   description   ' kNDifNO3 * uFunTmDif * cTurbDifNut * bPorCorS *'
end-output
output 'tNDifNH4'
   description   ' kNDifNH4 * uFunTmDif * cTurbDifNut * bPorCorS *'
end-output
output 'tO2Dif'
   description   ' kO2Dif / aDepthDif * uFunTmDif * cTurbDifO2 * bPo'
end-output
output 'tPDifGroun'
   description   ' 0.0'
end-output
output 'tNDifGroun'
   description   ' 0.0'
end-output
output 'tNDifGrou4'
   description   ' 0.0'
end-output
output 'aPAdsMaxW'
   description   ' cRelPAdsD + aCorO2BOD * cRelPAdsFe * fFeDIM   + c'
end-output
output 'aKPAdsW'
   description   ' (1.0 - fRedMax * (1.0-aCorO2BOD)) * cKPAdsOx'
end-output
output 'aPIsoAdsW'
   description   ' aPAdsMaxW * aKPAdsW * sPO4W / (1.0 + aKPAdsW * sP'
end-output
output 'aPEqIMW'
   description   ' aPIsoAdsW * sDIMW'
end-output
output 'wPSorpIMW'
   description   ' kPSorp * (aPEqIMW - sPAIMW)'
end-output
output 'aPAdsMaxS'
   description   ' cRelPAdsD + afOxySed * cRelPAdsFe * fFeDIM    + c'
end-output
output 'aKPAdsS'
   description   ' (1.0 - fRedMax * (1.0-afOxySed)) * cKPAdsOx'
end-output
output 'aPIsoAdsS'
   description   ' aPAdsMaxS * aKPAdsS * oPO4S / (1.0 + aKPAdsS * oP'
end-output
output 'aPEqIMS'
   description   ' aPIsoAdsS * sDIMS'
end-output
output 'tPSorpIMS'
   description   ' kPSorp * (aPEqIMS - sPAIMS)'
end-output
output 'tPChemPO4'
   description   ' MAX( 0.0, kPChemPO4 * (oPO4S - coPO4Max) )'
end-output
output 'wDAbioIMW'
   description   ' (uDErosIMW - tDSetIM + tDResusIM) / sDepthW'
end-output
output 'wDAbioDetW'
   description   ' (- tDSetDet + tDResusDet ) / sDepthW - wDMinDetW'
end-output
output 'tDAbioIMS'
   description   ' uDErosIMS + tDSetIM - tDResusIM'
end-output
output 'tDAbioDetS'
   description   ' tDSetDet - tDResusDet - tDMinDetS'
end-output
output 'tDAbioHumS'
   description   ' uDErosOM + fRefrDetS * tDMinDetS - tDMinHumS'
end-output
output 'tDAbioTotT'
   description   ' cDErosTot - wDMinDetW * sDepthW   - (1.0 - fRefrD'
end-output
output 'wO2AbioW'
   description   ' tO2Aer / sDepthW - wO2MinDetW - wO2NitrW   - (tO2'
end-output
output 'wPAbioDetW'
   description   ' - wPMinDetW - (tPSetDet - tPResusDet) / sDepthW'
end-output
output 'wPAbioPO4W'
   description   ' wPMinDetW - wPSorpIMW - tPInfPO4W / sDepthW   + t'
end-output
output 'wPAbioAIMW'
   description   ' (- tPSetAIM + tPResusAIM) / sDepthW + wPSorpIMW'
end-output
output 'tPAbioDetS'
   description   ' - tPMinDetS + tPSetDet - tPResusDet'
end-output
output 'tPAbioHumS'
   description   ' uPErosOM + fRefrDetS * tPMinDetS - tPMinHumS'
end-output
output 'tPAbioPO4S'
   description   ' tPInfPO4W - tPInfPO4S + (1.0-fRefrDetS) * tPMinDe'
end-output
output 'tPAbioAIMS'
   description   ' tPSetAIM - tPResusAIM + tPSorpIMS'
end-output
output 'tPAbioTotT'
   description   ' uPErosOM - tPChemPO4 - tPInfPO4S - tPDifGroundPO4'
end-output
output 'wNAbioNH4W'
   description   ' wNMinDetW - wNNitrW - tNInfNH4W / sDepthW   + (tN'
end-output
output 'wNAbioNO3W'
   description   ' wNNitrW - wNDenitW + (tNDifNO3 + tNResusNO3 - tNI'
end-output
output 'wNAbioDetW'
   description   ' - wNMinDetW - (tNSetDet - tNResusDet ) / sDepthW'
end-output
output 'tNAbioNH4S'
   description   ' tNInfNH4W - tNInfNH4S + (1.0-fRefrDetS) * tNMinDe'
end-output
output 'tNAbioNO3S'
   description   ' tNInfNO3W - tNInfNO3S + tNNitrS - tNDenitS   - tN'
end-output
output 'tNAbioDetS'
   description   ' - tNMinDetS + tNSetDet - tNResusDet'
end-output
output 'tNAbioHumS'
   description   ' uNErosOM + fRefrDetS * tNMinDetS - tNMinHumS'
end-output
output 'tNAbioTotT'
   description   ' uNErosOM - tNDenitS - wNDenitW * sDepthW - tNInfN'
end-output
output 'fManElod'
   description   ' fManVeg'
end-output
output 'fManCera'
   description   ' fManVeg'
end-output
output 'fManChar'
   description   ' fManVeg'
end-output
output 'fManNymp'
   description   ' fManHelo'
end-output
output 'kMigrLemn'
   description   ' ckMigrLemn + (1.0 - fObstrLemn) * ukOut'
end-output
output 'FlagInitEl'
   description   ' 0'
end-output
output 'aDayInitEl'
   description   ' 9999000.0'
end-output
output 'bfRootElod'
   description   ' fRootElodWin'
end-output
output 'bfShootElo'
   description   ' 1.0 - bfRootElod'
end-output
output 'aDRootElod'
   description   ' bfRootElod * sDElod'
end-output
output 'aDShootElo'
   description   ' bfShootElod * sDElod'
end-output
output 'aDEmergElo'
   description   ' fEmergElod * aDShootElod'
end-output
output 'aDFloatElo'
   description   ' fFloatElod * aDShootElod'
end-output
output 'bfSubElod'
   description   ' 1.0 - fFloatElod - fEmergElod'
end-output
output 'aDSubElod'
   description   ' bfSubElod * aDShootElod'
end-output
output 'aExtElod'
   description   ' cExtSpElod * aDSubElod / sDepthW'
end-output
output 'aDepth1Elo'
   description   ' fDepth1Elod * sDepthW'
end-output
output 'aDepth2Elo'
   description   ' fDepth2Elod * sDepthW'
end-output
output 'afCovSurfE'
   description   ' MIN(1.0, MAX(aDFloatElod / (cDLayerElod   + NearZ'
end-output
output 'afCovEmerg'
   description   ' MIN(1.0, PerCent * cCovSpElod * aDEmergElod)'
end-output
output 'aCovElod'
   description   ' MIN(100.0, cCovSpElod * aDShootElod)'
end-output
output 'FlagInitCh'
   description   ' 0'
end-output
output 'aDayInitCh'
   description   ' 9999000.0'
end-output
output 'bfRootChar'
   description   ' fRootCharWin'
end-output
output 'bfShootCha'
   description   ' 1.0 - bfRootChar'
end-output
output 'aDRootChar'
   description   ' bfRootChar * sDChar'
end-output
output 'aDShootCha'
   description   ' bfShootChar * sDChar'
end-output
output 'aDEmergCha'
   description   ' fEmergChar * aDShootChar'
end-output
output 'aDFloatCha'
   description   ' fFloatChar * aDShootChar'
end-output
output 'bfSubChar'
   description   ' 1.0 - fFloatChar - fEmergChar'
end-output
output 'aDSubChar'
   description   ' bfSubChar * aDShootChar'
end-output
output 'aExtChar'
   description   ' cExtSpChar * aDSubChar / sDepthW'
end-output
output 'aDepth1Cha'
   description   ' fDepth1Char * sDepthW'
end-output
output 'aDepth2Cha'
   description   ' fDepth2Char * sDepthW'
end-output
output 'afCovSurfC'
   description   ' MIN(1.0, MAX(aDFloatChar / (cDLayerChar   + NearZ'
end-output
output 'afCovEmerr'
   description   ' MIN(1.0, PerCent * cCovSpChar * aDEmergChar)'
end-output
output 'aCovChar'
   description   ' MIN(100.0, cCovSpChar * aDShootChar)'
end-output
output 'FlagInitCe'
   description   ' 0'
end-output
output 'aDayInitCe'
   description   ' 9999000.0'
end-output
output 'bfRootCera'
   description   ' fRootCeraWin'
end-output
output 'bfShootCer'
   description   ' 1.0 - bfRootCera'
end-output
output 'aDRootCera'
   description   ' bfRootCera * sDCera'
end-output
output 'aDShootCer'
   description   ' bfShootCera * sDCera'
end-output
output 'aDEmergCer'
   description   ' fEmergCera * aDShootCera'
end-output
output 'aDFloatCer'
   description   ' fFloatCera * aDShootCera'
end-output
output 'bfSubCera'
   description   ' 1.0 - fFloatCera - fEmergCera'
end-output
output 'aDSubCera'
   description   ' bfSubCera * aDShootCera'
end-output
output 'aExtCera'
   description   ' cExtSpCera * aDSubCera / sDepthW'
end-output
output 'aDepth1Cer'
   description   ' fDepth1Cera * sDepthW'
end-output
output 'aDepth2Cer'
   description   ' fDepth2Cera * sDepthW'
end-output
output 'afCovSurfa'
   description   ' MIN(1.0, MAX(aDFloatCera / (cDLayerCera   + NearZ'
end-output
output 'afCovEmera'
   description   ' MIN(1.0, PerCent * cCovSpCera * aDEmergCera)'
end-output
output 'aCovCera'
   description   ' MIN(100.0, cCovSpCera * aDShootCera)'
end-output
output 'FlagInitLe'
   description   ' 0'
end-output
output 'aDayInitLe'
   description   ' 9999000.0'
end-output
output 'bfRootLemn'
   description   ' fRootLemnWin'
end-output
output 'bfShootLem'
   description   ' 1.0 - bfRootLemn'
end-output
output 'aDRootLemn'
   description   ' bfRootLemn * sDLemn'
end-output
output 'aDShootLem'
   description   ' bfShootLemn * sDLemn'
end-output
output 'aDEmergLem'
   description   ' fEmergLemn * aDShootLemn'
end-output
output 'aDFloatLem'
   description   ' fFloatLemn * aDShootLemn'
end-output
output 'bfSubLemn'
   description   ' 1.0 - fFloatLemn - fEmergLemn'
end-output
output 'aDSubLemn'
   description   ' bfSubLemn * aDShootLemn'
end-output
output 'aExtLemn'
   description   ' cExtSpLemn * aDSubLemn / sDepthW'
end-output
output 'aDepth1Lem'
   description   ' fDepth1Lemn * sDepthW'
end-output
output 'aDepth2Lem'
   description   ' fDepth2Lemn * sDepthW'
end-output
output 'afCovSurfL'
   description   ' MIN(1.0, MAX(aDFloatLemn / (cDLayerLemn   + NearZ'
end-output
output 'afCovEmern'
   description   ' MIN(1.0, PerCent * cCovSpLemn * aDEmergLemn)'
end-output
output 'aCovLemn'
   description   ' MIN(100.0, cCovSpLemn * aDShootLemn)'
end-output
output 'FlagInitNy'
   description   ' 0'
end-output
output 'aDayInitNy'
   description   ' 9999000.0'
end-output
output 'bfRootNymp'
   description   ' fRootNympWin'
end-output
output 'bfShootNym'
   description   ' 1.0 - bfRootNymp'
end-output
output 'aDRootNymp'
   description   ' bfRootNymp * sDNymp'
end-output
output 'aDShootNym'
   description   ' bfShootNymp * sDNymp'
end-output
output 'aDEmergNym'
   description   ' fEmergNymp * aDShootNymp'
end-output
output 'aDFloatNym'
   description   ' fFloatNymp * aDShootNymp'
end-output
output 'bfSubNymp'
   description   ' 1.0 - fFloatNymp - fEmergNymp'
end-output
output 'aDSubNymp'
   description   ' bfSubNymp * aDShootNymp'
end-output
output 'aExtNymp'
   description   ' cExtSpNymp * aDSubNymp / sDepthW'
end-output
output 'aDepth1Nym'
   description   ' fDepth1Nymp * sDepthW'
end-output
output 'aDepth2Nym'
   description   ' fDepth2Nymp * sDepthW'
end-output
output 'afCovSurfN'
   description   ' MIN(1.0, MAX(aDFloatNymp / (cDLayerNymp   + NearZ'
end-output
output 'afCovEmerp'
   description   ' MIN(1.0, PerCent * cCovSpNymp * aDEmergNymp)'
end-output
output 'aCovNymp'
   description   ' MIN(100.0, cCovSpNymp * aDShootNymp)'
end-output
output 'FlagInitHe'
   description   ' 0'
end-output
output 'aDayInitHe'
   description   ' 9999000.0'
end-output
output 'bfRootHelo'
   description   ' fRootHeloWin'
end-output
output 'bfShootHel'
   description   ' 1.0 - bfRootHelo'
end-output
output 'aDRootHelo'
   description   ' bfRootHelo * sDHelo'
end-output
output 'aDShootHel'
   description   ' bfShootHelo * sDHelo'
end-output
output 'aDEmergHel'
   description   ' fEmergHelo * aDShootHelo'
end-output
output 'aDFloatHel'
   description   ' fFloatHelo * aDShootHelo'
end-output
output 'bfSubHelo'
   description   ' 1.0 - fFloatHelo - fEmergHelo'
end-output
output 'aDSubHelo'
   description   ' bfSubHelo * aDShootHelo'
end-output
output 'aExtHelo'
   description   ' cExtSpHelo * aDSubHelo / sDepthW'
end-output
output 'aDepth1Hel'
   description   ' fDepth1Helo * sDepthW'
end-output
output 'aDepth2Hel'
   description   ' fDepth2Helo * sDepthW'
end-output
output 'afCovSurfH'
   description   ' MIN(1.0, MAX(aDFloatHelo / (cDLayerHelo   + NearZ'
end-output
output 'afCovEmero'
   description   ' MIN(1.0, PerCent * cCovSpHelo * aDEmergHelo)'
end-output
output 'aCovHelo'
   description   ' MIN(100.0, cCovSpHelo * aDShootHelo)'
end-output
output 'aPVeg'
   description   ' sPElod + sPChar + sPCera  + sPLemn + sPNymp + sPH'
end-output
output 'aNVeg'
   description   ' sNElod + sNChar + sNCera  + sNLemn + sNNymp + sNH'
end-output
output 'afCovSurfV'
   description   ' MIN(1.0,  afCovSurfElod + afCovSurfChar  + afCovS'
end-output
output 'afCovEmeeg'
   description   ' MIN(1.0,  afCovEmergElod + afCovEmergChar  + afCo'
end-output
output 'aExtVeg'
   description   ' aExtElod + aExtChar + aExtCera + aExtLemn  + aExt'
end-output
output 'aExtCoef'
   description   ' aExtCoefOpen + aExtVeg'
end-output
output 'aLPARBot'
   description   '  uLPAR0 * EXP(- aExtCoef * sDepthW)'
end-output
output 'rPDElod'
   description   ' sPElod / (sDElod+NearZero)'
end-output
output 'rNDElod'
   description   ' sNElod / (sDElod+NearZero)'
end-output
output 'tDMigrElod'
   description   ' kMigrElod * (cDElodIn - sDElod)'
end-output
output 'tPMigrElod'
   description   ' kMigrElod * (cPDElod0* cDElodIn - sPElod)'
end-output
output 'tNMigrElod'
   description   ' kMigrElod * (cNDElod0* cDElodIn - sNElod)'
end-output
output 'uFunTmProd'
   description   ' cQ10ProdElod ** (0.1 * (uTm - cTmRef))'
end-output
output 'uFunTmResp'
   description   ' cQ10RespElod ** (0.1 * (uTm - cTmRef))'
end-output
output 'aVPUptMaxC'
   description   ' MAX( 0.0,  cVPUptMaxElod * uFunTmProdElod *  (cPD'
end-output
output 'aVPUptElod'
   description   ' sPO4W * aVPUptMaxCrElod /  (aVPUptMaxCrElod / cAf'
end-output
output 'tPUptElodW'
   description   ' aVPUptElodW * (aDSubElod + aDFloatElod)'
end-output
output 'aVPUptEloS'
   description   ' oPO4S * aVPUptMaxCrElod /  (aVPUptMaxCrElod / cAf'
end-output
output 'tPUptElodS'
   description   ' aVPUptElodS * aDRootElod'
end-output
output 'tPUptElod'
   description   ' tPUptElodW + tPUptElodS'
end-output
output 'aVNUptMaxC'
   description   ' MAX( 0.0,  cVNUptMaxElod * uFunTmProdElod *  (cND'
end-output
output 'ahNUptElod'
   description   ' aVNUptMaxCrElod / cAffNUptElod'
end-output
output 'aVNUptElod'
   description   ' oNDissW * aVNUptMaxCrElod / (ahNUptElod + oNDissW'
end-output
output 'tNUptElodW'
   description   ' aVNUptElodW * (aDSubElod + aDFloatElod)'
end-output
output 'afNH4UptEl'
   description   ' sNH4W * sNO3W / ((ahNUptElod + sNH4W) *  (ahNUptE'
end-output
output 'tNUptNH4El'
   description   ' afNH4UptElodW * tNUptElodW'
end-output
output 'tNUptNO3El'
   description   ' tNUptElodW - tNUptNH4ElodW'
end-output
output 'aVNUptEloS'
   description   ' oNDissS * aVNUptMaxCrElod / (ahNUptElod + oNDissS'
end-output
output 'tNUptElodS'
   description   ' aVNUptElodS * aDRootElod'
end-output
output 'afNH4UptES'
   description   ' oNH4S * oNO3S / ((ahNUptElod + oNH4S +NearZero) *'
end-output
output 'tNUptNH4ES'
   description   ' afNH4UptElodS * tNUptElodS'
end-output
output 'tNUptNO3ES'
   description   ' tNUptElodS - tNUptNH4ElodS'
end-output
output 'tNUptElod'
   description   ' tNUptElodW + tNUptElodS'
end-output
output 'aLPAR1Elod'
   description   '  uLPAR0 * EXP(- aExtCoefOpen * aDepth1Elod)'
end-output
output 'aLPAR2Elod'
   description   '  aLPAR1Elod * EXP(- aExtCoef   * (aDepth2Elod - a'
end-output
output 'uhLElod'
   description   ' hLRefElod * uFunTmProdElod'
end-output
output 'aLLimShoot'
   description   ' fEmergElod + fFloatElod * (1.0 - afCovEmergVeg) +'
end-output
output 'aMuTmLElod'
   description   ' ufDay * bfShootElod * aLLimShootElod   * uFunTmPr'
end-output
output 'aPLimElod'
   description   ' MAX(0.0, (1.0 - cPDElodMin / rPDElod)   * cPDElod'
end-output
output 'aNLimElod'
   description   ' MAX(0.0, (1.0 - cNDElodMin / rNDElod)   * cNDElod'
end-output
output 'aNutLimElo'
   description   ' MIN( aPLimElod, aNLimElod)'
end-output
output 'aMuElod'
   description   ' aMuTmLElod * aNutLimElod'
end-output
output 'bkMortElod'
   description   ' kMortElodSum'
end-output
output 'akDIncrElo'
   description   ' aMuTmLElod - kDRespElod * uFunTmRespElod   - bkMo'
end-output
output 'tDEnvElod'
   description   ' MAX(0.0, akDIncrElod / (cDCarrElod+NearZero)   *'
end-output
output 'tDEnvProdE'
   description   ' aMuElod / cMuMaxElod * tDEnvElod'
end-output
output 'tDProdElod'
   description   ' MAX(0.0, aMuElod * sDElod  - tDEnvProdElod)'
end-output
output 'tDProdSubE'
   description   ' bfSubElod * tDProdElod'
end-output
output 'tDRespElod'
   description   ' kDRespElod * uFunTmRespElod * sDElod'
end-output
output 'tDEnvMortE'
   description   ' tDEnvElod - tDEnvProdElod'
end-output
output 'tDMortElod'
   description   ' bkMortElod * sDElod + tDEnvMortElod'
end-output
output 'tDMortEloW'
   description   ' fDetWMortElod * (1.0 - bfRootElod) * tDMortElod'
end-output
output 'tDMortEloS'
   description   ' tDMortElod - tDMortElodW'
end-output
output 'tDGrazElod'
   description   ' cPrefElodBird * sDElod / (hDVegBird + sDElod)  *'
end-output
output 'bkManElod'
   description   ' - log(1.0 - fManElod) / cLengMan'
end-output
output 'tDManElod'
   description   ' bkManElod * sDElod'
end-output
output 'tPManElod'
   description   ' rPDElod * tDManElod'
end-output
output 'tNManElod'
   description   ' rNDElod * tDManElod'
end-output
output 'tDBedElod'
   description   ' tDMigrElod + tDProdElod - tDRespElod - tDMortElod'
end-output
output 'tO2ProdElo'
   description   ' molO2molC * cCPerDW * tDProdElod'
end-output
output 'tO2RespElo'
   description   ' molO2molC * cCPerDW * bfSubElod * tDRespElod   *'
end-output
output 'tO2RespElS'
   description   ' molO2molC * cCPerDW * bfRootElod * tDRespElod   *'
end-output
output 'tO2ProdElS'
   description   ' MIN (tO2RespElodS, tO2ProdElod)'
end-output
output 'tO2ProdElW'
   description   ' MIN( tO2ProdElod - tO2ProdElodS,   bfSubElod * tO'
end-output
output 'tO2UptNO3E'
   description   ' O2PerNO3 * molO2molN * bfSubElod * tNUptNO3ElodW'
end-output
output 'tO2UptNO3S'
   description   ' O2PerNO3 * molO2molN * tNUptNO3ElodS'
end-output
output 'tPExcrElod'
   description   ' rPDElod / (cPDElodMin + rPDElod) * rPDElod   * tD'
end-output
output 'tPExcrEloS'
   description   ' bfRootElod * tPExcrElod'
end-output
output 'tPExcrEloW'
   description   ' tPExcrElod - tPExcrElodS'
end-output
output 'tPMortElod'
   description   ' rPDElod * tDMortElod'
end-output
output 'tPMortElo4'
   description   ' fDissMortVeg * tPMortElod'
end-output
output 'tPMortEloS'
   description   ' bfRootElod * tPMortElodPO4'
end-output
output 'tPMortEloW'
   description   ' tPMortElodPO4 - tPMortElodPO4S'
end-output
output 'tPMortElot'
   description   ' tPMortElod - tPMortElodPO4'
end-output
output 'tPMortEltW'
   description   ' fDetWMortElod * (1.0 - bfRootElod) *   tPMortElod'
end-output
output 'tPMortEltS'
   description   ' tPMortElodDet - tPMortElodDetW'
end-output
output 'tPGrazElod'
   description   ' rPDElod * tDGrazElodBird'
end-output
output 'tPBedElod'
   description   ' tPMigrElod + tPUptElod - tPExcrElod - tPMortElod'
end-output
output 'tNExcrElod'
   description   ' rNDElod / (cNDElodMin + rNDElod) * rNDElod   * tD'
end-output
output 'tNExcrEloS'
   description   ' bfRootElod * tNExcrElod'
end-output
output 'tNExcrEloW'
   description   ' tNExcrElod - tNExcrElodS'
end-output
output 'tNMortElod'
   description   ' rNDElod * tDMortElod'
end-output
output 'tNMortElo4'
   description   ' fDissMortVeg * tNMortElod'
end-output
output 'tNMortEloS'
   description   ' bfRootElod * tNMortElodNH4'
end-output
output 'tNMortEloW'
   description   ' tNMortElodNH4 - tNMortElodNH4S'
end-output
output 'tNMortElot'
   description   ' tNMortElod - tNMortElodNH4'
end-output
output 'tNMortEltW'
   description   ' fDetWMortElod * (1.0 - bfRootElod) *   tNMortElod'
end-output
output 'tNMortEltS'
   description   ' tNMortElodDet - tNMortElodDetW'
end-output
output 'tNGrazElod'
   description   ' rNDElod * tDGrazElodBird'
end-output
output 'tNBedElod'
   description   ' tNMigrElod + tNUptElod - tNExcrElod - tNMortElod'
end-output
output 'rPDChar'
   description   ' sPChar / (sDChar+NearZero)'
end-output
output 'rNDChar'
   description   ' sNChar / (sDChar+NearZero)'
end-output
output 'tDMigrChar'
   description   ' kMigrChar * (cDCharIn - sDChar)'
end-output
output 'tPMigrChar'
   description   ' kMigrChar * (cPDChar0* cDCharIn - sPChar)'
end-output
output 'tNMigrChar'
   description   ' kMigrChar * (cNDChar0* cDCharIn - sNChar)'
end-output
output 'uFunTmPror'
   description   ' cQ10ProdChar ** (0.1 * (uTm - cTmRef))'
end-output
output 'uFunTmResr'
   description   ' cQ10RespChar ** (0.1 * (uTm - cTmRef))'
end-output
output 'aVPUptMaxr'
   description   ' MAX( 0.0,  cVPUptMaxChar * uFunTmProdChar *  (cPD'
end-output
output 'aVPUptChar'
   description   ' sPO4W * aVPUptMaxCrChar /  (aVPUptMaxCrChar / cAf'
end-output
output 'tPUptCharW'
   description   ' aVPUptCharW * (aDSubChar + aDFloatChar)'
end-output
output 'aVPUptChaS'
   description   ' oPO4S * aVPUptMaxCrChar /  (aVPUptMaxCrChar / cAf'
end-output
output 'tPUptCharS'
   description   ' aVPUptCharS * aDRootChar'
end-output
output 'tPUptChar'
   description   ' tPUptCharW + tPUptCharS'
end-output
output 'aVNUptMaxr'
   description   ' MAX( 0.0,  cVNUptMaxChar * uFunTmProdChar *  (cND'
end-output
output 'ahNUptChar'
   description   ' aVNUptMaxCrChar / cAffNUptChar'
end-output
output 'aVNUptChar'
   description   ' oNDissW * aVNUptMaxCrChar / (ahNUptChar + oNDissW'
end-output
output 'tNUptCharW'
   description   ' aVNUptCharW * (aDSubChar + aDFloatChar)'
end-output
output 'afNH4UptCh'
   description   ' sNH4W * sNO3W / ((ahNUptChar + sNH4W) *  (ahNUptC'
end-output
output 'tNUptNH4Ch'
   description   ' afNH4UptCharW * tNUptCharW'
end-output
output 'tNUptNO3Ch'
   description   ' tNUptCharW - tNUptNH4CharW'
end-output
output 'aVNUptChaS'
   description   ' oNDissS * aVNUptMaxCrChar / (ahNUptChar + oNDissS'
end-output
output 'tNUptCharS'
   description   ' aVNUptCharS * aDRootChar'
end-output
output 'afNH4UptCS'
   description   ' oNH4S * oNO3S / ((ahNUptChar + oNH4S +NearZero) *'
end-output
output 'tNUptNH4CS'
   description   ' afNH4UptCharS * tNUptCharS'
end-output
output 'tNUptNO3CS'
   description   ' tNUptCharS - tNUptNH4CharS'
end-output
output 'tNUptChar'
   description   ' tNUptCharW + tNUptCharS'
end-output
output 'aLPAR1Char'
   description   '  uLPAR0 * EXP(- aExtCoefOpen * aDepth1Char)'
end-output
output 'aLPAR2Char'
   description   '  aLPAR1Char * EXP(- aExtCoef   * (aDepth2Char - a'
end-output
output 'uhLChar'
   description   ' hLRefChar * uFunTmProdChar'
end-output
output 'aLLimShoor'
   description   ' fEmergChar + fFloatChar * (1.0 - afCovEmergVeg) +'
end-output
output 'aMuTmLChar'
   description   ' ufDay * bfShootChar * aLLimShootChar   * uFunTmPr'
end-output
output 'aPLimChar'
   description   ' MAX(0.0, (1.0 - cPDCharMin / rPDChar)   * cPDChar'
end-output
output 'aNLimChar'
   description   ' MAX(0.0, (1.0 - cNDCharMin / rNDChar)   * cNDChar'
end-output
output 'aNutLimCha'
   description   ' MIN( aPLimChar, aNLimChar)'
end-output
output 'aMuChar'
   description   ' aMuTmLChar * aNutLimChar'
end-output
output 'bkMortChar'
   description   ' kMortCharSum'
end-output
output 'akDIncrCha'
   description   ' aMuTmLChar - kDRespChar * uFunTmRespChar   - bkMo'
end-output
output 'tDEnvChar'
   description   ' MAX(0.0, akDIncrChar / (cDCarrChar+NearZero)   *'
end-output
output 'tDEnvProdC'
   description   ' aMuChar / cMuMaxChar * tDEnvChar'
end-output
output 'tDProdChar'
   description   ' MAX(0.0, aMuChar * sDChar  - tDEnvProdChar)'
end-output
output 'tDProdSubC'
   description   ' bfSubChar * tDProdChar'
end-output
output 'tDRespChar'
   description   ' kDRespChar * uFunTmRespChar * sDChar'
end-output
output 'tDEnvMortC'
   description   ' tDEnvChar - tDEnvProdChar'
end-output
output 'tDMortChar'
   description   ' bkMortChar * sDChar + tDEnvMortChar'
end-output
output 'tDMortChaW'
   description   ' fDetWMortChar * (1.0 - bfRootChar) * tDMortChar'
end-output
output 'tDMortChaS'
   description   ' tDMortChar - tDMortCharW'
end-output
output 'tDGrazChar'
   description   ' cPrefCharBird * sDChar / (hDVegBird + sDChar)  *'
end-output
output 'bkManChar'
   description   ' - log(1.0 - fManChar) / cLengMan'
end-output
output 'tDManChar'
   description   ' bkManChar * sDChar'
end-output
output 'tPManChar'
   description   ' rPDChar * tDManChar'
end-output
output 'tNManChar'
   description   ' rNDChar * tDManChar'
end-output
output 'tDBedChar'
   description   ' tDMigrChar + tDProdChar - tDRespChar - tDMortChar'
end-output
output 'tO2ProdCha'
   description   ' molO2molC * cCPerDW * tDProdChar'
end-output
output 'tO2RespCha'
   description   ' molO2molC * cCPerDW * bfSubChar * tDRespChar   *'
end-output
output 'tO2RespChS'
   description   ' molO2molC * cCPerDW * bfRootChar * tDRespChar   *'
end-output
output 'tO2ProdChS'
   description   ' MIN (tO2RespCharS, tO2ProdChar)'
end-output
output 'tO2ProdChW'
   description   ' MIN( tO2ProdChar - tO2ProdCharS,   bfSubChar * tO'
end-output
output 'tO2UptNO3C'
   description   ' O2PerNO3 * molO2molN * bfSubChar * tNUptNO3CharW'
end-output
output 'tO2UptNOrS'
   description   ' O2PerNO3 * molO2molN * tNUptNO3CharS'
end-output
output 'tPExcrChar'
   description   ' rPDChar / (cPDCharMin + rPDChar) * rPDChar   * tD'
end-output
output 'tPExcrChaS'
   description   ' bfRootChar * tPExcrChar'
end-output
output 'tPExcrChaW'
   description   ' tPExcrChar - tPExcrCharS'
end-output
output 'tPMortChar'
   description   ' rPDChar * tDMortChar'
end-output
output 'tPMortCha4'
   description   ' fDissMortVeg * tPMortChar'
end-output
output 'tPMortChaS'
   description   ' bfRootChar * tPMortCharPO4'
end-output
output 'tPMortChaW'
   description   ' tPMortCharPO4 - tPMortCharPO4S'
end-output
output 'tPMortChat'
   description   ' tPMortChar - tPMortCharPO4'
end-output
output 'tPMortChtW'
   description   ' fDetWMortChar * (1.0 - bfRootChar) *   tPMortChar'
end-output
output 'tPMortChtS'
   description   ' tPMortCharDet - tPMortCharDetW'
end-output
output 'tPGrazChar'
   description   ' rPDChar * tDGrazCharBird'
end-output
output 'tPBedChar'
   description   ' tPMigrChar + tPUptChar - tPExcrChar - tPMortChar'
end-output
output 'tNExcrChar'
   description   ' rNDChar / (cNDCharMin + rNDChar) * rNDChar   * tD'
end-output
output 'tNExcrChaS'
   description   ' bfRootChar * tNExcrChar'
end-output
output 'tNExcrChaW'
   description   ' tNExcrChar - tNExcrCharS'
end-output
output 'tNMortChar'
   description   ' rNDChar * tDMortChar'
end-output
output 'tNMortCha4'
   description   ' fDissMortVeg * tNMortChar'
end-output
output 'tNMortChaS'
   description   ' bfRootChar * tNMortCharNH4'
end-output
output 'tNMortChaW'
   description   ' tNMortCharNH4 - tNMortCharNH4S'
end-output
output 'tNMortChat'
   description   ' tNMortChar - tNMortCharNH4'
end-output
output 'tNMortChtW'
   description   ' fDetWMortChar * (1.0 - bfRootChar) *   tNMortChar'
end-output
output 'tNMortChtS'
   description   ' tNMortCharDet - tNMortCharDetW'
end-output
output 'tNGrazChar'
   description   ' rNDChar * tDGrazCharBird'
end-output
output 'tNBedChar'
   description   ' tNMigrChar + tNUptChar - tNExcrChar - tNMortChar'
end-output
output 'rPDCera'
   description   ' sPCera / (sDCera+NearZero)'
end-output
output 'rNDCera'
   description   ' sNCera / (sDCera+NearZero)'
end-output
output 'tDMigrCera'
   description   ' kMigrCera * (cDCeraIn - sDCera)'
end-output
output 'tPMigrCera'
   description   ' kMigrCera * (cPDCera0* cDCeraIn - sPCera)'
end-output
output 'tNMigrCera'
   description   ' kMigrCera * (cNDCera0* cDCeraIn - sNCera)'
end-output
output 'uFunTmProa'
   description   ' cQ10ProdCera ** (0.1 * (uTm - cTmRef))'
end-output
output 'uFunTmResa'
   description   ' cQ10RespCera ** (0.1 * (uTm - cTmRef))'
end-output
output 'aVPUptMaxa'
   description   ' MAX( 0.0,  cVPUptMaxCera * uFunTmProdCera *  (cPD'
end-output
output 'aVPUptCera'
   description   ' sPO4W * aVPUptMaxCrCera /  (aVPUptMaxCrCera / cAf'
end-output
output 'tPUptCeraW'
   description   ' aVPUptCeraW * (aDSubCera + aDFloatCera)'
end-output
output 'aVPUptCerS'
   description   ' oPO4S * aVPUptMaxCrCera /  (aVPUptMaxCrCera / cAf'
end-output
output 'tPUptCeraS'
   description   ' aVPUptCeraS * aDRootCera'
end-output
output 'tPUptCera'
   description   ' tPUptCeraW + tPUptCeraS'
end-output
output 'aVNUptMaxa'
   description   ' MAX( 0.0,  cVNUptMaxCera * uFunTmProdCera *  (cND'
end-output
output 'ahNUptCera'
   description   ' aVNUptMaxCrCera / cAffNUptCera'
end-output
output 'aVNUptCera'
   description   ' oNDissW * aVNUptMaxCrCera / (ahNUptCera + oNDissW'
end-output
output 'tNUptCeraW'
   description   ' aVNUptCeraW * (aDSubCera + aDFloatCera)'
end-output
output 'afNH4UptCe'
   description   ' sNH4W * sNO3W / ((ahNUptCera + sNH4W) *  (ahNUptC'
end-output
output 'tNUptNH4Ce'
   description   ' afNH4UptCeraW * tNUptCeraW'
end-output
output 'tNUptNO3Ce'
   description   ' tNUptCeraW - tNUptNH4CeraW'
end-output
output 'aVNUptCerS'
   description   ' oNDissS * aVNUptMaxCrCera / (ahNUptCera + oNDissS'
end-output
output 'tNUptCeraS'
   description   ' aVNUptCeraS * aDRootCera'
end-output
output 'afNH4UptaS'
   description   ' oNH4S * oNO3S / ((ahNUptCera + oNH4S +NearZero) *'
end-output
output 'tNUptNH4aS'
   description   ' afNH4UptCeraS * tNUptCeraS'
end-output
output 'tNUptNO3aS'
   description   ' tNUptCeraS - tNUptNH4CeraS'
end-output
output 'tNUptCera'
   description   ' tNUptCeraW + tNUptCeraS'
end-output
output 'aLPAR1Cera'
   description   '  uLPAR0 * EXP(- aExtCoefOpen * aDepth1Cera)'
end-output
output 'aLPAR2Cera'
   description   '  aLPAR1Cera * EXP(- aExtCoef   * (aDepth2Cera - a'
end-output
output 'uhLCera'
   description   ' hLRefCera * uFunTmProdCera'
end-output
output 'aLLimShooa'
   description   ' fEmergCera + fFloatCera * (1.0 - afCovEmergVeg) +'
end-output
output 'aMuTmLCera'
   description   ' ufDay * bfShootCera * aLLimShootCera   * uFunTmPr'
end-output
output 'aPLimCera'
   description   ' MAX(0.0, (1.0 - cPDCeraMin / rPDCera)   * cPDCera'
end-output
output 'aNLimCera'
   description   ' MAX(0.0, (1.0 - cNDCeraMin / rNDCera)   * cNDCera'
end-output
output 'aNutLimCer'
   description   ' MIN( aPLimCera, aNLimCera)'
end-output
output 'aMuCera'
   description   ' aMuTmLCera * aNutLimCera'
end-output
output 'bkMortCera'
   description   ' kMortCeraSum'
end-output
output 'akDIncrCer'
   description   ' aMuTmLCera - kDRespCera * uFunTmRespCera   - bkMo'
end-output
output 'tDEnvCera'
   description   ' MAX(0.0, akDIncrCera / (cDCarrCera+NearZero)   *'
end-output
output 'tDEnvProda'
   description   ' aMuCera / cMuMaxCera * tDEnvCera'
end-output
output 'tDProdCera'
   description   ' MAX(0.0, aMuCera * sDCera  - tDEnvProdCera)'
end-output
output 'tDProdSuba'
   description   ' bfSubCera * tDProdCera'
end-output
output 'tDRespCera'
   description   ' kDRespCera * uFunTmRespCera * sDCera'
end-output
output 'tDEnvMorta'
   description   ' tDEnvCera - tDEnvProdCera'
end-output
output 'tDMortCera'
   description   ' bkMortCera * sDCera + tDEnvMortCera'
end-output
output 'tDMortCerW'
   description   ' fDetWMortCera * (1.0 - bfRootCera) * tDMortCera'
end-output
output 'tDMortCerS'
   description   ' tDMortCera - tDMortCeraW'
end-output
output 'tDGrazCera'
   description   ' cPrefCeraBird * sDCera / (hDVegBird + sDCera)  *'
end-output
output 'bkManCera'
   description   ' - log(1.0 - fManCera) / cLengMan'
end-output
output 'tDManCera'
   description   ' bkManCera * sDCera'
end-output
output 'tPManCera'
   description   ' rPDCera * tDManCera'
end-output
output 'tNManCera'
   description   ' rNDCera * tDManCera'
end-output
output 'tDBedCera'
   description   ' tDMigrCera + tDProdCera - tDRespCera - tDMortCera'
end-output
output 'tO2ProdCer'
   description   ' molO2molC * cCPerDW * tDProdCera'
end-output
output 'tO2RespCer'
   description   ' molO2molC * cCPerDW * bfSubCera * tDRespCera   *'
end-output
output 'tO2RespCeS'
   description   ' molO2molC * cCPerDW * bfRootCera * tDRespCera   *'
end-output
output 'tO2ProdCeS'
   description   ' MIN (tO2RespCeraS, tO2ProdCera)'
end-output
output 'tO2ProdCeW'
   description   ' MIN( tO2ProdCera - tO2ProdCeraS,   bfSubCera * tO'
end-output
output 'tO2UptNO3W'
   description   ' O2PerNO3 * molO2molN * bfSubCera * tNUptNO3CeraW'
end-output
output 'tO2UptNOaS'
   description   ' O2PerNO3 * molO2molN * tNUptNO3CeraS'
end-output
output 'tPExcrCera'
   description   ' rPDCera / (cPDCeraMin + rPDCera) * rPDCera   * tD'
end-output
output 'tPExcrCerS'
   description   ' bfRootCera * tPExcrCera'
end-output
output 'tPExcrCerW'
   description   ' tPExcrCera - tPExcrCeraS'
end-output
output 'tPMortCera'
   description   ' rPDCera * tDMortCera'
end-output
output 'tPMortCer4'
   description   ' fDissMortVeg * tPMortCera'
end-output
output 'tPMortCerS'
   description   ' bfRootCera * tPMortCeraPO4'
end-output
output 'tPMortCerW'
   description   ' tPMortCeraPO4 - tPMortCeraPO4S'
end-output
output 'tPMortCert'
   description   ' tPMortCera - tPMortCeraPO4'
end-output
output 'tPMortCetW'
   description   ' fDetWMortCera * (1.0 - bfRootCera) *   tPMortCera'
end-output
output 'tPMortCetS'
   description   ' tPMortCeraDet - tPMortCeraDetW'
end-output
output 'tPGrazCera'
   description   ' rPDCera * tDGrazCeraBird'
end-output
output 'tPBedCera'
   description   ' tPMigrCera + tPUptCera - tPExcrCera - tPMortCera'
end-output
output 'tNExcrCera'
   description   ' rNDCera / (cNDCeraMin + rNDCera) * rNDCera   * tD'
end-output
output 'tNExcrCerS'
   description   ' bfRootCera * tNExcrCera'
end-output
output 'tNExcrCerW'
   description   ' tNExcrCera - tNExcrCeraS'
end-output
output 'tNMortCera'
   description   ' rNDCera * tDMortCera'
end-output
output 'tNMortCer4'
   description   ' fDissMortVeg * tNMortCera'
end-output
output 'tNMortCerS'
   description   ' bfRootCera * tNMortCeraNH4'
end-output
output 'tNMortCerW'
   description   ' tNMortCeraNH4 - tNMortCeraNH4S'
end-output
output 'tNMortCert'
   description   ' tNMortCera - tNMortCeraNH4'
end-output
output 'tNMortCetW'
   description   ' fDetWMortCera * (1.0 - bfRootCera) *   tNMortCera'
end-output
output 'tNMortCetS'
   description   ' tNMortCeraDet - tNMortCeraDetW'
end-output
output 'tNGrazCera'
   description   ' rNDCera * tDGrazCeraBird'
end-output
output 'tNBedCera'
   description   ' tNMigrCera + tNUptCera - tNExcrCera - tNMortCera'
end-output
output 'rPDLemn'
   description   ' sPLemn / (sDLemn+NearZero)'
end-output
output 'rNDLemn'
   description   ' sNLemn / (sDLemn+NearZero)'
end-output
output 'tDMigrLemn'
   description   ' kMigrLemn * (cDLemnIn - sDLemn)'
end-output
output 'tPMigrLemn'
   description   ' kMigrLemn * (cPDLemn0* cDLemnIn - sPLemn)'
end-output
output 'tNMigrLemn'
   description   ' kMigrLemn * (cNDLemn0* cDLemnIn - sNLemn)'
end-output
output 'uFunTmPron'
   description   ' cQ10ProdLemn ** (0.1 * (uTm - cTmRef))'
end-output
output 'uFunTmResn'
   description   ' cQ10RespLemn ** (0.1 * (uTm - cTmRef))'
end-output
output 'aVPUptMaxn'
   description   ' MAX( 0.0,  cVPUptMaxLemn * uFunTmProdLemn *  (cPD'
end-output
output 'aVPUptLemn'
   description   ' sPO4W * aVPUptMaxCrLemn /  (aVPUptMaxCrLemn / cAf'
end-output
output 'tPUptLemnW'
   description   ' aVPUptLemnW * (aDSubLemn + aDFloatLemn)'
end-output
output 'aVPUptLemS'
   description   ' oPO4S * aVPUptMaxCrLemn /  (aVPUptMaxCrLemn / cAf'
end-output
output 'tPUptLemnS'
   description   ' aVPUptLemnS * aDRootLemn'
end-output
output 'tPUptLemn'
   description   ' tPUptLemnW + tPUptLemnS'
end-output
output 'aVNUptMaxn'
   description   ' MAX( 0.0,  cVNUptMaxLemn * uFunTmProdLemn *  (cND'
end-output
output 'ahNUptLemn'
   description   ' aVNUptMaxCrLemn / cAffNUptLemn'
end-output
output 'aVNUptLemn'
   description   ' oNDissW * aVNUptMaxCrLemn / (ahNUptLemn + oNDissW'
end-output
output 'tNUptLemnW'
   description   ' aVNUptLemnW * (aDSubLemn + aDFloatLemn)'
end-output
output 'afNH4UptLe'
   description   ' sNH4W * sNO3W / ((ahNUptLemn + sNH4W) *  (ahNUptL'
end-output
output 'tNUptNH4Le'
   description   ' afNH4UptLemnW * tNUptLemnW'
end-output
output 'tNUptNO3Le'
   description   ' tNUptLemnW - tNUptNH4LemnW'
end-output
output 'aVNUptLemS'
   description   ' oNDissS * aVNUptMaxCrLemn / (ahNUptLemn + oNDissS'
end-output
output 'tNUptLemnS'
   description   ' aVNUptLemnS * aDRootLemn'
end-output
output 'afNH4UptLS'
   description   ' oNH4S * oNO3S / ((ahNUptLemn + oNH4S +NearZero) *'
end-output
output 'tNUptNH4LS'
   description   ' afNH4UptLemnS * tNUptLemnS'
end-output
output 'tNUptNO3LS'
   description   ' tNUptLemnS - tNUptNH4LemnS'
end-output
output 'tNUptLemn'
   description   ' tNUptLemnW + tNUptLemnS'
end-output
output 'aLPAR1Lemn'
   description   '  uLPAR0 * EXP(- aExtCoefOpen * aDepth1Lemn)'
end-output
output 'aLPAR2Lemn'
   description   '  aLPAR1Lemn * EXP(- aExtCoef   * (aDepth2Lemn - a'
end-output
output 'uhLLemn'
   description   ' hLRefLemn * uFunTmProdLemn'
end-output
output 'aLLimShoon'
   description   ' fEmergLemn + fFloatLemn * (1.0 - afCovEmergVeg) +'
end-output
output 'aMuTmLLemn'
   description   ' ufDay * bfShootLemn * aLLimShootLemn   * uFunTmPr'
end-output
output 'aPLimLemn'
   description   ' MAX(0.0, (1.0 - cPDLemnMin / rPDLemn)   * cPDLemn'
end-output
output 'aNLimLemn'
   description   ' MAX(0.0, (1.0 - cNDLemnMin / rNDLemn)   * cNDLemn'
end-output
output 'aNutLimLem'
   description   ' MIN( aPLimLemn, aNLimLemn)'
end-output
output 'aMuLemn'
   description   ' aMuTmLLemn * aNutLimLemn'
end-output
output 'bkMortLemn'
   description   ' kMortLemnSum'
end-output
output 'akDIncrLem'
   description   ' aMuTmLLemn - kDRespLemn * uFunTmRespLemn   - bkMo'
end-output
output 'tDEnvLemn'
   description   ' MAX(0.0, akDIncrLemn / (cDCarrLemn+NearZero)   *'
end-output
output 'tDEnvProdL'
   description   ' aMuLemn / cMuMaxLemn * tDEnvLemn'
end-output
output 'tDProdLemn'
   description   ' MAX(0.0, aMuLemn * sDLemn  - tDEnvProdLemn)'
end-output
output 'tDProdSubL'
   description   ' bfSubLemn * tDProdLemn'
end-output
output 'tDRespLemn'
   description   ' kDRespLemn * uFunTmRespLemn * sDLemn'
end-output
output 'tDEnvMortL'
   description   ' tDEnvLemn - tDEnvProdLemn'
end-output
output 'tDMortLemn'
   description   ' bkMortLemn * sDLemn + tDEnvMortLemn'
end-output
output 'tDMortLemW'
   description   ' fDetWMortLemn * (1.0 - bfRootLemn) * tDMortLemn'
end-output
output 'tDMortLemS'
   description   ' tDMortLemn - tDMortLemnW'
end-output
output 'tDGrazLemn'
   description   ' cPrefLemnBird * sDLemn / (hDVegBird + sDLemn)  *'
end-output
output 'bkManLemn'
   description   ' - log(1.0 - fManLemn) / cLengMan'
end-output
output 'tDManLemn'
   description   ' bkManLemn * sDLemn'
end-output
output 'tPManLemn'
   description   ' rPDLemn * tDManLemn'
end-output
output 'tNManLemn'
   description   ' rNDLemn * tDManLemn'
end-output
output 'tDBedLemn'
   description   ' tDMigrLemn + tDProdLemn - tDRespLemn - tDMortLemn'
end-output
output 'tO2ProdLem'
   description   ' molO2molC * cCPerDW * tDProdLemn'
end-output
output 'tO2RespLem'
   description   ' molO2molC * cCPerDW * bfSubLemn * tDRespLemn   *'
end-output
output 'tO2RespLeS'
   description   ' molO2molC * cCPerDW * bfRootLemn * tDRespLemn   *'
end-output
output 'tO2ProdLeS'
   description   ' MIN (tO2RespLemnS, tO2ProdLemn)'
end-output
output 'tO2ProdLeW'
   description   ' MIN( tO2ProdLemn - tO2ProdLemnS,   bfSubLemn * tO'
end-output
output 'tO2UptNO3L'
   description   ' O2PerNO3 * molO2molN * bfSubLemn * tNUptNO3LemnW'
end-output
output 'tO2UptNOnS'
   description   ' O2PerNO3 * molO2molN * tNUptNO3LemnS'
end-output
output 'tPExcrLemn'
   description   ' rPDLemn / (cPDLemnMin + rPDLemn) * rPDLemn   * tD'
end-output
output 'tPExcrLemS'
   description   ' bfRootLemn * tPExcrLemn'
end-output
output 'tPExcrLemW'
   description   ' tPExcrLemn - tPExcrLemnS'
end-output
output 'tPMortLemn'
   description   ' rPDLemn * tDMortLemn'
end-output
output 'tPMortLem4'
   description   ' fDissMortVeg * tPMortLemn'
end-output
output 'tPMortLemS'
   description   ' bfRootLemn * tPMortLemnPO4'
end-output
output 'tPMortLemW'
   description   ' tPMortLemnPO4 - tPMortLemnPO4S'
end-output
output 'tPMortLemt'
   description   ' tPMortLemn - tPMortLemnPO4'
end-output
output 'tPMortLetW'
   description   ' fDetWMortLemn * (1.0 - bfRootLemn) *   tPMortLemn'
end-output
output 'tPMortLetS'
   description   ' tPMortLemnDet - tPMortLemnDetW'
end-output
output 'tPGrazLemn'
   description   ' rPDLemn * tDGrazLemnBird'
end-output
output 'tPBedLemn'
   description   ' tPMigrLemn + tPUptLemn - tPExcrLemn - tPMortLemn'
end-output
output 'tNExcrLemn'
   description   ' rNDLemn / (cNDLemnMin + rNDLemn) * rNDLemn   * tD'
end-output
output 'tNExcrLemS'
   description   ' bfRootLemn * tNExcrLemn'
end-output
output 'tNExcrLemW'
   description   ' tNExcrLemn - tNExcrLemnS'
end-output
output 'tNMortLemn'
   description   ' rNDLemn * tDMortLemn'
end-output
output 'tNMortLem4'
   description   ' fDissMortVeg * tNMortLemn'
end-output
output 'tNMortLemS'
   description   ' bfRootLemn * tNMortLemnNH4'
end-output
output 'tNMortLemW'
   description   ' tNMortLemnNH4 - tNMortLemnNH4S'
end-output
output 'tNMortLemt'
   description   ' tNMortLemn - tNMortLemnNH4'
end-output
output 'tNMortLetW'
   description   ' fDetWMortLemn * (1.0 - bfRootLemn) *   tNMortLemn'
end-output
output 'tNMortLetS'
   description   ' tNMortLemnDet - tNMortLemnDetW'
end-output
output 'tNGrazLemn'
   description   ' rNDLemn * tDGrazLemnBird'
end-output
output 'tNBedLemn'
   description   ' tNMigrLemn + tNUptLemn - tNExcrLemn - tNMortLemn'
end-output
output 'rPDNymp'
   description   ' sPNymp / (sDNymp+NearZero)'
end-output
output 'rNDNymp'
   description   ' sNNymp / (sDNymp+NearZero)'
end-output
output 'tDMigrNymp'
   description   ' kMigrNymp * (cDNympIn - sDNymp)'
end-output
output 'tPMigrNymp'
   description   ' kMigrNymp * (cPDNymp0* cDNympIn - sPNymp)'
end-output
output 'tNMigrNymp'
   description   ' kMigrNymp * (cNDNymp0* cDNympIn - sNNymp)'
end-output
output 'uFunTmProp'
   description   ' cQ10ProdNymp ** (0.1 * (uTm - cTmRef))'
end-output
output 'uFunTmRemp'
   description   ' cQ10RespNymp ** (0.1 * (uTm - cTmRef))'
end-output
output 'aVPUptMaxp'
   description   ' MAX( 0.0,  cVPUptMaxNymp * uFunTmProdNymp *  (cPD'
end-output
output 'aVPUptNymp'
   description   ' sPO4W * aVPUptMaxCrNymp /  (aVPUptMaxCrNymp / cAf'
end-output
output 'tPUptNympW'
   description   ' aVPUptNympW * (aDSubNymp + aDFloatNymp)'
end-output
output 'aVPUptNymS'
   description   ' oPO4S * aVPUptMaxCrNymp /  (aVPUptMaxCrNymp / cAf'
end-output
output 'tPUptNympS'
   description   ' aVPUptNympS * aDRootNymp'
end-output
output 'tPUptNymp'
   description   ' tPUptNympW + tPUptNympS'
end-output
output 'aVNUptMaxp'
   description   ' MAX( 0.0,  cVNUptMaxNymp * uFunTmProdNymp *  (cND'
end-output
output 'ahNUptNymp'
   description   ' aVNUptMaxCrNymp / cAffNUptNymp'
end-output
output 'aVNUptNymp'
   description   ' oNDissW * aVNUptMaxCrNymp / (ahNUptNymp + oNDissW'
end-output
output 'tNUptNympW'
   description   ' aVNUptNympW * (aDSubNymp + aDFloatNymp)'
end-output
output 'afNH4UptNy'
   description   ' sNH4W * sNO3W / ((ahNUptNymp + sNH4W) *  (ahNUptN'
end-output
output 'tNUptNH4Ny'
   description   ' afNH4UptNympW * tNUptNympW'
end-output
output 'tNUptNO3Ny'
   description   ' tNUptNympW - tNUptNH4NympW'
end-output
output 'aVNUptNymS'
   description   ' oNDissS * aVNUptMaxCrNymp / (ahNUptNymp + oNDissS'
end-output
output 'tNUptNympS'
   description   ' aVNUptNympS * aDRootNymp'
end-output
output 'afNH4UptNS'
   description   ' oNH4S * oNO3S / ((ahNUptNymp + oNH4S +NearZero) *'
end-output
output 'tNUptNH4NS'
   description   ' afNH4UptNympS * tNUptNympS'
end-output
output 'tNUptNO3NS'
   description   ' tNUptNympS - tNUptNH4NympS'
end-output
output 'tNUptNymp'
   description   ' tNUptNympW + tNUptNympS'
end-output
output 'aLPAR1Nymp'
   description   '  uLPAR0 * EXP(- aExtCoefOpen * aDepth1Nymp)'
end-output
output 'aLPAR2Nymp'
   description   '  aLPAR1Nymp * EXP(- aExtCoef   * (aDepth2Nymp - a'
end-output
output 'uhLNymp'
   description   ' hLRefNymp * uFunTmProdNymp'
end-output
output 'aLLimShoop'
   description   ' fEmergNymp + fFloatNymp * (1.0 - afCovEmergVeg) +'
end-output
output 'aMuTmLNymp'
   description   ' ufDay * bfShootNymp * aLLimShootNymp   * uFunTmPr'
end-output
output 'aPLimNymp'
   description   ' MAX(0.0, (1.0 - cPDNympMin / rPDNymp)   * cPDNymp'
end-output
output 'aNLimNymp'
   description   ' MAX(0.0, (1.0 - cNDNympMin / rNDNymp)   * cNDNymp'
end-output
output 'aNutLimNym'
   description   ' MIN( aPLimNymp, aNLimNymp)'
end-output
output 'aMuNymp'
   description   ' aMuTmLNymp * aNutLimNymp'
end-output
output 'bkMortNymp'
   description   ' kMortNympSum'
end-output
output 'akDIncrNym'
   description   ' aMuTmLNymp - kDRespNymp * uFunTmRespNymp   - bkMo'
end-output
output 'tDEnvNymp'
   description   ' MAX(0.0, akDIncrNymp / (cDCarrNymp+NearZero)   *'
end-output
output 'tDEnvProdN'
   description   ' aMuNymp / cMuMaxNymp * tDEnvNymp'
end-output
output 'tDProdNymp'
   description   ' MAX(0.0, aMuNymp * sDNymp  - tDEnvProdNymp)'
end-output
output 'tDProdSubN'
   description   ' bfSubNymp * tDProdNymp'
end-output
output 'tDRespNymp'
   description   ' kDRespNymp * uFunTmRespNymp * sDNymp'
end-output
output 'tDEnvMortN'
   description   ' tDEnvNymp - tDEnvProdNymp'
end-output
output 'tDMortNymp'
   description   ' bkMortNymp * sDNymp + tDEnvMortNymp'
end-output
output 'tDMortNymW'
   description   ' fDetWMortNymp * (1.0 - bfRootNymp) * tDMortNymp'
end-output
output 'tDMortNymS'
   description   ' tDMortNymp - tDMortNympW'
end-output
output 'tDGrazNymp'
   description   ' cPrefNympBird * sDNymp / (hDVegBird + sDNymp)  *'
end-output
output 'bkManNymp'
   description   ' - log(1.0 - fManNymp) / cLengMan'
end-output
output 'tDManNymp'
   description   ' bkManNymp * sDNymp'
end-output
output 'tPManNymp'
   description   ' rPDNymp * tDManNymp'
end-output
output 'tNManNymp'
   description   ' rNDNymp * tDManNymp'
end-output
output 'tDBedNymp'
   description   ' tDMigrNymp + tDProdNymp - tDRespNymp - tDMortNymp'
end-output
output 'tO2ProdNym'
   description   ' molO2molC * cCPerDW * tDProdNymp'
end-output
output 'tO2RespNym'
   description   ' molO2molC * cCPerDW * bfSubNymp * tDRespNymp   *'
end-output
output 'tO2RespNyS'
   description   ' molO2molC * cCPerDW * bfRootNymp * tDRespNymp   *'
end-output
output 'tO2ProdNyS'
   description   ' MIN (tO2RespNympS, tO2ProdNymp)'
end-output
output 'tO2ProdNyW'
   description   ' MIN( tO2ProdNymp - tO2ProdNympS,   bfSubNymp * tO'
end-output
output 'tO2UptNO3N'
   description   ' O2PerNO3 * molO2molN * bfSubNymp * tNUptNO3NympW'
end-output
output 'tO2UptNOpS'
   description   ' O2PerNO3 * molO2molN * tNUptNO3NympS'
end-output
output 'tPExcrNymp'
   description   ' rPDNymp / (cPDNympMin + rPDNymp) * rPDNymp   * tD'
end-output
output 'tPExcrNymS'
   description   ' bfRootNymp * tPExcrNymp'
end-output
output 'tPExcrNymW'
   description   ' tPExcrNymp - tPExcrNympS'
end-output
output 'tPMortNymp'
   description   ' rPDNymp * tDMortNymp'
end-output
output 'tPMortNym4'
   description   ' fDissMortVeg * tPMortNymp'
end-output
output 'tPMortNymS'
   description   ' bfRootNymp * tPMortNympPO4'
end-output
output 'tPMortNymW'
   description   ' tPMortNympPO4 - tPMortNympPO4S'
end-output
output 'tPMortNymt'
   description   ' tPMortNymp - tPMortNympPO4'
end-output
output 'tPMortNytW'
   description   ' fDetWMortNymp * (1.0 - bfRootNymp) *   tPMortNymp'
end-output
output 'tPMortNytS'
   description   ' tPMortNympDet - tPMortNympDetW'
end-output
output 'tPGrazNymp'
   description   ' rPDNymp * tDGrazNympBird'
end-output
output 'tPBedNymp'
   description   ' tPMigrNymp + tPUptNymp - tPExcrNymp - tPMortNymp'
end-output
output 'tNExcrNymp'
   description   ' rNDNymp / (cNDNympMin + rNDNymp) * rNDNymp   * tD'
end-output
output 'tNExcrNymS'
   description   ' bfRootNymp * tNExcrNymp'
end-output
output 'tNExcrNymW'
   description   ' tNExcrNymp - tNExcrNympS'
end-output
output 'tNMortNymp'
   description   ' rNDNymp * tDMortNymp'
end-output
output 'tNMortNym4'
   description   ' fDissMortVeg * tNMortNymp'
end-output
output 'tNMortNymS'
   description   ' bfRootNymp * tNMortNympNH4'
end-output
output 'tNMortNymW'
   description   ' tNMortNympNH4 - tNMortNympNH4S'
end-output
output 'tNMortNymt'
   description   ' tNMortNymp - tNMortNympNH4'
end-output
output 'tNMortNytW'
   description   ' fDetWMortNymp * (1.0 - bfRootNymp) *   tNMortNymp'
end-output
output 'tNMortNytS'
   description   ' tNMortNympDet - tNMortNympDetW'
end-output
output 'tNGrazNymp'
   description   ' rNDNymp * tDGrazNympBird'
end-output
output 'tNBedNymp'
   description   ' tNMigrNymp + tNUptNymp - tNExcrNymp - tNMortNymp'
end-output
output 'rPDHelo'
   description   ' sPHelo / (sDHelo+NearZero)'
end-output
output 'rNDHelo'
   description   ' sNHelo / (sDHelo+NearZero)'
end-output
output 'tDMigrHelo'
   description   ' kMigrHelo * (cDHeloIn - sDHelo)'
end-output
output 'tPMigrHelo'
   description   ' kMigrHelo * (cPDHelo0* cDHeloIn - sPHelo)'
end-output
output 'tNMigrHelo'
   description   ' kMigrHelo * (cNDHelo0* cDHeloIn - sNHelo)'
end-output
output 'uFunTmProo'
   description   ' cQ10ProdHelo ** (0.1 * (uTm - cTmRef))'
end-output
output 'uFunTmReso'
   description   ' cQ10RespHelo ** (0.1 * (uTm - cTmRef))'
end-output
output 'aVPUptMaxo'
   description   ' MAX( 0.0,  cVPUptMaxHelo * uFunTmProdHelo *  (cPD'
end-output
output 'aVPUptHelo'
   description   ' sPO4W * aVPUptMaxCrHelo /  (aVPUptMaxCrHelo / cAf'
end-output
output 'tPUptHeloW'
   description   ' aVPUptHeloW * (aDSubHelo + aDFloatHelo)'
end-output
output 'aVPUptHelS'
   description   ' oPO4S * aVPUptMaxCrHelo /  (aVPUptMaxCrHelo / cAf'
end-output
output 'tPUptHeloS'
   description   ' aVPUptHeloS * aDRootHelo'
end-output
output 'tPUptHelo'
   description   ' tPUptHeloW + tPUptHeloS'
end-output
output 'aVNUptMaxo'
   description   ' MAX( 0.0,  cVNUptMaxHelo * uFunTmProdHelo *  (cND'
end-output
output 'ahNUptHelo'
   description   ' aVNUptMaxCrHelo / cAffNUptHelo'
end-output
output 'aVNUptHelo'
   description   ' oNDissW * aVNUptMaxCrHelo / (ahNUptHelo + oNDissW'
end-output
output 'tNUptHeloW'
   description   ' aVNUptHeloW * (aDSubHelo + aDFloatHelo)'
end-output
output 'afNH4UptHe'
   description   ' sNH4W * sNO3W / ((ahNUptHelo + sNH4W) *  (ahNUptH'
end-output
output 'tNUptNH4He'
   description   ' afNH4UptHeloW * tNUptHeloW'
end-output
output 'tNUptNO3He'
   description   ' tNUptHeloW - tNUptNH4HeloW'
end-output
output 'aVNUptHelS'
   description   ' oNDissS * aVNUptMaxCrHelo / (ahNUptHelo + oNDissS'
end-output
output 'tNUptHeloS'
   description   ' aVNUptHeloS * aDRootHelo'
end-output
output 'afNH4UptHS'
   description   ' oNH4S * oNO3S / ((ahNUptHelo + oNH4S +NearZero) *'
end-output
output 'tNUptNH4HS'
   description   ' afNH4UptHeloS * tNUptHeloS'
end-output
output 'tNUptNO3HS'
   description   ' tNUptHeloS - tNUptNH4HeloS'
end-output
output 'tNUptHelo'
   description   ' tNUptHeloW + tNUptHeloS'
end-output
output 'aLPAR1Helo'
   description   '  uLPAR0 * EXP(- aExtCoefOpen * aDepth1Helo)'
end-output
output 'aLPAR2Helo'
   description   '  aLPAR1Helo * EXP(- aExtCoef   * (aDepth2Helo - a'
end-output
output 'uhLHelo'
   description   ' hLRefHelo * uFunTmProdHelo'
end-output
output 'aLLimShooo'
   description   ' fEmergHelo + fFloatHelo * (1.0 - afCovEmergVeg) +'
end-output
output 'aMuTmLHelo'
   description   ' ufDay * bfShootHelo * aLLimShootHelo   * uFunTmPr'
end-output
output 'aPLimHelo'
   description   ' MAX(0.0, (1.0 - cPDHeloMin / rPDHelo)   * cPDHelo'
end-output
output 'aNLimHelo'
   description   ' MAX(0.0, (1.0 - cNDHeloMin / rNDHelo)   * cNDHelo'
end-output
output 'aNutLimHel'
   description   ' MIN( aPLimHelo, aNLimHelo)'
end-output
output 'aMuHelo'
   description   ' aMuTmLHelo * aNutLimHelo'
end-output
output 'bkMortHelo'
   description   ' kMortHeloSum'
end-output
output 'akDIncrHel'
   description   ' aMuTmLHelo - kDRespHelo * uFunTmRespHelo   - bkMo'
end-output
output 'tDEnvHelo'
   description   ' MAX(0.0, akDIncrHelo / (cDCarrHelo+NearZero)   *'
end-output
output 'tDEnvProdH'
   description   ' aMuHelo / cMuMaxHelo * tDEnvHelo'
end-output
output 'tDProdHelo'
   description   ' MAX(0.0, aMuHelo * sDHelo  - tDEnvProdHelo)'
end-output
output 'tDProdSubH'
   description   ' bfSubHelo * tDProdHelo'
end-output
output 'tDRespHelo'
   description   ' kDRespHelo * uFunTmRespHelo * sDHelo'
end-output
output 'tDEnvMortH'
   description   ' tDEnvHelo - tDEnvProdHelo'
end-output
output 'tDMortHelo'
   description   ' bkMortHelo * sDHelo + tDEnvMortHelo'
end-output
output 'tDMortHelW'
   description   ' fDetWMortHelo * (1.0 - bfRootHelo) * tDMortHelo'
end-output
output 'tDMortHelS'
   description   ' tDMortHelo - tDMortHeloW'
end-output
output 'tDGrazHelo'
   description   ' cPrefHeloBird * sDHelo / (hDVegBird + sDHelo)  *'
end-output
output 'bkManHelo'
   description   ' - log(1.0 - fManHelo) / cLengMan'
end-output
output 'tDManHelo'
   description   ' bkManHelo * sDHelo'
end-output
output 'tPManHelo'
   description   ' rPDHelo * tDManHelo'
end-output
output 'tNManHelo'
   description   ' rNDHelo * tDManHelo'
end-output
output 'tDBedHelo'
   description   ' tDMigrHelo + tDProdHelo - tDRespHelo - tDMortHelo'
end-output
output 'tO2ProdHel'
   description   ' molO2molC * cCPerDW * tDProdHelo'
end-output
output 'tO2RespHel'
   description   ' molO2molC * cCPerDW * bfSubHelo * tDRespHelo   *'
end-output
output 'tO2RespHeS'
   description   ' molO2molC * cCPerDW * bfRootHelo * tDRespHelo   *'
end-output
output 'tO2ProdHeS'
   description   ' MIN (tO2RespHeloS, tO2ProdHelo)'
end-output
output 'tO2ProdHeW'
   description   ' MIN( tO2ProdHelo - tO2ProdHeloS,   bfSubHelo * tO'
end-output
output 'tO2UptNO3H'
   description   ' O2PerNO3 * molO2molN * bfSubHelo * tNUptNO3HeloW'
end-output
output 'tO2UptNOoS'
   description   ' O2PerNO3 * molO2molN * tNUptNO3HeloS'
end-output
output 'tPExcrHelo'
   description   ' rPDHelo / (cPDHeloMin + rPDHelo) * rPDHelo   * tD'
end-output
output 'tPExcrHelS'
   description   ' bfRootHelo * tPExcrHelo'
end-output
output 'tPExcrHelW'
   description   ' tPExcrHelo - tPExcrHeloS'
end-output
output 'tPMortHelo'
   description   ' rPDHelo * tDMortHelo'
end-output
output 'tPMortHel4'
   description   ' fDissMortVeg * tPMortHelo'
end-output
output 'tPMortHelS'
   description   ' bfRootHelo * tPMortHeloPO4'
end-output
output 'tPMortHelW'
   description   ' tPMortHeloPO4 - tPMortHeloPO4S'
end-output
output 'tPMortHelt'
   description   ' tPMortHelo - tPMortHeloPO4'
end-output
output 'tPMortHetW'
   description   ' fDetWMortHelo * (1.0 - bfRootHelo) *   tPMortHelo'
end-output
output 'tPMortHetS'
   description   ' tPMortHeloDet - tPMortHeloDetW'
end-output
output 'tPGrazHelo'
   description   ' rPDHelo * tDGrazHeloBird'
end-output
output 'tPBedHelo'
   description   ' tPMigrHelo + tPUptHelo - tPExcrHelo - tPMortHelo'
end-output
output 'tNExcrHelo'
   description   ' rNDHelo / (cNDHeloMin + rNDHelo) * rNDHelo   * tD'
end-output
output 'tNExcrHelS'
   description   ' bfRootHelo * tNExcrHelo'
end-output
output 'tNExcrHelW'
   description   ' tNExcrHelo - tNExcrHeloS'
end-output
output 'tNMortHelo'
   description   ' rNDHelo * tDMortHelo'
end-output
output 'tNMortHel4'
   description   ' fDissMortVeg * tNMortHelo'
end-output
output 'tNMortHelS'
   description   ' bfRootHelo * tNMortHeloNH4'
end-output
output 'tNMortHelW'
   description   ' tNMortHeloNH4 - tNMortHeloNH4S'
end-output
output 'tNMortHelt'
   description   ' tNMortHelo - tNMortHeloNH4'
end-output
output 'tNMortHetW'
   description   ' fDetWMortHelo * (1.0 - bfRootHelo) *   tNMortHelo'
end-output
output 'tNMortHetS'
   description   ' tNMortHeloDet - tNMortHeloDetW'
end-output
output 'tNGrazHelo'
   description   ' rNDHelo * tDGrazHeloBird'
end-output
output 'tNBedHelo'
   description   ' tNMigrHelo + tNUptHelo - tNExcrHelo - tNMortHelo'
end-output
output 'tDMigrVeg'
   description   ' tDMigrElod      + tDMigrChar      +   tDMigrCera'
end-output
output 'tPMigrVeg'
   description   ' tPMigrElod      + tPMigrChar      +   tPMigrCera'
end-output
output 'tNMigrVeg'
   description   ' tNMigrElod      + tNMigrChar      +   tNMigrCera'
end-output
output 'tDProdVeg'
   description   ' tDProdElod      + tDProdChar      +   tDProdCera'
end-output
output 'tPUptVegW'
   description   ' tPUptElodW     + tPUptCharW     +   tPUptCeraW'
end-output
output 'tPUptVegS'
   description   ' tPUptElodS     + tPUptCharS     +   tPUptCeraS'
end-output
output 'tNUptNH4Ve'
   description   ' tNUptNH4ElodW  + tNUptNH4CharW  +   tNUptNH4CeraW'
end-output
output 'tNUptNH4VS'
   description   ' tNUptNH4ElodS  + tNUptNH4CharS  +   tNUptNH4CeraS'
end-output
output 'tNUptNO3Ve'
   description   ' tNUptNO3ElodW  + tNUptNO3CharW  +   tNUptNO3CeraW'
end-output
output 'tNUptNO3VS'
   description   ' tNUptNO3ElodS  + tNUptNO3CharS  +   tNUptNO3CeraS'
end-output
output 'tDRespVeg'
   description   ' tDRespElod      + tDRespChar      +   tDRespCera'
end-output
output 'tPExcrVegW'
   description   ' tPExcrElodW    + tPExcrCharW    +   tPExcrCeraW'
end-output
output 'tPExcrVegS'
   description   ' tPExcrElodS    + tPExcrCharS    +   tPExcrCeraS'
end-output
output 'tNExcrVegW'
   description   ' tNExcrElodW    + tNExcrCharW    +   tNExcrCeraW'
end-output
output 'tNExcrVegS'
   description   ' tNExcrElodS    + tNExcrCharS    +   tNExcrCeraS'
end-output
output 'tO2ProdVeg'
   description   ' tO2ProdElod   + tO2ProdChar   + tO2ProdCera   + t'
end-output
output 'tO2ProdVeW'
   description   ' tO2ProdElodW + tO2ProdCharW + tO2ProdCeraW   + tO'
end-output
output 'tO2ProdVeS'
   description   ' tO2ProdElodS + tO2ProdCharS + tO2ProdCeraS   + tO'
end-output
output 'tO2RespVeg'
   description   ' tO2RespElodW + tO2RespCharW + tO2RespCeraW   + tO'
end-output
output 'tO2RespVeS'
   description   ' tO2RespElodS + tO2RespCharS + tO2RespCeraS   + tO'
end-output
output 'tO2UptNO3V'
   description   ' tO2UptNO3ElodW + tO2UptNO3CharW + tO2UptNO3CeraW'
end-output
output 'tO2UptNOgS'
   description   ' tO2UptNO3ElodS + tO2UptNO3CharS + tO2UptNO3CeraS'
end-output
output 'tDMortVegW'
   description   ' tDMortElodW    + tDMortCharW    +   tDMortCeraW'
end-output
output 'tDMortVegS'
   description   ' tDMortElodS    + tDMortCharS    +   tDMortCeraS'
end-output
output 'tPMortVegP'
   description   ' tPMortElodPO4W + tPMortCharPO4W +   tPMortCeraPO4'
end-output
output 'tPMortVegD'
   description   ' tPMortElodDetW + tPMortCharDetW +   tPMortCeraDet'
end-output
output 'tPMortVegS'
   description   ' tPMortElodPO4S + tPMortCharPO4S +   tPMortCeraPO4'
end-output
output 'tPMortVetS'
   description   ' tPMortElodDetS + tPMortCharDetS +   tPMortCeraDet'
end-output
output 'tNMortVegN'
   description   ' tNMortElodNH4W + tNMortCharNH4W +   tNMortCeraNH4'
end-output
output 'tNMortVegD'
   description   ' tNMortElodDetW + tNMortCharDetW +   tNMortCeraDet'
end-output
output 'tNMortVegS'
   description   ' tNMortElodNH4S + tNMortCharNH4S +   tNMortCeraNH4'
end-output
output 'tNMortVetS'
   description   ' tNMortElodDetS + tNMortCharDetS +   tNMortCeraDet'
end-output
output 'tDGrazVegB'
   description   ' tDGrazElodBird + tDGrazCharBird + tDGrazCeraBird'
end-output
output 'tPGrazVegB'
   description   ' tPGrazElodBird + tPGrazCharBird + tPGrazCeraBird'
end-output
output 'tNGrazVegB'
   description   ' tNGrazElodBird + tNGrazCharBird + tNGrazCeraBird'
end-output
output 'tDManVeg'
   description   ' tDManElod      + tDManChar      +   tDManCera'
end-output
output 'tPManVeg'
   description   ' tPManElod      + tPManChar      +   tPManCera'
end-output
output 'tNManVeg'
   description   ' tNManElod      + tNManChar      +   tNManCera'
end-output
output 'aCovSub'
   description   ' MIN(100.0,aCovElod + aCovChar + aCovCera)'
end-output
output 'tDAssVegBi'
   description   ' fDAssBird * tDGrazVegBird'
end-output
output 'tDEgesBird'
   description   ' tDGrazVegBird - tDAssVegBird'
end-output
output 'tPAssVegBi'
   description   ' fDAssBird * tPGrazVegBird'
end-output
output 'tPEgesBird'
   description   ' tPGrazVegBird - tPAssVegBird'
end-output
output 'tPEgesBir4'
   description   ' fDissEgesBird * tPEgesBird'
end-output
output 'tPEgesBirt'
   description   ' tPEgesBird - tPEgesBirdPO4'
end-output
output 'tNAssVegBi'
   description   ' fDAssBird * tNGrazVegBird'
end-output
output 'tNEgesBird'
   description   ' tNGrazVegBird - tNAssVegBird'
end-output
output 'tNEgesBir4'
   description   ' fDissEgesBird * tNEgesBird'
end-output
output 'tNEgesBirt'
   description   ' tNEgesBird - tNEgesBirdNH4'
end-output
output 'wDBedDetW'
   description   '(tDMortVegW  + tDEgesBird) / sDepthW'
end-output
output 'tDBedDetS'
   description   ' tDMortVegS'
end-output
output 'tDBedTotT'
   description   ' tDMigrVeg + tDProdVeg - tDRespVeg - tDManVeg - tD'
end-output
output 'wPBedPO4W'
   description   '(- tPUptVegW + tPExcrVegW + tPMortVegPO4W + tPEges'
end-output
output 'wPBedDetW'
   description   '(tPMortVegDetW + tPEgesBirdDet) / sDepthW'
end-output
output 'tPBedPO4S'
   description   ' - tPUptVegS + tPExcrVegS + tPMortVegPO4S'
end-output
output 'tPBedDetS'
   description   ' tPMortVegDetS'
end-output
output 'tPBedTotT'
   description   ' tPMigrVeg - tPManVeg - tPAssVegBird'
end-output
output 'wNBedNH4W'
   description   '(- tNUptNH4VegW + tNExcrVegW + tNMortVegNH4W + tNE'
end-output
output 'wNBedNO3W'
   description   '  - tNUptNO3VegW / sDepthW'
end-output
output 'wNBedDetW'
   description   '(tNMortVegDetW + tNEgesBirdDet) / sDepthW'
end-output
output 'tNBedNH4S'
   description   '  - tNUptNH4VegS + tNExcrVegS + tNMortVegNH4S'
end-output
output 'tNBedNO3S'
   description   '  - tNUptNO3VegS'
end-output
output 'tNBedDetS'
   description   '  tNMortVegDetS'
end-output
output 'tNBedTotT'
   description   ' tNMigrVeg - tNManVeg - tNAssVegBird'
end-output
output 'tO2BedW'
   description   ' tO2ProdVegW - tO2RespVegW + tO2UptNO3VegW'
end-output
output 'tO2BedS'
   description   ' tO2ProdVegS - tO2RespVegS + tO2UptNO3VegS'
end-output
output 'UseLoss'
   description   ' 1.0'
end-output
output 'uFunTmLoss'
   description   ' EXP(-0.5/cSigTmLoss**2 *((uTm-cTmOptLoss)**2 -(cT'
end-output
output 'rPDPhytW'
   description   ' sPPhytW /(sDPhytW+NearZero)'
end-output
output 'rNDPhytW'
   description   ' sNPhytW /(sDPhytW+NearZero)'
end-output
output 'rPDPhytS'
   description   ' sPPhytS /(sDPhytS+NearZero)'
end-output
output 'rNDPhytS'
   description   ' sNPhytS /(sDPhytS+NearZero)'
end-output
output 'uFunTmPhyt'
   description   ' EXP(-0.5/cSigTmPhyt**2 *((uTm-cTmOptPhyt)**2 - (c'
end-output
output 'uFunTmProt'
   description   ' uFunTmPhyt'
end-output
output 'uFunTmRest'
   description   ' uFunTmPhyt'
end-output
output 'aVPUptMaxt'
   description   ' MAX(0.0,cVPUptMaxPhyt * uFunTmProdPhyt *(cPDPhytM'
end-output
output 'aVPUptPhyt'
   description   ' sPO4W * aVPUptMaxCrPhyt /(aVPUptMaxCrPhyt  / cAff'
end-output
output 'wPUptPhyt'
   description   ' aVPUptPhyt * sDPhytW'
end-output
output 'aVNUptMaxt'
   description   ' MAX(0.0,cVNUptMaxPhyt * uFunTmProdPhyt * (cNDPhyt'
end-output
output 'ahNUptPhyt'
   description   ' aVNUptMaxCrPhyt / cAffNUptPhyt'
end-output
output 'aVNUptPhyt'
   description   ' oNDissW * aVNUptMaxCrPhyt /(ahNUptPhyt  + oNDissW'
end-output
output 'wNUptPhyt'
   description   ' aVNUptPhyt * sDPhytW'
end-output
output 'afNH4UptPh'
   description   ' sNH4W * sNO3W /((ahNUptPhyt +  sNH4W) *(ahNUptPhy'
end-output
output 'wNUptNH4Ph'
   description   ' afNH4UptPhyt * wNUptPhyt'
end-output
output 'wNUptNO3Ph'
   description   ' wNUptPhyt - wNUptNH4Phyt'
end-output
output 'uMuMaxTmPh'
   description   ' cMuMaxPhyt * uFunTmProdPhyt'
end-output
output 'aPLimPhyt'
   description   ' MAX(0.0,(1.0 - cPDPhytMin / rPDPhytW)   * cPDPhyt'
end-output
output 'aNLimPhyt'
   description   ' MAX(0.0,(1.0 - cNDPhytMin / rNDPhytW)   * cNDPhyt'
end-output
output 'aSiLimPhyt'
   description   ' 1.0'
end-output
output 'aLLimPhyt'
   description   '   UseSteelePhyt *(EXP(1.0) /(aExtCoef * sDepthW)'
end-output
output 'aMuTmLPhyt'
   description   ' ufDay *(1.0 - afCovSurfVeg) * aLLimPhyt  * uMuMax'
end-output
output 'aNutLimPhy'
   description   ' MIN(aPLimPhyt,aNLimPhyt,aSiLimPhyt)'
end-output
output 'aMuPhyt'
   description   '  aNutLimPhyt * aMuTmLPhyt'
end-output
output 'wDAssPhyt'
   description   ' aMuPhyt*sDPhytW'
end-output
output 'rChDPhyt'
   description   ' cChDPhytMax -(cChDPhytMax - cChDPhytMin) *  aLLim'
end-output
output 'oChlaPhyt'
   description   ' mgPerg * rChDPhyt * sDPhytW'
end-output
output 'aExtChPhyt'
   description   ' cExtSpPhyt / rChDPhyt'
end-output
output 'ukDRespTmP'
   description   ' kDRespPhyt * uFunTmRespPhyt'
end-output
output 'wDRespPhyt'
   description   ' ukDRespTmPhyt * sDPhytW'
end-output
output 'ukLossTmPh'
   description   ' UseLoss * kLossPhyt * uFunTmLoss'
end-output
output 'wDLossPhyt'
   description   ' ukLossTmPhyt * sDPhytW'
end-output
output 'wDMortPhyt'
   description   ' kMortPhytW * sDPhytW'
end-output
output 'uCorVSetPh'
   description   ' cVSetPhyt * aFunTauSetOM * uFunTmSet'
end-output
output 'tDSetPhyt'
   description   ' uCorVSetPhyt * sDPhytW'
end-output
output 'tDResusPht'
   description   ' sDPhytS /(aDPhytS+NearZero) * tDResusPhytTot'
end-output
output 'tDRespPhyt'
   description   ' ukDRespTmPhyt * sDPhytS'
end-output
output 'tDMortPhyt'
   description   ' kMortPhytS * sDPhytS'
end-output
output 'ukDDecPhyt'
   description   ' ukDRespTmPhyt + ukLossTmPhyt + kMortPhytW   +(uCo'
end-output
output 'wPExcrPhyt'
   description   ' rPDPhytW /(cPDPhytMin + rPDPhytW) * rPDPhytW   *'
end-output
output 'wPLossPhyt'
   description   ' rPDPhytW * wDLossPhyt'
end-output
output 'wPMortPhyt'
   description   ' kMortPhytW * sPPhytW'
end-output
output 'tPSetPhyt'
   description   ' rPDPhytW * tDSetPhyt'
end-output
output 'tPResusPhy'
   description   ' rPDPhytS * tDResusPhyt'
end-output
output 'tPExcrPhyt'
   description   ' rPDPhytS /(cPDPhytMin + rPDPhytS) * rPDPhytS   *'
end-output
output 'tPMortPhyt'
   description   ' kMortPhytS * sPPhytS'
end-output
output 'wNExcrPhyt'
   description   ' rNDPhytW /(cNDPhytMin + rNDPhytW) * rNDPhytW   *'
end-output
output 'wNLossPhyt'
   description   ' rNDPhytW * wDLossPhyt'
end-output
output 'wNMortPhyt'
   description   ' kMortPhytW * sNPhytW'
end-output
output 'tNSetPhyt'
   description   ' rNDPhytW * tDSetPhyt'
end-output
output 'tNResusPhy'
   description   ' rNDPhytS * tDResusPhyt'
end-output
output 'tNExcrPhyt'
   description   ' rNDPhytS /(cNDPhytMin + rNDPhytS) * rNDPhytS   *'
end-output
output 'tNMortPhyt'
   description   ' kMortPhytS * sNPhytS'
end-output
output 'wDPrimPhyt'
   description   ' wDAssPhyt - wDRespPhytW - wDLossPhyt  - wDMortPhy'
end-output
output 'wPPrimPhyt'
   description   ' wPUptPhyt - wPExcrPhytW - wPLossPhyt   - wPMortPh'
end-output
output 'wNPrimPhyt'
   description   ' wNUptPhyt - wNExcrPhytW - wNLossPhyt  - wNMortPhy'
end-output
output 'tDPrimPhyt'
   description   ' tDSetPhyt - tDResusPhyt - tDMortPhytS   - tDRespP'
end-output
output 'tPPrimPhyt'
   description   ' tPSetPhyt - tPResusPhyt - tPMortPhytS   - tPExcrP'
end-output
output 'tNPrimPhyt'
   description   ' tNSetPhyt - tNResusPhyt - tNMortPhytS   - tNExcrP'
end-output
output 'oChla'
   description   ' oChlaPhyt'
end-output
output 'wDPrimDetW'
   description   ' wDMortPhytW + wDLossPhyt'
end-output
output 'tDPrimDetS'
   description   ' tDMortPhytS'
end-output
output 'tDPrimTotT'
   description   '(wDAssPhyt - wDRespPhytW) * sDepthW - tDRespPhytS'
end-output
output 'wO2ProdPhy'
   description   ' molO2molC * cCPerDW * wDAssPhyt'
end-output
output 'wO2RespPhy'
   description   ' molO2molC * cCPerDW * wDRespPhytW * aCorO2BOD'
end-output
output 'wO2UptNO3P'
   description   ' O2PerNO3 * molO2molN * wNUptNO3Phyt'
end-output
output 'wO2PrimW'
   description   ' wO2ProdPhyt - wO2RespPhytW + wO2UptNO3Phyt'
end-output
output 'tO2RespPhy'
   description   ' molO2molC * cCPerDW * tDRespPhytS * afOxySed'
end-output
output 'tO2PrimS'
   description   ' tO2RespPhytS'
end-output
output 'wPMortPhyW'
   description   ' fDissMortPhyt * wPMortPhytW'
end-output
output 'wPMortPhtW'
   description   ' wPMortPhytW - wPMortPhytPO4W'
end-output
output 'wPLossPhy4'
   description   ' fDissLoss * wPLossPhyt'
end-output
output 'wPLossPhet'
   description   ' wPLossPhyt - wPLossPhytPO4'
end-output
output 'wPPrimPO4W'
   description   ' - wPUptPhyt + wPExcrPhytW   + wPLossPhytPO4 + wPM'
end-output
output 'wPPrimDetW'
   description   ' wPLossPhytDet + wPMortPhytDetW'
end-output
output 'tPMortPhyS'
   description   ' fDissMortPhyt * tPMortPhytS'
end-output
output 'tPMortPhtS'
   description   ' tPMortPhytS - tPMortPhytPO4S'
end-output
output 'tPPrimDetS'
   description   ' tPMortPhytDetS'
end-output
output 'tPPrimPO4S'
   description   ' tPExcrPhytS + tPMortPhytPO4S'
end-output
output 'tPPrimTotT'
   description   ' 0.0'
end-output
output 'wNMortPhyW'
   description   ' fDissMortPhyt * wNMortPhytW'
end-output
output 'wNMortPhtW'
   description   ' wNMortPhytW - wNMortPhytNH4W'
end-output
output 'wNLossPhy4'
   description   ' fDissLoss * wNLossPhyt'
end-output
output 'wNLossPhet'
   description   ' wNLossPhyt - wNLossPhytNH4'
end-output
output 'wNPrimNH4W'
   description   ' - wNUptNH4Phyt + wNExcrPhytW + wNLossPhytNH4   +'
end-output
output 'wNPrimNO3W'
   description   ' - wNUptNO3Phyt'
end-output
output 'wNPrimDetW'
   description   ' wNLossPhytDet + wNMortPhytDetW'
end-output
output 'tNMortPhyS'
   description   ' fDissMortPhyt * tNMortPhytS'
end-output
output 'tNMortPhtS'
   description   ' tNMortPhytS - tNMortPhytNH4S'
end-output
output 'tNPrimNH4S'
   description   ' tNExcrPhytS + tNMortPhytNH4S'
end-output
output 'tNPrimNO3S'
   description   ' 0.0'
end-output
output 'tNPrimDetS'
   description   ' tNMortPhytDetS'
end-output
output 'tNPrimTotT'
   description   ' 0.0'
end-output
output 'aPACoef'
   description   ' cPACoefMin  +(cPACoefMax - cPACoefMin) * hPACoef'
end-output
output 'bSecchiMax'
   description   ' sDepthW + cSecchiPlus'
end-output
output 'aSecchi'
   description   ' MIN(bSecchiMax,aPACoef / aExtCoefOpen)'
end-output
output 'aDepthEuph'
   description   ' cEuph * aSecchi'
end-output
output 'aRelDepthE'
   description   ' aDepthEuph / sDepthW'
end-output
output 'aChlaH'
   description   ' oChla * sDepthW'
end-output
output 'aCovPhytW'
   description   ' cCovSpPhyt *(oDPhytW * sDepthW)'
end-output
output 'rExtChPhyt'
   description   ' aExtPhyt /(oChla / mgPerg + NearZero)'
end-output
output 'tDSetTot'
   description   ' tDSetIM + tDSetDet + tDSetPhyt'
end-output
output 'tPSetTot'
   description   ' tPSetAIM + tPSetDet + tPSetPhyt'
end-output
output 'tNSetTot'
   description   ' tNSetDet + tNSetPhyt'
end-output
output 'tDResusTot'
   description   ' tDResusDead + tDResusPhytTot'
end-output
output 'tPResusTot'
   description   ' tPResusDet + tPResusAIM + tPResusPhyt + tPResusPO'
end-output
output 'tNResusTot'
   description   ' tNResusDet + tNResusNH4 + tNResusNO3 + tNResusPhy'
end-output
output 'bTimeDred'
   description   '(INT(TimeYears/cDredInterval) * cDredInterval) * D'
end-output
output 'aDepthStar'
   description   ' sDepthW'
end-output
output 'akDredDept'
   description   '(log(cDepthRef / aDepthStart)) / cLengDred'
end-output
output 'akDred'
   description   '(- log(1.0 - fEffDred)) / cLengDred'
end-output
output 'akDredBent'
   description   '(- log(1.0 - fEffDredBent)) / cLengDred'
end-output
output 'akDredLemn'
   description   '(- log(1.0 - fEffDredLemn)) / cLengDred'
end-output
output 'vDredDepth'
   description   ' akDredDepth * sDepthW'
end-output
output 'tDDredDetS'
   description   ' akDred * sDDetS'
end-output
output 'tPDredDetS'
   description   ' akDred * sPDetS'
end-output
output 'tNDredDetS'
   description   ' akDred * sNDetS'
end-output
output 'tPDredAIMS'
   description   ' akDred * sPAIMS'
end-output
output 'bRhoSolidl'
   description   ' fDOrgSoil * cRhoOM +(1 - fDOrgSoil) * cRhoIM'
end-output
output 'tDDredNetS'
   description   ' -(tDDredDetS / cRhoOM) * bRhoSolidSoil'
end-output
output 'tDDredNetI'
   description   '(1 - fDOrgSoil) * tDDredNetSoil'
end-output
output 'tDDredNetH'
   description   ' fDOrgSoil * tDDredNetSoil'
end-output
output 'tPDredNetH'
   description   ' cPDSoilOM * tDDredNetHumS'
end-output
output 'tNDredNetH'
   description   ' cNDSoilOM * tDDredNetHumS'
end-output
output 'tDDredPhyt'
   description   ' akDred * sDPhytS'
end-output
output 'tPDredPhyt'
   description   ' akDred * sPPhytS'
end-output
output 'tNDredPhyt'
   description   ' akDred * sNPhytS'
end-output
output 'tDDredElod'
   description   ' akDred * sDElod'
end-output
output 'tPDredElod'
   description   ' akDred * sPElod'
end-output
output 'tNDredElod'
   description   ' akDred * sNElod'
end-output
output 'tDDredCera'
   description   ' akDred * sDCera'
end-output
output 'tPDredCera'
   description   ' akDred * sPCera'
end-output
output 'tNDredCera'
   description   ' akDred * sNCera'
end-output
output 'tDDredChar'
   description   ' akDred * sDChar'
end-output
output 'tPDredChar'
   description   ' akDred * sPChar'
end-output
output 'tNDredChar'
   description   ' akDred * sNChar'
end-output
output 'tDDredLemn'
   description   ' akDredLemn * sDLemn'
end-output
output 'tPDredLemn'
   description   ' akDredLemn * sPLemn'
end-output
output 'tNDredLemn'
   description   ' akDredLemn * sNLemn'
end-output
output 'tDDredNymp'
   description   ' akDred * sDNymp'
end-output
output 'tPDredNymp'
   description   ' akDred * sPNymp'
end-output
output 'tNDredNymp'
   description   ' akDred * sNNymp'
end-output
output 'tDDredHelo'
   description   ' akDred * sDHelo'
end-output
output 'tPDredHelo'
   description   ' akDred * sPHelo'
end-output
output 'tNDredHelo'
   description   ' akDred * sNHelo'
end-output
output 'tDDredVeg'
   description   ' tDDredElod+tDDredCera+tDDredChar+tDDredLemn+tDDre'
end-output
output 'tPDredVeg'
   description   ' tPDredElod+tPDredCera+tPDredChar+tPDredLemn+tPDre'
end-output
output 'tNDredVeg'
   description   ' tNDredElod+tNDredCera+tNDredChar+tNDredLemn+tNDre'
end-output
output 'tDDredNetT'
   description   ' tDDredDetS - tDDredNetSoil + tDDredPhytS + tDDred'
end-output
output 'tPDredNetT'
   description   ' tPDredDetS - tPDredNetHumS + tPDredAIMS + tPDredP'
end-output
output 'tNDredNetT'
   description   ' tNDredDetS - tNDredNetHumS + tNDredPhytS + tNDred'
end-output
output 'tDIMS'
   description   ' tDAbioIMS'
end-output
output 'tDHumS'
   description   ' tDAbioHumS'
end-output
output 'tDDetS'
   description   ' tDAbioDetS + tDPrimDetS + tDWebDetS + tDBedDetS'
end-output
output 'vDeltaS'
   description   '(tDIMS / cRhoIM +(tDHumS + tDDetS) / cRhoOM) /(1.0'
end-output
output 'tDBurIM'
   description   '((tDHumS + tDDetS) +(cRhoOM / cRhoIM) * tDIMS) / ('
end-output
output 'tDBurOM'
   description   '(sDHumS + sDDetS) / sDIMS * tDBurIM'
end-output
output 'tDBurDet'
   description   ' sDDetS /(sDHumS + sDDetS) * tDBurOM'
end-output
output 'tDBurHum'
   description   ' tDBurOM - tDBurDet'
end-output
output 'tDBurTot'
   description   ' tDBurIM + tDBurOM'
end-output
output 'tPBurHum'
   description   ' rPDHumS * tDBurHum'
end-output
output 'tPBurDet'
   description   ' rPDDetS * tDBurDet'
end-output
output 'tPBurAIM'
   description   ' sPAIMS / sDIMS * tDBurIM'
end-output
output 'tPBurPO4'
   description   ' sPO4S *(vDeltaS / cDepthS)'
end-output
output 'tPBurTot'
   description   ' tPBurDet + tPBurHum + tPBurAIM + tPBurPO4'
end-output
output 'tNBurHum'
   description   ' rNDHumS * tDBurHum'
end-output
output 'tNBurDet'
   description   ' rNDDetS * tDBurDet'
end-output
output 'tNBurNH4'
   description   ' sNH4S *(vDeltaS / cDepthS)'
end-output
output 'tNBurNO3'
   description   ' sNO3S *(vDeltaS / cDepthS)'
end-output
output 'tNBurTot'
   description   ' tNBurDet + tNBurHum + tNBurNH4 + tNBurNO3'
end-output
output 'vDeltaW'
   description   ' 0.0'
end-output
output 'aRelDeltaW'
   description   '(vDeltaW + vDredDepthW) / sDepthW'
end-output
output 'dDepthW'
   description   ' vTranDepthW + vDeltaW + vDredDepthW'
end-output
output 'dPO4W'
   description   ' wPTranPO4W + wPAbioPO4W + wPPrimPO4W + wPBedPO4W'
end-output
output 'dPAIMW'
   description   ' wPTranAIMW + wPAbioAIMW - aRelDeltaW * sPAIMW - w'
end-output
output 'dNH4W'
   description   ' wNTranNH4W + wNAbioNH4W + wNPrimNH4W + wNBedNH4W'
end-output
output 'dNO3W'
   description   ' wNTranNO3W + wNAbioNO3W + wNPrimNO3W + wNBedNO3W'
end-output
output 'dO2W'
   description   ' wO2TranW + wO2AbioW + wO2PrimW + tO2BedW / sDepth'
end-output
output 'dDIMW'
   description   ' wDTranIMW + wDAbioIMW - aRelDeltaW * sDIMW - wDEx'
end-output
output 'dDDetW'
   description   ' wDTranDetW + wDAbioDetW + wDPrimDetW + wDBedDetW'
end-output
output 'dPDetW'
   description   ' wPTranDetW + wPAbioDetW + wPPrimDetW + wPBedDetW'
end-output
output 'dNDetW'
   description   ' wNTranDetW + wNAbioDetW + wNPrimDetW + wNBedDetW'
end-output
output 'dDPhytW'
   description   ' wDTranPhyt + wDPrimPhytW + wDWebPhytW - aRelDelta'
end-output
output 'dPPhytW'
   description   ' wPTranPhyt + wPPrimPhytW + wPWebPhytW - aRelDelta'
end-output
output 'dNPhytW'
   description   ' wNTranPhyt + wNPrimPhytW + wNWebPhytW - aRelDelta'
end-output
output 'dPO4S'
   description   ' tPAbioPO4S - tPBurPO4   + tPPrimPO4S + tPBedPO4S'
end-output
output 'dPAIMS'
   description   ' tPAbioAIMS - tPBurAIM - tPDredAIMS'
end-output
output 'dNH4S'
   description   ' tNAbioNH4S - tNBurNH4   + tNPrimNH4S + tNBedNH4S'
end-output
output 'dNO3S'
   description   ' tNAbioNO3S - tNBurNO3    + tNPrimNO3S + tNBedNO3S'
end-output
output 'dDIMS'
   description   ' tDAbioIMS - tDBurIM - tDDredNetIMS'
end-output
output 'dDHumS'
   description   ' tDAbioHumS - tDBurHum - tDDredNetHumS'
end-output
output 'dPHumS'
   description   ' tPAbioHumS - tPBurHum - tPDredNetHumS'
end-output
output 'dNHumS'
   description   ' tNAbioHumS - tNBurHum - tNDredNetHumS'
end-output
output 'dDDetS'
   description   ' tDAbioDetS - tDBurDet + tDPrimDetS + tDBedDetS +'
end-output
output 'dPDetS'
   description   ' tPAbioDetS - tPBurDet + tPPrimDetS + tPBedDetS +'
end-output
output 'dNDetS'
   description   ' tNAbioDetS - tNBurDet + tNPrimDetS + tNBedDetS +'
end-output
output 'dDPhytS'
   description   ' tDPrimPhytS + tDWebPhytS - tDDredPhytS'
end-output
output 'dPPhytS'
   description   ' tPPrimPhytS + tPWebPhytS - tPDredPhytS'
end-output
output 'dNPhytS'
   description   ' tNPrimPhytS + tNWebPhytS - tNDredPhytS'
end-output
output 'dDElod'
   description   ' tDBedElod - tDDredElod'
end-output
output 'dPElod'
   description   ' tPBedElod - tPDredElod'
end-output
output 'dNElod'
   description   ' tNBedElod - tNDredElod'
end-output
output 'dDChar'
   description   ' tDBedChar - tDDredChar'
end-output
output 'dPChar'
   description   ' tPBedChar - tPDredChar'
end-output
output 'dNChar'
   description   ' tNBedChar - tNDredChar'
end-output
output 'dDCera'
   description   ' tDBedCera - tDDredCera'
end-output
output 'dPCera'
   description   ' tPBedCera - tPDredCera'
end-output
output 'dNCera'
   description   ' tNBedCera - tNDredCera'
end-output
output 'dDLemn'
   description   ' tDBedLemn - tDDredLemn'
end-output
output 'dPLemn'
   description   ' tPBedLemn - tPDredLemn'
end-output
output 'dNLemn'
   description   ' tNBedLemn - tNDredLemn'
end-output
output 'dDNymp'
   description   ' tDBedNymp - tDDredNymp'
end-output
output 'dPNymp'
   description   ' tPBedNymp - tPDredNymp'
end-output
output 'dNNymp'
   description   ' tNBedNymp - tNDredNymp'
end-output
output 'dDHelo'
   description   ' tDBedHelo - tDDredHelo'
end-output
output 'dPHelo'
   description   ' tPBedHelo - tPDredHelo'
end-output
output 'dNHelo'
   description   ' tNBedHelo - tNDredHelo'
end-output
active-processes
   name  'HydDuflow' 'HydDuflow'
   name  'PD124' 'PD124'
end-active-processes
