///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.Reflection;
using System.IO;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DHYDRO.Modules.IO
{
    public partial class OpenProjectFile
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void WaitUntilProjectHasBeenOpened(RepoItemInfo progressbarInfo, string pathToProcessDefinitionFile)
        {
            var repos = DHYDRORepository.Instance;
            if (repos.DialogSelectFile.SelfInfo.Exists(Duration.FromMilliseconds(5000)))
            {
                repos.DialogSelectFile.FieldFilePath.Element.SetAttributeValue("Text", pathToProcessDefinitionFile);
                repos.DialogSelectFile.ButtonOpen.Click();
                Delay.Duration(1000, false);
            }
        	Report.Log(ReportLevel.Info, "Wait", "Waiting 2m to not exist. Associated repository item: 'progressbarInfo'", progressbarInfo, new ActionTimeout(120000));
            progressbarInfo.WaitForNotExists(120000);
        }

        public string CalculatePathToProcessDefinitionFile(string IsModelWAQ, string relativePathToProcessFile)
        {
        	var pathProcessFile = Path.GetFullPath(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location) + relativePathToProcessFile);
        	return pathProcessFile;
        }

    }
}
