///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DHYDRO.Modules.IO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SpecifyFileToExportTo recording.
    /// </summary>
    [TestModule("ad658c8e-eb55-433b-853a-d480d8c125c6", ModuleType.Recording, 1)]
    public partial class SpecifyFileToExportTo : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DHYDRO.DHYDRORepository repository.
        /// </summary>
        public static global::DHYDRO.DHYDRORepository repo = global::DHYDRO.DHYDRORepository.Instance;

        static SpecifyFileToExportTo instance = new SpecifyFileToExportTo();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SpecifyFileToExportTo()
        {
            FileName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SpecifyFileToExportTo Instance
        {
            get { return instance; }
        }

#region Variables

        string _FileName;

        /// <summary>
        /// Gets or sets the value of variable FileName.
        /// </summary>
        [TestVariable("f45d74d9-36b6-445d-a144-84af2629f2b3")]
        public string FileName
        {
            get { return _FileName; }
            set { _FileName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$FileName' on item 'DialogSelectAFileToExportTo.FieldFilePath'.", repo.DialogSelectAFileToExportTo.FieldFilePathInfo, new RecordItemIndex(0));
            repo.DialogSelectAFileToExportTo.FieldFilePath.Element.SetAttributeValue("Text", FileName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DialogSelectAFileToExportTo.ButtonSave' at Center.", repo.DialogSelectAFileToExportTo.ButtonSaveInfo, new RecordItemIndex(1));
            repo.DialogSelectAFileToExportTo.ButtonSave.Click();
            Delay.Milliseconds(0);
            
            Code.UserCodeLibrary.ClickIfExists(repo.ConfirmSaveAsDialog.ConfirmYesButtonInfo, ValueConverter.ArgumentFromString<int>("waitPeriodInMilliSeconds", "1000"));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
