#!/usr/bin/python3
"""
Update manuals within the SVN repository from a folder containing the manuals
with different covers, generated with generate_manuals.py.

This script is responsible for updating the pdfs within the setup folder,
with the manuals generated by the generate_manuals.py, in the user_manuals
repository.

This script can either be run stand-alone or used as a library. In stand-alone:

python3 update_manuals <path_to_repository_root> <path_to_manuals_root>
"""
__author__ = "Maarten Tegelaers"
__copyright__ = "Copyright (C) Stichting Deltares, 2019"
__version__ = "0.2"
__maintainer__ = "Maarten Tegelaers"
__email__ = "Maarten.Tegelaers@deltares.nl"
__status__ = "Production"


from pathlib import Path
import shutil
import argparse

from dataclasses import dataclass

import generate_manual_report as gmr

# Names based upon the folders generated by generate_manuals.py
DHYDRO1D2D_COVER = "dhydro1d2d"
DELFT3DFM1D2D_COVER = "delft3dfm1d2d"
DHYDRO_COVER = "dhydro"
DELFT3DFM_COVER = "delft3dfm2d3d"
SOBEK3_COVER = "sobek3-cover"


@dataclass
class CoverFolderNames:
    """
    CoverFolderNames defines the names of the folders in which the specific covers are
    stored. By default these are obtained from the constant values defined above, but
    can be overwritten through the arguments.
    """
    dhydro1d2d: str
    dhydro: str
    delft3dfm1d2d: str
    delft3dfm: str
    sobek3: str

class ManualInfo:
    """
    ManualInfo describes a single Manual within the setup folder of the
    repository.
    """
    def __init__(
        self, 
        full_path: Path,
        cover_names: CoverFolderNames,
    ):
        """
        Construct a new ManualInfo based upon the specified full_path.

        :param full_path: The full path to the Manual this ManualInfo describes
        :type full_path: Path
        :param d_hydro_cover_folder_name: The name of the d-hydro cover folder generated 
            by the generate_manuals.py.
        :type d_
        """
        self._path = full_path
        self._name = self.full_path.name.lower()
        self._cover_names = cover_names
        self._set_cover_type()

    @property
    def name(self) -> str:
        """ Get the name of this Manual. """
        return self._name

    @property
    def full_path(self) -> Path:
        """ Get the path of this Manual. """
        return self._path

    @property
    def cover(self) -> str:
        """ Get the type of cover of this Manual. """
        return self._cover

    def _set_cover_type(self) -> None:
        """
        Set the cover type based upon the name of the plugin folder, and manual folder.
        """
        # SOBEK cover: only happens when the plugin is sobek
        module = self.full_path.parent.parent.name
        if module == "Sobek":
            self._cover = self._cover_names.sobek3
            return

        # D-Hydro cover: if the plugin is not sobek and the cover type contains d-hydro
        cover_type = self.full_path.parent.name.lower()
        if "d-hydro" in cover_type:
            if "1d2d" in self.full_path.name.lower():
                print("name = {}".format(self.full_path.name.lower()))
                self._cover = self._cover_names.dhydro1d2d
            else :
                self._cover = self._cover_names.dhydro
            return

        # Delft3d: if the cover type does not contain d-hydro (this includes the framework)
        if "1d2d" in self.full_path.name.lower():            
            self._cover = self._cover_names.delft3dfm1d2d
            return        
        self._cover = self._cover_names.delft3dfm


def obtain_pdf_locations(path: Path, cover_names: CoverFolderNames) -> list:
    """
    Obtain all paths to pdf location in folders containing the phrase Manuals

    We assume that each manual pdf is located in a folder which contains the
    string "Manuals". This seems to be true for the NGHS solution.

    :param path: The path to the repository root.
    :type full_path: Path

    :returns: A list of ManualInfo objects describing the found manuals.
    """
    return list(ManualInfo(p, cover_names) for p in path.glob("**/*Manuals/*.pdf"))


def obtain_new_pdfs(path: Path, cover_names: CoverFolderNames) -> dict:
    """
    Obtain all relevant pdfs obtained by the manuals build script


    :param path: The path to the manual root.
    :type full_path: Path

    :returns: A dictionary mapping per cover the names of manuals onto paths.
    """
    manuals = {
        cover_names.sobek3: {},
        cover_names.dhydro1d2d: {},
        cover_names.dhydro: {},
        cover_names.delft3dfm1d2d: {},
        cover_names.delft3dfm: {}
    }

    for cover_type in manuals:
        for p in (path / Path(cover_type)).glob("*.pdf"):
            manuals[cover_type][p.name.lower()] = p.resolve()
    return manuals


def _generate_used_pdf_structure(pdfs: dict) -> dict:
    """
    Generate a dict corresponding with pdfs, where each
    inner value maps to False.
    """
    used_structure = {}
    for cover_type in pdfs:
        used_structure[cover_type] = {}

        for name in pdfs[cover_type]:
            used_structure[cover_type][name] = False

    return used_structure


def replace_existing_manuals_with_new(old_pdfs, new_pdfs, verbose: bool) -> None:
    """
    Replace all the paths specified in old_pdfs by the corresponding files in
    new_pdfs.

    If verbose is true, a report will be printed on finishing displaying the
    following information:

    * Replaced Manuals
    * Old Manuals not updated
    * New Manuals not used
    """
    used_structure = _generate_used_pdf_structure(new_pdfs)

    succeeded_manuals = []
    failed_manuals = []
    unused_manuals = []

    for manual_info in old_pdfs:
        try:
            src_location = new_pdfs[manual_info.cover][manual_info.name]
        except KeyError:
            failed_manuals.append(manual_info.full_path)
            continue

        trg_location = manual_info.full_path
        shutil.copy(str(src_location),
                    str(trg_location))

        succeeded_manuals.append(manual_info.full_path)
        used_structure[manual_info.cover][manual_info.name] = True

    if verbose:
        if succeeded_manuals:
            print("Copied manuals: ")
            for p in succeeded_manuals:
                print("  {}".format(p))
            print()

        if failed_manuals:
            print("Manuals without replacement:")
            for p in failed_manuals:
                print("  {}".format(p))
            print()

        for ct in used_structure:
            for manual in used_structure[ct]:
                if not used_structure[ct][manual]:
                    unused_manuals.append(new_pdfs[ct][manual])

        if unused_manuals:
            print("Generated Manuals which were not used:")
            for p in unused_manuals:
                print("  {}".format(p))
            print()
    
    return succeeded_manuals, failed_manuals, unused_manuals


def _report_covers(pdfs: dict) -> None:
    """
    Print the covers found by the obtain_new_pdfs function
    """
    n_covers = sum(len(pdfs[cover]) for cover in pdfs)
    print("Number of covers found: {}".format(n_covers))
    print()

    for cover in pdfs:
        print("{}: ".format(cover))
        for manual_name in pdfs[cover]:
            print("  {}".format(manual_name))
        print()


def _report_pdfs(pdfs: list) -> None:
    """
    Print the found locations
    """
    n_pdfs = len(pdfs)
    print("Number of pdfs found: {}".format(n_pdfs))

    for pdf in pdfs:
        print("{}: {}".format(pdf.name, pdf.cover))


def parse_arguments():
    """
    Parse the arguments with which this script was called through
    argparse.ArgumentParser
    """
    parser = argparse.ArgumentParser()

    parser.add_argument("svn_root_path", help="Path to the root of the SVN directory to update.")
    parser.add_argument("manual_root_path", help="Path to the root of the manuals.")
    parser.add_argument("--generate_report", action="store_true", help="Whether to generate a report.")
    parser.add_argument("--dhydro_cover_folder_name", type=str, default=DHYDRO_COVER, help="The name of the D-HYDRO cover folder")
    parser.add_argument("--dhydro1d2d_cover_folder_name", type=str, default=DHYDRO1D2D_COVER, help="The name of the D-HYDRO 1D2D cover folder")
    parser.add_argument("--sobek_cover_folder_name", type=str, default=SOBEK3_COVER, help="The name of the SOBEK3 cover folder")
    parser.add_argument("--delft3dfm_cover_folder_name", type=str, default=DELFT3DFM_COVER, help="The name of the Delft3D FM cover folder")
    parser.add_argument("--delft3dfm1d2d_cover_folder_name", type=str, default=DELFT3DFM1D2D_COVER, help="The name of the Delft3D FM 1D2D cover folder")

    return parser.parse_args()


def run() -> None:
    """
    Parse the argument, and execute the script.
    """
    args = parse_arguments()

    svn_path = Path(args.svn_root_path)
    manuals_path = Path(args.manual_root_path)

    if not svn_path.exists() or not svn_path.is_dir():
        print("Provided svn_root_path is not valid: {}".format(svn_path))
        return

    if not manuals_path.exists() or not manuals_path.is_dir():
        print("Provided manuals_path is not valid: {}".format(manuals_path))
        return

    cover_names = CoverFolderNames(
        dhydro1d2d=args.dhydro1d2d_cover_folder_name, 
        dhydro=args.dhydro_cover_folder_name, 
        delft3dfm1d2d=args.delft3dfm1d2d_cover_folder_name, 
        delft3dfm=args.delft3dfm_cover_folder_name, 
        sobek3=args.sobek_cover_folder_name
    )

    new_pdfs = obtain_new_pdfs(manuals_path, cover_names)
    _report_covers(new_pdfs)

    old_pdfs = obtain_pdf_locations(svn_path, cover_names)
    _report_pdfs(old_pdfs)

    succeeded_manuals, failed_manuals, unused_manuals = replace_existing_manuals_with_new(old_pdfs, new_pdfs, True)

    resolved_svn_path = svn_path.resolve()
    unused_manuals = list((Path(x).resolve()).relative_to(resolved_svn_path) for x in unused_manuals)

    if args.generate_report:
        gmr.generate_report(svn_path,
                            new_pdfs, 
                            old_pdfs, 
                            succeeded_manuals, 
                            unused_manuals,
                            failed_manuals)


if __name__ == "__main__":
    run()
