CR_1.1
CRSN id 'Weir1_IntervalControllers' nm 'Weir1_IntervalControllers' ci '1' lc 1700 crsn
CRSN id 'Weir2_TimeControllers' nm 'Weir2_TimeControllers' ci '2' lc 1700 crsn
CRSN id 'Weir3_HydraulicControllers' nm 'Weir3_HydraulicControllers' ci '3' lc 1700 crsn
CRSN id 'Weir4_PIDControllers' nm 'Weir4_PIDControllers' ci '4' lc 1700 crsn
CRSN id 'Weir5_RelativeTimeControllers' nm 'Weir5_RelativeTimeControllers' ci '5' lc 1700 crsn
CRSN id '18' nm '' ci '6' lc 1100 crsn
CRSN id 'Weir6_RelValueControllers' nm 'Weir6_RelValueControllers' ci '7' lc 1700 crsn
CRSN id 'Weir7_Time_IntV_PID_Cntrl' nm 'Weir7_Time_IntV_PID_Cntrl' ci '8' lc 1700 crsn
CRSN id 'Weir8_RelTime_Hydr_PID_Cntrl' nm 'Weir8_RelTime_Hydr_PID_Cntrl' ci '9' lc 1700 crsn
CRSN id 'Weir9_RelValue_IntV_Hydr_Cntrl' nm 'Weir9_RelValue_IntV_Hydr_Cntrl' ci '10' lc 1700 crsn
