CP_1.0
BRCH id '1' cp 1 ct bc 
TBLE
5000 90 <
tble brch

BRCH id '2' cp 1 ct bc 
TBLE
5000 90 <
tble brch

BRCH id '3' cp 1 ct bc 
TBLE
5000 90 <
tble brch

BRCH id '4' cp 1 ct bc 
TBLE
5000 90 <
tble brch

BRCH id '5' cp 1 ct bc 
TBLE
5000 90 <
tble brch

BRCH id '6' cp 1 ct bc 
TBLE
2500 90 <
tble brch

BRCH id '7' cp 1 ct bc 
TBLE
5000 90 <
tble brch

BRCH id '8' cp 1 ct bc 
TBLE
5000 90 <
tble brch

BRCH id '9' cp 1 ct bc 
TBLE
5000 90 <
tble brch

BRCH id '10' cp 1 ct bc 
TBLE
5000 90 <
tble brch

