ST_1.0
STRU id 'Weir1_IntervalCntrl' nm 'Weir1_IntervalCntrl' ci '1' lc 5900 stru
STRU id 'Weir2_TimeCntrl' nm 'Weir2_TimeCntrl' ci '2' lc 5900 stru
STRU id 'Weir3_HydraulicCntrl' nm 'Weir3_HydraulicCntrl' ci '3' lc 5900 stru
STRU id 'Weir4_PIDCntr' nm 'Weir4_PIDCntr' ci '4' lc 5900 stru
STRU id 'Weir5_RelTimeCntrl' nm 'Weir5_RelTimeCntrl' ci '5' lc 5900 stru
STRU id 'Weir6_RelValueCntrl' nm 'Weir6_RelValueCntrl' ci '7' lc 5900 stru
STRU id 'Weir7_Time_IntV_PID' nm 'Weir7_Time_IntV_PID' ci '8' lc 5900 stru
STRU id 'Weir8_RelTime_Hydr_PID' nm 'Weir8_RelTime_Hydr_PID' ci '9' lc 5900 stru
STRU id 'Weir9_RelValue_IntV_Hydr' nm 'Weir9_RelValue_IntV_Hydr' ci '10' lc 5900 stru
