CR_1.1
CRSN id 'B1_Crs_A' nm 'B1_Crs_A' ci '1' lc 0 crsn
CRSN id 'B2_Crs_B' nm 'B2_Crs_B' ci '2' lc 2250 crsn
CRSN id 'B3_Crs_C' nm 'B3_Crs_C' ci '3' lc 2250 crsn
CRSN id 'Crs_Inp_A&B' nm 'Crs_Inp_A&B' ci '6' lc 250 crsn
CRSN id 'B2A_Crs_B' nm 'B2A_Crs_B' ci '6' lc 2500 crsn
CRSN id 'B3A_Crs_C' nm 'B3A_Crs_C' ci '4' lc 2500 crsn
CRSN id 'B5_Crs_A' nm 'B5_Crs_A' ci '5' lc 0 crsn
CRSN id 'B7_Crs_B' nm 'B7_Crs_B' ci '7' lc 2250 crsn
CRSN id 'B8_Crs_A' nm 'B8_Crs_A' ci '8' lc 0 crsn
CRSN id 'B8_Crs_B' nm 'B8_Crs_B' ci '8' lc 3750 crsn
