                                                                                
 Found -A command line switch                                                   
 ONLY activated processes are switched on                                       
 Found -NP command line switch                                                  
 No processes from the process definition file are switched on                  


 Model :            Fraction calculation Sobek-WQ           
                                                            


 Run   :                                                    
                    T0: 2003.08.01 00:00:00  (scu=       1s)


 WARNING: circular input output relation detected in process library
 
 Using process definition file : proc_def                                
 Version number                :       4.52
 Serial                        :  825377359
 
# Determining which processes can be switched on                                                    
                                                                                                    
                                                                                                    
# Determinig the processes to model the substances.                             
                                                                                
-Fluxes for [Check     ]                                                        
 No fluxes found                                                                
-Dispersion for [Check     ]                                                    
 No dispersions found                                                           
-Velocity for [Check     ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Initial   ]                                                        
 No fluxes found                                                                
-Dispersion for [Initial   ]                                                    
 No dispersions found                                                           
-Velocity for [Initial   ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Lateral in]                                                        
 No fluxes found                                                                
-Dispersion for [Lateral in]                                                    
 No dispersions found                                                           
-Velocity for [Lateral in]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Lat_Maastr]                                                        
 No fluxes found                                                                
-Dispersion for [Lat_Maastr]                                                    
 No dispersions found                                                           
-Velocity for [Lat_Maastr]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Lat_DenHel]                                                        
 No fluxes found                                                                
-Dispersion for [Lat_DenHel]                                                    
 No dispersions found                                                           
-Velocity for [Lat_DenHel]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Lat_Twente]                                                        
 No fluxes found                                                                
-Dispersion for [Lat_Twente]                                                    
 No dispersions found                                                           
-Velocity for [Lat_Twente]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Lat_Eindho]                                                        
 No fluxes found                                                                
-Dispersion for [Lat_Eindho]                                                    
 No dispersions found                                                           
-Velocity for [Lat_Eindho]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Lat_Rotter]                                                        
 No fluxes found                                                                
-Dispersion for [Lat_Rotter]                                                    
 No dispersions found                                                           
-Velocity for [Lat_Rotter]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Boundary F]                                                        
 No fluxes found                                                                
-Dispersion for [Boundary F]                                                    
 No dispersions found                                                           
-Velocity for [Boundary F]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Noordzee  ]                                                        
 No fluxes found                                                                
-Dispersion for [Noordzee  ]                                                    
 No dispersions found                                                           
-Velocity for [Noordzee  ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Lat_DeBilt]                                                        
 No fluxes found                                                                
-Dispersion for [Lat_DeBilt]                                                    
 No dispersions found                                                           
-Velocity for [Lat_DeBilt]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Lat_Amster]                                                        
 No fluxes found                                                                
-Dispersion for [Lat_Amster]                                                    
 No dispersions found                                                           
-Velocity for [Lat_Amster]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Lat_Gronin]                                                        
 No fluxes found                                                                
-Dispersion for [Lat_Gronin]                                                    
 No dispersions found                                                           
-Velocity for [Lat_Gronin]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Lat_Leeuwa]                                                        
 No fluxes found                                                                
-Dispersion for [Lat_Leeuwa]                                                    
 No dispersions found                                                           
-Velocity for [Lat_Leeuwa]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Lat_RWZI  ]                                                        
 No fluxes found                                                                
-Dispersion for [Lat_RWZI  ]                                                    
 No dispersions found                                                           
-Velocity for [Lat_RWZI  ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Lat_OtherE]                                                        
 No fluxes found                                                                
-Dispersion for [Lat_OtherE]                                                    
 No dispersions found                                                           
-Velocity for [Lat_OtherE]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Lat_Precip]                                                        
 No fluxes found                                                                
-Dispersion for [Lat_Precip]                                                    
 No dispersions found                                                           
-Velocity for [Lat_Precip]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Lat_Other ]                                                        
 No fluxes found                                                                
-Dispersion for [Lat_Other ]                                                    
 No dispersions found                                                           
-Velocity for [Lat_Other ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Brabant   ]                                                        
 No fluxes found                                                                
-Dispersion for [Brabant   ]                                                    
 No dispersions found                                                           
-Velocity for [Brabant   ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Schelde   ]                                                        
 No fluxes found                                                                
-Dispersion for [Schelde   ]                                                    
 No dispersions found                                                           
-Velocity for [Schelde   ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [PL_Greveli]                                                        
 No fluxes found                                                                
-Dispersion for [PL_Greveli]                                                    
 No dispersions found                                                           
-Velocity for [PL_Greveli]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [PL_OosterS]                                                        
 No fluxes found                                                                
-Dispersion for [PL_OosterS]                                                    
 No dispersions found                                                           
-Velocity for [PL_OosterS]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [PL_WesterS]                                                        
 No fluxes found                                                                
-Dispersion for [PL_WesterS]                                                    
 No dispersions found                                                           
-Velocity for [PL_WesterS]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [NoordzeeWS]                                                        
 No fluxes found                                                                
-Dispersion for [NoordzeeWS]                                                    
 No dispersions found                                                           
-Velocity for [NoordzeeWS]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Evaporatio]                                                        
 No fluxes found                                                                
-Dispersion for [Evaporatio]                                                    
 No dispersions found                                                           
-Velocity for [Evaporatio]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Neerslag  ]                                                        
 No fluxes found                                                                
-Dispersion for [Neerslag  ]                                                    
 No dispersions found                                                           
-Velocity for [Neerslag  ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [KanGentTer]                                                        
 No fluxes found                                                                
-Dispersion for [KanGentTer]                                                    
 No dispersions found                                                           
-Velocity for [KanGentTer]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [kwel      ]                                                        
 No fluxes found                                                                
-Dispersion for [kwel      ]                                                    
 No dispersions found                                                           
-Velocity for [kwel      ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [sluis     ]                                                        
 No fluxes found                                                                
-Dispersion for [sluis     ]                                                    
 No dispersions found                                                           
-Velocity for [sluis     ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [industrie ]                                                        
 No fluxes found                                                                
-Dispersion for [industrie ]                                                    
 No dispersions found                                                           
-Velocity for [industrie ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Rnld      ]                                                        
 No fluxes found                                                                
-Dispersion for [Rnld      ]                                                    
 No dispersions found                                                           
-Velocity for [Rnld      ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [HHNK      ]                                                        
 No fluxes found                                                                
-Dispersion for [HHNK      ]                                                    
 No dispersions found                                                           
-Velocity for [HHNK      ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Groot Mijd]                                                        
 No fluxes found                                                                
-Dispersion for [Groot Mijd]                                                    
 No dispersions found                                                           
-Velocity for [Groot Mijd]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Bijlmer   ]                                                        
 No fluxes found                                                                
-Dispersion for [Bijlmer   ]                                                    
 No dispersions found                                                           
-Velocity for [Bijlmer   ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Horstermee]                                                        
 No fluxes found                                                                
-Dispersion for [Horstermee]                                                    
 No dispersions found                                                           
-Velocity for [Horstermee]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Holendrech]                                                        
 No fluxes found                                                                
-Dispersion for [Holendrech]                                                    
 No dispersions found                                                           
-Velocity for [Holendrech]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [HDSR      ]                                                        
 No fluxes found                                                                
-Dispersion for [HDSR      ]                                                    
 No dispersions found                                                           
-Velocity for [HDSR      ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [AGV       ]                                                        
 No fluxes found                                                                
-Dispersion for [AGV       ]                                                    
 No dispersions found                                                           
-Velocity for [AGV       ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Asd (boeze]                                                        
 No fluxes found                                                                
-Dispersion for [Asd (boeze]                                                    
 No dispersions found                                                           
-Velocity for [Asd (boeze]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [IJmuiden  ]                                                        
 No fluxes found                                                                
-Dispersion for [IJmuiden  ]                                                    
 No dispersions found                                                           
-Velocity for [IJmuiden  ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [DuivendrMi]                                                        
 No fluxes found                                                                
-Dispersion for [DuivendrMi]                                                    
 No dispersions found                                                           
-Velocity for [DuivendrMi]                                                      
 No velocity found                                                              
                                                                                
# Locating processes for requested output                                       
                                                                                
# Determining the input for the processes (in reversed order)                   
                                                                                
# Determining the use of the DELWAQ input                                       
                                                                                
 INFO: Constant [Iteration ] is NOT used by the PROCES system                   
                                                                                
# Locating requested output from active processes                               
                                                                                
                                                                                
