substance 'Continuity' active
   description        'Continuity'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'NatTemp' active
   description        'natural temperature'
   concentration-unit '(oC)'
   waste-load-unit    '-'
end-substance
parameter 'CP'
   description   'specific heat of water'
   unit          '(J/kg/oC)'
   value          0.2222E+05
end-parameter
parameter 'SwitchTemp'
   description   'switch modelled temp is absolute(0) or surplus(1)'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'XYScaleFac'
   description   'Mult for meteo to segment coordinates'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'NoMeteoSta'
   description   'Number of Meteo stations in calculation'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'MeteoClcSW'
   description   'Option (1=nearest; 2= lin dist 3=squared dist )'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'XSeg'
   description   'X-coordinate of DELWAQ segment (metric)'
   unit          '(m)'
   value         -0.9990E+03
end-parameter
parameter 'YSeg'
   description   'Y-coordinate of DELWAQ segment (metric)'
   unit          '(m)'
   value         -0.9990E+03
end-parameter
output 'RadSW'
   description   'Short wave radiation reaching water'
end-output
output 'SunFac'
   description   'Percentage sunshine'
end-output
output 'TempAir'
   description   'Air temperature'
end-output
output 'PAtm'
   description   'Air pressure'
end-output
output 'Depth'
   description   'depth of segment'
end-output
output 'RelHumAir'
   description   'Relative air humidity'
end-output
output 'cloud'
   description   'Cloud coverage (fraction)'
end-output
output 'WinDir'
   description   'Wind direction at location'
end-output
active-processes
   name  'ResTim' 'residence time'
   name  'HeatBal' 'Total heat flux for surface water'
   name  'Meteo' 'Process meteo from various meteo-stations'
   name  'DynDepth' 'dynamic calculation of the depth'
   name  'Salin' 'calculation of salinity from chloride'
end-active-processes
