                                                                                
 Found -A command line switch                                                   
 ONLY activated processes are switched on                                       
 Found -NP command line switch                                                  
 No processes from the process definition file are switched on                  


 Model :            Water quality calculation Sobek-WQ      
                                                            


 Run   :                                                    
                    T0: 2003.01.01 00:00:00  (scu=       1s)


 
 Using process definition file : proc_def                                
 Version number                :       4.51
 Serial                        :          0
 
# Determining which processes can be switched on                                                    
                                                                                                    
                                                                                                    
# Determinig the processes to model the substances.                             
                                                                                
-Fluxes for [Cl        ]                                                        
 No fluxes found                                                                
-Dispersion for [Cl        ]                                                    
 No dispersions found                                                           
-Velocity for [Cl        ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [cTR1      ]                                                        
 No fluxes found                                                                
-Dispersion for [cTR1      ]                                                    
 No dispersions found                                                           
-Velocity for [cTR1      ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [cTR2      ]                                                        
 No fluxes found                                                                
-Dispersion for [cTR2      ]                                                    
 No dispersions found                                                           
-Velocity for [cTR2      ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [cTR3      ]                                                        
 No fluxes found                                                                
-Dispersion for [cTR3      ]                                                    
 No dispersions found                                                           
-Velocity for [cTR3      ]                                                      
 No velocity found                                                              
                                                                                
# Locating processes for requested output                                       
                                                                                
# Determining the input for the processes (in reversed order)                   
                                                                                
# Determining the use of the DELWAQ input                                       
                                                                                
 INFO: Constant [Iteration ] is NOT used by the PROCES system                   
 INFO: Constant [VWIND     ] is NOT used by the PROCES system                   
 INFO: Constant [WINDDIR   ] is NOT used by the PROCES system                   
 INFO: Constant [TEMP      ] is NOT used by the PROCES system                   
 INFO: Constant [RAD       ] is NOT used by the PROCES system                   
 INFO: Parameter [Xseg      ] is NOT used by the PROCES system                  
 INFO: Parameter [Yseg      ] is NOT used by the PROCES system                  
                                                                                
# Locating requested output from active processes                               
                                                                                
 WARNING: Output [Surf                ] not located                             
                                                                                
