substance 'Cl' active
   description        'Chloride'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'cTR1' active
   description        'conservative tracer source 1'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'cTR2' active
   description        'conservative tracer source 2'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'cTR3' active
   description        'conservative tracer source 3'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
active-processes
end-active-processes
