//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaShell.Plugins.DelftModels.WaterFlowModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeltaShell.Plugins.DelftModels.WaterFlowModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Boundary {
            get {
                object obj = ResourceManager.GetObject("Boundary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn selected nodes into H.
        /// </summary>
        public static string BoundaryNodeDataMapTool_AddToolStripMenuItems_Turn_selected_nodes_into_H {
            get {
                return ResourceManager.GetString("BoundaryNodeDataMapTool_AddToolStripMenuItems_Turn_selected_nodes_into_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn selected nodes into H(t).
        /// </summary>
        public static string BoundaryNodeDataMapTool_AddToolStripMenuItems_Turn_selected_nodes_into_H_t_ {
            get {
                return ResourceManager.GetString("BoundaryNodeDataMapTool_AddToolStripMenuItems_Turn_selected_nodes_into_H_t_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn selected nodes into None.
        /// </summary>
        public static string BoundaryNodeDataMapTool_AddToolStripMenuItems_Turn_selected_nodes_into_none {
            get {
                return ResourceManager.GetString("BoundaryNodeDataMapTool_AddToolStripMenuItems_Turn_selected_nodes_into_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn selected nodes into Q.
        /// </summary>
        public static string BoundaryNodeDataMapTool_AddToolStripMenuItems_Turn_selected_nodes_into_Q {
            get {
                return ResourceManager.GetString("BoundaryNodeDataMapTool_AddToolStripMenuItems_Turn_selected_nodes_into_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn selected nodes into Q(h).
        /// </summary>
        public static string BoundaryNodeDataMapTool_AddToolStripMenuItems_Turn_selected_nodes_into_Q_h_ {
            get {
                return ResourceManager.GetString("BoundaryNodeDataMapTool_AddToolStripMenuItems_Turn_selected_nodes_into_Q_h_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn selected nodes into Q(t).
        /// </summary>
        public static string BoundaryNodeDataMapTool_AddToolStripMenuItems_Turn_selected_nodes_into_Q_t_ {
            get {
                return ResourceManager.GetString("BoundaryNodeDataMapTool_AddToolStripMenuItems_Turn_selected_nodes_into_Q_t_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap feedback {
            get {
                object obj = ResourceManager.GetObject("feedback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder_with_data {
            get {
                object obj = ResourceManager.GetObject("folder_with_data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap generateDataInSeriesToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("generateDataInSeriesToolStripMenuItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HBoundary {
            get {
                object obj = ResourceManager.GetObject("HBoundary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HConst {
            get {
                object obj = ResourceManager.GetObject("HConst", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn selected laterals into Q.
        /// </summary>
        public static string LateralSourceDataMapTool_AddToolStripMenuItems_Turn_selected_laterals_into_Q {
            get {
                return ResourceManager.GetString("LateralSourceDataMapTool_AddToolStripMenuItems_Turn_selected_laterals_into_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn selected laterals into Q(h).
        /// </summary>
        public static string LateralSourceDataMapTool_AddToolStripMenuItems_Turn_selected_laterals_into_Q_h_ {
            get {
                return ResourceManager.GetString("LateralSourceDataMapTool_AddToolStripMenuItems_Turn_selected_laterals_into_Q_h_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn selected laterals into Q(t).
        /// </summary>
        public static string LateralSourceDataMapTool_AddToolStripMenuItems_Turn_selected_laterals_into_Q_t_ {
            get {
                return ResourceManager.GetString("LateralSourceDataMapTool_AddToolStripMenuItems_Turn_selected_laterals_into_Q_t_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap None {
            get {
                object obj = ResourceManager.GetObject("None", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Observation {
            get {
                object obj = ResourceManager.GetObject("Observation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap QBoundary {
            get {
                object obj = ResourceManager.GetObject("QBoundary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap QConst {
            get {
                object obj = ResourceManager.GetObject("QConst", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap QHBoundary {
            get {
                object obj = ResourceManager.GetObject("QHBoundary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ReverseRoughnessSection {
            get {
                object obj = ResourceManager.GetObject("ReverseRoughnessSection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling the table of the Q or H function failed!.
        /// </summary>
        public static string RoughnessDataFileReader_FillFunctionWithTableData_Filling_the_table_of_the_Q_or_H_function_failed_ {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_FillFunctionWithTableData_Filling_the_table_of_the_Q_or_H" +
                        "_function_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling the table of the Q or H function failed, values count doesn&apos;t match the defined levels count!.
        /// </summary>
        public static string RoughnessDataFileReader_FillFunctionWithTableData_Filling_the_table_of_the_Q_or_H_function_failed__values_count_doesn_t_match_the_defined_levels_count_ {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_FillFunctionWithTableData_Filling_the_table_of_the_Q_or_H" +
                        "_function_failed__values_count_doesn_t_match_the_defined_levels_count_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read roughness definition data.
        /// </summary>
        public static string RoughnessDataFileReader_ReadDefinitionData_Could_not_read_roughness_definition_data {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadDefinitionData_Could_not_read_roughness_definition_da" +
                        "ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t read roughness section with a function type of : {0}.
        /// </summary>
        public static string RoughnessDataFileReader_ReadDefinitionData_Couldn_t_read_roughness_section_with_a_function_type_of____0_ {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadDefinitionData_Couldn_t_read_roughness_section_with_a" +
                        "_function_type_of____0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adding to network went wrong!.
        /// </summary>
        public static string RoughnessDataFileReader_ReadFile_adding_to_network_went_wrong_ {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadFile_adding_to_network_went_wrong_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read content section {0} properly.
        /// </summary>
        public static string RoughnessDataFileReader_ReadFile_Could_not_read_content_section__0__properly {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadFile_Could_not_read_content_section__0__properly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read file {0} properly, it doesn&apos;t exist..
        /// </summary>
        public static string RoughnessDataFileReader_ReadFile_Could_not_read_file__0__properly__it_doesn_t_exist_ {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadFile_Could_not_read_file__0__properly__it_doesn_t_exi" +
                        "st_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read file {0} properly, it seems empty.
        /// </summary>
        public static string RoughnessDataFileReader_ReadFile_Could_not_read_file__0__properly__it_seems_empty {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadFile_Could_not_read_file__0__properly__it_seems_empty" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set roughness data in model.
        /// </summary>
        public static string RoughnessDataFileReader_ReadFile_Could_not_set_roughness_data_in_model {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadFile_Could_not_set_roughness_data_in_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While reading roughness section an error occured :{0} {1}.
        /// </summary>
        public static string RoughnessDataFileReader_ReadFile_While_reading_roughness_section_an_error_occured___0___1_ {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadFile_While_reading_roughness_section_an_error_occured" +
                        "___0___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to branch ({0}) where the roughness should be put on is not available in the model.
        /// </summary>
        public static string RoughnessDataFileReader_ReadRoughnessBranchData_branch___0___where_the_roughness_should_be_put_on_is_not_available_in_the_model {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadRoughnessBranchData_branch___0___where_the_roughness_" +
                        "should_be_put_on_is_not_available_in_the_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read roughness branch data.
        /// </summary>
        public static string RoughnessDataFileReader_ReadRoughnessBranchData_Could_not_read_roughness_branch_data {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadRoughnessBranchData_Could_not_read_roughness_branch_d" +
                        "ata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the number of levels ({0}) and the defined number of levels of the branch property {1} are not the same of branch properties : {2}!.
        /// </summary>
        public static string RoughnessDataFileReader_ReadRoughnessBranchData_The_length_of_the_number_of_levels___0___and_the_defined_number_of_levels_of_the_branch_property__1__are_not_the_same_of_branch_properties____2__ {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadRoughnessBranchData_The_length_of_the_number_of_level" +
                        "s___0___and_the_defined_number_of_levels_of_the_branch_property__1__are_not_the_" +
                        "same_of_branch_properties____2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While reading branches for roughness section an error occured :{0} {1}.
        /// </summary>
        public static string RoughnessDataFileReader_ReadRoughnessBranchData_While_reading_branches_for_roughness_section_an_error_occured___0___1_ {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadRoughnessBranchData_While_reading_branches_for_roughn" +
                        "ess_section_an_error_occured___0___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import calibrated roughness section {0} because the calibrated roughness section you want to import doesn&apos;t exist in the model.
        /// </summary>
        public static string RoughnessDataFileReader_ReadRoughnessSection_Could_not_import_calibrated_roughness_section__0__because_the_calibrated_roughness_section_you_want_to_import_doesn_t_exist_in_the_model {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadRoughnessSection_Could_not_import_calibrated_roughnes" +
                        "s_section__0__because_the_calibrated_roughness_section_you_want_to_import_doesn_" +
                        "t_exist_in_the_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When reading reverse roughness section ({0}) the referring (linked) &apos;normal&apos; roughness section ({1}) is not found. The normal section ({1}) should be imported first!.
        /// </summary>
        public static string RoughnessDataFileReader_ReadRoughnessSection_When_reading_reverse_roughness_section___0___the_referring__linked___normal__roughness_section___1___is_not_found__The_normal_section___1___should_be_imported_first_ {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadRoughnessSection_When_reading_reverse_roughness_secti" +
                        "on___0___the_referring__linked___normal__roughness_section___1___is_not_found__T" +
                        "he_normal_section___1___should_be_imported_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While creating the roughnes section from the roughness file the fisrt argument of the roughness network coverage is not created (used to set the interpolation type.
        /// </summary>
        public static string RoughnessDataFileReader_ReadRoughnessSection_While_creating_the_roughnes_section_from_the_roughness_file_the_fisrt_argument_of_the_roughness_network_coverage_is_not_created__used_to_set_the_interpolation_type {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadRoughnessSection_While_creating_the_roughnes_section_" +
                        "from_the_roughness_file_the_fisrt_argument_of_the_roughness_network_coverage_is_" +
                        "not_created__used_to_set_the_interpolation_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While creating the roughnes section from the roughness file the roughness network coverage is not created.
        /// </summary>
        public static string RoughnessDataFileReader_ReadRoughnessSection_While_creating_the_roughnes_section_from_the_roughness_file_the_roughness_network_coverage_is_not_created {
            get {
                return ResourceManager.GetString("RoughnessDataFileReader_ReadRoughnessSection_While_creating_the_roughnes_section_" +
                        "from_the_roughness_file_the_roughness_network_coverage_is_not_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RoughnessSection {
            get {
                object obj = ResourceManager.GetObject("RoughnessSection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap unstruc {
            get {
                object obj = ResourceManager.GetObject("unstruc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap validation {
            get {
                object obj = ResourceManager.GetObject("validation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispersion F3 coefficient.
        /// </summary>
        public static string WaterFlowModel1D_AddDispersionF3CoverageDataItem_Dispersion_F3_coefficient {
            get {
                return ResourceManager.GetString("WaterFlowModel1D_AddDispersionF3CoverageDataItem_Dispersion_F3_coefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispersion F4 coefficient.
        /// </summary>
        public static string WaterFlowModel1D_AddDispersionF4CoverageDataItem_Dispersion_F4_coefficient {
            get {
                return ResourceManager.GetString("WaterFlowModel1D_AddDispersionF4CoverageDataItem_Dispersion_F4_coefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispersion F1 coefficient.
        /// </summary>
        public static string WaterFlowModel1D_EnableSalt_Dispersion_F1_coefficient {
            get {
                return ResourceManager.GetString("WaterFlowModel1D_EnableSalt_Dispersion_F1_coefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find log file: {0} at expected path: {1}.
        /// </summary>
        public static string WaterFlowModel1D_ReadSobekLogFile_Could_not_find_log_file___0__at_expected_path___1_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1D_ReadSobekLogFile_Could_not_find_log_file___0__at_expected_path__" +
                        "_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading log file: {0}, {1}.
        /// </summary>
        public static string WaterFlowModel1D_ReadSobekLogFile_Error_reading_log_file___0____1_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1D_ReadSobekLogFile_Error_reading_log_file___0____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to simulate 1D flow of water in open water systems, such as rivers and irrigation &amp; drainage channels..
        /// </summary>
        public static string WaterFlowModel1DApplicationPlugin_Description {
            get {
                return ResourceManager.GetString("WaterFlowModel1DApplicationPlugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch &apos;{0}&apos; has Q/H dependent roughness defined on section &apos;{1}&apos;. Q/H dependent roughness is only supported on branches with ZW crosssections (tabulated)..
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_GetRoughnessValidationIssuesForSection_Branch___0___has_Q_H_dependent_roughness_defined_on_section {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_GetRoughnessValidationIssuesForSection_Branch_" +
                        "__0___has_Q_H_dependent_roughness_defined_on_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch &apos;{0}&apos; has Q/H dependent roughness defined on section &apos;{1}&apos;. The Q/H dependent roughness table should have at least two rows..
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_GetRoughnessValidationIssuesForSection_Branch___0___has_Q_H_dependent_roughness_defined_on_section_2 {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_GetRoughnessValidationIssuesForSection_Branch_" +
                        "__0___has_Q_H_dependent_roughness_defined_on_section_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boundary conditions.
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateBoundaryConditions_Boundary_conditions {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateBoundaryConditions_Boundary_conditions" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The boundary condition {0} has duplicate values. All values in Q(h) boundaries must be sequential..
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateBoundaryConditions_DuplicateValues {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateBoundaryConditions_DuplicateValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The boundary condition {0} has non-sequential values. All values in Q(h) boundaries must be sequential..
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateBoundaryConditions_NonSequentialValues {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateBoundaryConditions_NonSequentialValues" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The boundary condition {0} has a salinity type of None. All open boundaries must specify salinity values..
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateBoundaryConditions_The_boundary_condition__0__has_a_salinity_type_of_None__All_open_boundaries_must_specify_salinity_values_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateBoundaryConditions_The_boundary_condit" +
                        "ion__0__has_a_salinity_type_of_None__All_open_boundaries_must_specify_salinity_v" +
                        "alues_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The boundary condition {0} has multiple connecting branches. This is only possible for waterlevel boundary conditions..
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateBoundaryConditions_The_boundary_condition__0__has_multiple_connecting_branches__This_is_only_possible_for_waterlevel_boundary_conditions_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateBoundaryConditions_The_boundary_condit" +
                        "ion__0__has_multiple_connecting_branches__This_is_only_possible_for_waterlevel_b" +
                        "oundary_conditions_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty roughness table.
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateExtraResistance_Empty_roughness_table {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateExtraResistance_Empty_roughness_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra resistance.
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateExtraResistance_Extra_resistance {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateExtraResistance_Extra_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;: Gate opening must be greater than or equal to 0..
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateGatedWeirFormula____Gate_opening_must_be_greater_than_or_equal_to_0_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateGatedWeirFormula____Gate_opening_must_" +
                        "be_greater_than_or_equal_to_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;: Maximum negative flow restrictions must be greater than or equal to 0..
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateGatedWeirFormula____Maximum_negative_flow_restrictions_must_be_greater_than_or_equal_to_0_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateGatedWeirFormula____Maximum_negative_f" +
                        "low_restrictions_must_be_greater_than_or_equal_to_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;: Maximum positive flow restrictions must be greater than or equal to 0..
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateGatedWeirFormula____Maximum_positive_flow_restrictions_must_be_greater_than_or_equal_to_0_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateGatedWeirFormula____Maximum_positive_f" +
                        "low_restrictions_must_be_greater_than_or_equal_to_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input restart state.
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateInputRestartState_Input_restart_state {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateInputRestartState_Input_restart_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid output time step must be positive value..
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateModelSettings_Grid_output_time_step_must_be_positive_value_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateModelSettings_Grid_output_time_step_mu" +
                        "st_be_positive_value_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morphology file does not exist..
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateModelSettings_Indicated_morphology_file_does_not_exist__ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateModelSettings_Indicated_morphology_fil" +
                        "e_does_not_exist__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sediment file does not exist..
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateModelSettings_Indicated_sediment_file_does_not_exist__ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateModelSettings_Indicated_sediment_file_" +
                        "does_not_exist__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No explicit working directory found. Please save model before morphology can be run..
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateModelSettings_No_explicit_working_directory_found__Please_save_model_before_morphology_can_be_run_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateModelSettings_No_explicit_working_dire" +
                        "ctory_found__Please_save_model_before_morphology_can_be_run_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical Parameter Iadvec1D must be 1,2 or 5. Given Value is: {0}.
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateModelSettings_Numerical_Parameter_Iadvec1D_must_be_1___5__Given_Value_is___0_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateModelSettings_Numerical_Parameter_Iadv" +
                        "ec1D_must_be_1___5__Given_Value_is___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical Parameter Limtyphu1D must be 1 - 3. Given Value is: {0}.
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateModelSettings_Numerical_Parameter_Limtyphu1D_must_be_1___3__Given_Value_is___0_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateModelSettings_Numerical_Parameter_Limt" +
                        "yphu1D_must_be_1___3__Given_Value_is___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical Parameter Momdilution1D must be 1 - 3. Given Value is: {0}.
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateModelSettings_Numerical_Parameter_Momdilution1D_must_be_1___3__Given_Value_is___0_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateModelSettings_Numerical_Parameter_Momd" +
                        "ilution1D_must_be_1___3__Given_Value_is___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structures output time step must be positive value..
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateModelSettings_Structures_output_time_step_must_be_positive_value_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateModelSettings_Structures_output_time_s" +
                        "tep_must_be_positive_value_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The structures output time step should be a multiple of the calculation time step..
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateModelSettings_The_structures_output_time_step_should_be_a_multiple_of_the_calculation_time_step_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateModelSettings_The_structures_output_ti" +
                        "me_step_should_be_a_multiple_of_the_calculation_time_step_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;: Capacity must be greater than or equal to 0..
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidatePump____Capacity_must_be_greater_than_or_equal_to_0_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidatePump____Capacity_must_be_greater_than_" +
                        "or_equal_to_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;: Delivery start level must be less than or equal to delivery stop level..
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidatePumpDeliverySide____Delivery_start_level_must_be_less_than_or_equal_to_delivery_stop_level_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidatePumpDeliverySide____Delivery_start_lev" +
                        "el_must_be_less_than_or_equal_to_delivery_stop_level_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;: Suction start level must be greater than or equal to suction stop level..
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidatePumpSuctionSide____Suction_start_level_must_be_greater_than_or_equal_to_suction_stop_level_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidatePumpSuctionSide____Suction_start_level" +
                        "_must_be_greater_than_or_equal_to_suction_stop_level_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salinity.
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateSalinity_Salinity {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateSalinity_Salinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;: Crest width must be greater than or equal to 0..
        /// </summary>
        public static string WaterFlowModel1DModelDataValidator_ValidateWeir____Crest_width_must_be_greater_than_or_equal_to_0_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelDataValidator_ValidateWeir____Crest_width_must_be_greater_th" +
                        "an_or_equal_to_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only allowed values &apos;Current&apos; and &apos;None&apos; for: {0}.
        /// </summary>
        public static string WaterFlowModel1DModelOutputSettingsValidator_ValidateAggregationOptions_Only_allowed_values__Current__and__None__for__0_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelOutputSettingsValidator_ValidateAggregationOptions_Only_allo" +
                        "wed_values__Current__and__None__for__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature parameters.
        /// </summary>
        public static string WaterFlowModel1DModelTemperatureValidator_ValidateModelParameters_Temperature_parameters {
            get {
                return ResourceManager.GetString("WaterFlowModel1DModelTemperatureValidator_ValidateModelParameters_Temperature_par" +
                        "ameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse DateTime {0} from file {1}.
        /// </summary>
        public static string WaterFlowModel1DOutputFileReader_ParseReferenceTime_UnableToParseDateTimeFromFile {
            get {
                return ResourceManager.GetString("WaterFlowModel1DOutputFileReader_ParseReferenceTime_UnableToParseDateTimeFromFile" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading NetCdf file {0}.
        /// </summary>
        public static string WaterFlowModel1DOutputFileReader_ReadMetaData_ErrorReadingNetCdfFile {
            get {
                return ResourceManager.GetString("WaterFlowModel1DOutputFileReader_ReadMetaData_ErrorReadingNetCdfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file {0}, contains more than 1 potential location_id variable..
        /// </summary>
        public static string WaterFlowModel1DOutputFileValidator_Validate_OutputFileContainsMoreThan1LocationIdVariable {
            get {
                return ResourceManager.GetString("WaterFlowModel1DOutputFileValidator_Validate_OutputFileContainsMoreThan1LocationI" +
                        "dVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file {0}, does not contain any time-dependent variables..
        /// </summary>
        public static string WaterFlowModel1DOutputFileValidator_Validate_OutputFileDoesNotContainAnyTimeDependentVariables {
            get {
                return ResourceManager.GetString("WaterFlowModel1DOutputFileValidator_Validate_OutputFileDoesNotContainAnyTimeDepen" +
                        "dentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file {0}, does not contain required location_id variable..
        /// </summary>
        public static string WaterFlowModel1DOutputFileValidator_Validate_OutputFileDoesNotContainRequiredLocationIdVariable {
            get {
                return ResourceManager.GetString("WaterFlowModel1DOutputFileValidator_Validate_OutputFileDoesNotContainRequiredLoca" +
                        "tionIdVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file {0}, does not contain required time dimension..
        /// </summary>
        public static string WaterFlowModel1DOutputFileValidator_Validate_OutputFileDoesNotContainRequiredTimeDimension {
            get {
                return ResourceManager.GetString("WaterFlowModel1DOutputFileValidator_Validate_OutputFileDoesNotContainRequiredTime" +
                        "Dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file {0}, does not contain required time variable..
        /// </summary>
        public static string WaterFlowModel1DOutputFileValidator_Validate_OutputFileDoesNotContainRequiredTimeVariable {
            get {
                return ResourceManager.GetString("WaterFlowModel1DOutputFileValidator_Validate_OutputFileDoesNotContainRequiredTime" +
                        "Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file {0}, does not exist..
        /// </summary>
        public static string WaterFlowModel1DOutputFileValidator_Validate_OutputFileDoesNotExist {
            get {
                return ResourceManager.GetString("WaterFlowModel1DOutputFileValidator_Validate_OutputFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time variable does not contain unit attribute..
        /// </summary>
        public static string WaterFlowModel1DOutputFileValidator_Validate_TimeVariableDoesNotContainUnitAttribute {
            get {
                return ResourceManager.GetString("WaterFlowModel1DOutputFileValidator_Validate_TimeVariableDoesNotContainUnitAttrib" +
                        "ute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time variable does not contain a valid unit in the required Format: &apos;{0} {1}&apos;..
        /// </summary>
        public static string WaterFlowModel1DOutputFileValidator_Validate_TimeVariableDoesNotContainValidUnitInRequiredFormat {
            get {
                return ResourceManager.GetString("WaterFlowModel1DOutputFileValidator_Validate_TimeVariableDoesNotContainValidUnitI" +
                        "nRequiredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find specified estuary mouth node {0}..
        /// </summary>
        public static string WaterFlowModel1DSalinityValidator_ValidateSalinityForKuijperVanRijnPrismaticIsValid_Can_not_find_specified_estuary_mouth_node__0__ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DSalinityValidator_ValidateSalinityForKuijperVanRijnPrismaticIsVal" +
                        "id_Can_not_find_specified_estuary_mouth_node__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estuary mouth node {0} is not a boundary node..
        /// </summary>
        public static string WaterFlowModel1DSalinityValidator_ValidateSalinityForKuijperVanRijnPrismaticIsValid_Estuary_mouth_node__0__is_not_a_boundary_node_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DSalinityValidator_ValidateSalinityForKuijperVanRijnPrismaticIsVal" +
                        "id_Estuary_mouth_node__0__is_not_a_boundary_node_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F4 Coverage values cannot all be set to 0. Either remove them or assign at least one value different from 0..
        /// </summary>
        public static string WaterFlowModel1DSalinityValidator_ValidateSalinityForKuijperVanRijnPrismaticIsValid_F4_Coverage_values_cannot_all_be_set_to_0__Either_remove_them_or_set_a_valid_value_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DSalinityValidator_ValidateSalinityForKuijperVanRijnPrismaticIsVal" +
                        "id_F4_Coverage_values_cannot_all_be_set_to_0__Either_remove_them_or_set_a_valid_" +
                        "value_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Estuary mouth node specified..
        /// </summary>
        public static string WaterFlowModel1DSalinityValidator_ValidateSalinityForKuijperVanRijnPrismaticIsValid_No_Estuary_mouth_node_specified_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DSalinityValidator_ValidateSalinityForKuijperVanRijnPrismaticIsVal" +
                        "id_No_Estuary_mouth_node_specified_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The boundary condition {0} has a temperature type of None. All open boundaries must specify temperature values..
        /// </summary>
        public static string WaterFlowModel1DTemperatureValidator_ValidateBoundaryConditions_The_boundary_condition__0__has_a_temperature_type_of_None__All_open_boundaries_must_specify_temperature_values_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DTemperatureValidator_ValidateBoundaryConditions_The_boundary_cond" +
                        "ition__0__has_a_temperature_type_of_None__All_open_boundaries_must_specify_tempe" +
                        "rature_values_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial temperature..
        /// </summary>
        public static string WaterFlowModel1DTemperatureValidator_ValidateInitialTemperature_Initial_temperature_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DTemperatureValidator_ValidateInitialTemperature_Initial_temperatu" +
                        "re_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values should be in double format..
        /// </summary>
        public static string WaterFlowModel1DTemperatureValidator_ValidateModelParameters_Values_should_be_in_double_format_ {
            get {
                return ResourceManager.GetString("WaterFlowModel1DTemperatureValidator_ValidateModelParameters_Values_should_be_in_" +
                        "double_format_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Wind {
            get {
                object obj = ResourceManager.GetObject("Wind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
