                                                                                
 Found -A command line switch                                                   
 ONLY activated processes are switched on                                       
 Found -NP command line switch                                                  
 No processes from the process definition file are switched on                  


 Model :            Fraction calculation Sobek-WQ           
                                                            


 Run   :                                                    
                    T0: 1900.07.03 02:00:00  (scu=       1s)


 WARNING: circular input output relation detected in process library
 
 Using process definition file : proc_def                                
 Version number                :       4.52
 Serial                        : 1431454287
 
# Determining which processes can be switched on                                                    
                                                                                                    
                                                                                                    
# Determinig the processes to model the substances.                             
                                                                                
-Fluxes for [Check     ]                                                        
 No fluxes found                                                                
-Dispersion for [Check     ]                                                    
 No dispersions found                                                           
-Velocity for [Check     ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Initial   ]                                                        
 No fluxes found                                                                
-Dispersion for [Initial   ]                                                    
 No dispersions found                                                           
-Velocity for [Initial   ]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Lateral in]                                                        
 No fluxes found                                                                
-Dispersion for [Lateral in]                                                    
 No dispersions found                                                           
-Velocity for [Lateral in]                                                      
 No velocity found                                                              
                                                                                
-Fluxes for [Boundary F]                                                        
 No fluxes found                                                                
-Dispersion for [Boundary F]                                                    
 No dispersions found                                                           
-Velocity for [Boundary F]                                                      
 No velocity found                                                              
                                                                                
# Locating processes for requested output                                       
                                                                                
# Determining the input for the processes (in reversed order)                   
                                                                                
# Determining the use of the DELWAQ input                                       
                                                                                
 INFO: Constant [Iteration ] is NOT used by the PROCES system                   
                                                                                
# Locating requested output from active processes                               
                                                                                
                                                                                
