Deltares, Parsen Version 2.08.002.54560 (Win64), Feb 20 2018, 11:17:39

Warning    : Time table fully outside runtime range
             Record: BTBL id 'HPJ-20131006-20131009' st 0 ty 0 h_ wt PDIN 0 0 '' .....
             Table Key: bt bl

Warning    : Time table fully outside runtime range
             Record: BTBL id 'SJGY-20131006-20131009' st 0 ty 0 h_ wt PDIN 0 0  p.....
             Table Key: bt bl

Warning    : Time table fully outside runtime range
             Record: BTBL id 'YJ-20131006-20131009' st 0 ty 0 h_ wt PDIN 0 0 '' p.....
             Table Key: bt bl

Informative Messages:        0
Warnings            :        3
Errors!             :        0

End of program
