substance 'Continuity' active
   description        'Continuity!'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance

substance 'Continuity!' active
   description        'Continuity'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance

parameter 'NH4'
   description        'Ammonium (dummy!)'
   unit               '(gN/m3)'
   value              0.0
end-parameter

parameter 'NH4!'
   description        'Ammonium (dummy)'
   unit               '(gN/m3)'
   value              0.0
end-parameter

output 'Cl'
   description   'Chloride!'
end-output

output 'Cl!'
   description   'Chloride'
end-output

active-processes
   name  'BLOOM_P' 'BLOOM II algae module!'
end-active-processes

active-processes
   name  'BLOOM_P!' 'BLOOM II algae module'
end-active-processes