; number of active and inactive substances
6             0
        ; active substances
1            'SeaBoundary01' ;Water from boundary type SeaBoundary01
2            'RiverBoundary01' ;Water from boundary type RiverBoundary01
3            'Vlissingen' ;Water from boundary type Vlissingen
4            'Hansweert' ;Water from boundary type Hansweert
5            'Terneuzen' ;Water from boundary type Terneuzen
6            'Initial' ;Water in system at start of simulation
        ; passive substances
