substance 'Continuity' active
   description        'Continuity'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'NH4' active
   description        'Ammonium (NH4)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'NO3' active
   description        'Nitrate (NO3)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'PO4' active
   description        'Ortho-Phosphate (PO4)'
   concentration-unit '(gP/m3)'
   waste-load-unit    '-'
end-substance
substance 'Si' active
   description        'dissolved Silica (Si)'
   concentration-unit '(gSi/m3)'
   waste-load-unit    '-'
end-substance
substance 'Opal' active
   description        'Opal-Si'
   concentration-unit '(gSi/m3)'
   waste-load-unit    '-'
end-substance
substance 'POC1' active
   description        'POC1 (fast decomposing fraction)'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'PON1' active
   description        'PON1 (fast decomposing fraction)'
   concentration-unit '(gN/m3)'
   waste-load-unit    '-'
end-substance
substance 'POP1' active
   description        'POP1 (fast decomposing fraction)'
   concentration-unit '(gP/m3)'
   waste-load-unit    '-'
end-substance
substance 'BLUEGRN_E' active
   description        'BLUEGRN energy type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'BLUEGRN_N' active
   description        'BLUEGRN nitrogen type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'BLUEGRN_P' active
   description        'BLUEGRN phosphorus type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'FDIATOMS_E' active
   description        'Fresh DIATOMS energy type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'FDIATOMS_P' active
   description        'Fresh DIATOMS P/Si type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'GREENS_E' active
   description        'GREENS energy type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'GREENS_N' active
   description        'GREENS nitrogen type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'GREENS_P' active
   description        'GREENS phosphorus type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'ULVAS_E' active
   description        'Ulva suspended energy type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'ULVAS_N' active
   description        'Ulva suspended nitrogen type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'ULVAS_P' active
   description        'Ulva suspended phosphorus type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'DetCS1' inactive
   description        'DetC in layer S1'
   concentration-unit '(gC/m2)'
   waste-load-unit    '-'
end-substance
substance 'DetNS1' inactive
   description        'DetN in layer S1'
   concentration-unit '(gN/m2)'
   waste-load-unit    '-'
end-substance
substance 'DetPS1' inactive
   description        'DetP in layer S1'
   concentration-unit '(gP/m2)'
   waste-load-unit    '-'
end-substance
substance 'DetSiS1' inactive
   description        'DetSi in layer S1'
   concentration-unit '(gSi/m2)'
   waste-load-unit    '-'
end-substance
substance 'ULVAF_E' inactive
   description        'Ulva attached energy type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'ULVAF_N' inactive
   description        'Ulva attached nitrogen type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
substance 'ULVAF_P' inactive
   description        'Ulva attached phosphorus type'
   concentration-unit '(gC/m3)'
   waste-load-unit    '-'
end-substance
parameter 'TimMultBl'
   description   'ratio bloom/delwaq time step'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'Temp'
   description   'ambient water temperature'
   unit          '(oC)'
   value          0.1500E+02
end-parameter
parameter 'SWBloomOut'
   description   'switch on BLOOM output (0=no,1=yes)'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'FrAutFDI_E'
   description   'frac. mort. algae  dissolved as nutrients FDIATOMS_E'
   unit          '(-)'
   value          0.3500E+00
end-parameter
parameter 'FrAutFDI_P'
   description   'frac. mort. algae  dissolved as nutrients FDIATOMS_P'
   unit          '(-)'
   value          0.3500E+00
end-parameter
parameter 'FrAutGRE_E'
   description   'frac. mort. algae  dissolved as nutrients GREENS_E'
   unit          '(-)'
   value          0.3500E+00
end-parameter
parameter 'FrAutGRE_N'
   description   'frac. mort. algae  dissolved as nutrients GREENS_N'
   unit          '(-)'
   value          0.3500E+00
end-parameter
parameter 'FrAutGRE_P'
   description   'frac. mort. algae  dissolved as nutrients GREENS_P'
   unit          '(-)'
   value          0.3500E+00
end-parameter
parameter 'FrAutBLU_E'
   description   'frac. mort. algae  dissolved as nutrients BLUEGRN_E'
   unit          '(-)'
   value          0.3500E+00
end-parameter
parameter 'FrAutBLU_N'
   description   'frac. mort. algae  dissolved as nutrients BLUEGRN_N'
   unit          '(-)'
   value          0.3500E+00
end-parameter
parameter 'FrAutBLU_P'
   description   'frac. mort. algae  dissolved as nutrients BLUEGRN_P'
   unit          '(-)'
   value          0.3500E+00
end-parameter
parameter 'FrAutULS_E'
   description   'frac. mort. algae  dissolved as nutrients ULVAS_E'
   unit          '(-)'
   value          0.3000E+00
end-parameter
parameter 'FrAutULS_N'
   description   'frac. mort. algae  dissolved as nutrients ULVAS_N'
   unit          '(-)'
   value          0.3000E+00
end-parameter
parameter 'FrAutULS_P'
   description   'frac. mort. algae  dissolved as nutrients ULVAS_P'
   unit          '(-)'
   value          0.3000E+00
end-parameter
parameter 'FrAutULF_E'
   description   'frac. mort. algae  dissolved as nutrients ULVAF_E'
   unit          '(-)'
   value          0.3000E+00
end-parameter
parameter 'FrAutULF_N'
   description   'frac. mort. algae  dissolved as nutrients ULVAF_N'
   unit          '(-)'
   value          0.3000E+00
end-parameter
parameter 'FrAutULF_P'
   description   'frac. mort. algae  dissolved as nutrients ULVAF_P'
   unit          '(-)'
   value          0.3000E+00
end-parameter
parameter 'FrDetFDI_E'
   description   'frac. mort. algae  detritus production FDIATOMS_E'
   unit          '(-)'
   value          0.5500E+00
end-parameter
parameter 'FrDetFDI_P'
   description   'frac. mort. algae  detritus production FDIATOMS_P'
   unit          '(-)'
   value          0.5500E+00
end-parameter
parameter 'FrDetGRE_E'
   description   'frac. mort. algae  detritus production GREENS_E'
   unit          '(-)'
   value          0.5500E+00
end-parameter
parameter 'FrDetGRE_N'
   description   'frac. mort. algae  detritus production GREENS_N'
   unit          '(-)'
   value          0.5500E+00
end-parameter
parameter 'FrDetGRE_P'
   description   'frac. mort. algae  detritus production GREENS_P'
   unit          '(-)'
   value          0.5500E+00
end-parameter
parameter 'FrDetBLU_E'
   description   'frac. mort. algae  detritus production BLUEGRN_E'
   unit          '(-)'
   value          0.6200E+00
end-parameter
parameter 'FrDetBLU_N'
   description   'frac. mort. algae  detritus production BLUEGRN_N'
   unit          '(-)'
   value          0.6200E+00
end-parameter
parameter 'FrDetBLU_P'
   description   'frac. mort. algae  detritus production BLUEGRN_P'
   unit          '(-)'
   value          0.6200E+00
end-parameter
parameter 'FrDetULS_E'
   description   'frac. mort. algae  detritus production ULVAS_E'
   unit          '(-)'
   value          0.7000E+00
end-parameter
parameter 'FrDetULS_N'
   description   'frac. mort. algae  detritus production ULVAS_N'
   unit          '(-)'
   value          0.7000E+00
end-parameter
parameter 'FrDetULS_P'
   description   'frac. mort. algae  detritus production ULVAS_P'
   unit          '(-)'
   value          0.7000E+00
end-parameter
parameter 'FrDetULF_E'
   description   'frac. mort. algae  detritus production ULVAF_E'
   unit          '(-)'
   value          0.7000E+00
end-parameter
parameter 'FrDetULF_N'
   description   'frac. mort. algae  detritus production ULVAF_N'
   unit          '(-)'
   value          0.7000E+00
end-parameter
parameter 'FrDetULF_P'
   description   'frac. mort. algae  detritus production ULVAF_P'
   unit          '(-)'
   value          0.7000E+00
end-parameter
parameter 'ExtVlFDI_E'
   description   'extinction coeff. visible light by algae FDIATOMS_E'
   unit          '(m2/gC)'
   value          0.2700E+00
end-parameter
parameter 'ExtVlFDI_P'
   description   'extinction coeff. visible light by algae FDIATOMS_P'
   unit          '(m2/gC)'
   value          0.1875E+00
end-parameter
parameter 'ExtVlGRE_E'
   description   'extinction coeff. visible light by algae GREENS_E'
   unit          '(m2/gC)'
   value          0.2250E+00
end-parameter
parameter 'ExtVlGRE_N'
   description   'extinction coeff. visible light by algae GREENS_N'
   unit          '(m2/gC)'
   value          0.1875E+00
end-parameter
parameter 'ExtVlGRE_P'
   description   'extinction coeff. visible light by algae GREENS_P'
   unit          '(m2/gC)'
   value          0.1875E+00
end-parameter
parameter 'ExtVlBLU_E'
   description   'extinction coeff. visible light by algae BLUEGRN_E'
   unit          '(m2/gC)'
   value          0.4000E+00
end-parameter
parameter 'ExtVlBLU_N'
   description   'extinction coeff. visible light by algae BLUEGRN_N'
   unit          '(m2/gC)'
   value          0.2875E+00
end-parameter
parameter 'ExtVlBLU_P'
   description   'extinction coeff. visible light by algae BLUEGRN_P'
   unit          '(m2/gC)'
   value          0.2875E+00
end-parameter
parameter 'ExtVlULS_E'
   description   'extinction coeff. visible light by algae ULVAS_E'
   unit          '(m2/gC)'
   value          0.2480E+00
end-parameter
parameter 'ExtVlULS_N'
   description   'extinction coeff. visible light by algae ULVAS_N'
   unit          '(m2/gC)'
   value          0.2480E+00
end-parameter
parameter 'ExtVlULS_P'
   description   'extinction coeff. visible light by algae ULVAS_P'
   unit          '(m2/gC)'
   value          0.2480E+00
end-parameter
parameter 'ExtVlULF_E'
   description   'extinction coeff. visible light by algae ULVAF_E'
   unit          '(m2/gC)'
   value          0.2480E-01
end-parameter
parameter 'ExtVlULF_N'
   description   'extinction coeff. visible light by algae ULVAF_N'
   unit          '(m2/gC)'
   value          0.2480E-01
end-parameter
parameter 'ExtVlULF_P'
   description   'extinction coeff. visible light by algae ULVAF_P'
   unit          '(m2/gC)'
   value          0.2480E-01
end-parameter
parameter 'DMCFFDI_E'
   description   'DM:C ratio algae FDIATOMS_E'
   unit          '(gDM/gC)'
   value          0.3000E+01
end-parameter
parameter 'DMCFFDI_P'
   description   'DM:C ratio algae FDIATOMS_P'
   unit          '(gDM/gC)'
   value          0.2500E+01
end-parameter
parameter 'DMCFGRE_E'
   description   'DM:C ratio algae GREENS_E'
   unit          '(gDM/gC)'
   value          0.2500E+01
end-parameter
parameter 'DMCFGRE_N'
   description   'DM:C ratio algae GREENS_N'
   unit          '(gDM/gC)'
   value          0.2500E+01
end-parameter
parameter 'DMCFGRE_P'
   description   'DM:C ratio algae GREENS_P'
   unit          '(gDM/gC)'
   value          0.2500E+01
end-parameter
parameter 'DMCFBLU_E'
   description   'DM:C ratio algae BLUEGRN_E'
   unit          '(gDM/gC)'
   value          0.2500E+01
end-parameter
parameter 'DMCFBLU_N'
   description   'DM:C ratio algae BLUEGRN_N'
   unit          '(gDM/gC)'
   value          0.2500E+01
end-parameter
parameter 'DMCFBLU_P'
   description   'DM:C ratio algae BLUEGRN_P'
   unit          '(gDM/gC)'
   value          0.2500E+01
end-parameter
parameter 'DMCFULS_E'
   description   'DM:C ratio algae ULVAS_E'
   unit          '(gDM/gC)'
   value          0.3300E+01
end-parameter
parameter 'DMCFULS_N'
   description   'DM:C ratio algae ULVAS_N'
   unit          '(gDM/gC)'
   value          0.3300E+01
end-parameter
parameter 'DMCFULS_P'
   description   'DM:C ratio algae ULVAS_P'
   unit          '(gDM/gC)'
   value          0.3300E+01
end-parameter
parameter 'DMCFULF_E'
   description   'DM:C ratio algae ULVAF_E'
   unit          '(gDM/gC)'
   value          0.3300E+01
end-parameter
parameter 'DMCFULF_N'
   description   'DM:C ratio algae ULVAF_N'
   unit          '(gDM/gC)'
   value          0.3300E+01
end-parameter
parameter 'DMCFULF_P'
   description   'DM:C ratio algae ULVAF_P'
   unit          '(gDM/gC)'
   value          0.3300E+01
end-parameter
parameter 'NCRFDI_E'
   description   'N:C ratio per algae type FDIATOMS_E'
   unit          '(gN/gC)'
   value          0.2100E+00
end-parameter
parameter 'NCRFDI_P'
   description   'N:C ratio per algae type FDIATOMS_P'
   unit          '(gN/gC)'
   value          0.1880E+00
end-parameter
parameter 'NCRGRE_E'
   description   'N:C ratio per algae type GREENS_E'
   unit          '(gN/gC)'
   value          0.2750E+00
end-parameter
parameter 'NCRGRE_N'
   description   'N:C ratio per algae type GREENS_N'
   unit          '(gN/gC)'
   value          0.1750E+00
end-parameter
parameter 'NCRGRE_P'
   description   'N:C ratio per algae type GREENS_P'
   unit          '(gN/gC)'
   value          0.2000E+00
end-parameter
parameter 'NCRBLU_E'
   description   'N:C ratio per algae type BLUEGRN_E'
   unit          '(gN/gC)'
   value          0.2250E+00
end-parameter
parameter 'NCRBLU_N'
   description   'N:C ratio per algae type BLUEGRN_N'
   unit          '(gN/gC)'
   value          0.1250E+00
end-parameter
parameter 'NCRBLU_P'
   description   'N:C ratio per algae type BLUEGRN_P'
   unit          '(gN/gC)'
   value          0.1500E+00
end-parameter
parameter 'NCRULS_E'
   description   'N:C ratio per algae type ULVAS_E'
   unit          '(gN/gC)'
   value          0.5940E-01
end-parameter
parameter 'NCRULS_N'
   description   'N:C ratio per algae type ULVAS_N'
   unit          '(gN/gC)'
   value          0.3300E-01
end-parameter
parameter 'NCRULS_P'
   description   'N:C ratio per algae type ULVAS_P'
   unit          '(gN/gC)'
   value          0.5940E-01
end-parameter
parameter 'NCRULF_E'
   description   'N:C ratio per algae type ULVAF_E'
   unit          '(gN/gC)'
   value          0.5940E-01
end-parameter
parameter 'NCRULF_N'
   description   'N:C ratio per algae type ULVAF_N'
   unit          '(gN/gC)'
   value          0.3300E-01
end-parameter
parameter 'NCRULF_P'
   description   'N:C ratio per algae type ULVAF_P'
   unit          '(gN/gC)'
   value          0.5940E-01
end-parameter
parameter 'PCRFDI_E'
   description   'P:C ratio per algae type FDIATOMS_E'
   unit          '(gP/gC)'
   value          0.1800E-01
end-parameter
parameter 'PCRFDI_P'
   description   'P:C ratio per algae type FDIATOMS_P'
   unit          '(gP/gC)'
   value          0.1130E-01
end-parameter
parameter 'PCRGRE_E'
   description   'P:C ratio per algae type GREENS_E'
   unit          '(gP/gC)'
   value          0.2380E-01
end-parameter
parameter 'PCRGRE_N'
   description   'P:C ratio per algae type GREENS_N'
   unit          '(gP/gC)'
   value          0.1500E-01
end-parameter
parameter 'PCRGRE_P'
   description   'P:C ratio per algae type GREENS_P'
   unit          '(gP/gC)'
   value          0.1250E-01
end-parameter
parameter 'PCRBLU_E'
   description   'P:C ratio per algae type BLUEGRN_E'
   unit          '(gP/gC)'
   value          0.1880E-01
end-parameter
parameter 'PCRBLU_N'
   description   'P:C ratio per algae type BLUEGRN_N'
   unit          '(gP/gC)'
   value          0.1880E-01
end-parameter
parameter 'PCRBLU_P'
   description   'P:C ratio per algae type BLUEGRN_P'
   unit          '(gP/gC)'
   value          0.1500E-01
end-parameter
parameter 'PCRULS_E'
   description   'P:C ratio per algae type ULVAS_E'
   unit          '(gP/gC)'
   value          0.1000E-01
end-parameter
parameter 'PCRULS_N'
   description   'P:C ratio per algae type ULVAS_N'
   unit          '(gP/gC)'
   value          0.6670E-02
end-parameter
parameter 'PCRULS_P'
   description   'P:C ratio per algae type ULVAS_P'
   unit          '(gP/gC)'
   value          0.3330E-02
end-parameter
parameter 'PCRULF_E'
   description   'P:C ratio per algae type ULVAF_E'
   unit          '(gP/gC)'
   value          0.1000E-01
end-parameter
parameter 'PCRULF_N'
   description   'P:C ratio per algae type ULVAF_N'
   unit          '(gP/gC)'
   value          0.6670E-02
end-parameter
parameter 'PCRULF_P'
   description   'P:C ratio per algae type ULVAF_P'
   unit          '(gP/gC)'
   value          0.3330E-02
end-parameter
parameter 'SCRFDI_E'
   description   'Si:C ratio per algae type FDIATOMS_E'
   unit          '(gSi/gC)'
   value          0.6600E+00
end-parameter
parameter 'SCRFDI_P'
   description   'Si:C ratio per algae type FDIATOMS_P'
   unit          '(gSi/gC)'
   value          0.5500E+00
end-parameter
parameter 'SCRGRE_E'
   description   'Si:C ratio per algae type GREENS_E'
   unit          '(gSi/gC)'
   value          0.1800E-02
end-parameter
parameter 'SCRGRE_N'
   description   'Si:C ratio per algae type GREENS_N'
   unit          '(gSi/gC)'
   value          0.1800E-02
end-parameter
parameter 'SCRGRE_P'
   description   'Si:C ratio per algae type GREENS_P'
   unit          '(gSi/gC)'
   value          0.1800E-02
end-parameter
parameter 'SCRBLU_E'
   description   'Si:C ratio per algae type BLUEGRN_E'
   unit          '(gSi/gC)'
   value          0.1800E-02
end-parameter
parameter 'SCRBLU_N'
   description   'Si:C ratio per algae type BLUEGRN_N'
   unit          '(gSi/gC)'
   value          0.1800E-02
end-parameter
parameter 'SCRBLU_P'
   description   'Si:C ratio per algae type BLUEGRN_P'
   unit          '(gSi/gC)'
   value          0.1800E-02
end-parameter
parameter 'SCRULS_E'
   description   'Si:C ratio per algae type ULVAS_E'
   unit          '(gSi/gC)'
   value          0.0000E+00
end-parameter
parameter 'SCRULS_N'
   description   'Si:C ratio per algae type ULVAS_N'
   unit          '(gSi/gC)'
   value          0.0000E+00
end-parameter
parameter 'SCRULS_P'
   description   'Si:C ratio per algae type ULVAS_P'
   unit          '(gSi/gC)'
   value          0.0000E+00
end-parameter
parameter 'SCRULF_E'
   description   'Si:C ratio per algae type ULVAF_E'
   unit          '(gSi/gC)'
   value          0.0000E+00
end-parameter
parameter 'SCRULF_N'
   description   'Si:C ratio per algae type ULVAF_N'
   unit          '(gSi/gC)'
   value          0.0000E+00
end-parameter
parameter 'SCRULF_P'
   description   'Si:C ratio per algae type ULVAF_P'
   unit          '(gSi/gC)'
   value          0.0000E+00
end-parameter
parameter 'ChlaCFDI_E'
   description   'Chlorophyll-a:C ratio per algae type FDIATOMS_E'
   unit          '(gChla/gC)'
   value          0.4000E-01
end-parameter
parameter 'ChlaCFDI_P'
   description   'Chlorophyll-a:C ratio per algae type FDIATOMS_P'
   unit          '(gChla/gC)'
   value          0.2500E-01
end-parameter
parameter 'ChlaCGRE_E'
   description   'Chlorophyll-a:C ratio per algae type GREENS_E'
   unit          '(gChla/gC)'
   value          0.3300E-01
end-parameter
parameter 'ChlaCGRE_N'
   description   'Chlorophyll-a:C ratio per algae type GREENS_N'
   unit          '(gChla/gC)'
   value          0.2500E-01
end-parameter
parameter 'ChlaCGRE_P'
   description   'Chlorophyll-a:C ratio per algae type GREENS_P'
   unit          '(gChla/gC)'
   value          0.2500E-01
end-parameter
parameter 'ChlaCBLU_E'
   description   'Chlorophyll-a:C ratio per algae type BLUEGRN_E'
   unit          '(gChla/gC)'
   value          0.3300E-01
end-parameter
parameter 'ChlaCBLU_N'
   description   'Chlorophyll-a:C ratio per algae type BLUEGRN_N'
   unit          '(gChla/gC)'
   value          0.2000E-01
end-parameter
parameter 'ChlaCBLU_P'
   description   'Chlorophyll-a:C ratio per algae type BLUEGRN_P'
   unit          '(gChla/gC)'
   value          0.2000E-01
end-parameter
parameter 'ChlaCULS_E'
   description   'Chlorophyll-a:C ratio per algae type ULVAS_E'
   unit          '(gChla/gC)'
   value          0.1000E-02
end-parameter
parameter 'ChlaCULS_N'
   description   'Chlorophyll-a:C ratio per algae type ULVAS_N'
   unit          '(gChla/gC)'
   value          0.1000E-02
end-parameter
parameter 'ChlaCULS_P'
   description   'Chlorophyll-a:C ratio per algae type ULVAS_P'
   unit          '(gChla/gC)'
   value          0.1000E-02
end-parameter
parameter 'ChlaCULF_E'
   description   'Chlorophyll-a:C ratio per algae type ULVAF_E'
   unit          '(gChla/gC)'
   value          0.1000E-03
end-parameter
parameter 'ChlaCULF_N'
   description   'Chlorophyll-a:C ratio per algae type ULVAF_N'
   unit          '(gChla/gC)'
   value          0.1000E-03
end-parameter
parameter 'ChlaCULF_P'
   description   'Chlorophyll-a:C ratio per algae type ULVAF_P'
   unit          '(gChla/gC)'
   value          0.1000E-03
end-parameter
parameter 'PPMaxFDI_E'
   description   'pot. maximum growth rate at 0 dg C FDIATOMS_E'
   unit          '(1/d)'
   value          0.3500E+00
end-parameter
parameter 'PPMaxFDI_P'
   description   'pot. maximum growth rate at 0 dg C FDIATOMS_P'
   unit          '(1/d)'
   value          0.3500E+00
end-parameter
parameter 'PPMaxGRE_E'
   description   'pot. maximum growth rate at 0 dg C GREENS_E'
   unit          '(1/d)'
   value          0.6800E-01
end-parameter
parameter 'PPMaxGRE_N'
   description   'pot. maximum growth rate at 0 dg C GREENS_N'
   unit          '(1/d)'
   value          0.6800E-01
end-parameter
parameter 'PPMaxGRE_P'
   description   'pot. maximum growth rate at 0 dg C GREENS_P'
   unit          '(1/d)'
   value          0.6800E-01
end-parameter
parameter 'PPMaxBLU_E'
   description   'pot. maximum growth rate at 0 dg C BLUEGRN_E'
   unit          '(1/d)'
   value          0.5600E-01
end-parameter
parameter 'PPMaxBLU_N'
   description   'pot. maximum growth rate at 0 dg C BLUEGRN_N'
   unit          '(1/d)'
   value          0.4800E-01
end-parameter
parameter 'PPMaxBLU_P'
   description   'pot. maximum growth rate at 0 dg C BLUEGRN_P'
   unit          '(1/d)'
   value          0.4800E-01
end-parameter
parameter 'PPMaxULS_E'
   description   'pot. maximum growth rate at 0 dg C ULVAS_E'
   unit          '(1/d)'
   value          0.6000E-01
end-parameter
parameter 'PPMaxULS_N'
   description   'pot. maximum growth rate at 0 dg C ULVAS_N'
   unit          '(1/d)'
   value          0.5000E-01
end-parameter
parameter 'PPMaxULS_P'
   description   'pot. maximum growth rate at 0 dg C ULVAS_P'
   unit          '(1/d)'
   value          0.5000E-01
end-parameter
parameter 'PPMaxULF_E'
   description   'pot. maximum growth rate at 0 dg C ULVAF_E'
   unit          '(1/d)'
   value          0.8000E-01
end-parameter
parameter 'PPMaxULF_N'
   description   'pot. maximum growth rate at 0 dg C ULVAF_N'
   unit          '(1/d)'
   value          0.6000E-01
end-parameter
parameter 'PPMaxULF_P'
   description   'pot. maximum growth rate at 0 dg C ULVAF_P'
   unit          '(1/d)'
   value          0.6000E-01
end-parameter
parameter 'Mort0FDI_E'
   description   'mortality rate at 0 dg C FDIATOMS_E'
   unit          '(1/d)'
   value          0.3500E-01
end-parameter
parameter 'Mort0FDI_P'
   description   'mortality rate at 0 dg C FDIATOMS_P'
   unit          '(1/d)'
   value          0.4500E-01
end-parameter
parameter 'Mort0GRE_E'
   description   'mortality rate at 0 dg C GREENS_E'
   unit          '(1/d)'
   value          0.3500E-01
end-parameter
parameter 'Mort0GRE_N'
   description   'mortality rate at 0 dg C GREENS_N'
   unit          '(1/d)'
   value          0.4500E-01
end-parameter
parameter 'Mort0GRE_P'
   description   'mortality rate at 0 dg C GREENS_P'
   unit          '(1/d)'
   value          0.4500E-01
end-parameter
parameter 'Mort0BLU_E'
   description   'mortality rate at 0 dg C BLUEGRN_E'
   unit          '(1/d)'
   value          0.3500E-01
end-parameter
parameter 'Mort0BLU_N'
   description   'mortality rate at 0 dg C BLUEGRN_N'
   unit          '(1/d)'
   value          0.4500E-01
end-parameter
parameter 'Mort0BLU_P'
   description   'mortality rate at 0 dg C BLUEGRN_P'
   unit          '(1/d)'
   value          0.4500E-01
end-parameter
parameter 'Mort0ULS_E'
   description   'mortality rate at 0 dg C ULVAS_E'
   unit          '(1/d)'
   value          0.1250E+00
end-parameter
parameter 'Mort0ULS_N'
   description   'mortality rate at 0 dg C ULVAS_N'
   unit          '(1/d)'
   value          0.1250E+00
end-parameter
parameter 'Mort0ULS_P'
   description   'mortality rate at 0 dg C ULVAS_P'
   unit          '(1/d)'
   value          0.1250E+00
end-parameter
parameter 'Mort0ULF_E'
   description   'mortality rate at 0 dg C ULVAF_E'
   unit          '(1/d)'
   value          0.7500E-01
end-parameter
parameter 'Mort0ULF_N'
   description   'mortality rate at 0 dg C ULVAF_N'
   unit          '(1/d)'
   value          0.7500E-01
end-parameter
parameter 'Mort0ULF_P'
   description   'mortality rate at 0 dg C ULVAF_P'
   unit          '(1/d)'
   value          0.7500E-01
end-parameter
parameter 'TcMrtFDI_E'
   description   'temperature coefficient for mortality FDIATOMS_E'
   unit          '(-)'
   value          0.1080E+01
end-parameter
parameter 'TcMrtFDI_P'
   description   'temperature coefficient for mortality FDIATOMS_P'
   unit          '(-)'
   value          0.1085E+01
end-parameter
parameter 'TcMrtGRE_E'
   description   'temperature coefficient for mortality GREENS_E'
   unit          '(-)'
   value          0.1080E+01
end-parameter
parameter 'TcMrtGRE_N'
   description   'temperature coefficient for mortality GREENS_N'
   unit          '(-)'
   value          0.1085E+01
end-parameter
parameter 'TcMrtGRE_P'
   description   'temperature coefficient for mortality GREENS_P'
   unit          '(-)'
   value          0.1085E+01
end-parameter
parameter 'TcMrtBLU_E'
   description   'temperature coefficient for mortality BLUEGRN_E'
   unit          '(-)'
   value          0.1080E+01
end-parameter
parameter 'TcMrtBLU_N'
   description   'temperature coefficient for mortality BLUEGRN_N'
   unit          '(-)'
   value          0.1085E+01
end-parameter
parameter 'TcMrtBLU_P'
   description   'temperature coefficient for mortality BLUEGRN_P'
   unit          '(-)'
   value          0.1085E+01
end-parameter
parameter 'TcMrtULS_E'
   description   'temperature coefficient for mortality ULVAS_E'
   unit          '(-)'
   value         -0.2500E+02
end-parameter
parameter 'TcMrtULS_N'
   description   'temperature coefficient for mortality ULVAS_N'
   unit          '(-)'
   value         -0.2500E+02
end-parameter
parameter 'TcMrtULS_P'
   description   'temperature coefficient for mortality ULVAS_P'
   unit          '(-)'
   value         -0.2500E+02
end-parameter
parameter 'TcMrtULF_E'
   description   'temperature coefficient for mortality ULVAF_E'
   unit          '(-)'
   value         -0.2500E+02
end-parameter
parameter 'TcMrtULF_N'
   description   'temperature coefficient for mortality ULVAF_N'
   unit          '(-)'
   value         -0.2500E+02
end-parameter
parameter 'TcMrtULF_P'
   description   'temperature coefficient for mortality ULVAF_P'
   unit          '(-)'
   value         -0.2500E+02
end-parameter
parameter 'MRespFDI_E'
   description   'maintenance respiration rate at 0 dg C FDIATOMS_E'
   unit          '(1/d)'
   value          0.3100E-01
end-parameter
parameter 'MRespFDI_P'
   description   'maintenance respiration rate at 0 dg C FDIATOMS_P'
   unit          '(1/d)'
   value          0.3100E-01
end-parameter
parameter 'MRespGRE_E'
   description   'maintenance respiration rate at 0 dg C GREENS_E'
   unit          '(1/d)'
   value          0.3100E-01
end-parameter
parameter 'MRespGRE_N'
   description   'maintenance respiration rate at 0 dg C GREENS_N'
   unit          '(1/d)'
   value          0.3100E-01
end-parameter
parameter 'MRespGRE_P'
   description   'maintenance respiration rate at 0 dg C GREENS_P'
   unit          '(1/d)'
   value          0.3100E-01
end-parameter
parameter 'MRespBLU_E'
   description   'maintenance respiration rate at 0 dg C BLUEGRN_E'
   unit          '(1/d)'
   value          0.1200E-01
end-parameter
parameter 'MRespBLU_N'
   description   'maintenance respiration rate at 0 dg C BLUEGRN_N'
   unit          '(1/d)'
   value          0.1200E-01
end-parameter
parameter 'MRespBLU_P'
   description   'maintenance respiration rate at 0 dg C BLUEGRN_P'
   unit          '(1/d)'
   value          0.1200E-01
end-parameter
parameter 'MRespULS_E'
   description   'maintenance respiration rate at 0 dg C ULVAS_E'
   unit          '(1/d)'
   value          0.1000E-01
end-parameter
parameter 'MRespULS_N'
   description   'maintenance respiration rate at 0 dg C ULVAS_N'
   unit          '(1/d)'
   value          0.1000E-01
end-parameter
parameter 'MRespULS_P'
   description   'maintenance respiration rate at 0 dg C ULVAS_P'
   unit          '(1/d)'
   value          0.1000E-01
end-parameter
parameter 'MRespULF_E'
   description   'maintenance respiration rate at 0 dg C ULVAF_E'
   unit          '(1/d)'
   value          0.1000E-01
end-parameter
parameter 'MRespULF_N'
   description   'maintenance respiration rate at 0 dg C ULVAF_N'
   unit          '(1/d)'
   value          0.1000E-01
end-parameter
parameter 'MRespULF_P'
   description   'maintenance respiration rate at 0 dg C ULVAF_P'
   unit          '(1/d)'
   value          0.1000E-01
end-parameter
parameter 'TcRspFDI_E'
   description   'temperature coefficient for respiration FDIATOMS_E'
   unit          '(-)'
   value          0.1072E+01
end-parameter
parameter 'TcRspFDI_P'
   description   'temperature coefficient for respiration FDIATOMS_P'
   unit          '(-)'
   value          0.1072E+01
end-parameter
parameter 'TcRspGRE_E'
   description   'temperature coefficient for respiration GREENS_E'
   unit          '(-)'
   value          0.1072E+01
end-parameter
parameter 'TcRspGRE_N'
   description   'temperature coefficient for respiration GREENS_N'
   unit          '(-)'
   value          0.1072E+01
end-parameter
parameter 'TcRspGRE_P'
   description   'temperature coefficient for respiration GREENS_P'
   unit          '(-)'
   value          0.1072E+01
end-parameter
parameter 'TcRspBLU_E'
   description   'temperature coefficient for respiration BLUEGRN_E'
   unit          '(-)'
   value          0.1072E+01
end-parameter
parameter 'TcRspBLU_N'
   description   'temperature coefficient for respiration BLUEGRN_N'
   unit          '(-)'
   value          0.1072E+01
end-parameter
parameter 'TcRspBLU_P'
   description   'temperature coefficient for respiration BLUEGRN_P'
   unit          '(-)'
   value          0.1072E+01
end-parameter
parameter 'TcRspULS_E'
   description   'temperature coefficient for respiration ULVAS_E'
   unit          '(-)'
   value          0.1066E+01
end-parameter
parameter 'TcRspULS_N'
   description   'temperature coefficient for respiration ULVAS_N'
   unit          '(-)'
   value          0.1066E+01
end-parameter
parameter 'TcRspULS_P'
   description   'temperature coefficient for respiration ULVAS_P'
   unit          '(-)'
   value          0.1066E+01
end-parameter
parameter 'TcRspULF_E'
   description   'temperature coefficient for respiration ULVAF_E'
   unit          '(-)'
   value          0.1066E+01
end-parameter
parameter 'TcRspULF_N'
   description   'temperature coefficient for respiration ULVAF_N'
   unit          '(-)'
   value          0.1066E+01
end-parameter
parameter 'TcRspULF_P'
   description   'temperature coefficient for respiration ULVAF_P'
   unit          '(-)'
   value          0.1066E+01
end-parameter
parameter 'SDMixFDI_E'
   description   'distribution water column: fraction of depth FDIATOMS_E'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixFDI_P'
   description   'distribution water column: fraction of depth FDIATOMS_P'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixGRE_E'
   description   'distribution water column: fraction of depth GREENS_E'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixGRE_N'
   description   'distribution water column: fraction of depth GREENS_N'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixGRE_P'
   description   'distribution water column: fraction of depth GREENS_P'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixBLU_E'
   description   'distribution water column: fraction of depth BLUEGRN_E'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixBLU_N'
   description   'distribution water column: fraction of depth BLUEGRN_N'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixBLU_P'
   description   'distribution water column: fraction of depth BLUEGRN_P'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixULS_E'
   description   'distribution water column: fraction of depth ULVAS_E'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixULS_N'
   description   'distribution water column: fraction of depth ULVAS_N'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixULS_P'
   description   'distribution water column: fraction of depth ULVAS_P'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SDMixULF_E'
   description   'distribution water column: fraction of depth ULVAF_E'
   unit          '(-)'
   value         -0.2500E+00
end-parameter
parameter 'SDMixULF_N'
   description   'distribution water column: fraction of depth ULVAF_N'
   unit          '(-)'
   value         -0.2500E+00
end-parameter
parameter 'SDMixULF_P'
   description   'distribution water column: fraction of depth ULVAF_P'
   unit          '(-)'
   value         -0.2500E+00
end-parameter
parameter 'FixFDI_E'
   description   'benthic:<0, resuspended:>0, plankton:=0 FDIATOMS_E'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'FixFDI_P'
   description   'benthic:<0, resuspended:>0, plankton:=0 FDIATOMS_P'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'FixGRE_E'
   description   'benthic:<0, resuspended:>0, plankton:=0 GREENS_E'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'FixGRE_N'
   description   'benthic:<0, resuspended:>0, plankton:=0 GREENS_N'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'FixGRE_P'
   description   'benthic:<0, resuspended:>0, plankton:=0 GREENS_P'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'FixBLU_E'
   description   'benthic:<0, resuspended:>0, plankton:=0 BLUEGRN_E'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'FixBLU_N'
   description   'benthic:<0, resuspended:>0, plankton:=0 BLUEGRN_N'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'FixBLU_P'
   description   'benthic:<0, resuspended:>0, plankton:=0 BLUEGRN_P'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'FixULS_E'
   description   'benthic:<0, resuspended:>0, plankton:=0 ULVAS_E'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'FixULS_N'
   description   'benthic:<0, resuspended:>0, plankton:=0 ULVAS_N'
   unit          '(-)'
   value          0.2000E+01
end-parameter
parameter 'FixULS_P'
   description   'benthic:<0, resuspended:>0, plankton:=0 ULVAS_P'
   unit          '(-)'
   value          0.3000E+01
end-parameter
parameter 'FixULF_E'
   description   'benthic:<0, resuspended:>0, plankton:=0 ULVAF_E'
   unit          '(-)'
   value         -0.1000E+01
end-parameter
parameter 'FixULF_N'
   description   'benthic:<0, resuspended:>0, plankton:=0 ULVAF_N'
   unit          '(-)'
   value         -0.2000E+01
end-parameter
parameter 'FixULF_P'
   description   'benthic:<0, resuspended:>0, plankton:=0 ULVAF_P'
   unit          '(-)'
   value         -0.3000E+01
end-parameter
parameter 'OXY'
   description   'Dissolved Oxygen'
   unit          '(g/m3)'
   value          0.1000E+02
end-parameter
parameter 'RcNit20'
   description   'MM- nitrification rate at 20 oC'
   unit          '(gN/m3/d)'
   value          0.1000E+00
end-parameter
parameter 'TcNit'
   description   'temperature coefficient for nitrification'
   unit          '(-)'
   value          0.1070E+01
end-parameter
parameter 'ku_dFdcC20'
   description   'upper limit mineralization rate fast detr-C'
   unit          '(1/d)'
   value          0.1800E+00
end-parameter
parameter 'kl_dFdcC20'
   description   'lower limit mineralization rate fast detr-C'
   unit          '(1/d)'
   value          0.1200E+00
end-parameter
parameter 'ku_dFdcN20'
   description   'upper limit mineralization rate fast detr-N'
   unit          '(1/d)'
   value          0.1800E+00
end-parameter
parameter 'kl_dFdcN20'
   description   'lower limit mineralization rate fast detr-N'
   unit          '(1/d)'
   value          0.1200E+00
end-parameter
parameter 'ku_dFdcP20'
   description   'upper limit mineralization rate fast detr-P'
   unit          '(1/d)'
   value          0.1800E+00
end-parameter
parameter 'kl_dFdcP20'
   description   'lower limit mineralization rate fast detr-P'
   unit          '(1/d)'
   value          0.1200E+00
end-parameter
parameter 'kT_dec'
   description   'temperature coefficient for decomposition'
   unit          '(-)'
   value          0.1047E+01
end-parameter
parameter 'b_poc1poc2'
   description   'fraction POC1 converted to POC2'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'b_poc1doc'
   description   'fraction POC1 converted to DOC'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'SWOMDec'
   description   'option: 0.0 for stripping, 1.0 for different rates'
   unit          '{no unit}'
   value          0.0000E+00
end-parameter
parameter 'SWOxCon'
   description   'Switch: only OxCon (1) or not (0)'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'RCdisSi20'
   description   '2nd order dissolution rate SiO2 at 20 oC'
   unit          '(m3/gSi/d)'
   value          0.1000E-03
end-parameter
parameter 'TCdisSi'
   description   'temperature dependency dissolution Si'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'Tau'
   description   'total bottom shear stress'
   unit          '(N/m2)'
   value         -0.9990E+03
end-parameter
parameter 'TaucS'
   description   'critical shear stress for sedimentation algae'
   unit          '(N/m2)'
   value          0.1000E+00
end-parameter
parameter 'MinDepth'
   description   'minimum waterdepth for sedimentation'
   unit          '(m)'
   value          0.1000E+00
end-parameter
parameter 'TauCrUlva'
   description   'critical shear stress for resuspension ULVA'
   unit          '(N/m2)'
   value          0.2000E+00
end-parameter
parameter 'FixGrad'
   description   'gradient of fixation versus shear stress'
   unit          '(-)'
   value          0.2000E+01
end-parameter
parameter 'Salinity'
   description   'Salinity'
   unit          '(g/kg)'
   value          0.3500E+02
end-parameter
parameter 'ExtVlPOC1'
   description   'VL specific extinction coefficient POC1'
   unit          '(m2/gC)'
   value          0.1000E+00
end-parameter
parameter 'ExtVlBak'
   description   'background extinction visible light'
   unit          '(1/m)'
   value          0.8000E-01
end-parameter
parameter 'RadSurf'
   description   'irradiation at the water surface'
   unit          '(W/m2)'
   value         -0.9990E+03
end-parameter
parameter 'a_enh'
   description   'enhancement factor in radiation calculation'
   unit          '(-)'
   value          0.1500E+01
end-parameter
parameter 'SWDepAve'
   description   'switch for module DepAve (0=off, 1=on)'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'Latitude'
   description   'latitude of study area'
   unit          '(degrees)'
   value          0.5210E+02
end-parameter
parameter 'RefDay'
   description   'daynumber of reference day simulation'
   unit          '(d)'
   value          0.0000E+00
end-parameter
parameter 'V0SedFDI_E'
   description   'sedimentation velocity algal type FDIATOMS_E'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'V0SedFDI_P'
   description   'sedimentation velocity algal type FDIATOMS_P'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'V0SedGRE_E'
   description   'sedimentation velocity algal type GREENS_E'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'V0SedGRE_N'
   description   'sedimentation velocity algal type GREENS_N'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'V0SedGRE_P'
   description   'sedimentation velocity algal type GREENS_P'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'V0SedBLU_E'
   description   'sedimentation velocity algal type BLUEGRN_E'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'V0SedBLU_N'
   description   'sedimentation velocity algal type BLUEGRN_N'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'V0SedBLU_P'
   description   'sedimentation velocity algal type BLUEGRN_P'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'V0SedULS_E'
   description   'sedimentation velocity algal type ULVAS_E'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'V0SedULS_N'
   description   'sedimentation velocity algal type ULVAS_N'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'V0SedULS_P'
   description   'sedimentation velocity algal type ULVAS_P'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'V0SedULF_E'
   description   'sedimentation velocity algal type ULVAF_E'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'V0SedULF_N'
   description   'sedimentation velocity algal type ULVAF_N'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'V0SedULF_P'
   description   'sedimentation velocity algal type ULVAF_P'
   unit          '(m/d)'
   value          0.0000E+00
end-parameter
parameter 'CrSS'
   description   'crit. susp. solid concentration for flocculation'
   unit          '(gDM/m3)'
   value          0.1000E+03
end-parameter
parameter 'nFDI_E'
   description   'coefficient in flocculation function FDIATOMS_E'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'nFDI_P'
   description   'coefficient in flocculation function FDIATOMS_P'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'nGRE_E'
   description   'coefficient in flocculation function GREENS_E'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'nGRE_N'
   description   'coefficient in flocculation function GREENS_N'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'nGRE_P'
   description   'coefficient in flocculation function GREENS_P'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'nBLU_E'
   description   'coefficient in flocculation function BLUEGRN_E'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'nBLU_N'
   description   'coefficient in flocculation function BLUEGRN_N'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'nBLU_P'
   description   'coefficient in flocculation function BLUEGRN_P'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'nULS_E'
   description   'coefficient in flocculation function ULVAS_E'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'nULS_N'
   description   'coefficient in flocculation function ULVAS_N'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'nULS_P'
   description   'coefficient in flocculation function ULVAS_P'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'nULF_E'
   description   'coefficient in flocculation function ULVAF_E'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'nULF_N'
   description   'coefficient in flocculation function ULVAF_N'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'nULF_P'
   description   'coefficient in flocculation function ULVAF_P'
   unit          '(-)'
   value          0.0000E+00
end-parameter
parameter 'TcSED'
   description   'temperature coefficient for sedimentation'
   unit          '(-)'
   value          0.1000E+01
end-parameter
parameter 'SMax'
   description   'salinity at which salinity function is maximal'
   unit          '(g/kg)'
   value          0.5000E+01
end-parameter
parameter 'EnhSdAlg'
   description   'salinity enhanced settling factor for algae'
   unit          '(-)'
   value          0.1000E+01
end-parameter
output 'ExtVl'
   description   'total extinction coefficient visible light'
end-output
output 'ExtVlPhyt'
   description   'VL extinction by phytoplankton'
end-output
output 'Depth'
   description   'depth of segment'
end-output
output 'BloomDepth'
   description   'average depth over Bloom time step'
end-output
output 'DayL'
   description   'daylength <0-1>'
end-output
output 'Limit Chlo'
   description   'total chlorophyll in algae'
end-output
output 'Limit nit'
   description   'limiting factor nitrogen'
end-output
output 'Limit pho'
   description   'limiting factor phosphorus'
end-output
output 'Limit sil'
   description   'limiting factor silicate'
end-output
output 'Limit e'
   description   'limiting factor energy'
end-output
output 'Limit gro'
   description   'limiting factor growth'
end-output
output 'Phyt'
   description   'total carbon in phytoplankton'
end-output
output 'AlgN'
   description   'total nitrogen in algae'
end-output
output 'AlgP'
   description   'total phosphorus in algae'
end-output
output 'AlgSi'
   description   'total silica in algae'
end-output
output 'AlgDM'
   description   'total DM in algae'
end-output
output 'TOC'
   description   'total organic C (including algae)'
end-output
output 'TotN'
   description   'total nitrogen (including algae)'
end-output
output 'KjelN'
   description   'Kjeldahl nitrogen'
end-output
output 'DIN'
   description   'dissolved inorganic nitrogen'
end-output
output 'TON'
   description   'total organic N (including algae)'
end-output
output 'PON'
   description   'Particulate Organic Nitrogen (including algae)'
end-output
output 'TotP'
   description   'total phosphorus (including algae)'
end-output
output 'TOP'
   description   'total organic P (including algae)'
end-output
output 'POP'
   description   'particulate organic P (incl algae)'
end-output
output 'TotSi'
   description   'total silica (including algae)'
end-output
output 'Chlfa'
   description   'Chlorophyll-a concentration'
end-output
output 'BLOOMGRP'
   description   'algae group concentration'
end-output
output 'VsedFDI_E'
   description   'sedimentation velocity algae FDIATOMS_E'
end-output
output 'VsedFDI_P'
   description   'sedimentation velocity algae FDIATOMS_P'
end-output
output 'VsedGRE_E'
   description   'sedimentation velocity algae GREENS_E'
end-output
output 'VsedGRE_N'
   description   'sedimentation velocity algae GREENS_N'
end-output
output 'VsedGRE_P'
   description   'sedimentation velocity algae GREENS_P'
end-output
output 'VsedBLU_E'
   description   'sedimentation velocity algae BLUEGRN_E'
end-output
output 'VsedBLU_N'
   description   'sedimentation velocity algae BLUEGRN_N'
end-output
output 'VsedBLU_P'
   description   'sedimentation velocity algae BLUEGRN_P'
end-output
output 'VsedULS_E'
   description   'sedimentation velocity algae ULVAS_E'
end-output
output 'VsedULS_N'
   description   'sedimentation velocity algae ULVAS_N'
end-output
output 'VsedULS_P'
   description   'sedimentation velocity algae ULVAS_P'
end-output
output 'VsedULF_E'
   description   'sedimentation velocity algae ULVAF_E'
end-output
output 'VsedULF_N'
   description   'sedimentation velocity algae ULVAF_N'
end-output
output 'VsedULF_P'
   description   'sedimentation velocity algae ULVAF_P'
end-output
output 'PSedFDI_E'
   description   'sedimentation probability <0-1> algae FDIATOMS_E'
end-output
output 'PSedFDI_P'
   description   'sedimentation probability <0-1> algae FDIATOMS_P'
end-output
output 'PSedGRE_E'
   description   'sedimentation probability <0-1> algae GREENS_E'
end-output
output 'PSedGRE_N'
   description   'sedimentation probability <0-1> algae GREENS_N'
end-output
output 'PSedGRE_P'
   description   'sedimentation probability <0-1> algae GREENS_P'
end-output
output 'PSedBLU_E'
   description   'sedimentation probability <0-1> algae BLUEGRN_E'
end-output
output 'PSedBLU_N'
   description   'sedimentation probability <0-1> algae BLUEGRN_N'
end-output
output 'PSedBLU_P'
   description   'sedimentation probability <0-1> algae BLUEGRN_P'
end-output
output 'PSedULS_E'
   description   'sedimentation probability <0-1> algae ULVAS_E'
end-output
output 'PSedULS_N'
   description   'sedimentation probability <0-1> algae ULVAS_N'
end-output
output 'PSedULS_P'
   description   'sedimentation probability <0-1> algae ULVAS_P'
end-output
output 'PSedULF_E'
   description   'sedimentation probability <0-1> algae ULVAF_E'
end-output
output 'PSedULF_N'
   description   'sedimentation probability <0-1> algae ULVAF_N'
end-output
output 'PSedULF_P'
   description   'sedimentation probability <0-1> algae ULVAF_P'
end-output
output 'fSedFDI_E'
   description   'sedimentation flux algae FDIATOMS_E'
end-output
output 'fSedFDI_P'
   description   'sedimentation flux algae FDIATOMS_P'
end-output
output 'fSedGRE_E'
   description   'sedimentation flux algae GREENS_E'
end-output
output 'fSedGRE_N'
   description   'sedimentation flux algae GREENS_N'
end-output
output 'fSedGRE_P'
   description   'sedimentation flux algae GREENS_P'
end-output
output 'fSedBLU_E'
   description   'sedimentation flux algae BLUEGRN_E'
end-output
output 'fSedBLU_N'
   description   'sedimentation flux algae BLUEGRN_N'
end-output
output 'fSedBLU_P'
   description   'sedimentation flux algae BLUEGRN_P'
end-output
output 'fSedULS_E'
   description   'sedimentation flux algae ULVAS_E'
end-output
output 'fSedULS_N'
   description   'sedimentation flux algae ULVAS_N'
end-output
output 'fSedULS_P'
   description   'sedimentation flux algae ULVAS_P'
end-output
output 'fSedULF_E'
   description   'sedimentation flux algae ULVAF_E'
end-output
output 'fSedULF_N'
   description   'sedimentation flux algae ULVAF_N'
end-output
output 'fSedULF_P'
   description   'sedimentation flux algae ULVAF_P'
end-output
output 'VxSedAlg'
   description   'sedimentation velocity'
end-output
output 'frFixedAlg'
   description   'fraction of algae fixed'
end-output
output 'M2_FDI_E'
   description   'concentration of algae square metre FDIATOMS_E'
end-output
output 'M2_FDI_P'
   description   'concentration of algae square metre FDIATOMS_P'
end-output
output 'M2_GRE_E'
   description   'concentration of algae square metre GREENS_E'
end-output
output 'M2_GRE_N'
   description   'concentration of algae square metre GREENS_N'
end-output
output 'M2_GRE_P'
   description   'concentration of algae square metre GREENS_P'
end-output
output 'M2_BLU_E'
   description   'concentration of algae square metre BLUEGRN_E'
end-output
output 'M2_BLU_N'
   description   'concentration of algae square metre BLUEGRN_N'
end-output
output 'M2_BLU_P'
   description   'concentration of algae square metre BLUEGRN_P'
end-output
output 'M2_ULS_E'
   description   'concentration of algae square metre ULVAS_E'
end-output
output 'M2_ULS_N'
   description   'concentration of algae square metre ULVAS_N'
end-output
output 'M2_ULS_P'
   description   'concentration of algae square metre ULVAS_P'
end-output
output 'M2_ULF_E'
   description   'concentration of algae square metre ULVAF_E'
end-output
output 'M2_ULF_N'
   description   'concentration of algae square metre ULVAF_N'
end-output
output 'M2_ULF_P'
   description   'concentration of algae square metre ULVAF_P'
end-output
output 'ExtVlBak'
   description   'background extinction visible light'
end-output
output 'ExtVlISS'
   description   'VL extinction by inorganic suspended matter'
end-output
output 'ExtVlOSS'
   description   'VL extinction by POC'
end-output
output 'RadSurf'
   description   'irradiation at the water surface'
end-output
output 'BlmDep_out'
   description   'average depth over Bloom time step OUTPUT'
end-output
output 'SalFnFDI_E'
   description   'salinity function on sedimentation algae type FDIATOMS_E'
end-output
output 'SalFnFDI_P'
   description   'salinity function on sedimentation algae type FDIATOMS_P'
end-output
output 'SalFnGRE_E'
   description   'salinity function on sedimentation algae type GREENS_E'
end-output
output 'SalFnGRE_N'
   description   'salinity function on sedimentation algae type GREENS_N'
end-output
output 'SalFnGRE_P'
   description   'salinity function on sedimentation algae type GREENS_P'
end-output
output 'SalFnBLU_E'
   description   'salinity function on sedimentation algae type BLUEGRN_E'
end-output
output 'SalFnBLU_N'
   description   'salinity function on sedimentation algae type BLUEGRN_N'
end-output
output 'SalFnBLU_P'
   description   'salinity function on sedimentation algae type BLUEGRN_P'
end-output
output 'SalFnULS_E'
   description   'salinity function on sedimentation algae type ULVAS_E'
end-output
output 'SalFnULS_N'
   description   'salinity function on sedimentation algae type ULVAS_N'
end-output
output 'SalFnULS_P'
   description   'salinity function on sedimentation algae type ULVAS_P'
end-output
output 'SalFnULF_E'
   description   'salinity function on sedimentation algae type ULVAF_E'
end-output
output 'SalFnULF_N'
   description   'salinity function on sedimentation algae type ULVAF_N'
end-output
output 'SalFnULF_P'
   description   'salinity function on sedimentation algae type ULVAF_P'
end-output
output 'FloFnFDI_E'
   description   'flocculation function on sedimentation algae FDIATOMS_E'
end-output
output 'FloFnFDI_P'
   description   'flocculation function on sedimentation algae FDIATOMS_P'
end-output
output 'FloFnGRE_E'
   description   'flocculation function on sedimentation algae GREENS_E'
end-output
output 'FloFnGRE_N'
   description   'flocculation function on sedimentation algae GREENS_N'
end-output
output 'FloFnGRE_P'
   description   'flocculation function on sedimentation algae GREENS_P'
end-output
output 'FloFnBLU_E'
   description   'flocculation function on sedimentation algae BLUEGRN_E'
end-output
output 'FloFnBLU_N'
   description   'flocculation function on sedimentation algae BLUEGRN_N'
end-output
output 'FloFnBLU_P'
   description   'flocculation function on sedimentation algae BLUEGRN_P'
end-output
output 'FloFnULS_E'
   description   'flocculation function on sedimentation algae ULVAS_E'
end-output
output 'FloFnULS_N'
   description   'flocculation function on sedimentation algae ULVAS_N'
end-output
output 'FloFnULS_P'
   description   'flocculation function on sedimentation algae ULVAS_P'
end-output
output 'FloFnULF_E'
   description   'flocculation function on sedimentation algae ULVAF_E'
end-output
output 'FloFnULF_N'
   description   'flocculation function on sedimentation algae ULVAF_N'
end-output
output 'FloFnULF_P'
   description   'flocculation function on sedimentation algae ULVAF_P'
end-output
output 'BLUEGRN'
   description   'Blue Greens'
end-output
output 'FDIATOMS'
   description   'Freshwater Diatoms'
end-output
output 'GREENS'
   description   'Green algae'
end-output
output 'UlvaS'
   description   'Ulva suspended'
end-output
output 'UlvaF'
   description   'Ulva rooted'
end-output
active-processes
   name  'BLOOM_P' 'BLOOM II algae module'
   name  'Compos' 'Composition'
   name  'Nitrif_NH4' 'Nitrification of ammonium'
   name  'DecFast' 'Mineralization fast decomp. detritus POC1'
   name  'CONSELAC' 'Consumption oxygen/other electron acceptors'
   name  'DisSi' 'Dissolution of Si in opal (SWITCH defaults)'
   name  'Phy_Blo_P' 'Computation of phytoplankton output - Bloom'
   name  'SEDALG' 'Sedimentation of algae species'
   name  'UlvaFix_P' 'Fixation of BLOOM algae at the bottom'
   name  'Salinchlor' 'Conversion of salinity into chloride or vv'
   name  'Extinc_VLG' 'Extinction of visible-light (370-680nm) DLWQ-G'
   name  'EXTINABVLP' 'Extinction of light by algae (Bloom)'
   name  'CalcRad' 'Radiation at segment upper and lower boundaries'
   name  'DynDepth' 'dynamic calculation of the depth'
   name  'DepAve' 'Average depth for Bloom step'
   name  'Daylength' 'Daylength calculation'
   name  'CalVSALG' 'Sedimentation velocity algae = f (Temp SS Sal)'
end-active-processes
